### ISSUE TITLE
Wrap .card-actions on .card

### ISSUE THREAD

**Issue by GreenDjango** [saadeghi/daisyui#10]
Hi, I work with daisy (great project btw) and I noticed better badge wrap with this:
```css
.card-actions {
   flex-wrap: wrap;
}
```
and for the `card with badge` example:
```html
<div class="mb-2 space-x-2 card-actions">
    <div class="badge badge-ghost mb-2">Colors</div>
    <div class="badge badge-ghost mb-2">UI Design</div>
    <div class="badge badge-ghost mb-2">Creativity</div>
</div>
```
Thank you for your time!

<img height="400px" src="https://user-images.githubusercontent.com/52924057/110044302-2f06ee00-7d49-11eb-8962-7f04673b4c5d.png"  alt="Screenshot_20210305_002227" /><img height="400px" src="https://user-images.githubusercontent.com/52924057/110044304-2f9f8480-7d49-11eb-8553-a0e332694c88.png" alt="Screenshot_20210305_002421" />

**Comment by saadeghi** [comment]
Of course. I'll fix this tomorrow 👍

**Comment by saadeghi** [comment]
Please update to latest version `0.14.0`  
I also, added margin for `card-actions` items so `space-x-2` is no longer needed.

**Comment by GreenDjango** [comment]
Thanks !
