### ISSUE TITLE
Question about CSS nesting.

### ISSUE THREAD

**Issue by WickedInvi** [saadeghi/daisyui#1000]
This is just a question and I am sorry if it's dumb but I am a newbie and would like to learn and help on the project.
I am getting issues with the nested CSS and I've looked for a few hours for solutions.
If I change the extension from CSS to SCSS it goes away.
Is there an extension I need to install?
Thank you for your time (:

![image](https://user-images.githubusercontent.com/49752323/182918437-e91069f5-8f69-4c85-9bd9-d21f2237be5b.png)
![image](https://user-images.githubusercontent.com/49752323/182918508-8e59f6c8-befe-467e-8f72-ca7f6a35009b.png)

**Comment by saadeghi** [comment]
I assume you're trying to run daisyUI package on local. If that's the case, CSS nesting should be handled by `postcss-nested` and it is a dev-dependency.

If you follow contribution guide, everything should work as expected:  
https://github.com/saadeghi/daisyui/blob/master/.github/CONTRIBUTING.md

Let me know if you have any questions

**Comment by WickedInvi** [comment]
Thank you when I tried to follow the contributing guide I ran into a problem when running

`npm run build` 

Here are some of the last lines before it fails
```
� daisyUI components 2.22.0  https://github.com/saadeghi/daisyui
  ✔︎ Including:  components, themes[29], utilities

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> daisyui@2.22.0 full
> postcss src/full/index.css -o dist/full.css --config src/full


> daisyui@2.22.0 postfull
> parcel-css --minify --targets '> 7%' dist/full.css -o dist/full.css

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Nom("")', src/main.rs:90:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by saadeghi** [comment]
I think the issue is from `parcel-css` dependency version `1.5.??`. I had this issue [here](https://github.com/saadeghi/daisyui/runs/7429245797?check_suite_focus=true).  
might be a temporary bug from `parcel-css` and I'm sure it will be fixed on the next updates.  

For now [fixing the dependency version](https://github.com/saadeghi/daisyui/commit/d07b971997c35e4e11c73b785ef26ce87e20dbcc) fixed the issue for me so if you use the latest daisyUI version, it should be fixed for you too.

**Comment by WickedInvi** [comment]
I've removed it and installed the latest `1.12.2` now the error is

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: SelectorError(EmptySelector), loc: Some(ErrorLocation { filename: "\\\\?\\D:\\dev\\projects\\opensource\\daisyui\\dist\\full.css", line: 41869, column: 6 }) }', src/main.rs:123:43 
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

There is the missing selector. There seems to be 8 of them when I searched for "   {"


![image](https://user-images.githubusercontent.com/49752323/183258773-dff19440-ee6a-4e3d-9264-4128efbdab40.png)

**Comment by saadeghi** [comment]
You don't need to change dependency versions manually.  
Just use the latest version of daisyUI which is using `"@parcel/css-cli": "1.5.0"` I haven't checked the latest changes on this dependency. there might be bugs on latest version. but version `1.5.0` works fine and [builds](https://github.com/saadeghi/daisyui/actions) are successful.

**Comment by WickedInvi** [comment]
I've installed WSL2 and ran the build thru ubuntu and works fine.
