### ISSUE TITLE
bug/clarification: Changing border-radius on table

### ISSUE THREAD

**Issue by tcc-sejohnson** [saadeghi/daisyui#1001]
Currently, the CSS selector being used to set the border-radius on the table visual is _hilariously_ specific, meaning it's almost impossible to override as far as I can tell. The only solution I've found so far is this:

```
<th
	class="{position === 'first' ? '!rounded-tl-md' : ''} {position === 'last'
		? '!rounded-tr-md'
		: ''}"
>
```

And then roughly the same thing with the table elements to change the bottom corners' radius. There's got to be an easier way that I'm just missing like a dunce, right?

**Comment by tcc-sejohnson** [comment]
@saadeghi Just wanted to check in -- if there's no easy way to achieve this behavior right now, I'm happy to discuss how we might be able to implement something and create a PR.

**Comment by saadeghi** [comment]
Hey. There are ways to reduce specificity.  
This will be fixed very soon. Don't worry.
