### ISSUE TITLE
How to center a dropdown ?

### ISSUE THREAD

**Issue by SimonLeclere** [saadeghi/daisyui#1009]
Hey, so I have a dropdown and I'd like it to be centered with the button that opened it. How could I simulate the dropdown-center class?

**Comment by saadeghi** [comment]
This is possible by adding the following classes to `dropdown-content`:  
```
translate-x-[-50%] left-[50%]
```
Example: https://play.tailwindcss.com/BBO06KbFHK
```html
<div class="dropdown dropdown-open">
  <label tabindex="0" class="btn m-1">Click</label>
  <ul tabindex="0" class="dropdown-content translate-x-[-50%] left-[50%] menu p-2 shadow bg-base-100 rounded-box w-52">
    <li><a>Item 1</a></li>
    <li><a>Item 2</a></li>
  </ul>
</div>
```

**Comment by SimonLeclere** [comment]
Thanks a lot ! Maybe you should add this to the documentation
