### ISSUE TITLE
tab animation

### ISSUE THREAD

**Issue by danielehrhardt** [saadeghi/daisyui#1013]
https://stackoverflow.com/questions/66279676/make-animated-tabs-in-tailwind-css
https://daisyui.com/components/tab/

**Comment by saadeghi** [comment]
We can't use absolute positions and fixed widths for tabs on daisyUI because tabs can be in any size.  
So that "pure Tailwind" solution you mentioned won't be useful unless we adjust the number of tabs and the width of tabs.
