### ISSUE TITLE
how to build input number component?

### ISSUE THREAD

**Issue by workingxx92** [saadeghi/daisyui#102]
Hi.
how to build an input number compoment?
<img width="149" alt="Screen Shot 2021-07-03 at 8 49 52 PM" src="https://user-images.githubusercontent.com/86577210/124356469-4fd04900-dc40-11eb-8796-3f601fd172b8.png">

**Comment by saadeghi** [comment]
`<input type="number">` has native -/+ buttons but if you want to show custom buttons, you need to use JS to increase/decrease the number.  
https://play.tailwindcss.com/mK1nUw0bsa
