### ISSUE TITLE
How to update the theme border color?

### ISSUE THREAD

**Issue by williamlmao** [saadeghi/daisyui#1022]
I am trying to set a default border color in my theme. I have already reviewed these docs: https://daisyui.com/docs/colors/ and they don't mention anything about updating the border colors. 

I have also tested updating all of the color names and the border color doesn't seem to be mapped to those.

Would be a huge help if anyone knows. Thanks!

**Comment by saadeghi** [comment]
Can you tell me what are the elements that you want border color for?  
You can set custom border colors for each element using daisyUI [`border-[COLORNAME]`](https://tailwindcss.com/docs/border-color) utility classes ([daisyUI color names](https://daisyui.com/docs/colors/) like `primary`, etc. are also supported)

**Comment by williamlmao** [comment]
@saadeghi I am using tailwind and am putting `border-2` on multiple divs. I know I could specify the border colors when writing the classnames for those elements, but I would much prefer to be able to update the border color globally within the theme.

**Comment by saadeghi** [comment]
you can use something like `border-2 border-primary` for your elements and they will have `primary` border color, and it will be the color from theme.

You can use any other daisyUI color names and they are all themeable.  

We can't possibly set border-color to all elements because the result wouldn't be good. Not all elements need borders or border colors.

Let me know if you have any questions

**Comment by thiagomajesk** [comment]
I'm also having this problem with DaisyUI and there's not a good solution from the framework side. An excellent way to visualize this is setting your `base-100` config to a dark color like `#111827` and adding `border border-2` to an element. 

@saadeghi it's not about setting border color to all elements. It's about defining the default color for the `border` utility. I guess there's a tailwindcss variable that does that, but I can't manage to find it right now.

> We can't possibly set border-color to all elements because the result wouldn't be good. Not all elements need borders or border colors.

BTW: Bootstrap has a solution for that. You have specific variables for component groups and a general variable that can set it all (they have more components with borders though).

**Comment by LouisLecouturier** [comment]
Any updates ?
