### ISSUE TITLE
Spacing problem in loading button.rtl (config) is true.

### ISSUE THREAD

**Issue by mehrang13** [saadeghi/daisyui#1030]
![loadingbutton](https://user-images.githubusercontent.com/36799592/184701383-82cdf7fb-6a11-495c-bc3a-a41ff809dac0.png)

**Comment by WickedInvi** [comment]
Could you provide the code you are using? Including the parent of the button to see what might be causing this.

**Comment by saadeghi** [comment]
I think you don't have `dir="rtl"` on your `<body>` tag.  
As [mentioned here](https://daisyui.com/docs/config/#rtl) you need this config on `tailwind.config.js`
```js
daisyui: {
  rtl: true,
},
```
And you need `dir="rtl"` on your `<body>` tag.

Example: https://play.tailwindcss.com/OZVQ2UgH7W
