### ISSUE TITLE
Recommendation for multi-select

### ISSUE THREAD

**Issue by znat** [saadeghi/daisyui#1036]
Hi, thanks a lot for this amazing UI kit!
I was wondering if you had any recommendation to implement an elegant multi-select with tags.
Something in that spirit but with the Daisy feel:
<img width="587" alt="image" src="https://user-images.githubusercontent.com/3694634/185383243-11c92af0-8653-46ea-bd22-f8dd3483804f.png">

Thanks

**Comment by saadeghi** [comment]
Unfortunately, that's not possible without JavaScript.  
So you need to use a JS plugin for that.

Let me know if you have any questions.
