### ISSUE TITLE
Changes to a jpg file

### ISSUE THREAD

**Issue by WickedInvi** [saadeghi/daisyui#1037]
I keep getting a change to bottom-navigation.jpg I am not sure what the difference is or why it is happening. I keep discarding but it just comes back. I understand this is not a DaisyUI issue per se but I was hoping for some advice.
![image](https://user-images.githubusercontent.com/49752323/185389057-c24607c3-0985-48f9-a6ae-75b76e3f96ef.png)

**Comment by saadeghi** [comment]
That's weird.  
Are you using anything that may automatically apply changes to an image? Any scripts, software, git hooks, etc?

**Comment by WickedInvi** [comment]
Someone on discord said `it's likely a rights issue, the account vscode is running under might not be allowed to delete that file`
I did switch to using WSL2 Ubuntu 20.04 recently so wondering if that has something to do with it. I will keep digging for know I keep deselecting when commiting.

**Comment by saadeghi** [comment]
Thank you.  
Let us know if you found a solution.  
However I should close this issue because it's not related to daisyUI.
