### ISSUE TITLE
alert component is influencing in width of box

### ISSUE THREAD

**Issue by helioh3** [saadeghi/daisyui#104]
When I place an alert under some input of the assembled component: Hero With Form, in the HERO section, it increases the width of the entire box.

**Comment by saadeghi** [comment]
@helioh3 can you please make an example on Tailwind Play or Codepen?

**Comment by helioh3** [comment]
thanks for answering! segue https://codepen.io/helioh3/pen/JjNYVvR quando add o Alert  on input, it change position with!

**Comment by saadeghi** [comment]
You need to add TailwindCSS file as well: https://codepen.io/saadeghi/pen/NWjGZwj

Class names like `hero`,`hero-content`, `card` etc... are component classes from [daisyUI](https://daisyui.com/)
but in your code, you also have classes like `w-full`, `max-w-sm`, `flex-1` etc... These are utility classes from [TailwindCSS](https://tailwindcss.com/).
So if you use both CSS files in your CodePen, you can use any component classes and any utility classes together:
```
https://cdn.jsdelivr.net/npm/tailwindcss@2.1/dist/tailwind.min.css
https://cdn.jsdelivr.net/npm/daisyui@1.6.1/dist/full.css
```
