### ISSUE TITLE
Modal does not set overflow

### ISSUE THREAD

**Issue by Loosie94** [saadeghi/daisyui#105]
Hi Guys,

Love the UI-kit. Just wondering; Is there a way to make the modal component also set the 'overflow' class on the body when opening? Now a user is able to scroll the whole page which is a bit weird. Thanks!

**Comment by saadeghi** [comment]
I'm afraid it's not possible without JS.  
You need some JS to add/remove `h-screen overflow-hidden` classes to `<body>` when checkbox is checked.  
Example: https://codepen.io/saadeghi/pen/Pomzvya?editors=1010
