### ISSUE TITLE
Outline Button does not have desired affect when active class is added

### ISSUE THREAD

**Issue by bmahnke** [saadeghi/daisyui#1050]
v2.18.1 ( & latest of 2.24.0)

Code:

`<button class="btn btn-outline btn-primary btn-active">Button</button>`

Result:

<img width="834" alt="Screen Shot 2022-08-23 at 3 12 23 PM" src="https://user-images.githubusercontent.com/3825922/186256599-28bded80-1e44-4dec-ae32-07d9fec8047f.png">

Expected:

<img width="837" alt="Screen Shot 2022-08-23 at 3 12 46 PM" src="https://user-images.githubusercontent.com/3825922/186256666-552e81cd-9fee-4198-ae4d-3bf1ea061692.png">

**Comment by danawoodman** [comment]
Just noticed this myself, makes the text illegible, breaking accessibility
