### ISSUE TITLE
iPhone mockup text not properly centered on mobile

### ISSUE THREAD

**Issue by hichemfantar** [saadeghi/daisyui#1063]
You can clearly see that the text is pushed slightly to the right.
Text is properly centered on larger viewports tho.

![Screenshot_20220827-095100.jpg](https://user-images.githubusercontent.com/34947993/187022996-c1a06217-a2af-4ea3-b4bd-b8ca415cf3a5.jpg)

**Comment by saadeghi** [comment]
well, we can't expect a phone to fit inside a phone 🤷‍♂️  
This is visually wrong but it's expected behavior. It's a mockup of a phone with fixed size.

**Comment by Yeom-JinHo** [comment]
@saadeghi

Hello
Since we’re in a mobile-first world now, I’d like to reopen this issue and propose a fix
Do you still hold the same view as before, or would you be open to me addressing it.

**Comment by Yeom-JinHo** [comment]
@saadeghi 
I’ve finished the changes.
I’ll open a PR — would you be able to review it?

**Comment by saadeghi** [comment]
@Yeom-JinHo PRs are welcome.  
Thank you

**Comment by Yeom-JinHo** [comment]
@saadeghi 

I’ve opened a PR for #4108 .
Please take a look when you have time.

Thank you.
