### ISSUE TITLE
Add Portuguese translations

### ISSUE THREAD

**Issue by nmferraz** [saadeghi/daisyui#1065]
Fully translated to Portuguese

So that people from all around world can use this beautiful plugin

**Comment by saadeghi** [comment]
I have to close this because it's not an issue.  
To help with translations, you can add or edit transition files here:  
https://github.com/saadeghi/daisyui/tree/master/src/docs/src/translation

Let me know if you have any questions.

**Comment by nmferraz** [comment]
OK thank you for the attention
