### ISSUE TITLE
Laggy Drawer Animation On Google Chrome

### ISSUE THREAD

**Issue by PeterUtekal** [saadeghi/daisyui#1067]
Hey Guys,

I've been struggling with a weird thing - the drawer animation is really laggy on my macbook pro, however, it only happens when using google chrome. When I open my web app in safari, everything is smooth. What do you think? Is the any way I could disable the animation completely?

**Comment by saadeghi** [comment]
This is not normal. Even a very old MacBook Air can handle that animation. It's not even a fancy CSS animation. It's a simple opacity and position transition.  
I think the problem must be from something else. Maybe something's wrong about Chrome settings or Chrome flags. Or maybe there's an extension that manipulates page content.

**Comment by saadeghi** [comment]
However, If you really want to disable the animations, you can add these 3 classnames to `drawer-toggle`
```
[&~.drawer-content]:transition-none [&~.drawer-side>.drawer-overlay]:transition-none [&~.drawer-side>.drawer-overlay+*]:transition-none
```
Example: https://play.tailwindcss.com/5xypi0TJl3
