### ISSUE TITLE
How to make a footer in drawer?

### ISSUE THREAD

**Issue by rosnaib11** [saadeghi/daisyui#1072]
```
<div className="drawer-side relative">
 <label htmlFor="my-drawer-2" className="drawer-overlay"></label>
  <ul>
    <li></li>
    ....
  </ul>
  <div>
    This div doesn't go to the bottom properly. If you try absolute, it will conflict with overlay.
  </div>
</div>
```

Adding `flex flex-col justify-end` in the drawer-side className and wrap the label and ul also conflicts

**Comment by leodip** [comment]
I have the same question... @bsor-dev  - how did you solve it?

Any chance you could give some info here, @saadeghi ?

When I try to add a <div>  after the <ul> it doesn't render well, it goes to the top, instead of rendering after the <ul>

**Comment by saadeghi** [comment]
Here's an example where footer is in content section:  
https://play.tailwindcss.com/oKamNfzThE

Here's an example where footer is inside the sidebar:
https://play.tailwindcss.com/AtS0Dh2lnC

The trick is having `flex flex-col` and adding `grow` to the section you want to fill the empty space and push the footer to stick to bottom

**Comment by leodip** [comment]
Amazing, thanks very much, @saadeghi
