### ISSUE TITLE
Is there a way to make modal-action sticky/fixed

### ISSUE THREAD

**Issue by anhsirk0** [saadeghi/daisyui#1081]

**Comment by anhsirk0** [comment]
I am currently using `sticky` . Its works fine. Will there be an official daisyui utility class for this.

**Comment by saadeghi** [comment]
Yes, `sticky` works.  
We can add a new class name for it but that won't be any more helpful when one Tailwind CSS does the job. daisyUI class names are often added when they apply more than one CSS rule. For a single CSS rule, Tailwind CSS class names are good enough and adding new class name for the same job would be duplication.

**Comment by anhsirk0** [comment]
Sorry for being unclear.
`sticky bottom-0` is what it needs to fix `modal-action`. few minor tweaks can also be made in order to make it look decent
Please take a look at this pen
https://play.tailwindcss.com/yM37rFyNU7

**Comment by saadeghi** [comment]
Yes. Any customization is possible.  
But after all, these are design decisions and we can't provide them all be default. In most designs, developers won't need a fixed button so I think it's better to just let people customize it only if needed.
