### ISSUE TITLE
include a github release or tag automatically on the build chore

### ISSUE THREAD

**Issue by gotjoshua** [saadeghi/daisyui#1082]
I got confused today that there are no github releases and the tags have fallen behind the npm releases

I see that there are chores running anyway
https://github.com/saadeghi/daisyui/commit/3127c8d87bd3cbd6152315fdc827f83f93d4125d

would it make sense to automate the tag and/or release cycle so that it all syncs up?

**Comment by saadeghi** [comment]
Yeah. I don't know why it stopped syncing. Something must be wrong with the CI/CD I guess 🤔

I will investigate this soon.

**Comment by saadeghi** [comment]
The problem was my Git client preferences for not pushing the tags. [All missing tags](https://github.com/saadeghi/daisyui/tags) are pushed now.
