### ISSUE TITLE
Documentation: Empty String passed to getElementById() in Modal Component

### ISSUE THREAD

**Issue by lymau** [saadeghi/daisyui#1089]
**Description**
When using [modal that closes when clicked outside ](https://daisyui.com/components/modal/#modal-that-closes-when-clicked-outside), it gave warning`Empty String passed to getElementById()`:  on browser console. The problem is in the documentation. It passed empty string on for attribute. Look at bold code below.
```html
<label class="modal-box relative" for="">
```

**To Reproduce**
Please change the documentation specifically the code above. Don't pass the empty string on for attribute. It should fix the warning.

That's all. Thank you.

**Comment by marcojanssen** [comment]
It actually prevents the modal to close if a click is done withing the modal itself. Doesn't seem to be the proper solution though. Any suggestions what it should be?
