### ISSUE TITLE
[hero] how to move content to left

### ISSUE THREAD

**Issue by workingxx92** [saadeghi/daisyui#109]
[hero] how to move content to left
<img width="1035" alt="Screen Shot 2021-07-14 at 7 16 36 PM" src="https://user-images.githubusercontent.com/86577210/125620629-fd0cd89c-f06a-4800-a11c-74ef81bbcbd2.png">

**Comment by ngnam** [comment]
@workingxx92  pls post snipet of you, or

you can use CSS - Positioning like `left:0` with `postition: absolute;`

**Comment by saadeghi** [comment]
@workingxx92 It's CSS grid, you can justify it by adding `justify-items-start` to `hero`.  
Example: https://play.tailwindcss.com/n2H77uIxac
