### ISSUE TITLE
Text input component not in view after click on mobile 

### ISSUE THREAD

**Issue by jasan-s** [saadeghi/daisyui#1091]
Visiting the daisy ui website and testing text area component https://daisyui.com/components/textarea/

Issue: after clicking in the text area on mobile the mobile keyboard opens and the text are is out of view completely .
The same issue seems to exist for text input component https://daisyui.com/components/input/

**Comment by saadeghi** [comment]
That's weird 🤔  

Can you provide more info?  
Like your phone model and browser?  
Also, a video would be helpful.

**Comment by saadeghi** [comment]
Feel free to re-open this issue after providing more info
