### ISSUE TITLE
Color names not working for Toggle component 

### ISSUE THREAD

**Issue by rambhosale** [saadeghi/daisyui#1092]
This snippet works as expected ```<input type="checkbox" class="toggle toggle-primary" />``` shows the toggle active state in primary color
but when using the other UI colors for toggle as  ```<input type="checkbox" class="toggle toggle-success"  />``` is not showing the success color

**Comment by saadeghi** [comment]
There's no `toggle-success` class name:  
https://daisyui.com/components/toggle/

 But you can apply `success` color or any other custom colors like this: https://github.com/saadeghi/daisyui/discussions/729
