### ISSUE TITLE
Button group 

### ISSUE THREAD

**Issue by hamzaelmaghari** [saadeghi/daisyui#1093]
Hi,
When having boutton group container with two or more buttons inside, there is a problem when clicking on them. It get all bounced.

## PREVIEW

https://user-images.githubusercontent.com/84163115/188283649-5bf85b37-00f6-471a-97ce-42db9b5e887b.mov

**Comment by saadeghi** [comment]
This is not normal. only the clicked button should have animation just like the example on the site: https://daisyui.com/components/button-group/

Please provide an example repo so I can reproduce the issue.

**Comment by hamzaelmaghari** [comment]
> This is not normal. only the clicked button should have animation just like the example on the site: https://daisyui.com/components/button-group/
> 
> Please provide an example repo so I can reproduce the issue.

Thank god, I realized what was the problem.
I use vue js, this when it loads new components, it gives animation to new loaded buttons.


https://user-images.githubusercontent.com/84163115/188491367-cdec030c-3cd7-4123-9d58-116db87cc832.mov

What can be done here is go to `tailwind.config.js`and make daisyui config `                "--animation-btn": "0.25s",
 =>                 "--animation-btn": "0",
`
