### ISSUE TITLE
2 drawer in RTL not positioning correctly

### ISSUE THREAD

**Issue by ariaieboy** [saadeghi/daisyui#1094]
this is the ltr version that works as intended :
https://play.tailwindcss.com/6ep4snumYj
but when we enable rtl it's not positioning correctly:
https://play.tailwindcss.com/6COQk65sU8

**Comment by saadeghi** [comment]
Fixed in `2.24.2`: https://play.tailwindcss.com/yfHsozYDhl

**Comment by ariaieboy** [comment]
https://play.tailwindcss.com/wyE9pXhUe3?file=config
