### ISSUE TITLE
JSX documentation issues

### ISSUE THREAD

**Issue by chazzox** [saadeghi/daisyui#1096]
[bottom navigation](https://daisyui.com/components/bottom-navigation/) jsx example includes `stroke-linecap`, `stroke-linejoin` and `stroke-width` attributes (should be `strokeLinecap` etc)

Used regex `className(.+)path stroke-([="\- \w]+)` to find

Currently looking for other examples will make a PR once i think i've found everything

**Comment by saadeghi** [comment]
Thank you!

**Comment by chazzox** [comment]
[Hero](https://daisyui.com/components/hero/) jsx example includes string style attribute

Searched for others using `className(.+) style="` and found nothing

**Comment by chazzox** [comment]
more svg attributes `fill-rule` and `clip-rule` are invalid in [footer](https://daisyui.com/components/footer/)

**Comment by chazzox** [comment]
[checkbox](https://daisyui.com/components/checkbox/) `checked="checked"`

I think thats all i can find for now! 

I'll make a pr tomorrow once i get back from work
