### ISSUE TITLE
Missing modifiers of some inputs

### ISSUE THREAD

**Issue by nyarthan** [saadeghi/daisyui#1097]
Like e.g. the `Text Input`, I think `Checkbox`, `Radio`, `Toggle` and maybe `Range` should also have the modifiers `info`, `success`, `warning` and `error`.
This might not be too useful in your day-to-day form but can be quite handy for feedback on the form e.g. exercises for learning software.

**Comment by NikarashiHatsu** [comment]
Hi @saadeghi, can I be assigned to this issue?
I'll try to apply those color modifiers to `Range`.

**Comment by saadeghi** [comment]
@NikarashiHatsu Yes of course!

**Comment by NikarashiHatsu** [comment]
Thank you!
