### ISSUE TITLE
applying opacity breaks collapse title toggle

### ISSUE THREAD

**Issue by curtis-j-campbell** [saadeghi/daisyui#1108]
Been attempting to tweak the styling of the collapse title for use within a footer on mobile view. Noticed that when applying either `footer-title` or specifically `opacity-50`, it breaks the collapse toggle functionality. I've made a [tailwind playground here](https://play.tailwindcss.com/UekGhQLnat) to show the issue. Let me know if you need more info or if there's a work around,

**Comment by saadeghi** [comment]
I think the link to playground is wrong. I don't see `opacity-50`.  
Where do you want to apply opacity?

**Comment by saadeghi** [comment]
Feel free to re-open this.
