### ISSUE TITLE
daisyUI logging breaking css output file using Bundle

### ISSUE THREAD

**Issue by kapitalisman** [saadeghi/daisyui#111]
I'm trying to use daisyUI for my Flask web app. I use Bundle with Flask-Assets (webassets) and apply filter="postcss" to compile the base tailwind css file. Bundle writes its output to a css file which now includes the logging of daisyUI:

� DaisyUI components 1.10.0  https://github.com/saadeghi/daisyui
  ✔︎ Including:  base, components, themes[2], utilities

Since this is not valid css, it breaks the entire file. Is there an option to disable logging (or mark them as warnings)?
Tailwind warnings like "You have enabled the JIT engine which is currently in preview." do not show up in the produced css file.

Bundle
```
styles_bundle = Bundle(
    "src/css/*.css", filters="postcss", output="dist/css/styles.min.css"
)
```

src/css/styles.css
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

postcss.config.js
```
const path = require('path')
const cssnano = require('cssnano')

module.exports = {
  plugins: [
    require('tailwindcss')(path.resolve(__dirname, 'tailwind.config.js')),
    require('autoprefixer'),
    cssnano({
      preset: 'default'
    }),
  ],
}
```

tailwind.config.js
```
const path = require('path')
const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  mode: 'jit',
  purge: {
    content: [path.resolve(__dirname, '../templates/**/*.html')],
    options: {
      safelist: [
        /data-theme$/,
      ],
    },
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      fontFamily: {
        sans: ['Nunito', ...defaultTheme.fontFamily.sans],
      },
    },
  },
  variants: {
    extend: {
    },
  },
  plugins: [
    require('daisyui'),
  ]
}
```

**Comment by kapitalisman** [comment]
Sorry for this. Just found the logs option in the source code.

**Comment by saadeghi** [comment]
@kapitalisman good. `logs` config and others are also documented on the site: https://daisyui.com/docs/config  

But I'm not sure why the logs goes inside the output file for you. It should just be printed on terminal 🤔
