### ISSUE TITLE
Same result on a btn element with disabled=true or disabled=false

### ISSUE THREAD

**Issue by Sonicfury** [saadeghi/daisyui#1112]
# Issue
I'm designing a link component, and need to be able to dynamically disable the link by passing props. Long story short, using `disabled=true` or `disabled=false` gives the same behavior which is annoying.

# How to reproduce

```html
<a disabled="false" class="btn btn-ghost" href="/">I am a link</a>
```

Just try that, the element should look disabled.

# Expected behavior
The element should be disabled only if disabled is set to true.

# Causes 

I believe this is disabled styles are put on
```css
.btn[disabled] {}
```

instead of 
```css
.btn[disabled=true] {}
```

**Comment by saadeghi** [comment]
Sorry but `disabled` is not a valid property for `<a>`  
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a  

I think if you need a `disabled` prop for your link, you should either return a completely different element (like a `<span>` without `href` or you should only disable the functionality of link without adding a `disabled` attribute to the `<a>` element.

**Comment by Sonicfury** [comment]
Ok you're right, my bad for the `<a>` (it's getting late).

Still, with a `<button>` element, this works the same. This would be practical not to style the `.btn[disabled]` but only `.btn[disabled=true]`.

Anyway, I found a workaround using the `btn-disabled`, but this felt cleaner to disable the element directly.

**Comment by saadeghi** [comment]
The reason we're using `[disabled]` selector instead of `[disabled=true]` is that `disabled` attribute is the shorthand for `disabled=true`. The expected way to handle this is either having a `disabled` attribute or completely remove the attribute.

**Comment by Sonicfury** [comment]
Yeah I figured. As long as I found a workaround, it's all good :)

Thanks for you work sir.
