### ISSUE TITLE
Adding daisyui plugin to tailwind config breaks build

### ISSUE THREAD

**Issue by johngrimsey** [saadeghi/daisyui#1116]
I have an Nx workspace with multiple apps. Adding this line to my Tailwind config:

`plugins: [require('daisyui')]`

Leads to build failure:

```
./apps/my-app-name/src/styles.scss - Error: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: node.walk is not a function

./apps/my-app-name/src/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: node.walk is not a function
```

After updating to the latest Nx with Angular 14 I'm encountering this. I'm not asking for a fix to Nx/Angular here in this repo obviously.

### Ideas
I'm not even 100% sure there's an issue with `daisyui` but thought I'd bring it up here. I'm not sure how to debug this. 

One guess is that it is related to paths, as I'm sharing styles between apps. 

Does `daisyui` use absolute paths anywhere, or does it construct paths in a manner that presumes the location of other files? 

Some of my deps:

```
    "postcss": "^8.4.16",

    "prettier-plugin-tailwindcss": "^0.1.13",

    "eslint-plugin-tailwindcss": "^3.6.1",

    "daisyui": "^2.25.0",

    "tailwindcss": "^3.1.8",
```

**Comment by johngrimsey** [comment]
I'm 99% sure this isn't a `daisyui` issue but more how I have scss files importing from various location. 

Shall leave this open in the hopes that something springs to mind, but please feel free to close if nothing does.

**Comment by johngrimsey** [comment]
Could it be something in `src/lib/postcss-prefixer` ?

**Comment by saadeghi** [comment]
As you mentioned, this is not an issue from daisyUI itself.

Might be a problem from one of your dependencies that handle CSS (probably the ones that are mentioned on your error log: `postcss-loader` or `mini-css-extract-plugin`)

Updating them or going back to older versions might help to find what exactly is causing the problem.

**Comment by saadeghi** [comment]
I'm closing this because it's not an issue from daisyUI package. Let me know if I can help

**Comment by christian-valadez** [comment]
Running into this as well @johngrimsey - did you happen to find a fix?
