### ISSUE TITLE
Checkbox Background Color unable to change 

### ISSUE THREAD

**Issue by sophonaroap** [saadeghi/daisyui#1119]
per: [How do I change the color of the checkbox](https://bytemeta.vip/repo/saadeghi/daisyui/issues/311)

> set --chkbg CSS variable for checkbox background color and --chkfg for checkbox foreground color.

This no longer works

**Comment by saadeghi** [comment]
The CSS works, but the config from that example link is old.  
Here's a new one: https://play.tailwindcss.com/MwBJTMq0JG?file=css

**Comment by zataara** [comment]
Hi @saadeghi will this method also work on a toggle as well to adjust the interior color that is base-100, not the bg or the border?

**Comment by saadeghi** [comment]
@zataara That's a little bit different. `toggle` has a CSS variable `--tglbg` and you can change it using a class name like `[--tglbg:yellow]`

So you can change the circle color, and border color and the the interior background like this:  
https://play.tailwindcss.com/qPtMRcJdLx
```html
<input
  type="checkbox"
  class="toggle bg-red-600 checked:bg-blue-600 checked:border-blue-600 [--tglbg:yellow]"
>
```
