### ISSUE TITLE
Question: How can I open / close a modal using JS?

### ISSUE THREAD

**Issue by Mashiane** [saadeghi/daisyui#1121]
Hi there

Id like to open / close the modal dialog via javascript? Is there a way to do it?

Thank you so much for your wonderful amazing lib.

**Comment by saadeghi** [comment]
The checkbox from [examples](https://daisyui.com/components/modal/) controls the modal. You can check/uncheck the checkbox using JS to open/close the modal.

**Comment by Mashiane** [comment]
Thank you so much.
