### ISSUE TITLE
img tag not closed on code snippet 

### ISSUE THREAD

**Issue by abhijitdotsharma** [saadeghi/daisyui#1122]
Three examples of **Card** component don't have `img` tag closed both in HTML and JSX snippet

- Card glass
- Card with image on side
- Responsive Card

[Card Component](https://daisyui.com/components/card/#card-glass)

<hr/>

![Card-glass](https://user-images.githubusercontent.com/61442144/189537648-2c27048e-40d0-47ab-b2ab-c68a8ccf788d.jpg)

![Card-img-responsive](https://user-images.githubusercontent.com/61442144/189537581-0b448a8c-bc56-40d2-ac75-8b9c3cbc9c10.jpg)

**Comment by abhijitdotsharma** [comment]
I would love to work on this if possible

**Comment by saadeghi** [comment]
Fixed in https://github.com/saadeghi/daisyui/pull/1131
