### ISSUE TITLE
Overriding both default light and dark theme's not working

### ISSUE THREAD

**Issue by greidinger-reis** [saadeghi/daisyui#1123]
I'm trying to override the default light theme with "emerald" and dark theme with "black"

```
daisyui: {
    themes: ["emerald", "black"],
    darkTheme: "black",
}
``` 

But this doesn't work. Instead it only overrides the light theme, and the dark theme is the same as the light one.

But when i let the default light theme be "light", the dark theme overriding works normally:

```
daisyui: {
    themes: ["light", "black"],
    darkTheme: "black",
}
``` 

Additionally when i add another theme to the array, the dark theme overriding also doesn't work:

```
daisyui: {
    themes: ["light", "black", "emerald"],
    darkTheme: "black",
}
``` 

I don't know if i'm doing something wrong there, but from what i've read at the docs it's pretty much explained like that

**Comment by amisora** [comment]
Hi @greidinger-reis !
I couldn't replicate this issue on my end.
Would you mind creating an mwe for this ?
I'd love to help :blush:

**Comment by greidinger-reis** [comment]
I don't even think it's a good idea to do what I was trying to do, so I will just close this issue
