### ISSUE TITLE
Collapse no longer works in my app with upgrade to versions > 2.25.0

### ISSUE THREAD

**Issue by grempe** [saadeghi/daisyui#1124]
Upgrading from release 2.25.0 to 2.26.0 or 2.27.0 breaks the use of the collapse component in my next.js application.

When clicking on the component there is no visible action that happens, nothing in the console.

Downgrading back to 2.25.0 resolves the issue.

I'm not able to reproduce in a simple new nextjs app at the moment but I can reproduce in my own more complex app.

I see that there were changes to the collapse component in release 2.26.0 which I suspect must be the cause of this.

https://github.com/saadeghi/daisyui/blob/master/CHANGELOG.md

https://github.com/saadeghi/daisyui/commit/e0fa734e957a9f6fa5202a3c35504315c50020fb

How can I help you identify what is happening to resolve?

**Comment by saadeghi** [comment]
Here's a Next.js repo, using the latest version of Next, daisyUI and Tailwind CSS:  
https://stackblitz.com/edit/daisyui-nextjs-bi21yk?file=pages%2Findex.js  

And everything works as expected.

I assume the problem should be either from your markup or some other thing (a build process change, some JS code, etc) might apply changes to styles.

**Comment by grempe** [comment]
Thanks, I'll take a look at the stackblitz. 

Please note though that I can reproduce this in my own repo by changing *only* the version of daisyui and *nothing* else. Doing this I can switch from working to non working at will.

Do you have suggestions, perhaps using browser console, how I might debug this?

I also pasted your simple sample collapse code to various pages in the app so it is not limited to a single page or context.

Thanks

**Comment by saadeghi** [comment]
Debugging process would be comparing the style from dev tools to see if your repo has the same CSS from my example repo. Make sure to compare both default style of elements and focus state.

And if the CSS is not the same, the CSS build process might cause the problem.  

As you mentioned in my commit, I added a `:where()` selector in daisyUI `2.26`. that might cause issues if the CSS build tool you're using is not updated (or might have bugs in processing `:where()` selector. So make sure everything related to CSS processing is using the last version (Post CSS and it's plugin, or any other CSS processor package you're using)

I would help debugging if you provide me a reproduction repo.

**Comment by grempe** [comment]
> Debugging process would be comparing the style from dev tools to see if your repo has the same CSS as my example repo. Make sure to compare both default style of elements and focus state.

I will try to examine this. 

> As you mentioned in my commit, I added a :where() selector in daisyUI 2.26. that might cause issues if the CSS build tool you're using is not updated (or might have bugs in processing :where() selector. So make sure everything related to CSS processing is using the last version (Post CSS and it's plugin, or any other CSS processor package you're using)

I have update to the latest version of every dependency. Everything is the latest version except for react 18 which I am not  using yet due to other conflicts. 

> I would help debugging if you provide me a reproduction repo.

I will try, but I'm also trying not to reproduce my entire app structure to do that.

Any additional tips appreciated. Is there a way I can remove just the 'where' to see if removing that solves it?

**Comment by saadeghi** [comment]
The problem is not `:where()`. The problem (I guess, maybe) is that `:where()` selector is not getting processed correctly in the build process.  
But that's just a guess because I've seen similar issue in an older version of Post CSS 7.

If you could provide a blank Next.js project with a similar [CSS processing] config of yours and dependency versions similar to your main project, the issue should be visible and I would help to debug.  
But if the same config and same dependencies work correctly, I don't know how to help.  
Maybe removing lock file and node_modules and running a fresh `npm i` will help getting rid of a faulty dependency version.

**Comment by grempe** [comment]
OK, I have a stackblitz example that demonstrates the issue. 💯 

https://stackblitz.com/edit/daisyui-nextjs-oeb3qn?file=README.md

See the `README.md` file in it to see more info. The summary is, I changed only the `dependencies` and `devDependencies` of `package.json` to match my project. I also changed the `tailwind.config.js` file to match my project.  It is not one or the other that causes the issue. It is some combination of the two.

The checkbox collapse JSX refuses to react when clicked. The focus collapse is OK.

I hope this helps resolve.

Cheers.

**Comment by grempe** [comment]
Wondering if you have any thoughts on this now that its been narrowed down with a working bug example.

**Comment by saadeghi** [comment]
The problem is `@tailwindcss/forms` plugin. By default, this plugin applies styles to all `<input>` elements.  
I don't think you would need the forms plugin and you can safely disable it because daisyUI already has class names to style form elements.  
But if you really need to use the `forms` plugin, use [its `strategy` config](https://github.com/tailwindlabs/tailwindcss-forms#using-only-global-styles-or-only-classes) so it doesn't apply style to all form elements by default.

**Comment by grempe** [comment]
Hi. Clearly, as you say,  there is a conflict between the tailwind forms plugin and DaisyUI. It took multiple hours of effort and communication with you to identify that and narrow it down to a reproducible bug. So clearly this is not obvious, or documented. 

Is there no way to deconflict DaisyUI against the entirety of the @tailwindlabs suite of tools?

I think that if you want to close this issue without any changes on the Daisy UI side that it is imperative that this issue be documented. If only to prevent many wasted hours for others who may unknowingly run into this issue in the future.

There should be a clear warning about conflicts and possible resolution strategies in the FAQ or Daisy UI setup documentation at a minimum.

**Comment by grempe** [comment]
Thanks for hearing me out.

I think the most important thing is to document known conflicts.

Yes, perhaps breakage could occur in combination with other tools, but in this case a conflict with @tailwindlabs is a special case since it is the foundation this library is built on.

If there is something you can detect in code that's helpful.

I would *not* make the assumption that developers will know about these conflicts. It is not clear at all how developers would go about doing a deep dive to understand the conflict with forms or any other lib. Remember, that was not even a suggested potential source of the issue when you yourself began the process of helping me diagnose this issue.

Some up front documentation about forms lib, and a warning against the potential for issues with other libs goes a long way I think.

Cheers
