### ISSUE TITLE
Tailwind typography's prose-invert not working with daisyUI

### ISSUE THREAD

**Issue by greidinger-reis** [saadeghi/daisyui#1128]
I'm trying to use the tailwind official typography plugin alongside with daisyUI, and when i try to use the prose-invert class the text simply doesn't invert colors, but as soon as i disable the daisyUI plugin, it works as intended, so maybe is this a bug or is there some caveat to using daisyUI with the typography plugin that i don't know?

**Comment by chornos13** [comment]
People don't understand what you are trying to achieve if there's no reproduce code 🥲

**Comment by greidinger-reis** [comment]
```javascript
<div className="prose dark:prose-invert"> // the color inversion from prose-invert doesn't work with the daisyUI plugin activated on the project.
    <ReactMarkdown remarkPlugins={[remarkGfm]}>{content}</ReactMarkdown>
</div>
```

**Comment by NikarashiHatsu** [comment]
Have you tried `dark:!prose-invert`?
It might solves the issue.

**Comment by saadeghi** [comment]
By default, daisyUI handles the dark mode.  
You won't need any `dark:` classes.  

Here's a working example: https://play.tailwindcss.com/z1tV76QHLF  
And a video:  

https://user-images.githubusercontent.com/7342023/199059932-83b67009-c0af-45af-bf49-b91c56022489.mp4

If that doesn't work for you, please share a sample repo so I can see what's wrong.

**Comment by st1ng7ay** [comment]
I have same issue with prose - https://play.tailwindcss.com/N5voK5X7Ur?file=config

module.exports = {
  daisyui: {
    styled: true,
    themes: [
      {
        light: {
          primary: '#0000ff',
          secondary: '#000000',
        },
      },
      {
        dark: {
          primary: '#00ff00',
          secondary: '#ff0000',
        },
      },
    ],
    base: true,
    utils: true,
    logs: true,
    darkTheme: 'dark',
  },
  plugins: [require('@tailwindcss/typography'), require('daisyui')],
}

**Comment by shrijit04** [comment]
Do you have the resolution. I am facing the same issue.

**Comment by saadeghi** [comment]
@shrijit04 What's the issue? Please share a [Tailwind Play link](https://daisyui.com/tailwindplay/)
