### ISSUE TITLE
Drawer only takes up header space

### ISSUE THREAD

**Issue by DanDev95** [saadeghi/daisyui#113]
In my header, I have a hamburger menu that makes use of the drawer. Unfortunately, the drawer only takes up the small space that the header has at the top, rendering it quiet useless. How can I make it take up the entire screen?

**Comment by saadeghi** [comment]
@DanDev95 Can you please show me an example of your code on Codepen or Tailwind Play or a GitHub repo?

**Comment by DanDev95** [comment]
Well it's the example code on the docs site.

`<div class="rounded-lg shadow bg-base-200 drawer h-52">
  <input id="my-drawer-3" type="checkbox" class="drawer-toggle"> 
  <div class="flex flex-col drawer-content">
    <div class="w-full navbar bg-base-300">
      <div class="flex-none lg:hidden">
        <label for="my-drawer-3" class="btn btn-square btn-ghost">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </label>
      </div> 
      <div class="flex-1 px-2 mx-2">
        <span>
              Change screen size to show/hide menu
            </span>
      </div> 
      <div class="flex-none hidden lg:block">
        <ul class="menu horizontal">
          <li>
            <a class="rounded-btn">Item 1</a>
          </li> 
          <li>
            <a class="rounded-btn">Item 2</a>
          </li>
        </ul>
      </div>
    </div>
  </div> 
  <div class="drawer-side">
    <label for="my-drawer-3" class="drawer-overlay"></label> 
    <ul class="p-4 overflow-y-auto menu w-80 bg-base-100">
      <li>
        <a>Item 1</a>
      </li> 
      <li>
        <a>Item 2</a>
      </li>
    </ul>
  </div>
</div>

`

**Comment by saadeghi** [comment]
just like the example on site, You need a container
```
<div class="drawer">
```
and to make it fill the height, you need to add `h-screen`
```
<div class="drawer h-screen">
```
https://play.tailwindcss.com/UVcJu0KhE7

Please let me know if you have any questions

**Comment by DanDev95** [comment]
Right, but then it makes the header very tall and pushes down the content below it (because of the screen height of the header)

**Comment by saadeghi** [comment]
@DanDev95 I'm not sure about the layout you want. you need to put the header, the page content, footer and everything inside `drawer-content`. the drawer is not the header, it's the container for whole page so it can show a off-canvas sidebar

**Comment by DanDev95** [comment]
Hmm, that will make it difficult to have a standalone Header component.

**Comment by saadeghi** [comment]
@DanDev95 Something like

```html
<div class="drawer h-screen">
  <input id="my-drawer" type="checkbox" class="drawer-toggle"> 
  <div class="drawer-content">

    <HeaderComponent/>
    <PageContent/>

  </div> 
  <div class="drawer-side">
    <label for="my-drawer" class="drawer-overlay"></label> 

    <SidebarContent/>

  </div>
</div>
```

**Comment by Colo-Codes** [comment]
I managed to solve this in a different way.

I used the `fixed`, `h-screen`, `w-full`, and `z-20` on the `drawer` (I got rid of the `drawer-content` `div` because it was messing up the layout of my components.

In this way, the drawer remains as an independent entity from my content, which is what I was looking for.

`
import { useState } from 'react';

const HamburgerMenu = props => {
    const [isOpen, setIsOpen] = useState(false);
    const [hide, setHide] = useState('');

    const clickHandler = () => {
        setIsOpen(!isOpen);

       // I'm still testing this part:
        setTimeout(() => {
            setHide('z-n1');
        }, 1000);
    };

    const fullPage = isOpen ? 'fixed h-screen w-full z-20' : hide;

    console.log("OPEN:", isOpen);
    return (
        <>
            <label for="my-drawer" class="btn btn-primary drawer-button fixed z-30 top-0 right-0" onClick={clickHandler} >open menu</label>

            <div class={`rounded-lg drawer drawer-end fixed h-screen w-full ${fullPage} `} >
                <input id="my-drawer" type="checkbox" class="drawer-toggle" checked={isOpen} />
                <div class="drawer-side">
                    <label for="my-drawer" class="drawer-overlay" onClick={clickHandler} ></label>
                    <ul class='p-6 pt-16 overflow-y-auto w-80 bg-base-100 flex-col '>
                        <li><a href='#section-projects' class='btn w-full mb-5' onClick={clickHandler}>Projects</a> </li>
                        <li><a href='#section-blog-posts' class='btn w-full mb-5' onClick={clickHandler}>Blog<span class='hidden sm:inline sm:ml-2'>Posts</span></a> </li>
                        <li><a href='#section-about' class='btn w-full mb-5' onClick={clickHandler}>About</a> </li>
                        <li><a href='#section-contact' class='btn w-full mb-5' onClick={clickHandler}>Contact</a> </li>
                    </ul>
                </div>
            </div>
        </>
    );
};

export default HamburgerMenu;`

**Comment by kominov** [comment]
Hi. Pleace tell me how can i hidden drawer when i click to menu link? now a new page opens and the menu stays in place. in your site when i click menu link drawer is hidden

**Comment by saadeghi** [comment]
@kominov https://github.com/saadeghi/daisyui/issues/288

**Comment by ninsky** [comment]
Also see here https://github.com/saadeghi/daisyui/issues/297

**Comment by msh2050** [comment]
I have the same issue if the navigation is outside the drawer you need to change the height of the drawer
see [this ](https://stackoverflow.com/questions/65976223/how-to-use-calc-in-tailwind-css)for more details
for me, I solve this with svelte by adding this :
```css
<style>
	:global(.drawer) {
		height: calc(100vh - theme('spacing.20'));
	}
</style>
```

**Comment by johngouf** [comment]
> @DanDev95 Something like
> 
> ```
> <div class="drawer h-screen">
>   <input id="my-drawer" type="checkbox" class="drawer-toggle"> 
>   <div class="drawer-content">
> 
>     <HeaderComponent/>
>     <PageContent/>
> 
>   </div> 
>   <div class="drawer-side">
>     <label for="my-drawer" class="drawer-overlay"></label> 
> 
>     <SidebarContent/>
> 
>   </div>
> </div>
> ```

Was wondering how we can change this example for making the header sticky on top?
So that both the sidebar and the content are below it?
I am trying to have this layout:
![image](https://user-images.githubusercontent.com/1265084/202428698-d1058db8-06bc-488b-9ef3-7fb57f9f9e6a.png)
It works fine but the when we scroll on the main content the bottom gets clipped
