### ISSUE TITLE
Drawer with tree structure..

### ISSUE THREAD

**Issue by Mashiane** [saadeghi/daisyui#1132]
Hi there

I am using an example of a drawer with a tree structure with parent and child items. Found it here somewhere as a response to a OP.

![image](https://user-images.githubusercontent.com/5799306/189942248-f04aa212-4502-46e9-8549-ab8920e812db.png)

What I could like to do is to have a fix about this overlap when more items are listed. I will attempt some code of only opening the active item and closing others. If there is anything like that already it would help.

Thanks a lot.

**Comment by NikarashiHatsu** [comment]
I faced this issue before, and #458 fixed the issue.
I also tried to add children as I tried to reproduce this issue, but it seems like it is working as intended.

<img width="288" alt="Screen Shot 2022-10-07 at 04 35 20" src="https://user-images.githubusercontent.com/43662951/194423093-6f5e1065-1079-45f9-bf74-7425091316c3.png">

It would be really helpful if you put some code sample.

**Comment by saadeghi** [comment]
@Mashiane Please provide a sample repo or a sample code so I can reproduce the issue.

Feel free to re-open this issue after providing a sample
