### ISSUE TITLE
Zoom issue in button

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [saadeghi/daisyui#1133]
On double tap button zoom. I don't want this behaviour. Can I know how to fix this issue without disabling zoom on entire site

**Comment by saadeghi** [comment]
Can you attach a video so I can see what you mean?  
I may also need details about your Phone model and browser version.

**Comment by rahulkumarsingh73690** [comment]
Phone model - iPhone 12
Browser - Chrome


https://user-images.githubusercontent.com/37482171/190076666-47ecfabc-2b1c-4693-809a-916c21f69182.MP4

**Comment by rahulkumarsingh73690** [comment]
This issue is in both chrome and safari on double tap on btn class

**Comment by joaom00** [comment]
Hey @rahulkumarsingh73690

You can use [`touch-manipulation`](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) to disable this behavior.

**Comment by rahulkumarsingh73690** [comment]
I am not sure what is the right way to disable in daisy UI

**Comment by joaom00** [comment]
Just pass the `touch-manipulation` class [like in tailwind](https://tailwindcss.com/docs/touch-action)

**Comment by joaom00** [comment]
You can use your css file to [customize the daisyUI's classes](https://daisyui.com/docs/customize/).

[Example (see CSS file)](https://play.tailwindcss.com/Ow7EGLOGTH)

**Comment by rahulkumarsingh73690** [comment]
Thanks @joaom00
