### ISSUE TITLE
Dropdown inside a modal causes overflow

### ISSUE THREAD

**Issue by ethanplee14** [saadeghi/daisyui#1149]
I'm trying to use the dropdown in a modal for a search input. I set the position of the dropdown to be fixed but it's still causing the modal to be overflowed. I can have the expected functionality work when I set overflow-y-visible for the model box, but i want the modal to be able to scroll. 

I expect the behavior to be like: 
https://play.tailwindcss.com/VSlXDsGiBn

but the dropdown causes the scroll in the modal-box: 
https://play.tailwindcss.com/yAzphbRGam

**Comment by shaik16** [comment]
hey @ethanplee14  you can add overflow-y-visible on line 7
![Screenshot 2022-09-18 at 12 40 09 AM](https://user-images.githubusercontent.com/32085146/190872865-fe71b293-0346-4f82-a6d1-bd6e6784d7be.png)

**Comment by ethanplee14** [comment]
> hey @ethanplee14 you can add class `overflow-y-visible `on line 7
> 
> ![Screenshot 2022-09-18 at 12 40 09 AM](https://user-images.githubusercontent.com/32085146/190872915-9cc00b4f-d40a-445e-9a81-c7e8f4cb9031.png)

Ya that works but then it disables the ability for the modal to scroll if there's too much content within it. I want the dropdown to be fixed and exit the document flow while keeping the scrolling behavior of the modal.

**Comment by shaik16** [comment]
@ethanplee14  you should define the max height of the modal I guess.  but if you are looking to hide the scrollbar when using scroll you can do that by adding an extra class

**Comment by ethanplee14** [comment]
> 

again i'm looking to keep the scrolling feature of the modal box. By establishing max height and overflow-y-visible, it fixes the issue, but it removes scrolling all together.

**Comment by ethanplee14** [comment]
> @ethanplee14 you should define the max height of the modal I guess. but if you are looking to hide the scrollbar when using scroll you can do that by adding an extra class

again i'm looking to keep the scrolling feature of the modal box. By establishing max height and overflow-y-visible, it fixes the issue, but it removes scrolling all together.

**Comment by saadeghi** [comment]
I created a CSS example here: https://play.tailwindcss.com/hQmU1H238J

You can see when there's `height` and `vertical scroll`, the absolute content will take the space. I'm afraid that's a limitation I can't do anything about it.

Possible workaround:  
I'm not sure about the content but you might want to separate your scrollable content like this:  
https://play.tailwindcss.com/803s8YQUCL

Let me know if you have any questions.
