### ISSUE TITLE
Add Color Picker  component 

### ISSUE THREAD

**Issue by workingxx92** [saadeghi/daisyui#115]

**Comment by saadeghi** [comment]
@workingxx92 why not using native color picker?
```html
<input type="color">
```

**Comment by workingxx92** [comment]
@saadeghi 
I cannot close dialog color when click outside

**Comment by saadeghi** [comment]
@workingxx92 I don't see any problem 🤔  
https://play.tailwindcss.com/dTrEqcgUNE  

https://user-images.githubusercontent.com/7342023/127782302-7f646172-7e28-4a1e-a98b-14f4f3a4b600.mp4

**Comment by workingxx92** [comment]
@saadeghi .
Please run on firefox. I cannot close dialog color when click outside on firefox

**Comment by saadeghi** [comment]
Firefox opens OS color picker as a popup window. Some people like it this way, some don't.  
Anyway, it's not possible to make a custom color picker in a CSS library like daisyUI, so if you need a custom color picker, you need to use a JS plugins for that.  

**A few to mention:**  
- https://github.com/jaames/iro.js
- https://github.com/Simonwep/pickr
- https://github.com/casesandberg/react-color
- https://github.com/efeskucuk/svelte-color-picker
- https://github.com/codeosemeke/vue-colour-picker
