### ISSUE TITLE
Button animation doesn't seem to be very smooth in safari?

### ISSUE THREAD

**Issue by zxdstyle** [saadeghi/daisyui#1150]
Button animation doesn't seem to be very smooth in safari?

**Comment by saadeghi** [comment]
I don't see any problem.  
- Do you see the same issue with CSS animations o other websites?
- Do you see the same issue using Safari on another Mac?

**Comment by zxdstyle** [comment]
The animation in safrai is obviously stuck, but it is normal on another computer, maybe my computer is wrong
