### ISSUE TITLE
provide safelists for components

### ISSUE THREAD

**Issue by arily** [saadeghi/daisyui#1155]
concatenated class names will not be detected by tailwind according to the document.
It would be much more convenient to have some pre-defined safelists for users to import. 

```js
// safelist
export const button = [
    {
      pattern: /btn-.+/
    }
]
```
```js
// tailwind.config.js
const { button } =  require('daisyui/config/safelist')

module.exports = {
  safelist: [
     ...button,
  ]
}
```

**Comment by saadeghi** [comment]
I can add a safelist file to the package that includes all class names used by daisyUI... But are you sure this is what you want to do? If you safelist all daisyUI styles, it won't be different than using the CDN file and every unused class name will be included in the production.

I don't think it's a good idea to safelist unused class names. Instead we should find a way to scan the markup and only include the styles we need.

**Comment by saadeghi** [comment]
Let me know if you have any questions

**Comment by arily** [comment]
Sorry I didn't paying attention to github notifications.
I was thinking about create an registery for any used components and maybe variants,

it will be something like this:

```js
import { register, createSafelist } from "somewhere"

register("btn") // will include every button styles

// includes only 'tabs' and 'tab-bordered' to safelist (tab will get included by tailwind scanning this file)
register("tab", { variant: "bordered" })

createSafelist() // generated safelist[]
```

so that wse can create the safelist programmatically and trying to safelist

```jsx
import { register } from "somewhere"
const button = ({ children, variant }) => {
  if (variant) {
    register("btn", { variant })
  }

  return <button className={`btn btn-${variant}`}>{children}</button>
}
```

and in tailwind config

```js
const { createSafelist } = require("somewhere")
module.exports = {
  safelist: [...createSafelist()],
}
```

I think we could provide this registery in daisyui out of the box if you are interested.
