### ISSUE TITLE
feat: divider-solid divider-dotted divider-dashed divider-double and so on

### ISSUE THREAD

**Issue by ThaddeusJiang** [saadeghi/daisyui#1163]
Maybe we can provide more `divider-*` classes for users.

Maybe we have provided this feature, if so, we just need to add some examples.

**Comment by yangricardo** [comment]
I also want options to customize divider colors

**Comment by saadeghi** [comment]
@yangricardo here's an example for colors:
https://play.tailwindcss.com/B7X71XGhTx

I don't think dots and dashes would be useful for the majority of users. So let's let the developers do it using custom CSS if they want.

Let me know if you have any questions

**Comment by yangricardo** [comment]
> @yangricardo here's an example for colors: https://play.tailwindcss.com/B7X71XGhTx
> 
> I don't think dots and dashes would be useful for the majority of users. So I think it's better to let the developers do it using custom CSS if they want.
> 
> Let me know if you have any questions

@saadeghi , thank you for the example and for all your work with Daisy Ui. It's really helping in my projects.
Going to try your example soon.
