### ISSUE TITLE
Open/close modal with class change

### ISSUE THREAD

**Issue by chrispytoes** [saadeghi/daisyui#1167]
From the docs, it seems the only way to open/close a modal is using a clickable button. I don't see any (simple) way to control the modal using JS. If there was a class that could be applied to open/close the modal, that would be all that's needed for this.

**Comment by oben01** [comment]
Hello @chrispytoes 
u can play with the class `modal-open` to open/close your modal. 
<img width="1390" alt="Capture d’écran 2022-10-04 à 18 44 20" src="https://user-images.githubusercontent.com/22369027/193878633-e2d1d8db-c2fb-4316-aced-063bcae8d525.png">

**Comment by chrispytoes** [comment]
@oben01 Woops, can't believe I missed that. Thanks!
