### ISSUE TITLE
Unable to add `input` fields within `collapse` component

### ISSUE THREAD

**Issue by Aravin** [saadeghi/daisyui#1171]
## Setup
Tailwind version 3+
DaisyUI version 2.3

## What I do

I am trying to put form within the collapse component, screenshot for your reference:

![image](https://user-images.githubusercontent.com/4869265/191774701-8bb65b95-a836-4fa8-8c3b-643aff2c3a25.png)

## Actual Issue
Whenever I try to edit the input field within the accordion, the accordion is collapsed automatically.

## Sample Code
Tailwind Play code: https://play.tailwindcss.com/Or7NaF3GEW

## What I am planning to do:
I am trying to achieve something like this

![image](https://user-images.githubusercontent.com/4869265/191775595-7b820120-512f-4cba-b20e-961f5424d4de.png)

**Comment by jonahisadev** [comment]
Because the accordion is only opened when focused, when you focus the input element, the accordion loses focus and collapses again. You want something that toggles separately from the accordion focus. You can find an example in the [docs](https://daisyui.com/components/collapse/#custom-colors-for-collapse-that-works-with-checkbox), and [in this playground](https://play.tailwindcss.com/UQT9zrptDS)

![image](https://user-images.githubusercontent.com/27779755/191837483-b18348d2-295c-4005-9e9a-bc2c18ae19c0.png)

**Comment by Aravin** [comment]
Cool. Thanks.

**Comment by DaniumX** [comment]
This still doesn't work on iPhone. It collapses as soon as the iphone keyboard is brought up.

**Comment by jonahisadev** [comment]
> This still doesn't work on iPhone. It collapses as soon as the iphone keyboard is brought up.

I was unable to reproduce this on an iPhone running the latest software. Please make sure you're using the correct example from the docs or the example I provided in my solution. If you're still having problems, consider opening a new issue with the steps needed to reproduce it.

**Comment by saadeghi** [comment]
@DaniumX as @jonahisadev said, make sure you're using the example with checkbox. If you use the example that works with `focus`, collapse will close if any other element steals the focus. That's just how focus works. One element can have focus at a time.

**Comment by DaniumX** [comment]
> @DaniumX as @jonahisadev said, make sure you're using the example with checkbox. If you use the example that works with `focus`, collapse will close if any other element steals the focus. That's just how focus works. One element can have focus at a time.

I did use the example with the checkbox. I did also solve this by removing the tabIndex. Strange solution but it worked.

**Comment by saadeghi** [comment]
@DaniumX I'm glad you found the solution.  
I just have to mention that in the [docs](https://daisyui.com/components/collapse/#collapse-with-checkbox) the example with checkbox does not have tabindex at all. Tabindex is used for the focus examples.

**Comment by DjTer3a** [comment]
I had a similar issue when using the collapse with the checkbox without using Tabindex. 
On my local machine, the following code was not working (The collapse was , unresponsive, not opening/closing when clicked), and I was not able to reproduce the issue in neither [codepen.io](https://codepen.io/) or [tailwind play](https://play.tailwindcss.com/UQT9zrptDS)  

Code from [docs](https://daisyui.com/components/collapse/#collapse-with-checkbox):-
```
<div className="collapse">
  <input type="checkbox" /> 
  <div className="collapse-title text-xl font-medium">
    Click me to show/hide content
  </div>
  <div className="collapse-content"> 
    <p>hello</p>
  </div>
</div>
```
Changing the collapse-title component from **div** to **label** and adding an id to both the checkbox and the label fixed the problem for me.

Solution:-
```
<div className="collapse">
  <input type="checkbox" id="collapse-checkbox" /> 
  <label for="collapse-checkbox" className="collapse-title text-xl font-medium">
    Click me to show/hide content
  </label>
  <div className="collapse-content"> 
    <p>hello</p>
  </div>
</div>
```
