### ISSUE TITLE
Tooltip partially hidden within Card

### ISSUE THREAD

**Issue by haobinliang** [saadeghi/daisyui#1175]
The tooltip within a card is bounded by `overflow: hidden` of the card; therefore when the content of the tooltip is too long or close to the edhe of the card, it is particlaly hidden.

Example: https://play.tailwindcss.com/Z8Hq3XM8pn

![Screenshot 2022-09-23 at 19 21 37](https://user-images.githubusercontent.com/7793969/192032407-493d68f1-67c5-45f5-bd21-d27da442c845.png)

**Comment by NikarashiHatsu** [comment]
The only possible temporary workaround is by applying `overflow-visible` class to the `card`. I'm also hoping that this issue will be fixed in the future 😅.

```html
<div class="card overflow-visible">
    <!-- content -->
</div>
```

**Comment by haobinliang** [comment]
> The only possible temporary workaround is by applying `overflow-visible` class to the `card`. I'm also hoping that this issue will be fixed in the future 😅.
> 
> ```
> <div class="card overflow-visible">
>     
> </div>
> ```

Thanks @NikarashiHatsu ... It's a trade off of showing the card photo corners as rectangle because they are overflow... 😢 So would need to add `rounded-tr rounded-tl` to the `img` tag as well...

**Comment by NikarashiHatsu** [comment]
Yea, it's kind of annoying to have put some extra classes 😅. I thought putting `z-50` along with `tooltip` will fix the issue, sadly it won't.

**Comment by jorgv** [comment]
Hi, I have the same problem when usingthe tooltip in a sidebar is there any other workaround to have the tooltip always showing
![image](https://user-images.githubusercontent.com/32174909/198276723-643ab028-3f87-4385-9f3f-bebb9caad0cd.png)

**Comment by SacredSkull** [comment]
This is still present AFAIK, I think `overflow-clip` is a better solution for this. I was getting some odd (and horrible to track down) additional spacing causing the entire page to overflow with multiple collapses in a column using `overflow-visible`.
