### ISSUE TITLE
Request for help: RadioGroup like InputGroup

### ISSUE THREAD

**Issue by Mashiane** [saadeghi/daisyui#1179]
Hi there

I am currently trying to customize by radio group to work like an input group and follow the same outline in the design.

![image](https://user-images.githubusercontent.com/5799306/192097582-44c9c396-46c2-40eb-8cc0-5839a2f3084f.png)

This is the playground.

https://play.tailwindcss.com/8e8tbD8M5X

I need to make it work perfectly. Can someone help please.

1.  I am not sure about the border properties for what I have set a label to host everything so that it works like an input border.
2. The other problem is the height, in the row-view with the current items its fine, more items added will surely sit outside the box, how do I make this work?
3. Also I am able to set a column-view by removing "flex" on that label, this works, however how do I make the items be placed on the left part and not far right

![image](https://user-images.githubusercontent.com/5799306/192097750-ba5b3aa1-1f59-4e26-a896-5a3ae20414b3.png)

PS: Please bear with me this is my 2nd week of learning this. Thanks.

**Comment by Mashiane** [comment]
This is the ultimate outline... it would help to make the radio flexible

![SignUp](https://user-images.githubusercontent.com/5799306/192098625-d1c617a2-ca73-4923-a6ea-475e676c2e29.jpg)

**Comment by saadeghi** [comment]
Sorry but I'm not sure I understand what is your goal 🤔  
If you want to make it a column on small screens and make it a row on larger screens, use a flexbox like this:
```css
flex flex-col lg:flex-row
```
And don't give it a fixed height. for border, radius, etc, you can use Tailwind CSS classes like this:
```css
border border-base-content/10 rounded-lg
```

I added those classes to your example: https://play.tailwindcss.com/YF2vhyxQZZ

I'm still not sure if that was the goal or not, but let me know if you have any qusetions.

**Comment by Mashiane** [comment]
Thank you so much.
