### ISSUE TITLE
aos not working

### ISSUE THREAD

**Issue by choi-spaceflo** [saadeghi/daisyui#1189]
Hello,
once I install daisyui in my nextjs project, AOS(animation on scroll) no longer work.
In fact every items which applied 'data-aos' attribute went hidden.
I guess some css attribute has overwritten..
I've checked if I remove require("daisyui") in tailwind.config.js, AOS work again.
plz help this.

https://github.com/michalsnik/aos

`<div data-aos="fade-in">TEST</div>`

**Comment by saadeghi** [comment]
are you using daisyUI's [`drawer`](https://daisyui.com/components/drawer/)?  
If so, that might be the issue. when you use `drawer`, the element that must be scrolled, is not `<body>` any more. you should monitor or manipulate the `drawer` element for scroll changes.

Let me know if you have any questions.

**Comment by choi-spaceflo** [comment]
thx for your reply! 
yes, I'm using `drawer`... so should I abandon one of them?:(
or if there's any solution or work-around to use `aos` and `drawer`, plz let me know.
