### ISSUE TITLE
Swap checkbox doesn't hidden

### ISSUE THREAD

**Issue by No1ceTea** [saadeghi/daisyui#1191]
I try to use some swap but the checkbox is clear and not hidden 
![image](https://user-images.githubusercontent.com/71291683/192543323-f52f5e8f-53ae-44bd-b07e-1a3b2163805b.png)

**Comment by saadeghi** [comment]
Please provide a code example on a small repo or a Tailwind Play page so I can reproduce the issue

**Comment by saadeghi** [comment]
Please reopen after providing and example repo. this seems like to be a problem caused form another CSS code.

**Comment by FLasH3r** [comment]
Same issue here,
 fresh project, I think all dependencies are latest.
 
 package.json
 ```json
"tailwindcss": "^3.2.4"
"@tailwindcss/forms": "^0.4.1",
"@tailwindcss/typography": "^0.5.7",
"daisyui": "^2.42.1",
```

tailwind.config.js
 ```javascript
 plugins: [
    require('@tailwindcss/forms'),
    require("@tailwindcss/typography"),
    require("daisyui")
  ],
  daisyui: {
    themes: ["fantasy","dark"],
  },
  ```

![image](https://user-images.githubusercontent.com/1413249/207197221-e6a16f0c-996e-4c92-9f98-4af2a91af414.png)
![image](https://user-images.githubusercontent.com/1413249/207198017-c7abf8f0-2faa-425c-87cf-36788484d880.png)

![image](https://user-images.githubusercontent.com/1413249/207197581-6c49489d-9b0f-4284-8267-40e7e8f54baf.png)

![image](https://user-images.githubusercontent.com/1413249/207197665-1a61f352-2143-4d82-a741-0450b67621e8.png)

![image](https://user-images.githubusercontent.com/1413249/207197701-50b71cab-a921-48a6-8e6c-e13682f7ad3d.png)

![image](https://user-images.githubusercontent.com/1413249/207197744-791b03d7-adc5-4ed0-a632-d7bc9fd7fd23.png)
