### ISSUE TITLE
Lots of overflow.

### ISSUE THREAD

**Issue by Bendimester23** [saadeghi/daisyui#1192]
Daisyui version: 2.24.0
Tailwind version: 2.2.19

When hovering on tooltips, only the part, where the original element is shows: 
![image](https://user-images.githubusercontent.com/58264102/192610221-a1c399eb-6b8f-4f48-bb1d-c5d752b28152.png)
Code is from the daisyui website.

Also for some reason event heading texts overflow: 
![image](https://user-images.githubusercontent.com/58264102/192610754-c04d4622-4ca8-4115-8516-313e206493ca.png)
Code:
![image](https://user-images.githubusercontent.com/58264102/192610835-25a795f4-01f4-460d-b018-525e2c4a7fc1.png)

**Comment by saadeghi** [comment]
I don't think this code is identically from daisyUI examples. The problem might be from other utility classes.  
Please share the code so I can reproduce the issue.

Also, the second screenshot is not even using a daisyUI class name.

**Comment by Bendimester23** [comment]
[here is the code](https://github.com/SkyVillageMC/web/blob/91a021d98ed68a7e0de1a391174103472e6bf957/components/TeamMemberCard.vue#L10)

**Comment by saadeghi** [comment]
😕 It's because of your custom CSS here: https://github.com/SkyVillageMC/web/blob/91a021d98ed68a7e0de1a391174103472e6bf957/assets/main.css#L6
