### ISSUE TITLE
IDEA: Allow applying button size to button-group

### ISSUE THREAD

**Issue by danawoodman** [saadeghi/daisyui#1194]
I think it would be nice (and intuitive) if you can apply a button size to a `.button-group`, perhaps like:

```html
<div class="btn-group btn-group-sm">
  <button class="btn">...</button>
  <button class="btn">...</button>
  <button class="btn">...</button>
</div>
```

This would allow you to style multiple buttons at once without duplicating styles per-button. Thoughts?

**Comment by saadeghi** [comment]
What should happen if we use button size on both the group and the button itself? That would be confusing.

**Comment by danawoodman** [comment]
Arguably you should just set on the group so you don't have to duplicate it many times. I think it would just be more consistent and intuitive to apply to all children

**Comment by saadeghi** [comment]
I understand but I think we should avoid applying the same style to an element using class names coming from multiple elements (self and parent). That would be just confusing. I don't want someone to see a `btn-group-lg` and `btn-sm` inside and wonder what would be the size of button. that's just unpredictable code.

However, this is already possible using Tailwind CSS arbitrary class names. You can apply a class to all direct children using a class like `[&>*]:btn-xs`:  
https://play.tailwindcss.com/NBmWLrqM0X
```html
<div class="btn-group [&>*]:btn-xs">
  <button class="btn">Button</button>
  <button class="btn">Button</button>
  <button class="btn">Button</button>
</div>
```

**Comment by danawoodman** [comment]
Understand. However, maybe a sample showing this in the docs would be nice?
