### ISSUE TITLE
auto scroll for Full-bleed carousel

### ISSUE THREAD

**Issue by muhammedfayaz** [saadeghi/daisyui#1196]
How can I scroll in each second without mouse

**Comment by bingalls** [comment]
Hopefully, we can add this Vanilla JS to the docs. Works responsively for any width.
Add `id="carouselBox"` to the parent container
```javascript
<script>
    function carousel(numSlides) {
        "use strict";
        const carouselBox = document.getElementById('carouselBox');
        let slide = 0
        setInterval(() => {
            if (slide >= carouselBox.scrollWidth) {
                slide = 0;
            } else {
                slide += (carouselBox.scrollWidth / numSlides);
            }
            carouselBox.scrollLeft = slide;
        }, 6000);   // 6 sec delay between each slide
    }
    carousel(3);  // if you have 3 images
</script>
```

**Comment by muhammedfayaz** [comment]
Thanks, There was an issue in this plugin to swipe through mouse in desktop screen. So , I use swiperjs for sliders.

**Comment by bingalls** [comment]
@muhammedfayaz Could you be more specific on the steps to reproduce your problem?
On MacOS running Monterey & Chrome-like browser, 2-finger trackpad horizontal scrolling works.
The only swiping for such a desktop would be using mobile simulation in developer tools.
Also test that such a swipe works with any `overflow-x:scroll;` div

**Comment by muhammedfayaz** [comment]
am using mouse not trackpad

**Comment by muhammedfayaz** [comment]
solution: Swiperjs works for me

**Comment by saadeghi** [comment]
I just want to acknowledge that daisyUI carousel is just a basic CSS-only solution and it can't compete with JS carousel plugins.  
For a better accessibility and more control, using a JS plugin (like Swiperjs as you mentioned) would be a better decision.
