### ISSUE TITLE
Mobile: Navbar to Drawer?

### ISSUE THREAD

**Issue by IngwiePhoenix** [saadeghi/daisyui#12]
While checking out the components [here](https://saadeghi.github.io/daisyui-demo/), I noticed that the Navbar did not collapse or have any special function for a smaller viewport - as for a mobile device.

Is there a way to have a navbar that only shows a menu icon and unfolds a drawer for mobile screens but has a full and proper menu bar on tablets and desktop?

The fold-out menu that Bootstrap uses feels a little off, Drawers have a better way of customization.

Besides that, I love the components and theming features! Really great work there :)

Kind regards, Ingwie

**Comment by saadeghi** [comment]
Currently there's a [navbar component](https://daisy.js.org/components/navbar) and it just places items in a row using flexbox. There's also a [drawer component](https://daisy.js.org/components/drawer) which opens an off-canvas sidebar (or shows a fixes sidebar on desktop `lg` viewport if you want)

One solution might be dynamically changing the style of `navbar` items into a vertical menu and place them in a drawer.
- pros:
  - no duplicate HTML for menu items
- cons:
  - what actually is happening here is transforming one component to another component.
  - there could be anything on a navbar or sidebar drawer. it's not always a simple menu, so it might not the best decision to just put everything from navbar into a vertical drawer for mobile.

The other solution is just having a navbar, hide extra items on mobile resolution. then having a drawer to show the items on mobile. ([see example here](https://play.tailwindcss.com/aLJzPyk1aq))
- pros: 
  - there's no limit. you can put anything on your navbar and your drawer. not only a menu.
  - you can control which item should be visible on mobile or desktop (using `hidden` class)
- cons:
  - duplicate html for the menu (if you want to show it horizontally on desktop and vertically on mobile)

I'm not strict on this and I'm also looking for the best solution but for now, I think the second solution makes more sense and gives you more control ([like this](https://play.tailwindcss.com/aLJzPyk1aq))
