### ISSUE TITLE
is it possible to still load all themes with a custom one?

### ISSUE THREAD

**Issue by ctwhome** [saadeghi/daisyui#120]
I am trying to add my custom theme but it seems that it overwrite the rest of the theme, so the theme switcher doesn't work anymore. 

I tried this solution but doesn't load the themes, in fact, it breaks the tailwindcss.config.js file 

![](https://user-images.githubusercontent.com/4195550/128467698-3805a183-ccd6-4c47-88ee-35ea923997cf.png)

**Comment by saadeghi** [comment]
@ctwhome You can add theme names next to your own theme object. [[see this example](https://github.com/saadeghi/daisyui/blob/master/examples/custom-themes/tailwind.config.js)]  
If you want your own custom theme **+** all other themes, you need to name them all.  
In below example, `mytheme` will be default theme, `myothertheme` will be another custom theme and then the rest of themes:
```js
daisyui:{
  themes:[
    {'mytheme': {
      'primary: '#ffb83d',
    }},
    {'myothertheme': {
      'primary: '#ffb83d',
    }},
    'light',
    'dark',
    'cupcake',
    'bumblebee',
    'emerald',
    'corporate',
    'synthwave',
    'retro',
    'cyberpunk',
    'valentine',
    'halloween',
    'garden',
    'forest',
    'aqua',
    'lofi',
    'pastel',
    'fantasy',
    'wireframe',
    'black',
    'luxury',
    'dracula',
  ]
},
```

Please let me know if you have any questions.

**Comment by ctwhome** [comment]
working thanks!
