### ISSUE TITLE
hoverOnlyWhenSupported not works with daisyui

### ISSUE THREAD

**Issue by sr-tamim** [saadeghi/daisyui#1209]
https://github.com/tailwindlabs/tailwindcss/pull/8394

**Tailwind** has added a new feature. The feature is ~ stop hover effect in mobile & other touch devices. View above link 👆

> This is a very useful feature. Default hover selector of css causes _stuck_ hover state in mobile.

## Add this feature in daisyui ASAP

**Comment by sr-tamim** [comment]
@NikarashiHatsu
I've updated tailwind config file. As I said in previous comment that, hoverOnlyWhenSupported feature works when I use tailwind classes like `hover:bg-red-500` `hover:text-green-400` etc.
But it doesn't work when I use daisyui component classes like `button-outline` etc.

**Comment by saadeghi** [comment]
Let me mention some facts here.
- daisyUI component classes are used so people don't have to design things themselves.
- Tailwind CSS utility classes are used so people can design things themselves.
- If you use a daisyUI `btn` it means you don't want to decide how `hover` should look like etc.
- daisyUI is a plugin for Tailwind CSS. It's basically a collection of CSS files delivered straight to the Tailwind CSS engine. It's up to Tailwind how it compile the CSS so it's not really up to daisyUI to manipulate the style based on a specific Tailwind config.

I hope it clear things up.  
Let me know if you have any questions.
