### ISSUE TITLE
Add footer component

### ISSUE THREAD

**Issue by workingxx92** [saadeghi/daisyui#121]

**Comment by justingolden21** [comment]
![image](https://user-images.githubusercontent.com/30274440/128592980-855ac29c-62f8-4dc0-834c-9a4f5fc817dd.png)

the contrast of the logo in the footer is atrocious

**Comment by saadeghi** [comment]
fixed in 8227925041a6a4ed434e48db0805c33443beba2c

**Comment by justingolden21** [comment]
That's a little better, thanks for fixing this 😄 

![image](https://user-images.githubusercontent.com/30274440/130532013-47351f88-5be6-4bb7-8454-2699e21664d3.png)
