### ISSUE TITLE
disable daisyui in nextjs

### ISSUE THREAD

**Issue by KailasMahavarkar** [saadeghi/daisyui#1210]
hello devs!
is it possible to disable daisyui plugin for just 1 page in Next.js?

**Comment by saadeghi** [comment]
Ideally you only need 1 CSS file for a Tailwind project.  
You use the same CSS file on all pages. The file is cached on the first load so nothing to worry about if some CSS rules are not used on a specific page.  
However if you really need to have 2 different CSS files, you can have 2 separate PostCSS files with 2 different Tailwind configs. one with daisyUI, one without it.

Let me know if you have any questions.
