### ISSUE TITLE
How to fix the select width when using w-full?

### ISSUE THREAD

**Issue by Mashiane** [saadeghi/daisyui#1212]
Hi there

I am using w-full for my select, just like I did for an input component, however the select has overflow.

https://play.tailwindcss.com/Q44e9ogP4m

The input component on the other hand works well in a similar use case.

Can you please advise what I'm missing.

Thank you in advance.

**Comment by saadeghi** [comment]
Use `grow` instead of `w-full`:
https://play.tailwindcss.com/q6Wk8tpFJ6

**Comment by Mashiane** [comment]
Thank you so much.
