### ISSUE TITLE
Removing hover when we are using the menu class

### ISSUE THREAD

**Issue by ricardoseb** [saadeghi/daisyui#1213]
Hello,

I would like to know if it's possible to remove hover when we are using the menu class, for example remove this:
![image](https://user-images.githubusercontent.com/31752537/194451120-000f77fc-6abd-4ec6-8709-6b3450078a8a.png)

I have been adding hover:bg-none, but no success.
`<ul class="menu menu-horizontal rounded-box hover:bg-none">`

I'am using tailwind version: 3.1.8
Thanks!!

**Comment by saadeghi** [comment]
Something like `hover:bg-transparent` can be used:
```html
<ul class="menu menu-horizontal rounded-box hover:bg-none">
  <li><a class="hover:bg-transparent">Link</a></li>
  <li><a class="hover:bg-transparent">Link</a></li>
  <li><a class="hover:bg-transparent">Link</a></li>
</ul>
```
https://play.tailwindcss.com/jQkrqWAKN0
