### ISSUE TITLE
Invalid CSS when using md:table class

### ISSUE THREAD

**Issue by rpungello** [saadeghi/daisyui#1214]
I am running into an issue with the CSS being generated by Tailwind when daisyUI is installed if the source files use the class md:table.

I was able to reproduce this by loading Tailwind into a blank directory as outlined [here](https://tailwindcss.com/docs/installation), installing daisyUI as outlined [here](https://daisyui.com/docs/install/), then adding a <table class="hidden md:table"></table> tag to the index.html file provided by the Tailwind setup instructions

End result of index.html shown below
```
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="/dist/output.css" rel="stylesheet">
</head>
<body>
  <h1 class="text-3xl font-bold underline">
    Hello world!
    <table class="hidden md:table"></table>
  </h1>
</body>
</html>
```

With this in place, building the output CSS file produces the following.
```
.md\:table :where(tbody th, tbody td) {
    --tw-bg-opacity: 1;
    background-color: hsl(var(--b1) / var(--tw-bg-opacity));
  }

   {
    border-top-left-radius: 0.5rem;
    border-top-right-radius: 0.5rem;
    border-bottom-left-radius: 0.5rem;
    border-bottom-right-radius: 0.5rem;
  }
```

Notably, there is no selector in place for the block with 4 border-radius definitions.
This triggers a warning when using a CSS minifier.
Removing daisyUI from the Tailwind plugins results in the following for the md:table selector
```
@media (min-width: 768px) {
  .md\:table {
    display: table;
  }
}
```
There is no selector-less block after it, leading me to believe something within daisyUI is causing something to go wrong here, I just can't figure out what.

**Comment by saadeghi** [comment]
The problem is, the `table` class on daisyUI is not responsive. In fact, not all class names are responsive. Only the ones with `responsive` label (you can see on the [docs](https://daisyui.com/components/table/)) are responsive and can accept `sm:`, `md:`, etc.

So if you want to conditionally show a table or hide it, I would suggest to put it in a `<div class="hidden md:block">`
