### ISSUE TITLE
Dropdown and Tooltip missing one direction

### ISSUE THREAD

**Issue by brunocalou** [saadeghi/daisyui#1218]
Hello guys, I have a use case that is not possible to achieve right now.

The dropdown component has `top`, `left`, and `right` directions. The `bottom` is the default one. It works for most use cases but fails when I need the dropdown to appear on top on mobile and bottom on desktop. That's because once I add `dropdown-top`, there is no class to override the `top` style, like `lg:dropdown-bottom`. According to the tailwind docs, [there is no way to target a single breakpoint.](https://tailwindcss.com/docs/responsive-design#targeting-a-single-breakpoint)

The same happens with the Tooltip, but the `top` direction is missing.

If it makes sense, I can open a PR with the change.

**Comment by NikarashiHatsu** [comment]
I just noticed that `dropdown-bottom` modifier is missing.
It would really helpful to have such modifier.
