### ISSUE TITLE
Is it possible to stretch / grow the tabs to fit available width?

### ISSUE THREAD

**Issue by Mashiane** [saadeghi/daisyui#1224]
Hi there

The attached image bears reference (for clarity). Its made from copying parts of the doc examples.

![StretchedTabs](https://user-images.githubusercontent.com/5799306/194730088-13c875f6-4eb5-40f1-ba95-f35b733f4451.png)

Is it possible to stretch the tabs to fit equally? 

Thank you so much.

**Comment by Chandraprakash-Darji** [comment]
Give to flex-1 to all the tabs

**Comment by saadeghi** [comment]
as @Chandraprakash-Darji said.  
`grow` class also works: https://play.tailwindcss.com/p5L6YmQf4f

**Comment by Mashiane** [comment]
Thank you so much..
