### ISSUE TITLE
Bug: Checkbox in rtl is rotate

### ISSUE THREAD

**Issue by amirsarafian** [saadeghi/daisyui#1233]
checkbox with rtl config is rotate direction: 
![Screenshot 2022-10-11 111951](https://user-images.githubusercontent.com/22930592/195031802-455b4cc9-6c05-487c-88be-bce521259cc1.png)

**Comment by Omer-Shahar** [comment]
The problem occurs with the element `<input type="checkbox" checked="checked" className="checkbox" />`
with `rtl: true` in the config file and `direction: rtl` on the `main` element.
