### ISSUE TITLE
How can I make the Stat to be responsive / vertical for small devices?

### ISSUE THREAD

**Issue by Mashiane** [saadeghi/daisyui#1236]
Hi there

I cant seem to make the Stat reponsive. Here is the tailwind play... Im trying to make it vertical for small devices

https://play.tailwindcss.com/0QWV1BN9Gb?size=470x720

![stat](https://user-images.githubusercontent.com/5799306/195363891-13fd98e1-f97a-442e-8d06-f81bbc052c9f.png)

Thanks in advance

**Comment by daveteu** [comment]
```<div class="stats stats-vertical sm:stats-horizontal shadow">```

**Comment by Mashiane** [comment]
Sorry, please bear with me, just to confirm, your solution works, but shouldnt this be the other way round? Can you please clarify?
Horizontal is from left to right whilst vertical is top to bottom or vice versa.

![image](https://user-images.githubusercontent.com/5799306/195470663-9c9568f6-add1-46e0-94ae-98aa2f885601.png)

So **stats-vertical** means top to bottom (my request) whilst **sm:stats-horizontal** means left to right (the opposite)

![image](https://user-images.githubusercontent.com/5799306/195470706-a428ce49-9a50-401b-a349-d98972e047ed.png)

<div class="stats stats-vertical sm:stats-horizontal shadow">

Shouldnt the classes be stats-horizontal (left to right for anything else) and then sm:stats-vertical (top to bottom) for small devices)?

**Comment by Mashiane** [comment]
Anyway I just noted this, https://github.com/saadeghi/daisyui/issues/807 and am realizing what my problem is, I guess I have to wait for the next update. Thanks you.

**Comment by saadeghi** [comment]
> Shouldnt the classes be stats-horizontal (left to right for anything else) and then sm:stats-vertical (top to bottom) for small devices)? Confusing...

`sm:` prefix on Tailwind CSS means "screens larger than sm (640px)"  
So, in `<div class="stats stats-vertical sm:stats-horizontal">` it means:
- it's `vertical` by default
- it will be `horizontal` on screens larger than 640px
