### ISSUE TITLE
How can I make the drawer have its own vertical scroll bar?

### ISSUE THREAD

**Issue by Mashiane** [saadeghi/daisyui#1237]
Hi there

The demo drawer spans items across, how can I make it have its own scroll bar. If I use x-clip, its using the document scrollbar, which is not favourable.

https://play.tailwindcss.com/XCGtFKSDYf

Thank you in advance

**Comment by saadeghi** [comment]
Remove that `overflow-y-auto` from `menu`: https://play.tailwindcss.com/Nsol0HBFTY

**Comment by Mashiane** [comment]
Thank you, is it possible for the scroll bar to be "inside" the drawer and not on the body?

![image](https://user-images.githubusercontent.com/5799306/197089752-8e887527-eb13-4778-8203-e39e44e7e042.png)

**Comment by saadeghi** [comment]
Sure. Here's an example: https://play.tailwindcss.com/lfIx166zzt
