### ISSUE TITLE
Can't change background of any table elements

### ISSUE THREAD

**Issue by Frohus** [saadeghi/daisyui#1239]
I'm unable to change background of any table elements when using .table class in table element.
I've tried changing with tailwind classes and directly in CSS in every table element - thead, tr, th, tbody. Nothing works.

I've checked devtools but I can't see anything there that would be blocking background change, the class changing the background also isn't crossed out. 
Tried in chrome, brave and firefox with the same result.

**Comment by saadeghi** [comment]
The whole table doesn't have a background color. Every cell has.  
So the easiest way would be a class name like `[&_*]:bg-primary` on `<table>`.  
Example: https://play.tailwindcss.com/MCewKL2h7O

Let me know if you have any questions

**Comment by Frohus** [comment]
@saadeghi this changes the background for the whole table, I raised the issue when I wanted to change the header's background only as the default one blends with my page background so it doesn't stand out enough. 
It would also be nice to be able to change the color of zebra rows

**Comment by Frohus** [comment]
For those annoyed by this, I've overcome this by adding the following CSS.

```
.table :where(tbody th,tbody td), .table :where(thead,tfoot) :where(th,td) {
    background-color: inherit;
}
```
