### ISSUE TITLE
How to close/open modal programmatically

### ISSUE THREAD

**Issue by workingxx92** [saadeghi/daisyui#124]
Hello,
How to open/close modal programmatically

Thanks

**Comment by saadeghi** [comment]
There are 2 types of modal: https://daisyui.com/components/modal/  
First one works with URL hash (anchor link) so you if you change the URL using JS, you can open/close the modal.  
Second one works with a hidden checkbox, so you can check/uncheck that checkbox to open/close the modal.

Please let me know if you have any questions.

**Comment by workingxx92** [comment]
Hi @saadeghi 
It's not show modal programmatically
<img width="663" alt="Screen Shot 2021-08-09 at 4 46 45 PM" src="https://user-images.githubusercontent.com/86577210/128688132-a1305d06-d360-4367-88b2-edb5214c7e18.png">

Code:
https://play.tailwindcss.com/9VIa7IYlHj

**Comment by saadeghi** [comment]
@workingxx92 I'm not sure if I understand you correctly.  
If you you want the modal to be open by default, you just need to add `checked` to checkbox:
```html
<input type="checkbox" id="my-modal-2" class="modal-toggle" checked>
```
If you want to check/uncheck the checkbox with JS:
```js
document.querySelector('#my-modal-2').checked = true;
document.querySelector('#my-modal-2').checked = false;
```

**Comment by vuejstime** [comment]
is there any way to toggle a class to open and close modal? i think it's much more easier with js frameworks

**Comment by saadeghi** [comment]
@vuejstime Good idea. I will add it by tomorrow.

**Comment by pineshmenat** [comment]
@saadeghi could you help me on how can I use this class modal-open to programmatically open close modal?

Thank you in advance

**Comment by pineshmenat** [comment]
@saadeghi thank you for your time,I realised after using model-open I did not add onclick method on label.

**Comment by MahdiGhanati** [comment]
Hello I have two modals (I use diasyui component) for close and open others:

onclick="my_modal_2.showModal(); my_modal_1.close()"

**Comment by gregorvand** [comment]
riffing on what @MahdiGhanati says, in a svelte component you can therefore define a function like:

```
function closeModal() {
    const modal = document.getElementById('my_modal');
    modal.close() 
  }
```

and call that from another function (e.g. when a successful action completes) or attach to an element with native svelte `on:click`

**Comment by haissamtariqzaman** [comment]
> Hello I have two modals (I use diasyui component) for close and open others:
> 
> onclick="my_modal_2.showModal(); my_modal_1.close()"

Thanks this works :)
