### ISSUE TITLE
[FEATURE]: Extend no themes by default

### ISSUE THREAD

**Issue by AbhijithGanesh** [saadeghi/daisyui#1251]
Currently DaisyUI extends themes which result in graying(by this I mean appearance of a gray BG) out of DOM elements, I suggest, we make it optional and extend no themes by default

**Comment by saadeghi** [comment]
So if there are no themes by default, every current existing daisyUI project will need to manually add themes to their config.  
I'm pretty sure the majority of developers don't want this. They want to install the package and get everything right away. So I don't think applying this breaking change will be a good idea.  
However if someone doesn't need the themes or wants custom themes, it can be done on the config file.
