### ISSUE TITLE
Bug: vertical alignement in menu

### ISSUE THREAD

**Issue by hug0git** [saadeghi/daisyui#1252]
Hi  👋

The elements in the menu aren't aligned correctly. I don't know how to fix that.

![image](https://user-images.githubusercontent.com/16294883/196251305-cb3a159f-df60-464c-93c9-f9ab4ff1ac38.png)

```jsx
<div className="navbar py-2 lg:py-8 px-4 lg:px-56 bg-base-100 fixed top-0">
   <div className="navbar navbar-end">
      <ul className="menu menu-horizontal font-bold space-x-6">
         <li>
            <a>Features</a>
         </li>   
         <li>
            <a>Plateform</a>
         </li>
         <li>
            <a>FAQ</a>
         </li>
      </ul>
   </div>
</div>
```

Thanks in advance.
Hugo.

**Comment by saadeghi** [comment]
Your code looks good here: https://play.tailwindcss.com/0uBhOqc3Ew
Are you sure there aren't any other CSS affecting your elements?

**Comment by hug0git** [comment]
Ok, I just find the issue. There was a `space-y-2` in my css that affect the `menu-horizontal`. Thanks for the response.
