### ISSUE TITLE
Pagination in tfoot is placed at the top

### ISSUE THREAD

**Issue by Mashiane** [saadeghi/daisyui#1253]
Hi

I am trying to create a "card" with some kind of toolbar and then a table.

https://play.tailwindcss.com/1atdGNlByr

I was putting a pagination component at the tables footer, this however gets shown at the top of the table.

Can you kindly advise.

**Comment by saadeghi** [comment]
This is invalid HTML. you can't put a `<div>` directly inside a `<tr>`. Valid elements inside a `<tr>` are `<td>` or `<th>`
