### ISSUE TITLE
How can I get the button group to have circle buttons?

### ISSUE THREAD

**Issue by Mashiane** [saadeghi/daisyui#1254]
Hi

I'm trying to apply the btn-circle class to the buttons on my pagination component.

https://play.tailwindcss.com/aXQNEu1dmr

Is it possible to archieve circular buttons with it?

Thanks a lot

**Comment by saadeghi** [comment]
Well, when we use button group, the buttons inside will lose their border radius, except the fist and last button, so it looks like all buttons are next to each other. That being said, the middle buttons can not be circle at all.  

But if you want something like this: 
<img width="146" alt="1" src="https://user-images.githubusercontent.com/7342023/196387380-a098c715-b81a-4c3b-bc29-eeec3f4a89f3.png">
you can do it by changing `--rounded-btn` value with a class name like this: `[--rounded-btn:2rem]`. Example: https://play.tailwindcss.com/jiTgJoXdFu

Let me know if you have any questions

**Comment by Mashiane** [comment]
Thanks Saadeghi, I will keep this in mind.

**Comment by saadeghi** [comment]
What do you think about this idea: https://github.com/saadeghi/daisyui/discussions/1572
