### ISSUE TITLE
collapse visibility: collapse

### ISSUE THREAD

**Issue by Syiana** [saadeghi/daisyui#1261]
3.2.0 - 2022-10-19
Add new collapse utility for visibility: collapse https://github.com/tailwindlabs/tailwindcss/pull/9181

daisyui collapse is not visibility by default now

**Comment by szluyufeng** [comment]
I got the same problem. Have you figure it out?

**Comment by Syiana** [comment]
@szluyufeng  

I fixed it with this for now:

@layer utilities {
  .collapse {
    visibility: visible;
  }
}

**Comment by szluyufeng** [comment]
> 

@Syiana Thanks, it works. But the collapse can not be collapsed now.

**Comment by saadeghi** [comment]
Thanks for reporting this.  
Fixed in version `2.33.0`: https://play.tailwindcss.com/6H2smF4tRz?file=config

Really hard to deal with it when a new version of Tailwind CSS adds a new class name that already exists in daisyUI 🤐  
It's a minor release for Tailwind but I can't change the class name to something else because that would break all existing projects.

**Comment by Syiana** [comment]
> > 
> 
> 
> 
> @Syiana Thanks, it works. But the collapse can not be collapsed now.

I do this in vue anyway, that's why it works for me:

`<template>
  <div class="collapse border rounded-xl">
  <input type="checkbox" v-model="checked"/>
  <div class="flex collapse-title text-xl font-medium p-4">
    {{data.title}}
      <Icon class="ml-auto transition ease-in-out" :class="{ 'rotate-90': checked }" name="ri:arrow-right-s-line" size="24"/>
  </div>
  <div class="collapse-content">
    <p>{{data.description}}</p>
  </div>
</div>
</template>

<script setup>
defineProps({
  open: { type: Boolean, default: false },
  data: Object,
  index: { type: Number, default: 0 }
})

const checked = ref(false)
</script>`

**Comment by saadeghi** [comment]
@zed-wong Why your `.collapse` has `!important`?  
Because I'm pretty sure nothing in Tailwind has `!important` [by default](https://tailwindcss.com/docs/configuration#important). 🤔

**Comment by Koaieus** [comment]
I would like to use both the DaisyUI `collapse` class and the Tailwind `collapse` class in my project, how would I go about separating these? Can I rename one of them somehow?

**Comment by dawmsi** [comment]
![image](https://github.com/saadeghi/daisyui/assets/96021986/9fada2f8-69e6-43e8-83a4-f2ee950ed987)

**Comment by Goondrious** [comment]
if you're seeing this in recent versions, you might be using `important: true` in tailwind config.

You can manually override using the same method daisyui does, but in your own globals.css:

```
.collapse:not(td):not(tr):not(colgroup) {
    visibility: visible !important;
  }
```
