### ISSUE TITLE
no way to override --tab-bg in theme config

### ISSUE THREAD

**Issue by pdkn** [saadeghi/daisyui#1262]
--tab-bg is hardcoded in the tab component ```--tab-color: hsla(var(--bc) / var(--tw-text-opacity, 1));```. currently, to override it I've had to do something like  ```'!bg-gray-100': isActive```. Any chance --tab-bg can be hosted up to be configurable ( for the active and inactive states? thoughts before I look at making a PR?

**Comment by pdkn** [comment]
just seen how you do it in the docs - interesting! ```class="tab tab-lifted tab-active [--tab-bg:hsl(var(--n))] [--tab-color:hsl(var(--nc))] [--tab-border-color:hsl(var(--n))]"```

**Comment by saadeghi** [comment]
As you mentioned, those CSS variables can be customized using Tailwind CSS arbitrary class names.  
Also you can customize them in the config like this: https://play.tailwindcss.com/KVUr6JBBy0?file=config
```js
daisyui: {
  themes: [
    {
      light: {
        ...require("daisyui/src/colors/themes")["[data-theme=light]"],
        ".tab": {
          "--tab-bg": "darkorange",
          "--tab-color": "white",
          "--tab-border-color": "yellow",
        }
      },
    },
  ],
},
```
