### ISSUE TITLE
Opacity on alert

### ISSUE THREAD

**Issue by Hakamate** [saadeghi/daisyui#127]
![image](https://user-images.githubusercontent.com/33601556/129003046-af9288c4-c6d6-4831-b9e2-405a388134c2.png)

Hello, I see something weird with alert components.

They have an opacity affected on them. 
So we can't really use them as notifications (as fixed position).

Maybe using a system like bg-red-500 can solve it ?

**Comment by saadeghi** [comment]
@Hakamate I am planning to apply some color changes for next major version to fix this.  
Until then, you can customize the colors using utility classes like `bg-` and `text-`:
```html
<div class="alert bg-success text-base-content">
```
Example: https://play.tailwindcss.com/z4npFaMXey
