### ISSUE TITLE
responsive-dropdown menu：dropdown menu not showing

### ISSUE THREAD

**Issue by Youngzx88** [saadeghi/daisyui#1271]
https://daisyui.com/components/navbar/#responsive-dropdown-menu-on-small-screen-center-menu-on-large-screen
If I don't give the navbar a fixed height I can't see the dropdown.
like this:
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/56037320/197347631-5d047cac-98fd-47f6-b8e5-24f5e7e7c266.png">
when i give outside div "h-64" ,it looks like after:
<img width="1499" alt="image" src="https://user-images.githubusercontent.com/56037320/197347651-2b689e77-5f01-4438-8dc5-3c946eba17c2.png">

**Comment by Youngzx88** [comment]
i use in another normal div,it can works，Maybe it conflicts with one of my attributes?
Header is the common components copy in https://daisyui.com/components/navbar/#responsive-dropdown-menu-on-small-screen-center-menu-on-large-screen
```html
<Header></Header>
    <div className='relative w-full'>
      <img className='hidden lg:w-full lg:block' src="https://www.magelesi.cn/assests/applicationField/1-%E9%A6%96%E5%9B%BEcoretech%402x.jpg" alt="" />
      <div className="bgImage_applicationField bg-cover w-full">
        <div className='lg:mx-auto lg:absolute w-full lg:top-0 lg:left-0'>
          <div className="container mx-auto w-full">
            <div className='lg:pt-[10vw] p-20'>
              <div className='mx-auto text-[12px] lg:text-[22px] lg:mx-auto lg:w-30'><img src="https://www.magelesi.cn/assests/applicationField/coretectTitle.png" alt="" /></div>
              <div className="mx-auto mt-4 opacity-[0.7] text-white text-[12px] lg:mt-8 lg:text-[22px] lg:text-white lg:opacity-[0.7] lg:mx-auto lg:w-[650px] lg:ml-0">公司拥有强大的科技研发能力，核心技术包括纳米材料和MEMS芯片两方面，经多年沉淀积累，处于行业领先水平，解决了多项卡脖子技术，拥有多项专利。主要产品均有核心技术加持，拥有显著的成本性能竞争力和广阔的市场前景</div>
            </div>
          </div>
        </div>
      </div>
    </div>
```

**Comment by saadeghi** [comment]
I can't be sure what's the issue unless I see your code. Because [this is](https://play.tailwindcss.com/IzCZPP8Ksy) the same example from docs and it works as expected.
