### ISSUE TITLE
Is it possible to indicate the "off" color for toggle?

### ISSUE THREAD

**Issue by Mashiane** [saadeghi/daisyui#1273]
Hi there

When off, the toggle is gray..

![image](https://user-images.githubusercontent.com/5799306/197380804-fb22ef30-a8ee-40f2-a1bd-f24d53549466.png)

Is it possible to make it another color, for example, i'd like to set it to "red" when off and green when on.

Is it also possible to use other colors besides primary, accent and secondary as per docs?

Thank you so much!.

**Comment by saadeghi** [comment]
Yes you can.  
Here's an example: https://play.tailwindcss.com/cSYwUcZxrg
```html
<input
  type="checkbox"
  class="toggle bg-red-600 checked:bg-blue-600 checked:border-blue-600"
>
```

**Comment by Mashiane** [comment]
Thank you so much
