### ISSUE TITLE
Bug: RTL Select has wrong padding

### ISSUE THREAD

**Issue by Omer-Shahar** [saadeghi/daisyui#1275]
When adding a select element in RTL mode, the padding does not change accordingly:
![image](https://user-images.githubusercontent.com/38870042/197407881-412b0ebc-bcb5-4e1c-a87f-949a27ed2bdd.png)

```
<select className="select-bordered select select-xs w-full max-w-xs">
    <option>דוגמה לבעיה בעיצוב האלמנט</option>
</select>
```

The problem is in [this file](https://github.com/saadeghi/daisyui/blob/master/src/utilities/unstyled/select.css).
`pl-[]` and `pr-[]` should be replaced with `padding-inline-start` and `padding-inline-end`.
An even better option would be to add the tailwind classes `pis-[]` and `pie-[]` (or some other name, [as suggested here](https://github.com/tailwindlabs/tailwindcss/discussions/1483)), as they are necessary for a bidirectional UI.

**Comment by saadeghi** [comment]
Fixed in `2.34.0`  
Thank you!
