### ISSUE TITLE
Remains height when dropdown is hidden

### ISSUE THREAD

**Issue by banakemi** [saadeghi/daisyui#1276]
hi,maintainer!
I am using `.dropdown` with a small modal, but when I hide it, the height of the element remains and so does the scrollbar.
The CSS defining the dropdown is `visibility:hidden`, so can I submit a pull request with an additional definition of `display:none` (&`block`)?

**Comment by saadeghi** [comment]
I couldn't reproduce this. Can you please provide a [Tailwind Play](https://daisyui.com/tailwindplay/) page with your example code?

**Comment by banakemi** [comment]
hi,@saadeghi 
Thanks for the comment.
`display:none` to `dropdown-content` shows that the modal is smaller.
https://play.tailwindcss.com/HpiODsmxep
and screenshot
<img width="534" alt="dropdown-contentHeight" src="https://user-images.githubusercontent.com/9716661/198322410-179bd459-43e7-415a-9f21-f530d48c025f.png">

**Comment by saadeghi** [comment]
Thanks for the example. By default, it is expected for `modal-box` content to have a scroll on overflow.  
In your case you can change this behavior by adding `overflow-y-visible` class to `modal-box`
```diff
- <div class="modal-box">
+ <div class="modal-box overflow-y-visible">
```

Let me know if you have any questions

**Comment by banakemi** [comment]
@saadeghi 
Thanks for the comment.
I'm using it inside an iframe with a fixed modal height.
What should I do in that case?
It's not an iframe, but here's what it looks like
https://play.tailwindcss.com/9Mr3O6NZOM

**Comment by banakemi** [comment]
I would like to do this
```
.dropdown .dropdown-content{
    @apply hidden;
  }

  .dropdown:not(.dropdown-hover):focus-within .dropdown-content {
    @apply block;
  }
```

**Comment by saadeghi** [comment]
I won't suggest using iframes in the first place because there's no direct way for elements inside and outside an iframe to affect eachother so the container will never know the size of content inside the iframe.  

Isn't there any other way to show the content?

**Comment by banakemi** [comment]
It is intended to be embedded in someone else's website, so an iframe must be used.
This is to prevent CSS from interfering with each other.

**Comment by saadeghi** [comment]
I'm not sure... you might want to hardcode the height of `modal-box` if it's always a fixed height. Otherwise, you might be able to dynamically set the height of iframe using JS. I don't think there's a CSS way to get the height of content from an iframe.

**Comment by banakemi** [comment]
https://play.tailwindcss.com/eA2OwRWRtv
↑For example, try setting the height of the iframe you are previewing to 200px as shown in the image
Scrolling is displayed.
If `display:none`, it will not be displayed.
<img width="1802" alt="scrollBar" src="https://user-images.githubusercontent.com/9716661/198843065-faf5533f-a982-4ddb-9036-9f2930f05835.png">

**Comment by saadeghi** [comment]
At this point I'm a little confused about your goal.  
Do you want the dropdown content from an iframe to overflow out of the iframe? because that's impossible.

**Comment by banakemi** [comment]
> Do you want the dropdown content from an iframe to overflow out of the iframe?
No, it is not.
https://github.com/saadeghi/daisyui/issues/1276#issuecomment-1293644675
The problem is that the Dom height is still there and the scrollbar shows up when the DOM is not displayed because `visivility:hidden` is set.
I think it is correct that there is no Dom height when not displayed.
