### ISSUE TITLE
Filling space between slider and start of element with a different color in form-range 

### ISSUE THREAD

**Issue by pooyaEst** [saadeghi/daisyui#128]
Hi pouya thanks for this great work!

i think it would be cool if there was an option to make the space between slider and start of the range element filled with a different color.

kinda like this : 
![Slider](https://i.ytimg.com/vi/3Eb6FtjkZ_k/maxresdefault.jpg)

if the ballon effect also could be added that would be even more awesome.

**Comment by saadeghi** [comment]
I wish I could 😔  
Unfortunately, the only things we can style for a input range are `-webkit-slider-thumb` and `-webkit-slider-runnable-track` (for Firefox: `-moz-range-thumb` and `-moz-range-track`) so if you want to fill half of the range with a different color, there are 3 options:
1. Use the browser's default style
2. Set a custom linear gradient as the background and change the position of gradient with JS everytime the value of input changes.
3. Making a custom range slider with custom divs using JS

Please let me know if you have any questions.
