### ISSUE TITLE
Better documentation for modals

### ISSUE THREAD

**Issue by Bandes** [saadeghi/daisyui#129]
I have been trying to follow the documentation for the modal component, but when I add the markup given in the example I cannot get a modal to appear - all of my modal content just appears directly as part of the page content. Is there javascript that I need to link, or another trick to it?

**Comment by saadeghi** [comment]
@Bandes There is no trick and no JS dependency.
Here's the the same example on Tailwind Play: https://play.tailwindcss.com/kvjZQeGpbG  
Please make sure your CSS file is building correctly and purging the correct files.

If you could provide a small example (Github repo, Codepen, etc...) so I can reproduce the problem, that would be great.

**Comment by Bandes** [comment]
Thank you - I am pretty sure this was all just user error. It is working now after I double-checked my config and recompiled a few times. Sorry for the n00b ticket :)
