### ISSUE TITLE
Is there a way to control the over-lapping of the select items?

### ISSUE THREAD

**Issue by Mashiane** [saadeghi/daisyui#1291]
![SelectOverlap](https://user-images.githubusercontent.com/5799306/198850512-c5fc500d-e665-4a4d-ba6e-b0db5a865cb8.jpg)

**Comment by saadeghi** [comment]
I don't know what you mean by overlapping, but:
1. There's no way to style the select items using CSS (unless a JS library creates divs and spans for each item on-demand)
2. Select options won't display like this on a mobile device. They will have large iOS UI or android UI.

Let me know if you have any questions
