### ISSUE TITLE
How can I add a value percentage inside the progress component?

### ISSUE THREAD

**Issue by Mashiane** [saadeghi/daisyui#1295]
Hi there

How can I have a value shown as text inside the progress component?

https://play.tailwindcss.com/G9CxJJC3sG

More like the progress radial?

Thanks.

**Comment by saadeghi** [comment]
We can't put content inside a `<progress>` element. But we can overlap a div on the progress.  

For example:  
https://play.tailwindcss.com/rXGWeslP3k
```html
<div class="m-20 grid place-items-center">
  <progress class="progress col-start-1 row-start-1 w-100 h-10 bg-[#ff1d58] [--rounded-box:0]" value="40" max="100"></progress>
  <div class="col-start-1 row-start-1 z-20">40%</div>
</div>

```

**Comment by Mashiane** [comment]
Wow, thank you so much.

This will do a great deal.
