### ISSUE TITLE
Feature request: Provide the ability to set light and dark themes at runtime

### ISSUE THREAD

**Issue by akkie** [saadeghi/daisyui#1296]
Hi,

I would like to allow the user to choose between different dark and light themes. So if a user has the dark mode enabled, he/she/it can choose between different dark themes and if a user has light mode enabled, he/she/it can choose between different light themes. The same as GitHub allows under Settings/Appearance.

For that I suggest to provide a `data-light-theme` and a `data-dark-theme` attribute as well to the existing `data-theme`. Would that be possible?

Best regards,
Christian

**Comment by saadeghi** [comment]
I think this is pretty much possible right now.  

Scenario:  
Let's say we use 4 of [daisyUI themes](https://daisyui.com/docs/themes/) on a site:
- `light`
- `dark`
- `cupcake` (another light theme)
- `night` (another dark theme)

So by default, the user will see `light` or `dark` themes based on their OS preferences.  
Then user picks an alternative dark theme (`night`) and we put their choice in `<html data-theme="night">` The user will see the chosen theme (`night`) as expected.

In fact, daisyUI doesn't care if the a is is dark or light.  
Any theme can be dark or light or anything based on its colors and user will see any theme we set for `data-theme`.  

The only catch is, daisyUI also [sets one of the dark themes as `@media (prefers-color-scheme: dark)`](https://unpkg.com/browse/daisyui@2.36.1/dist/themes.css) for when the user never picked any themes yet and we just want to show the dark/light based on their OS preferences. And that default dark theme can be changed using [the `darkTheme` config](https://daisyui.com/docs/config/).

That being said, I think there's no need for two `data-light-theme` and `data-dark-theme` attributes.

Let me know if you have any questions.

**Comment by akkie** [comment]
The idea is that the user can choose a light and dark theme at the same time. And if he switches the light or dark mode on the system, the preferred theme for that specific mode should be chosen. I think this is currently not possible.

**Comment by saadeghi** [comment]
I understand.  
This could be added in the future but currently adding this feature will double the CSS size of themes.  
Currently [all daisyUI themes](https://unpkg.com/browse/daisyui@2.36.1/dist/themes.css) are available on runtime and that's `25kb` (`4kb Gzip`) unless the developer [removes unused themes](https://daisyui.com/docs/themes/#-1).

It's not hard to make it happen tho. We just need to duplicate all themes CSS inside `@media (prefers-color-scheme: dark)` like this:
```css
[data-light-theme=THEME1] {
  /* colors */
}
[data-light-theme=THEME2] {
  /* colors */
}
/* etc. */

@media (prefers-color-scheme: dark) {
  [data-dark-theme=THEME1] {
    /* colors */
  }
  [data-dark-theme=THEME2] {
    /* colors */
  }
  /* etc. */
}
```
See this working CSS example: https://play.tailwindcss.com/nJCLmgyPHO?file=css

But the challenges for adding this to daisyUI would be:
1. Breaking change for existing daisyUI users
2. File size

Solution for what you want:  
You can manually copy theme color variables [from here](https://unpkg.com/browse/daisyui@2.36.1/dist/themes.css) and use them like this: https://play.tailwindcss.com/G6059j0zJ0?file=css
In above link, I made `light` and `cupcake` themes available for light mode and I made `dark` and `night` themes available for dark mode.
