### ISSUE TITLE
Tooltip can't wrap avatar

### ISSUE THREAD

**Issue by spencerjsmall** [saadeghi/daisyui#1299]
Tooltip does not appear when wrapping a placeholder avatar. Any advice?

<img width="726" alt="Screen Shot 2022-10-31 at 12 32 18 PM" src="https://user-images.githubusercontent.com/61337412/199093861-b865da88-e1f6-48f4-8890-48b5c9607b48.png">

**Comment by esoteloferry** [comment]
I have this issue as well , @spencerjsmall  could you sort it out?

**Comment by zAlweNy26** [comment]
@esoteloferry if you are still facing this issue, the problem is the `overflow: hidden` of the `avatar-group`. Try adding a `overflow-visible` in the same class of `avatar-group`.
Here there is an [example](https://play.tailwindcss.com/XFt6eRDCC3).

**Comment by esoteloferry** [comment]
@zAlweNy26 it worked !, thank you
