### ISSUE TITLE
some issue with checkbox

### ISSUE THREAD

**Issue by kknono** [saadeghi/daisyui#1301]
hello,
  when use checkbox  `<input type="checkbox" checked="true" class="checkbox " />`  will appear border-color 
<img width="74" alt="截屏2022-11-01 16 51 43" src="https://user-images.githubusercontent.com/2398446/199195688-48ae9454-d22b-41f4-aeca-011180bc8fd0.png">

it looks different from example  
how to remove default border-color 

thx

**Comment by saadeghi** [comment]
Are you using any other CSS packages or plugins that may apply styles to the checkbox? Like `@tailwindcss/forms`?

**Comment by kknono** [comment]
thx.
