### ISSUE TITLE
Error: "declare module 'daisyui';"

### ISSUE THREAD

**Issue by PterPmnta** [saadeghi/daisyui#131]
I had created a project in Angular 12 and will decide to install this CSS component library based in Tailwind, for learning too. But this has been really weird, I have been following the steps, but can't work. A message to appear in my VS Code, say this

`Test "npm i --save-dev @types/daisyui" if exists or add new file with the statement (.d.ts), and this must include "declare module 'daisyui'".`

`'c:/Users/peter/Documents/GitHub/SolarApp/node_modules/daisyui/index.js' has a type "any" as an implicit way.`

`No declaration file was found for module 'daisyui'.`

**Comment by saadeghi** [comment]
@PterPmnta do you get this error when you simply `npm  I daisyui`?  
Can you please make a small GitHub repo so I can reproduce this problem?

**Comment by PterPmnta** [comment]
> @PterPmnta do you get this error when you simply `npm i daisyui`?
> Can you please make a small GitHub repo so I can reproduce this problem?

Yes, I install using that command, even remove and reinstall, but still appear the error.

I started a project with angular 11.X new project and clean, the first I did was update angular, with the intention that Tailwind was supported by defect, and after that, I found this library and try to install it. 

Is possible for the update in my project to generate this error?

What recommended you, create another project with angular 12.X by default.

**Comment by PterPmnta** [comment]
> @PterPmnta do you get this error when you simply `npm i daisyui`?
> Can you please make a small GitHub repo so I can reproduce this problem?

Yes, I install using that command, even remove and reinstall, but still appear the error.

I started a project with angular 11.X new project and clean, the first I did was update angular, with the intention that Tailwind was supported by defect, and after that, I found this library and try to install it. 

Is possible for the update in my project to generate this error?

What recommended you, create another project with angular 12.X by default.

**Comment by PterPmnta** [comment]
> @PterPmnta do you get this error when you simply `npm i daisyui`?
> Can you please make a small GitHub repo so I can reproduce this problem?

Yes, I install using that command, even remove and reinstall, but still appear the error.

I started a project with angular 11.X new project and clean, the first I did was update angular, with the intention that Tailwind was supported by defect, and after that, I found this library and try to install it. 

Is possible the update in my project generate this error?

What recommended you, create another project with angular 12.X by default.

**Comment by saadeghi** [comment]
@PterPmnta Ok, I started a new Angular project:
```
```

**Comment by saadeghi** [comment]
@PterPmnta Ok, 
1. I started a new Angular project:
```
ng new my-app
```
2. Installed Tailwind and daisyUI:
```
npm install -D tailwindcss daisyui
```
3. Added `tailwind.config.js`
```js
module.exports = {
  purge: {
    content: [
      './src/**/*.{html,ts}',
    ]
  },
  plugins: [
    require('daisyui')
  ],
};
```
4. added these to styles.css
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```
5. Run app:
```
npm run start
```

And everything works perfectly.  
Here's the source: https://github.com/saadeghi/daisyui/tree/master/examples/angular
It's Angular version `12.2.0` I'm not sure about other versions but there shouldn't be a problem.

**Comment by PterPmnta** [comment]
> @PterPmnta Ok,
> 
> 1. I started a new Angular project:
> 
> ```
> ng new my-app
> ```
> 
> 1. Installed Tailwind and daisyUI:
> 
> ```
> npm install -D tailwindcss daisyui
> ```
> 
> 1. Added `tailwind.config.js`
> 
> ```js
> module.exports = {
>   purge: {
>     content: [
>       './src/**/*.{html,ts}',
>     ]
>   },
>   plugins: [
>     require('daisyui')
>   ],
> };
> ```
> 
> 1. added these to styles.css
> 
> ```css
> @tailwind base;
> @tailwind components;
> @tailwind utilities;
> ```
> 
> 1. Run app:
> 
> ```
> npm run start
> ```
> 
> And everything works perfectly.
> Here's the source: https://github.com/saadeghi/daisyui/tree/master/examples/angular
> It's Angular version `12.2.0` I'm not sure about other versions but there shouldn't be a problem.

I'll go try, and answer with the result. Thanks

**Comment by PterPmnta** [comment]
The issue still happens, I don't know why just don't work at all.

Error: [Error](https://imgur.com/M8cwqGX)
Buttons: [Buttons](https://imgur.com/jl03Uxy)
Code; [Code](https://imgur.com/l9BrpNo)

My `package.json` same as the example you sent me to the link.

```
{
  "name": "test-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~12.2.0",
    "@angular/common": "~12.2.0",
    "@angular/compiler": "~12.2.0",
    "@angular/core": "~12.2.0",
    "@angular/forms": "~12.2.0",
    "@angular/platform-browser": "~12.2.0",
    "@angular/platform-browser-dynamic": "~12.2.0",
    "@angular/router": "~12.2.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.2.1",
    "@angular/cli": "~12.2.1",
    "@angular/compiler-cli": "~12.2.0",
    "@types/jasmine": "~3.8.0",
    "@types/node": "^12.11.1",
    "daisyui": "^1.11.1",
    "jasmine-core": "~3.8.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "tailwindcss": "^2.2.7",
    "typescript": "~4.3.5"
  }
}
```

I would download just the folder with the angular example, I could do that.

**Comment by PterPmnta** [comment]
Finally, I did, I solved the problem run this command, `ng add @ngneat/tailwind`
