### ISSUE TITLE
Issue with "dark:"

### ISSUE THREAD

**Issue by jay-s-p** [saadeghi/daisyui#1313]
See this:-

https://stackblitz.com/edit/daisyui-cdn-fhdn1g?file=index.html

I also explained the problem there.
Thank you.

**Comment by saadeghi** [comment]
Read this please: https://github.com/saadeghi/daisyui/discussions/640#discussioncomment-2424834  
And this: https://daisyui.com/docs/colors/

Let me know if you have any questions
