### ISSUE TITLE
Indeterminate checkbox background color

### ISSUE THREAD

**Issue by s-montigny-desautels** [saadeghi/daisyui#1314]
Hi!

The background colour seems to not be set for the indeterminate checkbox. This is what it looks like when I use the checkbox inside a table
![image](https://user-images.githubusercontent.com/84924528/199857701-2499ac25-d93d-4c30-ad2a-f0d2427eaf59.png)

I think the `indeterminate` pseudo-class is missing for each colour of the checkbox.

**Comment by saadeghi** [comment]
Do you see this issue [here](https://codepen.io/saadeghi/pen/GRGqjEQ?editors=1010) too?  
Are you using any other CSS package or plugin that may apply styles to a checkbox?

**Comment by s-montigny-desautels** [comment]
Yes, I see this issue in the codepen. It's subtle, but there is a black border around the checkbox.

Here is with Google Chrome
![image](https://user-images.githubusercontent.com/84924528/199978747-247d1203-2ae1-44e6-b221-821a7cfd9217.png)

Here is with Firefox
![image](https://user-images.githubusercontent.com/84924528/199978800-dcb0845b-67ca-4958-8118-3e32eb1f3566.png)

When the checkbox is checked, it look like this
![image](https://user-images.githubusercontent.com/84924528/199978880-fc979c9a-0155-450a-b759-2abcb364e208.png)

I'm only using DaisyUI with Tailwindcss for the CSS.

**Comment by saadeghi** [comment]
I can't see the issue unfortunately. Tested on Android, iOS and tested on MacOS with Chrome, Safari, Edge and Firefox.  

Can you try it on incognito mode with all plugins disabled? I want to make sure Chrome plugins are not affecting the style.

Also, please tell me What OS and which Chrome version you're using.

**Comment by s-montigny-desautels** [comment]
I'm using Chrome 107.0.5304.87 on Fedora 37. I see the issue in Incognito. I see the issue on my phone too, wich is a Samsung S20 on android 12 using Google Chrome. 

On a mac, at first, I didn't see the issue. But when I changed the zoom, I started to see it sometimes.
I've managed the find a workaround for my project. I've added those components in my tailwind config.

```js
addComponents({
	".checkbox": {
		"&-primary": {
			"@apply indeterminate:!bg-primary": {},
		},
		"&-secondary": {
			"@apply indeterminate:!bg-secondary": {},
		},
		"&-accent": {
			"@apply indeterminate:!bg-accent": {},
		},
		"&-success": {
			"@apply indeterminate:!bg-success": {},
		},
		"&-info": {
			"@apply indeterminate:!bg-info": {},
		},
		"&-warning": {
			"@apply indeterminate:!bg-warning": {},
		},
		"&-error": {
			"@apply indeterminate:!bg-error": {},
		},
	},
});
```
