### ISSUE TITLE
How can modal box adapt to image size automatically?

### ISSUE THREAD

**Issue by ddahan** [saadeghi/daisyui#1329]
I use modal to display images with different sizes.
My code has `class="modal-box relative max-w-5xl"` attribute.

When the image is big enough to take the use the specified width, it's displayed as expected:
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/1933516/200563724-aa13aee6-3574-456a-aa6c-341c4433c26b.png">

However, when the image is smaller, I keep getting white margin, as the image does not fill the 5xl width:
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/1933516/200563889-d2473365-7476-44de-b24c-c67da9f8fa4b.png">

I'd like the modal box size to adapt to the image size if the image is smaller.
Thanks for your help.

**Comment by saadeghi** [comment]
You can add `max-w-max` to `modal-box`  
https://play.tailwindcss.com/tJcxUZ6OAY
