### ISSUE TITLE
Toggle and range slider are not working but radio button are working fine

### ISSUE THREAD

**Issue by mel-in-a** [saadeghi/daisyui#133]
Hello, 

I' m using daisy ui with react and as said in the subject range slider and toggle animation are not working.

here is my tailwind config

`module.exports = {
  purge: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    styled: true,
    themes: true,
    base: true,
    utils: true,
    logs: true,
    rtl: false,
  },
}
`

Everything else seems to work fine. 
Thanks

**Comment by saadeghi** [comment]
@mel-in-a  Can you make a small repo on GitHub so I can reproduce this issue?

**Comment by mel-in-a** [comment]
hello and thank you for this quick answer. i can't really share my repo it's the beginning of a private project. Do you have an idea what could explain that ? can i try something ?

**Comment by saadeghi** [comment]
@mel-in-a 
- make sure your purge config is [working correctly](https://tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html)
- make sure the class names are correct. No typo, etc...
- make sure you're not using an old version of daisyui. `range` was added in version `1.11.0` so older versions won't have it.
- make sure there aren't any external CSS affecting the the exact styles. For example there could be another `.toggle` style in your project somewhere. Or could be some external global reset style `*{...}` affecting all elements
- try another browser. Maybe there's a browser plugin, applying some changes on pages.

**Comment by mel-in-a** [comment]
Hello, im' using the right version 
![image](https://user-images.githubusercontent.com/303499/129481151-ee13137a-20b9-4d03-9370-e739a8f5b335.png)

but  'have a message in console that could help us : 
![image](https://user-images.githubusercontent.com/303499/129481303-33df0eaa-9c82-4d84-9852-d73b885586e8.png)

**Comment by mel-in-a** [comment]
it's solved : 

  <input type="checkbox" defaultChecked className="toggle"/>
i used the defaultChecked

Thank you for your help, you framework is wonderful ! Have a nice day
