### ISSUE TITLE
progressbar "Indeterminate (without value)" is not working in Firefox

### ISSUE THREAD

**Issue by vfilatov** [saadeghi/daisyui#1330]
https://daisyui.com/components/progress/

last example on the page above is not animating in Firefox
OS: Ubuntu 22.10
checked:
- 106.0.5 (64-bit)
- Developer Edition 107.0b9 (64-bit)

**Comment by kumitatepazuru** [comment]
This problem occurs in the current version of firefox and daisyui (regardless of OS).
As shown in the screenshot below, the progress bar is filled in the black and the after element specific to Indeterminate is not present.
Please fix this problem.
![image](https://user-images.githubusercontent.com/43287589/206973175-9b6b26ee-f773-4088-8c5a-81e89a09c76b.png)

**Comment by saadeghi** [comment]
Fixed in `3.0.6`
