### ISSUE TITLE
rtl section in version 2.38.0 and 2.38.1

### ISSUE THREAD

**Issue by navid-mohammadi** [saadeghi/daisyui#1334]
Hello, version 2.38 has a problem for the rtl part that the styles of the checkboxes are not called and their states are irregular, if possible, you can solve the problem.
![kalayto-app-shop (7)](https://user-images.githubusercontent.com/47582141/200814876-8d01e144-09e4-4859-b38a-55fad92190e8.png)

**Comment by saadeghi** [comment]
Make sure:
1. You have `dir="rtl"` on your `<body>` tag.
2. You're using `tailwindcss-flip` plugin.
3. You set `rtl` daisyUI config as `true`

These are mentioned on the docs here: https://daisyui.com/docs/config/#rtl  
And here's an example: https://play.tailwindcss.com/NjT8G4QEwl

Let me know if you have any questions.

**Comment by saadeghi** [comment]
Colors are fixed now. update to the latest version.
