### ISSUE TITLE
Open Modal doesn't prevent background scrolling

### ISSUE THREAD

**Issue by JoshElias** [saadeghi/daisyui#1341]
### Description
I installed the Modal component in my Solidjs project and while it open/closes fine, it doesn't prevent the background from scrolling as it does with the example on DaisyUI. I've tested it with Firefox and Chrome.

### Steps To Reproduce

1. Install Node.js (https://nodejs.org/en/download/)
2. Install Solidjs /w TailwindCSS (https://tailwindcss.com/docs/guides/solidjs)
3. Install DaisyUI (https://daisyui.com/docs/install/)
4. Add the Modal HTML (https://daisyui.com/components/modal/) to a page that overflows and open it.

This is my first ever Github Issue. Please let me know how I can improve this documentation. I could include a sample project and/or a screencast showing the issue but I felt like it was self explanatory.

**Comment by JoshElias** [comment]
I thought maybe it was an issue with SolidJS but I'm getting the same error in React. Followed the same steps above but using a guide for Create React App: https://tailwindcss.com/docs/guides/create-react-app

**Comment by MentalGear** [comment]
For most use cases, you need extra JS, as CSS can not guarantee cross-browser body scrolling prevention.

**Comment by saadeghi** [comment]
Here's an example with Solid.js and I can't see scroll on the background:  
https://stackblitz.com/edit/daisyui-solidjs-8yddmx?file=src%2FApp.jsx

Please provide a code example so I can see your markup.

**Comment by JoshElias** [comment]
> Here's an example with Solid.js and I can't see scroll on the background: https://stackblitz.com/edit/daisyui-solidjs-8yddmx?file=src%2FApp.jsx
> 
> Please provide a code example so I can see your markup.

I'll do you one better. I get the same behavior with your sample code.
![scroll-bug](https://user-images.githubusercontent.com/7076407/201372008-0cb66da6-9bd9-46c6-ac6f-2f9d8ff4bc0a.gif)

That was tested in Windows in Firefox. I decided to take Linux out of the equation. It does however work on Windows+Chrome! So although it didn't work in Chrome on Linux, maybe this is a Firefox issue?

**Comment by JoshElias** [comment]
> For most use cases, you need extra JS, as CSS can not guarantee cross-browser body scrolling prevention.

I think you're right. I'm only able to get it working in Windows+Chrome. Linux+Chrome, Linux+Firefox, Windows+Firefox all don't work. For myself I'll probably use some Javascript to get it done using `document.body.style.overflow = "hidden";`.

**Comment by MentalGear** [comment]
iOS's another hard case. What you really want to do is use a specific library to cover all the edge cases (also, doing overflow hidden will reset body scroll position).

Maybe daisyui could put a note on the docs for this, or even recommend a no-scroll lib.

**Comment by JoshElias** [comment]
It seems to work consistently on all browsers on the DaisyUI website. Maybe they have a shim that's covering it that I'm missing.

**Comment by saadeghi** [comment]
I see the issue on Firefox (MacOS) and it's weird.  
Modal is using `overscroll-behavior` so the page doesn't scroll when we're scrolling on the `modal` However, Firefox is not respecting that even though Firefox Supports `overscroll-behavior`

**Comment by dcruz1990** [comment]
It also happens in Chrome

**Comment by Michael0520** [comment]
Has anyone found a solution for this please?

**Comment by nullart** [comment]
Just add `overflow-y-scroll flex-wrap` classes beside the `modal` class

```
<div class="modal overflow-y-scroll flex-wrap">
  <div class="modal-box relative bg-gray-700  ">
   ...
  </div>
</div
```

**Comment by PranavDhamanage** [comment]
Thanks Man. It really helped 👍

**Comment by esskar** [comment]
> @PranavDhamanage scroll lock works if you use the [drawer](https://daisyui.com/components/drawer/):  
> 
> https://play.tailwindcss.com/1uyKbqhqLN  
> 
> But I'm rewriting both modal and drawer styles for daisyUI `3.0` anyway.  
> 
> In daisyUI 3.0 modal will use `<dialog>` element and it will fix this issue and other issues related to modal.  
> 
> It will be released in May.

Not on iphone. 😔
