### ISSUE TITLE
Allow grabbing Carousel Items

### ISSUE THREAD

**Issue by baseplate-admin** [saadeghi/daisyui#1349]
Hi there,

It seems that `daisyui` doesn't allow grabbing carousel items ( which makes navigation on desktop a bit messy )

Is it possible to add this property ?

Here is an [example of `embla carousel`](https://codesandbox.io/s/embla-carousel-default-vanilla-gqh0n) which is what i expect a carousel to behave like ? ( is it possible to make this somehow using daisy ui ? )

[SwiperJS does the same thing too](https://swiperjs.com/)

**Comment by saadeghi** [comment]
This is simply not possible for a CSS library.  
daisyUI is CSS only but that doesn't mean you can not use JS solutions for specific components. For a carousel, a JS plugin provides you more options.

Let me know if you have any questions.

**Comment by baseplate-admin** [comment]
No that's all i had. I thought as CSS Does cool stuffs it might have been possible to do THIS with CSS only

Thanks for fast answer. Good day to you :D
