### ISSUE TITLE
Add auto dark mode/light mode switching based on system preference

### ISSUE THREAD

**Issue by MiraiSubject** [saadeghi/daisyui#135]
This feature is currently only included in the default light/dark mode setup: https://github.com/saadeghi/daisyui/blob/ae4f2a1d9e2e957ff683feb49d7fe7f0cd0ed312/src/index.js#L119-L120

Would be nice if you could do something like `mytheme-light` and `mytheme-dark` and have it be picked up the same way.

**Comment by saadeghi** [comment]
Now you can specify one of themes to be the default dark mode theme (based on `prefers-color-scheme: dark`):  
https://play.tailwindcss.com/CLrZGvf3ww?file=config  
And the first item in `themes` config will be the default light theme.
