### ISSUE TITLE
Tooltip being clipped out when used with Collapse

### ISSUE THREAD

**Issue by mscofield0** [saadeghi/daisyui#1358]
So my scenario is the following: I have a lobby list that I want to expand when clicked on. So I used the `collapse` component. However, I also have data inside the `collapse-title` that I would like to be hoverable showing some information. I am unable to do that, as the tooltip gets clipped out.

I've made a small example that should be enough to show the problem:
```html
<div class="h-10 collapse">
  <div class="collapse-title">
    <div class="tooltip tooltip-bottom" data-tip="banana">
      <button class="btn">Click me</button>
    </div>
  </div>
</div>
```

Not even `z-index` helps in this case.

Is this fixable or is this just how it is?

**Comment by Suniron** [comment]
Did you found a solution ? Same problem here:
![image](https://user-images.githubusercontent.com/36677774/219479493-eda44d62-2fc6-4d5b-a825-947f339a8127.png)

**Comment by saadeghi** [comment]
Sorry I missed this issue.  
Adding `overflow-visible` to the `collapse` will fix this. I will try to improve this in the future.

Let me know if you have any questions.
