### ISSUE TITLE
Toggle off state looks same as disabled.

### ISSUE THREAD

**Issue by acalvino4** [saadeghi/daisyui#1361]
I noticed that when daisy toggles are off, they lose their color and look the same as the [disabled state](https://daisyui.com/components/toggle/#disabled); hence it seems odd for that to be the default behavior.

1. What is a workaround to allow these toggles to maintain their color in the off state?
2. Would maintainers consider adjusting this to the default behavior, so that 'off' toggles don't appear disabled, OR consider making the off-white color seen [here](https://daisyui.com/components/toggle/#toggle) in the checked state the 'off' color.

**Comment by saadeghi** [comment]
Fixed.  
Disabled toggle now looks different
