### ISSUE TITLE
Closing Drawer when clicking <Link> tag? NextJS 13

### ISSUE THREAD

**Issue by grantgariepy** [saadeghi/daisyui#1362]
Is there a way to close the drawer when clicking a `<Link>` tag? I was looking at #288 but since NextJS 13 requires things such as "onClick" to be in  'use client' component, I was wondering there was an easy way to close the drawer when clinking a `<Link>` tag.

**Comment by pszafer** [comment]
Just curious, did you make it work using server components?

**Comment by saadeghi** [comment]
It's changing a checkbox value in the browser so the code must run on the client. Not server.

**Comment by Malewooo16** [comment]
I am having the same issue and I added the use client directive, but the drawer isn't closing

**Comment by pnavk** [comment]
To make this work, first encapsulate the drawer into it's own Client Component, like this:

```
'use client';

import { useState } from 'react';
import Link from 'next/link';

export default function Drawer() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="drawer">
      <input
        id="my-drawer"
        type="checkbox"
        className="drawer-toggle"
        checked={isOpen}
        onChange={() => setIsOpen(!isOpen)}
      />
      <div className="drawer-content">
        {/* Page content here */}
        <label htmlFor="my-drawer" className="btn btn-primary drawer-button">
          Open drawer
        </label>
      </div>
      <div className="drawer-side">
        <label
          htmlFor="my-drawer"
          aria-label="close sidebar"
          className="drawer-overlay"
        ></label>
        <ul className="menu p-4 w-80 min-h-full bg-base-200 text-base-content">
          {/* Sidebar content here */}
          <li>
            <Link onClick={() => setIsOpen(false)}>Sidebar Item 1</Link>
          </li>
          <li>
            <Link onClick={() => setIsOpen(false)}>Sidebar Item 2</Link>
          </li>
        </ul>
      </div>
    </div>
  );
}

```

Then use the `<Drawer />` component where the drawer toggle button should display.

**Comment by sabbir2609** [comment]
> To make this work, first encapsulate the drawer into it's own Client Component, like this:
> 
> ```
> 'use client';
> 
> import { useState } from 'react';
> import Link from 'next/link';
> 
> export default function Drawer() {
>   const [isOpen, setIsOpen] = useState(false);
> 
>   return (
>     <div className="drawer">
>       <input
>         id="my-drawer"
>         type="checkbox"
>         className="drawer-toggle"
>         checked={isOpen}
>         onChange={() => setIsOpen(!isOpen)}
>       />
>       <div className="drawer-content">
>         {/* Page content here */}
>         <label htmlFor="my-drawer" className="btn btn-primary drawer-button">
>           Open drawer
>         </label>
>       </div>
>       <div className="drawer-side">
>         <label
>           htmlFor="my-drawer"
>           aria-label="close sidebar"
>           className="drawer-overlay"
>         ></label>
>         <ul className="menu p-4 w-80 min-h-full bg-base-200 text-base-content">
>           {/* Sidebar content here */}
>           <li>
>             <Link onClick={() => setIsOpen(false)}>Sidebar Item 1</Link>
>           </li>
>           <li>
>             <Link onClick={() => setIsOpen(false)}>Sidebar Item 2</Link>
>           </li>
>         </ul>
>       </div>
>     </div>
>   );
> }
> ```
> 
> Then use the `<Drawer />` component where the drawer toggle button should display.

what about SSR?
