### ISSUE TITLE
Feature request: Add Sidebar Menu Dropdown Toggle

### ISSUE THREAD

**Issue by lifeitech** [saadeghi/daisyui#1363]
It would be great if vertical menus can be toggled, and show dropdown submenus on toggle. An example would be [Flowbite's multilevel dropdown](https://flowbite.com/docs/components/sidebar/#multi-level-dropdown).

Right now in daisyUI there is only a [menu component](https://daisyui.com/components/menu/#vertical-with-submenu) that shows submenus on _hover_, but there is no component for toggling.

**Comment by REJack** [comment]
Simply combine collapse with menu 😉 like this, it's not W3C valid but it works and looks good. I will use it for my private projects till I can switch to an official solution 🤣.

```html
<ul class="menu menu-compact p-4 space-y-1 w-60 bg-base-200 text-base-content">
    <li><a class="" href="#">Dashboard</a></li>
    <div class="collapse collapse-arrow overflow-hidden rounded-lg">
        <input type="checkbox" class="min-h-[0] p-0 hover:bg-base-content/10 !opacity-100">
        <div class="collapse-title text-sm py-2 min-h-8">Submenu</div>
        <div class="collapse-content">
            <ul class="space-y-1 pt-1">
                <li><a href="#">Item</a></li>
            </ul>
        </div>
    </div>
</ul>
```
