### ISSUE TITLE
Disable DaisyUI form elements?

### ISSUE THREAD

**Issue by Loosie94** [saadeghi/daisyui#1364]
Hi, really like DaisyUI and I have been using it a lot lately! :)

Now I am facing an issue where the class `.radio` is being used in a form field (of a plugin). This is causing some styling issues.
So I was wondering; Is it possible to disable the DaisyUI form elements, since I already have another solutions for this.

Thanks!

**Comment by wrench1815** [comment]
You can add prefix to class names for Daisy UI. like "du-" for instance. Then all the Daisy UI classes that you'll use will have to use that prefix as in "du-bg-primary", du-radio" etc. More [here](https://daisyui.com/docs/config/#prefix).

**Comment by saadeghi** [comment]
Currently there are no daisyUI configs to exclude some class names.  
- You can do as @wrench1815 said and add a prefix for all daisyUI class name sot avoid conflicts.
- Another option is to discard unwanted classnames using Tailwind CSS `blocklist` config: https://tailwindcss.com/docs/content-configuration#discarding-classes
