### ISSUE TITLE
Collapse Element Only Opens/Closes When Clicking One Specific Area 

### ISSUE THREAD

**Issue by kadenthayer** [saadeghi/daisyui#1382]
When using the following collapse element: 

"[#]Custom colors for collapse that works with checkbox"

The element only opens/closes when I click on one specific area to the left of the text, and not when I click any other area of the div box.

I get this issue when trying to use any of collapse with checkbox elements.

**Comment by sahilas** [comment]
the issue from tailwindcss form plugin

[type="checkbox"], [type="radio"]{
-webkit-appearance: none;
-moz-appearance: none;
appearance: none;
padding: 0;
-webkit-print-color-adjust: exact;
print-color-adjust: exact;
display: inline-block;
vertical-align: middle;
background-origin: border-box;
-webkit-user-select: none;
-moz-user-select: none;
user-select: none;
flex-shrink: 0;
height: 1rem;
**width: 1rem; //comment this**
color: #2563eb;
background-color: #fff;
border-color: #6b7280;
border-width: 1px;
--tw-shadow: 0 0 #0000;
}
