### ISSUE TITLE
Question: List of daisyUI classes

### ISSUE THREAD

**Issue by RobertJGabriel** [saadeghi/daisyui#1383]
Hey,

Just looking for if there is a list of daisyUI classes.

As I am updating a project to use a prefix and might be easier to find what to update if I know what classes are daisy vs regular tailwind.

Thank you

@saadeghi

**Comment by saadeghi** [comment]
You can get a list of all class names from a CSS file using a JS code like this:  
https://codepen.io/saadeghi/pen/gOKeMMy?editors=0010
```js
// get CSS file
fetch("https://unpkg.com/daisyui@2.41.0/dist/full.css")
  .then( result => result.text() )
  .then( content => {
  // find class names using regex
  let arr = content.match(/(?:[\.]{1})([a-zA-Z_]+[\w-_]*)(?:[\s\.\,\{\>#\:]{0})/igm)
  // remove duplicates from array
  let unique = [...new Set(arr)];
  // print all
  unique.forEach(element => {
    document.write(`${element} <br/>`)
  })
})
  ```

**Comment by RobertJGabriel** [comment]
Amazing, thank you
