### ISSUE TITLE
Font family in custom themes

### ISSUE THREAD

**Issue by tom-acceleratecompliance** [saadeghi/daisyui#139]
Hi, thanks for the fantastic library.

I feel like I am missing something obvious, I'm looking at building a custom theme and defining the font family for the theme, like some of the inbuilt themes do (wireframe for example).

I've found the definitions of the inbuilt themes and they use the "fontFamily" key, but when I add this to my custom theme, nothing happens. 

Is this possible? 

Thanks

**Comment by tom-acceleratecompliance** [comment]
Sorry for wasting your time, that works perfectly, I just wasn't passing the config in correctly.
Thanks!

**Comment by saadeghi** [comment]
@tom-acceleratecompliance Good.
Here's an example, if anyone else looking for that:  
https://play.tailwindcss.com/QtVDNrydis?file=config
