### ISSUE TITLE
can i use daisyui together with flowbite?

### ISSUE THREAD

**Issue by kknono** [saadeghi/daisyui#1390]
Hi,
  can i use daisyui together with flowbite?

thx.

**Comment by saadeghi** [comment]
Yes of course.  
There are no conflicts as far as I know.

**Comment by kknono** [comment]
nice. thank you very much.

**Comment by leomorpho** [comment]
Actually, I ran into a conflict with the daisyui dropdown. For some reason, when adding flowbite to my project, my dropdown stops working. I've also noticed other styling from daisyui breaking, so not too sure that these two don't interact in an unfriendly manner.

**Comment by saadeghi** [comment]
If there's a class name conflict, try adding a `prefix` to daisyUI classes names:   
https://daisyui.com/docs/config/

**Comment by kknono** [comment]
Hi, I have used a prefix added to the front of the daisyUI classes, and other components are working fine. However, the checkbox component is not. The code is as follows:
`<input
  type="checkbox"
  class="!dy-checkbox"
/>`

When used in combination with Flowbite, the checkmark inside the checkbox appears very small when checked, which is inconsistent with the default daisyUI appearance."


Please need more help. thanks
