### ISSUE TITLE
access subelements /(ex. tr in table)

### ISSUE THREAD

**Issue by wibed** [saadeghi/daisyui#1392]
one can style a table using the class `table`

but if i had a singled out row. as i would get in a drag and drop context.
how would i style a single row independently?

**Comment by saadeghi** [comment]
Depends on what style you need.  
Basically, every cell has a background color so if you want to set a background color for a the whole row, you should either apply background color utility classes for each cell or you can use something like `bg-red-200 [&>*]:bg-transparent` for the row to apply background color for the row and remove the background color of each row:  
https://play.tailwindcss.com/zKgbSTEDSr

Let me know if you have any questions.
