### ISSUE TITLE
Buttons components should not be Capitalized

### ISSUE THREAD

**Issue by RSickenberg** [saadeghi/daisyui#140]
Hello !

I'm not sure if it is intended or not, but the buttons always capitalize the text inside, and I have to add a `normal-case` modifier.

Thanks for this lib !

Regards

**Comment by saadeghi** [comment]
@RSickenberg This is intended.
In almost all default themes, buttons are capitalize. This is adapted from Material Design buttons.
There are 3 ways to change that:
- using `normal-case` utility class on all buttons
- [adding a style to your css](https://play.tailwindcss.com/79qJUqnN8n?file=css):
  ```
  .btn{
    text-transform: none;
  }
  ```
- If you're using a custom theme, [set the button style in config](https://play.tailwindcss.com/O5lRJ0pmte?file=config)

Please let me know if you have any questions

**Comment by RSickenberg** [comment]
I used `normal-case` indeed. If it's not a bug, it's okay for me! :-)
