### ISSUE TITLE
Modal sizes

### ISSUE THREAD

**Issue by pavangayakwad** [saadeghi/daisyui#141]
How can I set the modal sizes? sm, md, lg and xl? 

Please assist.

**Comment by saadeghi** [comment]
@pavangayakwad It doesn't have size. But you can use width/height utility classes like `w-96` or `h-96`

Please let me know if you have any questions.

**Comment by pavangayakwad** [comment]
Thanks for your quick reply.

It seems the sizes are not really affecting even when I set something like 

`<div className="modal-box w-full">` 

or

 `<div className="modal-box w-10/12">`.

The `w-{}` have limited sizes so I was exploring other large size options.


![image](https://user-images.githubusercontent.com/1834890/129911118-196951d3-ab2b-43f6-b007-9a76d637f851.png)

**Comment by saadeghi** [comment]
@pavangayakwad 
Try adding a `max-w-full` as well
```
<div class="modal-box max-w-full w-full">
```
```
<div class="modal-box max-w-full w-10/12">
```

**Comment by pavangayakwad** [comment]
This worked like a charm! 

Updating the documentation with details should help who are looking for these tweaks! This is approach is far far better idea than giving limited sm, md, lg, xl kind of settings. 

Indeed a great work from you guy!!! keep it going! 👍 and Thank you very much @saadeghi for taking time and responding.
