### ISSUE TITLE
cannot use daisyui together with aos

### ISSUE THREAD

**Issue by kknono** [saadeghi/daisyui#1414]
<template>
    <div class="drawer  ">
        <input id="drawer-input" type="checkbox" class="drawer-toggle">
        <div class="drawer-content    ">
            <div data-aos="fade-up" class="h-[50%] bg-red-200"></div>
            <div data-aos="fade-up" class="h-[50%] bg-red-400"></div>
            <div data-aos="fade-up" class="h-[50%] bg-green-200"></div>
            <div data-aos="fade-up" class="h-[50%] bg-green-400"></div>
        </div>
    </div>
</template> 
  

Hi,
  when i  use "drawer" component, it seems not working with "aos".

thx

**Comment by kknono** [comment]
`<template>
    <div class="drawer  ">
        <input id="drawer-input" type="checkbox" class="drawer-toggle">
        <div class="drawer-content    ">
            <div data-aos="fade-up" class="h-[50%] bg-red-200"></div>
            <div data-aos="fade-up" class="h-[50%] bg-red-400"></div>
            <div data-aos="fade-up" class="h-[50%] bg-green-200"></div>
            <div data-aos="fade-up" class="h-[50%] bg-green-400"></div>
        </div>
    </div>
</template> `

**Comment by kknono** [comment]
<template>
    <div class="drawer  ">
        <input id="drawer-input" type="checkbox" class="drawer-toggle">
        <div class="drawer-content    ">
            <div data-aos="fade-up" class="h-[50%] bg-red-200"></div>
            <div data-aos="fade-up" class="h-[50%] bg-red-400"></div>
            <div data-aos="fade-up" class="h-[50%] bg-green-200"></div>
            <div data-aos="fade-up" class="h-[50%] bg-green-400"></div>
        </div>
    </div>
</template>

**Comment by kknono** [comment]
<div class="drawer  ">
        <input id="drawer-input" type="checkbox" class="drawer-toggle">
        <div class="drawer-content    ">
            <div data-aos="fade-up" class="h-[50%] bg-red-200"></div>
            <div data-aos="fade-up" class="h-[50%] bg-red-400"></div>
            <div data-aos="fade-up" class="h-[50%] bg-green-200"></div>
            <div data-aos="fade-up" class="h-[50%] bg-green-400"></div>
        </div>
    </div>

**Comment by saadeghi** [comment]
I wish I could help but I really can't do anything about it. daisyUI's `drawer` is a scrollable container but AOS library only supports the scroll of root element.  
Related issue: https://github.com/michalsnik/aos/issues/85  

You should either stop using daisyUI's `drawer` and make your own sidebar using Tailwind CSS classes or you should use another scroll animation library that supports scroll of scrollable containers (not just the root element)

Let me know if you have any questions.
