### ISSUE TITLE
[Feature Request] Add Combobox (Autocomplete)

### ISSUE THREAD

**Issue by QUERY-GANI** [saadeghi/daisyui#1421]
It would be great if there are class like [combobox headlessui](https://headlessui.com/react/combobox).

Right now in daisyUI there is only a [dropdown component](https://daisyui.com/components/dropdown) that shows submenus on click, but there is no input and not support for keyboard navigation.

**Comment by saadeghi** [comment]
daisyUI is just CSS and it's the UI only. So it's not possible to do the same thing HeadlessUI is doing or to have keyboard navigation.  
You can simply use HeadlessUI and daisyUI together tho. Because daisyUI only provides visual representation without functionality and daisyUI only provides functionality without UI so these two are perfect match together.

Let me know if you have any questions.

**Comment by iamandrewluca** [comment]
An example of combobox using RadixUI & daisyUI. Maybe is not fully accessible, but it works 

**Example**

<img width="235" alt="image" src="https://github.com/saadeghi/daisyui/assets/1881266/f08af5fe-b42c-4f43-8a37-e30edcdc2a81">


**Usage**

```vue
<Combobox
	v-model="selectedType"
	placeholder="Types"
	:options="typesOptions"
/>
```

**Code**

```vue
<script setup lang="ts">
import {
	ComboboxAnchor,
	ComboboxContent,
	ComboboxEmpty,
	ComboboxGroup,
	ComboboxInput,
	ComboboxItem,
	ComboboxItemIndicator,
	ComboboxRoot,
	ComboboxTrigger,
	ComboboxViewport,
} from 'radix-vue';
import { ChevronDownIcon, CheckIcon } from '@heroicons/vue/24/solid';

defineEmits<{
	'update:modelValue': [value: string];
}>();

defineProps<{
	modelValue?: string;
	options: readonly string[];
	placeholder?: string;
}>();
</script>

<template>
	<ComboboxRoot
		:model-value="modelValue"
		class="relative dropdown"
		@update:model-value="$emit('update:modelValue', $event as string)"
	>
		<ComboboxAnchor class="mb-2 relative">
			<ComboboxInput
				class="input input-bordered pr-8 truncate input-sm"
				:placeholder="placeholder ?? 'Select...'"
			/>
			<ComboboxTrigger class="absolute right-0 inset-y-0 flex items-center p-2">
				<ChevronDownIcon class="h-4 w-4" />
			</ComboboxTrigger>
		</ComboboxAnchor>

		<ComboboxContent
			class="dropdown-content z-[1] shadow bg-base-200 rounded-lg min-w-full"
		>
			<ComboboxViewport>
				<ComboboxEmpty class="px-4 py-2 text-center text-sm" />

				<ComboboxGroup as="ul" class="menu space-y-1">
					<ComboboxItem
						v-for="(option, index) in options"
						:key="index"
						:value="option"
						as="li"
						class="group"
					>
						<button class="whitespace-nowrap group-data-[highlighted]:hidden">
							<ComboboxItemIndicator :as="CheckIcon" class="h-3 w-3" />
							{{ option }}
						</button>
						<button
							class="whitespace-nowrap hidden active group-data-[highlighted]:grid"
						>
							<ComboboxItemIndicator :as="CheckIcon" class="h-3 w-3" />
							{{ option }}
						</button>
					</ComboboxItem>
				</ComboboxGroup>
			</ComboboxViewport>
		</ComboboxContent>
	</ComboboxRoot>
</template>
```

**Comment by saadeghi** [comment]
@iamandrewluca Thank you 💚

>Maybe is not fully accessible, but it works

As far as I know Radix provides keyboard and screen reader accessibility. Have you experienced a problem?

**Comment by iamandrewluca** [comment]
Maybe something in terms of styling, because is a little bit tricky.

For example, to render the option active, I had to do this (from the above code, simplified)

```
<button class="group-data-[highlighted]:hidden">
	{{ option }}
</button>
<button class="hidden active group-data-[highlighted]:grid">
	{{ option }}
</button>
```

I need to apply the `active` class on the element inside the `li`, but the active state is only added to the `li` as a data attribute.

**Comment by waynesbrain** [comment]
I built this one over the weekend - https://github.com/saadeghi/daisyui/discussions/4707
