### ISSUE TITLE
How to avoid rendering the modal component?

### ISSUE THREAD

**Issue by TAQ2** [saadeghi/daisyui#1436]
Hi, thanks so much for this library, was hoping you can help me with a noobie question.

I wondering if there is a way I can create a modal component with react that doesn't render in the dom unless the modal is open? That way the data fetch I need to do within the modal doesn't need to happen until the user opens the modal. Secondly the modal I have is quite heavy and has lots of elements so it would be good to clean up the dom of these components that aren't being used since lighthouse is complaining about too many dom elements present. 

Thanks in advanced!

**Comment by saadeghi** [comment]
In React, you can conditionally render a part of the page like this:  
```jsx
<div>
{someVariable &&
  <div>conditionally rendered div</div>
}
</div>
```

**Comment by TAQ2** [comment]
@saadeghi  I appreciate the reply! 

What you are saying makes sense but if we look at the [render method](https://daisyui.com/components/modal/#modal-using-label--hidden-checkbox) of how the modal from daily ui should be used, the button and the modal are rendered. There isn't use of conditional rendering meaning that if I was to use the modal with conditional rendering I lose all the benefits that the dailyui modal component has e.g. clicking outside of the modal closes it.  Any ideas?

**Comment by saadeghi** [comment]
No won't lost the functionality of modal because it's a simple HTML checkbox and it works regardless of what the JS framework is doing.
You just need to place the button:
```jsx
<label htmlFor="my-modal" className="btn">open modal</label>
```
And set a conditional render for the content of the modal
```jsx
<input type="checkbox" id="my-modal" className="modal-toggle" />
<div className="modal">
  {someVariable && <>
    <div className="modal-box">
      <h3 className="font-bold text-lg">Congratulations random Internet user!</h3>
      <p className="py-4">You've been selected for a chance to get one year of subscription to use Wikipedia for free!</p>
      <div className="modal-action">
        <label htmlFor="my-modal" className="btn">Yay!</label>
      </div>
    </div>
  }
</div>
```
Then set that variable to `true` when you want it to be rendered

**Comment by saadeghi** [comment]
Also, if you're using React or any other JS library, I would suggest to use a JS plugin for the modal part. Because daisyUI's solution is a CSS-only modal and it can't give you all the benefits that a JS modal have.

**Comment by 7flash** [comment]
> Also, if you're using React or any other JS library, I would suggest to use a JS plugin for the modal part. Because daisyUI's solution is a CSS-only modal and it can't give you all the benefits that a JS modal have.

Which plugin would you suggest to use? I would like to control my modal with react state instead of html label/checkbox
