### ISSUE TITLE
why an error is reported during installation

### ISSUE THREAD

**Issue by admin8756** [saadeghi/daisyui#1437]
![image](https://user-images.githubusercontent.com/21336637/207757964-f841c2e7-4186-4631-8155-b144ec55d91f.png)
package.json
``` sh
  "dependencies": {
    "axios": "^1.2.1",
    "dayjs": "^1.11.7",
    "pinia": "^2.0.28",
    "vue": "^3.2.41",
    "windicss": "^3.5.6"
  },
  "devDependencies": {
    "unplugin-auto-import": "^0.12.1",
    "unplugin-vue-components": "^0.22.12",
    "@vitejs/plugin-vue": "^3.2.0",
    "daisyui": "^2.42.1",
    "postcss": "^8.4.19",
    "vite": "^3.2.3",
    "vite-plugin-windicss": "^1.8.10",
    "vite-plugin-compression": "^0.5.1",
    "vite-plugin-restart": "^0.2.0"
  }
```

**Comment by saadeghi** [comment]
Are you using npm version 6 or less?  
You can check by running `npm --version`

**Comment by admin8756** [comment]
> Are you using npm version 6 or less? You can check by running `npm --version`
I'm using yarn for 1.22.19
I'm using node for v16.17.1

![image](https://user-images.githubusercontent.com/21336637/207896927-78a3ab9a-6946-4922-9a53-b2d1adf250e4.png)
![image](https://user-images.githubusercontent.com/21336637/207897231-bfae2667-8b31-4275-9acd-409734648a10.png)

**Comment by admin8756** [comment]
> Are you using npm version 6 or less? You can check by running `npm --version`

npm for  8.19.2
