### ISSUE TITLE
Incorrectly positioned loading in Button

### ISSUE THREAD

**Issue by lyn-eva** [saadeghi/daisyui#1444]
**Chrome version**: 108.0.5359.98
**OS**: Ubuntu 22.04  

[Screencast from 12-17-2022 03:44:58 PM.webm](https://user-images.githubusercontent.com/90125292/208234935-33b9e820-708e-4484-9308-c2c9129fa974.webm)

**Comment by saadeghi** [comment]
Does this also happen on Incognito Mode (with all Chrome plugins disabled)?  
Because I suspect something might be manipulating the style. Same Chrome version on all operating systems should give the same result 🤔

**Comment by lyn-eva** [comment]
@saadeghi You are right. Maybe some extensions are overriding the styling. It works fine on incognito.

**Comment by saadeghi** [comment]
Great.  
If you found out which extension is causing the issue, please let me know.
