### ISSUE TITLE
How do I remove the sticky table header?

### ISSUE THREAD

**Issue by JamieGrimwood** [saadeghi/daisyui#1447]
How do I remove this styling on my table? I don't want it there. https://github.com/saadeghi/daisyui/blob/master/src/components/unstyled/table.css

I have tried adding "static" to the first row in my table and I have tried nested CSS but that doesn't work with Next.JS either (or i'm doing something very wrong).

Thanks!

**Comment by irg1008** [comment]
Why on earth would we want for the first column to always be sticky? This should be optional, maybe a new class table-sticky?

**Comment by JamieGrimwood** [comment]
Exactly!

**Comment by saadeghi** [comment]
Currently there is no modifier class name to disable this style.  
But you can add an arbitrary Tailwind CSS class name like `[&_th]:first:relative` to the table and it will not be sticky anymore.

Let me know if you have any questions.
