### ISSUE TITLE
Toggle incorrectly rendering as checkbox

### ISSUE THREAD

**Issue by saguirre** [saadeghi/daisyui#1449]
Before clicking the toggle:
<img width="60" alt="image" src="https://user-images.githubusercontent.com/43446586/208484100-b5f28ae3-87c9-4521-9570-9d175c1b062c.png">
After checked:
<img width="68" alt="image" src="https://user-images.githubusercontent.com/43446586/208484148-9d1622ce-f910-4369-9fca-aad8ffb1ebf1.png">
After reset to unchecked state
<img width="66" alt="image" src="https://user-images.githubusercontent.com/43446586/208484186-b117debc-5fb7-414a-836e-dc2489ec83d8.png">

Here's the input element:
<img width="446" alt="image" src="https://user-images.githubusercontent.com/43446586/208484545-19d9e77a-1bef-4014-b0ba-6a942e1b40f7.png">

Here's my package.json:
{
  "private": true,
  "scripts": {
    "dev": "next dev -p 3001",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@heroicons/react": "^2.0.13",
    "@tailwindcss/forms": "^0.5.3",
    "@tailwindcss/typography": "^0.5.8",
    "axios": "^1.2.1",
    "classnames": "^2.3.2",
    "cookies-next": "^2.1.1",
    "daisyui": "^2.45.0",
    "date-fns": "^2.29.3",
    "iron-session": "^6.3.1",
    "next": "latest",
    "next-themes": "^0.2.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.40.0",
    "react-toastify": "^9.1.1",
    "swr": "^2.0.0"
  },
  "devDependencies": {
    "@types/node": "18.11.3",
    "@types/react": "18.0.21",
    "@types/react-dom": "18.0.6",
    "autoprefixer": "^10.4.12",
    "postcss": "^8.4.18",
    "tailwindcss": "^3.2.1",
    "typescript": "4.8.4"
  }
}

**Comment by saadeghi** [comment]
This style is from `@tailwindcss/forms` package. I don't think you need both daisyUI and forms plugin on the same project because both of theme do the same job.

Related topics:
- https://github.com/saadeghi/daisyui/issues/1431
- https://github.com/saadeghi/daisyui/issues/1378
- https://github.com/saadeghi/daisyui/issues/1301
- https://github.com/saadeghi/daisyui/issues/804

**Comment by saguirre** [comment]
That was exactly it. Thanks for your time and your answer! Loving the library!
