### ISSUE TITLE
how can I make mobile buttons not lock on hover 

### ISSUE THREAD

**Issue by kphamm** [saadeghi/daisyui#1450]
hello, I have an issue where whenever I click a button in chrome tools simulating a touch screen device, it stays in the "hover" state. is there any way to change the button so that it resets to the normal state after clicking the button?

basically I want to make a checkbox that looks like a button
```
<label className={`btn btn-outline justify-start ${checked ? "btn-active" : ""}`}>
    <input>
</label>
```

but after clicking on mobile and clicked becomes false, the button still looks active because of a sticky state. then i have to click away for the active state to go away.

i also tried this in my tailwind config

```
future: {
    hoverOnlyWhenSupported: true,
  },
```

but it doesn't fix it. is there any way to fix this on the daisyui side? is there a way to easily disable hover styles or only apply some of them for `btn` class?

**Comment by saadeghi** [comment]
I believe when touch devices keep the hover style until next focus, is normal and there's nothing wrong about it. However some people don't like that behavior.  
If you want to disable the hover effect on touch devices, you can add a CSS with `@media (hover: none)`. For example, for the outline button, background color and text color changes so we can prevent that like this:
```css
@media (hover: none) {
  .btn.btn-outline:hover{
    background-color: transparent;
    color: inherit;
  }
}
```
Example: https://play.tailwindcss.com/boA6orgPcQ?file=css
