### ISSUE TITLE
Breadcrumbs don't render

### ISSUE THREAD

**Issue by kimdre** [saadeghi/daisyui#1456]
I tried the examples in the docs, but none of them worked (Everything else does)
https://daisyui.com/components/breadcrumbs/

The entries just get rendered like a list without dots.

**Comment by kimdre** [comment]
Nevermind. After updating the packages it does work now.

**Comment by saadeghi** [comment]
Make sure your `content` config on `tailwind.config.js` file is pointing to all your markup files (layouts and components)
