### ISSUE TITLE
Question - Getting color values via Javascript

### ISSUE THREAD

**Issue by 112RG** [saadeghi/daisyui#146]
Hi first off I wanted to say thank you for this library! It's wonderful to use. I am loving the easy theme switching. Just a quick question.

I have a canvas element that is drawing a visualization to music I am setting the canvas background via
`this.myCtx.fillStyle = getComputedStyle(document.getElementsByClassName('bg-base-100')[0]).backgroundColor` But this is very annoying since i need to have bg-base-100 on of my elememnts. And then with bg-primary to use below.
`this.gradient.addColorStop(0.5, '#f50782')
this.gradient.addColorStop(0, '#f14ea2')`

I am wondering if there is a way via JS to get the current bg-base bg-primary colors to set the canvas color dynamically depending on the theme

**Comment by saadeghi** [comment]
@112RG color values are stored inside CSS variables. For example:  
```
.bg-primary{background-color: hsl(var(--p))}
.bg-secondary{background-color: hsl(var(--s))}
```
See name of CSS variables [here](https://github.com/saadeghi/daisyui/blob/master/src/colors/colorNames.js)  
So you should be able to use `hsl(var(--VARIABLE))` as the color name in your JS.  
Please let me know if you have any questions.

**Comment by 112RG** [comment]
Thank you this worked!

**Comment by MentalGear** [comment]
As a user, I find it rather confusing that a shorthand is used for the css vars instead of the full name that is used throughout the entire dasiyUI framework. (e.g. --p instead of --primary).

Is there an option to change this ?

**Comment by saadeghi** [comment]
@MentalGear currently there's not an option to change the variable names, but you can always define your own variables and color names on tailwind.config.js and use your own color names.  
I used short names for color variables because most devs won't even need to see or use the CSS variables. Most people just need to use the class names (`bg-primary`, `text-neutral` etc...) so it's an opportunity to lower the size of output CSS file.

**Comment by MentalGear** [comment]
Thx for your anser @saadeghi .

Yes, but sometimes you would need to use the css vars for setting theme styles that don't have a tailwind class-name. For example: border-top-color: hsl( var(--p) )

In this case, I would have expected the daisyUI standard color name, and values like --bc or --ac are confusing and require research. Personally, strong naming conventions would outweigh small optimization every time.

I normalized names by adding:
```sass
      .tabulator-col-content
        .tabulator-col-sorter
          .tabulator-arrow
            // using theme colors
            border-top-color: hsl( var(--p) ) !important
            border-bottom-color: hsl( var(--p) ) !important
```

**Comment by saadeghi** [comment]
@MentalGear but... we can use different colors for each border side [using JIT](https://tailwindcss.com/docs/just-in-time-mode#per-side-border-colors)  
example: https://play.tailwindcss.com/6xQB0sLM3C
