### ISSUE TITLE
Button does not retain its color when the "disabled" attribute is applied to it

### ISSUE THREAD

**Issue by Withervoid77** [saadeghi/daisyui#1461]
It changes its color to dark gray always, no matter what kind of button it is, how could i solve the problem?

### Code:
![image](https://user-images.githubusercontent.com/95507613/209484039-e69bf9c8-3c6c-4e35-ad97-211e22546c77.png)

### Button:
![image](https://user-images.githubusercontent.com/95507613/209484096-a073fbcc-7adf-4c02-9995-f3ff6a3c4980.png)

### Button disabled:
![image](https://user-images.githubusercontent.com/95507613/209484085-f88a3b4a-f5f1-49a8-8f7d-6877b13081e4.png)

**Comment by saadeghi** [comment]
This is intended.  
I think when button is disabled, it does nothing so having a color to look different from other disabled buttons wouldn't help anyone.

However you can always customize daisyUI buttons the way you want using custom CSS or Tailwind CSS utility classes.

Let me know if you have any questions.
