### ISSUE TITLE
[Feature Request] Support for multi-select component

### ISSUE THREAD

**Issue by thdoan** [saadeghi/daisyui#1465]
I wish the [Select component](https://daisyui.com/components/select/) could render multiple selections with checkmarks like this:

![image](https://user-images.githubusercontent.com/4110567/209719874-c5ea77b5-700e-4cd0-96ff-f461e58e9229.png)

Examples:
https://carbon-components-svelte.onrender.com/components/MultiSelect
https://shoelace.style/components/select?id=multiple

**Comment by jnfrati** [comment]
Although I understand that daisyui is more of a utility classes UI framework, I would love to see features like this. 
Maybe accepting some ideas/contributions on this side?

**Comment by boian-ivanov** [comment]
Even though I'd be all for such a dropdown to exist (since I need it as well), you would need state to exist with it. Since DaisyUI is only a CSS framework on top of Tailwind, you'd either need to defer that functionality to the user (through the documentation), or just straight up create something like Headless UI (or a component lib) around it.

**Comment by saadeghi** [comment]
Indeed. Something like this requires JS to work.  
It's basically a text input + dropdown + some pills with a remove button. when you write on the input text, there should be a JS code to search the items and suggest them. When you pick from the dropdown, JS should add a pill for it and when you click on remove button, JS should remove it. And all of these should be accessible as a JS object to for the app to use.

So... CSS can not do this. But you can use the native HTML `datalist` which gives you the ability to type, search and pick 1 option from the list (but you're free to write custom value):  
https://play.tailwindcss.com/K0k9DWt9wq
```html
<input 
 list="items"
 class="input input-bordered m-10"
 placeholder="Pick a Simpson"
>

<datalist id="items">
  <option>Homer</option>
  <option>Marge</option>
  <option>Bart</option>
  <option>Lisa</option>
  <option>Maggie</option>
</datalist>
```
For a "multi-select component" like you asked for, you would need a JS plugin.

**Comment by NikarashiHatsu** [comment]
Might bump to answer @psygo question, you might want to try my approach https://github.com/saadeghi/daisyui/discussions/2817

**Comment by psygo** [comment]
@NikarashiHatsu do you have a full sandbox example of that? It would be really helpful to me, specially considering that I don't have any experience with Choices.js, and very little with DaisyUI.

**Comment by psygo** [comment]
So, I ended up coding my own multi-select, though it's not thoroughly generalized ([this video](https://youtu.be/V2zEAXLQbF4) by Web Dev Cody helped a bit):

```typescript
import { useState } from "react"

import { Theme, useTheme } from "@context"

type MultiSelectProps = {
  label: string
  placeHolder: string
  options: string[]
  initialSelection?: string[]
  onChangeHook: (selected: Set<string>) => void
}

export function MultiSelect({
  label,
  placeHolder,
  options,
  initialSelection,
  onChangeHook,
}: MultiSelectProps) {
  const [selected, setSelected] = useState<string[]>(
    initialSelection ?? []
  )

  function handleToggle(
    e: React.MouseEvent<HTMLInputElement>
  ) {
    const clicked = (e.target as HTMLInputElement).dataset
      .value!
    const selectedSet = new Set(selected)

    selectedSet.has(clicked)
      ? selectedSet.delete(clicked)
      : selectedSet.add(clicked)

    onChangeHook(selectedSet)
    setSelected([...selectedSet])
  }

  function hasSelection() {
    return selected.length !== 0
  }

  const { theme } = useTheme()
  const borderColor =
    theme === Theme.dark ? "#383f47" : "#c4bda9"

  return (
    <div className="w-full">
      <div className="label">
        <span className="label-text">{label}</span>
      </div>
      <div className="dropdown w-full">
        <div
          tabIndex={0}
          role="button"
          className={`multiselect-btn btn h-max p-2 px-3 w-full justify-start font-normal bg-base-100 border-[${borderColor}] shadow-none`}
        >
          {!hasSelection() ? (
            <p className="text-neutral-400">
              {placeHolder}
            </p>
          ) : (
            ""
          )}
          {selected.map((l, i) => {
            return (
              <span
                className="text-neutral-100 bg-neutral-700 p-[8px] rounded-xl"
                key={i}
              >
                {l}
              </span>
            )
          })}
        </div>
        <div className="grid grid-cols-1 justify-start gap-2 max-h-[200px] w-52 mt-1 overflow-y-auto p-2 shadow menu dropdown-content z-[1] bg-base-200 rounded-box">
          {options.map((option, i) => (
            <div key={i} className="flex gap-2">
              <input
                type="checkbox"
                defaultChecked={selected.includes(option)}
                className="checkbox"
                data-value={option}
                onClick={handleToggle}
              />
              <p>{option}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
```
