### ISSUE TITLE
Drawer breaks when tabbing (drawer-end)

### ISSUE THREAD

**Issue by Xarunoba** [saadeghi/daisyui#1470]
This still happens in the latest version, 2.46.0.
Only happens when using `drawer drawer-end`.

Same issue in a previous version: #369

**Comment by saadeghi** [comment]
That issue is fixed and here you can see there's no problem:  
https://play.tailwindcss.com/qrGY8kbhzK

If there's a problem in your project, please provide a code example so I can help
