### ISSUE TITLE
simple question | documentation of known text-* classes

### ISSUE THREAD

**Issue by talksik** [saadeghi/daisyui#1472]
I see that there are classes like text-info and text-primary and text-neutral which I see in full.css.

Is there documentation on this typography? the docs seem to just link to @tailwind/typography docs and I believe has custom typography that can be used and helpful.

Thank you!

**Comment by saadeghi** [comment]
[`text-[COLOR]`](https://tailwindcss.com/docs/text-color) or [`bg-[COLOR]`](https://tailwindcss.com/docs/background-color) etc. are Tailwind CSS utility classes for colors and Tailwind generates these class names for all colors.  
daisyUI [adds additional color names](https://daisyui.com/docs/colors/) to Tailwind CSS.  
So every daisyUI color name are available for all Tailwind CSS color class names.

`@tailwindcss/typography` is a different topic.  It's a plugin that adds some basic style like font size, weight, colors, etc.

Let me know if you have any questions.

**Comment by talksik** [comment]
Thank you @saadeghi !

I was also referring to some classes I have seen like `text-neutral-content` and others similar.

They are in full.css but no documentation I believe?
