### ISSUE TITLE
Adding DaisyUI to simple Tailwind table changes header content alignment

### ISSUE THREAD

**Issue by tonysepia** [saadeghi/daisyui#1474]
Please consider the following Tailwind example project:
https://play.tailwindcss.com/13NDVqF3tM

If you don't have daisyui added as a pluging the result looks like this:
![image](https://user-images.githubusercontent.com/104355836/210225600-c4215d4f-5874-45cd-97e5-0856824c8462.png)

But if you add the following line:
```
module.exports = {
    content: ["./src/**/*.{html,js,svelte}"],  theme: {
    extend: {},
  },
  plugins: [
    require("daisyui")  // <-------
  ],
}
```
 the output changes:
![image](https://user-images.githubusercontent.com/104355836/210225680-2b643dcf-30e5-4ac5-be96-96e9ea7d7f2d.png)

Is this normal and if Yes then what class can I add to counteract it in the most optimal way?
Thank you!

**Comment by saadeghi** [comment]
Yes it is normal. daisyUI has styles for the table so when you add daisyUI and add `table` class to your table, the style for daisyUI's table component will apply.  
If you want the `<thead>` to be centered like your first screenshot, you can add `text-center` class to `<thead>`  

Let me know if you have any question.

**Comment by tonysepia** [comment]
Thank you!
