### ISSUE TITLE
example for changing theme with toggle

### ISSUE THREAD

**Issue by cloeys** [saadeghi/daisyui#1480]
I am developing a small application in SvelteKit and I wanted to implement a toggle button to switch between light and dark mode. I wanted to use DaisyUI's Toggle component and the recommended package "theme-change" to accomplish this. My code looks like this:

````
<script>
     import { themeChange } from 'theme-change';
...
     const toggleTheme = () => {
        themeChange(false)
    }
...
</script>

<input type="checkbox" class="toggle" on:change={toggleTheme} data-toggle-theme="dark,light" />
````

This kinda works, but I always need to click the toggle twice in order for the theme to switch to the other one. It might well be I am making a mistake somewhere since I am very new to Svelte and DaisyUI, but I can't figure out what it is. I can see the data-theme element getting updated on every click on the toggle, but it's always from dark to dark to light to light etc. Any chance you could figure out what the issue is here?

**Comment by half-metal** [comment]
Try using beforeUpdate from Svelte https://svelte.dev/tutorial/update, I think it should still work even after Sveltekit migration something like this
```
<script> //theme change
    import { onMount } from "svelte"
    import { beforeUpdate } from 'svelte';
    import { themes } from "$lib/data.js"
    import { themeChange } from "theme-change"
  
    beforeUpdate(() => {
    themeChange(false)
  })
  
  export const dropdownClasses = ""
  export const btnClasses = "btn-ghost"
  export const contentClasses = "mt-16"
  </script>
```

**Comment by saadeghi** [comment]
The problem is my package `theme-change` only works by clicking on stuff and it can't read or manipulate the `checked` value of a checkbox (at current version)  

I should add this in the next version of `theme-change` ...but for now, it won't work with a checkbox. Sorry.  

So if you want to use `theme-change` don't use a checkbox toggle. Instead, use button that looks like a checkbox.  

Like this: https://stackblitz.com/edit/daisyui-sveltekit-1oeytr?file=src%2Froutes%2F%2Bpage.svelte
```svelte
<script>
import { onMount } from 'svelte'
import { themeChange } from 'theme-change'

onMount(() => {
  themeChange(false)
})
</script>

<div class="m-20">
	🌞
	<div class="inline-block w-10">
		<button data-toggle-theme="dark" data-act-class="pl-4" class="border rounded-full border-green-700 flex items-center cursor-pointer w-10 transition-all duration-300 ease-in-out">
			<span class="rounded-full w-3 h-3 m-1 bg-green-700"></span>
		</button>
	</div>
	🌚
</div>
```

let me know if you have any questions.
