### ISSUE TITLE
feat: Vertical Range Slider

### ISSUE THREAD

**Issue by MentalGear** [saadeghi/daisyui#1483]
It'd be great if we had a standardized vertical range slider. I know this is rather tricky to do, but aren't framework there for this. :)

Here's a cross browser approach which should also be helpful when ignoring the JS wrap:
https://dev.to/konnorrogers/creating-a-vertical-slider-using-input-typerange-1pen 

What do you think?

**Comment by MentalGear** [comment]
There's also a much easier CSS only trick I just found out about which is using transforms.
https://stackoverflow.com/a/29888724/5037146

**Comment by MentalGear** [comment]
Might be the better approach. But will wait on your input.

**Comment by saadeghi** [comment]
I'm not sure about this one. A vertical range slider is not a common thing and there's no such thing in HTML...  
So just like the example you mentioned, we can rotate a horizontal range slider to get what we want.

Here's a quick example to fit it in a div:  
https://play.tailwindcss.com/nlZ1immSxf
```html
<div class="m-10 w-6 h-40 relative bg-red-200">
  <input type="range" min="0" max="100" value="40" class="range w-40 -rotate-90 origin-left absolute -bottom-3 left-3" />
</div>
```

Let me know if you have any questions.

**Comment by TheBrenny** [comment]
It kinda is now... https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_writing_modes/Vertical_controls#range_sliders_meters_and_progress_bars .

I'll give it a crack, I guess!

**Comment by saadeghi** [comment]
@TheBrenny Interesting!
