### ISSUE TITLE
SvelteKit install guide may be out of date.

### ISSUE THREAD

**Issue by rogadev** [saadeghi/daisyui#1487]
For reference: https://daisyui.com/docs/install/

Setting up a current SvelteKit project will generate a `tailwind.config.cjs` file, whereas daisyUI docs seem to indicate it is a `.js` file.

If we click on the StackBlitz lin for SvleteKit's setup example on the daisyUI `/docs/install` page (https://stackblitz.com/edit/daisyui-sveltekit?file=package.json) we are given an outdated SvelteKit setup to look at. If I edit my `svelte.config.js` file to look like the one in this example, I immediately get errors trying the dev server in my own project.

For reference, I've set up my SvelteKit project using the TailwindCSS documentation, which is my most commonly used reference for setting up TailwindCSS in any given project - SvelteKit, Nuxt, Astro, etc.. I'm using TypeScript, and selected yes to eslint, prettier, and vitest.

**Comment by saadeghi** [comment]
I will update it today. Thank you for reporting

**Comment by saadeghi** [comment]
Example is updated not: https://stackblitz.com/edit/daisyui-sveltekit
