### ISSUE TITLE
Add pointer-events-none by default to .collapse:focus class

### ISSUE THREAD

**Issue by kimdre** [saadeghi/daisyui#1508]
To close a [collapse container](https://daisyui.com/components/collapse/) you need to click outside of it to remove the focus. Imho closing it should also be possible with a second click inside the container.
This is at the moment only possible by using the [collapse with a checkbox](https://daisyui.com/components/collapse/#collapse-with-checkbox).

As a workaround you can add this to your custom .css file:

```css
.collapse:focus {
    @apply pointer-events-none;
}
```

Can we perhaps have this feature implemented by default for non-checkbox collapses?

**Comment by saadeghi** [comment]
Regarding the conversation on the PR, I couldn't find a CSS solution for this to get closed by both losing focus or second click.  
The only solution for this is writing some JS to uncheck the checkbox when it's clicked outside.
