### ISSUE TITLE
Button with type attributes seem get overriden by tailwindcss

### ISSUE THREAD

**Issue by nabilshuja** [saadeghi/daisyui#1512]
By specifying type attribute on the button element, tailwindcss would tend to override the class used with daisyui. 

For example in this image, I specified type as `button` and it had its `background-color` overridden  
![image](https://user-images.githubusercontent.com/25796380/211727836-f1795e8a-037f-40b0-bb87-3cb98a9efdb4.png)

**Comment by saadeghi** [comment]
It's hard to help when you don't provide a code example but I guess your tailwind config is not correct.
your reset style is being generated after component styles which is wrong.

There's no such problem with buttons in the library: https://play.tailwindcss.com/RBjXAEgSBm

**Comment by nabilshuja** [comment]
>It's hard to help when you don't provide a code example

Apologies, I'll keep that in mind next time.
  
>your reset style is being generated after component styles which is wrong.

You are right, mistake on my part for importing components before base..

Jumped the gun on making the issue. 😓
