### ISSUE TITLE
Feature Request: Set bg and text color with one utility.

### ISSUE THREAD

**Issue by acalvino4** [saadeghi/daisyui#1521]
The color pairs such as `primary`/`primary-content` and `secondary`/`secondary-content` work great for coloring buttons through a single class (such as `btn-primary` and `btn-secondary`), but it would also be awesome if they could be used for general content areas as well. For example, when I set `bg-primary` it also applies `text-primary-content`. After all, that's why these pairs exist, right? This would not work in the reverse order. Text color could certainly be overridden, but my guess is that overall this approach will result in far less `text-<color>` classes having to be used at all, and will make it easy to ensure content is always legible on its background by default. It would also deal with the issue where maybe no `text-` class is applied bc it happens to be the same or similar to the base color, but looks wrong when the theme switches.

Anyway, that's the general idea - but I am pretty sure DaisyUI sets their colors simply as an extension of tailwinds theming system, so the above might not work. Additionally, there may be some backword compatibility concerns.

Hence, I suspect that the better way of achieving the above would be with `content-` or `section-` prefixes that set the foreground and background appropriately at once. We would probably want `content-base` applied at the root (which I guess it effectively is already with `bg-base-100` and `text-base-content`). Then we just override to a new foreground/background pair with `content-primary` (or similar, assuming 'content-' prefix).

If I'm missing a feature that already exists, just let me know!

**Comment by acalvino4** [comment]
> But instead of use content- or section- that you suggested, I'm thinking about using the color name itself as the class name.
Even better idea 😄

**Comment by fini** [comment]
if you are using the name itself as the class name, beware of possible clashes, there are probably a lot of info, success and error classes used out in the wild..

**Comment by saadeghi** [comment]
> if you are using the name itself as the class name, beware of possible clashes, there are probably a lot of info, success and error classes used out in the wild..

Yes that would be dangerous 🤔 thanks for mentioning

**Comment by saadeghi** [comment]
I'm not sure if it's a good idea or not but what if we add text color to all the daisyUI `bg-*` class names by default (low CSS specificity).
```css
:where(.bg-primary){
  @apply text-primary-content;
}
:where(.bg-secondary){
  @apply text-secondary-content;
}
:where(.bg-accent){
  @apply text-accent-content;
}
:where(.bg-neutral){
  @apply text-neutral-content;
}
:where(.bg-base){
  @apply text-base-content;
}
:where(.bg-info){
  @apply text-info-content;
}
:where(.bg-success){
  @apply text-success-content;
}
:where(.bg-warning){
  @apply text-warning-content;
}
:where(.bg-error){
  @apply text-error-content;
}
```

So whenever someone uses `bg-primary` it will set the background name (as expected) but it also changes the text color to `primary-content` by default. unless the developer changes the text color using a utility class.

**Comment by saadeghi** [comment]
This will create many problems and confusion.  
Also it will require everyone to learn new utility class names (which is not extended from Tailwind's color utility classes like `text-*` or `bg-*`) and they are not going to fix a problem. They would be just alias for another alias.
I'm closing this issue for now
