### ISSUE TITLE
Help needed for scrollbar behaviour while using drawer

### ISSUE THREAD

**Issue by dk009dk** [saadeghi/daisyui#153]
daisyUI :2.13.2
tailwindcss:2.2.7

[Play Tailwind Link](https://play.tailwindcss.com/YKVNFMZ9XH)
https://play.tailwindcss.com/YKVNFMZ9XH

I'm using two daisyUI  drawers.
One drawer for Navbar and another one for sidebar.
But problem is related to scroll behavior.
You can see in [play tailwind](https://play.tailwindcss.com/YKVNFMZ9XH) there are two scrollbars .I want only one with full page scrolling.

![Capture-11](https://user-images.githubusercontent.com/60841968/130668108-06cc26ed-bb21-4179-8f89-07119e669337.PNG)

Can anyone help me in this case ??
Thanks and regards.

Thanks to @saadeghi for this amazing ui kit

**Comment by saadeghi** [comment]
@dk009dk That's a weird scenario and I don't think it's a good UX practice either.  
Anyhow, can be fixed like this: https://play.tailwindcss.com/JqjVjltIKB?file=css  
I added a `inner-drawer` class and this CSS:
```
.inner-drawer .drawer-content,
.inner-drawer .drawer-side{
  height: auto;
  max-height: none;
}
```
