### ISSUE TITLE
Feature Request: add `input-default` to reset input style back to default (unstyled background color)

### ISSUE THREAD

**Issue by fnimick** [saadeghi/daisyui#1537]
This would be useful to e.g. turn an `input-success` back into a standard `input` based on a focus or hover selector.

Use case: `<input class="input input-success focus:input-default" ... />`

I've accomplished this with the following in my main tailwind css file:
```
@layer components {
  .input-default {
    border-color: hsl(var(--b1) / var(--tw-bg-opacity));
  }
  .input-default:focus {
    outline: 2px solid hsla(var(--bc) / 0.2);
    outline-offset: 2px;
  }
}
```

**Comment by fnimick** [comment]
Resolved in #1538

**Comment by saadeghi** [comment]
Thank you for the PR but I don't think this will be useful for the majority of developers.  
I think class names like `input-success` are for validation proposes. For example, when the value is valid you add `input-success` using JS and when it's not valid you add `input-error`. Or you just remove those classes when the field is empty, etc.  
So I'm not sure what would be the goal of having an input `success` but removing the color on focus. When it's focused the value is the same...

Anyway, if you really need this behavior on your project you can use a class name like `[&:not(:focus)]:input-success` so the success color only gets applied when input is not focused. But I don't think having a `input-default` would be useful.

**Comment by fnimick** [comment]
Thank you so much! I had no idea you could do a "not focused" selection with Tailwind. All the docs I found suggested applying a style, then applying a different style for the focused variant, which is why I wanted to create a "return to default" input style.
