### ISSUE TITLE
select dropdown in Chromium is not decorated

### ISSUE THREAD

**Issue by vfilatov** [saadeghi/daisyui#1540]
https://daisyui.com/components/select/
It works fine in Firefox 110.0b1 (64-bit)
![image](https://user-images.githubusercontent.com/1231330/213210016-dfbf23bd-88ca-41b0-9c34-52d9dfe59543.png)

Not in Chromium 109.0.5414.74 (Official Build) snap (64-bit)
![image](https://user-images.githubusercontent.com/1231330/213210306-4bef6f33-61ae-4be0-9c8c-2f76b3d42591.png)

**Comment by fini** [comment]
> Styling the <option> element is highly limited. Options don't inherit the font set on the parent. In Firefox, only [color](https://developer.mozilla.org/en-US/docs/Web/CSS/color) and [background-color](https://developer.mozilla.org/en-US/docs/Web/CSS/background-color) can be set however in Chrome or Safari it's not possible to set any properties.

- [Source: MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option)

**Comment by saadeghi** [comment]
Indeed there's no way to style the `<option>` tag. Each browser and each OS uses a different style and CSS can't really fix that. The screenshots you posted are from Windows I guess. On MacOS, it's completely different and on iOS and Android it's not even a dropdown. It's a fullscreen modal.

There are JS solutions that replace the standard `<select>` element with `<div>`s and lists so it can be styled using CSS. For example: https://headlessui.com/react/listbox
