### ISSUE TITLE
Daisyui colors not using custom prefix

### ISSUE THREAD

**Issue by marco-beduschi** [saadeghi/daisyui#1541]
Hello!

I'm using daisyui with a custom prefix "ui-" and I expected the custom colors provided by the library to respect that configuration, meaning "bg-base-100" would translate to "ui-bg-base-100" for example, but apparently they do not.

Just to confirm, is this the intended behaviour?

Playground: https://play.tailwindcss.com/1ZCeyGvaEi

Thanks! 😄

**Comment by saadeghi** [comment]
The difference between a class name like `.btn` and a class name like `.bg-base-100` is that the first one is added by daisyUI but the second one is getting added by Tailwind CSS.  
daisyUI actually extends Tailwind CSS colors and adds new color names like `primary`, `secondary`, etc.  

So, yes it is how it should work.  
You might also want to [add prefixes to all Tailwind CSS class names](https://tailwindcss.com/docs/configuration#prefix) if you want

Let me know if you have any questions

**Comment by marco-beduschi** [comment]
Thanks for the quick response!

I guess my mental model was incorrect, as I assumed "everything related to daisyui would be prefixed". It works either way, thanks! 😄
