### ISSUE TITLE
Custom prefixes for CSS variables

### ISSUE THREAD

**Issue by chartung17** [saadeghi/daisyui#1543]
There does not appear to be any way to add a custom prefix to the CSS variables created by daisyUI, which can result in conflicts.

In my case, I was attempting to apply custom CSS to the control panel of a Craft CMS site, but the secondary color did not appear in the control panel. One of the CSS files that Craft uses for the control panel uses the variable `--s` to mean 8px, and that `--s` overrides the `--s` which daisyUI uses to indicate secondary color.

**Comment by saadeghi** [comment]
Currently there's no config for prefixing CSS variables and probably wouldn't be available anytime soon but you can use a Post CSS plugin like this to rename CSS variables:
https://www.npmjs.com/package/postcss-variables-prefixer-plugin
