### ISSUE TITLE
Conditionally show tooltip - but always showing the child of the tooltip :-)

### ISSUE THREAD

**Issue by gkatsanos** [saadeghi/daisyui#1549]
Assuming you use tooltips to display an error for a form, e.g.
```html
    <div class="tooltip tooltip-open tooltip-error" data-tip="error">
      <input
        class="input input-bordered w-full"
        class:input-error={form?.incorrect}
        type="password"
        required
        placeholder="Your password"
        name="password"
        disabled={isLoading}
        bind:value={password}
      />
    </div>
```

You've got a `form.incorrect` that should display the `.tooltip` when `TRUE`. But how do you do this when the child element (the text input) has to always be visible? (besides duplicating the entire block...)

**Comment by saadeghi** [comment]
You just need to conditionally show/hide the class names and `data-tip` attribute whenever needed.  
Assuming you're using Svelte, you can conditionally show a set of class names like this:
```html
<input class="input input-bordered w-full {validation1 ? 'input-error' : ''}"/>
```
And you can conditionally show/hide the `data-tip` attribute like this
```html
data-tip={validation1 || null}
```

Example code:
```svelte
<script>
  let validation1 = false;
  let validation2 = "There is an error";
</script>

<div 
  class="m-6 inline-block {validation1 ? 'tooltip tooltip-open tooltip-error' : ''}"
  data-tip={validation1 || null}
>
  <input class="input input-bordered w-full {validation1 ? 'input-error' : ''}"/>
</div>

<div
  class="m-6 inline-block {validation2 ? 'tooltip tooltip-open tooltip-error' : ''}"
  data-tip={validation2 || null}
>
  <input class="input input-bordered w-full {validation2 ? 'input-error' : ''}"/>
</div>
```

Let me know if you have any questions

**Comment by gkatsanos** [comment]
Ah ok, so basically `tooltip-open` is enough to toggle and conditionally show/ hide the tooltip!

**Comment by saadeghi** [comment]
`tooltip-open` makes it to be visible by default (instead of hover) but f you want it to conditionally have or not have a tooltip completely, you should add remove all those class names.

**Comment by gkatsanos** [comment]
thank you

**Comment by gkatsanos** [comment]
I think a nice doc section for building form groups + validation would be helpful!
