### ISSUE TITLE
bug: Menu Title Color Inheritance Issue

### ISSUE THREAD

**Issue by sergebenard** [saadeghi/daisyui#1560]
### What version of daisyUI are you using?

_2.47.0_

### Describe your issue

Using Menu Titles as documented, when I apply a colour to the menu background and text, the Titles in the menu do not inherit the colour change as specified; it remains as the Title's default text colour.

To replicate:

_Menu item and menu title appear as expected defaults._
```html
<ul class="menu bg-base-100 w-56 p-2 rounded-box">
  <li class="menu-title">
    <span>Category</span>
  </li>
  
  <li>
    <a>Item 1</a>
  </li>
</ul>
```

_Menu with secondary colour specified for background and text elements shows menu item' text colour changes as expected, but the menu title remains as default._
```html
<ul class="menu bg-secondary text-secondary-content w-56 p-2 rounded-box">
  <li class="menu-title">
    <span>Category</span>
  </li>

  <li>
    <a>Item 1</a>
  </li>
</ul>
````

It's not a big deal, but it'd be nice to have menu titles' colours adapt to inheritance as the menu items do. 😃 

Thanks so much for your work!!

Serge

### What browsers are you seeing the problem on?

Chrome, Firefox, Edge

### Reproduction URL (optional)

https://play.tailwindcss.com/UiyWTPsI6t

**Comment by saadeghi** [comment]
Fixed in the latest version: `2.50.0`   
https://play.tailwindcss.com/g7QsWDq3UH?file=config
