### ISSUE TITLE
docs: alternative for placeimg api

### ISSUE THREAD

**Issue by chukwumaokere** [saadeghi/daisyui#1562]
### On which page do you see this issue?

https://daisyui.com/components/avatar/

### Describe the issue

PlaceIMG is being sunset so I think we should find an alternative for the images used in the documentation.
Unsplash, which is free or Lorem Picsum as well.

I can update the docs and make a PR for this update.

Issue noted below:
https://placeimg.com/192/192/people
![image](https://user-images.githubusercontent.com/16673873/214951311-f0b38850-c3a3-4f55-96cd-4f086089f197.png)
![image](https://user-images.githubusercontent.com/16673873/214951722-e2b48abe-e788-4ff0-acdc-0ee1bc660aba.png)

### What browsers are you seeing the problem on?

All

**Comment by saadeghi** [comment]
Thank you for reporting.  
It's sad. PlaceIMG was a good service.  

I think it's better if I pick a few good images and host them myself this time. They would load faster and the it would look better than being random.

**Comment by chukwumaokere** [comment]
Fair enough, I can leave you to that! 
I also liked placeimg :( Pretty sad to see it go!
