### ISSUE TITLE
bug:  collapse arrow  in RTL mode transition issue

### ISSUE THREAD

**Issue by faridvatani** [saadeghi/daisyui#1564]
### What version of daisyUI are you using?

V.2.49.0

### Describe your issue

 The icon transition is not corrected by a collapse arrow in RTL mode.
 

https://user-images.githubusercontent.com/18399665/215311980-f24861d7-50e3-4019-891e-a87b1fcf335c.mov

### What browsers are you seeing the problem on?

Chrome, Safari, Firefox, Other

### Reproduction URL (optional)

https://play.tailwindcss.com/F6gJTHZyTb

**Comment by saadeghi** [comment]
Fixed in the latest version `2.50.0`: https://play.tailwindcss.com/qLSKfCDk6k
But if your page is RTL, you should have `dir=rtl` in your root element of course.
