### ISSUE TITLE
bug: Navbar with dropdown, center logo and icon

### ISSUE THREAD

**Issue by Anotso** [saadeghi/daisyui#1565]
### What version of daisyUI are you using?

v2.49.0

### Describe your issue

The menu takes up a lot of the screen even when hidden.

- Full screen hidden:
![image](https://user-images.githubusercontent.com/40184359/215357651-a6845ab8-fb5a-4122-9f94-3fc75e8a836b.png)

- Full screen visible:
![image](https://user-images.githubusercontent.com/40184359/215357678-e9576916-358c-43bc-b392-b1a0873fd9fa.png)

- Mobile hidden:
![image](https://user-images.githubusercontent.com/40184359/215357709-77101663-e0e8-4c76-986c-2fcd74f627b3.png)

- Mobile visible:
![image](https://user-images.githubusercontent.com/40184359/215357723-a70ed0ad-89ad-4bc5-9c77-c5f6a426e0e0.png)

**Comment by saadeghi** [comment]
I'm not sure what is the problem here?  
How it looks like and how do you want it to look like?  

`dropdown-content` is visually hidden and when we click on the button, it gets visible. It's not getting any space because it's has `position: absolute`
