### ISSUE TITLE
bug: Tailwind latest version issue with Node.walk (TypeError)

### ISSUE THREAD

**Issue by Loosie94** [saadeghi/daisyui#1566]
### What version of daisyUI are you using?

2.47.0

### Describe your issue

Issue with node.walk function.
Error: `TypeError: node.walk is not a function`

See also: https://github.com/postcss/postcss-selector-parser/issues/265
Seems like the latest Tailwind version is having trouble with DaisyUI

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
I don't think it's a problem from `tailwindcss` + `daisyui` because they work fine on other build tools.  
Maybe it's about Parcel. Can you try to build the same style without Parcel?

**Comment by Loosie94** [comment]
I tried but unfortunately I get the same error.
Reverting to Tailwind version: 3.0.24 worked for me for now.

**Comment by saadeghi** [comment]
Can you give me a reproduction repo so I can reproduce the issue myself?

**Comment by Loosie94** [comment]
Yes, I created one here: https://github.com/Loosie94/daisyui-issue
Is deleted the most stuff inside the folders, because I found this while working for a client.
But the setup is the same.
Hope this helps!

**Comment by Loosie94** [comment]
This had probably to do with my own setup. I close this one, thanks anyway!
