### ISSUE TITLE
bug: breadcrumb should support an ordered list (SEO)

### ISSUE THREAD

**Issue by digitalcortex** [saadeghi/daisyui#1569]
### What version of daisyUI are you using?

v2.49.0

### Describe your issue

I tried using breadcrumbs from [example page](https://daisyui.com/components/breadcrumbs/) but the source code is written with `<ul>`. Changing `<ul>` to `<ol>` didn't help probably because DaisyUI does not include style definitions for an ordered list inside the breadcrumb tag.

Using ordered list `<ol>` for breadcrumbs is semantically better and may be important for SEO. By using ordered list you are telling the search engine that the order of the links inside your breadcrumb is important. Ordered list for breadcrumbs creates a meaningful hierarchy for your internal navigation

Is there any way to update class definition to support `<ol>` tags as well?

**Comment by amirsinaa** [comment]
Hi,
I've fixed this issue: #1648 
@saadeghi @digitalcortex

**Comment by saadeghi** [comment]
Thank you @amirsinaa. This will be merged today
