### ISSUE TITLE
Click the dropdown button again to close dropdown

### ISSUE THREAD

**Issue by kpaquino2** [saadeghi/daisyui#157]
Is there a way to make it so the dropdown closes when the dropdown button is clicked while the dropdown is open?

**Comment by birdhackor** [comment]
I'm trying to make dropdown menu close when dropdown button click again or click other area but keep dropdown menu open when click dropdown content item.

The first idea was to use a state to simply control it, but this wasn't easy because the blur event would be triggered when the user clicked on the dropdown content item and vice versa. This makes it not easy to distinguish between clicking on a dropdown menu and clicking on a blank area.

I finally came up with a solution. But I don't think it's an elegant way.

Is there a better way to make this function?

I use React to do this.

```
function App() {
  const [themeMenuOpened, setThemeMenuOpened] = useState(false);
  const themeMenu = useRef(null);
  const themeMenuButton = useRef(null);
  useEffect(() => {
    if (!themeMenuOpened) {
      document.activeElement.blur();
    } else if (
      themeMenuOpened &&
      !themeMenu.current.contains(document.activeElement)
    ) {
      setThemeMenuOpened(false);
    }
  }, [themeMenuOpened]);

  return (
    <>
      <div className="navbar sticky top-0 shadow-lg bg-neutral text-neutral-content">
        <div className="flex-1 px-2 mx-2">
          <span className="text-lg font-bold">daisyUI</span>
        </div>
        <div className="flex-none">
          <div ref={themeMenu} className="dropdown dropdown-end">
            <div
              ref={themeMenuButton}
              tabIndex="0"
              className="btn btn-square btn-ghost"
              onBlur={(e) => {
                setThemeMenuOpened(false);
              }}
              onClick={(e) => {
                if (themeMenuOpened) {
                  setThemeMenuOpened(false);
                } else {
                  setThemeMenuOpened(true);
                }
              }}
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                className="inline-block w-6 h-6 stroke-current"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M4 6h16M4 12h16M4 18h16"
                ></path>
              </svg>
            </div>
            <ul
              tabIndex="0"
              className="p-2 shadow menu dropdown-content bg-base-100 rounded-box w-52 text-neutral"
              onBlur={(e) => {
                b.current.focus();
              }}
              onFocus={(e) => {
                setThemeMenuOpened(true);
              }}
            >
              <li>
                <a>Item 1</a>
              </li>
              <li>
                <a>Item 2</a>
              </li>
              <li>
                <a>Item 3</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </>
  );
}
```

**Comment by david-feldstein** [comment]
A simple solution for this:
When you add event listener for "onclick", then element is already focused when you check. But when you add "onmousedown" listener, element is focused after this event occurs. So it gives you ability to check if it was previously focused and there is no need to handle state in a variable.

```
<div ref={themeMenu} className="dropdown dropdown-end">
	<div tabindex="0" class="btn" onmousedown="checkAndCloseDropDown(e)"></div>
	<ul tabindex="0" class="p-2 shadow menu dropdown-content">
		...
	</ul>
</div>

function checkAndCloseDropDown(e){
		if(e.target && e.target.matches(':focus')){
			console.log('should close');
			setTimeout(function(){
			    e.target.blur();
            }, 0);
        }
    }
```

**Comment by saadeghi** [comment]
Here's another example using JS to add/remove `dropdown-open` class:  
https://play.tailwindcss.com/Xavjuk4SGS

**Comment by cangSDARM** [comment]
> Here's another example using JS to add/remove `dropdown-open` class: https://play.tailwindcss.com/Xavjuk4SGS

It does not solve the effect of closing when clicking on other elements.

This should be the basic effect of a `Dropdown` component, at least this flaw should be prompted in the document or implemented in daisy-ui.
Otherwise, this component is very tasteless.

**Comment by saadeghi** [comment]
That's not a flaw. That's just how native CSS `: focus` works. When you click a focused element, it should not and will not lose focus.  
However I can add a open/close functionality with a hidden checkbox (similar to `collapse` component) but that way, dropdown will only close if it's clicked again. It won't get closed when clicked outside.

More personalized functionality can be achieved with JS tho.

**Comment by theodosiskats** [comment]
If you are using React then it can be done by useState. Here is an example code that is working on a navbar:


//Here we set the state for the display and the button, if clicked or not. //
  const [menuDisplay, setmenuDisplay] = useState(true);
  const [displayMenuStyle, setdisplayMenuStyle] = useState('');

  const showMenu = () => {
    setmenuDisplay(!menuDisplay)
    if (menuDisplay) {
      setdisplayMenuStyle('')
    } else {
      setdisplayMenuStyle('none')
    }
    return displayMenu
  }

// Here we pass the displayMenu state ('string') that is set to '' empty or 'none'. //
      <div className="flex-none text-neutral">
        <div className="dropdown dropdown-end" onClick={showMenu}>
          <div tabIndex="0" className="m-1 btnHamburger mr-5">
            <i className="fal fa-bars text-2xl text-white" />
          </div>
          <ul tabIndex="0" style={{ display: displayMenuStyle}} className="p-2 shadow menu dropdown-content bg-slate-200 rounded-box w-52 mr-5 ">
            <li className="text-slate-600">
              <Link to='/'>Item 1</Link>
            </li>
            <li className="text-slate-600">
              <Link to='/'>Item 2</Link>
            </li>
            <li className="text-slate-600">
              <Link to='/'>Item 3</Link>
            </li>
          </ul>
        </div>
      </div>
    </div>

A quick explanation of the logic for noobs like myself....

We set 2 states, the one is checking if the button is clicked for the first time or the second. So we use the true or false to check that.

Its initial state is set to true because for some reason when it is set to false the first time you click it it will open and close instantly the menu ? no clue why, maybe the masters can help on that one.

Then we check if the menuDisplay state is true. If it's true then display is set to '' empty string and the menu pops up. If its false then the display is set to 'none' and the menu disappears.

Weird but it's working.
Cheers!

**Comment by saadeghi** [comment]
thanks @theodosiskats  
Here's another example with React using `useRef` to handle focus instead of using states: https://codesandbox.io/s/eloquent-tree-bu2dt?file=/src/App.js

**Comment by oben01** [comment]
for those who use angular 
```typescript
import { Directive, ElementRef, HostListener } from "@angular/core";

@Directive({
  selector: '[appFocusRemover]'
})
export class FocusRemoverDirective {

  constructor(private elRef: ElementRef) {}

  @HostListener('click') onClick() {
    this.elRef.nativeElement.parentElement.classList.toggle('dropdown-open');
    if (document.activeElement instanceof HTMLElement) {
      document.activeElement.blur();
    }
  }
}
```

```typescript
<div *ngIf="(isUserAuthenticated$ | async)" class="dropdown dropdown-end" >
      <label appFocusRemover tabindex="0" class="btn btn-ghost btn-circle avatar" >
        <div class="w-10 rounded-full">
          <img src="https://api.lorem.space/image/face?hash=33791">
        </div>
      </label>
      <ul appFocusRemover tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52" >
        <li>
          <a>
            Profile
          </a>
        </li>
        <li><a routerLink="/dashboard" >Dashboard</a></li>
        <li><a>Settings</a></li>
        <li><a (click)="Logout()">Logout</a></li>
      </ul>
    </div>
```

**Comment by whoisYeshua** [comment]
I decide to refuse the opportunity to open a dropdown with focus because it adds more problems in my case. 
Implementation on svelte:
```js
  let isDropdownOpen= false // default state (dropdown close)

  const handleDropdownClick = () => {
    isDropdownOpen = !isDropdownOpen// togle state on click
  }

  const handleDropdownFocusLost = ({ relatedTarget, currentTarget }) => {
    // use "focusout" event to ensure that we can close the dropdown when clicking outside or when we leave the dropdown with the "Tab" button
    if (relatedTarget instanceof HTMLElement && currentTarget.contains(relatedTarget)) return // check if the new focus target doesn't present in the dropdown tree (exclude ul\li padding area because relatedTarget, in this case, will be null)
    isDropdownOpen = false
  }
```
Manually control the visibility of the dropdown without relying on the "focus" event:
```html
<div class="dropdown" on:focusout={handleDropdownFocusLoss}>
		<button class ="btn m-1" on:click = {handleDropdownClick} >
		{#if isDropdownOpen}
			<svg> <title>Close Dropdown</title> </svg>
		{:else}
			<svg> <title>Open Dropdown</title> </svg>
		{/if}
		</button>
		<ul 
                        class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52" 
                        style:visibility={isDropdownOpen ? 'visible' : 'hidden'}>
			<li><button class="btn text-slate-300">Item 1</button></li>
			<li><button class="btn text-slate-300">Item 2</button></li>
		</ul>
	</div>
```
[REPL](https://svelte.dev/repl/4c5dfd34cc634774bd242725f0fc2dab?version=3.46.4)

**Comment by reasecret** [comment]
I've used alpine js for this and looks like it's working well...

```
<div x-data="{ showMenu: null }">
    <div class="dropdown dropdown-left">
        <label tabindex="0" class="btn m-1" x-on:click="showMenu = '{{ $item->id }}'">Click</label>
            <ul tabindex="0" x-on:click.away="showMenu = false" x-show="showMenu  === '{{ $item->id }}'" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
                <li><a href="#">Edit</a></li>
                <li><a href="#">Delete</a></li></li>
            </ul>
    </div>
</div>
```

**Comment by mehdijai** [comment]
For my case, I added a event listener to blur() the focused item whenever `.dropdown-content>li` got clicked.
```vue
onMounted(() => {
  const dropdownContent = document.querySelectorAll(".dropdown-content>li");
  dropdownContent.forEach((element) => {
    element.addEventListener("click", () => {
      document.activeElement.blur();
    });
  });
});
```

**Comment by msh2050** [comment]
> I decide to refuse the opportunity to open a dropdown with focus because it adds more problems in my case. Implementation on svelte:


@whoisYeshua  for typescript, I have to add type
```
const handleDropdownFocusLoss = ({
		relatedTarget,
		currentTarget
	}: {
		relatedTarget: any;
		currentTarget: any;
	}) => {
		// use "focusout" event to ensure that we can close the dropdown when clicking outside or when we leave the dropdown with the "Tab" button
		if (relatedTarget instanceof HTMLElement && currentTarget.contains(relatedTarget)) return; // check if the new focus target doesn't present in the dropdown tree (exclude ul\li padding area because relatedTarget, in this case, will be null)
		isDropdownOpen = false;
	};
```

instead of any what is `relatedTarget`, `currentTarget` types?!

**Comment by whoisYeshua** [comment]
@msh2050 

```ts
currentTarget: HTMLDivElement
``` 
Since the handler is hanging on the `div`

```ts 
relatedTarget: Element | null
``` 
`Element` since it is necessary to cover all possible focusable elements -  `HTMLElement` & `SVGElement` (yup, `SVGElement` can be focusable if we add `tabindex="0"` to it)
`null` for all other elements which not focusable

**Comment by msh2050** [comment]
if I change types from any I will get the following error:
```
[{
	"resource": "******/src/lib/components/Navbar.svelte",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "2322",
	"severity": 8,
	"message": "Type '({ relatedTarget, currentTarget }: { relatedTarget: HTMLDivElement; currentTarget: Element | null; }) => void' is not assignable to type 'FocusEventHandler<HTMLDivElement>'.\n  Types of parameters '__0' and 'event' are incompatible.\n    Type 'FocusEvent & { currentTarget: EventTarget & HTMLDivElement; }' is not assignable to type '{ relatedTarget: HTMLDivElement; currentTarget: Element | null; }'.\n      Types of property 'relatedTarget' are incompatible.\n        Type 'EventTarget | null' is not assignable to type 'HTMLDivElement'.\n          Type 'null' is not assignable to type 'HTMLDivElement'.",
	"source": "ts",
	"startLineNumber": 29,
	"startColumn": 25,
	"endLineNumber": 29,
	"endColumn": 36
}]```

**Comment by whoisYeshua** [comment]
@msh2050 

I'm personally use this code:

```ts
const handleDropdownFocusLoss = ({ relatedTarget, currentTarget }: FocusEvent) => {
	if (
		relatedTarget instanceof Element &&
		(currentTarget as HTMLDivElement).contains(relatedTarget)
	) return;
	isDropdownOpen = false;
};
```

But you can try something like this:
```ts
type DivFocusEvent = FocusEvent & { currentTarget: HTMLDivElement };

const handleDropdownFocusLoss = ({ relatedTarget, currentTarget }: DivFocusEvent) => {
	if (relatedTarget instanceof Element && currentTarget.contains(relatedTarget)) return;
	isDropdownOpen = false;
};
```
or:
```ts
const handleDropdownFocusLoss: svelte.JSX.FocusEventHandler<HTMLDivElement> = ({
	relatedTarget,
	currentTarget
}) => {
	if (relatedTarget instanceof Element && currentTarget.contains(relatedTarget)) return;
	isDropdownOpen = false;
};
```

**Comment by chasoft** [comment]
My case is… I want to `close the popup menu` when `menuItem is clicked`

A simple solution is to add this onClick to the menuItem:

```js
onClick={() => {
  if (document.activeElement instanceof HTMLElement) {
    document.activeElement.blur()
  }
}}
```

**Comment by Yokoi-Tofu** [comment]
What if I want to do the same thing by `drowdown-hover`?

**Comment by saadeghi** [comment]
@Yokoi-Tofu you mean open the menu on first hover and close it on second hover? 🤔

**Comment by Yokoi-Tofu** [comment]
@saadeghi 
I want to click on the `dropdown-hover` menu to close it.
But this is a hover, not a focus, so `document.activeElement.blur()` doesn't work.

**Comment by boriscy** [comment]
> For my case, I added a event listener to blur() the focused item whenever `.dropdown-content>li` got clicked.
> 
> ```
> onMounted(() => {
>   const dropdownContent = document.querySelectorAll(".dropdown-content>li");
>   dropdownContent.forEach((element) => {
>     element.addEventListener("click", () => {
>       document.activeElement.blur();
>     });
>   });
> });
> ```

This has actually worked with Svelte, thanks
> document.activeElement.blur()

**Comment by abu-tech** [comment]
> 



> @kpaquino2 It's working with `:focus` so as long as the button is focused, drop-down will remain open. But you can use JavaScript to remove the focus on second whenever you want.
> 
> Please let me know if you have any questions.

@saadeghi can you lemme know the code for the same i didnt know how to do it in react

**Comment by eugeneo** [comment]
React, this is what I ended up with:
```
const clickRef = useRef(0);

if (!user || user.isAnonymous) {
    return (
        <Link className='btn btn-secondary' to='/login'>
            Login
        </Link>
    );
}

return (
    <div className='dropdown dropdown-end ml-4'>
        <Avatar
            user={user}
            onFocus={() => (clickRef.current = 0)}
            onClick={(event) => {
                if (++clickRef.current === 2) {
                    event.currentTarget.blur();
                }
            }}
        />
...
```

**Comment by ASoldo** [comment]
This situations make me wanna puke every time I say some good things about framework/library to someone (boss, coworker)... and then we are not able to close on click... and then some random dude comes here and give some solution and it actually works. I wonder how many of this bs situations will I encounter after I ???finish??? this project.
Like some said before me: Love the visuals but god damn do I hate stupid bs. 
Thank you @serkodev, now it works. -.-'

**Comment by saadeghi** [comment]
> This situations make me wanna puke every time I say some good things about framework/library to someone (boss, coworker)... and then we are not able to close on click... and then some random dude comes here and give some solution and it actually works. I wonder how many of this bs situations will I encounter after I ???finish??? this project. Like some said before me: Love the visuals but god damn do I hate stupid bs. Thank you @serkodev, now it works. -.-'

daisyUI is a CSS library and there is no `click` event on CSS. As I mentioned, dropdown works with CSS `:focus`.  
You can use JS whenever you need but unfortunately you can't expect a CSS library to handle JavaScript click events.

**Comment by oancea-ilie** [comment]
> If you are using React then it can be done by useState. Here is an example code that is working on a navbar:
> 
> //Here we set the state for the display and the button, if clicked or not. //
> 
> ```
>   const [menuDisplay, setmenuDisplay] = useState(true);
>   const [displayMenuStyle, setdisplayMenuStyle] = useState('');
> 
>   const showMenu = () => {
>     setmenuDisplay(!menuDisplay)
>     if (menuDisplay) {
>       setdisplayMenuStyle('')
>     } else {
>       setdisplayMenuStyle('none')
>     }
>     return displayMenu
>   }
> ```
> 
> // Here we pass the displayMenu state ('string') that is set to '' empty or 'none'. //
> 
> ```
>       <div className="flex-none text-neutral">
>         <div className="dropdown dropdown-end" onClick={showMenu}>
>           <div tabIndex="0" className="m-1 btnHamburger mr-5">
>             <i className="fal fa-bars text-2xl text-white" />
>           </div>
>           <ul tabIndex="0" style={{ display: displayMenuStyle}} className="p-2 shadow menu dropdown-content bg-slate-200 rounded-box w-52 mr-5 ">
>             <li className="text-slate-600">
>               <Link to='/'>Item 1</Link>
>             </li>
>             <li className="text-slate-600">
>               <Link to='/'>Item 2</Link>
>             </li>
>             <li className="text-slate-600">
>               <Link to='/'>Item 3</Link>
>             </li>
>           </ul>
>         </div>
>       </div>
>     </div>
> ```
> 
> A quick explanation of the logic for noobs like myself....
> 
> We set 2 states, the one is checking if the button is clicked for the first time or the second. So we use the true or false to check that.
> 
> Its initial state is set to true because for some reason when it is set to false the first time you click it it will open and close instantly the menu ? no clue why, maybe the masters can help on that one.
> 
> Then we check if the menuDisplay state is true. If it's true then display is set to '' empty string and the menu pops up. If its false then the display is set to 'none' and the menu disappears.
> 
> Weird but it's working. Cheers!

also, add the ` onBlur={showMenu}` for keeping the state synced.

**Comment by ArtimusMaximus** [comment]
Need the drop down menu to close upon clicking a link, yes. 
The drop down menu closes after you click it manually again. I am using React in nextJS.
do:
onClick={() => document.querySelector('#menu').click()}
e.g.:
<div className="navbar-center hidden lg:flex">
                <ul className="menu menu-horizontal px-1" >
                <li tabIndex={0}>
                    <details>
                    <summary id="menu">Products</summary>
                    <ul className="p-2">
                        {mainCategories.map((category) => {
                            return (
                                <li key={category.id} >
                                    <Link 
                                        href={`${category.link}`}
                                        **onClick={() => document.querySelector('#menu').click()}**
                                    >{category.title}   
                                    </Link>
                                </li>
                            )
                        })}
                    </ul>
                    </details>
                </li>
                <li><a>Contact</a></li>
                <li><a>About</a></li>
                </ul>
            </div>

**Comment by esphoenixc** [comment]
> thanks @theodosiskats Here's another example with React using `useRef` to handle focus instead of using states: https://codesandbox.io/s/eloquent-tree-bu2dt?file=/src/App.js

How can I while applying this logic remain the functionality of closing the dropdown by clicking outside?

**Comment by filippog** [comment]
I ran into this issue too (dropdown not closing after click) and I've used to [hyperscript](https://hyperscript.org/) to first settle the transition and then close the dropdown. Not settling results in the transition finishing only when the dropdown gets opened again.

Using the [dropdown example](https://daisyui.com/components/dropdown/):

```html
<details class="dropdown mb-32">
  <summary class="m-1 btn">open or close</summary>
  <ul _="on click settle then remove @open from the closest .dropdown"
         class="p-2 shadow menu dropdown-content z-[1] bg-base-100 rounded-box w-52">
    <li><a>Item 1</a></li>
    <li><a>Item 2</a></li>
  </ul>
</details>
```

**Comment by gandlafbtc** [comment]
For me, this worked using the `<details>` dropdown

```
on:click={(e) => {
    e.target.parentElement.parentElement.parentElement.removeAttribute('open');
}}
```

**Comment by danzilberdan** [comment]
This is what worked for me with Alpine.js:
```
<details class="dropdown dropdown-end" x-data="{}">
    <summary class="avatar cursor-pointer" @click.outside="$el.parentElement.removeAttribute('open')">
        <div class="w-12 rounded">
            <img src={getAvatarUrl(ctx, "100x100")} />
        </div>
    </summary>
    <ul class="menu dropdown-content bg-base-100 rounded-box z-[1] w-52 p-2 shadow">
        <li><a>Item 1</a></li>
        <li><a>Item 2</a></li>
    </ul>
</details>
```

**Comment by Iskrata** [comment]
None of these solutions worked well on Next.js 14 so here is a quick and easy solution using useState() inspired by @theodosiskats 

`
  const [displayMenuStyle, setdisplayMenuStyle] = useState("");
  const handleSuffixClick = (slot: SlotType, suffix: string) => {
    if (setSuffix) {
      setSuffix(slot, suffix);
    }
    setdisplayMenuStyle("none");
  };
`

Then just add this to the outer <div>
`
<div
    className="dropdown dropdown-hover dropdown-top dropdown-end"
    onMouseEnter={() => setdisplayMenuStyle("")}
    onMouseLeave={() => setdisplayMenuStyle("none")}
  >
`

And styling for the <ul>
`
  <ul
    tabIndex={0}
    style={{ display: displayMenuStyle }}
    className="dropdown-content menu bg-base-100 rounded-box z-[1] w-52 p-2 shadow text-black"
  >
`

It works like a charm. Anyways, good job to the DaisyUI team 🌼

**Comment by Chaperone562** [comment]
https://reacter.space/questions/hide-a-dropdown-menu-if-a-user-clicks-on-any-item-within-it Observe this note

**Comment by czue** [comment]
If anyone is looking for a solution that works with:

1. Clicking the open/close button
2. Clicking outside
3. Clicking on an individual item inside the menu

This is what worked for me with Alpine. For some reason explicitly setting "open" with a state variable did not work.

```html
<details class="mx-2 dropdown dropdown-end" x-data="{}">
  <summary class="btn btn-ghost btn-sm" @click.outside="$el.parentElement.removeAttribute('open')">
    Open or Close
  </summary>
  <ul class="menu dropdown-content bg-base-100 rounded-box z-1 w-52 p-2 shadow-sm">
    <li><button @click="$el.parentElement.parentElement.removeAttribute('open');">Item 1</button></li>
    <li><button @click="$el.parentElement.parentElement.removeAttribute('open');">Item 2</button></li>
    <li><button @click="$el.parentElement.parentElement.removeAttribute('open');">Item 3</button></li>
  </ul>
</details>
```
