### ISSUE TITLE
bug: vite warnings when minifying css

### ISSUE THREAD

**Issue by kanersps** [saadeghi/daisyui#1571]
### What version of daisyUI are you using?

v2.5

### Describe your issue

During build, Vite throws a warning during CSS minification. Removing the DaisyUI plugin from Tailwind resolves the issue.

The full message:

```
warnings when minifying css:
▲ [WARNING] Unexpected "{" [css-syntax-error]

    <stdin>:1980:2:
      1980 │ } {
           ╵   ^
```

### What browsers are you seeing the problem on?

Other

**Comment by saadeghi** [comment]
Can you create a reproduction repo?

**Comment by kanersps** [comment]
Yes I can!

And doing that resulted in figuring out it does not neccesarily need to be DaisyUI's fault.

Removing the "autoprefixer" postcss plugin fixes it as well, then using cssnano's version of autoprefixer works and the warnings are gone.
