### ISSUE TITLE
Issue: Stackblitz examples not running the latest version

### ISSUE THREAD

**Issue by Slluxx** [saadeghi/daisyui#1591]
### On which page do you see this issue?

https://daisyui.com/docs/install/

### Describe the issue

The current Svelte (Vite) example on Stackblitz (and probably the other examples too) does not use the latest version of daisyUI and thus components like the "chat bubbles" do not work. Trying to update yields a `ERR_PACKAGE_PATH_NOT_EXPORTED` error. I was trying to follow tailwind/daisyui update guides but nothing solved the issue, so my guess would be vite, svelte or even the node version to be the culprit. However i have not really researched this thoroughly.

In any way, i hope the examples do get an update sometime soon.

Regards,
Slluxx

### What browsers are you seeing the problem on?

Chrome

**Comment by Slluxx** [comment]
I am just going to bump this because no reply, no labels, nothing.

**Comment by saadeghi** [comment]
Sorry I missed this issue. Examples will be updated by tomorrow 👍

**Comment by saadeghi** [comment]
Updated Svelte examples:
- https://stackblitz.com/edit/daisyui-sveltekit
- https://stackblitz.com/edit/daisyui-svelte-vite

Let me know if you have any questions.
