### ISSUE TITLE
bug: Too many 🌼 daisyUI components messages

### ISSUE THREAD

**Issue by dolanmiu** [saadeghi/daisyui#1593]
### What version of daisyUI are you using?

2.50.0

### Describe your issue

Is there a way to disable this? It is polluting the logs whenever I use `ng lint` from my `Angular` project:

## Reproduction steps:

```bash
$ ng lint
```

## Result

![image](https://user-images.githubusercontent.com/2917613/218289110-20bbc4fc-e1a8-4c95-bced-4226869d6907.png)

### What browsers are you seeing the problem on?

Other

**Comment by saadeghi** [comment]
You can disable this using [`logs: false` config](https://daisyui.com/docs/config/)  
But if it is getting printed multiple times, that means your build process is executing the script many times which is not optimal. It should only run once.
