### ISSUE TITLE
bug: Not being able to set "undefined" or empty value for range input

### ISSUE THREAD

**Issue by zirho** [saadeghi/daisyui#1595]
### What version of daisyUI are you using?

2.27.0

### Describe your issue

I can not set an empty value for range selector so that users would intuitively know the value has not been set.

It always sets the range bar value-selected (arbitrary value) by default even when no value is provided yet, and that is being perceived as value-selected to users.

```
      <input type='range' min='0' max='100' className='range' />
```

this shows up as this

![image](https://user-images.githubusercontent.com/1251296/218367003-7ad12e42-2d98-4470-abaa-918907223c0c.png)

Another issue related to this is when I set range from 1 to 5 and default arbitrary value is set to 2, user would have to click the value other than 2 and click 2 again to set the value to 2.

* I am using this in react. Not sure if this is react specific.

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
How does it look if you remove daisyUI's `range` class name?
