### ISSUE TITLE
bug: progress animation does not work on safari (and mobile safari) (even in simulator)

### ISSUE THREAD

**Issue by zirho** [saadeghi/daisyui#1608]
### What version of daisyUI are you using?

2.50.1

### Describe your issue

https://daisyui.com/components/progress/#indeterminate-without-value

Progress animation does not work in safari

on safari, iOS
<img width="371" alt="image" src="https://user-images.githubusercontent.com/1251296/219467562-4919267d-0309-4240-93d0-c4606d9e9b63.png">

on chrome
<img width="266" alt="image" src="https://user-images.githubusercontent.com/1251296/219467599-fe99cd51-9bac-4c39-8430-760f38a091c8.png">

### What browsers are you seeing the problem on?

Safari

### Reproduction URL (optional)

https://daisyui.com/components/progress/#indeterminate-without-value

**Comment by alexkates** [comment]
Same problem on Brave.

**Comment by BRAiNCHiLD95** [comment]
I can confirm this is failing on Safari, and Firefox.

> Same problem on Brave.

Somehow it works for me in Brave (and Chrome).

**Comment by BRAiNCHiLD95** [comment]
I can confirm this is failing on Safari, and Firefox.

> Same problem on Brave.

Somehow it works for me in Brave (and Chrome).

From what I see -
On Firefox - the :after element is not added to the DOM.

On Safari - the :after element in enclosed in it's own Shadow Content DOM.

**Comment by zirho** [comment]
duplicated https://github.com/saadeghi/daisyui/issues/794
