### ISSUE TITLE
bug: Modal accessibility -> Trap focus within modal when open + enable esc and tab key functionality

### ISSUE THREAD

**Issue by marksist300** [saadeghi/daisyui#1609]
### What version of daisyUI are you using?

2.31.0

### Describe your issue

Currently when a modal is open the focus is not trapped within the modal. This means when hitting the `tab` key while the modal is open the whole page (behind the modal) is tabbed through.

When open, modals should have all focus fixed within so a user can use the `tab` key to interact with the modal's content, buttons etc.

Also, user's should be able to use the `escape` key to close the modal.

### What browsers are you seeing the problem on?

Chrome, Safari, Firefox, Edge, Other

**Comment by saadeghi** [comment]
I wish I could provide all these functionalities, but daisyUI is just a CSS file. You should handle these yourself using JS. Or you can use a JS modal plugin alongside daisyUI. for example: https://headlessui.com/react/dialog

**Comment by marksist300** [comment]
> I wish I could provide all these functionalities, but daisyUI is just a CSS file. You should handle these yourself using JS. Or you can use a JS modal plugin alongside daisyUI. for example: https://headlessui.com/react/dialog

Yeah, my bad. Didn't know the library was CSS only, I closed the issue when I saw. Will just do the JS my end. 

Have you ever thought of creating a JS integrated library with DaisyUI? Would be happy to collaborate on the project if you ever do 🙂.

**Comment by saadeghi** [comment]
> Have you ever thought of creating a JS integrated library with DaisyUI? Would be happy to collaborate on the project if you ever do 🙂.

Yes but when there are existing plugins that do the job, I don't think there would be need for me to create a new JS bundle. Because at best, it would be exactly like [Headless UI](https://headlessui.com/) or [Radix UI](https://www.radix-ui.com/). They give you JS functionality plus all the things CSS can't provide (like keyboard navigation or ARIA attributes, etc.) but they don't provide CSS styling and design decisions so you can perfectly use them with daisyUI styles.

**Comment by marksist300** [comment]
> > Have you ever thought of creating a JS integrated library with DaisyUI? Would be happy to collaborate on the project if you ever do 🙂.
> 
> Yes but when there are existing plugins that do the job, I don't think there would be need for me to create a new JS bundle. Because at best, it would be exactly like [Headless UI](https://headlessui.com/) or [Radix UI](https://www.radix-ui.com/). They give you JS functionality plus all the things CSS can't provide (like keyboard navigation or ARIA attributes, etc.) but they don't provide CSS styling and design decisions so you can perfectly use them with daisyUI styles.

Yeah, that makes sense. I appreciate all the work you and the collaborators have put into DaisyUi, it's a great library! 🙏
