### ISSUE TITLE
bug: break-words doesn't do what it must

### ISSUE THREAD

**Issue by ktecho** [saadeghi/daisyui#1611]
### What version of daisyUI are you using?

2.50.1

### Describe your issue

Using the `break-words` class, makes use of this css:

```
overflow-wrap: break-word;
```

But it does this:

![image](https://user-images.githubusercontent.com/547169/219705338-b19fe479-2373-4fd4-bf82-c843a85f9590.png)

It cuts all the words, not just the neccessary as stated in the docs.

If I put this:

```
style="word-break: break-word;"
```

![image](https://user-images.githubusercontent.com/547169/219705509-f8dcd07b-1e7f-4181-9c50-08f19fbef5d8.png)

So now only the big number is cut in half, but words are correct.

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
This doesn't seem to be a problem from daisyUI. `break-words` class is [coming from Tailwind CSS itself](https://tailwindcss.com/docs/word-break).  
Is this creating a problem with one of daisyUI components? Can you provide a code example?

**Comment by ktecho** [comment]
Wow... I feel so stupid...

You're right, this should be a bug for Tailwind CSS. Thanks a lot.
