### ISSUE TITLE
docs: comments on jsx code snippet is regular html comments

### ISSUE THREAD

**Issue by durosly** [saadeghi/daisyui#1613]
### On which page do you see this issue?

https://daisyui.com/components/table/

### Describe the issue

Comments in JSX code snippets which is always written as 
```html
<!-- hello world -->
```
shoud be written as 
```jsx
{/* hello world */}
```

**Comment by adiitiii** [comment]
Can i work on this issue, I'd really like to contribute

**Comment by saadeghi** [comment]
@adiitiii of course. Thank you 🙌

**Comment by durosly** [comment]
I would like to work on it too if it is not too late

**Comment by saadeghi** [comment]
@durosly it's just a simple text replacement so there's no need for competition 😅 If you can help with answering other issues/discussions or possibly helping to fix them I would really appreciate it.

**Comment by durosly** [comment]
@saadeghi No problem. I will see what else I can do
