### ISSUE TITLE
bug: tooltip within `stat-title` inherits opacity

### ISSUE THREAD

**Issue by johnbchron** [saadeghi/daisyui#1617]
### What version of daisyUI are you using?

v2.50.0

### Describe your issue

When you place a tooltip inside of the `stat-title` class of a stat (for example if you wanted to show a question icon with a tooltip explanation), the tooltip inherits `opacity: 0.6` from the `stat-title` class. This is overridden while the tooltip is inactive, but when it's active it has `opacity: 0.6` and looks off. I don't know enough to know if what I'm suggesting is a good alternative, but setting opacity outright within `stat-title` seems uncharacteristic for DaisyUI. Maybe set the text color with a modified opacity, or add a dedicated css variable?

### What browsers are you seeing the problem on?

I've only tested on chrome, but I don't think it's relevant.

### Reproduction URL (optional)

https://codepen.io/johnbchron/pen/bGxVPMo

**Comment by saadeghi** [comment]
Thank you. Fixed in version `2.50.2`
