### ISSUE TITLE
bug: Text Input, text colour for defaultValue when disabled 

### ISSUE THREAD

**Issue by PatrickMunsey** [saadeghi/daisyui#1622]
### What version of daisyUI are you using?

2.49.0

### Describe your issue

I'm implementing some forms with disabled fields using the 'business' theme and I'd like to make a suggestion to make the text colour a bit darker for a disabled text input with a defaultValue or value specified similar to when placeholder is.

With darker themes, disabled inputs are not immediately distinguishable from active inputs without hovering, when a defaultValue/value is used to populate the input instead of a placeholder.

## Disabled field with placeholder specified
![disabledFieldWithPlaceholder](https://user-images.githubusercontent.com/80461348/220240382-0a7f01ed-9db7-4a99-a81c-d87cb2e521ed.PNG)

## Disabled field with defaultValue specified
![disabledFieldWithDefaultValue](https://user-images.githubusercontent.com/80461348/220240378-61d35d1e-39d3-4289-9acd-010f5ef74b3b.PNG)

## Field with Placeholder specified
![FieldWithPlaceholder](https://user-images.githubusercontent.com/80461348/220241022-ca1803ea-ab16-4e8e-a6f8-e53aa0b5a405.PNG)

## Field with defaultValue specified
![FieldWithDefaultValue](https://user-images.githubusercontent.com/80461348/220240659-63d20fae-d109-45f9-b633-0127e74c47ff.PNG)

Would be good to know your thoughts. Thanks

### What browsers are you seeing the problem on?

Edge

### Reproduction URL (optional)

https://play.tailwindcss.com/MRPWesNq4H

**Comment by 35grain** [comment]
Agreed. Currently it looks like it is interactable.
