### ISSUE TITLE
bug: prettier-plugin-tailwindcss with daisyUI plugin breaks prettier

### ISSUE THREAD

**Issue by Apestein** [saadeghi/daisyui#1623]
### What version of daisyUI are you using?

latest

### Describe your issue

Exactly as the title says. If I remove the daisy plugin from tailwind.config.js, prettier works again. 

### What browsers are you seeing the problem on?

Chrome

**Comment by nikhilfurious** [comment]
> ### What version of daisyUI are you using?
> latest
> 
> ### Describe your issue
> Exactly as the title says. If I remove the daisy plugin from tailwind.config.js, prettier works again.
> 
> ### What browsers are you seeing the problem on?
> Chrome
> 
> ### Reproduction URL (optional)
> _No response_

,

**Comment by saadeghi** [comment]
Can you give me an example repo where I can reproduce the issue?

**Comment by dolanmiu** [comment]
I have this same set up, no issues on my side…

**Comment by Apestein** [comment]
> Can you give me an example repo where I can reproduce the issue?

I tried to reproduce it today but I couldn't. I'm really not sure. I had bugs disappear after I restarted my dev server before. Maybe it was just a case of that.
