### ISSUE TITLE
bug: Drawer breaks the previous page's scrolling position when navigating back/previous page

### ISSUE THREAD

**Issue by cappe** [saadeghi/daisyui#1633]
### What version of daisyUI are you using?

v2.51.0

### Describe your issue

1. Have a webpage with DaisyUI drawer
2. Scroll down page A
3. Navigate to page B through any link
4. Go back (using browser's back button)
5. The scrolling position on page A is lost/reset

This behavior is present on [DaisyUI's docs](https://daisyui.com/components/drawer/). I'm reporting this issue as it reduces UX quite a lot.

I'm currently looking for a workaround so if anyone has tips, please do share. I hope to be able to contribute on the issue too :)

### What browsers are you seeing the problem on?

Chrome

### Reproduction URL (optional)

https://daisyui.com/components/drawer/

**Comment by saadeghi** [comment]
I have no solution for this unfortunately.  
Browsers only save the scroll position of the <html> element but daisyUI's drawer is using scroll on a div (because that's the only way to have control over the style of sidebar and the content without using JS)

**Comment by patleb** [comment]
You'll need to change your html structure in a way that you can put your `drawer` class on the body with `overflow-y-auto` and add `overflow-y-visible` to the `drawer-content` class. That should do it. This way, the scroll is on the body instead of the wrapper div.

Also, the `scroll-smooth` class will have to be applied to `html` instead of the body.

**Comment by patleb** [comment]
Although, you'll lose the sticky sidebar on scroll down for large screens, it'll stay at the top with the content.

**Comment by mustofa-id** [comment]
> You'll need to change your html structure in a way that you can put your `drawer` class on the body

I agree with this. Also using `drawer-content` for the main scroll can cause the page to become heavy and lead to high CPU usage while scrolling.

**Comment by saadeghi** [comment]
I'm trying to refactor drawer in the next major version ( daisyUI `3.0`)  
I'm going to use [CSS `:has()`](https://caniuse.com/css-has) for it. That's the only way to do it without JS, without needing an extra div container (so the scroll problem won't happen) and still being able to apply styles to the parent `<html>`.  
The only problem would be Firefox but I hope they enable it be default soon.

<img width="673" alt="3f" src="https://user-images.githubusercontent.com/7342023/224368021-ded8dc81-c7f0-4015-b6fc-259cbddf221f.png">

**Comment by patleb** [comment]
@saadeghi it looks a little bit too much bleeding edge... would it be possible to keep the current drawer implementation (but maybe with some kind of adjustments like I highlighted before) dedicated to the `body` tag and having another one for any other html tags if you're ok with having it not working for ~15% of the browsers on the market?

**Comment by patleb** [comment]
Thx!
