### ISSUE TITLE
bug: Themes not rendering with configuration 

### ISSUE THREAD

**Issue by Dino-14** [saadeghi/daisyui#1635]
### What version of daisyUI are you using?

v2.50.2

### Describe your issue

I have configured the plugin within my tailwind.config.js as such

plugins: [require("daisyui")],
  daisyui: {
    styled: true,
    themes: true,
    base: true,
    utils: true,
    logs: true,
    rtl: false,
    prefix: "",
    darkTheme: "garden",

and the files are imported and load on my console

 daisyUI components 2.50.2  https://daisyui.com
  ✔︎ Including:  base, components, 29 themes, utilities
  ❤︎ Support daisyUI:  https://opencollective.com/daisyui 

but the theme does not render on the application regardless of which theme is chosen. I have upgraded the next.js modules as well as daisy and tailwind and it still does not render.
 

### What browsers are you seeing the problem on?

Chrome, Safari, Firefox, Edge

**Comment by saadeghi** [comment]
Here's a Next.js example setup and all themes are included in CSS:  
https://stackblitz.com/edit/daisyui-nextjs

So if it's not working for your setup, I would need a reproduction repo so I can see the result.
