### ISSUE TITLE
bug: Safari: Collapse inside drawer not working properly

### ISSUE THREAD

**Issue by jo-gross** [saadeghi/daisyui#1640]
### What version of daisyUI are you using?

v2.51.1

### Describe your issue

Hi folks,

i am using an drawer with a collapse inside to group menu items like this:
<img width="591" alt="grafik" src="https://user-images.githubusercontent.com/11421371/221450815-ad5b62d8-ff28-432c-9c4f-57cbd08f8b68.png">

This works fine in Firefox and Chrome, but not in Safari, there it looks like:
<img width="591" alt="grafik" src="https://user-images.githubusercontent.com/11421371/221451497-b87f9a43-6ef1-4a49-84af-a7227344c01b.png">
The arrow and the little bit of the menu item at the bottom only appeard after i opened the inspector. 

I sat up an entirely new project with the basic drawer form the documentation and the collapse i used in my main project.
Here is the code i used to test:

```
<div className="drawer drawer-mobile">
        <input id="my-drawer-2" type="checkbox" className="drawer-toggle"/>
        <div className="drawer-content flex flex-col items-center justify-center">
            <label htmlFor="my-drawer-2" className="btn btn-primary drawer-button lg:hidden">Open drawer</label>

        </div>
        <div className="drawer-side">
            <label htmlFor="my-drawer-2" className="drawer-overlay"></label>
            <ul className="menu p-4 w-80 bg-base-200 text-base-content">
                <li><a>Sidebar Item 1</a></li>
                <li><a>Sidebar Item 2</a></li>

                <div
                    className={`collapse collapse-arrow border border-base-300 bg-base-200 rounded-box`}>
                    <input type='checkbox' className='peer'/>
                    <div className='collapse-title'>
                        <span className={'text-primary'}>Group</span>
                    </div>
                    <div className='collapse-content'>
                        <ul>
                            <li><a>Sidebar Item 3</a></li>
                            <li><a>Sidebar Item 4</a></li>
                        </ul>
                    </div>
                </div>
            </ul>
        </div>
    </div>
```

Does anybody have an idea how can i fix this? I have tested a bit with the inspector but couldn´t find the reason.

Thanks for maintaining this awesome project!

### What browsers are you seeing the problem on?

Safari

**Comment by saadeghi** [comment]
That was a weird behavior from Safari.  
Thank you for reporting. Fixed in version `2.51.2`   
https://play.tailwindcss.com/dV1E9mCNql?layout=horizontal
