### ISSUE TITLE
Make it possible for button groups with radio inputs to have tooltips

### ISSUE THREAD

**Issue by saadeghi** [saadeghi/daisyui#1642]
### Discussed in https://github.com/saadeghi/daisyui/discussions/1641

<div type='discussions-op-text'>

<sup>Originally posted by **douglaslassance** February 27, 2023</sup>
Expectedly, the following HTML will not work.

```html
<div class="btn-group">
  <div class="tooltip" data-tip="hello">
    <input type="radio" name="options" data-title="A" class="btn" checked />
  </div>
  <input type="radio" name="options" data-title="B" class="btn" />
  <input type="radio" name="options" data-title="C" class="btn" />
</div>
```

Would love to know how this can be achieved.</div>

**Comment by REJack** [comment]
@saadeghi I accomplished button-groups with tooltips directly on the btn itself, only with only a small css change

```css
.btn.tooltip {
    @apply inline-flex;
}
```
