### ISSUE TITLE
Button outline focus state

### ISSUE THREAD

**Issue by janat08** [saadeghi/daisyui#165]
Buttons with focus state (after click.) Semantically it's like showing loading state if it's not spa. There should be an option between selecting animation and state transition. https://www.tailwind-kit.com/components/buttons

**Comment by saadeghi** [comment]
@janat08 daisyUI only shows rings on [`:focus-visible`](https://caniuse.com/?search=focus-visible) (navigation using keyboard)   
If you need rings when you click the buttons as well, you can add this CSS: https://play.tailwindcss.com/jZ8OxOiPjx?file=css

**Comment by mundane799699** [comment]
> @janat08 daisyUI only shows rings on [`:focus-visible`](https://caniuse.com/?search=focus-visible) (navigation using keyboard) If you need rings when you click the buttons as well, you can add this CSS: https://play.tailwindcss.com/jZ8OxOiPjx?file=css

Could please tell me how to remove the outline when the button is on :focus-visible?
