### ISSUE TITLE
bug: Fontawesome / Icon goes blank when inside a .btn but should be treated as text.

### ISSUE THREAD

**Issue by christo8989** [saadeghi/daisyui#1651]
### What version of daisyUI are you using?

2.51.1

### Describe your issue

DaisyUI + Fontawesome = bug?

```
<button className="btn">
  <Icon icon={faArrowLeft} />
</button>
```

Sometimes the icon appears as it should, and then when I click around, the icon will disappear or get really big.
https://play.tailwindcss.com/fNJCO8Wl5i?size=540x720

My expectation is for an svg to be treated as text.

### What browsers are you seeing the problem on?

Chrome

**Comment by sanskar-mk2** [comment]
Add `w-8` and/or `h-8` or similar in the classes of the `svg` element to make it a better fit your button.

Thank you.

**Comment by christo8989** [comment]
Of course, it's possible to treat svg as an image. And it's possible to treat fontawesome svg icons as an image. But, the point I'm making is that fontawesome's svgs are meant to be treated like text. 

https://fontawesome.com/docs/web/style/size

If this bug is closed because the project doesn't care, then that's fine (also, maybe its a bug with tailwind and not daisyui). But I hope we understand that it is a bug because these icons, even though they're svgs, can and are treated as text.

**Comment by christo8989** [comment]
What's also weird, is locally, when I first load the page, the icons look good. Then when I click to a new page, they either get really big or disappear. So, something here is not right. But I couldn't necessarily get that to show in the link I posted.

**Comment by christo8989** [comment]
<img width="71" alt="image" src="https://user-images.githubusercontent.com/1092511/222475943-c47dacda-9538-480a-8884-2f841c28013e.png">

<img width="69" alt="image" src="https://user-images.githubusercontent.com/1092511/222476074-dc1404d5-136a-40be-92fc-1419d80c5997.png">

**Comment by sanskar-mk2** [comment]
The font awesome icon in the `<i>` tag are being treated as text.
But the example you gave earlier was an `<svg>` element.

You see, we can change icon size with `text-xl` but we cannot do the same for hardcoded `svg` like you shown earlier.

```html
<link rel="stylesheet" href="https://unpkg.com/font-awesome@4.7.0/css/font-awesome.css">


<!-- buttons -->
<div class="p-4 flex items-center gap-4">
  <button class="text-4xl btn btn-primary">
    <i class="fa fa-apple"></i>
  </button>

  <button class="text-3xl btn btn-primary">
    <i class="fa fa-apple"></i>
  </button>

  <button class="text-sm btn btn-primary">
    <i class="fa fa-apple"></i>
  </button>

  <button class="btn btn-primary">
    Text
  </button>
</div>
```

**Comment by saadeghi** [comment]
I'm not sure. I need a better reproduction code so I can see the issue.  
The link you gave me does not include Font awesome's CSS and it's just a single SVG tag (which has no width/height so it will be 0px in size)  

I can just confirm that daisyUI doesn't apply any styles to all SVG tags. Tailwind applies this style and I don't think it creates any issue with sizing:
```css
img, svg, video, canvas, audio, iframe, embed, object {
    display: block;
    vertical-align: middle;
}
```

Please provide a better code example where I can see both daisyUI and Font Awesome styles are being applied and I can see the issue.

**Comment by sanskar-mk2** [comment]
I think this is the possible problem for you (correct me if I am wrong):

> This package, under the hood, uses SVG with JS and the @fortawesome/fontawesome-svg-core library. This implementation differs drastically from the classic Web Font-based one in Font Awesome 4 and earlier. If you want to know the details, [read up on fontwesome-svg-core](https://fontawesome.com/web/advanced/svg-javascript-core). If you're coming from Version 4, we also recommend [learning more about upgrading to Font Awesome 5](https://fontawesome.com/web/setup/upgrade-from-v4) in general.

https://fontawesome.com/v5/docs/web/use-with/react

**Comment by christo8989** [comment]
Yeah. Their examples aren't helping me. 

I copy pasted the svg from fontawesome into the link because I don't see a way to bring in the package for version 6.

And yes, the approach for svgs is different. 

Also, I think it's a tailwind issue. So I can move this over there.

I do see that centering is a little off, which I think is a result of it being an svg. In my mind, that may be a difficult bug to fix because its an svg and not a font. But the size of the icon should work as expected.

This is from their documentation, and is meant to work for both font+css and svg+js.

> By default, icons inherit the font-size of their parent container which allow them to match any text you might use with them. In addition to that, Font Awesome comes with the following sizing tools.

Anywho, thank you for helping me think through this. I will take it up with tailwind. 👍

**Comment by saadeghi** [comment]
Here's an example of using fontawesome 6 on React. I hope it helps:  
https://stackblitz.com/edit/daisyui-react-vite-fontawesome?file=src%2FApp.jsx


About the centering: I would suggest using `flex` for putting buttons next to eachother, It will guarantee them to be in the same line regardless of being text, image, or having any size.
```html
<div className="flex gap-2">
  <button class="btn">Text</button>
  <button class="btn">Text</button>
</div>
```

**Comment by sanskar-mk2** [comment]
https://fontawesome.com/v6/docs/web/dig-deeper/webfont-vs-svg

If you are using it with React by installing their node package, you are agreeing to use their "SVG+JS method". And you cannot use webfonts. It says on the setup page: https://fontawesome.com/v6/docs/web/use-with/react/

**Comment by christo8989** [comment]
To close the loop on this, the bug is with my code. 😶‍🌫️ 

I don't quite understand why the GlobalLayout is causing this, but I suspect it has to do with flex missing from the headers. Uh. Sorry for wasting your time. But thank you for obliging. 

https://stackblitz.com/edit/nextjs-qzqxde?file=src%2Fpages%2F_app.tsx

**Comment by christo8989** [comment]
I'm not 100% what's happening between nextjs and dairyui, but I noticed if I remove the `p-0` from `.btn-circle`, it fixes the issue.

The icon isn't sized by the font-size, but the padding makes the button look good. So, would be happy with that.

**Comment by christo8989** [comment]
Adding `w-[1em] h-[1em]` to the icons fixes it.
