### ISSUE TITLE
bug: Tooltip lies under the side drawer

### ISSUE THREAD

**Issue by jo-gross** [saadeghi/daisyui#1655]
### What version of daisyUI are you using?

2.51.3

### Describe your issue

Hi there,

i have an other questions, is this behavior consciously? 
<img width="591" alt="grafik" src="https://user-images.githubusercontent.com/11421371/222527486-39d4a737-285c-4e0d-b82c-bd01d1de1254.png">

I am using a drawer, always open on pc, for the navigation. I added a tooltip on an item very near to the drawer. Parts of the message gets overlapped. 

I tried diffrent stuff like changing the z-index or the boundaries of the tooltip to show the whole text, but i cannot get it to work. Do you have some idea how can i solve this?
Introducing a new class tag which allows the tooltip to overlap anything like the drawer could be a smart solution. 

### What browsers are you seeing the problem on?

Chrome, Safari, Firefox, Edge

### Reproduction URL (optional)

https://play.tailwindcss.com/SQdMdB4PwX

**Comment by REJack** [comment]
That's truly not a bug, due the drawer uses overflow, anything inside the drawer gets cut-off. You would need to "teleport" the tooltip to body trough a JavaScript (e.g. using PopperJS) that's sadly only way to accomplish the correct behavior.
