### ISSUE TITLE
bug: daisyui@2.51.3" has unmet peer dependency "autoprefixer@^10.0.2".

### ISSUE THREAD

**Issue by admin8756** [saadeghi/daisyui#1656]
### What version of daisyUI are you using?

2.51.3

### Describe your issue

When I enter the yarn installation dependency.

**Comment by saadeghi** [comment]
Please provide a reproduction repo so I can see the issue.

**Comment by admin8756** [comment]
> Please provide a reproduction repo so I can see the issue.

I'm so sorry, After I switched windicss to tailwindcss, there was no error.
