### ISSUE TITLE
How to apply styles to dynamic content? i.e content from Strapi CMS

### ISSUE THREAD

**Issue by Aravin** [saadeghi/daisyui#166]
Hi,

I have my backend build on Strapi CMS and the frontend is Next.js (Tailwind + Daisy UI).

I love the mockup code.

Can I use mockup-code within my content that comes from CMS?

Example data

```
Some random text
...
<HTML>...</HTML>
....
Somemore content
```

**Comment by saadeghi** [comment]
@Aravin I'm not sure how Strapi works. Somewhere it's converting the markdown to HTML and and you should see if you can add classes to that HTML or not.  

If you can't add classes, you can just manually add the style of mockup for your own elements:  
https://github.com/saadeghi/daisyui/blob/master/src/components/unstyled/mockup.css  
https://github.com/saadeghi/daisyui/blob/master/src/components/styled/mockup.css

**Comment by Aravin** [comment]
What is the difference between styled and unstyled @saadeghi?

**Comment by saadeghi** [comment]
@Aravin  
`unstyled` includes the layout and positioning of components.  
`styled` includes the design decisions such as colors and spacing.

**Comment by Aravin** [comment]
Got it. @saadeghi
