### ISSUE TITLE
bug: dynamic props not working

### ISSUE THREAD

**Issue by atomicpages** [saadeghi/daisyui#1664]
### What version of daisyUI are you using?

2.51.3

### Describe your issue

Seeing some weird issues with missing styles when applying button primary/secondary/etc class names based on props. I've been able to reproduce this using both React and Solid.js. I haven't see this using tailwindcss directly. Here's a screencap showing the missing styles. Truth be told I'm not sure this is a bug or a me problem

<img width="864" alt="image" src="https://user-images.githubusercontent.com/1824291/223032258-3af0b1d6-7cd7-4cdc-b852-d56066cded63.png">

### What browsers are you seeing the problem on?

Chrome

### Reproduction URL (optional)

https://stackblitz.com/edit/daisyui-react-vite-h8k5y3?file=src%2FApp.jsx,src%2FButton.tsx

**Comment by saadeghi** [comment]
Read this please: https://tailwindcss.com/docs/content-configuration#dynamic-class-names

In a Tailwind CSS project, you should have the class name as a whole string. When you use half-variable/half-string (like `btn-{color}`) there is no way for Tailwind to know that you need the `btn-primary` class name. Use the class name as a whole string like `btn-primary`

If you really need to do that, you should safelist all possible class names in your `tailwind.config.js` file

**Comment by atomicpages** [comment]
Got it. Thanks!
