### ISSUE TITLE
No list of supported tailwind versions

### ISSUE THREAD

**Issue by william-will-angi** [saadeghi/daisyui#167]
It seems to work in both v1 and v2 Tailwind. Are both officially supported by this plugin?

**Comment by saadeghi** [comment]
@william-will-angi Yes. Technically, daisyUI has no dependencies and can be used even without Tailwind CSS ([example](https://github.com/saadeghi/daisyui/tree/master/examples/vite-daisyui-notailwind)) just as a component library or with other utility-first frameworks.  
daisyUI gives you the components but you also need utility classes for width, margin, flexbox, etc... Both Tailwind v1 and v2 have the essential utility classes but v2 [has a lot more](https://blog.tailwindcss.com/tailwindcss-v2).
