### ISSUE TITLE
Question - If I only use one theme, how can i purge rest of them when generating bundle for production

### ISSUE THREAD

**Issue by Ammadkhalid** [saadeghi/daisyui#168]
Hi,

Is it possible to remove rest of the other theme and its css? i'm using daisyui in my nuxt.js project with tailwind.

Thank you!

**Comment by saadeghi** [comment]
@Ammadkhalid Yes. See config docs: https://daisyui.com/docs/config  
```js
daisyui: {
  themes: [
    'light', // the only theme
  ],
},
```
Let me know if you have any questions.
