### ISSUE TITLE
Toggle issue with tailwindcss/forms

### ISSUE THREAD

**Issue by loranger** [saadeghi/daisyui#1689]
### What version of daisyUI are you using?

2.41.0

### Describe your issue

I use [filament](https://filamentphp.com/) as my app backoffice crud and it requires the `tailwindcss/forms` to be enabled.
Unfortunately, it breaks the toggle behaviour on my front office app using daisyui (as reported in #1449, #1431, #1378, #1301, #804).

How can I use both (the marvelous daisyui and the wonderful filament) without choosing which part will be ugly?

### What browsers are you seeing the problem on?

Firefox

**Comment by saadeghi** [comment]
I answered this on https://github.com/saadeghi/daisyui/issues/1431#issuecomment-1347822839 and https://github.com/saadeghi/daisyui/issues/1378#issuecomment-1323755049  

> Tailwind Forms applies style for all inputs by default so this is not something we can fix on daisyUI side.  
You should either use [the `strategy: 'class'` config for Tailwind Forms](https://github.com/tailwindlabs/tailwindcss-forms) so this plugin only applies style to the inputs with specific class names.

If Filament forces you to use `@tailwindcss/forms` with the default config and you can't use `strategy: 'class'` config and also you don't have access to the form elements to use class names on them, this is basically Filament forcing you to apply CSS styles to all form elements on the page (either if it's their own form or your components). That's not cool and they should provide a solution to opt-out of the default styling.

If there's no option to disable the default `@tailwindcss/forms` styles on Filament, or add your own class names for the form elements, that's a limitation from Filament and you should ask them for a solution.

A dirty workaround would be overriding the default `@tailwindcss/forms` styles by adding your own CSS with some `!important` rules so it will fix the daisyUI components (for example `<input type="checkbox" class="toggle">`) who are also affected by the `@tailwindcss/forms` global default styles (like `input[type=checkbox]{}`)

Let me know if you have any questions.
