### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by BrunoRealan** [saadeghi/daisyui#1697]
### What version of daisyUI are you using?

 "daisyui": "^2.51.4",

### Describe your issue

Trying to put a margin-right to a Navbar I realized that it doesn't work and protrudes from the screen.
If I don't use the navbar class it solves the problem but the component doesn't work as such.

### What browsers are you seeing the problem on?

Chrome

**Comment by gukanozadze** [comment]
I would suggest using padding instead.

Width of navbar is set to 100% it's not advisable to use margins, you can do -ml-4 which is similar to mr-4, I don't know what you are trying to build, but I would stick to padding or change my layout so where navbar occupies 100% of width.

**Comment by saadeghi** [comment]
I just have to mention that it's true that navbar has 100% width but if you don't want 100%, you can add any width utility class to override that default width.
