### ISSUE TITLE
twind installation 

### ISSUE THREAD

**Issue by Zegoverno** [saadeghi/daisyui#171]
https://twind.dev/

nice option and aligned with the goal of daisyui and web components I think

**Comment by saadeghi** [comment]
@Zegoverno Currently we can use twind and daisyUI from CDN ([example](https://github.com/saadeghi/daisyui/blob/master/examples/twind/index.html))
But we can't install daisyUI as a Tailwind plugin unless twind adds this feature ([related issue](https://github.com/tw-in-js/twind/issues/211))
