### ISSUE TITLE
bug: btn-outline is not working

### ISSUE THREAD

**Issue by fentech** [saadeghi/daisyui#1712]
### What version of daisyUI are you using?

v2.51.5

### Describe your issue

Here's my Tailwind config:
```
/** @type {import('tailwindcss').Config} */

const defaultTheme = require('tailwindcss/defaultTheme')

module.exports = {
  content: [
    './src/pages/**/*.{js,jsx,ts,tsx}',
    './src/components/**/*.{js,jsx,ts,tsx}',
  ],
  // safelist: ['min-h-full'],
  darkMode: false,
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', ...defaultTheme.fontFamily.sans],
      },
      fontSize: {
        '4xl': '3.2rem',
        '5xl': '3.8rem',
      },
    },
  },
  daisyui: {},
  plugins: [
    require('@tailwindcss/line-clamp'),
    require('@tailwindcss/typography'),
    require('daisyui'),
  ],
}
```

I'm trying to use a simple button with an outline, but it's causing the text to be the same color as the background and it doesn't look outlined at all:
```
<button
            className={cn('btn btn-outline btn-secondary', {
              loading: true,
            })}
            onClick={likeArticle}
          >
            <HandThumbUpIcon className="w-5 h-5 " />
            likes
          </button>
```

With `.btn-outline`

![Screen Shot 2023-03-26 at 3 54 05 PM](https://user-images.githubusercontent.com/9545374/227804084-0c5fe8c7-3cbb-4a98-a04a-1f6a8352652d.png)

Without `.btn-outline`

![Screen Shot 2023-03-26 at 3 54 17 PM](https://user-images.githubusercontent.com/9545374/227804099-afbef47c-5bdc-4a93-ab4e-36eb4ddcf2da.png)

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
Looks like the style for `btn-outline` is not getting generated 🤔   
Can you please provide a reproduction repo?

**Comment by fentech** [comment]
My apologies. Thank you so much for pointing that out. I realize that the directory of that template wasn't in Tailwind config content array blobs.
