### ISSUE TITLE
Daisyui tooltips showing when hovered where the tooltip should be.

### ISSUE THREAD

**Issue by sidney61498** [saadeghi/daisyui#172]
In the documentation it doesn't happen but when I copy the code from the documentation to my code when I hover where the tooltip should be the tooltip shows.

**Comment by saadeghi** [comment]
@sidney61498 can you please make a sample GitHub repo so I can reproduce this bug?

**Comment by obrunsmann** [comment]
Having the same issue. This video might demonstrate it well. But it's kinda weird - I tried to created a minimal example but there it worked fine.

So I gonna try to clean up my table on the video as much as possible to find out what could cause this issue.

https://user-images.githubusercontent.com/763812/133222891-86b75bd4-c6e8-472a-ae33-01d53a389bf0.mov

Working example, similar to the video, so it should reproduce but it doesn't: https://gist.github.com/obrunsmann/c78b66f6d1b8196c380a2314073eb32e

**Comment by saadeghi** [comment]
@obrunsmann Are you sure both repos are using the same version of daisyUI? This issue [was fixed](https://github.com/saadeghi/daisyui/commit/a9f730be710b191ad947769353949f74a839b272) in version `1.12.1`

**Comment by obrunsmann** [comment]
Oh wow, shame on me. I was sure it was the latest version. Obviously, I was not right.

Working absolutely fine with the latest version. Thank you @saadeghi!
