### ISSUE TITLE
bug: Square button style not working correctly

### ISSUE THREAD

**Issue by B4Dmonkey** [saadeghi/daisyui#1720]
### What version of daisyUI are you using?

2.51.5

### Describe your issue

If you set the theme to forest and use the tag btn-square you don't get a square button you get a circle button instead. This is viewable on the daisyui button page

### What browsers are you seeing the problem on?

Chrome, Safari, Other

### Reproduction URL (optional)

https://daisyui.com/components/button/

**Comment by divyashC** [comment]
@saadeghi can you assign me this issue? I guess its a legitimate one, you can see the [Button with loading spinner](https://daisyui.com/components/button/#button-with-loading-spinner) turn round while changing the page theme to forest.

**Comment by saadeghi** [comment]
The reason is, in `forest` them specifically, every radius is rounded. I know that it's called `square` and it should look different from `circle` but how can we expect it to have sharper edges when every other rectangle button has a pill-shaped round corners? 🤔
