### ISSUE TITLE
bug: btm-nav not in flex-row. 

### ISSUE THREAD

**Issue by Coltensiemer** [saadeghi/daisyui#1725]
### What version of daisyUI are you using?

2.51.5

### Describe your issue

Using "btm-nav" on IOS, the text layout is column, not row. I believe this is from the apply for IOS where a "flex-col" is being applied. 

```
.btm-nav {
  @apply flex flex-row items-center justify-around fixed bottom-0 left-0 right-0 w-full;
  padding-bottom: env(safe-area-inset-bottom);
  &>* {
    @apply flex items-center justify-center flex-col basis-full h-full cursor-pointer relative gap-1;
  }
}
```

Checked with chrome dev tools to find that turning off 'flex-direction: column' allows the row to work. 

[
<img width="1512" alt="Screen Shot 2023-03-30 at 8 38 10 PM" src="https://user-images.githubusercontent.com/110078481/228994362-add53e54-db99-4cc2-8188-87b1c7ade1c7.png">

**Comment by saadeghi** [comment]
I think you have an extra div or something in `btm-nav`. The HTML should be something like this
```html
<div class="btm-nav">
  <button>
    About me
  </button>
  <button class="active">
    Projects
  </button>
</div>
```
(or with `<a>` links instead of `<button>`)

Or if you want icons, something like this
```html
<div class="btm-nav">
  <button>
    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" /></svg>
    <span class="btm-nav-label">About me</span>
  </button>
  <button class="active">
    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" /></svg>
    <span class="btm-nav-label">Projects</span>
  </button>
</div>
```

If the markup is correct and you still have issues, I need to see your code so I can find the problem

**Comment by Coltensiemer** [comment]
Hey so I went back to my code. I did have an extra div in my code. This should be good to close the issue. 

Thanks for the help!
