### ISSUE TITLE
bug: can't change or reset margin in card-title and padding in card-body

### ISSUE THREAD

**Issue by bdemon245** [saadeghi/daisyui#1727]
### What version of daisyUI are you using?

v2.51.5

### Describe your issue

While using the card component there are 2 problems that I faced
1. margin utility class doesn't work on cart-title
2. padding utility class doesn't work on cart-body

To reproduce this problem
take a card component and try changing card-body's padding or card-title's margin using utility class

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
Both of them work. Here's an example: https://play.tailwindcss.com/K0p0Y3P1me

If it's not working in your project, please provide a reproduction repo so I can see the code.
