### ISSUE TITLE
Custom color on secondary-focus not work

### ISSUE THREAD

**Issue by Akhsanfr** [saadeghi/daisyui#173]
I wanted to customize the secondary color and it didn't work. The resulting color is incorrect. That's what happened, for example in the component button, the secondary-focus took the color reference from the neutral-focus.
This also occurs in accent colors but not in primary and neutral. For primary and neutral, it still works as it should

**Comment by saadeghi** [comment]
@Akhsanfr Can you make a sample GitHub repo (or Codepen/Tailwind Play page) so I can reproduce this issue?

**Comment by saadeghi** [comment]
Feel free to reopen this issue if the problem still exists or of you have any questions
