### ISSUE TITLE
bug: Fixed Sidebar for desktop not working in electronjs

### ISSUE THREAD

**Issue by rungtavaidik** [saadeghi/daisyui#1730]
### What version of daisyUI are you using?

v2.51.5

### Describe your issue

Hi,
I'm using the below code for a fixed sidebar for desktop electronjs app. It does not seem to be working properly and only lists the items.
Code: 
```html
<!DOCTYPE html>
<html lang="en" data-theme="business">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/daisyui@2.51.5/dist/full.css" rel="stylesheet" type="text/css" />
    <title>Document</title>
</head>
<body>
    <div class="drawer drawer-mobile">
        <input id="my-drawer-2" type="checkbox" class="drawer-toggle" />
        <div class="drawer-content flex flex-col items-center justify-center">
          <!-- Page content here -->
          <label for="my-drawer-2" class="btn btn-primary drawer-button lg:hidden">Open drawer</label>
        
        </div> 
        <div class="drawer-side">
          <label for="my-drawer-2" class="drawer-overlay"></label> 
          <ul class="menu p-4 w-80 bg-base-100 text-base-content">
            <!-- Sidebar content here -->
            <li><a>Sidebar Item 1</a></li>
            <li><a>Sidebar Item 2</a></li>
          </ul>
        
        </div>
      </div>
</body>
<script src="https://cdn.tailwindcss.com"></script>
</html>
```

SS:
![image](https://user-images.githubusercontent.com/122138632/229361121-4a1c1fe8-dd86-4118-bec2-4bed4bc62d86.png)

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
The code is correct and it works in the browser: https://codepen.io/saadeghi/pen/abaeQbj?editors=1000  
I don't have much experience with Electron but are you sure the setup is correct? Judging by your screenshot, it looks like paddings and margins are not correct. Looks like part of the styles are missing.   
Can you try installing Tailwind CSS and daisyUI as Node dependencies instead of using CDN files?

**Comment by rungtavaidik** [comment]
> The code is correct and it works in the browser: https://codepen.io/saadeghi/pen/abaeQbj?editors=1000 I don't have much experience with Electron but are you sure the setup is correct? Judging by your screenshot, it looks like paddings and margins are not correct. Looks like part of the styles are missing. Can you try installing Tailwind CSS and daisyUI as Node dependencies instead of using CDN files?

Thank you, it does work by installing tailwindcss instead of using CDN files

**Comment by rungtavaidik** [comment]
> The code is correct and it works in the browser: https://codepen.io/saadeghi/pen/abaeQbj?editors=1000 I don't have much experience with Electron but are you sure the setup is correct? Judging by your screenshot, it looks like paddings and margins are not correct. Looks like part of the styles are missing. Can you try installing Tailwind CSS and daisyUI as Node dependencies instead of using CDN files?

On installing tailwindcss via npm, it's just more messed up...
![image](https://user-images.githubusercontent.com/122138632/229839995-a5a3ae6c-2395-4d78-a790-f2c7f2bfbcf0.png)
Tailwind config:
![image](https://user-images.githubusercontent.com/122138632/229840279-d93718e8-4b87-4c7f-9b1b-b1b9511711ca.png)

**Comment by saadeghi** [comment]
Something's wrong here. Can you share a reproduction repo so I can run it and see the issue?

**Comment by rungtavaidik** [comment]
> Something's wrong here. Can you share a reproduction repo so I can run it and see the issue?

https://github.com/rungtavaidik/electron-app

**Comment by rungtavaidik** [comment]
The code works perfectly in electron fiddle. But for some reason it does not work for me so I think i'll have to transfer my entire app into fiddle for it to work. Thank you for the help
