### ISSUE TITLE
bug: When using button groups, if your first button isn't the default active, hovering/clicking any button (or a label) will trigger the hover effect on the first button

### ISSUE THREAD

**Issue by TheYuriG** [saadeghi/daisyui#1734]
### What version of daisyUI are you using?

2.51.5

### Describe your issue

If you hover the label or any button without hovering over the first button, it will light up. Hovering the button and then something else will disable the hover until you leave the group, but then it comes back again.

I wanted to have the old Discord style selectors with [✅, **//**, ❌] having the middle option (not selected) as default on, but this bug causes bad UX so I had to switch the orders for now, as a workaround. Eventually, this will not cut it since our users will be able to change the default, causing this issue to reappear for them.

---
@Makowo FYI.

### What browsers are you seeing the problem on?

Chrome (my experience), Firefox (Makowo's experience)

### Reproduction URL (optional)

https://play.tailwindcss.com/LjrItrghiL

**Comment by saadeghi** [comment]
The problem is, you're putting multiple inputs in 1 `label` which is not valid HTML. A label should be used for 1 input element. Consider using another element (like div or span) if you want to put multiple inputs in it.
