### ISSUE TITLE
bug: Cannot lose focus on ios safari while touching.

### ISSUE THREAD

**Issue by gylove1994** [saadeghi/daisyui#1737]
### What version of daisyUI are you using?

2.51.5

### Describe your issue

https://user-images.githubusercontent.com/47300853/230229228-d243415e-27c2-4d1c-b38d-3b06d7b296ad.mp4

### What browsers are you seeing the problem on?

Safari

### Reproduction URL (optional)

https://github.com/gylove1994/daisyui-for-angular

**Comment by gurgunday** [comment]
FYI: if you change the element to `<button>`, it correctly loses focus in Safari as well.

**Comment by saadeghi** [comment]
This is indeed an issue with iOS Safari and CSS `:focus`.  There's no proper fix yet but there are workarounds.

Please follow related discussions: 
- https://github.com/saadeghi/daisyui/issues/824
- https://github.com/saadeghi/daisyui/issues/234

**Comment by Gypsy-147** [comment]
Solve with adding a tabindex="0" to the container or root element
