### ISSUE TITLE
Question: How to customize heights and widths across the whole package

### ISSUE THREAD

**Issue by amitjindal** [saadeghi/daisyui#174]
Hi,
I came across this project and instantly loved this. Felt like tailwind finally became more organized for me.
Thank you for this hard work.

**Problem**
I have been trying to rebuild some of the tailwind UI designs in daisyui for apply to a project.
The problem I am facing is with spacing and sizes. At places tailwind-ui uses h-8/w-8 whereas daisy-ui is using a different size like h-12/w-12 in unstyled buttons.

I want to make this change across the package so I can be consistent. I did not find any variable to do that.
I cannot simply convert the h-12 to act as h-8.

**Screenshots of what I mean**

![2021-09-02_12-41-23](https://user-images.githubusercontent.com/3275983/131799070-b60cccef-9ca9-4bb3-abe2-e258a43e6259.jpg)
![2021-09-02_12-38-23](https://user-images.githubusercontent.com/3275983/131799072-170c5cdd-27bc-4a38-8ad3-74cfe2a2b502.jpg)

**The options I see are:**

1. I am missing something and there is an easy way to do this.
2. I clone daisyui repo and hack the CSS to make it work for me.
3. I override CSS and change it as needed.
4. Define a custom theme which may give me a way to override these. Although I tried I did not find a way.

For 3, currently I am trying this:

```scss
// =========== Daisy ============
.btn {
  @apply h-10 min-h-8;
}

.input {
  @apply h-10 min-h-8;
}

.avatar {
  img {
    @apply rounded-full w-8 h-8;
  }
}

.btn-icon {
  @apply btn-ghost flex-shrink-0 rounded-full p-1 text-gray-400 hover:text-gray-500 focus:outline-none;
}

```

**Question**
Is this the right way? Is there any better way to do this?

Thank you for this package.
Regards
Amit

**Comment by saadeghi** [comment]
@amitjindal Thanks.  
Yes there are fixed sizes for [unstyled buttons](https://github.com/saadeghi/daisyui/blob/master/src/utilities/unstyled/button.css) so they will apply to buttons even if we use [`styled:false` config](https://daisyui.com/docs/config).   
According to this issue, I think that was a wrong decision from me and I had to disable default sizes for [`unstyled` mode](https://daisyui.com/docs/config).  

I just want to confirm that your customized component is using the `styled:false` config. right?

**Comment by amitjindal** [comment]
@saadeghi Thanks for your reply.

Sorry I am very new to this so this might be wrong.

I tried with `styled:false` also but the size was still there so currently I am using the default style customized. This is my config.

Perhaps that could be a css-variable that can be overridden?

```js
    daisyui: {
       styled: true,
       themes: [
          {
             'custom': {                              /* your theme name */
                'primary': primaryColor['600'],             /* Primary color */
                'primary-focus': primaryColor['700'],       /* Primary color - focused */
                'primary-content': colors.white,            /* Foreground content color to use on primary color */

                'secondary': secondaryColor['500'],         /* Secondary color */
                'secondary-focus': secondaryColor['600'],   /* Secondary color - focused */
                'secondary-content': colors.white,          /* Foreground content color to use on secondary color */

                'accent': accentColor['500'],               /* Accent color */
                'accent-focus': accentColor['600'],         /* Accent color - focused */
                'accent-content': colors.white,             /* Foreground content color to use on accent color */

                'neutral': neutralColor['800'],             /* Neutral color */
                'neutral-focus': neutralColor['900'],       /* Neutral color - focused */
                'neutral-content': colors.white,            /* Foreground content color to use on neutral color */

                'base-100': colors.warmGray['50'],          /* Base color of page, used for blank backgrounds */
                'base-200': colors.warmGray['100'],         /* Base color, a little darker */
                'base-300': colors.warmGray['200'],         /* Base color, even more darker */
                'base-content': colors.warmGray['900'],     /* Foreground content color to use on base color */

                'info': infoColor['500'],                   /* Info */
                'success': successColor['500'],             /* Success */
                'warning': warningColor['500'],             /* Warning */
                'error': errorColor['500'],                 /* Error */

                  /*  CSS Values  */
                '--rounded-box': '0.375rem',                 /* border-radius for cards and other big elements */
                '--rounded-btn': '0.375rem',                 /* border-radius for buttons and similar elements */
                '--rounded-badge': '1.9rem',                /* border-radius for badge and other small elements */

                '--animation-btn': '0.15s',                 /* bounce animation time for button */
                '--animation-input': '.1s',                 /* bounce animation time for checkbox, toggle, etc */

                '--padding-card': '1.5rem',                   /* default card-body padding */

                '--btn-text-case': '',             /* default text case for buttons */
                '--navbar-padding': '0',                /* default padding for navbar */
                '--border-btn': '1px',                      /* default border size for button */
                '--focus-ring': '1px',                      /* focus ring size for button and inputs */
                '--focus-ring-offset': '0',                 /* focus ring offset size for button and inputs */
             }
          },
       ],
       base: true,
       utils: true,
       logs: true,
       rtl: false,
    },
 ```

In case the colors don't make sense, I define a primary and secondary color in my tailwind config so that templates are configurable.

```js
const colors = require('tailwindcss/colors');

const primaryColor = colors.emerald;
const secondaryColor = colors.trueGray;
```

Regards
Amit

**Comment by amitjindal** [comment]
Maybe we need some sort of a scaling factor. Mostly form components are consistent in height for a particular template.

If as a user I had a choice to specify that in config, that would solve it.

**Comment by saadeghi** [comment]
@amitjindal actually I'm thinking about completely disable button's fixed sizes when config is `styled:false` because those sizes are design decisions.  
Is that okay?

**Comment by amitjindal** [comment]
Hmm.. So lets think about that.

Yes when `styled:false` it should be disabled as you correctly pointed out, its a design decision.
However after doing that all users who are depending on this behavior (styled:false) will see their code break.
You might need to provide backward compatibility. Either by a switch or a configurable default variable like `--component-height`.

Now for styled elements, you will still need to add these in each style. That will probably be better served with a variable so that its easy to configure.

In practice, most (except maybe textarea) components are of same height. So I would suggest using a variable (or more than one variables) to provide this behavior. It will ensure backward compatibility and a way to easily customize controls.

The way I see daisyui is similar to what bootstrap offers via SCSS variables that can be configured to reshape the framework. Here we are doing that with vars.

**Comment by saadeghi** [comment]
@amitjindal Using a variable looks interesting but not all components are sharing the same values.  
`btn-md` height is `h-12`  
`input-md` height is `h-12`  
`tab-md` height is `h-8`
`checkbox-md` height is `h-6`  
`badge-md` height is `h-5`  
etc...   
The reason is they all come in 4 sizes but a medium button shouldn't be the same size as a medium checkbox.

**Comment by amitjindal** [comment]
@saadeghi Sure. So we will need to create multiple variables. Probably what you are suggesting or these:

```
--btn-height: h12
--input-height: h12
--tab-height: h8
--input-checkbox-height: h6
--badge-height: h5
```

**Comment by gregroyal** [comment]
I'm interested in this feature. Has there been any headway on it?

**Comment by saadeghi** [comment]
I would like to make it possible but using CSS variables to make every sizing customizable will increase the file size significantly.  
However it is possible to change the size of every element all together:  
Because both Tailwind CSS and daisyUI are using `rem` units, you can basically change the font size of root element and make everything smaller/bigger: https://play.tailwindcss.com/h3snkGvWTb?file=css
