### ISSUE TITLE
docs: how to disable the hover effect from the entire theme? 

### ISSUE THREAD

**Issue by shadowDarsan** [saadeghi/daisyui#1741]
### Describe the issue

In every theme there is by default hover effects in button , a tags 

### What browsers are you seeing the problem on?

_All_

**Comment by saadeghi** [comment]
See this: https://github.com/saadeghi/daisyui/discussions/1511   
let me know if you have any questions

**Comment by saadeghi** [comment]
You can use a Post CSS plugin like this to remove all hover styles: 

https://www.npmjs.com/package/postcss-hover

Or this to remove the hover styles for touch devices:  
https://www.npmjs.com/package/postcss-hover-media-feature
