### ISSUE TITLE
Footer component not styling correctly

### ISSUE THREAD

**Issue by seanodotcom** [saadeghi/daisyui#175]
Trying to replicate the <a href="https://daisyui.com/components/footer/" class="underline">Daisy UI footer</a>, specifically the simple "footer with copyright text and social icons", but the flex/grid styling does not match the docs, either in testing or on Codepen - each &lt;div&gt; gets kicked to a new line.

Codepen demo, copy/pasted from docs with no alterations: https://codepen.io/seanodotcom/pen/BaZzKpB

Effect is the same in & out of the .container &lt;div&gt;.

**Comment by saadeghi** [comment]
@seanodotcom Fixed on version `1.14.1`: https://codepen.io/saadeghi/pen/abwaVYd  
Use the new markup from examples: https://daisyui.com/components/footer/  

Let me know if there was an issue
