### ISSUE TITLE
Potential to have more control over dark mode.

### ISSUE THREAD

**Issue by tom-acceleratecompliance** [saadeghi/daisyui#176]
Hi!
Not sure how possible this would be, but it would be fantastic to be able to have more control over what gets automatically switched to when the system changes to dark mode.

My understanding is currently, if any theme with the name 'dark' it will be swapped to when the browser goes dark.

However, in a situation where we have three seperate branded themes which we route users to based on their email host (or something else), they all have to have the same 'dark' theme. I don't know how possible it is, but something like this would be fantastic:

```
<html data-theme='customTheme' data-dark-theme='customThemeDark'>
```

Another option would be to have some way of extending it in the `themes` config, I'm not sure what that would look like thought.

Thanks again for the fantastic framework!

**Comment by saadeghi** [comment]
@tom-acceleratecompliance You're right.  
This feature will be added on the next major release.

( Related issue https://github.com/saadeghi/daisyui/issues/135 )

**Comment by saadeghi** [comment]
Now you can specify one of themes to be the default dark mode theme (based on `prefers-color-scheme: dark`):  
https://play.tailwindcss.com/CLrZGvf3ww?file=config  
And the first item in `themes` config will be the default light theme.
