### ISSUE TITLE
bug: select element not displaying correctly

### ISSUE THREAD

**Issue by m00dy** [saadeghi/daisyui#1760]
### What version of daisyUI are you using?

Latest DaisyUI

### Describe your issue

https://user-images.githubusercontent.com/1063085/232600587-6e1aad59-4ef4-4739-9a32-6119f0a1c3f2.mov

Google Chrome 
Version 112.0.5615.121 (Official Build) (arm64)
Dimensions: Iphone 12 pro

It only happens on Iphone 12 pro simulation.

### What browsers are you seeing the problem on?

Chrome

Sample code:
```
        <div className="form-control w-full max-w-xs">
            <label className="label">
                <span className="label-text">{props.description}</span>
            </label>
            <select className="select select-bordered">
                <option key={0} disabled>Pick one</option>
                {props.options.map((option: string, idx:number) => <option key={idx+1}>{option}</option>)}
            </select>
            <label className="label">
                <span className="label-text-alt">Alt label</span>
            </label>
        </div>
```

**Comment by saadeghi** [comment]
- Does this happen if you disable the daisyUI? (does the select menu open in a small size in the corner of the screen?)
- Do you have a proper viewport metatag in your HTML?  
  (for example `<meta name="viewport" content="width=device-width, initial-scale=1" />`)

**Comment by saadeghi** [comment]
Feel free to re-open this issue if the problem still exists.
