### ISSUE TITLE
Question: Why does daisyui doesn't not add into "bundle" in production but tailwind does?

### ISSUE THREAD

**Issue by Hugo01** [saadeghi/daisyui#177]
I'm building a lib which uses Vite/Vue3 and Tailwind with Daisy 
The problem is: When I use "yarn build", while on production all the classes from tailwind works but none of the classes of daisy works, it didn't export the classes from daisyui
DIST directory outputs a ES,UMD module and a style.css which does not contain any of the daisyui classes

Here's my tailwind.config
```
module.exports = {
  important: true,
  purge: [
    './*.html',
    './src/**/*.html',
    './src/**/*.vue',
    './src/**/*.jsx',
    './src/**/*.ts'
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      animation: ['hover', 'focus']
    },
    backgroundColor: theme => ({
      ...theme('colors'),
      infoDark: '#ededed',
      infoLight: '#fbfbfb',
      infoDarker: '#dcdcdc'
    })
  },
  variants: {
    extend: {}
  },
  plugins: [
    require('daisyui')
  ],
  daisyui: {
    themes: [
      'light',
      'dark'
    ]
  }
}

```

Here's my index.css
```

@tailwind base;
@tailwind components;
@tailwind utilities;
```

My index.ts which is the entrypoint for vite to build as a library (I think the issue is around here somewhere)
```
import './index.css' 
export { default as AMMap } from ...

```

Here's my vite.config
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import * as path from 'path'
import typescript2 from "rollup-plugin-typescript2"

// https://vitejs.dev/config/

export default defineConfig({
  plugins: [vue()],
  optimizeDeps: {
    esbuildOptions: {}
  },
  build: {
    lib: {
      entry: path.resolve(__dirname, '/src/index.ts'),
      name: 'name',
      fileName: (format) => `lib-name.${format}.js`
    },
    rollupOptions: {
      external: ['vue'],
      output: {
        globals: {
          vue: 'Vue'
        }
      }
    }
  },
  resolve: {
    alias: {
      '@': path.join(__dirname, '/src')
    }
  }
})

```

**Comment by saadeghi** [comment]
@Hugo01 Can you please make an example repo so I can reproduce this?

**Comment by Hugo01** [comment]
> @Hugo01 Can you please make an example repo so I can reproduce this?

Thanks for the quick answer, i managed to get it working, vite wasn't re-creating the style.css, I just cleaned the yarn cache and it worked
Right now I have another question, in my situation I have 2 projects, both using DaisyUi, one main project and another one that actually work as a library

1. **Project1** (main project) has its own DaisyUi theme with custom colors and everything, so if i call:
`<button class="btn btn-primary"> Button</button>` it will apply the configured theme on tailwind.config.js

2. **Project2** (Library which is imported in project1) also uses Daisy with custom themes, what happens is since project2 is being imported in project1, project2 are now using Project1 classes since they both have the same name, ex: "btn btn-primary", is there any workaround for this?

**Comment by saadeghi** [comment]
> 2\. what happens is since project2 is being imported in project1, project2 are now using Project1 classes since they both have the same name, ex: "btn btn-primary", is there any workaround for this?

@Hugo01 You can use [Tailwind's prefix](https://tailwindcss.com/docs/configuration#prefix) and every class name of that build will only work with your prefix. However it applies to *every* utility class from tailwind (like `tw-w-10`) as well as daisyUI classes (like `tw-btn`)

**Comment by Hugo01** [comment]
@saadeghi Thanks! but it didn't work, I added the prefix but still when I import the CSS from the lib on the main project `import "dist/mylib/style.css` (note that the style.css ONLY contains classes with the prefixes, I checked that) it seems that all classes are somehow overwritten, for instance, "bg-neutral" that used to be blue is now grey, it looks like it is applying the default theme somehow, perhaps thats because on the lib i'm exporting "index.css" which contains
```
@tailwind base; 
@tailwind components;
@tailwind utilities
```


This kinda of stuff is hard to explain and easy to show, I'll be creating the two repo so will be easy to test it

**Comment by Hugo01** [comment]
Here's the **Project1**: (the main project that imports the lib, you can see that on the package.json) https://gitlab.com/hugo6467/project1/-/tree/master (Just run yarn install and yarn dev)

Here's the **Lib**: https://gitlab.com/hugo6467/amazing-map/-/tree/develop (Run yarn install and yarn dev to see what the colours should be, you can run)

To test the changes you should probably run `yarn link` on the lib and `yarn link my-lib` on project1 and then `yarn build` on the lib

**Comment by Hugo01** [comment]
A little update.
Still haven't found a solution for this
The "workaround" I'm using for now is just don't import the style from the lib and let the entire application on the same "theme"

**Comment by Hugo01** [comment]
@saadeghi 
Hey! I think I've found the source of the problem
When building as library mode, "style.css" generated by vite uses for example: "**AM-btn-primary**" as "**background-color:hsla(var(--p)/var(--tw-bg-opacity,1))**" which is pretty much the same as regular **btn-primary** that's why even using prefixes it doesn't change anything
![image](https://user-images.githubusercontent.com/8092834/132149206-9f13e5b7-8da1-4862-b7ec-de0dedb06c5a.png)
![image](https://user-images.githubusercontent.com/8092834/132149229-27cf6df6-65f6-4850-ab76-6547a57df979.png)

**Comment by saadeghi** [comment]
@Hugo01 So, the problem is CSS variables with the same name?  
Isn't it better to use one tailwind build with two [daisyUI themes](https://daisyui.com/docs/default-themes)? Because you can use multiple themes in different parts of a page.
Example:
```
<div data-theme="cupcake">

  <button class="btn">this button uses cupcake theme</button>
  <div data-theme="valentine">
    <button class="btn">this button uses valentine theme</button>
  </div>

</div>
```

**Comment by saadeghi** [comment]
Feel free to reopen this issue if above solution doesn't work for you or if you have any questions
