### ISSUE TITLE
not working with windi css

### ISSUE THREAD

**Issue by ctwhome** [saadeghi/daisyui#178]
hi!

I couldn't make it work with windicss and 'nuxt-windicss'

![](https://user-images.githubusercontent.com/4195550/131982855-2b976682-5e42-430c-a4a5-f83858cd504c.png)

Sometimes also complains about postcss

![](https://user-images.githubusercontent.com/4195550/131984474-99b3c3a1-5d31-4806-8ede-3f6873c8734d.png)

**Comment by ctwhome** [comment]
related issue https://github.com/windicss/nuxt-windicss-module/issues/113

**Comment by saadeghi** [comment]
@ctwhome Can you please make an example repo so I can reproduce this?  
I'm not sure but this looks like a problem from Windi CSS, not daisyUI.  
daisyUI is essentially just a [collection of class names](https://unpkg.com/daisyui@1.14.0/dist/styled.js) 🤷‍♂️

**Comment by ctwhome** [comment]
yes, thank you for taking a look at it 

[https://github.com/ctwhome/windi-daisyui](https://github.com/ctwhome/windi-daisyui)

It seems that some daisyui styles are not being applied either

**Comment by saadeghi** [comment]
@ctwhome Purge list is not targetting the `.vue` files: https://github.com/ctwhome/windi-daisyui/blob/master/windi.config.js  
I didn't get any errors but `btn` had no style.  
So I made this change and it worked:  
```diff
const { transform } = require('windicss/helpers')

module.exports = {
  extract: {
-  include: ['./*.html'],
+  include: ['./pages/*.vue'],
  },
  plugins: [transform('daisyui')],
}

```

**Comment by Destaq** [comment]
Encountering a similar issue when trying to combine `nuxt-windicss` and `daisyui` - this issue only crops up when `transform`ing `daisyui` (as below):

```js
const { transform } = require("windicss/helpers");

module.exports = {
  plugins: [transform("kutty")],
};
```

Sample repo is [here](https://github.com/Destaq/nuxt3-windi-daisyui). Any tips?

**Comment by itshizhan** [comment]
🌼 daisyUI components 1.19.0  https://github.com/saadeghi/daisyui                                           

 ERROR  [unhandledRejection] Maximum call stack size exceeded                                                 

  at String.trim (<anonymous>)
  at splitSelectors (/D:/dev/vocabpark_com/node_modules/windicss/lib/index.mjs:361:25)
  at guessClassName /D:/dev/vocabpark_com/node_modules/windicss/lib/index.mjs:367:16)
  at /D:/dev/vocabpark_com/node_modules/windicss/lib/index.mjs:367:67
  at Array.map (<anonymous>)
  at guessClassName /D:/dev/vocabpark_com/node_modules/windicss/lib/index.mjs:367:41)
  a /D:/dev/vocabpark_com/node_modules/windicss/lib/index.mjs:367:67
  at Array.map (<anonymous>)

**Comment by saadeghi** [comment]
@itshizhan https://github.com/saadeghi/daisyui/issues/349#issuecomment-999218977

**Comment by itshizhan** [comment]
upgrade nuxt-windicss v2.2.5 is ok
