### ISSUE TITLE
bug: Size issue with rating half stars

### ISSUE THREAD

**Issue by pguardiario** [saadeghi/daisyui#1787]
### What version of daisyUI are you using?

2.51.5

### Describe your issue

Can someone explain how to get normal-sized half stars in rating classes?
```
<div class="rating rating-sm">
  <input type="radio" class="mask mask-star-2 bg-orange-400 ">
  <input type="radio" class="mask mask-star-2 bg-orange-400 mask-half-1" checked="">
  <input type="radio" class="mask mask-star-2 bg-orange-400 ">
  <input type="radio" class="mask mask-star-2 bg-orange-400">
  <input type="radio" class="mask mask-star-2 bg-orange-400">
</div>
```
![image](https://user-images.githubusercontent.com/58795222/235390184-32d1f0a7-c3d5-4266-a515-a669e00570e2.png)

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
If your total options are 10 (10 half stars = 5 stars) then you should have 10 inputs like [the example](https://daisyui.com/components/rating/#half-stars)  
Also `rating-half` is needed (which changes the width of each input to half)  
Example: https://play.tailwindcss.com/nm0O0NXUam?layout=horizontal

Let me know if you have any questions

**Comment by pguardiario** [comment]
Thanks, that makes sense
