### ISSUE TITLE
How to properly close modal

### ISSUE THREAD

**Issue by DanDev95** [saadeghi/daisyui#179]
When clicking close, the modal is just set to hidden. When opening again, it still has it's old values you typed in before closing it. I have a component which has to have its own modal, but right now it inherits the last input from modals that have been opened in other instances of the component.

**Comment by saadeghi** [comment]
I think you need some javascript to reset the form: https://play.tailwindcss.com/Z2vcj1Qwod

Let me know if you have any questions
