### ISSUE TITLE
Drawer content doesn't hide iOS browser bar on scroll

### ISSUE THREAD

**Issue by gazmania** [saadeghi/daisyui#1793]
### What version of daisyUI are you using?

2.51.6

### Describe your issue

Hi,

Loving DaisyUI, thank you so much.

For Drawer, it currently use a nested div for the content panel and that nested div is set to overflow so it can scroll.  It's a minor niggle but because the scroll is inside the nested div and not the body that is scrolling, the nav/browser bar on iOS doesn't hide.  After digging around and trying a few hacks i've not been able to get the iOS browser bar to hide while using the drawer.  From what i've read it only hides on a body scroll event.

I noted from another ticket that you were rewriting Drawer for v3.0.  Is there any chance you could consider this enhancement and somehow getting the content pane to not have to use overflow so it falls back to the body scroll?

### What browsers are you seeing the problem on?

Safari

**Comment by saadeghi** [comment]
Yes this will be fixed in version 3.0 coming this month.

**Comment by gazmania** [comment]
@saadeghi fantastic, thank you
