### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by minhhungit** [saadeghi/daisyui#1799]
### Describe your issue

home page, component demo page...
![image](https://user-images.githubusercontent.com/2279508/236495917-9600593b-f5e7-431b-a020-3ea5659a37b7.png)

![image](https://user-images.githubusercontent.com/2279508/236495959-a5c18eb9-e1f9-4c90-af71-3898a444e80c.png)

**Comment by minhhungit** [comment]
@saadeghi unlucky not yet

**Comment by minhhungit** [comment]
I think I know why, my adblock extension caused it

**Comment by minhhungit** [comment]
I use uBlock orginin

**Comment by saadeghi** [comment]
I can't do anything about this because daisyUI has no trackers and no cookies, so it's not expected for AdBlock to block any scripts. Especially if it's preventing the page to render.  
It should just hide that small ad banner visually.
