### ISSUE TITLE
When using cdn to import daisyui for use, must I import tailwindcss?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [saadeghi/daisyui#1801]
### Describe your issue

```
<link href="https://cdn.jsdelivr.net/npm/daisyui@2.51.6/dist/full.css" rel="stylesheet" type="text/css" />
<script src="https://cdn.tailwindcss.com"></script>
```

Is it possible to import only daisyui for use?

**Comment by saadeghi** [comment]
Yes, daisyUI CSS file works without Tailwind CSS but it only includes diasyUI class names for components (`.btn`, `.card`, `.toggle`, etc.) It does not include Tailwind CSS utility classes (`flex`, `text-lg`, `p-2` etc...)

Let me know if you have any question.
