### ISSUE TITLE
bug: stroke colors not quite working

### ISSUE THREAD

**Issue by joshcho** [saadeghi/daisyui#1802]
### What version of daisyUI are you using?

2.45.0

### Describe your issue

I am trying to set class "stroke-primary" on an svg, but it isn't quite working. I tried "stroke-cyan-500" like in vanilla tailwind and it works. Tested on chrome and brave.

### What browsers are you seeing the problem on?

Chrome, Other

**Comment by saadeghi** [comment]
It should work. Here's a example: https://play.tailwindcss.com/qiMm40siv3

If it's not working, I think something might be wrong about your Tailwind CSS config.  
Make sure the path to all your template files is addressed in `tailwind.config.js` file. If you couldn't find the issue, please share a sample repo so I can see.
