### ISSUE TITLE
bug: button size changes on click

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [saadeghi/daisyui#1806]
### What version of daisyUI are you using?

2.51.6

### Describe your issue

On `btn-xs` when using `no-animation` class to prevent scale on click (active & focus state), looks like a small change happened on button size when clicking...
It's something like italic of letter-spacing applied to text but there is not any modification like this.
Looks like the `transform: scale(var(--btn-focus-scale,.95));` property which expects to do nothing on `no-animation` buttons is causing this issue. When I disable this property it doesn't happen.  

Firefox Developer Edition 113:
[Screencast from 05-10-2023 09:22:31 PM.webm](https://github.com/saadeghi/daisyui/assets/17345129/1fbdb8af-29c3-4225-8d3e-4f88f31fe056)

Firefox 112:
[Screencast from 05-10-2023 09:25:57 PM.webm](https://github.com/saadeghi/daisyui/assets/17345129/bf92e6f9-4348-4317-af18-b5d8a280d35e)

### What browsers are you seeing the problem on?

Firefox

### Reproduction URL (optional)

https://play.tailwindcss.com/FYJ9XB8teW

**Comment by saadeghi** [comment]
That's strange. I couldn't reproduce the issue on my FireFox (MacOS 13.3) but thanks for the video.  
using `no-animation` class, `--btn-focus-scale` value is `1` so basically `transform: scale(var(--btn-focus-scale,.95))` is `transform: scale(1)` which is expected to have no effect.

Can you please try the following tests:

1. With `:active` and `:hover` enabled, does checking/unchecking this line, apply a visual change in the button?  
    <img width="573" alt="49384" src="https://github.com/saadeghi/daisyui/assets/7342023/3866d7d2-30f0-4ac4-8471-7a7f4b69e187">

2. In normal state, if you add a `transform: scale(1)` style to the button, does it apply a visual change?  
    <img width="452" alt="532" src="https://github.com/saadeghi/daisyui/assets/7342023/c7ad7895-a7c2-453c-8d92-f39ebee7cf02">

**Comment by AmirHosseinKarimi** [comment]
Yes `--button-focus-scale` value is `0` but looks like this bug comes from Firefox. Because `scale(1)` should not cause any change to element, which causes in Firefox!
Anyway, I created #1809. That doesn't add `transform: scale()` property to buttons has `no-animation` class which fix the issue.
I think it's better to don't apply `scale` instead to apply `scale(1)`.

**Comment by AmirHosseinKarimi** [comment]
Also, I created a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1832501) for Firefox.
