### ISSUE TITLE
Add password input

### ISSUE THREAD

**Issue by DanDev95** [saadeghi/daisyui#182]
Please add a password input, as it does not already exist.

**Comment by Hugo01** [comment]
Just use type "password" on the native input html tag
```
 <input type="password" >
```

**Comment by saadeghi** [comment]
As @Hugo01 mentioned, you can use `type="password"`.  
I don't think a password input needs any specific style 🤷‍♂️

**Comment by crapthings** [comment]
maybe an reveal button?

**Comment by saadeghi** [comment]
> maybe an reveal button only use css?

Well, we can't change the input type using CSS (to reveal the password). We need JS for that
