### ISSUE TITLE
Add sizing for component stats

### ISSUE THREAD

**Issue by devopg** [saadeghi/daisyui#183]
Add sizing for component stats can apply to single stat or one time for group

stat
stat-xs
stat-sm
stat-md
stat-lg

like this:

![image](https://user-images.githubusercontent.com/61819835/132105338-fbbefdb3-899f-426a-a4c1-d0c7971ed3fa.png)

**Comment by devopg** [comment]
is it difficult to do ? do you have an understanding?

**Comment by saadeghi** [comment]
This is now possible by using Tailwind's utility classes for font size:  
https://play.tailwindcss.com/SoEMzyqu37
So I don't think we need more classes just to adjust the font size.

Please let me know if you have any questions
