### ISSUE TITLE
bug: base-100 becomes page background color, is this intended?

### ISSUE THREAD

**Issue by franklsf95** [saadeghi/daisyui#1835]
### What version of daisyUI are you using?

2.51.6

### Describe your issue

When I set the `base-100` color in my `tailwind.config.js` like so:
```
  daisyui: {
    themes: [
      {
        mytheme: {
          // ...
          "base-100": "#C8F6F3",
        },
      },
    ],
  },
```

I noticed any page I have by default has this `base-100` as the background color. Is this intended behavior? If so, is it documented somewhere? It took me a while to find out this is the behavior.

### What browsers are you seeing the problem on?

Chrome

### Reproduction URL (optional)

https://play.tailwindcss.com/pFaarOZGkz?file=config

**Comment by saadeghi** [comment]
It's mentioned here on the [colors](https://daisyui.com/docs/colors/) page:

>base-100
Base color of page, used for blank backgrounds

Also, I think the name "base" is descriptive itself.  

Without this behavior, it would be required for everyone to add `bg-base-100 text-base-content` to their `<html>` tag to get the expect colors of each theme and that would be extra work.

Is there something else you were going to achieve? Like using another color for the background?

Let me know if you have any questions

**Comment by franklsf95** [comment]
Thanks for explaining. I didn't realize its role, I only set it because it is said to be required by a theme.
