### ISSUE TITLE
docs: medium button not explicitly indicated

### ISSUE THREAD

**Issue by jofftiquez** [saadeghi/daisyui#1837]
### On which page do you see this issue?

https://daisyui.com/components/button/#button-sizes

### Describe the issue

In connection to https://github.com/saadeghi/daisyui/issues/1836 the issue happened because I thought there is no explicit class for medium button which apparently is existing in the code but not documented properly in the example which led to the said confusion.

**Comment by saadeghi** [comment]
But... it is documented:  
https://daisyui.com/components/button/


<img width="772" alt="Screenshot 2023-05-24 at 20 51 57" src="https://github.com/saadeghi/daisyui/assets/7342023/558c8138-0979-4241-a91b-da643d15316a">

**Comment by jofftiquez** [comment]
@saadeghi fair, however some people jumps to the example directly. Like what happened to me 🤣 IDK still up to you, I just think it'd be a good addition to accommodate the btn-md in the example as well :D 

Love your work btw, best tailwind library! 🔥
