### ISSUE TITLE
Allow create badge with image

### ISSUE THREAD

**Issue by devopg** [saadeghi/daisyui#184]
Allow create badge with image without padding and round with 1 side  (watch badge №3)
![image](https://user-images.githubusercontent.com/61819835/132105139-178635a3-71e1-49c6-a61e-d9060dc90730.png)

**Comment by devopg** [comment]
or it will be 'TAG' component? 


is this up-to-date information?
![image](https://user-images.githubusercontent.com/61819835/132128445-1a8dd294-bd07-457b-930d-93d30f1b39c6.png)

**Comment by saadeghi** [comment]
@devopg I'm not sure how to generally handle the padding of the badge for all these scenarios:
- only text
- text and image with no padding
- text and icon with padding

Any suggestions?

**Comment by devopg** [comment]
> @devopg I'm not sure how to generally handle the padding of the badge for all these scenarios:
> 
> * only text
> * text and image with no padding
> * text and icon with padding
> 
> Any suggestions?

leave everything as it is, but if the picture is so add class: 

<div class="badge badge-image badge-primary">
      <img src="path">
       primary
</div>

**Comment by saadeghi** [comment]
@devopg But the `<img>` could be a svg or png icon 🤔

**Comment by devopg** [comment]
if see badge-image 
then padding: 0

**Comment by nandi95** [comment]
@saadeghi I imagine this can be closed as it's pretty easy to make with the `join` utility.
