### ISSUE TITLE
bug: tooltip leaves the screen

### ISSUE THREAD

**Issue by nikkorejz** [saadeghi/daisyui#1842]
### What version of daisyUI are you using?

v2.51.6

### Describe your issue

I have a tooltip, that places close to right border of screen. When I hover the div (with tooltip), the tooltip leaves the screen. 
I know that I can use class `tooltip-left` for example, but in vuetify library (for example), the tooltip will offset to left or changed itself width for correct view

How it looks like:
![2023-05-28_14-24](https://github.com/saadeghi/daisyui/assets/8490106/96dbbc69-723d-43c3-bf82-49e5a0cd5311)

What I expected:
![2023-05-28_14-22](https://github.com/saadeghi/daisyui/assets/8490106/b1b02c33-d718-4f3b-b2f4-2a634dda92b6)

**Comment by saadeghi** [comment]
Vuetify is a JS library so the can calculate the offset from the edge of screen using JS and position the tooltip accordingly.  
This is not possible with CSS and daisyUI is just a CSS file. However you can write your own JS to position the tooltip depending on the position or you can use a headless library like Floating UI alongside daisyUI which does the exact thing you're looking for.

Let me know if you have any questions

**Comment by robsontenorio** [comment]
@saadeghi At this time, is there any workaround without JS ?

**Comment by saadeghi** [comment]
@robsontenorio Unfortunately no. [Floating UI](https://floating-ui.com) is the best option we have for now.

**Comment by saadeghi** [comment]
The upcoming CSS feature `CSS Anchor Positioning` would make this possible, but it's not supported by browsers yet. Only Chrome Canary at this time with the `#experimental-web-platform-features` flag.

- https://www.w3.org/TR/css-anchor-position-1/
- https://developer.chrome.com/blog/whats-new-css-ui-2023/#anchor-positioning
- https://codepen.io/web-dot-dev/pen/PoyRaZe
