### ISSUE TITLE
Modal opens another modal

### ISSUE THREAD

**Issue by DanDev95** [saadeghi/daisyui#185]
I have 2 different modals in my code, they have different ids. When I open one of them, it automatically opens the other too. Is this a bug in the library?

**Comment by DanDev95** [comment]
Here is a video showing it https://streamable.com/9t5238

**Comment by saadeghi** [comment]
@DanDev95 I see... this happens when all modals are siblings 🤦‍♂️  
I will fix this on next update. Until then, you can put each modal inside a div to isolate them from others: https://play.tailwindcss.com/71B7rdeaX0
