### ISSUE TITLE
We need v3 version

### ISSUE THREAD

**Issue by Toursslivers** [saadeghi/daisyui#1856]
### What version of daisyUI are you using?

v3.0.0

### Describe your issue

We need v3 version

**Comment by saadeghi** [comment]
It will be published to NPM tomorrow.  
You can install `daisyui@0.0.0-insiders.3.16` to try it sooner.  
And you can read the changelog here: https://github.com/saadeghi/daisyui/blob/v3/CHANGELOG.md

**Comment by kauhat** [comment]
Refreshed the docs today and noticed the new version was out. I've updated a project already with no issues.

Thanks for all your hard work on this!
