### ISSUE TITLE
bug: table header unnecessary z-index

### ISSUE THREAD

**Issue by lkwr** [saadeghi/daisyui#1857]
### What version of daisyUI are you using?

v2.52.0

### Describe your issue

The first child of a `<th>` in a table has a `z-index` of `11`. Why is this needed? I don't see the benefit and in my project this produce a weird overlapping with the navbar:

![Screenshot 2023-05-31 at 10 25 53](https://github.com/saadeghi/daisyui/assets/49527534/4d8fcea7-aab1-4959-9069-547d9151d01f)

The first column is overlapping my navbar here. I know I can easily increase the `z-index` of my navbar but the `z-index` in the `<th>` makes no sense for me.

Is there a reason why the `z-index` exists? [(code reference)](https://github.com/saadeghi/daisyui/blob/bf7b1d8914fff816f9913cb78c01f5c10662c420/src/components/unstyled/table.css#L7)

**Comment by saadeghi** [comment]
This is no longer an issue in the new version `3.0` update.  
In daisyUI `2.0` table was too opinionated and it was causing issues in many cases. The style is completely rewritten for `3.0` and it's more customizable.
