### ISSUE TITLE
Add skeleton loader

### ISSUE THREAD

**Issue by ExordiumX** [saadeghi/daisyui#186]
A nice addition to this ui kit would be a skeleton loader, such as this one https://vuetifyjs.com/en/components/skeleton-loaders/#usage

**Comment by Hugo01** [comment]
Would be nice but tailwind already has one that kinda works
https://tailwindcss.com/docs/animation
Checkout the "pulse" animation, could be use as skeleton loader

**Comment by devopg** [comment]
> Would be nice but tailwind already has one that kinda works
> https://tailwindcss.com/docs/animation
> Checkout the "pulse" animation, could be used as skeleton loader

i think about skeleton without code 
like this:
`<div class="w-4 h-15 skeleton-type-1"></div>`
and you receive: 
![image](https://user-images.githubusercontent.com/61819835/132189612-a27e5189-5ed3-44e4-b318-be74950de7a2.png)

**Comment by saadeghi** [comment]
@Hugo01 That would be cool but I think there's a high chance that the real layout don't match one of these 👀

**Comment by tom-acceleratecompliance** [comment]
Just to add a +1 - we'd have a real use for these types of components as well. Often when designing a page, the actual component is rendered with data in the application, but in the design view we use a placeholder, a variety of placeholders would be perfect for this.

**Comment by atresnjo** [comment]
That would be nice. Would be really cool to have something like skeleton-circle, skeleton-square, skeleton-progress etc

**Comment by saadeghi** [comment]
Yeah, that's probably the most efficient way 🤔  
- skeleton (for rectangle)
- skeleton-text
- skeleton-circle

And anything can be achieved using width/height utilities and flexbox/grid

**Comment by GustavoFenilli** [comment]
Maybe add as an modifier to the components that are most likely used for those? Input, Avatar, Button and so on

So something like `btn btn-primary skeleton`, skeleton would use sizing and all from the btn, but remove color and text to add pulse.

**Comment by nandi95** [comment]
What tailwind doesn't have is a shimmer animation, that could be added here maybe?
https://codepen.io/maoberlehner/pen/bQGZYB

**Comment by saadeghi** [comment]
Fixed in daisyUI 4
