### ISSUE TITLE
docs: HTML and JSX examples in some pages are empty 

### ISSUE THREAD

**Issue by arily** [saadeghi/daisyui#1860]
### On which page do you see this issue?

https://daisyui.com/components/menu/

### Describe the issue

![image](https://github.com/saadeghi/daisyui/assets/10007589/7483f6ce-59a9-4d92-a9ce-c7b79890bf87)
![image](https://github.com/saadeghi/daisyui/assets/10007589/1f271777-81a5-47c0-bd95-10b39117d397)

it looks like that only some v3 examples are empty. Clean my cache does not help.

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by saadeghi** [comment]
Will be fixed in 5 min...

**Comment by saadeghi** [comment]
Fixed. Let me know if you found other issues 🙏
