### ISSUE TITLE
bug: The <a> tag in .menu has an abnormal style when it is focused and active

### ISSUE THREAD

**Issue by zkl2333** [saadeghi/daisyui#1868]
### What version of daisyUI are you using?

v3.0.0

### Describe your issue

The `<a>` tag in `.menu` has an abnormal style when it is focused and active
![image](https://github.com/saadeghi/daisyui/assets/18900961/d98a68bb-d4d3-4097-9cfc-f2b9bc2ae251)
![image](https://github.com/saadeghi/daisyui/assets/18900961/be8d3d7c-89af-49a2-bb65-344aeda9e036)

### What browsers are you seeing the problem on?

Chrome

**Comment by Bjeaurn** [comment]
Seeing the same, it seems to default to use the `--n` variable for `neutral` color as background, instead of using `primary` or `--p` like it did previously. Might be a regression.

**Comment by Andrew67** [comment]
Another workaround: I was already applying `bg-primary` to active menu items, so I changed it to `bg-primary focus:bg-primary-focus` and it also worked.

**Comment by mohammadsemmo** [comment]
You could also remove focus from the element after it's clicked
```
const handleClick = () => {
  if (document.activeElement instanceof HTMLElement) {
    document.activeElement.blur();
  }
};
```
