### ISSUE TITLE
Badge inconsistency when using success, error, warning and info

### ISSUE THREAD

**Issue by colorninja** [saadeghi/daisyui#187]
Big thanks to you Pouya and to all contributors for this amazing component set!

When using `badge-error`, some of our users find it difficult to read the number off the badge. This is because the colour of the number is the error colour and the background has opacity. For example (primary #2266B1, error: #ff0000):
![image](https://user-images.githubusercontent.com/32983864/132227002-4842da77-9787-4829-8813-827a3267b79b.png)

I have intentionally added `badge-primary` next to it, so the difference can be seen easily.

**`badge-primary` defines the background colour and `badge-error` defines the text colour, which is confusing.**

I think this has been implemented using opacity, because there is no error-content colour in the themes. I think it might be useful to add the `*-focus` and `*-content` properties for success, error, warning and info. I would also be happy to submit a PR to add them.

**Comment by saadeghi** [comment]
@colorninja You're right. Those four state colors need separate color values for text and background. however, I'm trying to write a script to automatically pick black/white based on contrast and readability of the color. this way, a red `badge-error` would have a red background and white text (not red text on transparent red background)  
This idea is for daisyUI `v2.0` and I need more research to use the most efficient method.

**Comment by colorninja** [comment]
You should try https://app.contrast-finder.org/. The source code is on GitHub. Bonus points if the ratio is over 4.5 for being WCAG compliant.

Although it would be good if users can still explicitly set the colour when defining themes.

**Comment by pooyaEst** [comment]
not related to this bug but do you have a rough idea of when V2.0 will be released ?
Daisy ui is one of the few Github repositories i frequently check for updates.

**Comment by saadeghi** [comment]
@pooyaEst For version 2.0 colors, I'm trying to find the best structure to have maximum flexibility along with clean markup and efficient file size plus minimum breaking changes. So It's not just adding a few colors. I don't want to release an unthoughtful patch just to quickly fix things. Unfortunately I was super busy in the past weeks but I'll be back very soon.

**Comment by pooyaEst** [comment]
@saadeghi didn't meant just color, i was curios about v2 and what new components might be in it.

**Comment by saadeghi** [comment]
New colors added to daisyUI v2.0:
```
info-content
success-content
warning-content
error-content
```
https://daisyui.com/docs/colors

Changelog: https://daisyui.com/docs/changelog
