### ISSUE TITLE
bug: modal do not show when open attribute is added

### ISSUE THREAD

**Issue by vasilvestre** [saadeghi/daisyui#1871]
### What version of daisyUI are you using?

3.0.0

### Describe your issue

When I use the example given, the modal to not show. It seems to be due to missing .modal[open] css 

### What browsers are you seeing the problem on?

Chrome

### Reproduction URL (optional)

https://stackblitz.com/edit/daisyui-nextjs-t1yfiy?file=pages%2Findex.js

**Comment by vasilvestre** [comment]
This is due to daisy 3.0.0 not being used right now by default on next, don't know why tho. Sorry for the issue

**Comment by dkraczkowski** [comment]
@vasilvestre Hey I have the same issue, what was the solution?

**Comment by saadeghi** [comment]
@dkraczkowski are you using the latest version?

**Comment by vasilvestre** [comment]
> @vasilvestre Hey I have the same issue, what was the solution?

I wasn't on daisyUI 3.0 despite my check. Installing it again worked
