### ISSUE TITLE
Custom colors

### ISSUE THREAD

**Issue by wpea** [saadeghi/daisyui#188]
I have this custom colors for the daisy ui cyberpunk theme, the problem is where does this go in my tailwind.config.js file?

`module.exports = {
  purge: [
     './resources/**/*.blade.php',
     './resources/**/*.js',
     './resources/**/*.vue',
   ],
  darkMode: false, // or 'media' or 'class'
    theme: {
        extend: {    
    },
    },
  
  variants: {
    extend: {},
  },
    plugins: [
      require('daisyui'),
    ],
}
`

```
daisyui: {
    themes: [
      {
        'mytheme': {
          'primary': '#000000',
          'primary-focus': '#212121',
          'primary-content': '#ffffff',
          'secondary': '#000000',
          'secondary-focus': '#242424',
          'secondary-content': '#ffffff',
          'accent': '#1c1c1c',
          'accent-focus': '#000000',
          'accent-content': '#ffffff',
          'neutral': '#3d4451',
          'neutral-focus': '#2a2e37',
          'neutral-content': '#ffffff',
          'base-100': '#ffffff',
          'base-200': '#000000',
          'base-300': '#000000',
          'base-content': '#000000',
          'info': '#000000',
          'success': '#15d192',
          'warning': '#ff9900',
          'error': '#ff5724',
        },
      },
    ],
  },
```

**Comment by saadeghi** [comment]
@wpea See this pages: 
- https://daisyui.com/docs/config  
- https://daisyui.com/core/colors

There are examples for using themes and adding custom themes.

Let me know if you have any questions

**Comment by MentalGear** [comment]
Would it also be possible to only selectively overwrite some colors and keep the rest of the theme ?

**Comment by veado** [comment]
> Would it also be possible to only selectively overwrite some colors and keep the rest of the theme ?

@MentalGear Example to override `primary` color for `dark` theme only. In `tailwind.config.js`: 
```ts
const {
  "[data-theme=dark]": darkTheme,
} = require("daisyui/colors/themes");

const config = {
  content: ["./src/**/*.{html,js,svelte,ts}"],

  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],

  daisyui: {
    themes: [
      {
        dark: {
          ...darkTheme,
          primary: "#2fdcc7",
        },
      },
    ],
  },
};

module.exports = config;

```

**Comment by MentalGear** [comment]
> > Would it also be possible to only selectively overwrite some colors and keep the rest of the theme ?
> 
> @MentalGear Example to override `primary` color for `dark` theme only. In `tailwind.config.js`:
> 
> ```ts
> const {
>   "[data-theme=dark]": darkTheme,
> } = require("daisyui/colors/themes");
> 
> const config = {
>   content: ["./src/**/*.{html,js,svelte,ts}"],
> 
>   theme: {
>     extend: {},
>   },
>   plugins: [require("daisyui")],
> 
>   daisyui: {
>     themes: [
>       {
>         dark: {
>           ...darkTheme,
>           primary: "#2fdcc7",
>         },
>       },
>     ],
>   },
> };
> 
> module.exports = config;
> ```

Smart.
