### ISSUE TITLE
bug: v3 text input and text area, select default focused border color is different

### ISSUE THREAD

**Issue by maslomeister** [saadeghi/daisyui#1880]
### What version of daisyUI are you using?

v3.0.0

### Describe your issue

Not sure what happened, but default color of focused border is different for **text input** and **text area**, **select**

<img width="1045" alt="Screenshot 2023-06-01 at 17 54 48" src="https://github.com/saadeghi/daisyui/assets/64310545/1cf14ea6-846c-4122-be6a-52ca1a3aef08">
<img width="1000" alt="Screenshot 2023-06-01 at 17 56 04" src="https://github.com/saadeghi/daisyui/assets/64310545/636b3b6d-254a-4a17-b002-51b5508e5235">
<img width="973" alt="Screenshot 2023-06-01 at 18 00 45" src="https://github.com/saadeghi/daisyui/assets/64310545/eb4bc6ad-1e8c-426f-ab87-9b3c288ca77b">

### What browsers are you seeing the problem on?

Chrome

**Comment by maslomeister** [comment]
fix merged

**Comment by saadeghi** [comment]
Thank you 🙏
