### ISSUE TITLE
btn-outline not working properly

### ISSUE THREAD

**Issue by RegalOctopus** [saadeghi/daisyui#189]
Hi, I've come across a strange problem.
When I was trying to create a button I noticed that I cannot create a btn-outline style using `@apply` like so:
![Screenshot_2021-09-08-19_447x61](https://user-images.githubusercontent.com/32423204/132462505-5b13cc9c-38a8-4c81-9a15-8f5c46d43aa7.png)
what I expected to happen was that the "green accent" button would behave the same way as "green_accent2"
the codes:
green accent: `green_accent{
        @apply btn btn-outline btn-accent btn-sm;
    }`
green_accent2 : ` <button class="btn btn-outline btn-accent btn-sm">green_accent2</button> `
any help would be appreciated, as I know next to nothing about CSS :slightly_smiling_face:

**Comment by saadeghi** [comment]
@RegalOctopus I wish I could fix this on my end but unfortunately this is how `@apply` works.  
When we use
```
class="btn btn-outline btn-accent btn-sm"
```
styles apply in exact order as defined in plugin source but when we put classes in `@apply`:
```
.mybutton{ @apply btn btn-outline btn-accent btn-sm; }
```
it won't use the correct order.  
I suggest using daisyUI classes directly inside your HTML.  
Yes, one class name is cleaner than 3 class names in HTML but I guess `@apply` won't work as intended in this scenario.

**Comment by Garito** [comment]
And what to do if its is not possible to use dasyui classes inline?
Example: third party components...

**Comment by saadeghi** [comment]
Another [dirty] way is to use `!important`
