### ISSUE TITLE
bug: Modal closes when pressing enter button

### ISSUE THREAD

**Issue by keanesnow98** [saadeghi/daisyui#1893]
### What version of daisyUI are you using?

3.0.0

### Describe your issue

Welcome new 3.0.0 dialog!
In the past, I wrote code myself that closes modal when pressing ESC, but the new 3.0.0 modal is really good to solve this problem.
But I found that this modal also closes when pressing 'Enter'.
I can't find any mention in documentation!

**Comment by saadeghi** [comment]
This is not about daisyUI. That's how `<dialog>` element works.  
If there is `<button>` inside `<form method="dialog">` when you open the modal that button gets focused by default

See this: 
- https://stackoverflow.com/a/61855683
- https://stackoverflow.com/a/76158858
