### ISSUE TITLE
bug: v3 some animations don't appear to be working in ios safari

### ISSUE THREAD

**Issue by johnslemmer** [saadeghi/daisyui#1898]
### What version of daisyUI are you using?

3.0.1

### Describe your issue

A number of animations don't appear to be working in iOS safari with daisy v3.  See video below.  The ones I found:

- button click animation
- loading spinner
- indeterminate progress

The button click animation used to work in v2.  However, the indeterminate progress did not work in v2.  And as the loading spinner is new this version (thanks for that by the way!), there is nothing to compare it to.

https://github.com/saadeghi/daisyui/assets/18610918/716a6275-eed0-480c-afc8-1d31cd33a147

### What browsers are you seeing the problem on?

Safari

**Comment by tansanDOTeth** [comment]
The drawer animation is also broken. Most notabily, the outro animation is gone now.

**Comment by saadeghi** [comment]
> The drawer animation is also broken. Most notabily, the outro animation is gone now.

There's an issue for that already: #1888 

> * button click animation

Button click animation is fixed now on version `3.0.2`

> * indeterminate progress

Here's the issue about indeterminate progress: #1330 I'm working on it.

> * loading spinner

I don't see a problem with spinner animation. Here's a video on both Safari and Safari iOS:

https://github.com/saadeghi/daisyui/assets/7342023/97581270-c4e0-44a3-aa52-7c5923829349

Can you tell me which iOS/Safari version you're using?

**Comment by johnslemmer** [comment]
Strange, the loading spinner is working for me too now. I had recorded that on a iPad simulator on macOS. But today it is working fine. Also checked on an actual iPhone and iPad. Works fine there too. So I would say there is no issue there.

Thanks for fixing the button animation! And sorry to clog up with a duplicate on the other. Should be good to close this issue.

**Comment by blakenz** [comment]
I'm noticing the button click animation on iOS not working when I use daisyUI on my own project, however it works on daisyui.com

**Comment by saadeghi** [comment]
@blakenz please open a new issue with a minimal reproduction link

**Comment by jayjayjayjayjayjay** [comment]
@blakenz Similar issue for me currently. Did you figure out a fix?
