### ISSUE TITLE
bug: v3 Tooltip: `tooltip-open` broken in Firefox and focus-based not working

### ISSUE THREAD

**Issue by Andrew67** [saadeghi/daisyui#1899]
### What version of daisyUI are you using?

v3.0.1

### Describe your issue

Two issues that I believe are related:
- Firefox: `tooltip-open` does nothing
- Firefox/Edge: focusing on the button in the example page doesn't trigger the tooltip

I think this is the root cause: https://github.com/saadeghi/daisyui/commit/6190c84477240dbb780ddf7f4bdc350e7eb2f94f
[Per MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:has), use of `:has()` in Firefox (which doesn't support it) breaks that entire selector chain which includes `.tooltip-open`.
Secondly, I'm thinking `:where()` was intended instead of `:has()`? Since `:has()` is for matching children and `:where()` allows using unsupported selectors like `:focus-visible` might be.

### What browsers are you seeing the problem on?

Firefox, Edge

### Reproduction URL (optional)

https://daisyui.com/components/tooltip/

**Comment by orzarchi** [comment]
Also seems to effect chrome, but only on mobile

**Comment by saadeghi** [comment]
I'm working on it...
