### ISSUE TITLE
Suggestion: Clarify Default Theme usage in docs

### ISSUE THREAD

**Issue by eikaramba** [saadeghi/daisyui#19]
I have a question and a suggestion ;)

1)
For me it is unclear after reading the website whether daisyui is using the base theme by default.

e.g. on https://daisyui.netlify.app/docs/default-themes it just says i need to include `<html data-theme="dark">` to my html, but what if i don't? Do i then use the base colors? I would add this to the docs if that is how it works.

i'm currently trying to integrate it with windicss and it does not work yet, that's why i am confused, i am sure if it would work i would just "see" it. But now that i only have the docs and cannot make it yet work in the code, i would propose this little documentation improvement.

2)
Another hint could be added to the themes config page https://daisyui.netlify.app/docs/config.
Something like
"If it's true, default themes will be included. **If false, you can still define your own custom theme**"

**Comment by saadeghi** [comment]
@eikaramba Hi,  
You're right. I will update the docs with more clear descriptions.  
About WindiCSS: it's currently experimental to use DaisyUI as a plugin for WindiCSS. There's a problem with converting CSS variables and I think it applies to all other Tailwind plug-in that use CSS variables.  
This problem might get fixed soon tho. You can follow this issues for more info:  
https://github.com/windicss/windicss/issues/218  
https://github.com/windicss/windicss/issues/219  
Also https://github.com/saadeghi/daisyui/issues/18

**Comment by saadeghi** [comment]
This color issue seems to be fixed (https://github.com/windicss/windicss/issues/218)  
@eikaramba Can you please update WindiCSS to latest version (2.5.10) and confirm if it works now?

**Comment by eikaramba** [comment]
sure will let you know once https://github.com/windicss/vite-plugin-windicss i updated

**Comment by gunters63** [comment]
I got DaisyUI theming now to work with WindiCSS (and React) by setting the data-them on the html root element (using a patched version of [theme-change]( "theme-change": "github:gunters63/theme-change#5a8a3aaaa300a9a4a19afb8e55617688c618748c") and by importing a copy of the DaisyUI theme CSS file where I deleted the ` "@media (prefers-color-scheme:dark)"` style.

**Comment by eikaramba** [comment]
i can confirm it works now, very good.
