### ISSUE TITLE
bug: table-zebra has stopped working

### ISSUE THREAD

**Issue by tonygustafsson** [saadeghi/daisyui#1900]
### What version of daisyUI are you using?

3.0.1

### Describe your issue

I just upgraded to DiasyUI 3.0.1 (from 2) and `table-zebra` class has stopped working. Inspecting the `<tr>`s and I can see: 

```
.table-zebra tbody tr:nth-child(even) {
    --tw-bg-opacity: 1;
    background-color: hsl(var(--b2) / var(--tw-bg-opacity));
}
```

But the background doesn't look any different. Tried it on default light and dark theme.

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
It works: https://play.tailwindcss.com/KWmiShKN7W

Maybe you're using the same color as a background? If so, add a `bg-base-100` to the table to see the difference.

**Comment by tonygustafsson** [comment]
Aaah, works. Stupid me :)
