### ISSUE TITLE
[translation issue] no translation in /docs/cdn & footer

### ISSUE THREAD

**Issue by sinskiy** [saadeghi/daisyui#1901]
### On which page do you see this issue?

https://daisyui.com/docs/cdn/

### Describe the issue

i found out that there is no translation in all languages for:
"Use daisyUI from CDN
How to use daisyUI from a CDN?"
also no translation for "related projects" in the footer on the main page

**Comment by Sinskiy** [comment]
also in docs/config (Read more about themes)
![image](https://github.com/saadeghi/daisyui/assets/105501997/f65f518d-291a-4dca-bc1e-f7927a6d5d2b)

**Comment by Sinskiy** [comment]
also in docs/themes
![image](https://github.com/saadeghi/daisyui/assets/105501997/a6ceee8a-8f78-4732-83ab-9820408e787b)

**Comment by Sinskiy** [comment]
mostly no translation on this page
https://daisyui.com/docs/layout-and-typography/

**Comment by SameerJS6** [comment]
How can I contribute to this issue? Help

**Comment by saadeghi** [comment]
@SameerJS6 translation files are here:  
https://github.com/saadeghi/daisyui/tree/master/src/docs/src/translation

And here's a guide to contribute:  
https://github.com/saadeghi/daisyui/blob/master/.github/CONTRIBUTING.md

Thank you send let me know if you have any questions
