### ISSUE TITLE
bug: v3 Navbar and Footer are not displayed correctly using Sveltekit

### ISSUE THREAD

**Issue by jaads** [saadeghi/daisyui#1905]
### What version of daisyUI are you using?

v3.0.1

### Describe your issue

After upgrading to v3 the navbar and the footer components stopped working correctly. Here's a screenshot of the [Navbar with menu and submenu](https://daisyui.com/components/navbar/#navbar-with-menu-and-submenu) which I copied from the docs in my project.
![Screenshot 2023-06-03 at 18-18-07 Jan Arends](https://github.com/saadeghi/daisyui/assets/34009329/3000f8ba-71e8-458c-859c-fcf603385d5d)

Or here the [footer with the logo section](https://daisyui.com/components/footer/#footer-with-a-logo-section) from the documentation:
![Screenshot 2023-06-03 at 18-18-22 Jan Arends](https://github.com/saadeghi/daisyui/assets/34009329/7482ba22-72ff-4e49-abe8-ee26fad7a924).

Other components I checked so far are working just fine.

To check if some of my custom CSS doesn't interfere with DaisyUI, I deleted all of it the custom CSS temporarily but without success. The Navbar and Footer were looking the same. It doesn't make a difference if I use dev mode or the preview of the build. I tried to compare my configs with the [sveltekit stackblitz one](https://stackblitz.com/edit/daisyui-sveltekit/) but this projects is not yet upgrade to v3. Any other ideas?

**Comment by saadeghi** [comment]
It's probably a problem with your `tailwind.config.js`  
Make sure the path to all your template files (any file that you have class names inside it) is addressed in `content`  
https://tailwindcss.com/docs/content-configuration


Also make sure you're using the class names as a whole string (not half-variable):  
https://tailwindcss.com/docs/content-configuration#dynamic-class-names

Let me know if these didn't fix the issue.

**Comment by jaads** [comment]
we were absolutely right 👍
