### ISSUE TITLE
bug: menu active item broken on hover on "light" theme

### ISSUE THREAD

**Issue by Aragur** [saadeghi/daisyui#1907]
### What version of daisyUI are you using?

v3.0.2

### Describe your issue

Menu active item on hover seems to be broken on the default “light” theme (See screenshot attached below).
Furthermore, I think that this black color is very intrusive on the other dark themes, it is looking more neutral.

<img width="725" alt="Screenshot 2023-06-03 at 23 31 51" src="https://github.com/saadeghi/daisyui/assets/11004008/b96ad10f-5217-4f0b-9eeb-ae7bfc9d1f2a">

### What browsers are you seeing the problem on?

Chrome, Safari, Firefox, Other

### Reproduction URL (optional)

https://daisyui.com/components/menu/#menu-with-active-item

**Comment by NikarashiHatsu** [comment]
Apparently, this issue applies to all of the theme.
I used the `emerald` theme, and it's the same.

<img width="289" alt="Screenshot 2023-06-04 at 12 50 45" src="https://github.com/saadeghi/daisyui/assets/43662951/9b08d7c3-0e98-406f-b8b6-3d57be4d9671">

Temporary workaround is using the class explicitly such as `bg-primary`
<img width="281" alt="Screenshot 2023-06-04 at 12 52 29" src="https://github.com/saadeghi/daisyui/assets/43662951/26d85179-862e-4d66-af82-3c83847fae47">

But yea, the hover state is still bugged
<img width="294" alt="Screenshot 2023-06-04 at 12 52 56" src="https://github.com/saadeghi/daisyui/assets/43662951/b69a5421-6ff9-4f5e-8fdf-d8fe1c338fb1">
