### ISSUE TITLE
Change collapse height

### ISSUE THREAD

**Issue by DanDev95** [saadeghi/daisyui#191]
Is there any way to change the closed collapse height?

**Comment by saadeghi** [comment]
Currently the only way is some custom CSS  
You can see the current style here: https://github.com/saadeghi/daisyui/blob/master/src/components/styled/collapse.css

Please let me know if you have any questions

**Comment by arvigeus** [comment]
A hack-around would be to force min-height like this:

```html
    <div className="collapse">
      <input type="checkbox" className="!min-h-fit p-1" tabIndex={0} />
      <div className="collapse-title !min-h-fit p-1">Files</div>
      <div className="collapse-content">
        <FileTreeView />
      </div>
    </div>
```

`!min-h-fit` was added to `input` and `.collapse-title` elements. This won't work if you use arrow/plus. @saadeghi wouldn't that be a better solution than hardcoding `min-height`? The arrow/plus element could be tricky, but it can be left to the user to implement.

**Comment by saadeghi** [comment]
There are new updates since version `2.26.0` that makes everything easier.  
See this: https://github.com/saadeghi/daisyui/discussions/1110#discussioncomment-3616445
