### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by JTorresConsulta** [saadeghi/daisyui#1916]
### What version of daisyUI are you using?

3.0.1

### Describe your issue

Loading icons and animations are not showing 

<a href="https://ibb.co/D8TTX4H"><img src="https://i.ibb.co/TbddXcx/loading-not.png" alt="loading-not" border="0"></a>

### What browsers are you seeing the problem on?

Chrome

### Reproduction URL (optional)

https://stackblitz.com/edit/daisyui-cdn-3mjkuy/?file=index.html

**Comment by dodo1708** [comment]
Had a similar issue, but I'm using 3.0.3. Had to add autoprefixer as the css props mask-* are not available in chromium based browsers.

**Comment by ryankashi** [comment]
Tried this inside of my Electron app. Same issue. All instances of -mask-image or whatever it's called need to be replaced with webkit-mask-image.

Making this change makes things work properly

**Comment by saadeghi** [comment]
Fixed in 3.0.4

**Comment by ldevai** [comment]
Seems like this same issue resurfaced at some point, I am having the exact same problem with 4+ (4.5.0)
I see mask-images browsing Chrome and my images don't get loaded. Works as expected in safari.

"devDependencies": {
    "daisyui": "^4.5.0",
    "autoprefixer": "^10.4.16",
    "postcss": "^8.4.33",
    "react-daisyui": "^5.0.0",
    "tailwindcss": "^3.4.1"
  },
