### ISSUE TITLE
bug: Menu will not allow text to break

### ISSUE THREAD

**Issue by benhchoi** [saadeghi/daisyui#1924]
### What version of daisyUI are you using?

v3.0.3

### Describe your issue

I expect menu items to respect word breaks, but they don't. Instead, menu items will always overflow. This used to work before the upgrade from v2 to v3 (words would break according to `break-normal` by default without the need to even include the class, which in my opinion seems like the most logical default).

### What browsers are you seeing the problem on?

Chrome

### Reproduction URL (optional)

https://play.tailwindcss.com/TdBkm1eFoU

**Comment by benhchoi** [comment]
Gotcha, thanks for clarifying!

**Comment by ddadaal** [comment]
But neither approaches (auto-cols-auto and flex) doesn't work for submenus.

https://play.tailwindcss.com/Sy4pCzcY2y
