### ISSUE TITLE
bug: background-color and position: sticky don't mix well with `modal` class

### ISSUE THREAD

**Issue by adamsmietanka** [saadeghi/daisyui#1925]
### What version of daisyUI are you using?

3.0.3

### Describe your issue

The button div at the bottom has `sticky bg-base-100` and I've added a `duration-1000` to the modal for clarity. Adding `background-transparent` resolves the color changing issues but unfortunately removes the background dim. Also works well when `sticky` is removed

https://github.com/saadeghi/daisyui/assets/42046760/b2dbfafb-7e71-4f13-aa76-c5a3205502a4

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by saadeghi** [comment]
Is this the new `<dialog>` element?  
https://daisyui.com/components/modal/#dialog-modal
