### ISSUE TITLE
how to toggle to RTL when language switched ?

### ISSUE THREAD

**Issue by morteza-mortezai** [saadeghi/daisyui#193]
i trying to change Direction to RTL when language switched to RTL one , 
i set Direction attribute to RTL when language switched but components mess up ,
how can it be done correctly ?

**Comment by saadeghi** [comment]
@morteza-mortezai set [rtl config](https://daisyui.com/docs/config) to true and then add `dir="rtl` to body.

**Comment by SaeedSheikhi** [comment]
Hey @saadeghi 

Any idea to Change Direction on production mode? rather than pre-production and one-time config setup that mentioned in docs

Thanks in advance.

**Comment by saadeghi** [comment]
@SaeedSheikhi 
The RTL direction classes are generated at build time so if you want to switch it on production, I would suggest building 2 CSS files. One for RTL and one for LTR.  

Also, this is the reason why CSS is generated at build time only for one direction:
https://github.com/MohammadYounes/rtlcss/issues/164#issuecomment-601678221
