### ISSUE TITLE
bug: Progress intermediate not working on Safari

### ISSUE THREAD

**Issue by sheunglaili** [saadeghi/daisyui#1931]
### What version of daisyUI are you using?

v3.0.3

### Describe your issue

Progress intermediate have no animation on Safari 

https://daisyui.com/components/progress/

### What browsers are you seeing the problem on?

Safari

### Reproduction URL (optional)

https://daisyui.com/components/progress/

**Comment by saadeghi** [comment]
Fixed in `3.0.6`
