### ISSUE TITLE
bug: No utility classes were detected in your source files.

### ISSUE THREAD

**Issue by Jarvie789** [saadeghi/daisyui#1932]
### What version of daisyUI are you using?

v3.0.3

### Describe your issue

Although it works fine, there is always a warn in... If I add any of the classes from tailwindcss it works perfectly fine without any errors. How to shield this warn, thanks in advance!
My development environment: daisyui, electron, react, webpack, tailwindcss, postcss, postcss-loader.

The same goes for the official example.
https://stackblitz.com/edit/daisyui-react-webpack/

### What browsers are you seeing the problem on?

Chrome, Other

### Reproduction URL (optional)

https://stackblitz.com/edit/daisyui-react-webpack/

**Comment by saadeghi** [comment]
This is not a bug and it's not an error. 

That warning is from Tailwind itself and I can't do anything about it. But it's not an error. It's just a warning and it's supposed to warn you when you didn't use any utility class. If you don't want to use them, you can safely ignore the warning.

...But are you really not using *any* utility class in your project? Not even a `flex` or a margin or something?
