### ISSUE TITLE
bug: doesn't upload styles for custom component

### ISSUE THREAD

**Issue by Kiborgik** [saadeghi/daisyui#1936]
### What version of daisyUI are you using?

3.0.3

### Describe your issue

Im using Next.js 13.4.5
When Im using the component like:
`<Button
            label='Sign Out'
            size='small'
            backgroundColor='success'
            onClick={() => signOut()}
          />` where `btn-${backgroundColor}` It create the element `<button type="button" class="btn-success font-bold uppercase btn-xs rounded mb-1 mr-1">Sign Out</button>` but this class is not exist, only when Im adding the normal button with the same class on this page the color will apply to both buttons. 

### What browsers are you seeing the problem on?

Chrome

**Comment by Kiborgik** [comment]
P.S. if I adding class `btn-success` to any element on page it will apply to my button component

**Comment by saadeghi** [comment]
In a Tailwind project, you shouldn't use dynamic class names otherwise how can you expect Tailwind to find the class name in your source files?

Read this: https://tailwindcss.com/docs/content-configuration#dynamic-class-names

**Comment by Kiborgik** [comment]
@saadeghi Thank you, I changed to use
`const ButtonColor = {
    primary: 'btn-primary',
    secondary: 'btn-secondary',
    neutral: 'btn-neutral',
    accent: 'btn-accent',
    ghost: 'btn-ghost',
    link: 'btn-link',
    info: 'btn-info',
    success: 'btn-success',
    warning: 'btn-warning',
    error: 'btn-error',
  }  and ${ButtonColor[backgroundColor]} ` and it works now, also `import 'daisyui/dist/full.css'` was a solution but with your help it works without including everything :)
