### ISSUE TITLE
'Colors' page in docs does not update color codes in UI based on theme change

### ISSUE THREAD

**Issue by aviditi-will** [saadeghi/daisyui#194]
### Steps to Recreate:

1. Go to [the 'Colors' page in the Docs](https://daisyui.com/core/colors)
2. Update the selected theme in the top right corner ("Change Theme")
3. View the color pallet on the 'Customize' tab

### Expected Behavior:

- The colors update visually
- The color codes displayed correspond with the theme selected
- The color pickers have the correct 

### Current Behavior:

- The colors update visually
- The color codes displayed correspond with the 'light' theme regardless of the theme selected
- The color pickers have the incorrect color selected

<img width="1397" alt="Screen Shot 2021-09-12 at 1 32 11 PM" src="https://user-images.githubusercontent.com/75289494/132997166-d3b03c81-18bf-4f3f-b55a-bb3e673d2604.png">
color selected

**Comment by Aravin** [comment]
Yes, I also noticed this bug.

**Comment by saadeghi** [comment]
For now, you can use this theme generator which has a better implementation than mine: https://themes.ionevolve.com/
