### ISSUE TITLE
bug: Detail/Summary in Navbar is not working

### ISSUE THREAD

**Issue by ryoppippi** [saadeghi/daisyui#1941]
### What version of daisyUI are you using?

v3.0.4

### Describe your issue

I try to use the Navbar with menu, but the style doesn't look as the documentation page.
Here is the demo environment

https://stackblitz.com/edit/daisyui-sveltekit-vhupzp/?file=src/routes/+layout.svelte

**Comment by saadeghi** [comment]
This Stackblitz link is using version `2.51.5`. If you install version 3 `npm i -D daisyui@latest` it will be fixed.  

I'm updating the Stackblitz examples to the latest version one by one (daisyUI and all other dependencies) but it takes time to be honest.

**Comment by ryoppippi** [comment]
Thanks! it works!!
