### ISSUE TITLE
bug: theme is not applied

### ISSUE THREAD

**Issue by ryoppippi** [saadeghi/daisyui#1942]
### What version of daisyUI are you using?

3.0.4

### Describe your issue

Hi!
I set the `cupcake` theme at app.html but it does not work

https://stackblitz.com/edit/daisyui-sveltekit-vhupzp/?file=src/app.html,src/routes/+layout.svelte,src/app.css

### What browsers are you seeing the problem on?

Chrome, Safari, Firefox, Edge

**Comment by ryoppippi** [comment]
I found that `light` theme can be applied

**Comment by ryoppippi** [comment]
OK I found that we need to add themes to tailwind.config.js
Thanks

**Comment by saadeghi** [comment]
Starting with version 3 `light` and `dark` themes are enabled by default but you can enable more themes from the config: 
Changelog: https://daisyui.com/docs/changelog/#theme-improvements

**Comment by ryoppippi** [comment]
Thanks! I need to read changelog to migrate
