### ISSUE TITLE
bug: component tabs

### ISSUE THREAD

**Issue by savionascimentodev** [saadeghi/daisyui#1944]
### What version of daisyUI are you using?

v2.52.0

### Describe your issue

Tabs component is not doing its default behavior of changing the tab

Note: I'm using an old version because of a specific lib, but in the current version on the website, it's not working either

### What browsers are you seeing the problem on?

Chrome

### Reproduction URL (optional)

https://daisyui.com/components/tab/

**Comment by ahmad1702** [comment]
From what I understand this is on purpose. For the tabs component Daisyui is offering the styling not the behavior to make it versatile, so it is up to you once you consume the library to decide how you want to implement it.

**Comment by saadeghi** [comment]
> Daisyui is offering the styling not the behavior

Yes. daisyUI is just CSS.  

You can use tabs for anything. It can be external link, it can change a part of page, it can run a JS function. daisyUI provides the style but you can control the behavior yourself.
