### ISSUE TITLE
bug: Card overlaps dropdown

### ISSUE THREAD

**Issue by paultuckey** [saadeghi/daisyui#1948]
### What version of daisyUI are you using?

3.0.3

### Describe your issue

When a card is next to an open dropdown the card will be in front of the dropdown. In previous versions this was not the case.

<img width="473" alt="image" src="https://github.com/saadeghi/daisyui/assets/1170968/65c989ce-5064-4000-be16-1958c196535f">

Thanks for daisyui BTW, love it 🥇!

### What browsers are you seeing the problem on?

Chrome

### Reproduction URL (optional)

https://play.tailwindcss.com/R0M0FQuMLB

**Comment by saadeghi** [comment]
[Starting with version `3.0`](https://daisyui.com/docs/changelog/#breaking-changes) `dropdown` doesn’t have a `z-index` by default  
>Using `z-index` for `dropdown` as a default style was a mistake because sometimes we need elements on top of th dropdown and sometimes we want the dropdown to be on top of other elements. Now you can use `z-[1]` or any other z-index class to control it as you want.

https://tailwindcss.com/docs/z-index
