### ISSUE TITLE
bug: Mobile browsers problems

### ISSUE THREAD

**Issue by JTorresConsulta** [saadeghi/daisyui#1956]
### What version of daisyUI are you using?

3.0.20

### Describe your issue

1- Modal: not open on **iOs mobile browsers**
2- Online indicator: show a background square on **iOs and Android browsers**
3- Swap: show checkbox on **iOs browsers**
 
<img src="https://i.ibb.co/YbF9g2Z/photo-2023-06-08-14-14-39.jpg" alt="photo-2023-06-08-14-14-39" border="0">

Other thing: How to trigger the drowdown close? For example, clicking in the button that opened.

Thanks.

### What browsers are you seeing the problem on?

All browsers

### Reproduction URL (optional)

https://codepen.io/JTorresConsulta/pen/dyQPXZo

**Comment by saadeghi** [comment]
I opened your Codepen Link on iOS and I can't see the issues:  
<img width="533" alt="Screenshot 2023-06-21 at 01 32 50" src="https://github.com/saadeghi/daisyui/assets/7342023/4cd252a9-d9b2-43c1-ba4e-b338680d9cb1">


What iOS version are you using?

**Comment by JTorresConsulta** [comment]
![D72B9301-D9ED-4C24-BDE7-9FF2A048F958](https://github.com/saadeghi/daisyui/assets/22349981/a19ffcf6-888b-4fa9-835c-843579149d89)

**Comment by Keshavdulal** [comment]
I can confirm the same issue on `daisyui:3.1.1` across multiple ios mobile devices on Safari & Chrome.
Not on iPad though.
Not on Desktop Safari or Chrome either.
Not on Desktop Safari and Chrome's Mobile view either.

I am using a Modal Component to signin/up and people see the following on their iPhones.
This makes it very hard to debug/fix.

**Comment by zuzy-dev** [comment]
`<dialog>`-element is not supported in iOS 14:
https://www.lambdatest.com/web-technologies/dialog-support-on-safari-14

Refactor code to 
https://daisyui.com/components/modal/#method-2-using-a-hidden-checkbox-legacy
or
https://daisyui.com/components/modal/#method-2-using-a-hidden-checkbox-legacy
