### ISSUE TITLE
drawer is not in correct position when direction is RTL

### ISSUE THREAD

**Issue by morteza-mortezai** [saadeghi/daisyui#196]
when toggling to RTL , the drawer is not in its correct position .
as you see in below picture , i switched to RTL direction and drawer is not shown correct.
![image](https://user-images.githubusercontent.com/75200938/133042543-95c0b369-754d-4a03-ad2e-6809cfaa3926.png)

**Comment by sakkelaaksonen-siili** [comment]
Looking for a solution to this.

**Comment by morteza-mortezai** [comment]
is this bug fixed ?

**Comment by saadeghi** [comment]
@morteza-mortezai Yes. update to latest version (`1.14.1`)
