### ISSUE TITLE
bug: modal-box not working when wrapped in tailwind breakpoint range

### ISSUE THREAD

**Issue by claysam75** [saadeghi/daisyui#1963]
### What version of daisyUI are you using?

3.0.22

### Describe your issue

The modal-box class does not seem to be playing nicely with tailwind responsive breakpoints. 

This is my react component, which switches between displaying as a card or a modal depending on the screen size. On sm-lg screens it will be a modal and above that it will be a card. 

```
import React from "react";

const ModalOrCard = ({ children }) => {
    return (
        <>
            <input
                type="checkbox"
                checked
                id="modalExt"
                className="modal-toggle"
            />
            <div className="xs:max-lg:modal xs:max-lg:modal-bottom lg:mx-2 lg:w-full lg:bg-base-100 lg:shadow-xl lg:card">
                <div className="xs:max-lg:modal-box lg:card-body">
                    {children}
                </div>
            </div>
        </>
    );
};

export default ModalOrCard;

```

Almost all of it works except for the modal-box class. If I remove modal-box from the breakpoint range wrapper then it applies correctly. See the screenshots below for how the component appears in each scenario.

https://imgur.com/a/uq7psKZ

### What browsers are you seeing the problem on?

Chrome

![Screenshot 2023-06-09 150210](https://github.com/saadeghi/daisyui/assets/65623622/ab017270-2334-41ff-8b26-d201074ec4f5)
![Screenshot 2023-06-09 150157](https://github.com/saadeghi/daisyui/assets/65623622/5d66e270-eed0-4556-963c-030e3373552b)

**Comment by saadeghi** [comment]
You're applying responsive prefixes to class names that are not responsive.

As you can see here only `modal-top`, `modal-bottom`, `modal-middle` are responsive. And generally it's not a good idea to change the whole component to something else (converting a modal to a card?) based on screen size.

The original selector to style the `.modal-box` inside `.modal-bottom` is:
```
.modal-bottom :where(.modal-box){}
```
so none of the `modal-box` styles work this way when you add a prefix.

If you really have to do this, you can add these styles to re-apply the needed class names: 
```
max-lg:w-full max-lg:scale-100 max-lg:rounded-b-none max-lg:max-w-none
```
https://play.tailwindcss.com/GFgm9lOW4M
