### ISSUE TITLE
bug: nested collapse arrow icon state is influenced by ancestor collapse-open

### ISSUE THREAD

**Issue by bmcbarron** [saadeghi/daisyui#1966]
### What version of daisyUI are you using?

3.0.20

### Describe your issue

The css rule that affects the appearance of the arrow icon (up or down) looks like this:

.collapse-open.collapse-arrow .collapse-title:after, ... {
  // Show as open
}

However, you nest collapse entries, and the parent has collapse-open set, then this rule applies to all descendant collapse arrows. Note that the nested collapse still works correctly, it's just that the arrow is always shown as "open", even when it's closed.

### What browsers are you seeing the problem on?

Chrome

**Comment by ktecho** [comment]
Related with this:

https://play.tailwindcss.com/lvAd5H5DFP

As you can see, when the outer `collapse` is `collapse-open`, the collapses on the inside are opened by default.

This is while using latest DaisyUI (v3.4.0), but also happened with v2.
