### ISSUE TITLE
docs: Website unavailable

### ISSUE THREAD

**Issue by JuliusGudni** [saadeghi/daisyui#1969]
### On which page do you see this issue?

https://daisyui.com

### Describe the issue

 I'm getting this error message when trying to access daisyui.com: "Site not found - There isn't a GitHub Pages site here."

### What browsers are you seeing the problem on?

All browsers

**Comment by bineetNaidu** [comment]
yes the site is unavailable

**Comment by saadeghi** [comment]
Is it available now?

Probably it was getting deployed that second.

**Comment by egemadra** [comment]
Still unavailable.
