### ISSUE TITLE
bug: 'table-pin-rows' is not present

### ISSUE THREAD

**Issue by TheOnlyWayUp** [saadeghi/daisyui#1973]
### What version of daisyUI are you using?

3.0.25

### Describe your issue

I pasted the [example](https://daisyui.com/components/table/#table-with-pinned-rows) from the documentation exactly on a Fresh Install of DaisyUI (v3.0.25) and TailwindCSS (v3.3.2).

There doesn't seem to be a class with the name `table-pin-rows` in DaisyUI. Using it doesn't apply any styling to my table.

It's present in the documentation for the version I'm using, is this implemented yet?

Thanks, awesome work!

**Comment by saadeghi** [comment]
By default, table has no width or height limit and if the table content will fit the available space. (This is the default HTML bahaviour, not a daisyUI design decision)

But if you set a width or height, you can see the sticky rows or column.

See this example: https://play.tailwindcss.com/5bvndLAknD
