### ISSUE TITLE
bug: Drawer transition is wrong in RTL

### ISSUE THREAD

**Issue by CripyIce** [saadeghi/daisyui#1974]
### What version of daisyUI are you using?

3.0.25

### Describe your issue

When using `drawer` component in RTL layout, the entering transition is wrong and there is no transition at all on exit.
Just use the example code from the website https://daisyui.com/components/drawer/#responsive while setting dir="rtl" to your html tag and applying the following config:
`daisyui: {
    rtl: true,
  }`

**Comment by ariaieboy** [comment]
https://play.tailwindcss.com/YPqWPLZjsW

**Comment by CripyIce** [comment]
@ariaieboy Exactly.

**Comment by lbensaad** [comment]
the bug disappears and works correctly if you remove ```daisyui: { rtl: true, }``` and keep ```<html dir="rtl">```

**Comment by HJassar** [comment]
You can add these lines to `app.postcss` for a decent result (i.e. the drawer closes abruptly, I couldn't figure this one out).

```
[dir='rtl'] .drawer-toggle ~ .drawer-side {
	@apply -translate-x-[100%];
}

[dir='rtl'] .drawer-toggle:checked ~ .drawer-side {
	@apply translate-x-0;
}

[dir='rtl'] .drawer-side > *:not(.drawer-overlay) {
	@apply translate-x-[100%];
}
```
