### ISSUE TITLE
bug: Website domain downed.

### ISSUE THREAD

**Issue by mhmtbsrglu** [saadeghi/daisyui#1977]
### Describe your issue

Hi,
Daisyui's website is down. I don't know why it is down, but I cannot access anything.
![image](https://github.com/saadeghi/daisyui/assets/99546413/0978ed7c-760d-4986-8de1-c91f10254705)

### What browsers are you seeing the problem on?

All browsers

**Comment by saadeghi** [comment]
Fixed.
