### ISSUE TITLE
bug: A button inside a modal closes the modal on click

### ISSUE THREAD

**Issue by LastxTemplar** [saadeghi/daisyui#1986]
### What version of daisyUI are you using?

v 3.0.22

### Describe your issue

Any button inside a modal will close the modal. The expected behaviour is for the modal to not close.
I know that this behaviour is mentioned in the docs, but why is it this way? I need to have multiple button inside the modal.

**Comment by saadeghi** [comment]
This is not about daisyUI. It's how `<dialog>` element works.  
Only the button inside `<form method="dialog">` closes the modal.  
You can use a `<div>` for `modal-box` instead of `<form>` and put the `<form method="dialog">` and its button inside it. Then you can add more buttons outside of the form:  
https://play.tailwindcss.com/LqicNR5OMg
```html
<!-- Open the modal using ID.showModal() method -->
<button class="btn" onclick="my_modal_1.showModal()">open modal</button>
<dialog id="my_modal_1" class="modal">
  <div class="modal-box">
    <h3 class="font-bold text-lg">Hello!</h3>
    <p class="py-4">Press ESC key or click the button below to close</p>
    <div class="modal-action">
      <!-- if there is a button in form, it will close the modal -->
      <form method="dialog">
        <button class="btn">Close</button>
      </form>
      <button class="btn">Does nothing</button>
    </div>
  </div>
</dialog>
```

**Comment by LastxTemplar** [comment]
ok, thanks for the solution :)

**Comment by CaffeinatedTech** [comment]
It would be good to update the examples in the documentation to use the above format.  I see several issues with essentially the same resolution.

**Comment by nanaknketsiah** [comment]
With this method, modal does not just close but reloads the entire app

**Comment by saadeghi** [comment]
@CaffeinatedTech Done ✅
