### ISSUE TITLE
Styling divider with utility classes?

### ISSUE THREAD

**Issue by nino-w4u** [saadeghi/daisyui#199]
is there a utility class that allows me to style the divider? (color, thickness, etc..) ?

Or is the only way to add some css targeting the divider element?

**Comment by saadeghi** [comment]
@nino-w4u divider is using `:before` and `:after`:
https://github.com/saadeghi/daisyui/blob/master/src/components/styled/divider.css  
If you're using Tailwind's [`jit` mode](https://tailwindcss.com/docs/just-in-time-mode), you can use utility classes to style them.
