### ISSUE TITLE
bug: issues with collapse & docs

### ISSUE THREAD

**Issue by megagames-me** [saadeghi/daisyui#1992]
### What version of daisyUI are you using?

v3.1.0

### Describe your issue

There seem to be multiple problems with the collapse component.

## Animation on collapse with custom background

When a custom background is applied to a collapse component, the border radius becomes messed up on the bottom area when it is transitioning to the collapsed state. This is also shown in the documentation but I have provided a simplified version of it.

## Text doesn't animate out properly

When closing any collapse components, the text disappears straight away instead of animating out. Collapse always has seemed to be rough and broken but I think fixing this would make it much smoother.

## `collapse-title` isn't vertically aligned sometimes

If the font size of `collapse-title` is too small, the text is too high up in the `collapse-title` container. This could be fixed with flexbox or vertical-align. Flexbox breaks in the animation, though, and vertical-align doesn't work properly with text that is big enough to fit. I'll see if I can fix it, though.

## Documentation inconsistency

For [this part of the documentation](https://daisyui.com/components/collapse/#custom-colors-for-collapse-that-works-with-checkbox), it says to use "Tailwind CSS `peer` and `peer-checked` utilities to apply style when sibling checkbox is checked" but the example doesn't use `peer-checked`. This should be an easy fix I think.

<hr />

I'd like to fix these issues myself if possible but I'd just like to document this if anyone has any ideas.

### What browsers are you seeing the problem on?

Chrome

### Reproduction URL (optional)

https://play.tailwindcss.com/hh0gQWQsir

**Comment by saadeghi** [comment]
Quote from https://github.com/saadeghi/daisyui/pull/1993#issuecomment-1600392172
>It could be that the main issue was specific to my system because this example is quite broken for me. Removing the invisible class fixed most of the issues with it. If this doesn't work, I'm not sure how to fix it because the behavior with animating grid-template seems kind of broken as the top row stretches out a bit when animating. When animating out (this animation going out is created by removing the invisible class, I'm not sure whether it would break anything though) without the translate, there was some sort of flicker because of the weird grid-template animation behavior.

@megagames-me can you please share a video of the broken animation so I can see the issue?
