### ISSUE TITLE
bug: Navigation contains dropdown item not working with drawer

### ISSUE THREAD

**Issue by iozcelik** [saadeghi/daisyui#1994]
### What version of daisyUI are you using?

v3.1.0

### Describe your issue

When I try to add a navigation menu which contains dropdown item, then add to carousel. However dropdown items are going backward and not visible.

### What browsers are you seeing the problem on?

Chrome, Edge

### Reproduction URL (optional)

https://play.tailwindcss.com/1aE7QM355V

**Comment by saadeghi** [comment]
Add a z-index to `menu`:  
https://play.tailwindcss.com/tMmJuNrZms
