### ISSUE TITLE
Add icon button

### ISSUE THREAD

**Issue by DanDev95** [saadeghi/daisyui#200]
A nice new addition to the buttons would be an icon button that takes things like svg as its children, where it has the same animation as the other buttons, but doesn't have any surrounding box, . Something like the link button.

**Comment by saadeghi** [comment]
@DanDev95 You can do this using `btn btn-square btn-ghost`. example:  
https://play.tailwindcss.com/6byb93sBOe

Please let me know if you have any questions.

**Comment by DanDev95** [comment]
> @DanDev95 You can do this using `btn btn-square btn-ghost`. example:  
> 
> https://play.tailwindcss.com/6byb93sBOe
> 
> 
> 
> Please let me know if you have any questions.

No because that still got the button box around the icon.

**Comment by saadeghi** [comment]
@DanDev95 How about [this](https://play.tailwindcss.com/5yOMOMT97G)?

**Comment by DanDev95** [comment]
> @DanDev95 How about [this](https://play.tailwindcss.com/5yOMOMT97G)?

I've used the link button but it's too wide and tall so I can't stack multiple icon buttons close to each other.

**Comment by saadeghi** [comment]
@DanDev95 I'm not sure about your layout but [here's an example](https://play.tailwindcss.com/R97V1bsGCb) with icons close to each other 🤷‍♂️
