### ISSUE TITLE
bug: lg:drawer-open not working on laptop/desktop

### ISSUE THREAD

**Issue by oauter** [saadeghi/daisyui#2000]
### What version of daisyUI are you using?

v3.1.0

### Describe your issue

The responsive drawer HTML code does not work, when I cut and past it from https://daisyui.com/components/drawer/#responsive into a new/empty html file. Specifically the **lg:drawer-open** class does not display the navbar on a large screen like it should, if I just type in **drawer-open** and leave off the **lg**  modifier it displays as it should on a large screen.

### What browsers are you seeing the problem on?

Chrome, Edge

### Reproduction URL (optional)

https://stackblitz.com/edit/web-platform-ufspcw?file=index.html

**Comment by bosichong** [comment]
Me too...

**Comment by nilskretschmer** [comment]
I can confirm this issue

**Comment by nilskretschmer** [comment]
Still present in v3.1.1 - Returned to v2.x for now using the deprecated drawer-mobile class.

**Comment by saadeghi** [comment]
This was a issue on CDN file. Now fixed in version `3.1.2`

**Comment by jamesclavel** [comment]
lg:drawer-open stays collapsed in Firefox `145.0 (aarch64)` desktop for 
DaisyUI version `"daisyui": "^5.5.5"`

**Comment by pdanpdan** [comment]
You mean in this example: https://play.tailwindcss.com/4AybsPcml1
the drawer thin bar on the left is not visible on large screens, and this happens specifically only on firefox (aarch64)?
Because in firefox (x86) it works as expected

**Comment by Oberonc** [comment]
It doesnt work in Codepen (Firefox 140.7.0esr) ([Example](https://codepen.io/Oberonc/pen/NPbNvpM?editors=1000))
[Works](https://play.tailwindcss.com/4AybsPcml1) in Tailwind play.

**Same** code basically, why is that ?

**Comment by pdanpdan** [comment]
Check docs
https://daisyui.com/docs/cdn/

daisyUI variant class names like is-drawer-open and is-drawer-close are not included in the CDN files because adding them for all class names will result in a very large file size

**Comment by Oberonc** [comment]
> Check docs https://daisyui.com/docs/cdn/
> 
> daisyUI variant class names like is-drawer-open and is-drawer-close are not included in the CDN files because adding them for all class names will result in a very large file size

Didnt notice that.
Thanks for the swift reply
