### ISSUE TITLE
bug: Menu hierarchy in v3.1.1

### ISSUE THREAD

**Issue by s-montigny-desautels** [saadeghi/daisyui#2008]
### What version of daisyUI are you using?

v3.1.1

### Describe your issue

Hi!

The menu hierarchy is not working anymore on version 3.1.1

Image taken from the changelog:
![image](https://github.com/saadeghi/daisyui/assets/84924528/e25df495-88b8-462b-9f6f-f61bdb6c8a36)

Image taken from the doc on 3.1.1:

![image](https://github.com/saadeghi/daisyui/assets/84924528/331b5a29-8b8e-4ee4-ad9b-4fd10fe0f227)
![image](https://github.com/saadeghi/daisyui/assets/84924528/f97f1a73-ac13-4c0d-8980-5af58a3db573)

### What browsers are you seeing the problem on?

Chrome

**Comment by bayasdev** [comment]
same

**Comment by saadeghi** [comment]
Thanks for reporting. I will fix this soon.
