### ISSUE TITLE
Dropdown Force Close

### ISSUE THREAD

**Issue by christianblandford** [saadeghi/daisyui#201]
It doesn't seem like there's a way to force close a dropdown. I'm using a dropdown in my navbar to allow users to navigate to their profile or settings page. When the dropdown menu item is clicked, the app navigates and leaves the dropdown open.

Also, I wish there was a way to tell the dropdown to close if the button is clicked and the dropdown is already open. I guess you could call this toggling.

**Comment by christianblandford** [comment]
Here's a quick hack in React to get it working in a pinch if anyone else has this problem:

`const [menuOpen, setMenuOpen] = useState(false)`

`<button className="btn btn-sm btn-square btn-ghost" onClick={() => setMenuOpen(!menuOpen)}>
          <DotsHorizontalIcon className="h-5 w-5 text-base-content dark:text-gray-100" />
        </button>

        {menuOpen && (
          <div class="dropdown dropdown-end dropdown-open">
            <ul
              tabindex="0"
              class="mt-4 p-2 shadow menu dropdown-content bg-base-100 rounded-box w-52"
            >
              <li>
                <Link to="/settings" onClick={() => setMenuOpen(false)}>
                  Settings
                </Link>
              </li>
            </ul>
          </div>
        )}`

**Comment by saadeghi** [comment]
@christianblandford daisyUI modal uses `:focus` to show/hide the dropdown. When content is focused, the dropdown stays open. when it loses the focus, dropdown gets closed.  
To close the dropdown on a SPA when a link is clicked (you want to change page content but dropdown is still focused), you can use Javascript to remove the focus: https://play.tailwindcss.com/sLI0mVhaZ3

**Comment by allaghi** [comment]
you can use document.activeElement.blur() in watch route if you want to

**Comment by BryonVerdone** [comment]
I'm using NextJs and the document.activeElement.blur() fix works locally but I get an error saying 'document is not defined'

**Comment by brianshano** [comment]
> I'm using NextJs and the document.activeElement.blur() fix works locally but I get an error saying 'document is not defined'

You need to check that it's running client-side
`onClick={() => {
                  if (typeof window !== "undefined") {
                    document.activeElement.blur();
                  }
                }}`
