### ISSUE TITLE
bug: Collapse not expanding correctly on Ecosia on Android

### ISSUE THREAD

**Issue by Aragur** [saadeghi/daisyui#2010]
### What version of daisyUI are you using?

v3.1.1

### Describe your issue

Collapse content is not expanding as expected.
See image attached below:
![246488722-06fe821b-cc32-4a09-b507-9e0c5b042133](https://github.com/saadeghi/daisyui/assets/11004008/fbc49856-934a-424f-a663-c35d4d49e467)

### What browsers are you seeing the problem on?

Ecosia 7.1.0 on Android 13

### Reproduction URL (optional)

https://daisyui.com/components/collapse/#collapse-with-checkbox

**Comment by saadeghi** [comment]
I have no idea what is "Ecosia". I just saw their website and it says it's a ...search engine?  
If it's a search engine, what is the actual browser you're using?  
Do you have this issue on other browsers on your Android? (probably `Chrome for Android` or `Android Browser` or `Samsung Internet`)
