### ISSUE TITLE
Show how to modify Modal trigger by state changed

### ISSUE THREAD

**Issue by ChapmanCheng** [saadeghi/daisyui#202]
I'd like to suggest at the docs: [modal](https://daisyui.com/components/modal)
show user how to trigger the the opening of the modal manually, e.g. I'm using React's state change to open the modal, not `<a>` or `<input type="checkbox"/>`

It's just this part: 
```
<div id="my-modal" className={state ? "modal opacity-100 pointer-events-auto visible" : "modal"}>
    <div className={state? "modal-box transform scale-100 translate-y-0" : "modal-box"}>
        // rest of modal code
    </div>
</div>
```

thanks

**Comment by saadeghi** [comment]
@ChapmanCheng There's a utility class as mentioned [in the docs](https://daisyui.com/components/modal/):  
`modal-open`: Add/remove this class to open/close the modal using JS
