### ISSUE TITLE
bug: `btn-disabled` doesn't overwrite e.g. `btn-error` styling anymore in v3

### ISSUE THREAD

**Issue by tristndev** [saadeghi/daisyui#2023]
### What version of daisyUI are you using?

v3.1.1

### Describe your issue

In daisyUI v2 I used to conditionally add the `btn-disabled` class to all kinds of `btn` elements. Here, this would overwrite the type of the button, no matter what that was (e.g., `btn-primary` or `btn-error`).

In daiysUI v3 this doesn't seem to work anymore: Conditionally adding the `btn-disabled` class just changes the button behavior (unclickable, no changed cursor) but the styling stays the same. 

### What browsers are you seeing the problem on?

Firefox

### Reproduction URL (optional)

https://play.tailwindcss.com/eUmbFJcv1M

**Comment by Toysoldier34** [comment]
This may not fully resolve things, but try adding "!" to the front of the btn-disabled as this may help to force it to not be overridden. On your testing URL adding btn-disabled to a button did exactly as you described, but !btn-disabled did mute the button and disable more as you would expect.
