### ISSUE TITLE
bug: two tooltips next to each other groups

### ISSUE THREAD

**Issue by viktorvoltaire** [saadeghi/daisyui#2028]
### What version of daisyUI are you using?

v3.1.0

### Describe your issue

When using more then one tooltip in a table, also tried with using `<div>` inside the each column, the layout of the table gets disregarded. If I insert an empty between the tooltips `<th></th>` then it doesnt break.

Without tooltip:
<img width="866" alt="Screenshot 2023-06-20 at 15 28 18" src="https://github.com/saadeghi/daisyui/assets/19266705/20ac9653-f00c-436b-893d-a476ea2ac923">

With tooltip:
<img width="897" alt="Screenshot 2023-06-20 at 15 28 58" src="https://github.com/saadeghi/daisyui/assets/19266705/f2499e8d-9242-4fdc-a743-97847bf337a6">

```html
<table className="table w-full table-auto text-center">
  <thead>
    <tr>
      <th>One</th>
      <th>Two</th>
      <th>Three</th>
      <th>Four</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <th>2</th>
      <th className="tooltip" data-tip="..">3</th>
      <th className="tooltip" data-tip="..">4</th>
    </tr>
  </tbody>
</table>
```

### What browsers are you seeing the problem on?

Chrome Version 114.0.5735.133

**Comment by saadeghi** [comment]
Don't add `tooltip` class to table cells because it changes cell's `display` from `table-cell` to `inline-block` and that of course changes the cell layout.  
Instead add a div in the table cell and add `tooltip` class to that:  
https://play.tailwindcss.com/XuUt467zlp

**Comment by viktorvoltaire** [comment]
@saadeghi as I wrote in the description I tried that and I it rendered the same result
