### ISSUE TITLE
bug: active styles are applied to whole submenu when a submenu item is selected

### ISSUE THREAD

**Issue by deva-ct** [saadeghi/daisyui#2033]
### What version of daisyUI are you using?

3.1.5

### Describe your issue

when clicking on any submenu item of any nested level, the active styles are applying to the whole topmost submenu (to the `details` tag) instead of the current clicked item

This may be related to this recent change,
```
.menu li > *:active,
.menu li > *.active {
  @apply bg-neutral text-neutral-content [@media(hover:hover)]:bg-neutral [@media(hover:hover)]:text-neutral-content;
}
```

### What browsers are you seeing the problem on?

All browsers

### Reproduction URL (optional)

https://daisyui.com/components/menu/

**Comment by saadeghi** [comment]
duplicate of #2041
