### ISSUE TITLE
bug: Black theme button texts defaults to lower case

### ISSUE THREAD

**Issue by Vijayabhaskar96** [saadeghi/daisyui#2036]
### What version of daisyUI are you using?

3.1.5

### Describe your issue

The "black" theme button text defaults to all lowercase, which differs from all the other themes.

![Screenshot_154](https://github.com/saadeghi/daisyui/assets/17958636/83fc76c3-ac0d-41e9-9773-03081bd01e24)

### What browsers are you seeing the problem on?

Chrome

### Reproduction URL (optional)

https://daisyui.com/components/button/

**Comment by saadeghi** [comment]
It's not a bug.  
It's a design decision for that theme:  
https://github.com/saadeghi/daisyui/blob/d60878c80d952e9edce04c5f60abe1f97dcac5ba/src/theming/themes.js#L34

But you can change that like this if you want: https://play.tailwindcss.com/Bcq18ArYlL?file=config
