### ISSUE TITLE
Suggestion of improvement indicator !?

### ISSUE THREAD

**Issue by devopg** [saadeghi/daisyui#204]
indicator on little object is okey:
![image](https://user-images.githubusercontent.com/61819835/133851021-823e1df5-5876-45cf-986a-622f8f751e20.png)
but on big avatar we have indicator out of avatar:
![image](https://user-images.githubusercontent.com/61819835/133851180-847c023c-45c5-42ad-b7ee-48ecfe3f9611.png)

i think better will be if 
1) indicator always be in 
2) indicator size be proportionally avatar size 

like that 
![image](https://user-images.githubusercontent.com/61819835/133851558-fed8c19d-2b8e-45e1-9146-e8b30791ad93.png)

**Comment by saadeghi** [comment]
@devopg you're right and that definitely looks better.  
The problem is that image can be any size and I couldn't come up with a positioning for the indicator that always touch the circle 🤷‍♂️

**Comment by devopg** [comment]
all simple ? 

```
.avatar::before {
    position: absolute;
    right: 0;
    bottom: 0;
    width: 25%;
    height: 25%;
    border-radius: 50%;
    content: '';
    border: 2px solid #fff;
}


.avatar {
    width: 3rem;
    height: 3rem;
}

.avatar-xxl {
    width: 8rem;
    height: 8rem;
}
```

![image](https://user-images.githubusercontent.com/61819835/134787359-024fe7d8-140f-4ead-ba8b-0b9f549e71d1.png)
