### ISSUE TITLE
Dropdown Bug

### ISSUE THREAD

**Issue by Chahat-Rakshawat-ALDS** [saadeghi/daisyui#2040]
### What version of daisyUI are you using?

in each version

### Describe your issue

When we click on single element of dropdown it doesn't close the dropdown.

### What browsers are you seeing the problem on?

Chrome, Safari, Firefox, Edge, All browsers, Other

**Comment by saadeghi** [comment]
If you're using [method 1](https://daisyui.com/components/dropdown/#method-1-using-details-and-summary-tags) `<details>` tag, This is how HTML [`<details>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) works. It opens or closes only when you click on `<summary>`. When you click, an attribute names `open` gets added and you can control the state by adding or removing the `open` attribute whenever you want.

If you're using [method 2](https://daisyui.com/components/dropdown/#method-2-using-label-and-css-focus) it works with CSS focus. the dropdown stays open until something else if focused.

Here is an example on how you can close the dropdown when an item is focused:  
https://play.tailwindcss.com/mdhT227vEC   
```html

<div class="dropdown">
  <div tabindex="0" class="m-1 btn">Open with focus</div> 
  <ul tabindex="0" class="p-2 shadow menu dropdown-content z-[1] bg-base-100 rounded-box w-44">
    <li>
      <span onclick="document.activeElement.blur()">Close on click</span>
    </li> 
    <li><span>Item 2</span></li>
  </ul>
</div>
```
```html
<details class="dropdown mb-32" id="myDropdown">
  <summary class="m-1 btn">open or close</summary>
  <ul class="p-2 shadow menu dropdown-content z-[1] bg-base-100 rounded-box w-44">
    <li>
      <span onclick="document.getElementById('myDropdown').removeAttribute('open')">Close on click</span>
    </li>
    <li><span>Item 2</span></li>
  </ul>
</details>
```
