### ISSUE TITLE
bug: Tab className

### ISSUE THREAD

**Issue by nnnnnnnnnni** [saadeghi/daisyui#2044]
### Describe your issue

Im confuse about Tab component
in 'modifier' classnames
why tabs-boxed in div DOM, but tab-lifted and tab-bordered in a DOM?

### What browsers are you seeing the problem on?

Other

### Reproduction URL (optional)

https://daisyui.com/components/tab/?lang=en

**Comment by saadeghi** [comment]
Because `tabs-boxed` modifies the style of parent (`tabs` class)  
`tab-lifted` and `tab-bordered` only modify the style of children (`tab` class)

**Comment by saadeghi** [comment]
For questions, please use [Discussions](https://github.com/saadeghi/daisyui/discussions). Not issues.

**Comment by nnnnnnnnnni** [comment]
> For questions, please use [Discussions](https://github.com/saadeghi/daisyui/discussions). Not issues.

OK。thks
