### ISSUE TITLE
bug: accessibility issue with checkbox

### ISSUE THREAD

**Issue by AshotN** [saadeghi/daisyui#2045]
### Describe your issue

I want to be able to tab onto a checkbox and press `space` to toggle it's state. It works on Chromium, but not Firefox.

### What browsers are you seeing the problem on?

Firefox

### Reproduction URL (optional)

https://daisyui.com/components/checkbox/

**Comment by saadeghi** [comment]
It works on Firefox just like other browsers. Here's a video:

https://github.com/saadeghi/daisyui/assets/7342023/b1168c65-b144-4a25-a4d9-03d383baca6f

- Are you using any plugin or extension that may change the keyboard navigation behavior?
- Do you have this issue with incognito mode as well?
- Do you have this issue with normal checkbox (without daisyUI)?

**Comment by AshotN** [comment]
Interesting, with my plugins disabled it does work correctly. Oddly, with my plugins enabled this page works fine https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/checkbox. 

Not sure what the root cause is, but clearly isn't a Daisy issue, sorry for wasting your time.
