### ISSUE TITLE
bug: New dialog implementation does not inherit text color.

### ISSUE THREAD

**Issue by Jabronironi** [saadeghi/daisyui#2048]
### What version of daisyUI are you using?

3.1.6

## Issue

I noticed that when using the new <dialog> option for modals, the text colors are not matching the theme (for example dark theme - font is #FFFFFF - pulled from user agent canvas setting).

## Work Around

I am adding a class to the dialog to set it to the proper text-base color.

### What browsers are you seeing the problem on?

Edge

**Comment by saadeghi** [comment]
It does inherit the text color. I can't see the issue you mentioned.   
Can you please provide an example on Tailwind Play or StackBlitz or a GitHub repo so I can see the issue?

**Comment by Jabronironi** [comment]
Sure:

https://play.tailwindcss.com/XRzjj26wDI

You can see the text next to the button takes on the the data theme font color (which is not #FFF.  However, within the dialog, that is not respected, and you get a stark white color.
