### ISSUE TITLE
Component Not found

### ISSUE THREAD

**Issue by SupunSam** [saadeghi/daisyui#205]
Hi, I am using daisyui for my laravel app and it works fine or that's what I thought. Whenever I use something with components as below chrome console throws an error. I tried to use a Carousal for my app.

`<a href="/components/carousel#item1" class="btn btn-xs btn-circle">1</a>`

Saying 404 it's not found. So I believe these components should be in my components folder. Right?

I followed the documentation clearly. Is there anyway to publish these components to my reources\Views folder

**Comment by saadeghi** [comment]
@SupunSam that's just demo URL. If you're using that carousel example, you just need the anchor link like this:
```
<a href="#item1" class="btn btn-xs btn-circle">1</a>
```

Let me know if you have any questions

**Comment by SupunSam** [comment]
Oh, how stupid of me. Yes of course. Thanks. Got it.
