### ISSUE TITLE
bug: Dialog backdrop not working when controlled using `open`

### ISSUE THREAD

**Issue by omikader** [saadeghi/daisyui#2052]
### What version of daisyUI are you using?

v3.1.6

### Describe your issue

Thank you for building such an awesome library!

I've been working with the `Modal` component and controlling it's state using the [`open`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/open) property instead of the [`showModal`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal) method. On v3.0.3, everything works as expected -- the modal backdrop appears and the modal is hidden when I click the backdrop.

https://github.com/saadeghi/daisyui/assets/16735699/1ef1e5f1-8456-4716-8df4-9b42e9d2c1b8

However, in the latest version of daisyUI (v3.1.6), I noticed that the backdrop is no longer appearing.

https://github.com/saadeghi/daisyui/assets/16735699/b752cbb1-3979-48f0-bc9f-87922c4fd218

I saw a duplicate issue in https://github.com/saadeghi/daisyui/issues/1962 but the issue persists for me. [Code](https://github.com/omikader/nytx/blob/main/app/src/pages/home/PlayerModal.tsx) can be found below:

```
import { isNull } from "lodash";

import { PlayerModalContent } from "./PlayerModalContent";

interface IProps {
  name: string | null;
  handleClose: () => void;
}

export const PlayerModal = ({ name, handleClose }: IProps) => {
  return (
    <dialog className="modal modal-bottom sm:modal-middle" open={!isNull(name)}>
      <form method="dialog" className="modal-box">
        {name && <PlayerModalContent name={name} />}
      </form>

      <form method="dialog" className="modal-backdrop">
        <button onClick={handleClose} />
      </form>
    </dialog>
  );
};
```

I've deployed my project at the reproduction URL with v3.1.6 of daisyUI in case you wanted to play around

### What browsers are you seeing the problem on?

All browsers

### Reproduction URL (optional)

https://nytx.omikader.com

**Comment by RamonGal** [comment]
this isnt really a bug, it is just missing the class that defines the backdrop color, just define a color globaly like:

.modal-backdrop {
  background-color: rgba(105, 105, 105, 0.34);
}

**Comment by saadeghi** [comment]
@omikader This is how the HTML element `<dialog>` works.  
From [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog):  
>It is recommended to use the `.show()` or `.showModal()` methods to render dialogs, rather than the open attribute. If a `<dialog>` is opened using the open attribute, it will be non-modal.

If you wan't the backdrop, open the modal using `.showModal()` method instead of adding `open` attribute. This way it will have `::backdrop` pseudo element.  If you open it just by adding removing `open` attribute, it won't have backdrop.  

Another way is adding/removing `modal-open` class alongside with the `open` attribute. That way you can also have the backdrop color.
