### ISSUE TITLE
bug: Avatar indicator has a square outline in Safari

### ISSUE THREAD

**Issue by omikader** [saadeghi/daisyui#2053]
### What version of daisyUI are you using?

v3.1.6

### Describe your issue

Thanks for building such an awesome library!

I noticed that the online avatar indicator has a square outline in Safari:

![image](https://github.com/saadeghi/daisyui/assets/16735699/e360f9df-c760-4d26-9879-4175ed446937)

I believe it is due to the `outline-style` property

https://github.com/saadeghi/daisyui/assets/16735699/deddc373-4d5b-4f27-8511-6ea4d49d02b2

### What browsers are you seeing the problem on?

Safari

### Reproduction URL (optional)

https://nytx.omikader.com

**Comment by saadeghi** [comment]
I don't see this issue on Safari. Which version of Safari are you using?

**Comment by omikader** [comment]
Not sure anymore since I just upgrade all of my devices to the latest iOS and MacOS and it appears to be resolved 🥳
