### ISSUE TITLE
bug: Drawer contents make contents over screen on mobile.

### ISSUE THREAD

**Issue by seunex17** [saadeghi/daisyui#2060]
### What version of daisyUI are you using?

v3.0.1

### Describe your issue

Look like there is a problem when using an external classes in a drawer contents. The designs are perfect on version 2 but look broken on v3. 

In my pages i am using a slider library swiperjs any time it in the drawer-content is overlap the screen. But when you move it out of the drawer conte tents it remain perfect.

P.S this does look okay on PC and Tablet view but only affect the mobile views please take a look the screen below.

PC:
![image](https://github.com/saadeghi/daisyui/assets/38796424/69c92cd7-d9bb-4f6f-ae75-0f97ad8919a5)

Tablet PC:
![image](https://github.com/saadeghi/daisyui/assets/38796424/e137174c-e9e0-4e19-9980-9732947e5365)

On Mobile Device: (V3)
![image](https://github.com/saadeghi/daisyui/assets/38796424/ed84ddfc-7a4a-4d1c-9ae8-b3803ddd92c6)

Mobile device (v2)
![image](https://github.com/saadeghi/daisyui/assets/38796424/05f7bfb6-6d90-4ae7-ae74-7f5a5e6361e5)

Am not sure why but just find it this way. No much worries on my end i just have to rollback to v2 and keep building with it. 
But any one who try to build with diasy ui and going to use Drawer and a slider packages like SwiperJs or Splide with face this problem.

### What browsers are you seeing the problem on?

Chrome, Firefox, Edge

**Comment by saadeghi** [comment]
It's really hard to guess what is the issue when you don't provide a reproduction repo or a code example, my friend.

**Comment by seunex17** [comment]
@saadeghi  I am not very experienced in reporting issues and bugs, but a quick way to reproduce the problem is by setting up a new project with Daisy UI and using the drawer component to wrap the page contents. Then, try using one of the slider packages like Swiper.js or Splide. The responsiveness may be an issue on mobile devices, whereas it looks perfect on PCs. I will prepare a reproduction code for this today. Thank you.

**Comment by Bewinxed** [comment]
No idea why this fixes it but it fixes it 

Set overflow x auto on the collapse content div

https://github.com/saadeghi/daisyui/issues/1914#issuecomment-1575699931
