### ISSUE TITLE
bug: (feature request) I'd like to be able to disable themes on the fly using `data-theme="disabled"`.

### ISSUE THREAD

**Issue by ivandimitrov8080** [saadeghi/daisyui#2061]
### What version of daisyUI are you using?

latest npm package

### Describe your issue

I'd like to be able to disable the theme dynamically using an html flag so that I can embed apps in transparent iFrames more easily.

Currently when the default themes are present, the entire page is styled according to the chosen theme and I can't seem to be able to override any styles. I tried using
```
* {
    background-color: white !important;
}
```
or
```
* {
    background-color: transparent !important;
}
```
but the styles remain untouched. This affects how the app is shown inside an iframe.

If I were to disable all themes using
```
  daisyui: {
    themes: []
  }
```
then the iFrame is transparent and it blends in well with the parent page. This affects how the app looks like when it is not inside an iFrame.

If I could set the `data-theme="disabled"` on  the html element, then I could use some JS to detect whether or not the app is inside an iFrame and change themes accordingly.

---
Could I have my cake and eat it too, please?

### What browsers are you seeing the problem on?

All browsers

**Comment by saadeghi** [comment]
So the problem is not the theme, you just want the background of the page (iframe) to be transparent?

**Comment by saadeghi** [comment]
I think you should use some JS to detect if it's iframe or not. I don't think that's possible with CSS.  
but to make the background transparent, you can add `bg-transparent` to the `<html>` tag.
