### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by NaviTheCoderboi** [saadeghi/daisyui#2069]
### What version of daisyUI are you using?

v3.1.5

### Describe your issue

why daisyui css is not applying to the chat bubble background?
this is my code of tailwind.config.css
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                "text-dark": "#f7faf4",
                "bg-dark": "#221632",
                "primary-btn": "#6f449c",
                "secondary-btn": "#261a37",
                "accent-dark": "#6f449c",
                "dark-nav": "#262329",
            },
        },
    },
    plugins: [require("daisyui")],
    darkMode: "class",
    daisyui: {
        themes: [],
    },
};
```
and this is my code 
```tsx
                    <div className="p-6">
                        <div className="chat chat-start">
                            <div className="chat-bubble chat-bubble-primary">
                                What kind of nonsense is this
                            </div>
                        </div>
                    </div>
```
https://media.discordapp.net/attachments/244238416248569857/1123202761295659109/image.png

### What browsers are you seeing the problem on?

All browsers

**Comment by santiruffino** [comment]
Hey @NaviTheCoderboi. What happens if you use a theme without any customization? Did you try with another component to check if the issues is only on the chat bubble?

**Comment by saadeghi** [comment]
@NaviTheCoderboi When you have an empty array for `themes`
```
    daisyui: {
        themes: [],
    },
```
That means you disabled all themes, so there is no primary color or any other daisyUI colors included so no component will have any colors by default.

See config docs: https://daisyui.com/docs/config/
