### ISSUE TITLE
Suggestion : Search box with floating results

### ISSUE THREAD

**Issue by pooyaEst** [saadeghi/daisyui#207]
A search box with floating on top suggestions box just like Github, google, Stackoverflow and many others. 
i dont know if it fits into a new component or just a demo using currently available components but it's a very much needed feature.
Thank you

**Comment by saadeghi** [comment]
@pooyaEst  
Using [dropdown](https://daisyui.com/components/dropdown) with [text input](https://daisyui.com/components/form/input) and [menu](https://daisyui.com/components/menu): 
 https://play.tailwindcss.com/UeXWmfZ2tR

**Comment by pooyaEst** [comment]
Thank you very much. i think it's a good idea to add this to examples in website, maybe under text input.
