### ISSUE TITLE
bug: Type 'string' is not assignable to type 'boolean'.

### ISSUE THREAD

**Issue by sytpb** [saadeghi/daisyui#2078]
### What version of daisyUI are you using?

3.1.1

### Describe your issue

error happne in my tsx file , 

Details : 

I copy the code from daisy web 

`<input type="checkbox" checked="checked" className="checkbox" />`

the error show me in vscode "Type 'string' is not assignable to type 'boolean'."  the word 'checked' is red notice .

**Comment by saadeghi** [comment]
This is valid HTML code and you should be able to use it with or without daisyUI.  

So, maybe you should ask this question on a Typescript discussion forum?  
Because that warning is not related to daisyUI. It's about a simple HTML attribute.

**Comment by sytpb** [comment]
OK ,thanks  for you reply, something I am not understand , daisyUI doesn't support typescript ?

**Comment by saadeghi** [comment]
daisyUI just adds additional CSS class names to Tailwind CSS.  
Typescript is for JavaScript type safety.  

daisyUI has nothing to do with your JS/TS code. It's just CSS so I'm not sure what you mean by supporting typescript?!
