### ISSUE TITLE
bug: radial-progress was complained by vscode about `--value` and `--size`

### ISSUE THREAD

**Issue by hughlv** [saadeghi/daisyui#2081]
### What version of daisyUI are you using?

v3.1.7

### Describe your issue

The following simple code caused vscode complaining about `--value`:

```
<div className="radial-progress" style={{ '--value': progress, '--size': '1rem' }} />
```

The issue is:

```
Type '{ '--value': number; '--size': string; }' is not assignable to type 'Properties<string | number, string & {}>'
```

<img width="922" alt="image" src="https://github.com/saadeghi/daisyui/assets/817110/c42ffcab-f465-434d-af7b-eb684c527bae">

### What browsers are you seeing the problem on?

Edge

**Comment by saadeghi** [comment]
You should ask this in a typescript forum discussion but here's your answer: https://stackoverflow.com/questions/52005083/how-to-define-css-variables-in-style-attribute-in-react-and-typescript

**Comment by hughlv** [comment]
> You should ask this in a typescript forum discussion but here's your answer: https://stackoverflow.com/questions/52005083/how-to-define-css-variables-in-style-attribute-in-react-and-typescript

Thanks.

**Comment by Radexman** [comment]
To fix this TypeScript error all you need to do is to import CSSProperties from react and use assertion on custom property:
`
          <div
            className="radial-progress text-primary"
            style={{ "--value": completedPercentage } as CSSProperties}
          >
            <p>{`${completedPercentage.toFixed()}%`}</p>
          </div>
`
