### ISSUE TITLE
docs: JSX style is wrong

### ISSUE THREAD

**Issue by ullenboom** [saadeghi/daisyui#2082]
### On which page do you see this issue?

https://daisyui.com/components/hero/

### Describe the issue

In JSX style is an object:

    <div className="hero min-h-screen" style="background-image: url(/images/stock/photo-1507358522600-9f71e620c44e.jpg);">

->

    <div className="hero min-h-screen" style={{backgroundImage: 'url(/images/stock/photo-1507358522600-9f71e620c44e.jpg);'}}>

**Comment by santiruffino** [comment]
Trying to give a hand here. The problem seems to be on the `hero-content` class.
