### ISSUE TITLE
bug: Dark Mode via `prefers-dark-mode` not Working when themes are customized

### ISSUE THREAD

**Issue by jonnylangefeld** [saadeghi/daisyui#2085]
### What version of daisyUI are you using?

v3.0.2

### Describe your issue

Following [the docs](https://daisyui.com/docs/themes/#-1) to set other than the default themes it says:
> You can only include the themes you want in your project. This will reduce the size of your CSS file. In the below example
cupcake will be the default theme for light mode
dark will be the default theme for dark mode
cmyk can be applied on any HTML tag with data-theme='cmyk'
```
    module.exports = {
      daisyui: {
        themes: ["cupcake", "dark", "cmyk"],
      },
    }
```

However that doesn't quite work.
In [this stackblitz](https://stackblitz.com/edit/daisyui-nextjs-t67mmu?file=tailwind.config.js) I intentionally chose a lighter theme (`lemonade`) as the dark theme to make it obvious that it never takes that in.

I'm using chrome dev tools > Rendering > Emulate CSS media feature prefers-dark-mode for testing. See gif:

![daisy](https://github.com/saadeghi/daisyui/assets/18717376/656f148a-2a43-411e-a9bf-900c4d6d56b3)

Both, light and dark should both look pretty light, as lemonade is a light theme.

Automatic light and dark mode detection works if not setting any custom themes.

### What browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://stackblitz.com/edit/daisyui-nextjs-t67mmu?file=tailwind.config.js

**Comment by jonnylangefeld** [comment]
This discussion from February definitely seems like it should work: https://github.com/saadeghi/daisyui/discussions/1574#discussioncomment-4865692

Also,  a config like
```
module.exports = {
  content: ['./pages/**/*.{js,ts,jsx,tsx,mdx}'],
  plugins: [require('daisyui')],
  darkTheme: 'lemonade',
};
```
Doesn't respect the darkTheme setting at all.

I also noticed that the https://daisyui.com/docs page itself doesn't react to prefers-dark-mode

**Comment by saadeghi** [comment]
It should be like this
```
module.exports = {
  content: ['./pages/**/*.{js,ts,jsx,tsx,mdx}'],
  plugins: [require('daisyui')],
  daisyui: {
    darkTheme: 'lemonade',
  }
};
```
Not this:
```
module.exports = {
  content: ['./pages/**/*.{js,ts,jsx,tsx,mdx}'],
  plugins: [require('daisyui')],
  darkTheme: 'lemonade',
};
```

All daisyUI configs should be inside `daisyui{ }` object. See the docs: https://daisyui.com/docs/config/
