### ISSUE TITLE
bug: Hovering <a href="/login">login</a> link add some unexpected css rules

### ISSUE THREAD

**Issue by KKKaisar** [saadeghi/daisyui#2089]
### What version of daisyUI are you using?

v2.52.0

### Describe your issue

I have <a href="/login">login</a> in drawer and hovering it adds some styles to html like margin or padding. I tried to hover other links and nothing happen. I tried to remove href or change it to other href like "login", "user/login", "login/to" and it works fine. Only when href="/login" it adds some styles. I also tried  to place it somewhere else in body or navbar and it still adds some style to span or other tags. Also links in drawer gets some margin or padding after hover that login link.
It only works in DaisyUI and not in Tailwind play. I am using SvelteKit.

### What browsers are you seeing the problem on?

Chrome, Other

**Comment by saadeghi** [comment]
[`link`](https://daisyui.com/components/link/) class has no margin or padding. `drawer` has no margin or padding either. So I don't know why you're having these issues.  

Can you provide an example repo so I can see the issue?

**Comment by KKKaisar** [comment]
@saadeghi Yes, I'll try to make example repo

**Comment by KKKaisar** [comment]
@saadeghi I found problem. It is because sveltekit gets different route's styles when hovering link to that route. Sorry for thinking that is daisy's bug. Thanks
