### ISSUE TITLE
bug: DDark theme on dropdown items makes text very hard to read

### ISSUE THREAD

**Issue by Ly-sg** [saadeghi/daisyui#2090]
### What version of daisyUI are you using?

v3.1.7

### Describe your issue

Hello there,
I'm trying to implement DaisyUi on a Ionic (angular) app.
I've searched a bit on how to setup the default light and dark themes and toggle on of them, i noticed that the dropdown menu items in dark theme have dark text on a dark background which makes it really hard to read, i doubt it's the intended result.
![image](https://github.com/saadeghi/daisyui/assets/61589599/6c925739-6b27-4b7b-8104-dce493ff1101)
As you can see the dropdown button's fine white on black, however the items in the dropdown are black on black and the text is nearly invisible (bg-base-100 class on dropdown).

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
Some styles are missing in your app.  

As you can see here: https://play.tailwindcss.com/1Bbxg1iLi7  
the `<html>` tag should have background color and text color by default which creates a good color combination for all themes
<img width="530" alt="Screenshot 2023-07-04 at 00 16 55" src="https://github.com/saadeghi/daisyui/assets/7342023/9799f0f4-8d74-4a2b-8470-c63ccd93c9a0">

If it's not like that on your app, something's wrong. It may be another CSS file applying styles or it can be scoping issue. If you provide an example repo I can help with that.

Also as a workaround you can add `text-base-content` to `bg-base-100` so it creates a good foreground color for that background.

**Comment by Ly-sg** [comment]
Hello,
Thanks for the quick response, you are right there was a style that was interferring with DaisyUi's theme, i first thought that it was ionic's core stylesheet variables but in reality the dropdown's color was overriden by ionic's Tab component style (the dropdown is IN the tab)
I placed another dropdown outside of the tab and it's style is looking good as you can see
![Screenshot_2023-07-04_14-08-51](https://github.com/saadeghi/daisyui/assets/61589599/28766903-f206-4638-b695-174b8107aba9)


I'll try to use only DaisyUi components to avoid the two component libraries interferferences.

Thanks for your help
