### ISSUE TITLE
bug: drawer-end with drawer-open appears on the left

### ISSUE THREAD

**Issue by FireSon** [saadeghi/daisyui#2094]
### What version of daisyUI are you using?

3.1.7

### Describe your issue

When I use the drawer with drawer-end and drawer-open I would expect to see the drawer on the right side but it appears on the left.  If however you open the drawer by clicking in the button it appears on the right.
Below is the example.

https://play.tailwindcss.com/8MzVL2nRXQ

### What browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://play.tailwindcss.com/8MzVL2nRXQ

**Comment by VladimirAmosov** [comment]
Hello! I faced the same problem with drawer. However, that way I fixed it: <div className="drawer-side" style={{**display: 'inherit'**}}>
