### ISSUE TITLE
bug: bordered menu item not working in 3+

### ISSUE THREAD

**Issue by brendanmatkin** [saadeghi/daisyui#2097]
### What version of daisyUI are you using?

v3.1.9

### Describe your issue

This MIGHT be a documentation issue. Looks like bordered menu items are either broken or no longer included. If "bordered" is no longer a class option on purpose, then its removal is missing from the changelog. 

### What browsers are you seeing the problem on?

All browsers

**Comment by saadeghi** [comment]
Yes it was removed.  
Basically the whole menu style was rewritten from scratch and with the new style there's no need for a specific `bordered` modifier class because you can use any Tailwind CSS border utility class now.  
It was missing from the changelog. My bad. I will add it now.

**Comment by brendanmatkin** [comment]
> Yes it was removed. Basically the whole menu style was rewritten from scratch and with the new style there's no need for a specific `bordered` modifier class because you can use any Tailwind CSS border utility class now. It was missing from the changelog. My bad. I will add it now.

Makes sense, thanks for updating the changelog!
