### ISSUE TITLE
bug: tailwind css not applying when using ternary operator for chat bubble classnames

### ISSUE THREAD

**Issue by Jemsukie** [saadeghi/daisyui#2098]
### What version of daisyUI are you using?

3.1.9

### Describe your issue

Chat bubbles are not positioning well and tailwind css is not applying also when I am using ternary operator to decide for position and color
![image](https://github.com/saadeghi/daisyui/assets/108327043/ab5ea1ba-a19a-46de-8c66-c915d1cef67f)

In the elements tab we can see that the chat bubbles have these classes "chat chat-end" to position it and "chat-bubble chat-bubble-primary" for the color. What's happening right now is I'm having this black bg bubbles with incorrect positions.
![image](https://github.com/saadeghi/daisyui/assets/108327043/aaee0bc4-2445-474d-b265-beb2c802ac53)

Here's how I implement it:
```tsx

const isSent = c.remark === 'Sent'
const pos = isSent ? 'end' : 'start'
const color = isSent ? 'primary' : 'success'

return (
<div className={`chat chat-${pos}`} key={idx}>
        <div  className={`chat-bubble chat-bubble-${color}`}>
        </div>
</div>
)
```

Another observation is if I make it this way (hardcoded):
```tsx
<div className={`chat chat-end`} key={idx}>
        <div  className={`chat-bubble chat-bubble-primary`}>
        </div>
</div>
```

I'll be seeing:
![image](https://github.com/saadeghi/daisyui/assets/108327043/6d4d039d-51b2-40b5-82c6-795a5a8c0add)

*Create an account in this [web app](https://chat-agvla35f1-jemsukie.vercel.app/) and observe*

### What browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://chat-agvla35f1-jemsukie.vercel.app/

**Comment by omikader** [comment]
https://github.com/saadeghi/daisyui/issues/2077#issuecomment-1613744734

**Comment by saadeghi** [comment]
Let me know if this 👆 didn't solve the issue.

**Comment by Jemsukie** [comment]
> > [#2077 (comment)](https://github.com/saadeghi/daisyui/issues/2077#issuecomment-1613744734)
> 
> Let me know if this 👆 didn't solve the issue.

Thanks for this one @saadeghi!
