### ISSUE TITLE
DaisyUi does not work properly with WindiCSS

### ISSUE THREAD

**Issue by gunters63** [saadeghi/daisyui#21]
I think it makes sense to create an upstream issue here for bugs which make DaisyUi not work properly with WindiCSS.

[WindiCSS-related bugs](https://github.com/windicss/windicss/issues?q=is%3Aissue+author%3A%40me+)

All those are bugs in WindiCSS!

Big improvements were already made in the last couple of days. I hope it will work fully soon.

**Comment by saadeghi** [comment]
@gunters63 Thanks!  
It's good to follow them all in one place.

**Comment by atresnjo** [comment]
Thanks! I believe your link is wrong.

Should be [WindiCSS-related bugs](https://github.com/windicss/windicss/issues?q=+is%3Aissue+author%3Agunters63) am I right?

**Comment by gunters63** [comment]
I switched to Tailwind Jit now, works fine with Vite. WindiCSS still has many little quirks. 
I also fear maybe the developers of WindiCSS have now lost interest in their project (because of Tailwind Jit).
Its a pity, because I think the concept of WindiCSS still has some advantages.

**Comment by gunters63** [comment]
From my side we can close this issue

**Comment by saadeghi** [comment]
@gunters63 Thanks.
