### ISSUE TITLE
Incorrect  behavior of navbar menu for desktop + drawer for mobile

### ISSUE THREAD

**Issue by deyanskiq** [saadeghi/daisyui#210]
<img width="1161" alt="Screenshot 2021-09-22 at 19 37 56" src="https://user-images.githubusercontent.com/11162576/134385780-43e03818-5201-439e-b4ff-773bc57e0423.png">

While trying to implement similar standard layout structure, I'm hitting the problem from the screenshot, i.e 
`drawer-overlay` is supposed to cover the whole screen while right now it's covering only the drawer component.

Any suggestions how to achieve this?

**Comment by saadeghi** [comment]
@deyanskiq Here's an example: https://play.tailwindcss.com/MAxwyAigeN?size=866x720  

Let me know if you have any questions.

**Comment by deyanskiq** [comment]
Thanks for the quick response!

However I want to achieve this: https://play.tailwindcss.com/WzRL4MPumw?size=866x720
The `page content` should be behind the overlay.

**Comment by saadeghi** [comment]
@deyanskiq `drawer` is a wrapper for `drawer-content` and `drawer-side`. It's a grid layout. so your content [should be inside `drawer-content`](https://play.tailwindcss.com/zXuHA4PBzp?size=754x503)

**Comment by deyanskiq** [comment]
Thanks, I wasn't sure this is the correct way to do it.
