### ISSUE TITLE
bug: input-bordered class doesn't have any effect

### ISSUE THREAD

**Issue by samnayakawadi** [saadeghi/daisyui#2101]
### What version of daisyUI are you using?

2.51.0

### Describe your issue

I want to apply input-error class if the user enters the wrong input (validation error). But, I don't want the border to appear. Hence, I tried to remove the input-bordered from the className="input input-bordered input-error w-full max-w-xs" (Provided at the official documentation https://daisyui.com/components/input/#error-color)
But, It doesn't have any effect. input-error class forces the border.

Kindly have a look & resolve.

Also, check this for text area too.

### What browsers are you seeing the problem on?

All browsers

**Comment by omikader** [comment]
https://github.com/saadeghi/daisyui/issues/2077#issuecomment-1613744734

**Comment by saadeghi** [comment]
What is your expected style?  
I mean `input-error` class just adds the red border so why do you use that class if you don't want the border?

**Comment by samnayakawadi** [comment]
Yes! You are correct. But, I thought of a different way. Anyways, Thanks. Keep up the good work.
