### ISSUE TITLE
bug: Spinner does not work when applied to Alert

### ISSUE THREAD

**Issue by ZaxyxaZ** [saadeghi/daisyui#2103]
### What version of daisyUI are you using?

3.1.9

### Describe your issue

The following code does not work in 3.0. We are applying an Alert with a button that shows a spinner. The data is then fetched and the alert is displayed during that period. In 2.5.1+ this worked without issue. In 3.0+ there seems to be some blocking issue and the spinner is prevented from spinning and the button is not active.  We are using DaisyUI with current version of TailwindCSS and SvelteKit. 

Below is the code:

            <div class="alert">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-info shrink-0 w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                    <span>Loading data please wait...</span>
                
                <button class="btn btn-sm btn-primary place-self-end" on:click="{goToSetup}">
                    <span class="loading loading-spinner"></span>
                    Go to setup...
                </button>
            </div>

### What browsers are you seeing the problem on?

Chrome, Safari, Firefox

**Comment by saadeghi** [comment]
I don't see any issues:   
https://play.tailwindcss.com/9v3GbmypjZ

Are you using the latest version of daisyUI
