### ISSUE TITLE
bug: Menu - Clicked submenu item causes highlighting of parent item

### ISSUE THREAD

**Issue by jankoessendrup** [saadeghi/daisyui#2107]
### What version of daisyUI are you using?

3.1.11

### Describe your issue

Hey everyone,

I tried the menu example with the multiple submenus from the daisui documentation and had to notice the hover highlighting spreads over the complete parent during the click. I try to use it within an angular app and typescript version "~5.0.2".

![grafik](https://github.com/saadeghi/daisyui/assets/138893937/b8530f3a-ff8d-4590-a8fa-8e90ed0bbc16)

```
"devDependencies": {
    "@angular-builders/custom-webpack": "^16.0.0",
    "@angular-devkit/build-angular": "^16.0.4",
    "@angular/cli": "~16.0.4",
    "@angular/compiler-cli": "^16.0.0",
    "@types/jasmine": "~4.3.0",
    "autoprefixer": "^10.4.14",
    "daisyui": "^3.1.11",
    "jasmine-core": "~4.6.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "postcss": "^8.4.24",
    "postcss-import": "^15.1.0",
    "postcss-loader": "^7.3.3",
    "postcss-scss": "^4.0.6",
    "tailwindcss": "^3.3.2",
    "typescript": "~5.0.2"
  }
```

If there are any further questions, I am lucky to help.

**Comment by saadeghi** [comment]
This issue was fixed 2 weeks ago with `3.1.6` update.  

- Are you sure you're using the latest version? try uninstalling daisyUI and installing the latest version `npm i -D daisyui@latest`
- Are you sure there are no other CSS file in your project that may affect the colors?
