### ISSUE TITLE
bug: progress inner bar has no rounded end in Firefox

### ISSUE THREAD

**Issue by Zeerats** [saadeghi/daisyui#2116]
### What version of daisyUI are you using?

v3.2.1

### Describe your issue

The end of the progress inside the progress bar is not rounded in Firefox.
`<progress class="progress progress-primary w-full bg-neutral-600" value="70" max="100"></progress>`
![daisy_ui_progress](https://github.com/saadeghi/daisyui/assets/51681756/a2e23492-f2f1-43e6-bbf2-7bfba056f575)

### What browsers are you seeing the problem on?

Firefox

**Comment by beetrandahiya** [comment]
@saadeghi can you assign this one to me?

**Comment by saadeghi** [comment]
@beetrandahiya Yes. Thank you

**Comment by flomero** [comment]
@beetrandahiya just checking in. Are you still working on this? 
encountered the same issue right now and would like to fix it otherwise
