### ISSUE TITLE
bug: toggle doesn't seem well when clicked on it

### ISSUE THREAD

**Issue by unitythemaker** [saadeghi/daisyui#2119]
### What version of daisyUI are you using?

v3.2.1

### Describe your issue

There is an issue with toggle. Here is a video showing the bug:

https://github.com/saadeghi/daisyui/assets/83316880/77b412e6-3363-4f58-aff9-bc5d8b1c488f

I wonder if this happens for anyone else.

### What browsers are you seeing the problem on?

Chrome, Firefox

**Comment by saadeghi** [comment]
This style is not from daisyUI. It's from `@tailwindcss/forms` plugin.  
Read more: https://github.com/saadeghi/daisyui/issues/1431#issuecomment-1347822839
