### ISSUE TITLE
Use it with Nuxtjs

### ISSUE THREAD

**Issue by allaghi** [saadeghi/daisyui#212]
Hi everyone,
Have a nice day,
Firstly, I would really thank you for this library , it saves my days during work.
Secondly, I would like to know how can I use it with nuxt js in a proper way. if is there any specific requirement ? 

Thanks in advance.

**Comment by saadeghi** [comment]
@allaghi Here's a guide for adding Tailwind CSS to Nuxt: [this](https://tailwindcss.com/docs/guides/nuxtjs) or [this](https://tailwindcss.nuxtjs.org/)
Then you can install and add daisyUI [like this](https://daisyui.com/docs/install)

Let me know if you have any questions
