### ISSUE TITLE
Unexpected Behaviour: Modal + Drawer

### ISSUE THREAD

**Issue by pietz** [saadeghi/daisyui#213]
The behaviour of the modal and drawer components don't behave as I would expect when you use them in combination:

- If the two overlap because the modal is so wide, it will be hidden underneath the drawer. I think an active modal should be on top of everything else.
- The drawer is not greyed out like the rest of the UI when a modal is open. When a modal is open it probably should take the entire attention of the user. No matter if a drawer is used or not.

**Comment by saadeghi** [comment]
@pietz Take a look at this example: https://play.tailwindcss.com/rzAPde1JUj  
Let me know if you have any questions
