### ISSUE TITLE
bug: Property 'tabindex' does not exist on type 'HTMLAttributes<HTMLUListElement>'

### ISSUE THREAD

**Issue by LazyClicks** [saadeghi/daisyui#2130]
### What version of daisyUI are you using?

3.2.1

### Describe your issue

eslint for typescript is going crazy with tabindex inside the label element for the navbar

Type '{ children: Element[]; tabindex: string; class: string; }' is not assignable to type 'HTMLAttributes<HTMLUListElement>'.
  Property 'tabindex' does not exist on type 'HTMLAttributes<HTMLUListElement>'. Did you mean 'tabIndex'?

**Comment by saadeghi** [comment]
Is this JSX? If so it should be `tabIndex` (with capital i)   
Which code example from the docs is giving this warning?

**Comment by saadeghi** [comment]
Let me know if the problem still exists.

**Comment by LazyClicks** [comment]
> 

sorry i thought i had replied, and yeah it was a mistake on my end
