### ISSUE TITLE
bug: dasiyui overids tailwind colors

### ISSUE THREAD

**Issue by RjManhas** [saadeghi/daisyui#2136]
### What version of daisyUI are you using?

3.2.1

### Describe your issue

Hello i have my tailwind config like this 
```
/** @type {import('tailwindcss').Config} */

module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  	theme: {
		extand: {
			colors: {
				main: {
					test: "#6B01C3"
				}
			}
		}
	},
	
	
	daisyui: {
		themes: []
	},
	  plugins: [ require("daisyui")],
	
 


}

```

because I don't want to use any themes because they overide the default colors of tailwind and I like them but Im trying to add my branding colors to the tailwind and its not working anymore, i did in v2 but now it does not

### What browsers are you seeing the problem on?

Chrome

### Reproduction URL

none

**Comment by saadeghi** [comment]
You have a typo: `extand`.
daisyUI doesn't override Tailwind colors

**Comment by RjManhas** [comment]
omg thank you so much, idk how I missed that I was so confused but thanks,

**Comment by RjManhas** [comment]
just stared the repo since its a nice framework and good support lol
