### ISSUE TITLE
Remove Background

### ISSUE THREAD

**Issue by BuddiesTV** [saadeghi/daisyui#214]
Hello, i'm using daisyui for my alt:V Gamemode (GTA 5 Multiplayer Mod), to create better buttons and much more. I'm using Vue & i want to remove the background Color, how i can do it?

**Comment by tom-acceleratecompliance** [comment]
Are you looking to remove it at the theme level, or at an individual button?
With tailwind, adding the `bg-transparent` class should get rid of the background color.

**Comment by BuddiesTV** [comment]
Where i have to add bg-transparent?

**Comment by saadeghi** [comment]
@BuddiesTV You can add `bg-transparent` to your root element (`<html>`)  
Or you can add this to your CSS file:  
```
:root{
  background-color: none;
}
```
Or you can completely disable the base style [from config](https://daisyui.com/docs/config)
