### ISSUE TITLE
bug: Drawer content shouldn't be scrollable when drawer sidebar has no scrollable content

### ISSUE THREAD

**Issue by saadeghi** [saadeghi/daisyui#2142]
### What version of daisyUI are you using?

3

### Describe your issue

From discussion https://github.com/saadeghi/daisyui/discussions/2134

### What browsers are you seeing the problem on?

All browsers

**Comment by jordan-orionfinity** [comment]
Hello, is there any progress on this one or recommended solutions in the meantime? We are having issues where our drawer allows scrolling on the `drawer-content` behind it.

Thanks for the awesome library by the way, super cool! 😄

**Comment by bayasdev** [comment]
Drawer content is still scrollable on iOS Safari, not reproducible on other browsers or desktop Safari. You can reproduce this issue on my website:

https://bayas.dev/

PD: Thanks again @saadeghi!

**Comment by saadeghi** [comment]
@bayasdev yes. We're using CSS scrollbar-gutter which is the correct way to handle this situation. It's not currently supported I'm iOS Safari (it works behind a flag) but it is expected to be supported by default in the next version of safari.  
Since this behavior is not breaking the UI, I think it is worth it to wait for the next version of Safari.
