### ISSUE TITLE
bug: incorrect display of Join elements on native iPhone 13

### ISSUE THREAD

**Issue by stephanrudenko** [saadeghi/daisyui#2143]
### What version of daisyUI are you using?

v3.2.1

### Describe your issue

While working on my side project using Join elements, I came across an incorrect display on iPhone 13. First of all, we are talking about [https://daisyui.com/components/join/#join-radio-inputs-with-btn-style](https://daisyui.com/components/join/#join-radio-inputs-with-btn-style), when using the default component in Chrome Web Tools, the elements are displayed as expected:
<img width="960" alt="image" src="https://github.com/saadeghi/daisyui/assets/87760767/a21f3926-fbf9-4f3a-982a-98ff4c47e134">
but on the native iPhone 13 the elements stuck together:
![photo_2023-07-17_22-46-11](https://github.com/saadeghi/daisyui/assets/87760767/abbc1e1c-619b-48de-8864-51034d224ba1)
Then I tried to implement [https://daisyui.com/components/join/#responsive-its-vertical-on-small-screen-and-horizontal-on-large-screen](https://daisyui.com/components/join/#responsive-its-vertical-on-small-screen-and-horizontal-on-large-screen) by modifying the code to work with the radio buttons from the previous example, so the code looks as follows: 
`<div className="join-vertical join rounded-2xl py-6 lg:join-horizontal">
      <input
        className="join-item btn"
        type="radio"
        name="options"
        aria-label="Бюджетні"
        onClick={() => handleButtonClick("LOW")}
      />
      <input
        defaultChecked
        className="join-item btn"
        type="radio"
        name="options"
        aria-label="Середні"
        onClick={() => handleButtonClick("MIDDLE")}
      />
      <input
        className="join-item btn"
        type="radio"
        name="options"
        aria-label="Топ-ові"
        onClick={() => handleButtonClick("HIGH")}
      />
    </div>
`
and again, this component looks amazing in Web Tools, as well as on Android devices (as in the previous example):
<img width="960" alt="image" src="https://github.com/saadeghi/daisyui/assets/87760767/83c1c8d8-ed29-41c7-8cef-b25a3a05bd5b">
then on iphone 13: 
![photo_2023-07-17_22-55-52](https://github.com/saadeghi/daisyui/assets/87760767/efc42b86-c6bd-4603-9ec0-dca610ad5b16)
and after trying a huge number of options, I could not fix the look of this component - and visiting from iphone 13 to [https://daisyui.com/components/join/#join-radio-inputs-with-btn-style](https://daisyui.com/components/join/#join-radio-inputs-with-btn-style), on the site this element also appears compressed:
![photo_2023-07-17_23-00-30](https://github.com/saadeghi/daisyui/assets/87760767/82135407-7526-46f4-8cb7-2cc48387307d)
and also two components above looks a bit inconsistent (custom border radius, extra elements in the group)

### What browsers are you seeing the problem on?

Chrome, Safari, Firefox, Safari iOS

**Comment by saadeghi** [comment]
It must be fixed no in the latest version `3.2.2`  
Let me know if there are still issues

**Comment by stephanrudenko** [comment]
Works as expected, thank you! Will be in touch.
