### ISSUE TITLE
bug: poor constrast

### ISSUE THREAD

**Issue by samfundev** [saadeghi/daisyui#2152]
### What version of daisyUI are you using?

v3.2.1

### Describe your issue

Grab the background color and button component's background color and throw them into a contrast checker:
![image](https://github.com/saadeghi/daisyui/assets/6759716/fb5e6a6d-9928-4181-a375-d2b44849159a)

Seems like there are contrast tests, but they don't check base-100 and base-200. Which is what the background and button are using for their colors respectively. The button isn't the only thing this applies to, many components are using base-200 as their background color.

### Reproduction URL

https://daisyui.com/components/button/

**Comment by saadeghi** [comment]
You're comparing the background text of the button with the background text of the page. As you can see in your screenshot, the contrast tool you're using is for comparing the text color on a background color. For example, you can compare the text color of button with the background color of the button.

**Comment by samfundev** [comment]
@saadeghi The last section in the screenshot is titled "Graphical Objects and User Interface Components". The page says:
> WCAG 2.1 requires a contrast ratio of at least 3:1 for graphics and user interface components (such as form input borders).
