### ISSUE TITLE
bug: Background is White in razorpay window

### ISSUE THREAD

**Issue by sujitbalasubramanian** [saadeghi/daisyui#2167]
### What version of daisyUI are you using?

v3.2.1

### Describe your issue

The razorpay screen is transparent normally but when i add daisyui to it it turns white

Before daisyui
![2023-07-23-172247_709x769_scrot](https://github.com/saadeghi/daisyui/assets/69096629/83feff36-f45f-4efc-b43c-0b93feb991c2)

After Adding daisy ui
![2023-07-23-172036_771x790_scrot](https://github.com/saadeghi/daisyui/assets/69096629/54669e7a-eb9f-49ad-bb59-ade49f85b4bb)

I don't know how his is happening

tailwind.config.js
```js
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui"), require('tailwind-scrollbar')({ nocompatible: true })],
  daisyui: {
    themes: false,
    base: false,
  }
}

```

### What browsers are you seeing the problem on?

All browsers

**Comment by saadeghi** [comment]
with `base: false` config, it shouldn't happen.  
Can you please inspect the background and see what CSS rule is applying background color?
