### ISSUE TITLE
bug: Carousel not Working

### ISSUE THREAD

**Issue by rizki5411** [saadeghi/daisyui#2186]
### What version of daisyUI are you using?

v 3.5.0

### Describe your issue

Carousel not runing and cant swipe/slide.
![image](https://github.com/saadeghi/daisyui/assets/31713769/7b70831d-586a-4a83-bec0-697847d7c7e1)

It's also like that in the documentation.

I've copied exactly the documentation and the carousel still won't run.

**Comment by sodapng** [comment]
`Shift + Scroll Wheel`

**Comment by saadeghi** [comment]
> `Shift + Scroll Wheel`

Yes.  

Additional explanation: It's just a scrollable area, so depending on the OS you're using or your mouse settings you can scroll it horizontally the same way you do horizontal scroll any other place.

**Comment by brothanek** [comment]
@saadeghi is this really wanted behavior for standard carousel?

**Comment by farzadaqajani** [comment]
I've been trying to figure out why the carousel isn't working for hours!
**Shift + Scroll Wheel**?! Really? I don't know what the point of a carousel like this is.
