### ISSUE TITLE
Button text shouldn't be uppercase

### ISSUE THREAD

**Issue by tkrotoff** [saadeghi/daisyui#2187]
Button text shouldn't be uppercase (at least by default)

https://daisyui.com/components/button/

<img width="698" alt="image" src="https://github.com/saadeghi/daisyui/assets/643434/5188c2ea-0ec7-4b76-a2b4-dff9505ed5ad">

<br>
<br>

Google (Chrome, web), Amazon, Microsoft (Windows, web), GitHub, Apple (iOS, macOS, web), Android, Facebook, [KDE/Qt](https://doc.qt.io/qt-6/qpushbutton.html), [GNOME](https://developer.gnome.org/hig/patterns/controls/buttons.html)... don't do that

Other web UI libs don't do that: [Bootstrap](https://getbootstrap.com/docs/5.3/components/buttons/#variants), [Mantine](https://mantine.dev/core/button/), [MUI BaseUI](https://mui.com/base-ui/react-button/), [Spectrum](https://react-spectrum.adobe.com/react-spectrum/Button.html), [Chakra](https://chakra-ui.com/docs/components/button), [Ant Design](https://ant.design/components/button), [PrimeReact](https://primereact.org/button/), [Grommet](https://v2.grommet.io/button), [Bulma](https://bulma.io/documentation/elements/button/), [standard HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button)...

<br>
<br>

Without uppercase (padding should be reduced btw):

<img width="625" alt="image" src="https://github.com/saadeghi/daisyui/assets/643434/d96b41c2-8d59-4d56-acc4-5d9f9d912ff4">

<br>
<br>
<br>

Also this makes `btn-link` inconsistent with `link`:

<img width="49" alt="image" src="https://github.com/saadeghi/daisyui/assets/643434/6e467a82-bf1d-47c5-bedd-01455a2c70ba">

vs

<img width="134" alt="image" src="https://github.com/saadeghi/daisyui/assets/643434/2c464081-4fb7-4b77-879f-c9d4695fb24f">

**Comment by saadeghi** [comment]
> Other web UI libs don't do that: [Bootstrap](https://getbootstrap.com/docs/5.3/components/buttons/#variants), [Mantine](https://mantine.dev/core/button/), [MUI BaseUI](https://mui.com/base-ui/react-button/), [Spectrum](https://react-spectrum.adobe.com/react-spectrum/Button.html), [Chakra](https://chakra-ui.com/docs/components/button), [Ant Design](https://ant.design/components/button), [PrimeReact](https://primereact.org/button/), [Grommet](https://v2.grommet.io/button), [Bulma](https://bulma.io/documentation/elements/button/), [standard HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button)...

Material design has uppercase button text by default: https://m2.material.io/components/buttons
So does Material UI: https://mui.com/material-ui/react-button/

It's not uppercase in daisyUI by default. 
It is uppercase in daisyUI's built-in themes.  
But you don't have to use the built-in themes. You can customize them or you can [make your own theme](https://daisyui.com/theme-generator/) and use `"--btn-text-case": "none"` [CSS variable](https://daisyui.com/docs/themes/#-5) if you don't want uppercase text:

```js
// tailwind.config.js
module.exports = {
  plugins: [require('daisyui')],

  daisyui: {
    themes: [
      {
        light: {
          ...require("daisyui/src/theming/themes")["[data-theme=light]"],
          "--btn-text-case": "none",
        },
      },
    ],
  },
}

```

**Comment by tkrotoff** [comment]
> Material design has uppercase button text by default

[Material Design](https://en.wikipedia.org/wiki/Material_Design) **dropped** uppercase buttons: https://m3.material.io/components/all-buttons

As for [MUI](https://mui.com/material-ui/react-button/) it is based on [old Material Design v2 guidelines](https://github.com/mui/material-ui/issues/29345): new v6 will be based on Material Design v3 guidelines.
Also by the same team, [BaseUI](https://mui.com/base-ui/react-button/) and [JoyUI](https://mui.com/joy-ui/react-button/) don't have uppercase buttons.

**Comment by saadeghi** [comment]
I didn't know that.  

However I don't see any reasons to drop the uppercase for the built-in default theme.  
Some people prefer uppercase, some don't.  
Changing this variable for the built-in themes affects all the websites made by daisyUI that use the default themes and this decision is not going to be in favor of for the people who prefer uppercase by default.  

It's easy to change the CSS variable if you don't like the uppercase

**Comment by tkrotoff** [comment]
Defaults should be carefully considered: they should embody the best practices (mainly accessibility here) and not the author's personal preferences.
This is what makes the difference between a good and an excellent product.

It's not a question of "easy to change if you don't like uppercase".

<br>

Beside uppercase buttons, [borderless inputs _by default_](https://daisyui.com/components/input/#text-input) is also bad.

<img width="544" alt="image" src="https://github.com/saadeghi/daisyui/assets/643434/83e94f52-ed2b-408d-924d-0986e4d762e1">

https://coyleandrew.medium.com/form-design-best-practices-9525c321d759#5759

Others don't do that: [Bootstrap](https://getbootstrap.com/docs/5.3/forms/overview/#overview), [Mantine](https://mantine.dev/core/input/#usage), [MUI BaseUI](https://mui.com/base-ui/react-input/#introduction), [MUI JoyUI](https://mui.com/joy-ui/react-input/#introduction), [Spectrum](https://react-spectrum.adobe.com/react-spectrum/Form.html#example), [Chakra](https://chakra-ui.com/docs/components/input#usage), [Ant Design](https://ant.design/components/input#examples), [PrimeReact](https://primereact.org/inputtext/#basic), [Bulma](https://bulma.io/documentation/form/input/), [standard HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input), [Qt/KDE](https://doc.qt.io/qt-6/qlineedit.html#details), [GNOME/GTK+](https://developer.gnome.org/hig/patterns/controls/text-fields.html), [Apple](https://developer.apple.com/design/human-interface-guidelines/text-fields), [Microsoft](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/controls/textbox-overview)...

<br>

When there is a consensus you need strong reasons not to follow them.

**Comment by saadeghi** [comment]
I think I should make something clear here.  
daisyUI is the library that provides the ability to make your own theme by defining colors (and other variables)  

The built-in default themes only exist as a starting point to see how each component would look like with different colors and styles. I even made a theme generator page to encourage developers to make their own theme with custom colors and styles.

The uppercase text was not a random decision. It was already being used in Material design (used in various Google products and almost every Android)  

The advantage of uppercase is gaining more attention for the buttons and makes it more obvious that it's an ACTION BUTTON. It is loud but I don't see any downside.  

If there's a downside of having uppercase text for buttons, please let me know.

About inputs, it's important to make it obvious. It can be using borders or other design decisions. The article you mentioned is about forms. There are other ways to make an input obvious for example an icon, a placeholder text and a search button would make it obvious where is a search input. Design best practices are not absolute.

**Comment by tkrotoff** [comment]
> The article you mentioned is about forms [...] Design best practices are not absolute

Don't miss the part where Google discover after a 4 months study and over 600 participants that fields should have a "rectangular (box) shape"

<br>

This is DaisyUI default field:

<img width="428" alt="image" src="https://github.com/saadeghi/daisyui/assets/643434/212e0662-04be-4fcd-b92e-0f0deef956a7">

<br>
<br>

<img width="883" alt="image" src="https://github.com/saadeghi/daisyui/assets/643434/5c2d5786-0218-4771-8529-88f8e0c390cc">

<br>
<br>


And users thinking "it's the default way so it must be the best way!"

Don't get me wrong: I love DaisyUI, its approach and the great work you put in it. I just think it could be better thx to sensible defaults.

**Comment by saadeghi** [comment]
> And users thinking "it's the default way so it must be the best way!"

That wouldn't be a correct. The default is the bare minimum style of a component which can be modifier with modifier class names or Tailwind's utility classes.  

It makes more sense if the default is without border and we use a modifier class name to add something (border) to it, that using a modifier class name to remove something from it.

**Comment by tkrotoff** [comment]
> If there's a downside of having uppercase text for buttons, please let me know

https://material.angular.io/components/button/overview#capitalization

_"[capitalizing] buttons [...] can cause issues in certain locales. [Also] using ALL CAPS in the text itself causes issues for screen-readers, which will read the text character-by-character"_

<br>
<br>

<sup>when they say _"According to the Material design spec"_ they are referring to the old spec - v2 instead of v3</sup>

**Comment by tkrotoff** [comment]
> I need more info

Couldn't find any details

Found this interesting comment that recaps all issues with ALL CAPS:
https://github.com/humanmade/hm-pattern-library/issues/75#issuecomment-235672885

Found this in Angular Material repo (nothing new :-/):
- https://github.com/angular/components/issues/4821 (https://github.com/angular/components/pull/4829)
- https://github.com/angular/components/issues/4496
- https://github.com/angular/components/pull/4567

**Comment by tkrotoff** [comment]
> It makes more sense if the default is without border and we use a modifier class name to add something (border)

From a technical point of vue, yes it feels satisfying and clean. However not from the user (accessibility) point of vue given the Google study.
So I would do this opposite (even if it's better from a technical point of vue to avoid negation):

```JSX
<input class="input" /> // Bordered by default
<input class="input-borderless" />

<textarea class="textarea"></textarea> // Bordered by default
<textarea class="textarea-borderless"></textarea>

<select class="select"></select> // Bordered by default
<select class="select-borderless"></select>
```

**Comment by tkrotoff** [comment]
Since Daisy v4.0.0, buttons are not uppercase by default: https://github.com/saadeghi/daisyui/commit/81d1748da8588e495d03291097be891da722893f#diff-8528536c6fcdde4b2cbf719245958793cf703a7f3e320680b8cac1d59b4702a3L5

Since Daisy v5.0.0, input comes with a border by default: https://github.com/saadeghi/daisyui/pull/3484

Thanks for the changes
