### ISSUE TITLE
bug: loading components not working with mac chrome + remix

### ISSUE THREAD

**Issue by xendarboh** [saadeghi/daisyui#2193]
### What version of daisyUI are you using?

3.5.0

### Describe your issue

In chrome browser on mac os and using daisyui within a basic install of [Tailwind CSS with Remix](https://tailwindcss.com/docs/guides/remix), all of the [loading components](https://daisyui.com/components/loading/) display as a solid colored box.

Works as expected in all other browsers tested including Mac safari/firefox and Linux chrome/brave/firefox. The loading components in daisyui docs display as expected as well (in mac chrome), and other icons are fine (like collapse arrow), so seems to be something within the tailwind+remix+daisyui setup.

Also, an animated SVG [like this](https://github.com/SamHerbert/SVG-Loaders/blob/master/svg-loaders/puff.svg?short_path=288de9e) for example works fine.

### What browsers are you seeing the problem on?

Chrome

**Comment by AhmedNawaf** [comment]
I'm using Remix and so far I've used Loading and Rating components.
I'm still facing this issue that caused these components to display a box only

**Comment by saadeghi** [comment]
Please provide a reproduction repo because I don't see this issue with the latest version of daisyUI.

**Comment by AhmedNawaf** [comment]
Someone helped me with this issue.
It turned out you need postcss + autoprefixer to make the icons work correctly.
Follow tailwind setup for a react project then follow [this](https://remix.run/docs/en/1.19.1/guides/styling#postcss).
It should work after that.

**Comment by xendarboh** [comment]
Thanks! That was it, postcss + autoprefixer was required for remix+tailwindcss+daisyui on mac chrome.
The components now display as expected. (and they're great!)
Closing issue.
