### ISSUE TITLE
bug: Chat bubbles in Safari (macOS/iOS)

### ISSUE THREAD

**Issue by dmythro** [saadeghi/daisyui#2199]
### What version of daisyUI are you using?

latest (website)

### Describe your issue

Chat bubbles have this vertical divider between the tail and main bubble body:

![image](https://github.com/saadeghi/daisyui/assets/1391015/aaaafac6-169d-435c-960e-dde03b3c005a)

On iOS it's more subtle, but still there. Especially with zoom.

In Chrome it looks good.

Also, is there an option to have this tail off?
Like in iMessage, the chat bubble tail is only shown on the last message.

### What browsers are you seeing the problem on?

Safari, Safari iOS

### Reproduction URL

https://daisyui.com/components/chat/

**Comment by NikarashiHatsu** [comment]
Didn't occur on my device, but there's definitely a slight divider while resizing.

https://github.com/saadeghi/daisyui/assets/43662951/5445bf6b-0048-4112-a7b3-78d151ca55c7

**Comment by dmythro** [comment]
Re-checked, looks like I have a clarification: it is an issue on external display in Safari only, and when zooming in. So, priority I guess is probably minor. A lot of devs use external displays with Macs though. Hope it helps!

**Comment by NikarashiHatsu** [comment]
There should be a better alternative such as using clip properties which I'm pretty sure would fix the issue. I'll try to reproduce this on my local machine, and if that works' I'll do a PR to fix this issue.
