### ISSUE TITLE
Contribute to the docs

### ISSUE THREAD

**Issue by florian-lefebvre** [saadeghi/daisyui#22]
Hi, awesome work with Daisy UI @saadeghi !
I would like to contribute to the docs but couldn't find any repo. Maybe you could make it open source ?

**Comment by saadeghi** [comment]
Thanks @florian-lefebvre 
The docs repo is here: https://github.com/saadeghi/daisyui-demo

Please let me know if you have any questions.

**Comment by florian-lefebvre** [comment]
Oh thank you! I didn't see it :)
