### ISSUE TITLE
Use Navbar inside the Draw, it should not work well

### ISSUE THREAD

**Issue by CheezeLab** [saadeghi/daisyui#220]
Hi
Using Daisyui, I have a question during development.

Making the page, put Navbar component in a Drawer.
Navbar placed on top of the page,
contents in the middle,
footer placed below.

There is no problem on the desktop browser,
But on the mobile, there is a problem with scrolling.

I developed page is same homepage operation,
I recorded homapage screen scrolling.
The main page without the Drawer is not a problem with scrolling and shown contents.

In the page (introduce components) with the Drawer,
scrolling end of the page, the last contents are not visible.
(perhaps there is wrapped in a Drawer),  pull more the contents are shown.
However, the top Navbar goes out of the area.
At this time, when scrolling up, the Navbar is not displayed properly, and it will be seen again when you go down.

On the general page, when you scroll, the address area of browser and bottom area of browser are reduced.
And when it is scroll to the end, the area become larger again.
But, there is no change on the using Drawer page. (I think it seems to be scrolling in the Drawer's inside)

Below is a recording image.
(I am using the iPhone. Likewise, it is same for Android.)
I can not speak English well, it's hard to understand but I will contact you here for the solution.
Thank you.

[https://youtu.be/R3TcuheQs-M](https://youtu.be/R3TcuheQs-M)
[https://youtu.be/bYaHQBbK7Tg](https://youtu.be/bYaHQBbK7Tg) (my project)

**Comment by saadeghi** [comment]
@CheezeLab Seems like it's a known bug on iOS safari when `sticky` element is inside a scrollable `fixed` element.  
Fortunately the new iOS safari (iOS 15) doesn't have this bug.
A workaround I found is this:

> Don't use `sticky` class for navbar, instead use `fixed top-0` for navbar and then and put the whole navbar inside a `<div class="h-16">` (so the fixed navbar won't go on the content).

example: https://play.tailwindcss.com/BAKdAgjbjR

Please let me know if you have any questions.

**Comment by CheezeLab** [comment]
As you pointed out, I was in that situation. I am using ios 14.7 (I need to upgrade ios soon)
And I used sticky in navbar.

I will refer to the code you provided.
daisyui is great. Thank you very much. :)
