### ISSUE TITLE
bug: Incompatibility with the plugin "tailwindcss-forms".

### ISSUE THREAD

**Issue by iamcarlos94** [saadeghi/daisyui#2202]
### What version of daisyUI are you using?

3.5.0

### Describe your issue

When using Tailwind's official plugin, [@tailwindcss/forms](https://github.com/tailwindlabs/tailwindcss-forms), form inputs don't look right.

Radio input with [daisyUI's fantasy theme](https://daisyui.com/components/radio/) and the mentioned plugin:
![image](https://github.com/saadeghi/daisyui/assets/62184065/b2158970-fbb2-4751-b1f3-c8ae4c36589b)

Without the plugin:
![image](https://github.com/saadeghi/daisyui/assets/62184065/7530295f-ec7e-48d3-a198-a09f636c89d7)

### What browsers are you seeing the problem on?

Firefox

**Comment by saadeghi** [comment]
Read this https://github.com/saadeghi/daisyui/issues/1431#issuecomment-1347822839
