### ISSUE TITLE
bug: Anchor tag (Link tag on Next.js) inside details element on navbar not working on every browser in iOS

### ISSUE THREAD

**Issue by KiddoKidz** [saadeghi/daisyui#2203]
### What version of daisyUI are you using?

v3.5.0

### Describe your issue

When clicking the Anchor tag (Link tag on Next.js) inside details element on navbar, it didn’t redirecting to the given route so that the page also not changing according to the given route.

At first, I think that this issue is related to Next.js framework. But, after I tried to reproduce the bug without daisyui installed, Anchor tag (Link tag) inside details element works as intended. So, I assumed it should be the daisyui that caused the bug.

I've 2 reproduction URL, the one with daisyui and the other without daisyui.

With daisyui:
URL: https://my-app-nextjs-nnijqdeio-kiddokidz.vercel.app/
Repository: https://github.com/KiddoKidz/my-app-nextjs

Without daisyui:
URL:https://reproduction-app-navbar-rmticl6m9-kiddokidz.vercel.app/
Repository: https://github.com/KiddoKidz/reproduction-app-navbar

Here is the video:

https://github.com/saadeghi/daisyui/assets/44206909/8939d22d-212b-420e-86dd-dac68b3ad2cb

### What browsers are you seeing the problem on?

Safari iOS

### Reproduction URL

https://my-app-nextjs-nnijqdeio-kiddokidz.vercel.app/

**Comment by NikarashiHatsu** [comment]
+1, Tested on MacOS Safari (responsive version), it also seems to fail.


https://github.com/saadeghi/daisyui/assets/43662951/164c802b-925c-4604-b92d-32beb97c120c

**Comment by NikarashiHatsu** [comment]
Update, on your `components/navbar.tsx@generateNavBarItem:77`, add `tabIndex={0}` to the `<details>` element.

```tsx
<details tabIndex={0}>
  <summary className="menu-summary">{navBarItem.name}</summary>
  ...
</details>
```

https://github.com/saadeghi/daisyui/assets/43662951/2b8bceab-b689-4d87-87de-d8f3f754bad9

It should be working as intended.
Safari has [this](https://bugs.webkit.org/show_bug.cgi?id=22261) weird behavior that they simply `Won't fix`.

**Comment by KiddoKidz** [comment]
I've tested the solution given by @NikarashiHatsu  and it worked! I spent a lot of time to debug the issue but I was never thinking about adding `tabIndex` attribute into the `<details>` element. 

Thanks a lot!
