### ISSUE TITLE
Suggestion: SnackBar component

### ISSUE THREAD

**Issue by kaname-png** [saadeghi/daisyui#221]
I see daisyUI doesn't have snackbar component, it would be great if it did.

**Comment by saadeghi** [comment]
@kaname-png Yes, this is in my to-do list but with "toast" name.  
I believe a "toast" and a "snackbar" is the same thing. Right?

**Comment by kaname-png** [comment]
@saadeghi Yes, they are the same. I hope you can implement it!

**Comment by priyang12** [comment]
hi, can I work on this????

**Comment by saadeghi** [comment]
@priyang12 sure. let me know if I can help

**Comment by priyang12** [comment]
@saadeghi hi I have cloned the repo and installed the packages and went to src/docs and installed the packages and run the development by yarn run dev. it is giving some import error

<img width="1225" alt="Screenshot 2022-01-28 at 10 20 13 PM" src="https://user-images.githubusercontent.com/72823974/151588034-4e74b481-3554-49da-b44f-fc31b7b24b94.png">

do I need to change some imports in components postcss config file ???
<img width="476" alt="Screenshot 2022-01-28 at 10 21 58 PM" src="https://user-images.githubusercontent.com/72823974/151588318-5e83e6ba-9906-4653-9ae0-605165d4ba1a.png">

**Comment by saadeghi** [comment]
@priyang12 make sure you build the daisyUI node package first: 
 https://github.com/saadeghi/daisyui/blob/master/.github/CONTRIBUTING.md#building-on-local

**Comment by cryptodeal** [comment]
Recently switched to using DaisyUI with SvelteKit and was looking to replace a svelte toast library with a custom store/DaisyUI implementation of toast notifications. I've forked the repository and built a working component consistent with your vision of the toast component & accompanying wrapper by largely imitating the styles of the Alert component.

If you can assign this to me, I'll gladly submit a PR with the changes as I'd likely need help with the animations, to clean up styles. 

https://user-images.githubusercontent.com/39316528/174497938-8669ee80-c9ca-4886-b9f5-dfd08ccc3e8f.mp4

**Comment by saadeghi** [comment]
We can close this issue now that we have [`toast` component](https://daisyui.com/components/toast/) (added in daisyUI `2.19.0`) thanks to @cryptodeal
