### ISSUE TITLE
bug: unsupported-css-nesting

### ISSUE THREAD

**Issue by RAK-MANIAK** [saadeghi/daisyui#2210]
### What version of daisyUI are you using?

v3.2.1

### Describe your issue

# When I use vite build I get these warnings
`warnings when minifying css:
▲ [WARNING] CSS nesting syntax is not supported in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14") [unsupported-css-nesting]

    <stdin>:917:35:
      917 │ ...lapse:not(.collapse-close):has(> input[type="checkbox"]:checked),
          ╵                                   ^

▲ [WARNING] CSS nesting syntax is not supported in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14") [unsupported-css-nesting]

    <stdin>:918:35:
      918 │ .collapse:not(.collapse-close):has(> input[type="radio"]:checked) {
          ╵                                    ^

▲ [WARNING] CSS nesting syntax is not supported in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14") [unsupported-css-nesting]

    <stdin>:1692:14:
      1692 │ .collapse:has(> input[type="checkbox"]:focus-visible),
           ╵               ^

▲ [WARNING] CSS nesting syntax is not supported in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14") [unsupported-css-nesting]

    <stdin>:1693:14:
      1693 │ .collapse:has(> input[type="radio"]:focus-visible) {
           ╵               ^
`

# My postcss.config.js file
`import postcssImport from 'postcss-import';
import tailwindcssNesting from '@tailwindcss/nesting';
import postcssNesting from 'postcss-nesting';
import tailwindcss from 'tailwindcss';
import autoprefixer from 'autoprefixer';

export default {
  plugins: [
    postcssImport,
    tailwindcssNesting(postcssNesting),
    postcssNesting,
    tailwindcss,
    autoprefixer,
  ],
};
`

**Comment by NikarashiHatsu** [comment]
Is there any specific reason on why to use `postcss-nesting` and `@tailwindcss/nesting`?
Apparently it work really well without them being used.
