### ISSUE TITLE
docs:  Bottom swap example does not work on my machine / browser.

### ISSUE THREAD

**Issue by luckynumberke7in** [saadeghi/daisyui#2215]
### On which page do you see this issue?

https://daisyui.com/components/swap/

### Describe the issue

The bottom example of swap (2 emoji's) does nothing on my browser. 

I use firefox and dark reader, I disable dark reader (which I sometimes have to do in order to see daisyui elements). However, with this particular example, after disabling / reloading page nothing happens in this example's swap. I then tried this example in chromium as well, still does not work.

### What browsers are you seeing the problem on?

Firefox, Other

**Comment by abhishekrawat22** [comment]
@luckynumberke7in  It will not do anything unless you add or remove *swap-active* class from the two icon labels respectively. The mentioned example is to swap icon on the basis of activating using the class name and not the checkbox.
You can compare the last two examples by their code.
