### ISSUE TITLE
bug: Applying to child selector doesn't work

### ISSUE THREAD

**Issue by joshcho** [saadeghi/daisyui#2218]
### What version of daisyUI are you using?

3.5.1

### Describe your issue

Applying [&>*]:bg-base-200 doesn't work. I am not sure if I have to change some things in my settings, but searched through issues and couldn't find anything. I haven't changed anything in my settings (so by default utility classes should be on).

**Comment by saadeghi** [comment]
Which component? Can you provide a code example?
