### ISSUE TITLE
bug: NavBar not use the correct color when apply `bg-base-300`

### ISSUE THREAD

**Issue by mamcx** [saadeghi/daisyui#2233]
### What version of daisyUI are you using?

3.5.0

### Describe your issue

Before in the `2.x` version I could style the `navbar` with `<nav class="navbar border-base-100 bg-base-300 p-4 shadow">`

But now, the color is totally different. Weirdly, with `bg-base-100` it works.

Config:

```js
module.exports = {
  plugins: [
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {        
          dark: {
            ...require("daisyui/src/theming/themes")["[data-theme=dark]"],
             primary: "#38bdf8",
             secondary: "#d1fae5",
             accent: "#1FB2A6",
             neutral: "#191D24",
             "base-100": "#064e3b",
             "base_200": "#242933",
             "base_300": "#053e2e",
             "base_content": "#A6ADBB",
             info: "#3ABFF8",
             success: "#4f46e5",
             warning: "#fcd34d",
             error: "#b91c1c",
             '--toolbar': '28 25 23',
          },
      },
    ],
  },
}
```

Code:

```html
<nav class="navbar border-base-100 bg-base-300 p-4 shadow">
  <div class="navbar-start">
    <figure class="block h-8 w-16">
      <a href="/admin" class="inline"> AA </a>
    </figure>
  </div>
  </nav>
```

### What browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://play.tailwindcss.com/kou6Fg8CLP

**Comment by NikarashiHatsu** [comment]
What do you mean? `bg-base-300` and `bg-base-200` has a slight different color. Your reproduction URL also works fine. It is `#e5e6e6` for `bg-base-300` and `#f2f2f2` for `bg-base-200`.

What color code did you expect it to work?

**Comment by mamcx** [comment]
> e5e6e6

Exactly, this is NOT the color. The config says:

```json
	neutral: "#191D24",
	"base-100": "#064e3b",
	"base_200": "#242933",
	"base_300": "#053e2e",
```

Note that if you change it to `"base_300": "red",` is easier to spot that the bar have not the expected color

**Comment by saadeghi** [comment]
You're using underscore for `base_200` `base_300` and `base_content` they all will be ignored and their values will be generated automatically. Use dash `-`. Not underscore `_`

Let me know if you have any questions
