### ISSUE TITLE
margins are missing in next.js production for daisyUI Navbar center menu list items

### ISSUE THREAD

**Issue by Prudhvi3216** [saadeghi/daisyui#2243]
### What version of daisyUI are you using?

3.5.1

### Describe your issue

I'm using https://daisyui.com/components/navbar/#responsive (dropdown menu on small screen, center menu on large screen) component. The margins are missing for `<li></li>` element in this `<ul className="menu menu-horizontal px-1"> ... </ul>.` I inspected chrom dev tools to look for what css portion was missing in both local and production env's. I found that 
```
 ul {
    display: block;
    list-style-type: disc;
    margin-block-start: 1em;
    margin-block-end: 1em;
    margin-inline-start: 0px;
    margin-inline-end: 0px;
    padding-inline-start: 40px;
}
```
 this code is not in production and it's a user agent style sheet. 

my app congif 
```
"devDependencies": {
    "autoprefixer": "^10.4.13",
    "daisyui": "^3.5.1",
    "jest": "^29.6.1",
    "postcss": "^8.4.21",
    "tailwindcss": "^3.3.3"
  }
```
First i thought it was cache but I deployed the code in vercel thrice but same issue. 
production url : https://core-pioneers.vercel.app/

### Local browser css for the app.
![issue](https://github.com/saadeghi/daisyui/assets/25653002/caf5ea45-3a46-4c5f-a82a-21bd2b46ca0b)
### Issue
![Screenshot from 2023-08-11 18-07-22](https://github.com/saadeghi/daisyui/assets/25653002/8554d132-9419-4848-9110-5d4a84ada5a1)

### What browsers are you seeing the problem on?

Chrome, Firefox, Edge, Chrome Android

### Reproduction URL

https://play.tailwindcss.com/RmxFs85xxk

**Comment by saadeghi** [comment]
Some styles are missing.  
Make sure you're using the latest version. the version in package.json may not be the same as installed package.
- run `npm i -D daisyui@latest` to install the latest daisyUI version
- run `npm i next@latest` to install the latest version of Next.js

If this didn't help, I would need a minimal reproduction repo so I can run the code and see what's the issue.

**Comment by Prudhvi3216** [comment]
I updated next.js to latest version 13.2 to 13.4.13 (latest) now, magically it worked. Maybe it's the issue with next.js i think. Thanks @saadeghi for quick help.

**Comment by saadeghi** [comment]
Yes. Sometimes there are bugs in the frameworks about processing the CSS but it usually gets fixed in later versions. Updating the dependencies to the latest version would save a lot of time ✌️
