### ISSUE TITLE
bug: Object.hasOwn is not a function

### ISSUE THREAD

**Issue by gottedev** [saadeghi/daisyui#2247]
### Describe your issue

I am getting Object.hasOwn is not a function and the directory the error pointing towards is /node_modules/daisyui/src/theming/functions.js:73:19

I am using daisy ui for a new project here are my dependencies:
  "dependencies": {
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.40",
    "@types/react": "^18.2.20",
    "@types/react-dom": "^18.2.7",
    "object.hasown": "^1.1.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.9.5",
    "web-vitals": "^2.1.4"
  },
  
  "devDependencies": {
    "daisyui": "^3.5.1",
    "tailwindcss": "^3.3.3"
  }
  
 ###Update:
 
 I was able to solve this issue for my project by using an older version of Daisy UI: ^2.6.0

**Comment by saadeghi** [comment]
Update the Node.js

**Comment by gottedev** [comment]
Thank you
