### ISSUE TITLE
Interacting with carousel component with mouse

### ISSUE THREAD

**Issue by Pankai222** [saadeghi/daisyui#226]
Hey, 

The carousel works fine when using swipe interaction on mobile devices, but all functionality is lost when using a mouse. 
Is carousel functionality not supported on desktop, or is there something I'm missing?

**Comment by saadeghi** [comment]
@Pankai222 It's just vertical scroll and it can be used with touchpad or mouse scroll. It's not a JavaScript carousel so don't expect dragging functionality with mouse.

Please let me know if you have any questions
