### ISSUE TITLE
docs: How to close modal via js

### ISSUE THREAD

**Issue by jeffery-zhang** [saadeghi/daisyui#2261]
### On which page do you see this issue?

https://daisyui.com/components/modal/#

### Describe the issue

Hi,
I'm using method 1 to open the modal with openModal function:
```js
window.my_modal.openModal()
```
How can I close this modal using the same method

**Comment by itsanishjain** [comment]
Are you using React or Nextjs?

**Comment by shunwatai** [comment]
same question, I'm using react.
after opened the modal, I have a button with an async onClick function, after doing my stuffs, what method should i call to close the modal?
I have tried the `window.my_modal.hideModal()` & `window.my_modal.closeModal()` both undefined...
I have also try set the `window.my_modal.open = false`, but also no work as expected.

**Comment by shunwatai** [comment]
> same question, I'm using react. after opened the modal, I have a button with an async onClick function, after doing my stuffs, what method should i call to close the modal? I have tried the `window.my_modal.hideModal()` & `window.my_modal.closeModal()` both undefined... I have also try set the `window.my_modal.open = false`, but also not work as expected.

After trails and errors, I found that simply run `window.my_modal.close()` can close the modal.

**Comment by shunwatai** [comment]
> ### On which page do you see this issue?
> 
> https://daisyui.com/components/modal/#
> ### Describe the issue
> 
> Hi, I'm using method 1 to open the modal with openModal function:
> 
> ```js
> window.my_modal.openModal()
> ```
> 
> How can I close this modal using the same method
> ### What browsers are you seeing the problem on?
> 
> _No response_

After trails and errors, I found that simply run window.my_modal.close() can close the modal.
