### ISSUE TITLE
bug: tables are not responsive when using drawer

### ISSUE THREAD

**Issue by durosly** [saadeghi/daisyui#2262]
### What version of daisyUI are you using?

3.1.9

### Describe your issue

Tables are not responsive with the overflow-x-auto container. When I changed the drawer display from grid to block, it worked just fine

### What browsers are you seeing the problem on?

I tried it on both google chrome and Firefox. Same issue

**Comment by stepollo2** [comment]
I have the same problem using latest daisyUI version, as a temporary solution you can add overflow-x-auto to drawer-content.
Source https://github.com/saadeghi/daisyui/issues/1914

**Comment by durosly** [comment]
That would add a scroll-bar to the drawer-content

**Comment by timB73** [comment]
When I do overflow-x-auto on drawer-content it doesn't seem to have any effect, the scrollbar is still across the entire page, not just drawer-content. It seems the issue is with the way the grid is setup, the only way I could get it to work was to do (320px is the sidebar width):

```
  .drawer {
    grid-template-columns: 320px calc(100% - 320px);
  }

  @media (max-width: 1200px) {
    .drawer {
      grid-template-columns: 0px 100%;
    }
  }
```
