### ISSUE TITLE
bug: DaisyUI message appearing twice

### ISSUE THREAD

**Issue by Vrajs16** [saadeghi/daisyui#2267]
### What version of daisyUI are you using?

3.5.1

### Describe your issue

When running npm run dev for an application built with sveltekit using daisyui, the following message appears twice.
<img width="695" alt="image" src="https://github.com/saadeghi/daisyui/assets/89588024/c9088387-4bcd-4c59-85e0-682abea0082e">

Is it possible to to remove this message all together or reduce it down to 1?

### What browsers are you seeing the problem on?

Not a browser, terminal

**Comment by itsanishjain** [comment]
Can you also add your tailwind config file too?

**Comment by itsanishjain** [comment]
Please read this
https://github.com/saadeghi/daisyui/discussions/1949

**Comment by Vrajs16** [comment]
> Please read this
> 
> https://github.com/saadeghi/daisyui/discussions/1949

Ok I will disable the message from the config. Thanks
