### ISSUE TITLE
bug: Colors are not working with  "daisyui": "^3.0.3",

### ISSUE THREAD

**Issue by itsanishjain** [saadeghi/daisyui#2268]
### What version of daisyUI are you using?

^3.0.3

### Describe your issue

When attempting to use the base color, at least as far as I understand, with the 'bg' prefix, it doesn't seem to work. For instance:

```
<div className="bg-base-300 md:col-span-2 flex justify-center">
  <Image src="/img.png" alt="img" width={600} height={600} />
</div>
```

In version 3, this color doesn't work as intended. However, in older versions like `"daisyui": "^2.50.0"`, it works as expected."

### What browsers are you seeing the problem on?

All browsers, Chrome

**Comment by saadeghi** [comment]
There's no such problem with the package now: https://play.tailwindcss.com/5QHDyG4WHZ   
If it's not working in your project, please provide a minimal reproduction link so we can run the project and see the issue.

**Comment by itsanishjain** [comment]
Hey @saadeghi 
here
https://codesandbox.io/p/github/itsanishjain/daisyuiTest/

**Comment by saadeghi** [comment]
Install the latest version of Tailwind CSS
```
npm i -D tailwindcss@latest
```
