### ISSUE TITLE
Style conflicts with @tailwindcss/forms plugin

### ISSUE THREAD

**Issue by Amar-Gill** [saadeghi/daisyui#227]
I am trying to use the [radio btn group example](https://daisyui.com/components/button-group) from the documentation.

I noticed the styles are off in my vue3 + vite app. A fix was to remove `@tailwindcss/forms` plugin. Is that plugin intended to be used with a component library plugin like Daisy UI? If not then I suppose I answered my own question and we can close this issue.

I included a github repo for a reproduction. There are instructions and a screenshot to show you what is happening. Just run `npm run dev` and open the app in your browser.

https://github.com/Amar-Gill/daisyui-btngroup-repro

ps. love the component library so far. great work :)

**Comment by saadeghi** [comment]
@Amar-Gill well... both plugins are doing the same job with form elements, So I don't think you will need both at the same time 😅

**Comment by Amar-Gill** [comment]
ok understood! thx for clarifying =p

**Comment by CapitaineToinon** [comment]
Just had the same issue. I know it seems obvious now that I removed the plugin but maybe just put that information somewhere in the doc because I assume a lot of people are going to use daisyui like me, aka added it to an existing Tailwind project with the official forms plugin already installed.
