### ISSUE TITLE
Arbitrary variants doesn't work

### ISSUE THREAD

**Issue by mirismaili** [saadeghi/daisyui#2274]
### What version of daisyUI are you using?

v3.5.1

### Describe your issue

According to my tests, [arbitrary variants](https://tailwindcss.com/docs/hover-focus-and-other-states#using-arbitrary-variants) doesn't work for daisyui classes. This is an example:
```jsx
<label className="swap-rotate swap [@media(prefers-color-scheme:dark)]:swap-active [@media(prefers-color-scheme:dark)]:bg-red-600">
```
And as you can see:
![image](https://github.com/saadeghi/daisyui/assets/15800189/ce6ca080-5894-475b-bc9c-4e7c49fa8444)
`[@media(prefers-color-scheme:dark)]:bg-red-600"` works, but `[@media(prefers-color-scheme:dark)]:swap-active` doesn't work.

### What browsers are you seeing the problem on?

Chrome Version 115.0.5790.171 (Official Build) (64-bit)

**Comment by saadeghi** [comment]
Fixed in `3.6.2`
