### ISSUE TITLE
Will using this library bloat my app?

### ISSUE THREAD

**Issue by adriandelgg** [saadeghi/daisyui#228]
Hi, I know that Tailwind CSS purges unused classes in production so that your app only uses what it actually needs.

If I use this library, will Tailwind do the same thing and remove all unused classes & components from their package installation?

**Comment by saadeghi** [comment]
@adriandelgg Yes, if you [use daisyUI as a plugin for Tailwind](https://daisyui.com/docs/install), unused class names from both Tailwind and daisyUI will be purged.

Please let me know if you have any questions.

**Comment by adriandelgg** [comment]
Awesome! Thank you for the quick response. 

So say for example I download this library & only use the `input` class. Every single other class this package downloaded will be purged and only the `input` class will be in production?

**Comment by saadeghi** [comment]
@adriandelgg I would say more than 99% of all other styles will be purged. A few unused rules won't be purged because of default purge config.
