### ISSUE TITLE
docs: code and command-line example text cannot be copied

### ISSUE THREAD

**Issue by jestrickler** [saadeghi/daisyui#2282]
### Describe the issue

The code and command-line example text cannot be selected to be copied, and there is not a copy button as there is on the github installation docs. It would be great for convenience if the code and command-line example text could be copied.

### What browsers are you seeing the problem on?

Chrome

**Comment by jestrickler** [comment]
Ok, nevermind, now I can seem to copy text. Maybe something going on with my browser...

**Comment by jestrickler** [comment]
I figured out what it is. You can't see that you've selected text with the 'light' theme.

**Comment by saadeghi** [comment]
Fixed the colors. Thank you
