### ISSUE TITLE
bug: Not close the sidebar dropdown

### ISSUE THREAD

**Issue by marcelloinfoweb** [saadeghi/daisyui#2288]
### What version of daisyUI are you using?

3.6.1

### Describe your issue

It is not possible to close the sidebar dropdown when clicked and even when it loses focus. I'm using Nuxt 3 in SPA mode.

```html
<details class="dropdown">
  <summary>Contas</summary>
  <ul class="menu dropdown-content">
    <li>
      <NuxtLink onclick="document.activeElement.blur()"
        >Pagar</NuxtLink
      >
    </li>
    <li>
      <NuxtLink onclick="document.activeElement.blur()"
        >Receber</NuxtLink
      >
    </li>
  </ul>
</details>
```

### What browsers are you seeing the problem on?

Edge

### Reproduction URL

https://play.tailwindcss.com/hZauBl2l2n?size=672x720

**Comment by saadeghi** [comment]
From the [docs](https://daisyui.com/components/dropdown/#method-1-using-details-and-summary-tags):  
>Stays open until gets clicked again. Or you can close it using JS by removing the `open` attribute

Learn more about the HTML `<details>` tag:  
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

Let me know if you have any questions

**Comment by marcelloinfoweb** [comment]
No problem, thank you.

I switched to [Preline](https://preline.co/index.html), it already does that and stuff.

**Comment by saadeghi** [comment]
daisyUI `dropdown` can also get closed when losing focus.  
There are 2 methods as explained on the docs: https://daisyui.com/components/dropdown/

You used `<details>` tag and HTML `<details>` tag works this way. It opens with first click and closes with second click.  
You could use the second method which closes when losing focus:  
https://daisyui.com/components/dropdown/#method-2-using-label-and-css-focus

**Comment by saadeghi** [comment]
@eagor You can use `document.activeElement.blur()` to programmatically close the dropdown since it's working with CSS `focus`

**Comment by jamaluddinrumi** [comment]
> No problem, thank you.
> 
> I switched to [Preline](https://preline.co/index.html), it already does that and stuff.

just knowing that daisyui-alternative is exist. 

i like that, but i'm still prefer daisyui because it doesn't require javascript much.

**Comment by marcelloinfoweb** [comment]
> > No problem, thank you.
> > I switched to [Preline](https://preline.co/index.html), it already does that and stuff.
> 
> just knowing that daisyui-alternative is exist.
> 
> i like that, but i'm still prefer daisyui because it doesn't require javascript much.

Yes, it is necessary, but it is up to the user.

**Comment by jamaluddinrumi** [comment]
> > > No problem, thank you.
> > > I switched to [Preline](https://preline.co/index.html), it already does that and stuff.
> > 
> > 
> > just knowing that daisyui-alternative is exist.
> > i like that, but i'm still prefer daisyui because it doesn't require javascript much.
> 
> Yes, it is necessary, but it is up to the user.

yup, i agree, user is the most important.
