### ISSUE TITLE
Package broke background colors on my app

### ISSUE THREAD

**Issue by adriandelgg** [saadeghi/daisyui#229]
When I installed the package and added it as a plugin to my tailwind config file, it caused my background to be different colors and also changed the color of the text. I don't know why it broke

**Comment by saadeghi** [comment]
@adriandelgg it's the default theme color. You can [disable the `base` config](https://daisyui.com/docs/config) if you don't want that.  
Read more about [themes](https://daisyui.com/docs/default-themes) and [colors](https://daisyui.com/core/colors)  

Please let me know if you have any questions
