### ISSUE TITLE
bug: the checkbox on Windows and Android devices does not display a check mark inside

### ISSUE THREAD

**Issue by stephanrudenko** [saadeghi/daisyui#2291]
### What version of daisyUI are you using?

v3.6.1

### Describe your issue

While continuing to work on the same project, I encountered a new bug in the component https://daisyui.com/components/checkbox/.
In the checked state, the element is completely filled with color and there is no indicator inside (check mark i guess?):
<img width="960" alt="image" src="https://github.com/saadeghi/daisyui/assets/87760767/887bd187-6d27-4b3c-afd8-4d6d65108999"> (Windows 11 Home, Chrome 116.0.5845.97)

Same thing on Edge (v116.0.1938.54):
<img width="919" alt="image" src="https://github.com/saadeghi/daisyui/assets/87760767/0df6d133-2c7f-4c35-9472-25fbed870627">

Unchecked just white, thats ok:
<img width="960" alt="image" src="https://github.com/saadeghi/daisyui/assets/87760767/d372842c-d4e2-40e2-904e-c465bd6cf388">

Also we have the same issue on the Android device (Xiaomi Browser):
![image](https://github.com/saadeghi/daisyui/assets/87760767/587bef4b-a01d-447f-959a-66a9090a7fc1)
![image](https://github.com/saadeghi/daisyui/assets/87760767/80ed98e0-f108-4aaf-9e8a-7a6803f66793)

But the same time iOS 16.6 (iPhone 13) Safari and Chrome works absolutly fine:
![image](https://github.com/saadeghi/daisyui/assets/87760767/6ac22cc7-ff56-481f-8e50-b5c2f5ccb467)
![image](https://github.com/saadeghi/daisyui/assets/87760767/c8d95935-402b-47c6-9660-ea3248fe826e)

// code were used
`<div className="form-control">
              <label className="label cursor-pointer">
                <span className="label-text">
                  I have read the terms and conditions and agree to the sale of
                  my personal information to the highest bidder.
                </span>
                <input type="checkbox" defaultChecked className="checkbox" />
              </label>
            </div>`

// upd
Android Chrome also reproduces

### What browsers are you seeing the problem on?

Chrome, Edge, Chrome Android, Other

**Comment by saadeghi** [comment]
- Are you using any other library or plugin that may apply styles to form elements? For example `@tailwindcss/forms`
- Do you have any other CSS code in your project that may affect checkboxes?
- Do you see the same issue on daisyUI website or [here](https://play.tailwindcss.com/KUX2ik7WBm)?

**Comment by stephanrudenko** [comment]
1. no
2. looks like i found a root of a problem: 

// globals.css
`
@tailwind base;
@tailwind components;
@tailwind utilities;

@supports (-webkit-overflow-scrolling: touch) {
  body * {
    background-attachment: scroll;
  }
}

@supports not (-webkit-overflow-scrolling: touch) {
  body * {
    background-attachment: fixed;
  }
}
`
<img width="960" alt="image" src="https://github.com/saadeghi/daisyui/assets/87760767/308e884b-ad8f-4dd2-aabe-d8f804bdaf84">

@support rules cause an issue...

4. yes, absolutely

**Comment by saadeghi** [comment]
I'm glad you found the issue.  
I think it's not a good idea to apply `background-attachment: fixed` to all elements `body *`.
