### ISSUE TITLE
Any button in a modal closes it, how do I change that?

### ISSUE THREAD

**Issue by plonai** [saadeghi/daisyui#2298]
### What version of daisyUI are you using?

Latest

### Describe your issue

If I add a button other than the close button inside a modal, it will automatically close it, however, I want to call a function or do another action if the button is clicked. How do I change that?

### What browsers are you seeing the problem on?

All browsers

**Comment by saadeghi** [comment]
The button inside `<form method="dialog">` closes the modal. It's just how HTML element `<dialog>` works.

You can use a div or something else instead of `<form method="dialog">` or you can move the button outside of `<form method="dialog">`


```diff
<button class="btn" onclick="my_modal_1.showModal()">open modal</button>
<dialog id="my_modal_1" class="modal">
-  <form method="dialog" class="modal-box">
+  <div class="modal-box">
    <h3 class="font-bold text-lg">Hello!</h3>
    <p class="py-4">Text here</p>
    <div class="modal-action">
      <!-- if there is a button in form, it will close the modal -->
      <button class="btn">Button</button>
    </div>
-  </form>
+  </div>
</dialog>
```
