### ISSUE TITLE
Dropdown like menu

### ISSUE THREAD

**Issue by gjovanov** [saadeghi/daisyui#23]
Hi there,
first of all, thanks for your effort put in Daisy UI. It really is awesome and flexible addition on top of Tailwind.

This is more of a question, than an actual issue.

Recently, we have encountered a requirement to display in a `navbar` component a Dropdown list that renders itself in form of a `menu` like this one:
- https://vuetifyjs.com/en/components/menus/#absolute-without-activator

Current `form-select` seems ok, but it's it cannot be customized e.g. items prefixed with icon, sub items etc. And the `menu` 
component seems static (no dialog/modal option).

We tried to combine a normal `btn` that opens up a `modal`, however the positioning of the `modal` seems to be always centered and it's not clear that the opened up `modal` belongs to the `btn` that has opened it.

So we are wondering, if there is a way with the current version of Daisy UI to implement a Dropdown list that opens up a menu right next to the activator `btn`  (bottom, top, left or right) in a `modal` mode (like the link provided)? Or if not, is it something feasible to hope it gets implemented in Daisy UI soon?

Many thanks in advance.

/GJ

**Comment by saadeghi** [comment]
Thanks @gjovanov,
DaisyUI doesn't have a CSS-only `dropdown` component yet. I will work on It this week and hopefully I will publish it until next week.  
Currently I think you need some JS to make it work (using a button and a menu)
Here's is a quick example: https://codepen.io/saadeghi/pen/yLMBzMg

**Comment by gjovanov** [comment]
Hey @saadeghi ,
thanks for your quick reply.

I've tested the example and it works just fine. Thanks for that.

Looking forward to have it integrated in Daisy UI. In the meanwhile, we are more than happy with the solution from above.

Feel free to close this issue; or if you want, keep it open until the official `dropdown` component is ready. 

Thanks again.

**Comment by saadeghi** [comment]
@gjovanov [dropdown component](https://daisy.js.org/components/dropdown) added.  
Please update to latest version (0.22.0)

**Comment by gjovanov** [comment]
That was quick. It works like a charm 🎉 

Thanks.

**Comment by gjovanov** [comment]
Hey @saadeghi ,
I'm reopening this one, because when using with `class="dropdown dropdown-hover"`  it works just fine, however when having a `dropdown` that opens up on click e.g. `class="dropdown dropdown-end"`, then clicking on any of the `menu` items in doesn't get handled:

```html
<ul class="shadow menu dropdown-content">
    <li>
          <a on:click={() => { alert('User prefs') }}>
            User preferences
          </a>
    </li>
</ul>
```

It seems that the dropdown gets closed before even it passing the click even to the `ul->li->a` element.

Is this something that we are doing wrong?

Or it's a bug?
Tnx.

**Comment by gjovanov** [comment]
... btw it seems that I cannot reopen it, as only `Comment` button is visible...

**Comment by saadeghi** [comment]
@gjovanov Try adding a `tabindex="0"` to your link so it can get a focus event before the menu loses its focus.

**Comment by gjovanov** [comment]
it works with `tabindex="0"` @saadeghi ... however the menu has more than one item and I had to add `tabindex="0"` to all of them... Important that it works now...

Is this the expected way of working with `dropdown` that opens up on click? Or u see a way of making some changes in the `dropdown` component itself?

If this is the expected approach, we can close this issue...

**Comment by saadeghi** [comment]
@gjovanov The reason is dropdown is working with `:focus` event (it's not click) and this is the only possible way to do it without JS.  
Because in CSS I can't listen to click event to see if user is clicking *outside* of my component (to close the dropdown) I only can see if my dropdown is focused or not... So we need to use `tabindex` to makes things focusable. It's not ideal but I haven't found a better pure CSS way.

**Comment by gjovanov** [comment]
Understood. Tnx for clarifying. Main thing there is a way around it.

**Comment by RayCodeArch** [comment]
> [@gjovanov](https://github.com/gjovanov) Try adding a `tabindex="0"` to your link so it can get a focus event before the menu loses its focus.

can't believe i find the solution here, just works!
