### ISSUE TITLE
docs: white space on the doc page when screen size is <lg

### ISSUE THREAD

**Issue by leowio** [saadeghi/daisyui#2304]
### On which page do you see this issue?

https://daisyui.com/docs/install/

### Describe the issue

<img width="1283" alt="Screenshot 2023-08-29 at 18 10 06" src="https://github.com/saadeghi/daisyui/assets/41331355/7cec69c8-1d9b-4843-a625-3daa01766447">

Seems like it's the sponsor message that is not hidden properly

### What browsers are you seeing the problem on?

All browsers

**Comment by saadeghi** [comment]
You're using an ad blocker.
