### ISSUE TITLE
bug: dropdown arrow

### ISSUE THREAD

**Issue by mark1502** [saadeghi/daisyui#2310]
### What version of daisyUI are you using?

v3.6.4

### Describe your issue

The dropdown arrow on identically styled select elements appear differently.  This seems to only happen in the chrome browser, not firefox or edge.  But it goes away if I remove the select select-sm classes, so it seems to be related to daisyui.

Here is an example:
![Screenshot_daisyui_selects](https://github.com/saadeghi/daisyui/assets/38567111/16350e38-3cb2-4c04-9b02-99171be1da28)

The arrow on the second select appears to be split.  This happens on several selects on the form, but I don't really see a pattern when it occurs on the form, except it usually occurs within the second column on the table.  

Here is another example from the same form:
![Screenshot_daisy_select_2](https://github.com/saadeghi/daisyui/assets/38567111/8d5c1e80-0bb0-4d91-88bb-98778f32a95f)

I tried  recreating a simple version on tailwind play, but it works fine there.  Still, it shows the classes used, so I included the url.

Anyway, I figured I'd pass it along in case it's helpful.

Thanks

### What browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://play.tailwindcss.com/kfYUg85CGi

**Comment by saadeghi** [comment]
I don't see this issue on Chrome (Version 116)  
Answering the following questions would be helpful.

1. Which version of Chrome are you using?
2. Which OS is this?
3. Does this happen in incognito mode as well?
4. Are you using any plugin or software that may apply CSS styles to web pages?
5. Are you using any specific font or aliasing setting in your OS?

**Comment by mark1502** [comment]
1. Chrome 116.0.5845.141
2. Win 11 Home, version 22H2
3. Yes
4. Not that I'm aware of.  Using Laravel Breeze (with Vue and Inertiajs)
5. No, all default stuff.  However, the tailwind.config.js file does add a font.  Here's that file:
```
/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [
        require('@tailwindcss/forms')({
            // strategy: 'base', // only generate global styles
            strategy: 'class', // only generate classes
          }),
        require("daisyui"),
    ],

};
```
It seems the 'Figtree font is added, but not sure if that's default behavior.  Also, fwiw, I previously installed tailwind forms, but then changed the strategy setting to 'class' to address a prior issue.

Not sure why the top line of the file is commented out.  I don't recall doing that so maybe it's the default.

Thanks
