### ISSUE TITLE
bug: some classes doesn't work

### ISSUE THREAD

**Issue by Brown000** [saadeghi/daisyui#2322]
### What version of daisyUI are you using?

v3.6.4

### Describe your issue

I am using [StencilJs](https://stenciljs.com/) to create my framework agnostic web component library, and I used Tailwindcss + DaisyUI to accelerate my development. When I developing a custom Button, I found the class name `btn-primary` lose effect when class name `btn` is working fine.
There is dependencies about tailwindcss and daisyui in `package.json`:
```json
"devDependencies": {
    "daisyui": "^3.6.4",
    "tailwindcss": "^3.3.3"
  },
```
There is the content of tailwindcss config in `tailwind.config.ts`:
```typescript
import type {Config} from 'tailwindcss';
import daisyui, { Config as DaisyUIConfig } from "daisyui";

export default {
  content: [
    './src/index.html',
    './src/components/**/*.tsx',
  ],
  plugins: [
    daisyui,
  ],
  // daisyUI config (optional - here are the default values)
  daisyui: {
    themes: false, // true: all themes | false: only light + dark | array: specific themes like this ["light", "dark", "cupcake"]
    darkTheme: "dark", // name of one of the included themes for dark mode
    base: true, // applies background color and foreground color for root element by default
    styled: true, // include daisyUI colors and design decisions for all components
    utils: true, // adds responsive and modifier utility classes
    rtl: false, // rotate style direction from left-to-right to right-to-left. You also need to add dir="rtl" to your html tag and install `tailwindcss-flip` plugin for Tailwind CSS.
    prefix: "", // prefix for daisyUI classnames (components, modifiers and responsive class names. Not colors)
    logs: true, // Shows info about daisyUI version and used config in the console when building your CSS
  } as DaisyUIConfig,
} as Config;
```
There is the script I used to generate css with tailwind in `package.json`:
```json
"scripts": {
    "tailwind": "npx tailwindcss -i ./src/tailwind.css -o ./src/index.css",
  },
```
There is the custom button definition in `src/components/er-button/er-button.tsx`:
```typescript
import {Component, h} from '@stencil/core';

@Component({
  tag: 'er-button',
  shadow: true,
  styleUrl: '../../index.css'
})
export class ErButton {

  render() {
    return (
      <button class="btn btn-primary">Button</button>
    )
  }

}
```
The problem is I can find some class names in index.css like `btn`,`card`, etc. But other class names are missing, have any idea about this?

### What browsers are you seeing the problem on?

All browsers

**Comment by saadeghi** [comment]
1. Is this
```js
  content: [
    './src/index.html',
    './src/components/**/*.tsx',
  ],
```
addressing all the files that include class names?

2. Are you using class names as strings like `btn-primary` or are you using half variables like `btn-{$color}`?

**Comment by saadeghi** [comment]
When you use dynamic class names, there's no way for Tailwind CSS to know what class names you're using. Read this:  
https://tailwindcss.com/docs/content-configuration#dynamic-class-names
