### ISSUE TITLE
bug: Modals inside of tables on Chrome

### ISSUE THREAD

**Issue by Redoxahmii** [saadeghi/daisyui#2324]
### What version of daisyUI are you using?

3.6.1

### Describe your issue

If any type of modal is used inside the table layout provided the modals do not work on Chrome. On firefox they are working as expected but on chrome the modal fails to even open. On HTML it seemed to work for some reason but fails in React

### What browsers are you seeing the problem on?

Chrome

**Comment by Redoxahmii** [comment]
Instead of using the method they provide for opening Modals `window.my_modal_2.showModal();` Instead use  this `document.getElementById('my_modal_3').show();` which seems to be working on both chrome and Firefox

**Comment by saadeghi** [comment]
> Instead of using the method they provide for opening Modals `window.my_modal_2.showModal();` Instead use this `document.getElementById('my_modal_3').show();` which seems to be working on both chrome and Firefox

Thanks. I updated the examples.

> On HTML it seemed to work for some reason but fails in React

It's probably because React using virtual DOM.
