### ISSUE TITLE
bug: join doesn't ignore hidden elements

### ISSUE THREAD

**Issue by tyywqtwui88ss** [saadeghi/daisyui#2330]
### What version of daisyUI are you using?

3.7.3

### Describe your issue

my code:
```html
<label class="join w-full 2xs:w-auto">
  <span class="btn no-animation join-item hidden 2xs:inline-flex">long label name here</span>
  <span class="btn no-animation join-item 2xs:hidden">short here</span>
  <input type="number" min="0" step="0.1" max="100" class="input input-bordered join-item w-full 2xs:max-w-[90px] text-center" placeholder="10" />
</label>
```
<br>

everything works fine on this one
<img width="408" alt="image" src="https://github.com/saadeghi/daisyui/assets/126598579/81128ba7-1389-4ae6-9780-c55fa53e9705">

<br>

it doesn't add styling for this one since it's the second child element inside label (join), even though the first child is hidden
<img width="338" alt="image" src="https://github.com/saadeghi/daisyui/assets/126598579/c7954447-2769-48c9-945d-aa4b13784ca9">

### What browsers are you seeing the problem on?

Safari, Chrome

### Reproduction URL

https://play.tailwindcss.com/GciBmdw5jp

**Comment by zAlweNy26** [comment]
Are you sure about this? I'm not able to replicate the issue, can you give me an example on Tailwind Playground?

**Comment by tyywqtwui88ss** [comment]
> Are you sure about this? I'm not able to replicate the issue, can you give me an example on Tailwind Playground?

yes here it is: https://play.tailwindcss.com/GciBmdw5jp

I also edited my issue to include this link

**Comment by robsontenorio** [comment]
@saadeghi  

I can replicate this on 4.4.19 . Is there something we can do on daisyUI side? Or is that expected?

**Comment by saadeghi** [comment]
>Is there something we can do on daisyUI side? Or is that expected?  

It's not expected. But as far as I know there's no solution for it. In CSS we have `:first-child` selector but we can't select "first child that is not hidden in the current screen size" because a CSS rule doesn't know if another CSS rule is applied or not.

As a workaround, instead of hiding join item, we can hide the items inside it conditionally:  
https://play.tailwindcss.com/PjDTVQ59kw

There's nothing I can do about it in CSS.

Let me know if you have a question.

**Comment by robsontenorio** [comment]
@saadeghi thanks! I end up with a solution on my side. Instead of relying on hidden elements.
