### ISSUE TITLE
bug: Regression regarding underlined characters in a button

### ISSUE THREAD

**Issue by mark1502** [saadeghi/daisyui#2331]
### What version of daisyUI are you using?

v3.6.4

### Describe your issue

After upgrading from version 2 (2.5.?) to version 3.6.4, I noticed a change on some of my buttons.  These buttons include an underline of a letter which indicate a hot key letter.  In version 2, they were fine, but in version 3, the buttons now appear with a space after the underline.

Here's an example of a version 3 button:
![daisyui_add_button](https://github.com/saadeghi/daisyui/assets/38567111/b1bb0610-7f51-4cc1-b611-7df7521eefcc)

The problem is the space added after the underlined character.  Sorry, I don't have a pic of the button from v.2, but it worked fine in v.2.

Here's the code for that button:
```
<button type="button" class="btn btn-outline btn-primary" :disabled="!state.disableEntryForm" 
  @click="Entry_List_ButtonClicked('Add')">
        + &nbsp;<u>A</u>dd
</button>
```

I also added a quick example from the tailwind play page.

Thanks

### What browsers are you seeing the problem on?

Chrome, Firefox, Edge

### Reproduction URL

https://play.tailwindcss.com/QsFCJDXAo1

**Comment by saadeghi** [comment]
Button has a default `gap` so when there's an icon inside the button, there would be a gap between the icon and text.  
You can remove that gap either by using `gap-0` on the button, or putting your whole text inside a span:  
https://play.tailwindcss.com/TEyAWQx0NE
```html
<div class="p-4">
  <button class="btn btn-primary gap-0">
    <u>p</u>rimary
  </button>
</div>

<div class="p-4">
  <button class="btn btn-primary">
    <span><u>p</u>rimary</span>
  </button>
</div>

```
