### ISSUE TITLE
bug: Modal does not work with a dialog element

### ISSUE THREAD

**Issue by dkraczkowski** [saadeghi/daisyui#2332]
### What version of daisyUI are you using?

3.3.3

### Describe your issue

When I use dialog element, code literally copied from the documentation:

```svelte
<script>
    function showModal() {
        let modal = document.getElementById("my_modal_1");
        modal.showModal()
    }
</script>
<button class="btn" on:click={showModal}>open modal</button>
<dialog id="my_modal_1" class="modal">
  <div class="modal-box">
    <h3 class="font-bold text-lg">Hello!</h3>
    <p class="py-4">Press ESC key or click the button below to close</p>
    <div class="modal-action">
      <form method="dialog">
        <!-- if there is a button in form, it will close the modal -->
        <button class="btn">Close</button>
      </form>
    </div>
  </div>
</dialog>
```

I can only see the overlay but the modal itself is invisible if I disable components styling the modal starts working. When the dialogue element is changed to div the modal works also OK.

Is this a bug, am I missing something?

### What browsers are you seeing the problem on?

Safari, Firefox

### Reproduction URL

stackblitz.com/edit/vitejs-vite-reh2q4

**Comment by saadeghi** [comment]
Update daisyUI to the latest version: `npm i -D daisyui@latest`  
That stackblitz link is using an older version (`2.x`)

I will update the dependencies for that example project soon.

**Comment by dkraczkowski** [comment]
Ah... Such a stupid mistake. @saadeghi thanks for you help.
