### ISSUE TITLE
[Help] Steps vertical alignment

### ISSUE THREAD

**Issue by robsontenorio** [saadeghi/daisyui#2338]
### What version of daisyUI are you using?

v3.7.3

### Describe your issue

I am trying to build a "timeline" by using "steps component". But it gives all "< li >" same highest height, then center.

The **"Register"** step should appear next to bullet.

<br><br><br>

![image](https://github.com/saadeghi/daisyui/assets/118955/50c17d21-13d1-45c3-9573-40f5dbda1260)

### What browsers are you seeing the problem on?

Safari

### Reproduction URL

https://play.tailwindcss.com/C4B832D0SD

**Comment by saadeghi** [comment]
With `steps` all items have the same size. It's not optimal to use as a timeline where items need different sizes.  
It's also not possible to change the behavior of `steps` because it will break all the current websites that are using it.  

A new `timeline` component will be released soon. I'm working on it and it will be perfect for what you need.

**Comment by robsontenorio** [comment]
@saadeghi Nice! looking forward

**Comment by robsontenorio** [comment]
@saadeghi For now I built my own version. But intend to switch to daisyUI component when you release it. 

https://mary-ui.com/docs/components/timeline

**Comment by saadeghi** [comment]
@robsontenorio Looks good 👍  

>intend to switch to daisyUI component when you release it

I will let you know when it's ready.

I'm really excited about Mary project 👏  
I also added a link on daisyUI's website footer. Let me know if I can help with anything.

**Comment by jamaluddinrumi** [comment]
> With `steps` all items have the same size. It's not optimal to use as a timeline where items need different sizes. It's also not possible to change the behavior of `steps` because it will break all the current websites that are using it.
> 
> A new `timeline` component will be released soon. I'm working on it and it will be perfect for what you need.

could you spill the eta?
