### ISSUE TITLE
bug: class="list-decimal" is not rendered

### ISSUE THREAD

**Issue by vespadj** [saadeghi/daisyui#2345]
### Describe your issue

```html
<ol class="list-decimal">
  <li>a</li>
  <li>b</li>
  <li>c</li>
  <li>d</li>
</ol>
```
return
a
b
c
d

instead of:
1. a
2. b
3. c
4. d

**Comment by jamaluddinrumi** [comment]
let me help by providing repro url 

here it is, https://stackblitz.com/edit/daisyui-cdn-2nnbsj?file=index.html

**Comment by saadeghi** [comment]
You can see the numbers, if you add a margin to your list. The numbers are outside of the box model.

Also, this has nothing to do with daisyUI. If you disable daisyUI plugin, it's the same result.

**Comment by jamaluddinrumi** [comment]
or, it can as easy as adding `list-inside` though 

```html
<ol class="list-decimal list-inside">
  <li>a</li>
  <li>b</li>
  <li>c</li>
  <li>d</li>
</ol>
```

**Comment by vespadj** [comment]
`class="list-decimal list-inside"` resolve.
`list-inside` is not reported in the examples in tailwindcss
[https://tailwindcss.com/docs/list-style-type](https://tailwindcss.com/docs/list-style-type)
Thank you
