### ISSUE TITLE
Question: Twin.macro + DaisyUI

### ISSUE THREAD

**Issue by drosi94** [saadeghi/daisyui#235]
I found out that using twin.macro with the DaisyUI plugin has some problems with the building of the application. It takes a very long time to build all the classes that DaisyUI needs.

Does anyone have used twin.macro with DaisyUI and found a solution on that? I have also started a discussion on twin.macro GitHub discussions.

Thank you!

https://github.com/ben-rogerson/twin.macro/discussions/549

**Comment by saadeghi** [comment]
@drosi94 I wish I could help but this is not something I can fix on my end. daisyUI is basically a collection of CSS rules and nothing more. If there's a bug only in a Twin.macro build, it's because CSS is not getting processed correctly.
