### ISSUE TITLE
bug: opacity not working

### ISSUE THREAD

**Issue by gitmalong** [saadeghi/daisyui#2351]
### What version of daisyUI are you using?

3.5.1

### Describe your issue

For some reason opacity classes do not work on any of the elements on my page.

`<progress class="progress grow ml-4 mt-7 transition-opacity opacity-0 bg-opacity-0 text-opacity-0" value="100" max="100"></progress>`

theme: business

package.json
```json
{
  "devDependencies": {
    "daisyui": "^3.5.1"
  },
  "dependencies": {
    "@tailwindcss/typography": "^0.5.9"
  }
}

```

### What browsers are you seeing the problem on?

Chrome, macOS

**Comment by saadeghi** [comment]
Is this still an issue if you disable `daisyui` plugin?

**Comment by gitmalong** [comment]
When disabling the `daisyui` plugin I don't have any stylesheets.


```js
// tailwind.config.js

/** @type {import('tailwindcss').Config} */
module.exports = {
  devtool: "source-map",
  content: {
    files: ["*.html", "./src/**/*.rs"],
  },
  theme: {
    extend: {},
  },
  plugins: [
    require("@tailwindcss/typography"), 
    require("daisyui"),
  ],
  daisyui: {
    themes: ["light", "business"],
  }
}
```

I am building on top of https://github.com/leptos-rs/leptos/tree/main/examples/tailwind_csr_trunk

**Comment by saadeghi** [comment]
I mean when you disable daisyUI, does the opacity class work? Is the `<progress>` element hidden or not?

**Comment by gitmalong** [comment]
When disabling it, opacity still has no effect.

**Comment by gitmalong** [comment]
Not an daisyui issue https://github.com/leptos-rs/leptos/issues/1737
