### ISSUE TITLE
bug: Using @apply with tooltip tooltip-primary is broken 

### ISSUE THREAD

**Issue by amir20** [saadeghi/daisyui#2371]
### What version of daisyUI are you using?

3.7.7

### Describe your issue

I am new DaisyUI so I might be doing something wrong here. But looking at the source code, I think I have found the culprit.  When using Tailwind's `@apply` does not work. 

Here is an example: 

```
<a class="tooltip-primary tooltip tooltip-right ...>...</a>
```
works

But using a class

```
a {
   @apply tooltip-primary tooltip tooltip-right;
}
```

It has no background. Looking at the code, I noticed that colors is implemented as `.tooltip.tooltip-primary { ... }` which means that they only works with classes on DOM. 

Is this to be expected? I have searched through all issues and didn't find anything. 

The reason I am using `@apply` is because 1000+ nodes which adding each class seems repetitive. 

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
Fixed in `3.8.0`
