### ISSUE TITLE
bug: Transparent focus outline used for dropdown menu button when using details/summary method

### ISSUE THREAD

**Issue by apphaus-simon** [saadeghi/daisyui#2377]
### What version of daisyUI are you using?

3.7.7

### Describe your issue

Based on the docs, there are two methods to create a dropdown.

- Using a wrapper with a focussable `label`.
- Using `details` / `summary` elements

One of the key differences between these two approaches is that when the `label` gains focus it will immediately display the dropdown menu, whereas the `summary` element will not.

Both approaches have their button outlines hidden by default on focus:

```css
.dropdown > *:focus {
    outline: 2px solid transparent;
    outline-offset: 2px;
}
```

As such, when tabbing through with a keyboard the `label` method will give visual feedback when focussed (the menu opens), but the `details` method won't (no outline and no menu).

I would expect that either:

- `summary` should keep it's outline when focussed, or
- `details` should have the same `:focus-within` rules to display it's contents

The second option might not be viable given the way the details element works though. I've not investigated to see if the visibility of it's contents can be manipulated with css only (where js would be an option). I've only tested chrome + firefox, but I would assume that other browsers would handle `details` the same way.

Thanks!

### What browsers are you seeing the problem on?

Chrome, Firefox

### Reproduction URL

https://play.tailwindcss.com/R9etB23qpj

**Comment by apphaus-simon** [comment]
I've had a closer look at `<details>` and I can confirm that there doesn't appear to be any way to manage the open state with CSS / relative to focus. Even handling things with JS is pretty tricky and not ideal.

So I would simply allow `summary` to be outlined.

**Comment by saadeghi** [comment]
I couldn't find a way to open/close `<details>` using CSS either.

outline for `<summary>` element inside `.dropdown` added in daisyUI `3.8.2`
