### ISSUE TITLE
bug: node error while running docs locally

### ISSUE THREAD

**Issue by flomero** [saadeghi/daisyui#2379]
### What version of daisyUI are you using?

3.8.2

### Describe your issue

when trying to run `npm run dev` in the docs folder I get the following error:

```bash
Node.js v18.9.0

    at ChildProcess.exithandler (node:child_process:412:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: "node src/lib/scripts/download-file 'https://opencollective.com/daisyui/members/all.json' 'src/lib/json/opencollective-members.json'"
}
Error executing command: node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:393:5)
    at URL.onParseError (node:internal/url:564:9)
    at new URL (node:internal/url:644:5)
    at request (node:https:346:32)
    at Object.get (node:https:394:15)
    at file:///C:/Users/flofi/repos/daisyui/daisyui/src/docs/src/lib/scripts/download-file.js:15:4
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:527:24)
    at async loadESM (node:internal/process/esm_loader:91:5) {
  input: "'https://opencollective.com/daisyui/members/all.json'",
  code: 'ERR_INVALID_URL'
}
```

### What browsers are you seeing the problem on?

Other

**Comment by saadeghi** [comment]
Can you open this URL on your browser?  
https://opencollective.com/daisyui/members/all.json

It could be a temporary error form that server.  

The daisyUI website downloads that JSON file to receive latest data for the homepage.

**Comment by flomero** [comment]
opening the URL works fine. what version of node are you on?

**Comment by saadeghi** [comment]
> what version of node are you on?

Latest.

Does this error happen all the time or was it temporary?

**Comment by flomero** [comment]
got the `get-json` part to work. seems like it tried to open the Urls including the `' '`. looking at this part of the error message:
```bash
input: "'https://opencollective.com/daisyui/members/all.json'",
```
removing them leads to the downloads succeeding 

<hr>

unfortunately, i ran into the next error 😅

```bash
> createStyleHandlerComponent:dev
> echo $'<script>import "@components/StyleDevelopment.svelte"</script>' > src/components/StyleHandler.svelte

The system cannot find the file specified.
```

**Comment by saadeghi** [comment]
I don't know. I think there's something wrong with your environment.

- What OS and OS version are you using?
- What terminal are you using?
- Can you try again after making this change:

  Replace `src/components/StyleHandler.svelte` with `'src/components/StyleHandler.svelte'` in `daisyui/src/docs/package.json` lines 8 and line 9


Let me know if this fixes the issue

**Comment by flomero** [comment]
```
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
```

and tried running the commands in both `Windows Powershell` and `Git Bash` resulting in the same errors. replacing the string as you suggested doesn't change the output unfortunately

**Comment by saadeghi** [comment]
Can you try running the script manually?  
```bash
cd src/docs
echo $'<script>import \"@components/StyleDevelopment.svelte\"</script>' > src/components/StyleHandler.svelte
```
It's a simple echo to create a file 🤔 I don't understand why you're having errors while it's running correctly on other machines. It's even running on GitHub workflows without issues.

**Comment by saadeghi** [comment]
Let me know if the issue still exists

**Comment by Todor46** [comment]
I'm having the same issue. I'm also having issues with the command "npm run init". A lot of parsing errors and commands not recognized.
I see that in the root there is a "bun.lockb" file which implies that bun is used as a package manager for the root of the project. Bun is not fully supported on windows yet (only bun runtime is available). So to install packages on windows, a different manager needs to be used which ignores the bun.lockb file. My guess is that the issues are coming from this inconvenience.

- Windows 11
- Node 20.10

**Comment by saadeghi** [comment]
>So to install packages on windows, a different manager needs to be used which ignores the bun.lockb file. My guess is that the issues are coming from this inconvenience.

I don't think that's the problem. Currently on GitHub actions, we're using Node 21.1.0 and NPM (not Bun) to build + deploy the package and docs. It works with no issues: https://github.com/saadeghi/daisyui/actions/runs/7161442895/job/19497052764

Can you tell more about the error you get?
