### ISSUE TITLE
bug: Drawer transition is wrong in RTL

### ISSUE THREAD

**Issue by sinapirani** [saadeghi/daisyui#2380]
### What version of daisyUI are you using?

3.8.2

### Describe your issue

same issue like: #1974 

### What browsers are you seeing the problem on?

All browsers

**Comment by saadeghi** [comment]
I don't see an issue:  
https://play.tailwindcss.com/e75hUQ3lnx

Please provide a reproduction link.

Also, make sure:
- Page has `dir="rtl"` attribute
- daisyUI config has `rtl:true`
- `tailwindcss-flip` plugin is installed and enabled

Docs: https://daisyui.com/docs/config/#rtl
