### ISSUE TITLE
bug: Changing the checked color of the join failed

### ISSUE THREAD

**Issue by teacher-too** [saadeghi/daisyui#2390]
### What version of daisyUI are you using?

3.8.3

### Describe your issue

When I wanted to change the checked color to green of the join, it didn't work.
```
<div class="join">
          <input
            class="join-item btn btn-success btn-xs btn-outline checked:bg-success checked:border-success"
            type="radio"
            name="options"
            aria-label="Online"
            checked="true"
          />
          <input
            class="join-item btn btn-success btn-xs btn-outline checked:radio-success checked:border-success"
            type="radio"
            name="options"
            aria-label="Offline"
          />
</div>
```

### What browsers are you seeing the problem on?

Edge

**Comment by saadeghi** [comment]
A `radio` input with `btn` class will use the `primary` color if it's checked:  
https://daisyui.com/components/button/#buttons-with-different-html-tags  

You can customize that with arbitrary class names but it's much easier with CSS by adding this CSS:  
https://play.tailwindcss.com/9Wuc4UHECV?file=css
```css
.btn:is(input[type="radio"]:checked) {
  @apply btn-success;
}
.btn:is(input[type="radio"]:not(:checked)) {
  @apply bg-transparent text-success border-success;
}
```

Let me know if you have any questions.
