### ISSUE TITLE
Modal iOS Quirks

### ISSUE THREAD

**Issue by MentalGear** [saadeghi/daisyui#240]
First off: Thank you for this great UI library to make working with tailwind easier!

I noticed when trying out the modal section on **iOS 15** that the URL Hash doesn't bring up a modal at all, and the "hidden checkbox" technique shows the modal, but the background is still scrollable (apparently Apple changed some things that made previous tricks to not work anymore).

This might be helpful on blocking scrolling on iOS 15 when a modal is open.
https://pqina.nl/blog/how-to-prevent-scrolling-the-page-on-ios-safari/

**Comment by saadeghi** [comment]
@MentalGear Yes, I've seen a similar solution on [CSS tricks](https://css-tricks.com/prevent-page-scrolling-when-a-modal-is-open/) but unfortunately all these bulletproof solutions need some JS. I'm trying to keep daisyUI JS-free as much as I can.
