### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by antimatter96** [saadeghi/daisyui#2403]
### 1. What version of daisyUI are you using?

v3.9.2

### 2. Describe your issue

I am trying to customize an existing theme : making border radius 0

Mixing the instructions at 
https://daisyui.com/docs/themes/#-7
https://daisyui.com/docs/themes/#-5

I can not get the variables like '-rounded-box' to be set to my values

StackBltiz : https://stackblitz.com/edit/daisyui-vue-vite-gu94y4?file=tailwind.config.js
Tailwind Play : https://play.tailwindcss.com/KkkyQOic4O

### 3. What browsers are you seeing the problem on?

Chrome

### 4. Reproduction URL

https://play.tailwindcss.com/KkkyQOic4O

**Comment by saadeghi** [comment]
themes is an array of objects. Not an object:
```diff
daisyui: {
-    themes: {
+    themes: [{
      corporate: {
```
