### ISSUE TITLE
DaisyUI and Hugo

### ISSUE THREAD

**Issue by arnaud-lecat** [saadeghi/daisyui#241]
Hi
I am trying to use DaisyUI with a Hugo web site but it does not seem to work.
I think that messages displayed in command line when processing files are embedded in the CSS file

Need help please

**Comment by jarod51** [comment]
This is this message that seems to be embedded in the start of file ! :)

"🌼 daisyUI components 1.14.3  https://github.com/saadeghi/daisyui
  ✔︎ Including:  base, components, themes[21], utilities"
