### ISSUE TITLE
bug: Multiple rating on same page reset other ratings

### ISSUE THREAD

**Issue by thakkaryash94** [saadeghi/daisyui#2421]
### 1. Checklist

- [X] I updated daisyUI (`npm i -D daisyui@latest`) but I still have this issue
- [X] I looked up into [FAQ](https://github.com/saadeghi/daisyui/discussions/1949) but I couldn't find a solution
- [X] I searched in [existing issues](https://github.com/saadeghi/daisyui/issues?q=is%3Aissue) and [discussion forum](https://github.com/saadeghi/daisyui/discussions?discussions_q=) but this bug has not addressed before
- [X] This bug is dasiyUI issue and it's **NOT** specific to a JS framework or a build tool."

### 2. What version of daisyUI are you using?

v3.9.3

### 3. Which browsers are you seeing the problem on?

All browsers

### 4. Reproduction URL

https://stackblitz.com/edit/daisyui-nextjs-w3gjca/?file=pages%2Findex.js

### 5. Describe your issue

If one page has multiple ratings eg. Reviews with each review has ratings. Only last rating component has correct value else every other component get reset with 5 stars.

Steps to reproduce:
1. Go to https://stackblitz.com/edit/daisyui-nextjs-w3gjca?file=pages%2Findex.js or https://play.tailwindcss.com/tzrYMck1oy
2. Click on rating 1 and then click on rating 2/rating 3, it will set other ratings as 5 stars.
3. I tried with useState, same issue

Links:
Stackblitz: https://stackblitz.com/edit/daisyui-nextjs-w3gjca?file=pages%2Findex.js
Tailwind Play: https://play.tailwindcss.com/tzrYMck1oy

**Comment by saadeghi** [comment]
You need to use a different `name` attribute for the other group of rating radio inputs.
