### ISSUE TITLE
bug: Dropdown is rendered behind the text of the adjacent tab with image overlay.

### ISSUE THREAD

**Issue by Dzemy** [saadeghi/daisyui#2433]
### What version of daisyUI are you using?

+-- daisyui@3.9.3

### Which browsers are you seeing the problem on?

Chrome, Firefox, Edge

### Reproduction URL

https://play.tailwindcss.com/GMyw3TAib2

### Describe your issue

I can't use z-index to fix this behavior, the problem only occurs when I use the image tab (image-full).

![image](https://github.com/saadeghi/daisyui/assets/21079305/6771d702-71b0-4b27-a158-be68fa7e842b)

**Comment by breakon** [comment]
## Solution
Add the Z-0 attribute to the style of the second card
## Reproduction URL
https://play.tailwindcss.com/6vPDStTKNz

**Comment by Dzemy** [comment]
My list is dynamically generated, but still your solution is useful because I can dynamically raise the z-index value. Thank you.
Still, I think it would be worth it if it could be fixed directly in the framework. I understand it's a bit of an unconventional approach, but still, dropdown should be above all elements.

**Comment by saadeghi** [comment]
The problem is, we can't decide about the value of z-index because it depends on the page design. Sometimes people may need items to go on top and sometimes on bottom. I think this is something that must be handled based on the page layout.
