### ISSUE TITLE
chore(lang): change language abbreviations to top-level domain names

### ISSUE THREAD

**Issue by wennerryle** [saadeghi/daisyui#2455]
### On which page do you see this issue?

whole site

### Describe the issue

Hi!
I have an issue with abbreviations of languages at header. My subjective opinion - people are better used to the names of their national domains (except English).
I would like following changes:
ko -> kr
ja -> jp
uk -> ua
zh -> cn

### What browsers are you seeing the problem on?

All browsers

**Comment by saadeghi** [comment]
The 2 letter characters are from [ISO standard](https://en.m.wikipedia.org/wiki/List_of_ISO_639-1_codes). I'm not sure how changing them to something else would be helpful.
