### ISSUE TITLE
bug: modal causes issues in production (e..g carousel and scrolling on touch gestures)

### ISSUE THREAD

**Issue by zpydee** [saadeghi/daisyui#2457]
### What version of daisyUI are you using?

3.9.4

### Reproduction URL

https://daisyui.com/components/modal/

### Describe your issue

i have a nextjs app that uses your carousel and modal (using `dialog` method). when deployed, touch gestures to move the carousel items do not work. when i comment out the component that implement modal, everything works.

i've also noticed that use of modal on pages affect scrolling with touch gestures, so i think the problem is with you modal implementation.

i don't have the time to implement a minimal reproduction, but that should be easy enough to do. perhaps its a postcss compile issue?

PS: error only occurs in production, all good in dev, thus the postcss theory

**Comment by saadeghi** [comment]
daisyUI only applies visuals to the HTML `<dialog>` element and has nothing to do with touch gestures.
Does this issue still happen if you remove daisyUI classes from `<dialog>`?

**Comment by phawitpp** [comment]
I'm facing the problem with modal too. I found this error only occurred on iPad. When I click on the button to show modal, nothing is open up.
