### ISSUE TITLE
svelte-rollup example not working

### ISSUE THREAD

**Issue by ninsky** [saadeghi/daisyui#246]
Hello

I've downloaded and installed the [svelte-rollup example](https://github.com/saadeghi/daisyui/tree/master/examples/svelte-rollup). I've followed the commands in svelte-rollup's [README.md](https://github.com/saadeghi/daisyui/blob/master/examples/svelte-rollup/README.md).  

Starting the server following error appears:
![image](https://user-images.githubusercontent.com/1623045/137191488-0390c1bb-cbe9-4ee2-89dc-b551bb9e55e5.png)

Thanks in advance for having a look at it
Nino

**Comment by saadeghi** [comment]
@ninsky example is updated now. thanks for reporting.

please let me know if you have any questions.
