### ISSUE TITLE
docs:  Some Korean translations are missing.

### ISSUE THREAD

**Issue by classbinu** [saadeghi/daisyui#2462]
### On which page do you see this issue?

https://daisyui.com/components/?lang=ko

### Describe the issue

I plan to add Korean translations for the items below.

Korean translations are missing for the following items:

### Title
1. Accordion
2. Bottom navigation
3. Join
4. Loading
5. Browser mockup
6. Toast

### Description
1. Accordion
2. Join
3. Loading
4. Browser

**Comment by saadeghi** [comment]
Thanks for the PR
