### ISSUE TITLE
docs: The square button should be a square button!

### ISSUE THREAD

**Issue by GauravBurande** [saadeghi/daisyui#2464]
### On which page do you see this issue?

https://daisyui.com/components/button/#square-button

### Describe the issue

This is the issue: 
![image](https://github.com/saadeghi/daisyui/assets/100035026/4dd498d2-78e4-4b2d-aab6-fc42bf197f6b)
In the above image the square button component should be a square!

### What browsers are you seeing the problem on?

It's chrome browser

**Comment by GauravBurande** [comment]
I think the above error is only forest theme specific

**Comment by GauravBurande** [comment]
It's also happening with cupcake, valentine and pastel theme

**Comment by saadeghi** [comment]
The square button is about having a square aspect ratio. Since the only difference between a square and a circle is actually border radius and the mentioned themes have a big border radius on buttons, it is expected for square button to have the same border radius as other buttons.
