### ISSUE TITLE
bug: error after updating

### ISSUE THREAD

**Issue by sveltarne** [saadeghi/daisyui#2467]
### What version of daisyUI are you using?

3.9.4

### Which browsers are you seeing the problem on?

Firefox

### Reproduction URL

https://codeberg.org/diamonc/observer

### Describe your issue

The error seems to be with the tailwind.config.cjs file, and this line (and another line like it for light theme) in particular:
```                 
   ...require("daisyui/src/colors/themes")[
                        "[data-theme=dark]"
                    ],
```
it worked just fine on ^2.28.0, but whenever i tried to update to ^3.9.4, i get this error:
![image](https://github.com/saadeghi/daisyui/assets/114943151/f38980dd-efd0-400f-adb5-99668f02e865)

**Comment by saadeghi** [comment]
Change `...require("daisyui/src/colors/themes")` to `...require("daisyui/src/theming/themes")`  

This change was in daisyUI version 3 update.  
Docs: https://daisyui.com/docs/themes/#-7
