### ISSUE TITLE
Visual bug for right side drawer

### ISSUE THREAD

**Issue by whitetown** [saadeghi/daisyui#2483]
### What version of daisyUI are you using?

latest

### Which browsers are you seeing the problem on?

Safari iOS

### Reproduction URL

https://daisyui.com/components/drawer/

### Describe your issue

Right side drawer reacts on swipes 
Left side is ok.

https://github.com/saadeghi/daisyui/assets/10551374/70751300-c065-4880-a9a2-f24a5e731edb

**Comment by antonbubel** [comment]
I recently fixed this issue in my project by adding overflow-hidden class to an element with drawer-side class. I believe this is what needs to be done in the library as well:

<img width="428" alt="image" src="https://github.com/saadeghi/daisyui/assets/47149096/84c8a341-1c5e-48d2-b29f-4b393d9f6ae2">
