### ISSUE TITLE
bug: btn-primary, btn-secondary and many more not applied with SolidJs

### ISSUE THREAD

**Issue by kivi** [saadeghi/daisyui#2487]
### What version of daisyUI are you using?

3.9.4

### Which browsers are you seeing the problem on?

Chrome, Firefox

### Reproduction URL

https://stackblitz.com/edit/daisyui-solidjs-wigk8l/?file=index.html

### Describe your issue

When I add `btn-primary` or `btn-secondary` it should apply the style to the button.
```html
      <button class="btn btn-primary">Button</button>
      <button class="btn btn-secondary">Button</button>
```

The Buttons appear as if they would not have the modifier. They are styled like plain daisyUI Buttons without -primary or -secondary. Also `bg-primary` or `text-primary` would not work.

_I have tried the code with Next.js and React. The -primary and -secondary modifiers are applied. https://stackblitz.com/edit/daisyui-nextjs-zafqye/?file=pages%2Findex.js,tailwind.config.js_

**Comment by saadeghi** [comment]
Class names are working. But your custom colors are not working because `tailwind.config.js` is wrong.  
It should be like this:  
https://stackblitz.com/edit/daisyui-nextjs-y3qhkp/?file=tailwind.config.js
```js
module.exports = {
  content: ['./pages/**/*.{js,ts,jsx,tsx,mdx}'],
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        mytheme:{
          primary: '#9A1C1A',
          secondary: '#598780',
          accent: '#55CC80',
          neutral: '#414558',
          base: '#ff0000',
          base: '#44ff00',
          'base-100': '#ff0000',
          info: '#cccccc',
          success: '#55CC80',
          warning: '#f1fa89',
          error: '#ff5757',
        }
      }
    ]
  }
};
```

**Comment by kivi** [comment]
I tried that as well. And something like that I had initially, but also did not work. Check the second link my original issue. You have a default -primary... and that seems to work with Nextjs/React

**Comment by saadeghi** [comment]
In your other link, your `content` config is wrong. the class names are in `./index.html` but `content` config is only addressing the files in `./src`

Working example: https://stackblitz.com/edit/daisyui-solidjs-lrhww2/?file=tailwind.config.js

**Comment by kivi** [comment]
I have isolated the error. It's an issue with [postcsss-prefix-selector](https://github.com/RadValentin/postcss-prefix-selector)  

My postcss.config.cjs

```postcss.config.cjs
module.exports = {
  plugins: {
    tailwindcss: {},
    'postcss-prefix-selector': {
      prefix: '.myprefix',
      transform: function (prefix, selector, prefixedSelector, filePath, rule) {
        if (prefixOverrideList.includes(selector)) {
          return prefix;
        } else {
          return prefixedSelector;
        }
      },
    },
    autoprefixer: {},
  },
};
```

Something similar: https://github.com/saadeghi/daisyui/issues/2487
if you change `prefix: '.myprefix'` you can see non of the styles are applied. 


@saadeghi Thanks, and thank you so much for this awesome work. 


I am not sure where exactly the error could be....
