### ISSUE TITLE
bug: Responsive dropdown modifiers not overriding

### ISSUE THREAD

**Issue by davidalejandroaguilar** [saadeghi/daisyui#2490]
### What version of daisyUI are you using?

3.9.2

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://codepen.io/davidalejandroaguilar/pen/zYewQpG

### Describe your issue

Responsive dropdown modifiers don't override other modifiers. For example:

```html
dropdown dropdown-bottom md:dropdown-right
```

I'd expect the dropdown to open to the bottom on mobile, and from `md` up, open to the right.

This bug is happening on latest daisyUI version (see example on attached Codepen).

**Comment by robsontenorio** [comment]
Maybe related to #2499
