### ISSUE TITLE
bug: TypeError: Cannot read properties of undefined (reading 'l')

### ISSUE THREAD

**Issue by luizkowalski** [saadeghi/daisyui#2496]
### What version of daisyUI are you using?

4.0.1

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

none

### Describe your issue

Hello!

I'm using DaisyUI on a Ruby on Rails project and I have the following configuration:

```js
import { fontFamily as fonts } from "tailwindcss/defaultTheme";

export const mode = "jit";

export const content = [
  "./app/views/**/*.{erb,haml,html,slim}",
  "./app/components/**/*.{erb,haml,html,slim}",
  "./app/helpers/**/*.rb",
  "./app/assets/stylesheets/**/*.css",
  "./app/javascript/**/*.{js,ts}",
];

export const plugins = [
  // eslint-disable-next-line no-undef
  require("daisyui")
];

export const daisyui = {
  darkTheme: "dracula",
  themes: [
    {
      "acid": {
        // eslint-disable-next-line
        ...require("daisyui/src/theming/themes")["[data-theme=acid]"],
        info: "#7bcef2",
       }
    },
    "dracula",
    // "dark-sumiu",
    // {
    //   "dark-sumiu": {
    //     primary: "#ff79c6",
    //     secondary: "#bd93f9",
    //     accent: "#ffb86c",
    //     neutral: "#414558",
    //     "base-100": "#1f2023",
    //     "base-content": "#f8f8f2",
    //     info: "#7bcef2",
    //     success: "#50fa7b",
    //     warning: "#f1fa8c",
    //     error: "#ff5555",
    //   },
    // },
  ],
};

export const theme = {
....
```

after upgrading to 4.0.1, I'm seeing this error after compilation

```shell
css        |
css        | 🌼   daisyUI 4.0.1
css        | TypeError: Cannot read properties of undefined (reading 'l')
css        |     at /Users/luiz/Projects/sumiu/node_modules/culori/src/interpolate/interpolate.js:45:47
css        |     at Array.map (<anonymous>)
css        |     at /Users/luiz/Projects/sumiu/node_modules/culori/src/interpolate/interpolate.js:45:29
css        |     at Array.reduce (<anonymous>)
css        |     at interpolate_fn (/Users/luiz/Projects/sumiu/node_modules/culori/src/interpolate/interpolate.js:36:27)
css        |     at interpolate (/Users/luiz/Projects/sumiu/node_modules/culori/src/interpolate/interpolate.js:140:2)
css        |     at Object.generateDarkenColorFrom (/Users/luiz/Projects/sumiu/node_modules/daisyui/src/theming/functions.js:31:20)
css        |     at /Users/luiz/Projects/sumiu/node_modules/daisyui/src/theming/functions.js:55:34
css        |     at Array.forEach (<anonymous>)
css        |     at Object.convertColorFormat (/Users/luiz/Projects/sumiu/node_modules/daisyui/src/theming/functions.js:42:27)
```

I noticed that by removing the `themes` key from the configuration it solves the problem but it seems weird: I kept the `darkTheme: dracula` and this is how the page looks like on dark mode:

<img width="538" alt="image" src="https://github.com/saadeghi/daisyui/assets/112706/224232dd-0e3c-4534-9424-b97fe9359b7f">

for comparison, this is how the page should look like/was looking like on Daisy v3:

<img width="471" alt="image" src="https://github.com/saadeghi/daisyui/assets/112706/b8384bf7-9f77-4e9a-9aae-f06ee4a359b9">

**Comment by luizkowalski** [comment]
Update: track it down to this:

```js
export const daisyui = {
  darkTheme: "dim",
  themes: [
    "dim",
    {
      "acid": {
        // eslint-disable-next-line
        ...require("daisyui/src/theming/themes")["[data-theme=acid]"],
        info: "#7bcef2",
       }
    },
    "dracula",
```
as soon as I add a custom theme, it breaks. Not sure exactly why but I guess it has something to do with the array of themes having strings and hashes. as soon hashes are added, it breaks

**Comment by LudoLogical** [comment]
Just wanted to confirm that this issue is also present with Next.js 14.0.2 and also appears to be caused by defining a custom theme. Tested with the following:

```typescript
daisyui: {
    themes: [
      {
        ludo: {
          primary: //...
          secondary: //...
          neutral: //...
          'base-100': //...
          info: //...
          success: //...
          warning: //...
          error: //...
        }
      }
    ],
    darkTheme: 'dark',
    base: true,
    styled: true,
    utils: true,
    rtl: false,
    prefix: '',
    logs: true
  }
```

**Comment by ColinFrick** [comment]
@luizkowalski

I had the same problem. It seems they changed the theme properties. Try replacing
```
        ...require("daisyui/src/theming/themes")["[data-theme=acid]"],
```
with
```
        ...require("daisyui/src/theming/themes")["acid"],
```

**Comment by BranislavLazic** [comment]
@ColinFrick That didn't fix it in my case. Still the same problem. If I remove a custom theme, all works fine.

**Comment by patrickoman** [comment]
I had the same problem after updating to 4.0. My custom theme didn't have a color definition for "accent".
Works again after adding it.

**Comment by sveltarne** [comment]
I think i'll merge my issue (#2503) here, as it seems to be the same issue.

**Comment by sveltarne** [comment]
> @luizkowalski
> 
> I had the same problem. It seems they changed the theme properties. Try replacing
> 
> ```
>         ...require("daisyui/src/theming/themes")["[data-theme=acid]"],
> ```
> 
> with
> 
> ```
>         ...require("daisyui/src/theming/themes")["acid"],
> ```

This does not fix it for me either.

**Comment by CDzungx** [comment]
Replacing worked for me.

**Comment by sveltarne** [comment]
@CDzungx Does your project have any custom themes?

**Comment by saxxas88** [comment]
I solved it by choosing an existing theme and customizing my variables
`/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors:{
        "custom": "#444444"
      }
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        "custom-theme": {
          ...require("daisyui/src/theming/themes")["light"],
          primary: "#570df8",
          secondary: "#f000b8",
          accent: "#1dcdbc",
          neutral: "#2b3440",
          info: "#3abff8",
          success: "#36d399",
          warning: "#fbbd23",
          error: "#f87272"
        },
      },
    ],
  },
};
`

**Comment by saadeghi** [comment]
> 
> I had the same problem. It seems they changed the theme properties. Try replacing
> 
> ```
>         ...require("daisyui/src/theming/themes")["[data-theme=acid]"],
> ```
> 
> with
> 
> ```
>         ...require("daisyui/src/theming/themes")["acid"],
> ```

Thank you @ColinFrick. It was a breaking change and the changelog didn't mention it. I just updated the changelog.  

---

@luizkowalski  
Does this fix the issue on your project?

**Comment by Karalix** [comment]
Adding my 2 cents here.
I was facing the same problem *TypeError: Cannot read properties of undefined (reading 'r')* using Nuxt 2, upgrading to DaisyUI 4.

I previously didn't import any existing theme in `tailwind.config.js`, using the syntax present in the example there : [How to add a new custom theme?](https://daisyui.com/docs/themes/#-4)

Adding the `...require("daisyui/src/theming/themes")["light"]` line to my custom theme, as presented in [How to customize an existing theme?](https://daisyui.com/docs/themes/#-7) fixed the error without impact on the look of my app (at least for now 🤞)

**Comment by sveltarne** [comment]
I still get this error even when i remove any custom themes from my tailwind config.

**Comment by saadeghi** [comment]
Hey everyone,  

> I had the same problem. It seems they changed the theme properties. Try replacing
> 
> ```
>         ...require("daisyui/src/theming/themes")["[data-theme=acid]"],
> ```
> 
> with
> 
> ```
>         ...require("daisyui/src/theming/themes")["acid"],
> ```

If this ☝️ doesn't solve the issue, please share a reproduction repo so I can reproduce the issue.

**Comment by sveltarne** [comment]
Here's my repo: https://codeberg.org/DiamonC/observer/src/branch/daisyui-v4-test

**Comment by ColinFrick** [comment]
@sveltarne  try it without the square brackets in the theme name
`"dark"` not `"[dark]"`

**Comment by sveltarne** [comment]
same error

**Comment by ColinFrick** [comment]
@sveltarne did you change both `"[dark]"` and `"[light]"`?

I tried it with your repository and when I change both it builds.

**Comment by sveltarne** [comment]
That fixed it for me.

**Comment by luizkowalski** [comment]
sorry for the late reply!

yeah, th

> > I had the same problem. It seems they changed the theme properties. Try replacing
> > ```
> >         ...require("daisyui/src/theming/themes")["[data-theme=acid]"],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > with
> > ```
> >         ...require("daisyui/src/theming/themes")["acid"],
> > ```
> 
> Thank you @ColinFrick. It was a breaking change and the changelog didn't mention it. I just updated the changelog and the docs.
> 
> @luizkowalski Does this fix the issue on your project?


this actually fixed but now I'm getting something different with 4.2.3:


```shell
css        |
css        | 🌼   daisyUI 4.2.3
css        | TypeError: Cannot read properties of undefined (reading 'l')
css        |     at /Users/luiz/Projects/sumiu/node_modules/culori/src/interpolate/interpolate.js:45:47
css        |     at Array.map (<anonymous>)
css        |     at /Users/luiz/Projects/sumiu/node_modules/culori/src/interpolate/interpolate.js:45:29
css        |     at Array.reduce (<anonymous>)
css        |     at interpolate_fn (/Users/luiz/Projects/sumiu/node_modules/culori/src/interpolate/interpolate.js:36:27)
css        |     at interpolate (/Users/luiz/Projects/sumiu/node_modules/culori/src/interpolate/interpolate.js:140:2)
css        |     at generateDarkenColorFrom (/Users/luiz/Projects/sumiu/node_modules/daisyui/src/theming/functions.js:23:38)
css        |     at /Users/luiz/Projects/sumiu/node_modules/daisyui/src/theming/functions.js:46:27
css        |     at Array.forEach (<anonymous>)
css        |     at convertColorFormat (/Users/luiz/Projects/sumiu/node_modules/daisyui/src/theming/functions.js:33:25)
```

does it ring a bell?

**Comment by JoeAlisson** [comment]
I still get same issue on 4.1.1. It was working fine in 4.0.4. 

It's probably now caused by the  [convert to ESM](https://github.com/saadeghi/daisyui/commit/aed8cd5e7523569dd56ef035cbda6da86f5d422a) change on themes.js.

Here's a repo to reproduce the issue: https://github.com/JoeAlisson/daisyui-theme-issue

As far as could see its is caused because the `require("daisyui/src/theming/themes")` is returning like this:

```json
{
  themes: {
    aqua: {
      'color-scheme': 'dark',
      primary: '#09ecf3',
      'primary-content': '#005355',
      secondary: '#966fb3',
      accent: '#ffe999',
      neutral: '#3b8ac4',
      'base-100': '#345da7',
      info: '#2563eb',
      success: '#16a34a',
      warning: '#d97706',
      error: 'oklch(73.95% 0.19 27.33)'
    }
  }
}
```

So adding a `themes` key as workaround is working:

```json
themes: [
      {
        light: {
          ...require("daisyui/src/theming/themes")['themes']["light"],
          primary: "blue",
          secondary: "teal",
        },
      },
    ]
```

**Comment by luizkowalski** [comment]
right! I overlooked the `themes` key, that fixed

**Comment by saadeghi** [comment]
Sorry about this issue.  
The conversion from CommonJS to ESM created a lot of unexpected consequences. I'm working on it.

**Comment by saadeghi** [comment]
I had to undo the whole ESM migration because of countless bugs. I apologize.

Now required themes are going to work like before:
```
...require("daisyui/src/theming/themes")["light"]
```
https://play.tailwindcss.com/WU6di4oDsk?file=config

Let me know if there's an issue
