### ISSUE TITLE
bug: custom theme breaks sveltekit project on v4

### ISSUE THREAD

**Issue by Sillyvan** [saadeghi/daisyui#2497]
### What version of daisyUI are you using?

4.0.1

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://stackblitz.com/edit/daisyui-sveltekit-v2kf5l/?file=package.json

### Describe your issue

So i just upgraded to v4 and it breaks my project because i have a custom theme. Is there more i need to do? if yes the docs are not updated at all. (https://daisyui.com/docs/themes/)

**Comment by stevemarsbar** [comment]
I had this too. You have to have all the colours in your theme:

**Breaks**
myTheme: {
	primary: "#009BA5",
	secondary: "#EDF23B"
}

**Works**
myTheme: {
	primary: "#009BA5",
	secondary: "#EDF23B",
	accent: "#000000",
	neutral: "#000000",
	"base-100": "#000000"
}

**Comment by Sillyvan** [comment]
> I had this too. You have to have all the colours in your theme:
> 
> **Breaks** myTheme: { primary: "#009BA5", secondary: "#EDF23B" }
> 
> **Works** myTheme: { primary: "#009BA5", secondary: "#EDF23B", accent: "#000000", neutral: "#000000", "base-100": "#000000" }

if you would have checked my stackblitz you would have seen that i indeed do have all of these.

**Comment by Sillyvan** [comment]
but i found that for some reason one of my color strings had a dot at the end. this didnt break before now it does. but it was my fault
