### ISSUE TITLE
docs: typo on https://daisyui.com/components/theme-controller/

### ISSUE THREAD

**Issue by sveltarne** [saadeghi/daisyui#2500]
### What version of daisyUI are you using?

4.0.1

### Which browsers are you seeing the problem on?

Firefox

### Reproduction URL

https://daisyui.com/components/theme-controller/

### Describe your issue

localStorage is spelled 'localStorege'.

**Comment by sveltarne** [comment]
ayy #2500

**Comment by itsBlair-hide** [comment]
Came here to report the same thing lol - https://github.com/saadeghi/daisyui/blob/e180f140cfee68d461b0e87404d672de9557ec33/src/docs/src/routes/(docs)/components/theme-controller/%2Bpage.svelte.md?plain=1#L31

There's two typos in this line, `localStorege` and `Storate`

**Comment by sveltarne** [comment]
this is fixed, so ill close this issue.
