### ISSUE TITLE
bug: select-bordered doesn't work

### ISSUE THREAD

**Issue by Rizzaxc** [saadeghi/daisyui#2505]
### What version of daisyUI are you using?

v4.0.3

### Which browsers are you seeing the problem on?

Chromium

### Reproduction URL

https://daisyui.com/components/select/

### Describe your issue

this property straight up doesn't work in v4, even in the updated doc you can see that the 'bordered' and plain version are identical

**Comment by seppe-dalen** [comment]
I am about to push a PR to fix this. Can this be assigned to me?
