### ISSUE TITLE
bug:  Color Styling Not Working in Select Component Demo On Official Website

### ISSUE THREAD

**Issue by ZbWeR** [saadeghi/daisyui#2513]
### What version of daisyUI are you using?

v4.0

### Which browsers are you seeing the problem on?

Edge

### Reproduction URL

https://daisyui.com/components/select/#dwqkl

### Describe your issue

I've noticed an issue while exploring the Select component demo on the new version of your official website. The color styles for 'Success' and 'Info' are not functioning as expected. Instead of displaying in their respective colors, they appear identical to the regular styles.

However, when these same components are used in the actual program, they function normally and display the correct color styles

![image](https://github.com/saadeghi/daisyui/assets/49082837/21e84a66-27a2-4160-b8a9-00fc29be274c)

**Comment by saadeghi** [comment]
Fixed in https://github.com/saadeghi/daisyui/pull/2514 by @seppe-dalen
