### ISSUE TITLE
bug: vite warnings when minifying css

### ISSUE THREAD

**Issue by michael-farwell** [saadeghi/daisyui#2515]
### What version of daisyUI are you using?

v4.0.0

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

NA

### Describe your issue

During build, Vite throws several warnings during CSS minification. This just started to occur when I upgraded DaisyUI to v4.
Here are the warnings:
`▲ [WARNING] Unexpected "-bordered" [css-syntax-error]

    <stdin>:2711:39:
      2711 │ .select-bordered, :where(select.select)-bordered{
           ╵                                        ~~~~~~~~~

▲ [WARNING] Unexpected "-ghost" [css-syntax-error]

    <stdin>:2724:36:
      2724 │ .select-ghost, :where(select.select)-ghost{
           ╵                                     ~~~~~~

▲ [WARNING] Unexpected "-ghost" [css-syntax-error]

    <stdin>:2728:42:
      2728 │ .select-ghost:focus, :where(select.select)-ghost:focus{
           ╵                                           ~~~~~~

▲ [WARNING] Unexpected "-primary" [css-syntax-error]

    <stdin>:2734:38:
      2734 │ .select-primary, :where(select.select)-primary{
           ╵                                       ~~~~~~~~

▲ [WARNING] Unexpected "-primary" [css-syntax-error]

    <stdin>:2739:44:
      2739 │ .select-primary:focus, :where(select.select)-primary:focus{
           ╵                                             ~~~~~~~~

▲ [WARNING] Unexpected "-secondary" [css-syntax-error]

    <stdin>:2745:40:
      2745 │ .select-secondary, :where(select.select)-secondary{
           ╵                                         ~~~~~~~~~~

▲ [WARNING] Unexpected "-secondary" [css-syntax-error]

    <stdin>:2750:46:
      2750 │ .select-secondary:focus, :where(select.select)-secondary:focus{
           ╵                                               ~~~~~~~~~~

▲ [WARNING] Unexpected "-accent" [css-syntax-error]

    <stdin>:2756:37:
      2756 │ .select-accent, :where(select.select)-accent{
           ╵                                      ~~~~~~~

▲ [WARNING] Unexpected "-accent" [css-syntax-error]

    <stdin>:2761:43:
      2761 │ .select-accent:focus, :where(select.select)-accent:focus{
           ╵                                            ~~~~~~~

▲ [WARNING] Unexpected "-info" [css-syntax-error]

    <stdin>:2767:35:
      2767 │ .select-info, :where(select.select)-info{
           ╵                                    ~~~~~

▲ [WARNING] Unexpected "-info" [css-syntax-error]

    <stdin>:2772:41:
      2772 │ .select-info:focus, :where(select.select)-info:focus{
           ╵                                          ~~~~~

▲ [WARNING] Unexpected "-success" [css-syntax-error]

    <stdin>:2778:38:
      2778 │ .select-success, :where(select.select)-success{
           ╵                                       ~~~~~~~~

▲ [WARNING] Unexpected "-success" [css-syntax-error]

    <stdin>:2783:44:
      2783 │ .select-success:focus, :where(select.select)-success:focus{
           ╵                                             ~~~~~~~~

▲ [WARNING] Unexpected "-warning" [css-syntax-error]

    <stdin>:2789:38:
      2789 │ .select-warning, :where(select.select)-warning{
           ╵                                       ~~~~~~~~

▲ [WARNING] Unexpected "-warning" [css-syntax-error]

    <stdin>:2794:44:
      2794 │ .select-warning:focus, :where(select.select)-warning:focus{
           ╵                                             ~~~~~~~~

▲ [WARNING] Unexpected "-error" [css-syntax-error]

    <stdin>:2800:36:
      2800 │ .select-error, :where(select.select)-error{
           ╵                                     ~~~~~~

▲ [WARNING] Unexpected "-error" [css-syntax-error]

    <stdin>:2805:42:
      2805 │ .select-error:focus, :where(select.select)-error:focus{
           ╵                                           ~~~~~~

▲ [WARNING] Unexpected "-disabled" [css-syntax-error]

    <stdin>:2814:23:
      2814 │   :where(select.select)-disabled,
           ╵                        ~~~~~~~~~

▲ [WARNING] Unexpected "-disabled" [css-syntax-error]

    <stdin>:2825:130:
      2825 │ ...der, :where(select.select)-disabled::-moz-placeholder, :where...
           ╵                              ~~~~~~~~~

▲ [WARNING] Unexpected "-disabled" [css-syntax-error]

    <stdin>:2833:23:
      2833 │   :where(select.select)-disabled::placeholder,
           ╵                        ~~~~~~~~~

▲ [WARNING] Unexpected "-multiple" [css-syntax-error]

    <stdin>:2843:23:
      2843 │   :where(select.select)-multiple,
`

**Comment by dtcooper** [comment]
Observing the same thing esbuild to minify.

**Comment by saadeghi** [comment]
Fixed in https://github.com/saadeghi/daisyui/pull/2514 by @seppe-dalen
