### ISSUE TITLE
bug: website error in Firefox developer edition (win 11, firefox v.120)

### ISSUE THREAD

**Issue by isidro-rodriguez** [saadeghi/daisyui#2525]
### Reproduction URL

https://example.com

### Describe your issue

![Captura de pantalla 2023-11-14 214128](https://github.com/saadeghi/daisyui/assets/141645287/8fdfdfb6-7daf-4c59-b181-d1c9c78ae57d)

**Comment by fattenap** [comment]
This is also happening on Mac - Sonama 14.1 (Firefox Developer  v.120.0b9)

**Comment by saadeghi** [comment]
Fixed in 4.0.7
