### ISSUE TITLE
Link as Button

### ISSUE THREAD

**Issue by ETFairfax** [saadeghi/daisyui#253]
Hi.

First of all many thanks for taking the time to create this library. It's fantastic ❤️ 

Just wondering if it would be a good idea to some utility classes to the link https://daisyui.com/components/link component to enable it to be displayed as a button?

It currently works the other way - I can add button that looks like a link....
`<button class="btn btn-link">Button as Link</button>`

would be nice if I could also do the same for link....
`<a class="link link-btn-primary">Link as Button</a>`

...or something along those lines.

In my react app if I want a link that looks like a button I have to create and actual button with event handlers to redirect the user to the page I want. However if it was a proper link then I could just use the `href/to` properties.

Hope that makes sense.

Thanks again.

ET

**Comment by saadeghi** [comment]
@ETFairfax you can use this too:
```
<a class="btn btn-primary">Link as Button</a>
```
or even
```
<div class="btn btn-primary">Link as Button</div>
```
Is that what you meant?
