### ISSUE TITLE
bug: Theme is not applying with NextJs and theme-change

### ISSUE THREAD

**Issue by djech** [saadeghi/daisyui#2530]
### What version of daisyUI are you using?

4.0.5

### Which browsers are you seeing the problem on?

Firefox

### Reproduction URL

https://stackblitz.com/edit/daisyui-nextjs-aou7tu?file=app%2Flayout.jsx

### Describe your issue

When upgrading to DaisyUI 4, the theme stopped being applied to my nextjs app, works fine with 3.x.

**Comment by saadeghi** [comment]
This is an issue from [`theme-change` project](https://github.com/saadeghi/theme-change/), not daisyUI. There's a problem with the recent versions of React.

For Next.js, you can use [`next-themes`](https://github.com/pacocoursey/next-themes) instead of `theme-change`

**Comment by djech** [comment]
Okay will do, thank u for your work on those projects!
