### ISSUE TITLE
bug: Group hover `tooltip-open` tooltip `after` element not displayed

### ISSUE THREAD

**Issue by exoRift** [saadeghi/daisyui#2533]
### What version of daisyUI are you using?

v3.9.4

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://play.tailwindcss.com/xdNBc4SOn3

### Describe your issue

The CSS rule for tooltips is malformed. There's an extra space that causes the rule to not apply to the `after` pseudoelement

![image](https://github.com/saadeghi/daisyui/assets/20345400/8f5d7911-bc83-4a81-96e6-0d45d6e73514)

**Comment by saadeghi** [comment]
Interesting. Looks like that extra space is not from daisyUI and Tailwind CSS is adding it while processing `group` styles.  
I'm going to test if separating the `:before`, `:after` styles into separate CSS selectors will fix it or not.

Creative use of tooltip by the way!

**Comment by saadeghi** [comment]
Fixed in `4.4.12`  
https://play.tailwindcss.com/No5WSmomkT?file=config
