### ISSUE TITLE
Vite postcss error with DaisyUI v4.0

### ISSUE THREAD

**Issue by nader-eloshaiker** [saadeghi/daisyui#2538]
### What version of daisyUI are you using?

v4.0.9

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://github.com/nader-eloshaiker/screen-geometry-app

### Describe your issue

 Using vite, when upgrading from v3.9.4 to > v.4.0.7, I get the following error Have a related issue. `[vite] Internal server error: [postcss] Cannot read properties of undefined (reading 'l')`

Steps to reproduce:

1. clone repo https://github.com/nader-eloshaiker/screen-geometry-app
2. ensure you have `pnpm`, if not, run `npm install -g pnpm`
3. run `pnpm i`
4. run `pnpm run dev`
5. page should render as it is using 3.9.4
6. terminate the server.
7. edit `package.json` and update daisyui to 4.0.9
8. run `pnpm i`
9. run the app again using 'pnpm run dev`
10. this time the page should fail with the error quoted earlier.

**Comment by saadeghi** [comment]
Thank you.

Please do the following:
1. Update to daisyUI version `4.1.0`
2. In `tailwind.config.js` replace these lines.
    ```diff
    - import daisyuiThemes from 'daisyui/src/theming/themes'
    + import { themes as daisyuiThemes } from 'daisyui/src/theming/themes'
    ```
    ```diff
    - ...daisyuiThemes['[data-theme=light]'],
    + ...daisyuiThemes['light'], 
    ```
    ```diff
    - ...daisyuiThemes['[data-theme=dark]'],
    + ...daisyuiThemes['dark'], 
    ```
Let me know if you have a question.

**Comment by saadeghi** [comment]
**_Update_**: Unfortunately there was an issue with `4.1.0` update and we had to revert changes. I apologize.

When you update daisyUI to the latest version agian (`4.3.0`+), change this:
```diff
- import daisyuiThemes from 'daisyui/src/theming/themes'
- import { themes as daisyuiThemes } from 'daisyui/src/theming/themes'
+ import { * as daisyuiThemes } from 'daisyui/src/theming/themes'
```
