### ISSUE TITLE
bug: button spinner doesn't include the spinner

### ISSUE THREAD

**Issue by thewh1teagle** [saadeghi/daisyui#2540]
### What version of daisyUI are you using?

4.1.0

### Which browsers are you seeing the problem on?

Other

### Reproduction URL

https://play.tailwindcss.com/8l3v88kRtK

### Describe your issue

As you can see the spinner doesn't apper,
on localhost it also doesn't apper

On localhost:
![image](https://github.com/saadeghi/daisyui/assets/61390950/9a3bdba5-a0a8-42b2-a43d-6d7bccaaed1e)

```ts
<button className="btn btn-sm btn-primary place-self-end">
  <span className="loading loading-spinner"></span>
  Go to setup...
</button>
```

When trying in localhost, it looks like the bug is in the URL of `mask-image`

**Comment by saadeghi** [comment]
It works in Tailwind Play if you write HTML `class`, not `className`:  
https://play.tailwindcss.com/CrDISu3oRo

And for your local build, do you have `autoprefixer`?  
Read more: https://tailwindcss.com/docs/installation/using-postcss

**Comment by thewh1teagle** [comment]
I don't have `autoprefixer`. I use `daisyui` along with `tailwind` on `remix.js`. didn't saw in the instructions to install that.
anyway I installed it but not sure how to enable it, the loadin still doesn't show.

**Comment by thewh1teagle** [comment]
Finally found solution:
if anyone encounter problems with `daisyUI` with `remix.js` icons:
enable this in `remix.config.js` `{ postcss: true, tailwind: true ... }`
install `autoprefixer` by `npm i -D autoprefixer`
create `postcss.config.js` with
```ts
export default {
  plugins: {
    autoprefixer: {},
  },
}
```

**Comment by inkyu0103** [comment]
@thewh1teagle 

Thank you :) It works!

I'm also using remix and daisyui.

I was having a problem with only black background when I gave the loading option. (like screenshot)
![스크린샷 2023-12-10 오후 10 15 09](https://github.com/saadeghi/daisyui/assets/48270642/a7e09804-3094-4e5a-a4f9-61de86d81e7a)

I fix the problem through the method you explained, thank you.

If you don't mind, can you explain why the problem could be fixed?

**Comment by saadeghi** [comment]
> If you don't mind, can you explain why the problem could be fixed?

Browsers need vendor prefixes (like `-webkit-`, `-moz-`, etc) for many CSS rules. For example here, Chrome doesn't support CSS `mask` but it supports `-webkit-mask`.  
[`autoprefixer`](https://github.com/postcss/autoprefixer) plugin automatically adds vendor prefixes when it's needed.
