### ISSUE TITLE
bug: PostCSS error from Vite (Similar to #2538)

### ISSUE THREAD

**Issue by srav001** [saadeghi/daisyui#2545]
### What version of daisyUI are you using?

v4.3.1

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://stackblitz.com/edit/daisyui-sveltekit-fhz4nu?file=tailwind.config.js,package.json

### Describe your issue

The issue is similar to #2538. Only difference being that this is a SvelteKit app.

When I run the dev server, I get this error - `[plugin:vite:css] [postcss] Cannot read properties of undefined (reading 'r')`

I have tried the fixes listed in #2538 and it didn't work. I am not sure if I did anything wrong or different. Any help will be much appreciated. I wanted to use the new skeleton components, so was eager to update to Daisy UI v4. 

Thank you.

**Comment by saadeghi** [comment]
`#0000000` is not a valid color in `tailwind.config.js`

**Comment by saadeghi** [comment]
✅ I added error handling in daisyUI `4.4.0` for cases like this when the color value is invalid

**Comment by srav001** [comment]
Hugely appreciated! and Thank you so much for Daisy UI.
