### ISSUE TITLE
bug: Theme Inconsistency in Package Version 4 on Firefox v119

### ISSUE THREAD

**Issue by Majd-eddine-BEN-TAHAR** [saadeghi/daisyui#2547]
### What version of daisyUI are you using?

4.4.2

### Which browsers are you seeing the problem on?

Firefox

### Reproduction URL

https://daisyui.com/docs/themes/

### Describe your issue

I've identified an issue related to theme changing within version 4 of the package. Specifically, when attempting to change the theme, I noticed that the border radius of elements and fonts dynamically adjusts as expected; however, the color changes are not reflected. This behavior is unique to Firefox Version 119, as the issue is not replicated in Chrome during testing.
It's important to highlight that this issue is specific to Version 4 of the package. Additionally, I tested this behavior not only on a personal application but also on your official website of the package using firefox. The website exhibits the same inconsistency in theme adjustments, and for your reference, I've provided the link to daisyui page without disclosing the link to my project.

**Comment by saadeghi** [comment]
Looks like it is fixed already.

Here's a video from Firefox 119:

https://github.com/saadeghi/daisyui/assets/7342023/1284440d-9981-45c2-a176-4980b93d5cc6
