### ISSUE TITLE
a css property causes broken text align for btn-sm class

### ISSUE THREAD

**Issue by Oguzhansimsekkk** [saadeghi/daisyui#255]
The line-height css property breaks text alignment for buttons with btn-sm class as shown in screenshots
<img width="925" alt="Ekran Resmi 2021-10-18 19 22 30" src="https://user-images.githubusercontent.com/45979145/137770999-8ef40271-c2e5-4e79-a8be-7f35183cd17f.png">

Disabling line-height: 2rem fixes the issue
<img width="925" alt="Ekran Resmi 2021-10-18 19 24 34" src="https://user-images.githubusercontent.com/45979145/137771057-8e79f84f-5c36-458d-a242-4895dec3f233.png">

**Comment by saadeghi** [comment]
@Oguzhansimsekkk May I ask which browser version and which OS are you using? because I can't see this issue.  
And there should't be any visual issue! small button has a fixed height of `2rem` and a line height of `2rem` must fit perfectly at the center.

**Comment by Oguzhansimsekkk** [comment]
I am using chrome 94.0.4606.81 in MacOS 10.15.7
