### ISSUE TITLE
bug: Broken Navbar image on copy

### ISSUE THREAD

**Issue by colbyfayock** [saadeghi/daisyui#2555]
### What version of daisyUI are you using?

4.4.2

### Reproduction URL

https://daisyui.com/components/navbar/#navbar-with-icon-indicator-and-dropdown

### Describe your issue

The image being referenced in the Navbar, at a minimuim the one with the Icon Indicator and Dropdown, references a local file that doesn't exist.

```
<img alt="Tailwind CSS Navbar component" src="/images/stock/photo-1534528741775-53994a69daeb.jpg" />
```

https://daisyui.com/components/navbar/#navbar-with-icon-indicator-and-dropdown

My assumption, given other components copy in the entire URL such as the Hero:

```
<div className="hero min-h-screen" style={{backgroundImage: 'url(https://daisyui.com/images/stock/photo-1507358522600-9f71e620c44e.jpg)'}}>
```

Is that this is incorrect

## Other Heros

I also noticed in some of the other Hero components that this was a similar case, particularly Hero with Figure:

```
<img src="/images/stock/photo-1635805737707-575885ab0820.jpg" className="max-w-sm rounded-lg shadow-2xl" />
```

https://daisyui.com/components/hero/#hero-with-figure

Let me know if you prefer a separate issue if this is generally something to be addressed.

**Comment by saadeghi** [comment]
But... Why do you want to use a sample image in your actual project?

**Comment by colbyfayock** [comment]
simply so it doesnt appear broken when i paste it in.

if your opposed, i have two suggestions/ideas:
* remove the image path from the snippets, replace with something like YOUR_IMAGE or <Your Image> or whatever
* remove the https://daisyui.com from the one that works for consistency

i prefer the DX though of something not appearing broken immediately after i paste it in, though you certainly run the risk of people leaving it there, like the background image of the Hero, which would currently be the case and not a new risk
