### ISSUE TITLE
docs: All button style classes are genereted with an error

### ISSUE THREAD

**Issue by SergiySev** [saadeghi/daisyui#2578]
### On which page do you see this issue?

https://daisyui.com/components/button/

### Describe the issue

Example:
`<button class="btn-linkbtn">Button</button>`
`<button class="btn-linkbtn btn-linkbtn-neutral">Neutral</button>`
`<button class="btn-linkbtn btn-linkbtn-link">Link</button>`

All button style classes have extra `btn-link` prefix in the generated code preview, instead of `btn btn-neutral` is generated `btn-linkbtn btn-linkbtn-neutral`

### What browsers are you seeing the problem on?

All browsers

**Comment by saadeghi** [comment]
I guess you added a prefix here:

![Screenshot_2023-11-26-06-36-51-658_com android chrome](https://github.com/saadeghi/daisyui/assets/7342023/84b7ecee-b79d-41b5-a85b-64dba49b7d58)
