### ISSUE TITLE
bug: Dropdown cannot be nested

### ISSUE THREAD

**Issue by GianfriAur** [saadeghi/daisyui#2584]
### What version of daisyUI are you using?

v4.4.9

### Which browsers are you seeing the problem on?

All browsers, Chrome

### Reproduction URL

https://play.tailwindcss.com/1WsOZ7vjkN

### Describe your issue

I need to put a dropdown inside another dropdown, but as shown with Tailwind Play this is not possible.

Upon investigation, I found the problem it's in the file `src/components/unstyled/dropdown.css`  and `src/components/styled/dropdown.css` which obviously describes the dropdowns. 

here you can see that the .dropdown-content class does not necessarily have to be a first-level child of the .dropdown class but it just needs to be any of its parents
More precisely, line 35 opens the dropdown inside the other dropdown even if this one is not in focus

I would suggest putting the first level child constraint `>` the result could be something like this

new `src/components/unstyled/dropdown.css`
```scss
.dropdown {
  @apply relative inline-block;
}
.dropdown > *:not(summary):focus {
  @apply outline-none;
}
.dropdown > .dropdown-content {
  @apply absolute;
}
.dropdown:is(:not(details)) > .dropdown-content {
  @apply invisible opacity-0;
}
.dropdown-end > .dropdown-content {
  @apply end-0;
}
.dropdown-left > .dropdown-content {
  @apply bottom-auto end-full top-0;
}
.dropdown-right > .dropdown-content {
  @apply bottom-auto start-full top-0;
}
.dropdown-bottom > .dropdown-content {
  @apply bottom-auto top-full;
}
.dropdown-top > .dropdown-content {
  @apply bottom-full top-auto;
}
.dropdown-end.dropdown-right > .dropdown-content {
  @apply bottom-0 top-auto;
}
.dropdown-end.dropdown-left > .dropdown-content {
  @apply bottom-0 top-auto;
}
.dropdown.dropdown-open > .dropdown-content,
.dropdown:not(.dropdown-hover):focus > .dropdown-content,
.dropdown:focus-within > .dropdown-content {
  @apply visible opacity-100;
}
@media (hover: hover) {
  .dropdown.dropdown-hover:hover > .dropdown-content {
    @apply visible opacity-100;
  }
}
.dropdown:is(details) summary::-webkit-details-marker {
  @apply hidden;
}
```

new `src/components/styled/dropdown.css`
```scss
.dropdown:is(:not(details)) > .dropdown-content {
  @apply origin-top scale-95 transform transition duration-200 ease-out;
}
.dropdown-bottom > .dropdown-content {
  @apply origin-top;
}
.dropdown-top > .dropdown-content {
  @apply origin-bottom;
}
.dropdown-left > .dropdown-content {
  @apply origin-right;
}
.dropdown-right > .dropdown-content {
  @apply origin-left;
}
.dropdown.dropdown-open > .dropdown-content,
.dropdown:focus > .dropdown-content,
.dropdown:focus-within > .dropdown-content {
  @apply scale-100;
}
@media (hover: hover) {
  .dropdown.dropdown-hover:hover > .dropdown-content {
    @apply scale-100;
  }
}
```

this should solve the problem, I can do the pullrequest if you want

**Comment by saadeghi** [comment]
That's... not a good idea.  
A dropdown inside another dropdown is not good UX.  
And in daisyUI dropdown ([method 2](https://daisyui.com/components/dropdown/#method-2-using-css-focus)) works with focus. In HTML, only one element can gain focus at a time so if the child dropdown gains focus, the parent will be closed.

That's not a good pattern and not something we want to add to daisyUI.

Instead of nesting dropdowns, you can use a submenu. It's much cleaner, more accessible and easier to read/develop/use:  
https://play.tailwindcss.com/MeSTOduz2r
