### ISSUE TITLE
bug: input checkbox background-image overrides checked:background-color

### ISSUE THREAD

**Issue by nader-eloshaiker** [saadeghi/daisyui#2585]
### What version of daisyUI are you using?

v4.4.9

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://play.tailwindcss.com/Ux75Tg56m3

### Describe your issue

When trying to override the backgroundColor of a checked input checkbox, it will not apply the color until the backgroundImage style is removed.

**Comment by nader-eloshaiker** [comment]
Thank you very much for not only fixing this in amazing time but for the added value of a better solution.

**Comment by saadeghi** [comment]
It can be hex. It can be any color format:  
https://play.tailwindcss.com/UyUhz4G0Zx

**Comment by nader-eloshaiker** [comment]
There appears to be another issue, if you set a transparency to the color, the background image gradient comes through.

**Comment by saadeghi** [comment]
It's not a SVG icon. It's an icon made with CSS gradient so, yes, the color shouldn't be transparent.  
If you tell me what exactly you want to design, I can help you better.

**Comment by nader-eloshaiker** [comment]
I was interested in allowing the container background color to bleed through the backgound of the checkbox (to tint the background of the checkbox). The background of the checkbox is dynamic and is not known at codetime, only at runtime.

**Comment by saadeghi** [comment]
In that case you can use a custom icon image with a custom background color like this:  
https://play.tailwindcss.com/bgY5cqUwkC
