### ISSUE TITLE
bug: With dropdown-hover, after clicking the "buttons", they remain selected in Chrome

### ISSUE THREAD

**Issue by richard-underwood** [saadeghi/daisyui#2587]
### What version of daisyUI are you using?

v4.4.10

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://daisyui.com/components/dropdown/#open-on-hover

### Describe your issue

When a menu item in a dropdown-hover is clicked in Chrome, the 'button' remains selected preventing the menu from being hidden when the cursor moves away. This can be seen on the daisyui.com documentation page.

The same does not happen in Safari.

**Comment by saadeghi** [comment]
This is intentional and it's for accessibility.  
It opens with hover and closes with mouse leave but it also keeps open if you click the button.  
It also gives a good keyboard accessibility or for touch screens (where there's no hover). Otherwise it would be inaccessible for those environments.
