### ISSUE TITLE
bug(typography): can't use before/after:content with .prose code

### ISSUE THREAD

**Issue by vchirikov** [saadeghi/daisyui#2589]
### What version of daisyUI are you using?

4.4.10

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://play.tailwindcss.com/8V87f1WNwn

### Describe your issue

Hi, first of all thanks for your awesome library.

I found that I can't add use `before:content` (or `after:content`) with daisyui in `div.prose` even if I add `not-prose`
 
https://github.com/saadeghi/daisyui/blob/f7defdc721e76d77c5435e587183c9f70eb54f53/src/components/styled/typography.css#L24-L27

Could we add `not-prose` selector for before/after here?

**Comment by vchirikov** [comment]
as workaround you always can use `!important` (with tailwindcss it's `before:!content-[attr(data-test)]`)

**Comment by saadeghi** [comment]
Fixed in `4.4.11`
