### ISSUE TITLE
bug: Line clamp ellipsis "..." are not styled

### ISSUE THREAD

**Issue by rishavs** [saadeghi/daisyui#2593]
### What version of daisyUI are you using?

4.4.12

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://play.tailwindcss.com/7XtGt9gyVI

### Describe your issue

I am using a line clamp in my menu list. I have specified the color for the menu text using `text-neutral-content`.

Now while the text itself is taking on the `text-neutral-content` color fine, the clamp ellipsis are coming in the primary content color instead.

![image](https://github.com/saadeghi/daisyui/assets/1210239/ec7374c9-dbc1-4aa0-81f2-54faf1183210)

**Comment by saadeghi** [comment]
I can't see the issue in your Tailwind Play link

**Comment by rishavs** [comment]
Sorry, should have specified - You will need to reduce the width till the line clamp takes over. I can see the ellipsis being a different color than the text

![image](https://github.com/saadeghi/daisyui/assets/1210239/72dd6f27-603f-4266-98d9-918f07c3bf93)

**Comment by rishavs** [comment]
Thank you @saadeghi . That did fix the issue.
