### ISSUE TITLE
docs: no scrollbar in sidebar

### ISSUE THREAD

**Issue by jlous** [saadeghi/daisyui#2598]
### On which page do you see this issue?

https://daisyui.com/components/

### Describe the issue

The left aside has no scroll bar of any kind.  This is a major accessibility issue.

Sure: gestures, mouse wheels etc are common today, but those should never be _required_ to make sensible use of the web. Everything should still be _possible_ to achieve with a one-button mouse.

I for one use a wacom pen+tablet, and gesture-scrolling with this is highly impractical. Enough for me to seriously consider switching toolkits just because the docs are hard to use.

Others may have disabilities that limit them to simple pointing devices.

### What browsers are you seeing the problem on?

Chrome on mac (with "scrollbars: always" enabled)

**Comment by Haolaaa** [comment]
what are you talking about?

**Comment by saadeghi** [comment]
You're right 👍  
Fixed in `4.4.15`
