### ISSUE TITLE
 Scrollable Option Class for Modals

### ISSUE THREAD

**Issue by aeadedoyin** [saadeghi/daisyui#260]
So I noticed that when the content of a modal is large, modals are not scrollable.
Tried the tricks I know to make the inner content scroll but to no avail. 
Just felt it will be easier to have one from the theme. e.g. `modal-scrollable.`

<img src="https://user-images.githubusercontent.com/20503883/138090535-c51873a7-8762-4515-b16b-73ad8a5b460f.png" width="50%">

**Comment by saadeghi** [comment]
Thanks for the effort. However, I think it's better to keep the modal less-opionated for now. However, If anyone wants a scrollable content, can use this method or any other style using utility classes or even custom CSS.
