### ISSUE TITLE
bug: <Link> from "react-router-dom" in Navbar breaks everything

### ISSUE THREAD

**Issue by phoskee** [saadeghi/daisyui#2603]
### What version of daisyUI are you using?

v4.0.3

### Which browsers are you seeing the problem on?

Firefox

### Reproduction URL

https://stackblitz.com/edit/daisyui-react-vite-hlgbgp?file=src%2Fmain.tsx

### Describe your issue

Placing a <Link ... > in the navbar, everything breaks.

**Comment by saadeghi** [comment]
This is not from daisyUI. As you can see even if you disable daisyUI, you still get that error.
daisyUI is a CSS library. `<Link>` is a React component from `react-router`

Ask your question here:  
https://github.com/remix-run/react-router
