### ISSUE TITLE
docs: Theme Generator doesn't work

### ISSUE THREAD

**Issue by Ashraf-Khabar** [saadeghi/daisyui#2606]
### On which page do you see this issue?

https://daisyui.com/theme-generator/

### Describe the issue

When I click on the colour on the right side in the theme generator page, it doesn't change the theme, for example when I Click on the “Primary” button nothing happening .

**Comment by saadeghi** [comment]
The right side is a preview to show how components look like. What do you expect to happen when you click that button?

**Comment by Ashraf-Khabar** [comment]
Ahhh okey I just notice this .
