### ISSUE TITLE
bug: Default fallback color not set to configure ! 

### ISSUE THREAD

**Issue by huazhuangnan** [saadeghi/daisyui#2611]
### What version of daisyUI are you using?

v4.4.17

### Reproduction URL

https://play.tailwindcss.com/YqKvjM3xkL?file=config

### Describe your issue

fallback color Color and theme color inconsistency causes the custom theme color to fail.

**Comment by huazhuangnan** [comment]
I need to set my theme color to fallback color how should I set it? @saadeghi

**Comment by saadeghi** [comment]
Like this. In CSS:

https://github.com/saadeghi/daisyui/blob/master/src/base/colors.css

**Comment by huazhuangnan** [comment]
Does this mean I need to set up the theme once in twindcss and then write a basic css to bring it in?

**Comment by huazhuangnan** [comment]
I wonder if it would be possible to add an option in the plugin for the user to decide if the fallback is the main variable of the theme? With your permission, I think I can change. @saadeghi 😊

**Comment by saadeghi** [comment]
>Does this mean I need to set up the theme once in twindcss and then write a basic css to bring it in?

Yes. daisyUI only provides fallback for the built-in `dark` and `light` themes. More than that increases the CSS size and package size unnecessarily.

>With your permission, I think I can change.

It's not worth it, all browsers support OKLCH now and even if you add this, we have to remove it again after a few months. 

Older versions of daisyUI are going to still be available if the majority of your audience are using outdated browsers.

Let me know if have any questions.
