### ISSUE TITLE
bug: Modal does not work with a dialog element on Safari

### ISSUE THREAD

**Issue by vfilatov** [saadeghi/daisyui#2636]
### What version of daisyUI are you using?

4.4.19

### Which browsers are you seeing the problem on?

Safari

### Reproduction URL

https://daisyui.com/components/modal/

### Clicking on `open modal` button doesn't open a modal in (old?) Safari

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15`

**Comment by saadeghi** [comment]
`<dialog>` element works on Safari 15.4+  
Update the browser  
https://caniuse.com/dialog
