### ISSUE TITLE
bug: Improve base themes

### ISSUE THREAD

**Issue by thewh1teagle** [saadeghi/daisyui#2642]
### What version of daisyUI are you using?

4.4.19

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://github.com/saadeghi/daisyui

### Describe your issue

I believe that the library needs a major improvement in the base theme design (light/dark). Some colors lack proper contrast, and there are several other design issues, especially in the dark mode.

**Comment by saadeghi** [comment]
Can you please explain more?  

>Some colors

Which colors exactly?

>several other design issues

Where?

**Comment by thewh1teagle** [comment]
All of these elements have bad contrast of colors
![image](https://github.com/saadeghi/daisyui/assets/61390950/1e49f4df-d6a5-45d5-907f-6270a03ae12a)
![image](https://github.com/saadeghi/daisyui/assets/61390950/293ab928-601c-4e2f-aa68-679575b4a968)
![image](https://github.com/saadeghi/daisyui/assets/61390950/d3da4cdd-8435-4f5e-8a20-4083559c3944)
![image](https://github.com/saadeghi/daisyui/assets/61390950/6d807f78-8b15-4d19-851d-eb491a736648)

**Comment by thewh1teagle** [comment]
Everything in the default dark theme, 
I think that the chosen background color can be much better.
I would take inspiration from MUI dark design 
https://mui.com/

**Comment by thewh1teagle** [comment]
![image](https://github.com/saadeghi/daisyui/assets/61390950/7ac37e23-5869-413e-afea-03963325dc2f)

**Comment by thewh1teagle** [comment]
![image](https://github.com/saadeghi/daisyui/assets/61390950/101cddcb-b944-4a46-abd8-bb815a955982)

**Comment by saadeghi** [comment]
Are you comparing the background color with background color? 🙃  
<img width="546" alt="Screenshot 2023-12-11 at 10 37 06 PM" src="https://github.com/saadeghi/daisyui/assets/7342023/c37cebb3-1484-4025-ab84-3891ebd04ec3">

**Comment by thewh1teagle** [comment]
I'm not sure if it's a problem or not, anyway I checked a lot of components,
and you right most of them pass the checks.

I don't know what, but something in the dark design of `daisyUI` bother me, it doesn't matter which theme I use.
I think it's the contrast between the buttons, but I'm not sure how can I control it in theme level,
For example look at this button of MUI:
![image](https://github.com/saadeghi/daisyui/assets/61390950/6c77cccc-19bc-4018-a639-fb011d93728b)


DaisyUI primary button:
![image](https://github.com/saadeghi/daisyui/assets/61390950/eca3a987-dc5e-4f78-b91d-7529fe90ee48)
It doesn't look and feel primary. how can I make it more brighter in dark mode?

**Comment by thewh1teagle** [comment]
![image](https://github.com/saadeghi/daisyui/assets/61390950/a52fb9d8-58a6-40d4-b9ac-eea52eb19e05)
https://daisyui.com/components/stat/#with-custom-colors-and-button

**Comment by thewh1teagle** [comment]
If you think this feedback doesn't help much at this point, let me know, and I will stop.

**Comment by saadeghi** [comment]
> how can I make it more brighter in dark mode?

[How to customize an existing theme?](https://daisyui.com/docs/themes/#-7)  

Example: https://play.tailwindcss.com/gRB5tLIDKW?file=config

**Comment by saadeghi** [comment]
> ![image](https://private-user-images.githubusercontent.com/61390950/289654605-a52fb9d8-58a6-40d4-b9ac-eea52eb19e05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMjU0MjcsIm5iZiI6MTcwMjMyNTEyNywicGF0aCI6Ii82MTM5MDk1MC8yODk2NTQ2MDUtYTUyZmI5ZDgtNThhNi00MGQ0LWI5YWMtZWVhNTJlYjE5ZTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDIwMDUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4MjI5NTA4NzlkNzkyYjViMGM1ZGRlNmVjZTI1ZDQ2YmM2NGRkYWNhODg2Mzg2MjQyYWEzZGYxMDlkODAzN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.we_Mig8oQqNYZg8000w_Dp4ixbGbFn3UDkdkqnD_7d0) https://daisyui.com/components/stat/#with-custom-colors-and-button

This is an issue 👍 Not from the daisyUI component itself, but from the custom colors I used for the example about using custom colors. I will fix it today.

**Comment by saadeghi** [comment]
> If you think this feedback doesn't help much at this point, let me know, and I will stop.

Not at all. I really appreciate feedbacks.  
However I think you haven'y tried to customize the colors at all. I understand that the built-in themes can not satisfy everyone (no matter how many themes we provide) That's why all colors are customizable and it's possible to make custom theme with custom colors.

**Comment by thewh1teagle** [comment]
So I made MUI theme for daisyUI (at least most of the colors I took from MUI website)
both dark and light themes.
Maybe I / you can Imrprove it and add it to the available themes
https://play.tailwindcss.com/wrf7eO0Jf5
