### ISSUE TITLE
bug: Theme switcher doesn't work on Firefox

### ISSUE THREAD

**Issue by sveltarne** [saadeghi/daisyui#2656]
### What version of daisyUI are you using?

4.4.19

### Which browsers are you seeing the problem on?

Firefox

### Reproduction URL

https://daisyui.com/components/theme-controller/

### Describe your issue

On firefox, the theme controller components simply don't switch the theme like they do on Edge (and presumabley chrome, but i only tested edge and firefox). This can be observed on the daisyui website, but is a problem with daisyUI itself as ive reproduced this error on my site.

**Comment by saadeghi** [comment]
Not yet.

<img width="1105" alt="Screenshot 2023-12-15 at 3 15 38 AM" src="https://github.com/saadeghi/daisyui/assets/7342023/19cc3185-49d4-4e0d-94dd-5c2249496c66">
