### ISSUE TITLE
docs: Update import of the sveltekit

### ISSUE THREAD

**Issue by souyang** [saadeghi/daisyui#2662]
### On which page do you see this issue?

https://daisyui.com/blog/how-to-install-sveltekit-and-daisyui/

### Describe the issue

The documentation does not match the latest code on importing vitePreprocess
`import { vitePreprocess } from '@sveltejs/kit/vite';`
needs to be updated to 
`import { vitePreprocess } from '@sveltejs/vite-plugin-svelte`

### What browsers are you seeing the problem on?
Chrome

### Proposed fix

**Comment by souyang** [comment]
[PR](https://github.com/saadeghi/daisyui/pull/2663/files) to fix this issue

**Comment by saadeghi** [comment]
Merged. Thanks
