### ISSUE TITLE
Suggestion: Floating Labels

### ISSUE THREAD

**Issue by cvkmohan** [saadeghi/daisyui#267]
It would be nice to have floating labels ala https://codepen.io/amiechen/pen/xjvMGb 
I tried applying the peer classes to the input and label controls in a formcontrol class - but - it is not working fine.

**Comment by MentalGear** [comment]
Still an interesting option. Did anyone got this working ?

**Comment by saadeghi** [comment]
Here's an example: https://github.com/saadeghi/daisyui/issues/298#issuecomment-967194458

**Comment by jpoles1** [comment]
I feel like this would be great to have as a default!
