### ISSUE TITLE
bug: "font-wight" is not a known CSS property

### ISSUE THREAD

**Issue by xcvbn2004** [saadeghi/daisyui#2682]
### What version of daisyUI are you using?

v4.4.21

### Reproduction URL

https://github.com/saadeghi/daisyui/blob/v4.4.21/src/components/styled/typography.css#L24

### Describe your issue

```[WARNING] "font-wight" is not a known CSS property [unsupported-css-property]```

I got this warning when build my project.
is "font-wight" of typographt.css typo?

**Comment by saadeghi** [comment]
Fixed in `4.4.22`
