### ISSUE TITLE
btn group dos't look right when RTL is true

### ISSUE THREAD

**Issue by morteza-mortezai** [saadeghi/daisyui#269]
i am using daisyUI in RtL mode 
but when that is true in Daisy config , Border radius is not look right
![image](https://user-images.githubusercontent.com/75200938/138954731-319d1ee0-d799-482e-8e26-b6b1c873b0dd.png)

**Comment by saadeghi** [comment]
@morteza-mortezai CSS file is generated at build time, so if you need to change the direction at run time, you will need 2 different Tailwind builds. Here's an example: https://github.com/saadeghi/daisyui-bidirectional-builds

**Comment by morteza-mortezai** [comment]
thanx but i am not sure this is best way .

i think maybe **another way** is  adding another **config parameter** like **bidirectional** 

and when that's **true** , components that **differs** in **rtl** and **ltr** dirction would have **two series of classes**

for example :

```
[dir=rtl] .btn-group{
...}
[dir-ltr] .btn-group{
...}
```

and when *bidirectional** is set to **false** , just one direction classes would **added** on **build time**

**Comment by saadeghi** [comment]
@morteza-mortezai that's not efficient because changing direction is not an everyday job. Users eventually only choose one of the directions and all other CSS lines would be unnecessary. So it's better to separate them in 2 files.
Also I couldn't find any Tailwind plugin or any PostCSS plugin to do the method you mentioned.

**Comment by morteza-mortezai** [comment]
thanks , 

I know you are worry about users that use just on direction 

**But** i think there will **not** be unnecessary CSS classes for them !

if (**bidirectional=false** && **rtl=false**) { just **ltr** classes would be available }

if ( **bidirectional=false** && **rtl=true**) {  just **rtl** classes would be available }

if ( **bidirectional=true** && **rtl=true**) { **Both rtl and ltr** classes would be available }

**Comment by saadeghi** [comment]
I understand,  
but as I said, I couldn't find any plugin to apply the method you mentioned.
