### ISSUE TITLE
bug: No border above table footer

### ISSUE THREAD

**Issue by jlous** [saadeghi/daisyui#2690]
### What version of daisyUI are you using?

4.4.23

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://play.tailwindcss.com/VV44TFAzwW
https://daisyui.com/components/table/#table-with-visual-elements

### Describe your issue

In a table with a single footer row and the basic 'table' style (with hairlines between rows), I would expect a line between the footer and the body.
This would mirror the header, and follow the general look of the basic table.

In stead, the footer  and the last row of the body look like they are somehow grouped as a single row.

**Comment by Nekxio** [comment]
Hello 😄
I'll take a look !
Which branch should I use to fix this issue ? @saadeghi
