### ISSUE TITLE
bug: Invalid theme switch（主题切换无效）

### ISSUE THREAD

**Issue by peng-xiao-shuai** [saadeghi/daisyui#2693]
### What version of daisyUI are you using?

4.4.23

### Which browsers are you seeing the problem on?

Chrome Android

### Reproduction URL

https://daisyui.com/docs/themes/

### Describe your issue

以 daisyUI 官网为例子，在手机浏览器中打开后更改主题无效

Taking daisyUI's official website as an example, changing the theme after opening it in the mobile browser does not work

https://github.com/saadeghi/daisyui/assets/53845479/3187b0e5-e8bf-414b-ae60-854f73010296

**Comment by peng-xiao-shuai** [comment]
daisyUI 在 3.9.4 版本中工作正常

daisyUI works fine in version 3.9.4

**Comment by saadeghi** [comment]
Which version of Android Chrome are you using?

**Comment by peng-xiao-shuai** [comment]
它在谷歌浏览器中没有问题，可能只是部分浏览器无法更改主题
我测试了 chrome、safari、Via 浏览器、华为浏览器，只有 Via 浏览器（5.1.1）、华为浏览器 无法更改

> 您使用的是哪个版本的 Android Chrome？

**Comment by peng-xiao-shuai** [comment]
> Which version of Android Chrome are you using?

它在谷歌浏览器中没有问题，可能只是部分浏览器无法更改主题
我测试了 chrome、safari、Via 浏览器、华为浏览器，只有 Via 浏览器（5.1.1）、华为浏览器 无法更改

It doesn't have a problem in Google Chrome, it may just be that some browsers can't change the theme
I have tested chrome, safari, Via browser and Huawei browser, only Via browser (5.1.1) and Huawei browser cannot be changed

**Comment by saadeghi** [comment]
You may want to use a modern browser that can support newer CSS features.

Or if you can't use a modern, updated browser, you can use [daisyUI 3](https://v3.daisyui.com/) instead of 4
