### ISSUE TITLE
bug: Daisy's CSS not working in Production

### ISSUE THREAD

**Issue by rhtm123** [saadeghi/daisyui#2696]
### What version of daisyUI are you using?

v4.4.23

### Reproduction URL

https://github.com/rhtm123/ff-frontend

### Describe your issue

It appears that Daisy CSS is functioning correctly in the development environment, as evidenced by successful builds on the local machine. However, an issue arises when attempting to deploy to production, with failures observed on both Vercel and Netlify. If anyone has encountered a similar problem, please share your experiences or suggestions. 

Find the outcome here - https://[remarkable-biscotti-0f0cb8.netlify.app](https://remarkable-biscotti-0f0cb8.netlify.app/)/ 

![Web capture_23-12-2023_173456_remarkable-biscotti-0f0cb8 netlify app](https://github.com/saadeghi/daisyui/assets/18226578/25e41e8c-2bbe-427c-ac84-607d2614e984)

**Comment by saadeghi** [comment]
Content config in `tailwind.config.js` is addressing to 
```
'./src/components/**/*.{js,ts,jsx,tsx,mdx}'
```
While the directory name in your repo is `Components` with capital C.
