### ISSUE TITLE
bug: Countdown does not work in cdn versions

### ISSUE THREAD

**Issue by yooneskh** [saadeghi/daisyui#2699]
### What version of daisyUI are you using?

4.4.24

### Which browsers are you seeing the problem on?

Chrome, Firefox

### Reproduction URL

https://play.tailwindcss.com/Bjca0H4e8p

### Describe your issue

I am using the cdn version of the daisy ui, but this problem exists in the codepen and tailwind play version too (which are the cdn version i suppose).

Essentially, the countdown numbers are not changing when i put them on the screen. I suppose there is a javascript code doing that which does not exist in the cdn version.

**Comment by saadeghi** [comment]
Please read [the docs](https://daisyui.com/components/countdown/):
>Countdown
>Countdown gives you a transition effect of changing numbers.
>**You need to change to `--value` CSS variable using JS**. Value must be a number between 0 and 99.
