### ISSUE TITLE
docs: npm i -D daisyui@latest in the install guide of 3.9.4

### ISSUE THREAD

**Issue by 99power** [saadeghi/daisyui#2702]
### On which page do you see this issue?

https://v3.daisyui.com/docs/install/

### Describe the issue

Shouldn't be latest, but should be npm i -D daisyui@3.9.4

### What browsers are you seeing the problem on?

All browsers

**Comment by Nekxio** [comment]
Hello @99power @saadeghi  😄 
I'll take a look ! Can I be assigned to this issue pls ?

**Comment by saadeghi** [comment]
They would be great!  
v3 docs is on `v3` branch by the way.

**Comment by Nekxio** [comment]
I also checked on versions 1 and 2, there is 'npm i daisyui'. Would it be better to add @1.25.4 and @2.52.0 for each of these versions ? If so, I can take care of that too 😄

**Comment by yosefebrahimi7** [comment]
plase help me.

i use **react-to-pdf** but ....

**Uncaught (in promise) Error: Attempting to parse an unsupported color function "oklch"**

**Comment by saadeghi** [comment]
@yosefebrahimi7 https://github.com/niklasvh/html2canvas/issues/2700

**Comment by yosefebrahimi7** [comment]
> @yosefebrahimi7 [niklasvh/html2canvas#2700](https://github.com/niklasvh/html2canvas/issues/2700)

this repository هt has not been operating for more than three years. Here's the problem:
There is no function for "oklch".

`
const SUPPORTED_COLOR_FUNCTIONS: {
    [key: string]: (context: Context, args: CSSValue[]) => number;
} = {
    hsl: hsl,
    hsla: hsl,
    rgb: rgb,
    rgba: rgb
};
`

help me to convert color to this number :

> ColorName: 0x7fffd4ff

**Comment by yosefebrahimi7** [comment]
some functions exist in here...
[color.txt](https://github.com/saadeghi/daisyui/files/13855803/color.txt)

**Comment by saadeghi** [comment]
@yosefebrahimi7 It's not related to this issue. And has nothing to do with daisyUI at all. If the library you're using can not read color function, open an issue there.  
I searched about the library you mentioned, I found their dependencies, and I found the [related issue](https://github.com/niklasvh/html2canvas/issues/2700) for you.
