### ISSUE TITLE
bug: OKLCH colors and themes not working on mobile

### ISSUE THREAD

**Issue by 99power** [saadeghi/daisyui#2703]
### What version of daisyUI are you using?

4.4.24

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://daisyui.com/docs/themes/

### Describe your issue

It seems not even the fallback colors for the "light" theme are working, only dark theme. 
Running on iPhone 7 (might this be phone related?)
- Firefox 121.0
- Chrome 120.0.6099
- Safari 15.6 (not the latest, but should work according to the docs)

Obviously a downgrade to 3.9.4 resolves the issue.

Personal note: While I love the much better colors, I think fallbacks should be complemented for all themes, maybe in a separate package. Not everyone updates their devices that regularly. 

![IMG_3566](https://github.com/saadeghi/daisyui/assets/124181072/0f552ab4-8870-40ad-b180-6666a6456fae)

**Comment by kriskratz** [comment]
Is your phone set to dark mode? What happens if you change the phone to light mode? This happened to me too.

I'm not sure if the website has all of the theme fallbacks defined. My generated CSS only defines Light and Dark themes by default.

**Comment by saadeghi** [comment]
>Running on iPhone 7

What is your iOS version?

**Comment by ranjan-purbey** [comment]
It turns out that safari doesn't have support of numeric value for lightness `oklch(0 0 0)` but does support percentage value `oklch(0% 0 0)`. This causes the `@support` query to fail and fallback styles from [`src/base/colors.css`](https://github.com/saadeghi/daisyui/blob/master/src/base/colors.css) are used instead.

**Comment by saadeghi** [comment]
> safari doesn't have support of numeric value for lightness `oklch(0 0 0)` but does support percentage value `oklch(0% 0 0)`

I didn't know that. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklch#browser_compatibility), **Mix `<percentage>` and `<number>` syntax in parameters** is supported by Safari 16.2+

I'm going to replace all percentages to numbers to avoid mixed syntax.

Thanks for digging the problem @ranjan-purbey

**Comment by ranjan-purbey** [comment]
On paper it does but appears to be a bug. We would need to replace number values with percentages (only for L. For C & H, numbers work fine)

**Comment by sadkebab** [comment]
I tried to work around this bug by overriding `--fallback` variables in the css but it does not work properly. Sometimes a oklch color gets opacity from another css variable, like  `--tw-text-opacity` in the case of `disabled` buttons, and the fallback for that is to a variable declared in hex like this `color: var(--fallback-bc, oklch(var(--bc)/var(--tw-text-opacity)));`. This is not a proper way of falling back to colors when oklch is not supported, since it applies opaque colors when there should be transparency.

**Comment by sadkebab** [comment]
I also tried downgrading to 3.9.4 but it did not solve the issue for me. colors are still falling back on mobile and there is the same issue with opacity

**Comment by saadeghi** [comment]
@sadkebab Are you also using iOS 15.8?

**Comment by ayazalam** [comment]
so whats the solution here? 

My website does not look good on safari I am using:
theme controller also not working on iOS I have checked on safari and chrome

iPhone 11         
iOS 16.0

is there any workaround?
![3991B713-5145-4601-B405-D0BC0CD654E4](https://github.com/saadeghi/daisyui/assets/16745754/4f84b5e8-f78e-4d94-884a-e506c78b8342)

**Comment by ayazalam** [comment]
> It turns out that safari doesn't have support of numeric value for lightness `oklch(0 0 0)` but does support percentage value `oklch(0% 0 0)`. This causes the `@support` query to fail and fallback styles from [`src/base/colors.css`](https://github.com/saadeghi/daisyui/blob/master/src/base/colors.css) are used instead.
> 
> As a workaround, you can override these fallback custom css properties in your project with hex color values.

hi where do I find this src/base/colors.css

**Comment by ruibaby** [comment]
It doesn't seem to work under Chromium 102 on Desktop.

<img width="1572" alt="image" src="https://github.com/saadeghi/daisyui/assets/21301288/227b72d1-f1ea-462b-86a2-0b4bd007eed8">

**Comment by saadeghi** [comment]
> It doesn't seem to work under Chromium 102 on Desktop.
> 
> <img alt="image" width="1572" src="https://private-user-images.githubusercontent.com/21301288/302072974-227b72d1-f1ea-462b-86a2-0b4bd007eed8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMjkyOTEsIm5iZiI6MTcwNzAyODk5MSwicGF0aCI6Ii8yMTMwMTI4OC8zMDIwNzI5NzQtMjI3YjcyZDEtZjFlYS00NjJiLTg2YTItMGI0YmQwMDdlZWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA2NDMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNWNiNGYxY2EzZGVhZGE5MzI2NWU4MzFmZGE4MTQ4MTZiMGFmYmQ2NzQxMzRlYmViMDJkNjhhOWE1Nzc5YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N15hoSJLf3cHntH7PaDto5dJ4ACqMMFSzt3IUFM1OBs">

Can you share your `tailwind.config.js`?

**Comment by ruibaby** [comment]
> Can you share your `tailwind.config.js`?

```js
/** @type {import('tailwindcss').Config} */
const { Icons } = require("tailwindcss-plugin-icons");
module.exports = {
  content: ["./templates/**/*.html", "./src/**/*.ts"],
  darkMode: "class",
  plugins: [
    require("@tailwindcss/typography"),
    require("@tailwindcss/aspect-ratio"),
    Icons(() => ({
      ri: {
        includeAll: true,
      },
      simpleIcons: {
        includeAll: true,
      },
      tabler: {
        includeAll: true,
      },
    })),
    require("daisyui"),
  ],
  daisyui: {
    themes: true,
  },
  safelist: [
    "i-ri-mail-line",
    "i-ri-wechat-2-line",
    "i-ri-qq-line",
    "i-ri-weibo-fill",
    "i-ri-zhihu-line",
    "i-ri-douban-line",
    "i-ri-bilibili-line",
    "i-ri-tiktok-line",
    "i-ri-telegram-fill",
    "i-ri-facebook-box-line",
    "i-ri-instagram-line",
    "i-ri-linkedin-box-line",
    "i-ri-twitter-line",
    "i-ri-slack-fill",
    "i-ri-discord-line",
    "i-ri-youtube-line",
    "i-ri-steam-fill",
    "i-ri-github-fill",
    "i-ri-gitlab-line",
    "i-ri-rss-fill",
    "i-simple-icons-matrix",
  ],
};

```

**Comment by ruibaby** [comment]
> @ruibaby it should work. I need a reproduction repo so I can see what's going on.

Repo：https://stackblitz.com/~/github.com/ruibaby/daisyui-color-issue

Video：

https://github.com/saadeghi/daisyui/assets/21301288/f455a915-2ab9-4a70-b794-3ad5ff405868

If there is any information missing, please let me know, thx.

**Comment by saadeghi** [comment]
@ranjan-purbey Update the browser. Chrome 102 is an old version.

**Comment by ranjan-purbey** [comment]
> @ranjan-purbey Update the browser. Chrome 102 is an old version.

I think you meant to tag @ruibaby 

Anyway, this affects iOS Safari versions before 16.4

**Comment by mctwistyup** [comment]
Hi all !

I can confirm that we encouters the same problem on safari desktop and mobile before 16.4 
All DaisyUI component are "black and white"

good version :
![image](https://github.com/saadeghi/daisyui/assets/90046724/3a528055-60ff-4f36-a40a-cef87819d10c)

bad version ; 
![image](https://github.com/saadeghi/daisyui/assets/90046724/cafd0c8d-60e0-42fe-9c4d-f7912481052b)

I will push any update i can here

**Comment by mctwistyup** [comment]
Here if i replace the value --p 0.75 by the value in percentage it's ok

![image](https://github.com/saadeghi/daisyui/assets/90046724/1d8a8c42-efab-496b-8a27-c76c3aa13924)

**Comment by mctwistyup** [comment]
@saadeghi

It seems that the supported format for oklch by all browsers is "xx% x.xx x.xx" instead of "x.xx x.xx x.xx" the oklch() function you use from culori package return new oklch code without percentage for the first number.

What do you think if we change the function in  src/theming/functions.js:

`colorObjToString:function (input) {
   const { l, c, h } = input
    return `${cutNumber(l)} ${cutNumber(c)} ${cutNumber(h)}`
  },`

In 

`colorObjToString: function (input) {
    const { l, c, h } = input
    return `${cutNumber(l)*100+"%"} ${cutNumber(c)} ${cutNumber(h)}`
  },`

I'm not sure its the best way and need your advice before forking.

Thanks

**Comment by millette** [comment]
@99power Actually, you need Safari 16.2 and above in order to support that syntax (decimal numbers instead of percentages) according to <https://caniuse.com/mdn-css_types_color_oklch_mixed_type_parameters>

**Comment by xpluscal** [comment]
Any update on this?

**Comment by Psli** [comment]
Any solution fallback for iOS 15?
