### ISSUE TITLE
bug: Right drawer get navigation focus if it has an input

### ISSUE THREAD

**Issue by robsontenorio** [saadeghi/daisyui#2738]
### What version of daisyUI are you using?

4.5.0

### Which browsers are you seeing the problem on?

Chrome, Safari

### Reproduction URL

https://play.tailwindcss.com/HFAwVO0YDc

### Describe your issue

When you have a right drawer it get focus when using tabs from external elements.

Is that expected? Any smart workaround?

https://daisyui.com/components/drawer/#drawer-that-opens-from-right-side-of-page

**Comment by robsontenorio** [comment]
I could set `tabindex="-1"` to all inputs inside drawer, but user expects can hit tab inside that drawer to navigate no next inputs.

**Comment by saadeghi** [comment]
There isn't a way for CSS to conditionally disable tab navigation, but in HTML there's a `inert` attribute.
You can use JS to add/remove `inert` to the sidebar div when the sidebar is closed to prevent tab navigation. 

Let me know if you have any questions.
