### ISSUE TITLE
bug: Badge component not responsive (not growing)

### ISSUE THREAD

**Issue by Tom-DK** [saadeghi/daisyui#2739]
### What version of daisyUI are you using?

v4.5.0

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://play.tailwindcss.com/N8VCXhXxeQ?layout=horizontal

### Describe your issue

![image](https://github.com/saadeghi/daisyui/assets/44878890/652aeb62-4dbc-446f-9c71-8223fe97b8e9)

When width is not big enough to have all text into the badge on one line, the text breaks. However, the badge doesn't grow with the text.

**Comment by saadeghi** [comment]
It's not supposed to grow. It has a fixed height. If it was going to grow height based on content, badges would have inconsistent sizes based on font size, font weight, font family, icon size, etc.

If you want to set height to auto, add `h-auto` class:
https://play.tailwindcss.com/xNu0kvcEt3

Let me know if you have a question.
