### ISSUE TITLE
bug: toggle should have a hover state

### ISSUE THREAD

**Issue by amir20** [saadeghi/daisyui#2741]
### What version of daisyUI are you using?

daisyui 4.5.0

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

n/a

### Describe your issue

By default, DaisyUI's button has `hover` https://github.com/saadeghi/daisyui/blob/c13b26bea8db8fa0d45eb60055f4fdee865f911e/src/components/styled/button.css#L23-L43

However, I noticed the same doesn't exist for toggle.  

Is this done intentionally?

**Comment by amir20** [comment]
PS. thanks for the amazing library

**Comment by amir20** [comment]
Happy to send a PR if it should have hover state.

**Comment by saadeghi** [comment]
I don't think it's necessary, but of course you can customize the style for your own project using utility classes.
