### ISSUE TITLE
bug: Carousel of Mobile Mockup does not work.

### ISSUE THREAD

**Issue by Ananta-One-1** [saadeghi/daisyui#2743]
### What version of daisyUI are you using?

4.5.0

### Reproduction URL

https://play.tailwindcss.com/ndh9AmpKfH

### Describe your issue

Look how the whole screen is becoming scrollable. I can not show my work like this.

**Comment by seriousm4x** [comment]
You can add a new `<div class="overflow-auto">` around your whole html.

```html
<div class="overflow-auto">
  <div class="carousel carousel-center space-x-4 rounded-box bg-neutral p-4">
    ...
  </div>
</div>
```

**Comment by saadeghi** [comment]
You can add a width or max width class name like the example:  
https://daisyui.com/components/carousel/#full-bleed-carousel

Also make sure you have `autoprefixer` PostCSS plugin in your project if you're using PostCSS.

Let me know if you have a question.
