### ISSUE TITLE
How do I add text to the carousel

### ISSUE THREAD

**Issue by rabol** [saadeghi/daisyui#275]
Hi

How can I add text to the carousel?

**Comment by saadeghi** [comment]
@rabol you can use `<div>`s or any other element. is there any problem?

**Comment by Aravin** [comment]
Can you share the code snippet @rabol?

**Comment by saadeghi** [comment]
here's an example with images and text: https://play.tailwindcss.com/GO6td8Xtfl

**Comment by rabol** [comment]
Sorry, had a busy weekend.

It is probably my missing lack of Tailwind knowledge that is the issue:
My expectation was / is that the image in a carousel is the background and the one can add text / buttons on 'top'

**Comment by Aravin** [comment]
You can use stack Component from Daisy UI https://daisyui.com/components/stack

Here is an example: https://play.tailwindcss.com/56pLrpm7vy

**Comment by rabol** [comment]
Thanks a lot!
