### ISSUE TITLE
bug: Toggling dark mode manually

### ISSUE THREAD

**Issue by Birddle** [saadeghi/daisyui#2754]
### What version of daisyUI are you using?

v4.6.0

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

none

### Describe your issue

The component does not support the manual switching mode of tailwindcss.
When switching dark mode manually, if there is a conflict between the system preferences and the manual settings, the manual settings are disabled. For example, if the system preference is dark and light is switched manually, the component style fails.
tailwindcss.config.js
```
...
darkMode: ['class', '[data-theme="dark"]'],
...
```
index.html
```
<html data-theme='light'>
<div class="stats shadow bg-base-200 dark:bg-slate-700">
                    <div class="stat">
                        <div class="stat-figure text-success">
                            <i class="text-3xl fa-solid fa-chart-simple"></i>
                        </div>
                        <div class="stat-title">Page Views</div>
                        <div class="stat-value text-success">2.6M</div>
                        <div class="stat-desc">21% </div>
                    </div>
                </div>
</html>
```

**Comment by saadeghi** [comment]
With daisyUI, you don't need to use `darkMode` in Tailwind config, and you don't need to use either `dark:` prefix or hardcoded colors like `bg-slate-700`  
[daisyUI themes](https://daisyui.com/docs/themes/) manage all the colors automatically. and you don't need extra class name for dark mode.

Read this page: https://daisyui.com/docs/colors/
Or this one for more details: https://daisyui.com/blog/daisyui-colors-and-themes/

Let me know if you have a question.
