### ISSUE TITLE
bug: tabs components example not working 

### ISSUE THREAD

**Issue by ChenaLee** [saadeghi/daisyui#2763]
### What version of daisyUI are you using?

v4.6.0

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://play.tailwindcss.com/Wevz2RS6c4

### Describe your issue

In the [official document](https://daisyui.com/components/tab/), jsx examples are not working as expected.
Other components so far have all been working as documented.

Relevant section: `radio tab bordered + tab content` 
Example provided in the official doc: 
```
<div role="tablist" className="tabs tabs-bordered">
  <input type="radio" name="my_tabs_1" role="tab" className="tab" aria-label="Tab 1" />
  <div role="tabpanel" className="tab-content p-10">Tab content 1</div>

  <input type="radio" name="my_tabs_1" role="tab" className="tab" aria-label="Tab 2" checked />
  <div role="tabpanel" className="tab-content p-10">Tab content 2</div>

  <input type="radio" name="my_tabs_1" role="tab" className="tab" aria-label="Tab 3" />
  <div role="tabpanel" className="tab-content p-10">Tab content 3</div>
</div>
```
### Expected:
<img width="245" alt="Screen Shot 2024-01-15 at 1 33 42 PM" src="https://github.com/saadeghi/daisyui/assets/24197975/6d185a8f-1ea3-445c-ae53-369f30b866e2">

### Actual:
<img width="235" alt="Screen Shot 2024-01-15 at 1 36 45 PM" src="https://github.com/saadeghi/daisyui/assets/24197975/3dfa12e3-1e2d-42c7-993d-07fb77d528bd">

### Problem:
- Style is different

### Solution:
- Changing the tabs to <button> element worked
```
<div className="tabs tabs-bordered" role="tablist">
            {navigation.map((item) => (
                    <button role="tab" onClick={() => setSelectedTabName(item.name)} className={selectedTabName === item.name ? "tab tab-active" : "tab"}> {item.name} </button>
              ))}
</div>
```
<img width="318" alt="Screen Shot 2024-01-15 at 1 41 59 PM" src="https://github.com/saadeghi/daisyui/assets/24197975/e74971a0-247c-479f-b4d2-49c93afc8a9f">

**Comment by saadeghi** [comment]
FAQ, second question: https://github.com/saadeghi/daisyui/discussions/1949

>checkbox/toggle/radio styles are broken
>
>Probably you're using `@tailwindcss/forms` (or another style or plugin) that is affecting form elements.  
daisyUI applies styles to class names but `@tailwindcss/forms` by default, applies styles to all form elements.  
If you really need `@tailwindcss/forms` alongside with daisyUI (which I doubt, because both are doing the same job) consider using its [`strategy: 'class'` config](https://github.com/tailwindlabs/tailwindcss-forms#using-only-global-styles-or-only-classes) so it only applies style to the elements with specific class name (not all form elements)

Let me know if you have a question.

**Comment by danfmn** [comment]
I reviewed the FAQ and I'm also experiencing this issue. I'm not utilizing `@tailwindcss/forms.` The issue occurs with the radios related to tabs. I'm able to use checkboxes/toggles just fine.

**Comment by ChenaLee** [comment]
Thanks!
