### ISSUE TITLE
bug: Select (Dropdown) menu content not positioned correctly on chrome

### ISSUE THREAD

**Issue by ConorCorp** [saadeghi/daisyui#2765]
### What version of daisyUI are you using?

v4.6.0

### Which browsers are you seeing the problem on?

Chrome (M1 Macbook Pro)
Chome Version: Version 120.0.6099.216 (Official Build) (arm64)
This should be latest.

### Reproduction URL

https://daisyui.com/components/select/

### Describe your issue

Select/Dropdown content is not positioned correctly on chrome. Specifically with small screens, works fine on larger ones. Looks like it also works fine on FF and safari at any size.

I can see this issue in my build and in the current daisyUI docs as well.

![Screenshot 2024-01-16 at 3 18 32 PM](https://github.com/saadeghi/daisyui/assets/14174629/d9cc5dca-97e5-4665-9a00-53e7babe064a)

**Comment by saadeghi** [comment]
This looks like a bug from the screen size emulator on chrome. It's not even possible to apply styles for the `<select>` dropdown using CSS (unfortunately)
