### ISSUE TITLE
Classes for using <button> as a menu item

### ISSUE THREAD

**Issue by j-mastr** [saadeghi/daisyui#277]
Hi @saadeghi,

I'm just getting started with daisyUI and am already flashed! Thank you for this awesome library!

During my experiments, I tried some combinations with the Dropdown and the Menu. To provide a better accessibility, I would like to swap the `<a>` container within a menu item with a `<button type="button">`. However, the button ("Delete" in the screenshot) does not look similar as the anchor ("Edit"), as it still has its own style:
<img width="231" alt="Screenshot 2021-10-30 at 23 45 37" src="https://user-images.githubusercontent.com/3593450/139559224-ec750067-b9a1-4893-85ac-60972a4f1f8e.png">
<img width="233" alt="Screenshot 2021-10-30 at 23 45 43" src="https://user-images.githubusercontent.com/3593450/139559228-39d88070-d5c7-4c91-8063-4b7f6d483cf0.png">

I also tried to assign the `btn btn-ghost` or the `btn btn-link` classes, unfortunately without any effect.

Which classes am I missing to use a `button` instead of an `a`nchor?

Thanks a lot for your assistance!

Best,
Janik

**Comment by saadeghi** [comment]
@j-mastr I think it's better to use [button group](https://daisyui.com/components/button-group) here.  
`menu` is good for `ul>li>a` but it might not be suitable for other elements because of the child CSS selectors.
You can use button group or a simple `flex` class on the container to keep the elements next to each other.

Please let me know if you have any questions.

**Comment by j-mastr** [comment]
Thanks for your fast reply and the hint, @saadeghi! I think for this use case a button group might be sufficient as well, even if I like the styling of the horizontal menu a bit more ;)

**Comment by tranvansang** [comment]
I have the same situation but the menu is vertical. Button group is horizontal only. Could you give a suggestion? For now, I have to look at the source code and clone the styling to `menu li>button` selector

**Comment by saadeghi** [comment]
@tranvansang Does these example help? https://play.tailwindcss.com/m4LRoe3e5s

**Comment by tranvansang** [comment]
Woa. Just a list of buttons on shadowed div. I didnt think about it. Actually, my list includes both anchor amd button. Now Im on phone so cannot test. But I think adding btn class to the anchor should work. Thank you very^2 much!!

**Comment by saadeghi** [comment]
Yes. anchor link can have `btn` class too and will look like a button.
