### ISSUE TITLE
bug: high incompatibility with QWebEngineBrowser (Qt library) (because it uses a quite old web engine?)

### ISSUE THREAD

**Issue by DJ-caddev** [saadeghi/daisyui#2781]
### What version of daisyUI are you using?

4.X

### Which browsers are you seeing the problem on?

Other

### Reproduction URL

https://daisyui.com/docs/themes/

### Describe your issue

Hello,

Using Qt 5.15.16 and the class to display web pages (https://doc.qt.io/qt-5/qwebengineview.html), I think the version 4.X of Daisy is incompatible.
![image](https://github.com/saadeghi/daisyui/assets/93262194/1a1ff6ae-a17f-440e-9998-9e0e1f384c3b)

I use to work on a web viewer (including a 3D engine) that uses DaisyUI, but I need to stick with V3.9.X for now because I do not get a clean display anyways with V4.X.

I think this issue is highly related to issue #2703.

---

To reproduce the issue, I just created a simple Qt 5.15.16 project using MSVC, and added a QWebEngineView to my QMainWindow. Then, I only changed the URL to https://daisyui.com/docs/themes/ and compiled and launched the project.

**Comment by saadeghi** [comment]
This is not a bug. QT 5.15 uses Chromium 87 ([source](https://wiki.qt.io/QtWebEngine/ChromiumVersions)) which is an old version of Chromium and doesn't support OKLCH colors ([source](https://caniuse.com/mdn-css_types_color_oklch)).

Updating to QT 6.6 should fix this.

**Comment by DJ-caddev** [comment]
I agree, but our projects are locked in Qt 5 for a while, sadly.
Anyways, I thought it was a good idea to check for compatibility with this quite old browser version. In my opinion, you might be able to fix some issues of the ticket #2703 too... But I might be wrong.

Whether you are going to fix it or not, you are making an awesome job anyways, I love using DaisyUI 😊
