### ISSUE TITLE
bug: custom color for step 

### ISSUE THREAD

**Issue by Muhammad-Yuda-Yudistira** [saadeghi/daisyui#2786]
### Which browsers are you seeing the problem on?

Edge

### Reproduction URL

https://pastebin.com/xeJcqJxc

### Describe your issue

i can custom background color for button, but i can't that at step. why? if there is way for it give in documentation please

**Comment by Muhammad-Yuda-Yudistira** [comment]
You're welcome. contact me soon if you have done please

**Comment by saadeghi** [comment]
Answered here  
https://github.com/saadeghi/daisyui/discussions/1947

Let me know if you have any questions
