### ISSUE TITLE
Vertical steps bar is misaligned when a height is applied

### ISSUE THREAD

**Issue by GaelLanez** [saadeghi/daisyui#279]
When you set a specific height for a vertical step element, the vertical step bar becomes misaligned.

### Current behavior
[View on Tailwind play](https://play.tailwindcss.com/yJFmo3QkXG)
![image](https://user-images.githubusercontent.com/22265293/139665459-61a82c6f-b864-4fcd-8599-6798538447aa.png)

### Expected behavior
![image](https://user-images.githubusercontent.com/22265293/139672611-8ab5eb53-3b25-40fa-b0c5-a0e5559052e0.png)

### Fix
Apply `-translate-y-1/2` instead of `margin-top: -100%;` on `.steps-vertical .step:before`

I would love to fix it myself and become a contributor of daisyUI :)

**Comment by saadeghi** [comment]
@GaelLanez Sure. [Here's the file to edit](https://github.com/saadeghi/daisyui/blob/master/src/components/styled/steps.css#L63)  
Can you open a PR?
