### ISSUE TITLE
bug: CSS variable

### ISSUE THREAD

**Issue by mohssineAboutaj** [saadeghi/daisyui#2790]
### What version of daisyUI are you using?

4.6.0

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://play.tailwindcss.com/sYIjpR4PTM

### Describe your issue

I have a project, i want to get the colors from the database, and I don't know what color format is used in **daisyUI** I don't find anything about this so I opened this issue
```css
  --p: .76859 .164659 70.08039;
```
is this format an **HSL** or **RGB** ?

**Comment by saadeghi** [comment]
It was HSL until daisyUI version `4.0`
 Now it's OKLCH.

You can use it like
```css
color: oklch(var(--p));
```
As mentioned in [this table](https://daisyui.com/docs/colors/)

Let me know if you have any questions
