### ISSUE TITLE
docs: Navigation Bar Selection Font Color

### ISSUE THREAD

**Issue by hutong9** [saadeghi/daisyui#2808]
### Describe the issue

When the background color of the navigation bar is bg-primary, the default color of the navigation selected item is black after clicking, and the style needs to be modified. Although it is not a bug, W single I think it needs to be modified.

**Comment by hutong9** [comment]
When the mouse is selected, the font color is light. When the mouse is removed, the font color changes to dark. At this time, the navigation bar is also dark, so the font cannot be seen.

**Comment by hutong9** [comment]
I added the style. The nav -link: active {color: white} fixed the problem, but I think the defau component should change this style

**Comment by saadeghi** [comment]
What browsers are you seeing the problem on?

**Comment by hutong9** [comment]
> What browsers are you seeing the problem on?

I found that the problem had been solved perfectly.
