### ISSUE TITLE
bug: carousel buttons are not working

### ISSUE THREAD

**Issue by muratkarabag** [saadeghi/daisyui#2813]
### What version of daisyUI are you using?

v4.6.1

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://daisyui.com/components/carousel/#item4

### Describe your issue

when i click the right or left buttons on the carousel its not change the picture. You can see in your website examples of carousel usage. its work if not scrolled to top.

**Comment by Tausif4171** [comment]
Hey,
can I help you to resolve this issue?

**Comment by muratkarabag** [comment]
Hi,
thank you for your response @Tausif4171  I'll try other way to fix this if i cant solve it i ll get in touch with you thank you again 👍  . This topic already opened by others so i'll close for now.
