### ISSUE TITLE
bug: html2canvas issue 

### ISSUE THREAD

**Issue by semiautomatix** [saadeghi/daisyui#2827]
### What version of daisyUI are you using?

v4.6.1

### Which browsers are you seeing the problem on?

Edge

### Reproduction URL

https://www.npmjs.com/package/jspdf

### Describe your issue

Attempting to implement the most basic example on any DaisyUI HTMLElement will result in the following browser error:

**Uncaught (in promise) Error: Attempting to parse an unsupported color function "oklch"**

Example code:

```typescript
export const printCard = (el?: HTMLElement | null) => {
  if (el) {
    // Default export is a4 paper, portrait, using millimeters for units
    const doc = new jsPDF();

    doc.text("Hello world!", 10, 10);
    doc.html(el, {
      callback: function (doc) {
        doc.save("sample.pdf");
      },
    });
  }
};
```

Further referenced in html2canvas repository where it's indicated this error is caused by using any version of DaisyUI 4+: https://github.com/niklasvh/html2canvas/issues/3130

**Comment by semiautomatix** [comment]
Prior issue appears to have been closed: https://github.com/niklasvh/html2canvas/issues/2700

**Comment by saadeghi** [comment]
There's nothing I can do on my end. we should wait for html2canvas update to support new colors.  
You can still use daisyUI version 3.x which uses older HSL color model.

**Comment by semiautomatix** [comment]
> There's nothing I can do on my end. we should wait for html2canvas update to support new colors. You can still use daisyUI version 3.x which uses older HSL color model.

I appreciate the swift reply. Let's leave the closed issue here, so anyone in a similar situation will understand where the issue exists and what can be done until html2canvas is updated.
