### ISSUE TITLE
docs: range with custom color

### ISSUE THREAD

**Issue by iamsatyajit05** [saadeghi/daisyui#2832]
### On which page do you see this issue?

https://daisyui.com/components/range/

### Describe the issue

There is no mention of how to add custom color to the range. A mention of it saves a little bit of time for most developers. Because the same thing is mentioned for the toggle. 

It can be done with [--range-shdw:colorname], that can be directname, #hexvalur, rgb(values)

### What browsers are you seeing the problem on?

All browsers

**Comment by iamsatyajit05** [comment]
@abhishekkr (sorry for disturb)

**Comment by abhishekkr** [comment]
@iamsatyajit05 `--range-shdw` is (just) mentioned at [utilities](https://daisyui.com/docs/utilities/#-4)

It would take me sometime to get to this... if you can raise a PR for the docs, I guess as soon @saadeghi or other maintainers get some time... it would be a quick merge.

**Comment by iamsatyajit05** [comment]
Okay, thanks.
