### ISSUE TITLE
bug: Out of bounds Tooltip gets cut in modal

### ISSUE THREAD

**Issue by JohannesKlauss** [saadeghi/daisyui#2838]
### What version of daisyUI are you using?

v4.6.2

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://play.tailwindcss.com/62oVagBZOZ

### Describe your issue

Open the modal and hover over the heading.

The tooltip goes out of bounds of the modal boundary and gets cut. I would expect the tooltip to "float" above, so that is has no boundaries but the viewport.

**Comment by saadeghi** [comment]
`.modal-box` has `overflow-y: auto` so when the content is overflowing it gets scrolls.  
I'm not sure what is expected to happen when there's an overflowing floating content on the very edge of the box. It is expected to get cut.

**Comment by thanhthinh95** [comment]
I also encountered a similar issue when nesting a dropdown inside a modal. When the dropdown is opened, it gets cut off and constrained by the height of the modal. I spent a lot of time trying to find a solution, but nothing worked



https://github.com/saadeghi/daisyui/assets/34879525/141c800a-4544-4629-ad45-2477177f1adf

**Comment by saadeghi** [comment]
@thanhthinh95 You can add `overflow-visible` to `modal-box`:  
https://play.tailwindcss.com/vHo9pOFYBW

But I wouldn't suggest going out of the modal. Your modal is placed at center but if you use overflowing content inside it and allow it to go outside of the box, you wouldn't be able to control if a larger content will create screen overflow on smaller devices or not.  
On top of that, Putting interactive elements inside of each other, makes it harder for user to have control over the page. a modal is already an interactive element that opens and covers the page content and then another element (dropdown) opens inside it and covers part of the modal and page… It's 3 visual layers on top of each other. Instead, I would suggest using other methods to show your dropdown content. Depending on your dropdown content, you can use links, buttons, tabs, or radio buttons, checkboxes, etc.

Let me know if you have a question.

**Comment by t1u1** [comment]
> I'm not sure what is expected to happen when there's an overflowing floating content on the very edge of the box. It is expected to get cut.

Maybe you can give the tool tip a z-index of (modal z-index + 1). I tried it locally and it works.
