### ISSUE TITLE
docs: typography section

### ISSUE THREAD

**Issue by MentalGear** [saadeghi/daisyui#284]
Could we have the typo section just below "Layout".
I'm constantly missing the "Typography" tab, and I'm somewhat sure others do as well.

https://daisyui.com/core/typography

**Comment by saadeghi** [comment]
Well, daisyUI doesn't provide any layout style or typography style (because Tailwind already has them). Those pages only exists to introduce Tailwind's layout utility classes and the the official typography plugin.

**Comment by MentalGear** [comment]
I didn’t mean to post about a feature request or bug,  but an visibility issue in the documentation. Because "Typography" is in a tab on the top, I often miss  it; my suggestion would be to have the "Typography" section right below the "Layout" section instead of in a separate tab.

**Comment by saadeghi** [comment]
I understand. I would do that if daisyUI was a "design system" (including typography and layout guidelines) but it's not. daisyUI is a component library on top of default Tailwind's style guide, which means it uses Tailwind's spacings, Tailwind's layout utilities, Tailwind's official typography plugin, etc...  
And as I said, `Layout` and `Typography` are not really part of daisyUI docs. they are only there to introduce Tailwind's layout utilities on official Tailwind website and to introduce the `Typography` plugin.

**Comment by MentalGear** [comment]
Sorry, I think there’s a misunderstanding. Again, this is only about the placement of the doc pages, not anything to do with the lib or design system.

**Comment by saadeghi** [comment]
I mean, typography and layout are unimportant pages. That's why they don't have separate links on the sidebar. 
They are not part of daisyUI docs at all. They only exist just in case someone asks "how should I make a flexbox?" Or "how can I customize paddings?"

**Comment by abalmos** [comment]
For what is is worth, I also looked to daisyui's docs for typographical things and didn't find that tab. I understand your point @saadeghi, but maybe some top level docs which explain your position would be helpful? Typographical classes aren't in Tailwind proper either, so it seems like the expectation is that external libraries will have strong opinions on it. 

I only add to this conversation because I think dasiyui is great and it very quickly cleaned up our application. I only want others to have the same smooth experiences with it that we did.

**Comment by saadeghi** [comment]
Your point is valid. I'm not saying the layout is perfect. Tabs at the top might get out of sight when we start reading the content, but [there's also a big "Next: Typography" button](https://daisyui.com/core/layout) after the content. So there's one link at the top (as tab) and again one link at the bottom (as button)

I mean... can you really miss both of them? 😅

**Comment by MentalGear** [comment]
Yupp, you can. :P You’ll probably find out that most people don’t go step by step over docs but navigate to specific pages that are of interest. Thanks @abalmos for chiming in and so I’m not the only one who overlooks this.

Actually, I started out with tailwind by way of DaisyUI, so having had the Layout & Typo section was important. But since I already missed Typography section (hidden in the tab on top) twice, I thought I’ll bring this up so other people (including my future self) will have an easier time on this.

Again, DaisyUI is super helpful and I think the fact that we opened this issue and are trying to make using it easier for other people to get started with speaks of the appreciation we hold for it.

**Comment by saadeghi** [comment]
I think It's better to merge two pages into one for now. It makes sense because the navbar link says both "layout and Typography" and the "Layout" page content is not that much.
I'm going to merge them this weekend.

Thanks @MentalGear and @abalmos
