### ISSUE TITLE
bug: Modal z-index issue.

### ISSUE THREAD

**Issue by Rowen-S** [saadeghi/daisyui#2858]
### What version of daisyUI are you using?

"daisyui": "^4.6.1"

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

NAN

### Describe your issue

my bug:

The z-index of the daisyUI modal is overshadowing the content that was originally intended to be displayed.

![image](https://github.com/saadeghi/daisyui/assets/50318674/a9d75bcb-8674-449a-8cdc-2d943dfd4cf7)

**"Connecting" should be below "walletConnect".**

my modal code:
```
...
return (
    <dialog
      id={modalId}
      ref={modalRef}
      className={`lower-z-index modal modal-bottom max-h-[${maxHeight}vh] min-h-[${minHeight}vh] ${scrollOverlay ? 'overflow-scroll' : ''} sm:modal-middle `}
    >
      <div className="lower-z-index modal-box p-0">{children}</div>
      {modalId && (
        <label className="modal-backdrop" htmlFor={modalId} onClick={onDismiss}>
          Close
        </label>
      )}
    </dialog>
  )
  
  
 .lower-z-index {
    z-index: 10 !important; 
  }
  
```
  
Why doesn't the z-index setting of the modal take effect? Could it be related to the outer `#top-layer` in the HTML?

**Comment by Rowen-S** [comment]
```
{ * html * }
<div id="walletconnect-wrapper">
  <div id="walletconnect-qrcode-modal" class="walletconnect-qrcode__base animated fadeIn">
    <div class="walletconnect-modal__base">
      <div class="walletconnect-modal__header">
        ...
      </div>
      <div>
        <div>
          <p id="walletconnect-qrcode-text" class="walletconnect-qrcode__text">使用兼容 WalletConnect 的钱包扫描二维码</p>
          <div>
            ...
          </div>
          <div class="walletconnect-modal__footer"><a>复制到剪贴板</a></div>
          <div class="walletconnect-qrcode__notification"></div>
        </div>
      </div>
    </div>
  </div>
</div>

{ * css * }
#walletconnect-wrapper {
    -webkit-user-select: none;
    align-items: center;
    display: flex;
    height: 100%;
    justify-content: center;
    left: 0;
    pointer-events: none;
    position: fixed;
    top: 0;
    user-select: none;
    width: 100%;
    z-index: 99999999999999;
}
```

**Comment by Rowen-S** [comment]
Method 2: using a hidden checkbox legacy works perfectly without any issues. Could this be because the Dialog modal is bound to the topmost layer, #top-layer?

**Comment by Rowen-S** [comment]
This could be an optimization, considering that Method 2 is a legacy method and might be deprecated soon.

**Comment by saadeghi** [comment]
I still can't reproduce the issue.  



> ```
> { * html * }
> <div id="walletconnect-wrapper">
>   <div id="walletconnect-qrcode-modal" class="walletconnect-qrcode__base animated fadeIn">
>     <div class="walletconnect-modal__base">
>       <div class="walletconnect-modal__header">
>         ...
>       </div>
>       <div>
>         <div>
>           <p id="walletconnect-qrcode-text" class="walletconnect-qrcode__text">使用兼容 WalletConnect 的钱包扫描二维码</p>
>           <div>
>             ...
>           </div>
>           <div class="walletconnect-modal__footer"><a>复制到剪贴板</a></div>
>           <div class="walletconnect-qrcode__notification"></div>
>         </div>
>       </div>
>     </div>
>   </div>
> </div>
> 
> { * css * }
> #walletconnect-wrapper {
>     -webkit-user-select: none;
>     align-items: center;
>     display: flex;
>     height: 100%;
>     justify-content: center;
>     left: 0;
>     pointer-events: none;
>     position: fixed;
>     top: 0;
>     user-select: none;
>     width: 100%;
>     z-index: 99999999999999;
> }
> ```

This is not daisyUI. And you have a questionable z-index value on the last line.

Can you give me a reproduction link where I can open and see the issue?  

You can use Tailwind Play https://daisyui.com/tailwindplay/

**Comment by Rowen-S** [comment]
> I still can't reproduce the issue.
> 
> > ```
> > { * html * }
> > <div id="walletconnect-wrapper">
> >   <div id="walletconnect-qrcode-modal" class="walletconnect-qrcode__base animated fadeIn">
> >     <div class="walletconnect-modal__base">
> >       <div class="walletconnect-modal__header">
> >         ...
> >       </div>
> >       <div>
> >         <div>
> >           <p id="walletconnect-qrcode-text" class="walletconnect-qrcode__text">使用兼容 WalletConnect 的钱包扫描二维码</p>
> >           <div>
> >             ...
> >           </div>
> >           <div class="walletconnect-modal__footer"><a>复制到剪贴板</a></div>
> >           <div class="walletconnect-qrcode__notification"></div>
> >         </div>
> >       </div>
> >     </div>
> >   </div>
> > </div>
> > 
> > { * css * }
> > #walletconnect-wrapper {
> >     -webkit-user-select: none;
> >     align-items: center;
> >     display: flex;
> >     height: 100%;
> >     justify-content: center;
> >     left: 0;
> >     pointer-events: none;
> >     position: fixed;
> >     top: 0;
> >     user-select: none;
> >     width: 100%;
> >     z-index: 99999999999999;
> > }
> > ```
> 
> This is not daisyUI. And you have a questionable z-index value on the last line.
> 
> Can you give me a reproduction link where I can open and see the issue?
> 
> You can use Tailwind Play https://daisyui.com/tailwindplay/


**this stackblitz link**
https://stackblitz.com/edit/stackblitz-starters-u3or7h?file=app%2Fpage.tsx

**Comment by rajeshwarpatlolla** [comment]
I encounter a similar problem where, regardless of the z-index assigned, the modal consistently remains above all other elements. My intention is to have the modal positioned behind another element, but unfortunately, this is not achieving the desired result. I am trying in vue.js.

**Comment by Rowen-S** [comment]
> I encounter a similar problem where, regardless of the z-index assigned, the modal consistently remains above all other elements. My intention is to have the modal positioned behind another element, but unfortunately, this is not achieving the desired result. I am trying in vue.js.

checkbox modal might fit your needs.

**Comment by rajeshwarpatlolla** [comment]
What do you mean by checkbox modal @Rowen-S ?

**Comment by Ritcheyy** [comment]
I have this bug as well, I want to place a message toast component above a modal, it doesn't seem possible irrespective of the `z-index`

**Comment by saadeghi** [comment]
This is not about daisyUI.  
The new HTML `<dialog>` element is "top layer" which means it stays on top of everything else so you can't show elements outside of dialog on top of the dialog by increasing the `z-index`.

**Comment by Blankeos** [comment]
Good info on the `<dialog>` element. What's the workaround?

**Comment by saadeghi** [comment]
@Blankeos You can put elements inside `<dialog>` but outside `modal-box` class. It will be visible when dialog is open.

**Comment by Blankeos** [comment]
@saadeghi I see. I'm not sure if that's possible for this usecase:
Rendering the toast component (https://sonner.emilkowal.ski) that exists outside the modal.
The <Toaster /> component exists in the root of the tree. It's kind of supposed to be global. Should I be putting that inside the `<dialog>` now?

**Comment by krongk** [comment]
<img width="1100" alt="feedback" src="https://github.com/saadeghi/daisyui/assets/99572/386adc3f-6656-4ba4-9b93-10cdaf848f60">

The seem issue when I submit a feedback.

**Comment by ivanamato** [comment]
> @saadeghi I see. I'm not sure if that's possible for this usecase: Rendering the toast component (https://sonner.emilkowal.ski) that exists outside the modal. The `<Toaster />` component exists in the root of the tree. It's kind of supposed to be global. Should I be putting that inside the `<dialog>` now?
> 
> <img alt="image" width="711" src="https://private-user-images.githubusercontent.com/38070918/331817887-7fe41ecc-dffe-497d-8e0f-d8bae5a7e7a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTczODMsIm5iZiI6MTcyNjc1NzA4MywicGF0aCI6Ii8zODA3MDkxOC8zMzE4MTc4ODctN2ZlNDFlY2MtZGZmZS00OTdkLThlMGYtZDhiYWU1YTdlN2EzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE0NDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZWNlMjk3Nzc2NTE0MjBlYjBmMDk0NWQ2MmI5NzgyMDQwNWUwNzc5NzAzYzJlMmU5NDM0OTAzNzZmMTVkZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tcfkyjLW4oV-L5yp8kLjNxP6vJRIOmZmTF4j_-LfV9k">
> EDIT: I found a workaround btw. It seems to work when I only use the `"modal-open"` class instead of the `.showModal()` and `.close()`. functions.
> 
> Basically if the modal was opened with `.showModal()` it will use the top-level layer or something so z-indexes wouldn't work?
> 
> But if It had the class `"modal-open"` instead, it would actually work. <img alt="image" width="511" src="https://private-user-images.githubusercontent.com/38070918/331847697-33c6f600-b0cd-43b6-9098-7fd801234913.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTczODMsIm5iZiI6MTcyNjc1NzA4MywicGF0aCI6Ii8zODA3MDkxOC8zMzE4NDc2OTctMzNjNmY2MDAtYjBjZC00M2I2LTkwOTgtN2ZkODAxMjM0OTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE0NDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MmMyMjhhMWY1NjFkNzU2NWI1ZGE4YzE1YzAzZWUxMjE5ZmViNTRjZGU1NDA0NWMxNjM4NzY5MjMzNDZlYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iCG3J1UON0Z4ga5IhzeuNVQSt70Ky0c6uar-HofEElw">

Excellent! worked for me! thanks!

**Comment by lars-hoeck** [comment]
Why was this closed? I see that it seems to be expected behavior of <dialog> but its not acknowleged in the documentation. Also the checkbox and anchor are marked as legacy which to me feels like they could be deprecated soon. So it feels like i dont have a long term solution for this problem(dont want to use the class workaround)? Please ether find a better way to handle moduls or remove the legacy tag from one of the other methodes.

**Comment by saadeghi** [comment]
> Why was this closed? 

https://github.com/saadeghi/daisyui/issues/2858#issuecomment-2010246981

> the checkbox and anchor are marked as legacy which to me feels like they could be deprecated soon. 

They are not going to be removed soon. They are tagged "legacy" because that was the old way. Using `<dialog>` is recommended because that's the new/correct HTML element to use for a modal. We're not going to suddenly remove anything.

> Please ether find a better way to handle moduls

https://github.com/saadeghi/daisyui/issues/2858#issuecomment-2113647233

If you have any specific challenge, please share the code so I can help 🙏

**Comment by lars-hoeck** [comment]
I found a solution for my problem. Instead of using ID.showModal() i use ID.show() which opens the modal in non-modal mode and therefore other elements can be layed on top with a higher z index (for exampel z-index: 9999).

https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/show

**Comment by farad-tech** [comment]
@Blankeos Thank you, your solution worked for me, This bug was really annoying.
