### ISSUE TITLE
Tooltip in menu horizontal with icon

### ISSUE THREAD

**Issue by esoteloferry** [saadeghi/daisyui#286]
Hi, 

First of all, I like your work and just want to say thanks for sharing it 👍 

I would like to use the menu - horizontal with icon in combination with tooltip on each icon. 

I took the example of menu and added the tooltip into `<li>` , also tried in `<a>` but did not work. 
I also tried wrapping up the `<a>` tag in a button but the tooltip still does not appear. 

Any idea how to make this? maybe I am missing something , I am a beginner in frontend. 

I am aware by exploring the issues that I could use the button-group  - use icons and add tooltip, but I really like the design of the menu , specially the bordered option. 

Thanks in advance.

**Comment by saadeghi** [comment]
@esoteloferry You need to add `overflow-visible` to the `menu`.  
example: https://play.tailwindcss.com/DMUyvDpsNq  

Reason:
> `menu` is using `overflow-hidden` to cut off the rounder corner on first and last menu items. `tooltip` goes outside of the container so it goes hidden.  

I will make some improvements on the next major version so this workaround won't be needed in the future.
