### ISSUE TITLE
docs: Anchors does not work for drawer page #drawer

### ISSUE THREAD

**Issue by svitiashchuk** [saadeghi/daisyui#2868]
### On which page do you see this issue?

https://daisyui.com/components/drawer/

### Describe the issue

There is a peculiar behavior on the drawer page. 

When copying a link to a particular section - https://daisyui.com/components/drawer/#drawer and navigating to that link, the page does not scroll, and it appears to be frozen (dropdowns, search and some other elements are not clickable).

#### Steps to reproduce:
- navigate to https://daisyui.com/components/drawer/#drawer
- try to click on search or theme/language dropdown

My guess that's due to the `input#drawer` element on that page.

```html
<input id="drawer" type="checkbox" class="drawer-toggle">
```

### What browsers are you seeing the problem on?

All browsers

**Comment by TheWilley** [comment]
I can confirm that the issue seems to be the input ID. After cloning and changing its ID to literally anything else the problem was resolved.

**Comment by saadeghi** [comment]
Do you have any other item with the same if on the page?


> changing its ID to literally anything else the problem was resolved

@svitiashchuk does this fix the issue?
