### ISSUE TITLE
bug: Can't style kbd when using prose

### ISSUE THREAD

**Issue by TaylanTatli** [saadeghi/daisyui#2872]
### What version of daisyUI are you using?

v4.7.2

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://play.tailwindcss.com/hKQyJqbKxM

### Describe your issue

KBD tag is unreadable when using dark themes. Test doesn't change with themes. Right now I'm using it like this:
```css
kbd {
  @apply kbd kbd-sm text-base-content !important;
}

```

**Comment by NikarashiHatsu** [comment]
This is actually an easy workaround, just apply `bg-base-100 dark:bg-base-content` to the `kbd` and you're good to go:

```html
<div class="prose" data-theme="">
  <div class="p-4">
    <kbd class="kbd bg-base-100 dark:bg-base-content">Keyboard</button>
  </div>
</div>
```

![Screenshot 2024-03-28 at 03 43 11](https://github.com/saadeghi/daisyui/assets/43662951/464a9efc-1ce7-4736-af15-b80eb868532b)

![Screenshot 2024-03-28 at 03 43 19](https://github.com/saadeghi/daisyui/assets/43662951/2373a80b-6dec-4c6e-aad2-06a31420ae0b)

It might need some time to fix it on library-level, so give it a go.

**Comment by kjeske** [comment]
I'm using this:

```css
:root .prose {
  --tw-prose-kbd: var(--tw-prose-body);
}
```
