### ISSUE TITLE
bug: the button is visible when the drawer is open , z-index doesn't work 

### ISSUE THREAD

**Issue by mohammjavad123** [saadeghi/daisyui#2873]
### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

  <div className="drawer z-30">         <input id="my-drawer" type="checkbox" className="drawer-toggle" />         <div className="drawer-content">           {/* Page content here */}           <label             htmlFor="my-drawer"             className="btn-primary btn drawer-button overflow-hidden"           >             Open drawer           </label>         </div>          <div className="drawer-side overflow-visible ">           <label             htmlFor="my-drawer"             aria-label="close sidebar overflow-visible "             className="drawer-overlay overflow-visible "           ></label>            <ul className="menu min-h-full w-4/12 overflow-visible bg-base-200 p-4 text-base-content">             <div className="w-11/12">               {' '}               <Drawer id={modal} categorylable={category.label} menu={menu} />             </div>             {/* Sidebar content here */}           </ul>         </div>       </div>

### Describe your issue

<img width="1440" alt="Screenshot 2024-02-27 at 14 10 54" src="https://github.com/saadeghi/daisyui/assets/54244996/133ab203-d393-4bfc-925c-28536cfb2a23">

**Comment by mohammjavad123** [comment]
<div className="drawer z-30">
        <input id="my-drawer" type="checkbox" className="drawer-toggle" />
        <div className="drawer-content">
          {/* Page content here */}
          <label
            htmlFor="my-drawer"
            className="btn-primary btn drawer-button overflow-hidden"
          >
            Open drawer
          </label>
        </div>

        <div className="drawer-side overflow-visible ">
          <label
            htmlFor="my-drawer"
            aria-label="close sidebar overflow-visible "
            className="drawer-overlay overflow-visible "
          ></label>

          <ul className="menu min-h-full w-4/12 overflow-visible bg-base-200 p-4 text-base-content">
            <div className="w-11/12">
              {' '}
              <Drawer id={modal} categorylable={category.label} menu={menu} />
            </div>
            {/* Sidebar content here */}
          </ul>
        </div>
      </div>

**Comment by saadeghi** [comment]
Please provide a minimum reproduction link
