### ISSUE TITLE
bug: The drop-down menu is blocked by other elements with （relative，filter, opacity） attributes such as

### ISSUE THREAD

**Issue by mgl-pub** [saadeghi/daisyui#2879]
### What version of daisyUI are you using?

4.7.2

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://play.tailwindcss.com/pv83KjArts

### Describe your issue

![Screenshot from 2024-02-29 10-42-18](https://github.com/saadeghi/daisyui/assets/4723621/8dbc09e2-749d-4e11-9771-8e6a389edac5)
![Screenshot from 2024-02-29 10-42-34](https://github.com/saadeghi/daisyui/assets/4723621/db64f5f4-9f70-4a94-b6aa-5165227c42ac)
![Screenshot from 2024-02-29 10-43-13](https://github.com/saadeghi/daisyui/assets/4723621/ed16d745-87a1-4a5a-8616-81103756ca12)
![Screenshot from 2024-02-29 10-43-32](https://github.com/saadeghi/daisyui/assets/4723621/f760e4cf-817e-45cd-ad8e-8f7ab53a85d1)

**Comment by Aravin** [comment]
@mgl-pub you can use z-index to fix this issue.

**Comment by saadeghi** [comment]
Here's an example of using z-index:  
https://play.tailwindcss.com/OpDgqCSiDT

The reason we don't use z-index values in the components by default is that z-index value should be decided based on the content of the page. sometimes you may want a menu to be on top of another element or sometimes you may want other elements to be on top.

Let me know if you have a question.
