### ISSUE TITLE
Close drawer right after clicked on an item in it?

### ISSUE THREAD

**Issue by KAnh262** [saadeghi/daisyui#288]
Hi, I'm using daisyui drawer as a sidebar for my project and it's working perfectly on desktop.
Just one small problem on mobile that it's not close after clicked on some item inside of the drawer, is there anyway to solve this?

**Comment by saadeghi** [comment]
@KAnh262 If it's not a SPA, clicking on links sends the user to new page and we won't need to close the drawer.  
But if it's a SPA (like Sveltekit, Nuxt, Next, etc...) you need to manually uncheck the checkbox that controls the drawer.

Vue example: https://codesandbox.io/s/funny-estrela-kkf02?file=/src/App.vue

**Comment by ninsky** [comment]
Also see here https://github.com/saadeghi/daisyui/issues/297
