### ISSUE TITLE
bug: Navbar dropdown doesn't close on the option click

### ISSUE THREAD

**Issue by Aravin** [saadeghi/daisyui#2880]
### What version of daisyUI are you using?

4.7.0

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://www.exaful.com/

### Describe your issue

![image](https://github.com/saadeghi/daisyui/assets/4869265/5cf0b1c4-83b9-43af-a996-78e4eeae64b3)

The dropdown is getting closed after choosing the option.

**Comment by saadeghi** [comment]
When the site is an SPA, clicking on links doesn't actually change the page. Instead your JS framework replaces the content with the new content. So It is expected for the dropdown to stay open because it is still focused.  

To close it, you can remove the focus from it using JS after the link is clicked.  
Let me know if you have any questions

**Comment by i0FFLINE** [comment]
> To close it, you can remove the focus from it using JS after the link is clicked. Let me know if you have any questions

any idea how to?

**Comment by Aravin** [comment]
I haven't done it yet. We have to use router/navigation and see the change in pathname accordingly modify the state of the navbar

**Comment by i0FFLINE** [comment]
I am stuck on the following:
- under hamburger in the mobile version in the details submenu, language selection is not closing, but the menu itself is closing. i reopen it - language selection is still open.
I use `document.activeElement.blur()`, but I understand that I need to close the whole menu in cascade.
any ideas?

**Comment by Aravin** [comment]
share the actual code or code sample.

**Comment by i0FFLINE** [comment]
```vue
<template>
    <div class="navbar py-1 px-2 bg-gradient-to-r from-slate-900 to-slate-600 text-light shadow-lg dark:shadow-none">
        <div class="flex-1">
            <a href="#" class="btn pl-1.5 btn-ghost text-xl">
                <Logo class="h-9 mr-3" /* SVG inside */ />
                {{ APP_NAME }}
            </a>
        </div>
        <div class="flex-none">
            <ThemeToggle class="h-full" /* SWAP inside */ />
            <!-- Mobile version navbar-hamberger -->
            <ul class="menu menu-horizontal pl-1 pr-0.5 gap-5 md:hidden">
                <li>
                    <div class="dropdown dropdown-bottom dropdown-end focus:outline-none active:outline-none p-0">
                        <div role="button" tabindex="0">
                            <svg>
                                <!-- cut -->
                            </svg>
                        </div>
                        <ul class="dropdown-content z-[1] menu bg-slate-700">
                            <li>
                                <details>
                                    <summary>{{ SELECTED_LOCALE }}</summary>
                                    <ul class="dropdown-content z-[1] menu bg-slate-700">
                                        <li v-for="(sli, slk) in SUPPORT_LOCALE_NAMES" :key="slk">
                                            <a href="#" onclick="document.activeElement.blur()">{{ sli }}</a>
                                        </li>
                                    </ul>
                                </details>
                            </li>
                            <li><a href="#" onclick="document.activeElement.blur()">Link1</a></li>
                            <li><a href="#" onclick="document.activeElement.blur()">Link2</a></li>
                            <li><a href="#">Settings</a></li>
                            <li><a href="#">Logout</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</template>
```
...something lke that

**Comment by saadeghi** [comment]
@xl0 
>Any chance you could document the best way to do this?

I wish, but there's no _best way_. It's different for each framework.  

There's a newly available HTML popover API which will fix this issue hopefully. We're expecting it to be the standard way to handle dropdowns in the next version of daisyUI.

**Comment by Aravin** [comment]
@saadeghi Is this feature add to beta version of daisyUI 5?

**Comment by saadeghi** [comment]
@Aravin Yes 🎉
