### ISSUE TITLE
docs:   Is there any way to change the 'base' value at runtime?

### ISSUE THREAD

**Issue by Ilwel** [saadeghi/daisyui#2884]
### Describe the issue

It can be done in the configuration file, but I need to do it dynamically so that it is applied to a specific theme instead of all themes.

![image](https://github.com/saadeghi/daisyui/assets/38703179/386a1e26-07f2-415e-93bc-63bb3e99cc6a)

**Comment by saadeghi** [comment]
Please don't open issues for asking questions.  
To change a color on runtime, you can set the CSS variable value.  
This table shows the CSS variable for each color:  
https://daisyui.com/docs/colors/

`base-100` CSS variable is `--b1` and its value should be OKLCH color.

Here are all the built-in themes:  
https://unpkg.com/browse/daisyui@4.7.2/dist/themes.css
