### ISSUE TITLE
bug: Glass Utility is not working in firefox

### ISSUE THREAD

**Issue by Benyaminrmb** [saadeghi/daisyui#2885]
### What version of daisyUI are you using?

v4.7.2

### Which browsers are you seeing the problem on?

Firefox

### Reproduction URL

https://daisyui.com/docs/utilities/#-2

### Describe your issue

There is no blur effect in Firefox like we have in Chrome

**Comment by irsyadpage** [comment]
@Benyaminrmb Which Firefox version did you use?

Please make sure it is version 103 or above because the `backdrop-filter` feature only enabled by default since Firefox version 103.

Refer here: [CSS Backdrop Filter](https://caniuse.com/css-backdrop-filter)

**Comment by Benyaminrmb** [comment]
> @Benyaminrmb Which Firefox version did you used?
> 
> Please make sure it is version 103 or above because the `backdrop-filter` feature only enabled by default since Firefox version 103.
> 
> Refer here: [CSS Backdrop Filter](https://caniuse.com/css-backdrop-filter)

@irsyadpage my Firefox version is : 123.0.1

**Comment by irsyadpage** [comment]
I tested in my Firefox and its working correctly.

![Capture](https://github.com/saadeghi/daisyui/assets/14093866/1cfe8108-2950-4e5b-b7bf-ae4b3c570797)

Maybe you could:
1. Share the screenshot of your Firefox window
2. Try use other "glass-effect" tools such as [here](https://10015.io/tools/css-glassmorphism-generator) to ensure the  `backdrop-filter` feature working correctly in your Firefox browser.

**Comment by irsyadpage** [comment]
Maybe you could try a fresh Firefox installation (remove user data / profiles / etc before re-install) and see if the problem still persist.

**Comment by saadeghi** [comment]
@Benyaminrmb Could you find a solution?
