### ISSUE TITLE
Button loading indicator could be improved/refurbished

### ISSUE THREAD

**Issue by VyMajoris** [saadeghi/daisyui#289]
Using 1.16.0

Right now the loading indicator looks dotted/jagged and sometimes it doesn't form a proper half-circle when it is small:
![image](https://user-images.githubusercontent.com/4342296/140550935-a39c1aa5-c4a8-4b78-a9c8-3110332c1a47.png)

Maybe it would be better to switch to a SVG based solution?

**Comment by saadeghi** [comment]
@VyMajoris is this screenshot from Firefox?

**Comment by VyMajoris** [comment]
> @VyMajoris is this screenshot from Firefox?

No, that was on Edge. Here is a comparison:
![image](https://user-images.githubusercontent.com/4342296/140648292-635e9983-35b4-4044-8318-efdef6a042db.png)

It's subtle, but you can see that on Edge and on Chrome there are some "dots" where the white color is faded. I believe this is caused because the browser is not interlacing the rounded border to a sufficient degree. So when you make it small it seems that some parts gets "phased out".

**Comment by neotan** [comment]
not sure if changing the defult spin icon to a radial one is an option, that will make the aliasing unnoticeable.

![image](https://user-images.githubusercontent.com/10399087/144697813-c0d532f1-c97c-4979-9f6d-3ff6ea3be51d.png)

**Comment by TylerAHolden** [comment]
The current spinner spins sooooo slooowwwlllyyy it kinda makes the UI feel slow. I'm looking to speed it up! Easy to do with custom CSS but I figured I'd mention here that I would personally prefer a faster default animation closer to .5s or .3s rather than the 2s default.

**Comment by saadeghi** [comment]
> The current spinner spins sooooo slooowwwlllyyy it kinda makes the UI feel slow. I'm looking to speed it up! Easy to do with custom CSS but I figured I'd mention here that I would personally prefer a faster default animation closer to .5s or .3s rather than the 2s default.

That button `loading` class is going to change in daisyUI `3.0`  
But for now you can change the speed using custom CSS or using an ugly class like `[&.btn:before]:[animation-duration:.3s]`: https://play.tailwindcss.com/DlrGGnPgW1
