### ISSUE TITLE
bug: Issue disabling background color

### ISSUE THREAD

**Issue by benzon** [saadeghi/daisyui#2890]
### What version of daisyUI are you using?

latest

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://play.tailwindcss.com/IIWW8U8Zeq

### Describe your issue

I have tried every possible solution I could come up with to get the background color removed, base: false, in tailwind settings, adding bg-transparet to html, and body, but nothing works.

Is there a viable solution to actually disable the background color, should not be this hard.

**Comment by saadeghi** [comment]
> I have tried every possible solution I could come up with to get the background color removed, base: false, in tailwind settings

https://play.tailwindcss.com/DKSx32y4RT?file=config

>adding bg-transparet to html, and body, but nothing works.

https://stackblitz.com/edit/daisyui-vite-lh5tai/?file=index.html

**Comment by benzon** [comment]
> > I have tried every possible solution I could come up with to get the background color removed, base: false, in tailwind settings
> 
> https://play.tailwindcss.com/DKSx32y4RT?file=config
> 
> > adding bg-transparet to html, and body, but nothing works.
> 
> https://stackblitz.com/edit/daisyui-vite-lh5tai/?file=index.html

Might be the dark theme then that got issues, since thats what from the css info i can find that im currently using, and that one refuses to change the background color

**Comment by saadeghi** [comment]
Can you tell me what is the goal? Do you want to set a specific color for the background?  
Dark themes have `color-scheme: dark` which sets enables the dark mode on the page including background color, text color, scrollbar color, select dropdowns etc.

It's not a color you can remove but you can set any color to the page using class names.

**Comment by benzon** [comment]
I'm doing a game specific ui, and the main design of the ui is based on dark colors, i would need a transparent background in general, since it's only the UI it self that should have colors, the background should be transparent, so you can actually see the game it self.

**Comment by ValdemarLarsen** [comment]
@benzon Kontakt mig på discord: valdemar._.

Min ven har fundet et fiks til det :D
