### ISSUE TITLE
bug: countdown component value positioning error

### ISSUE THREAD

**Issue by efeiron** [saadeghi/daisyui#2891]
### What version of daisyUI are you using?

v4.7.2

### Which browsers are you seeing the problem on?

IOS Safari

### Reproduction URL

https://play.tailwindcss.com/8GDZkmH9Va

### Describe your issue

I have issue with countdown component.

For some reason it doesn't look like it should.

Its working perfect in all browsers except IOS safari and IOS app and here is screenshot below. 
![IMG_87D7E1186E8F-1](https://github.com/saadeghi/daisyui/assets/90838471/23bd45c7-9ece-465f-8c7f-c5ab0e3ec8b0)

**Comment by saadeghi** [comment]
I can't see the issue on iOS Safari

<img width="531" alt="Screenshot 2024-04-03 at 6 57 49 PM" src="https://github.com/saadeghi/daisyui/assets/7342023/bea0cb67-87c6-4e8d-8f2e-e897c9ca3b17">

**Comment by efeiron** [comment]
Yes, when I look at the DaisyUI countdown component page from iOS Safari, it appears normal. I'm using Ionic to build an application, so there might be some conflicting style definitions. Thanks anyway.

**Comment by efeiron** [comment]
It's strange that it works fine in Chrome and macOS Safari but encounters issues in iOS Safari. I'm going to change the way I set the values and hope for the best.
