### ISSUE TITLE
Full width/ responsive tabs?

### ISSUE THREAD

**Issue by Nikola-Milovic** [saadeghi/daisyui#290]
Hello, I am looking for a way to get tabs to be responsive/ fill the width available. As currently there is little to no use for fixed-sized tabs. Any examples of how to achieve this?

Eg have this fill the entire width of the screen 
```
<div class="tabs">
  <a class="tab tab-bordered">Tab 1</a> 
  <a class="tab tab-bordered tab-active">Tab 2</a> 
  <a class="tab tab-bordered">Tab 3</a>
</div>
```

**Comment by saadeghi** [comment]
@Nikola-Milovic You can use `grid-flow-col`  
Example: https://play.tailwindcss.com/rGuoMT54dj
