### ISSUE TITLE
bug: Buttons in modals have unexpected borders when content behind them is focused

### ISSUE THREAD

**Issue by vsquared56** [saadeghi/daisyui#2900]
### What version of daisyUI are you using?

v4.6.1

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://play.tailwindcss.com/EzYAemZy7d

### Describe your issue

When a modal is opened in a way that seems to leave focus on another element, buttons inside the modal seem to have an unexpected border.  Please see the example on [Tailwind Play](https://play.tailwindcss.com/EzYAemZy7d).

I'm not quite certain that it's related to focus, but e.g. clicking on a `div` to open the modal reproduces the issue, while clicking on a `button` to open the modal does not:

![image](https://github.com/saadeghi/daisyui/assets/6411694/dcf63010-3874-4565-b080-44f0ff87f0f9)

![image](https://github.com/saadeghi/daisyui/assets/6411694/6fcbc534-217a-47f0-9ac2-57cbb1f653ad)

Clicking away within the modal causes the unexpected border to disappear, and usually prevents the issue from coming back for some time.  But, I can usually reproduce the issue again by manually bringing focus to the `div` in Dev Tools, e.g.

![image](https://github.com/saadeghi/daisyui/assets/6411694/44b1bbc4-ca22-439c-9cf4-5a8a1370c8a7)

Thanks in advance for the help!

**Comment by saadeghi** [comment]
It's not unexpected. It's just how HTML `<dialog>` element works.  
When we open it using keyboard, the first focusable element inside `<dialog>` gets the focus because everything outside `<dialog>` can not be focused while the dialog is open.

Let me know if you have a question.
