### ISSUE TITLE
What's the correct way to use `select` with `multiple`

### ISSUE THREAD

**Issue by turukawa** [saadeghi/daisyui#291]
I want to select multiple items in a select list. Adding `multiple` to the input/select component results in this:

![image](https://user-images.githubusercontent.com/998523/140642443-c7be841c-477e-4369-8fee-1c118a887f64.png)

Ideally, I'd like a dropdown, but even trying to increase the element height does nothing (using `size="8"` has no effect). This is the code:

```
<select class="select select-bordered w-full max-w-xs" multiple>
  <option disabled="disabled" selected="selected">Choose your superpowers</option> 
  <option>telekinesis</option> 
  <option>time travel</option> 
  <option>invisibility</option>
</select>
```

Is there a better way to do this?

**Comment by saadeghi** [comment]
@turukawa Adding a height class (like `h-20`) is the best we can do. example: https://play.tailwindcss.com/OIpl7qbi1P  
It doesn't look pretty but that's the best we can get using CSS only.  
An alternative way is to use checkboxes. Checkbox is easier to use and we can style them using CSS anyway we want.
