### ISSUE TITLE
bug:  Checkbox input not responsive if checked value is "true"

### ISSUE THREAD

**Issue by wackazong** [saadeghi/daisyui#2911]
### What version of daisyUI are you using?

v4.7.3

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://play.tailwindcss.com/dbreoATM6k

### Describe your issue

See Tailwind play. I would expect all toggles to work.

**Comment by yanggggjie** [comment]
I tested your case.

According to source code,  in this file: https://github.com/saadeghi/daisyui/blob/master/src/components/styled/toggle.css
line 24.

&[checked="true"]
This selector will always select the <input type="checkbox" class="toggle" checked="true"/>.

I copy the case code in playground to reproduce in local and reomove the selector, it works well.
Like this:
<img width="452" alt="image" src="https://github.com/saadeghi/daisyui/assets/60206592/79b5d811-8d8d-4d33-a147-5d0ca8e99d71">

**Comment by wackazong** [comment]
I agree. If that selector is removed then the toggle behaves as expected in all cases. As a workaround I remove this selector now manually in my tailwind setup.
