### ISSUE TITLE
bug: DaisyUI doesn't detect classes when using template litterals

### ISSUE THREAD

**Issue by Splinteer** [saadeghi/daisyui#2913]
### What version of daisyUI are you using?

4.7.2

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://stackblitz.com/edit/daisyui-angular-bys9bg?file=src%2Fapp%2Fbutton.component.ts

### Describe your issue

Classes like btn-primary, btn-secondary... are not working when using template litterals in TypeScript.
I need to do:
```ts
export type ButtonColor =
  | 'neutral'
  | 'primary'
  | 'secondary'
  | 'accent'
  | 'info'
  | 'success'
  | 'warning'
  | 'error'
  | 'ghost'
  | 'link';

type ButtonColorClass = 

    | 'btn-neutral'
    | 'btn-primary'
    | 'btn-secondary'
    | 'btn-accent'
    | 'btn-info'
    | 'btn-success'
    | 'btn-warning'
    | 'btn-error'
    | 'btn-ghost'
    | 'btn-link';
```

Instead of 
```ts
type ButtonColorClass = `btn-${ButtonColor}`;
```
to have my button with a working btn-primary class

**Comment by saadeghi** [comment]
It's not related to daisyUI. It's how Tailwind CSS works. All class names should exist in the file as a string:   
https://tailwindcss.com/docs/content-configuration#dynamic-class-names
