### ISSUE TITLE
docs: toast

### ISSUE THREAD

**Issue by ZhangPeibin** [saadeghi/daisyui#2921]
### On which page do you see this issue?

https://daisyui.com/components/toast/

### Describe the issue

Toast messages are usually used to display temporary notifications on the application interface. They will automatically disappear after a period of time.

Based on the above, I think the page should list Toast as a component, and then give different styles in the demo to display different toasts.

**Comment by twf-nikhila** [comment]
agree to this

**Comment by saadeghi** [comment]
Thanks for the suggestion but issue section is for reporting bugs.

>Toast messages are usually used to display temporary notifications on the application interface. They will automatically disappear after a period of time.

This description is different from what daisyUI provides for `toast` class name.

>Toast is a wrapper to stack elements, positioned on the corner of page.

even though you can achieve the described behavior using JS (to hide the element after a period of time)
