### ISSUE TITLE
bug: Failed to switch themes in mobile browser.

### ISSUE THREAD

**Issue by DataSciSorcerer** [saadeghi/daisyui#2924]
### What version of daisyUI are you using?

v4.4.19

### Which browsers are you seeing the problem on?

Chrome Android

### Reproduction URL

http://8.130.146.80/#/index/register

### Describe your issue

![image](https://github.com/saadeghi/daisyui/assets/145595300/cbec678d-3901-4a9d-b375-d37efe656287)
**☝🏻☝🏻☝🏻☝🏻☝🏻The theme can be switched normally and the background is black**
![a947e837ec893516689ea99985aa63d](https://github.com/saadeghi/daisyui/assets/145595300/348df0eb-0c64-45be-8fd1-0a9d62cd10ec)
**☝🏻☝🏻☝🏻☝🏻☝🏻When I open it on the mobile browser, I cannot switch the theme and the background color does not take effect. I am using Vue+Vite.**
**[This is project url](http://8.130.146.80/#/index/register)**

**Comment by saadeghi** [comment]
What's the version of your "mobile browser"? Because it's working for me.

**Comment by DataSciSorcerer** [comment]
https://github.com/saadeghi/daisyui/assets/145595300/a816b4d7-b337-46b2-a867-ac0ff3d4027c

**Only the button's rounded corners have changed**

**Comment by saadeghi** [comment]
This is how `theme-controller` works: it switches between the current theme and the theme specified for its value (`dracula` in your code)

And by default, daisyUI provides automatic dark mode based on OS/browser settings. So when the OS/browser is in dark mode, the `theme-controller` will switch from dark theme and `dracula` theme (both are dark)  

You can force the theme to be light and then you can use `theme-controller` to switch it to dark.   
Add `darkTheme: false` config to disable the automatic dark mode. This way the page will be light by default and it will be dark when `theme-controller` is clicked.

Let me know if you have a question.
