### ISSUE TITLE
bug: show sidebar content when using drawer-end class and press 'tab'

### ISSUE THREAD

**Issue by YeongCheon** [saadeghi/daisyui#2925]
### What version of daisyUI are you using?

v4.7.3

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://daisyui.com/components/drawer/#drawer-that-opens-from-right-side-of-page

### Describe your issue

when i click background(no 'open drawer' button) and press 'tab' key, sidebar is exposed, but I can't hide it again or click on the sidebar menu.

![Screenshot from 2024-03-21 00-10-47](https://github.com/saadeghi/daisyui/assets/17349021/ae2c19c4-e879-4c33-990e-90671a7e0f1c)

**Comment by saadeghi** [comment]
I see.  
It's possible to click button again to open/close the drawer.  
But unfortunately currently there's no way to fix this using CSS.  

A good solution would is adding/removing `inert` attribute to the sidebar using JS whenever the sidebar is closed. I wish it would be possible using CSS only but it's not.

Let me know if you have a question.
