### ISSUE TITLE
bug: I cannot keep the lines of the timeline component on the left or right side

### ISSUE THREAD

**Issue by ajiho** [saadeghi/daisyui#2928]
### What version of daisyUI are you using?

v4.7.3

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://vuetifyjs.com/zh-Hans/components/timelines/#section-65b95411-side

### Describe your issue

I consider daisyui as a replacement for bootstrap. I like this timeline component, but it cannot make the timeline always displayed on one side like some other UI libraries,[vertical-timeline-with-bottom-side-only](https://daisyui.com/components/timeline/#vertical-timeline-with-bottom-side-only)Although this example can only be displayed on one side, there is still a large blank space on the left. What should I do?

**Comment by saadeghi** [comment]
There's a `timeline-compact` class:  
https://play.tailwindcss.com/GjsbZ8rih9

Let me know if you have a question.
