### ISSUE TITLE
Copy paste components

### ISSUE THREAD

**Issue by hiteshkothari** [saadeghi/daisyui#293]
Giving the copy button for the html components for using

**Comment by fengkiej** [comment]
that's actually a good idea, something like hyperui.dev, it should be more customizable

**Comment by saadeghi** [comment]
Fixed

**Comment by hiteshkothari** [comment]
Loving the new feature

**Comment by luqmanusman** [comment]
Hi,

unable to copy partial component text or even copy option not available in customized components, colors, themes, Layout & Typography, kindly give copy option on all your components so that we can easily copy full or partial text.

Thanks / Luqman
