### ISSUE TITLE
bug: CDN build does not include outline colors

### ISSUE THREAD

**Issue by seanaye** [saadeghi/daisyui#2944]
### What version of daisyUI are you using?

v4.9.0

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://stackblitz.com/edit/daisyui-cdn-fv1he5?file=index.html

### Describe your issue

The daisyui cdn build does not include any of the outline colors as shown in the repro

**Comment by code-lwh** [comment]
Using CDN to impot daisyui has had many issues in the past, if you need to use it, the best option here is to try to get the class name and styles (if you have VS code intellisense it will come in clutch) and apply those styles in your global CSS file
