### ISSUE TITLE
Build version colors not proper

### ISSUE THREAD

**Issue by swaroop18122002** [saadeghi/daisyui#295]
I am using the cupcake theme and the dracula theme for dark mode. In the build version dracula theme's colors are working fine, but the cupcake theme colors aren't same and also the button styling isn't the same in the cupcake theme

repo URL - 
[https://github.com/swaroop18122002/daisyui-small-project.git](url)

build version - 
https://admiring-franklin-548fcf.netlify.app/

development version -
[https://cizm5.sse.codesandbox.io/](url)

**Comment by saadeghi** [comment]
@swaroop18122002 It looks like other themes are getting purged in your production build.  
Try safe listing `/data-theme$/` in tailwind.config.js  
More info: https://daisyui.com/docs/default-themes

Please let me know if have any questions.
