### ISSUE TITLE
CDN url return 404

### ISSUE THREAD

**Issue by davidjr82** [saadeghi/daisyui#296]
In the docs, customize components section: https://daisyui.com/docs/customize

There is a link to the base styles https://cdn.jsdelivr.net/npm/daisyui@1.16.2/base.css in the CDN 

This link points to a non existing resource.

**Comment by saadeghi** [comment]
@davidjr82 It should be [unstyled.css](https://cdn.jsdelivr.net/npm/daisyui@1.16.2/dist/unstyled.css). Fixed on docs. thanks
