### ISSUE TITLE
bug: dropdown not working

### ISSUE THREAD

**Issue by dhumal436** [saadeghi/daisyui#2960]
### What version of daisyUI are you using?

4.9.0

### Which browsers are you seeing the problem on?

Chrome, Edge

### Reproduction URL

https://play.tailwindcss.com/c8RaIchMFr

### Describe your issue

I am using a theme controller to change the theme but dropdown works sometimes some time it won't  work when I investigated I found classes are not loading for the dropdown 

below is code for dropdown 
```<div className="dropdown mb-72">
  <div tabIndex={0} role="button" className="btn m-1">
    Theme
    <svg width="12px" height="12px" className="h-2 w-2 fill-current opacity-60 inline-block" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2048 2048"><path d="M1799 349l242 241-1017 1017L7 590l242-241 775 775 775-775z"></path></svg>
  </div>
  <ul tabIndex={0} className="dropdown-content z-[1] p-2 shadow-2xl bg-base-300 rounded-box w-52">
    <li><input type="radio" name="theme-dropdown" className="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="Default" value="default"/></li>
    <li><input type="radio" name="theme-dropdown" className="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="Retro" value="retro"/></li>
    <li><input type="radio" name="theme-dropdown" className="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="Cyberpunk" value="cyberpunk"/></li>
    <li><input type="radio" name="theme-dropdown" className="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="Valentine" value="valentine"/></li>
    <li><input type="radio" name="theme-dropdown" className="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="Aqua" value="aqua"/></li>
  </ul>
</div>```

**Comment by saadeghi** [comment]
> https://play.tailwindcss.com/c8RaIchMFr

Here for the second dropdown you're using `tabIndex={0}` which is not valid HTML. It's JSX. Use `tabindex="0"` and [it works](https://play.tailwindcss.com/UrkcWJLQ9A)



> below is code for dropdown
> 
> ```
>   <div tabIndex={0} role="button" className="btn m-1">
>     Theme
>     <svg width="12px" height="12px" className="h-2 w-2 fill-current opacity-60 inline-block" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2048 2048"><path d="M1799 349l242 241-1017 1017L7 590l242-241 775 775 775-775z"></path></svg>
>   </div>
>   <ul tabIndex={0} className="dropdown-content z-[1] p-2 shadow-2xl bg-base-300 rounded-box w-52">
>     <li><input type="radio" name="theme-dropdown" className="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="Default" value="default"/></li>
>     <li><input type="radio" name="theme-dropdown" className="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="Retro" value="retro"/></li>
>     <li><input type="radio" name="theme-dropdown" className="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="Cyberpunk" value="cyberpunk"/></li>
>     <li><input type="radio" name="theme-dropdown" className="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="Valentine" value="valentine"/></li>
>     <li><input type="radio" name="theme-dropdown" className="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="Aqua" value="aqua"/></li>
>   </ul>
> </div>```
> ```

Working example: https://play.tailwindcss.com/SJoOx0psWq  
Make sure you enabled the needed themes in config: https://play.tailwindcss.com/SJoOx0psWq?file=config

Let me know if you have a question.
