### ISSUE TITLE
bug: tooltip crashes when theme is an empty array

### ISSUE THREAD

**Issue by this-oliver** [saadeghi/daisyui#2962]
### What version of daisyUI are you using?

4.7.2

### Which browsers are you seeing the problem on?

Safari, Safari iOS, Firefox

### Reproduction URL

https://play.tailwindcss.com/TQ3VC9hEFg

### Describe your issue

The tool tip crashes when the theme config in `tailwind.config.ts` is empty:

```json
{
 "daisyui": {
  "themes": []
 }
}
```

**Comment by saadeghi** [comment]
Crash?  
It just loses all the colors, like other components. You can add colors to it manually, or by defining a daisyUI theme using color variables.    
https://play.tailwindcss.com/xLYmX24vEW

Let me know if you have a question.

**Comment by this-oliver** [comment]
I see.

Apologies for the misunderstanding and thanks for explaining. Have a nice day!
