### ISSUE TITLE
How to close DaisyUI drawer menu with just one click?

### ISSUE THREAD

**Issue by ninsky** [saadeghi/daisyui#297]
_This is a copy of following Stackoverflow question. Maybe this question is unrelated on this tracker. Then just close it.
https://stackoverflow.com/questions/69941166/how-to-close-daisyui-drawer-menu-with-just-one-click_

I'm using the DaisyUI drawer component to render a menu on mobile. In the DaisyUI drawer example there's a button which can be used to open and close the mobile menu.

The button triggers a checked status on following checkbox to show/hide the drawer:

`<input id="my-drawer" type="checkbox" class="drawer-toggle">`

My code:
```
let checked = 'checked';

function handleClick() {
    (checked == 'checked') ? checked = '': checked = 'checked';
}
```

On the input:
`<input id="my-drawer-3" type="checkbox" class="drawer-toggle" bind:checked={checked}>`

On the menu item:
`<a on:click={handleClick} href='/test'>Test</a>`

The problem is that I have to click two times to hide the drawer. The first click triggers a visual effect on the menu item. The second click closes the drawer. How can I achive the same result with just one click? Is it possible to skip the visual effect somehow or is there any other solution?

**Comment by saadeghi** [comment]
@ninsky Here's an example using your code: https://svelte.dev/repl/ebfca7afdac04be9acae9940d591a8a8?version=3.44.1  
and everything works as expected 🤔

**Comment by ninsky** [comment]
@saadeghi , thanks for your help. It's fun. It works on REPL but not on my local environment. So I think it's not a DaisyUI problem. Must be something Svelte specific. Anyway, thank for having a look at it.

**Comment by ninsky** [comment]
I leave this open for you to verify my last comment, thanks.

**Comment by saadeghi** [comment]
@ninsky Thanks for the example.  
The problem is, you should either use the css-only approach (labels to open/close the drawer), or use a JS variable (with `on:click`). In your example, the menu opens with the label (for checkbox) but it closes with `on:click` so the first time the link gets clicked, the variable doesn't have the correct value because checkbox can't change the JS variable.
  
Here I replaced the hamburger menu from `label` to `<button on:click={handleClick}`:  
https://svelte.dev/repl/7db0794efa0543a0a36f59caf92c457a?version=3.29.7

**Comment by JulienQHN** [comment]
### SolidJs
For anyone looking about this with Solid, i managed to succeed this but i'ts a bit tricky : 

Like ninsky said above, same problem here, I had to click two times on a button to close the drawer, but if i pass my **toggle** on the `<li>` and the `<a>`, for some reason it's working.

This code is based on this daisyUI [example](https://daisyui.com/components/drawer/?lang=en#navbar-menu-for-desktop--sidebar-drawer-for-mobile) !

This is functional, anyway any explanations or better solution would be much appreciated !

```
const Header: Component = () => {
    const [isDrawerOpen, setDrawerOpen] = createSignal(false);
  const toggle = () => setDrawerOpen(!isDrawerOpen());
return (
<div class="drawer">
        <input
          id="my-drawer-3"
          type="checkbox"
          class="drawer-toggle"
          checked={isDrawerOpen()}
        ></input>
        <div class="drawer-content flex flex-col">
          <label for="my-drawer-3" class="btn btn-square btn-ghost">
            Open the drawer
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M4 6h16M4 12h16M4 18h16"
            ></path>
          </label>
        </div>
        <div class="drawer-side">
          <label for="my-drawer-3" class="drawer-overlay"></label>
          <ul class="menu p-8 overflow-y-auto w-80 bg-base-100">
            <li onClick={toggle} class="py-2">
              <a onClick={toggle} href="/#whatevere">
                CONTACT
              </a>
            </li>
          </ul>
        </div>
      </div>  
   );
};
```

**Comment by kkharji** [comment]
@JulienQHN Thanks for that.  It worked for me for a bit and indeed faced similar issue with il and a tag then when I made the signal global it totally stoped. 

Have you figured out a better solution?

**Comment by santy18** [comment]
@kkharji  i think i have found a better solution, so, I noticed that I on change event was fired normally, so i tapped to that and i was able to open and close the drawer correctly. hope it helps
`
const Header: Component = () => {
    const [isDrawerOpen, setDrawerOpen] = createSignal(false);
  const toggle = () => setDrawerOpen(!isDrawerOpen);
return (
<div class="drawer">
        <input
          id="my-drawer-3"
          type="checkbox"
          class="drawer-toggle"
          checked={isDrawerOpen}
          onChange={toggle}
        ></input>
        <div class="drawer-content flex flex-col">
          <label for="my-drawer-3" class="btn btn-square btn-ghost">
            Open the drawer
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M4 6h16M4 12h16M4 18h16"
            ></path>
          </label>
        </div>
        <div class="drawer-side">
          <label for="my-drawer-3" class="drawer-overlay"></label>
          <ul class="menu p-8 overflow-y-auto w-80 bg-base-100">
            <li class="py-2">
              <a onClick={toggle} href="/#whatevere">
                CONTACT
              </a>
            </li>
          </ul>
        </div>
      </div>  
   );
};

`
