### ISSUE TITLE
BUG: `tabs-lg` screws up layout

### ISSUE THREAD

**Issue by Pithikos** [saadeghi/daisyui#2970]
### What version of daisyUI are you using?

4.10.1

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://codepen.io/Nijoko/pen/BaExxeW

### Describe your issue

I'm trying to alter the official tabs example, but for simple changes it just doesn't play nicely. (This is on Vue3 for reference if it matters)

![image](https://github.com/saadeghi/daisyui/assets/400048/17610bf5-c2a1-417b-a482-280a80d2731f)

The [official example](https://daisyui.com/components/tab/#bordered) kind of works okayish as seen in the screenshot. Changing `tabs` to `tabs-lg` totally screws up the layout

![image](https://github.com/saadeghi/daisyui/assets/400048/1df533c6-f704-478b-b5a3-a9f93070bdfb)

**Comment by saadeghi** [comment]
I thing you forgot to use the `tabs` class.
```diff
- <div role="tablist" class="tabs-lg tabs-bordered">
+ <div role="tablist" class="tabs tabs-lg tabs-bordered">
```
`tabs-lg` is a modifier for `tabs`. It's not a replacement.

Let me know if you have a question.
