### ISSUE TITLE
Feature Request: Floating Labels

### ISSUE THREAD

**Issue by danielschweiger** [saadeghi/daisyui#298]
Can you add:
https://getbootstrap.com/docs/5.0/forms/floating-labels/

**Comment by saadeghi** [comment]
@danielschweiger I'm not going to add it to daisyUI. It's a Material Design pattern.  
However, you can do it using Tailwind CSS JIT utilities.  
example: https://play.tailwindcss.com/LlEaBvciDN
or: https://play.tailwindcss.com/gFvNyldAPJ?file=css
