### ISSUE TITLE
change hover background in dropdown menu list

### ISSUE THREAD

**Issue by allaghi** [saadeghi/daisyui#299]
Hello, 
I am trying to custom hover in dropdown list from gray to another color but it didn't work my code is 
`<li><NuxtLink to="/vehicles/inventory" class="hover:text-white hover:bg-black">Inventory</NuxtLink></li>`

I am using daisyui with nuxt js.

**Comment by saadeghi** [comment]
@allaghi Currently the only way is to use Tailwind's `important` prefix `!` to override the default hover style:
```
hover:!text-white hover:!bg-black
```
Without `!` it won't work because of CSS specificity. I will fix this on next update.

**Comment by allaghi** [comment]
I would like to let you know that `hover:text-white` is working , but `bg-blue-600` for example it doesn't work.
