### ISSUE TITLE
bug: Modal bug

### ISSUE THREAD

**Issue by fu3fi** [saadeghi/daisyui#2990]
### What version of daisyUI are you using?

4.10.2

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://play.tailwindcss.com/IIWW8U8Zeq

### Describe your issue

The problem appears when opening a modal window. It even appears in your standard example, which you use for examples on Tailwind Play. Notice how the page layout shifts to the left and a white stripe appears (it seems to be a scrollbar) when you open a modal window in Chrome. There is no such problem in Firefox.
For Example: https://play.tailwindcss.com/IIWW8U8Zeq
![image](https://github.com/saadeghi/daisyui/assets/48530932/3d0b2fbc-26d2-447c-91e2-7bc9327304ad)
![image](https://github.com/saadeghi/daisyui/assets/48530932/18a65008-ec56-4802-9cd9-3cef774a19fe)

**Comment by nbran** [comment]
This is a bug introduced recently. See here for a stopgap: https://github.com/saadeghi/daisyui/pull/2956#issuecomment-2043840868

**Comment by saadeghi** [comment]
Your will be fixed in the next minor version.

**Comment by johnniehard** [comment]
I'm getting this same issue in the latest version (4.12.22). The fix mentioned above solves it.
