### ISSUE TITLE
bug: 6.26 GB file in git

### ISSUE THREAD

**Issue by admin8756** [saadeghi/daisyui#2997]
### What version of daisyUI are you using?

4.10.2

### Which browsers are you seeing the problem on?

Other

### Reproduction URL

https://github.com/saadeghi/daisyui/tree/master

### Describe your issue

![image](https://github.com/saadeghi/daisyui/assets/21336637/1a583675-1dc4-4038-b560-b5079dfac5d3)
![image](https://github.com/saadeghi/daisyui/assets/21336637/6d56b423-2c0e-44ff-a0d4-35314690924d)
When cloning the repository, I encountered an extremely large file.

**Comment by saadeghi** [comment]
This is not a bug. The repository includes different branches. You would only need the master branch.  

First fork the repo. While forking, check the `Copy the master branch only` checkbox. Then clone the forked repo to your local.

**Comment by polyzen** [comment]
`git clone --single-branch https://github.com/saadeghi.git` should also do the trick.

**Comment by admin8756** [comment]
> `git clone --single-branch https://github.com/saadeghi/daisyui.git` should also do the trick.

Hi. Friend. I think this is not right. Because I have no problem cloning most repositories. I am saying that a large file has appeared. You all told me that just clone the master is enough. I am not looking for a solution. I'm just reporting an issue. This should not appear. Not how to solve it. Because I have already cloned it. So it doesn't help me at all. I don't understand the reason for this problem. However, thank you very much. Wishing you a happy life.

**Comment by admin8756** [comment]
> My friend... As I said, the repo includes multiple branches:
> 
> * v3.9.4-static
> * v3
> * v1.25.4-static
> * v2.52.0-static
> * v2
> * gh-pages
> 
> These branches are archives of past versions and generated framework static files for the documents of current version and each of the past versions. We use these branches to keep a live docs website for past versions (like https://v2.daisyui.com/)
> 
> These branches, especially the generated static ones are heavy because they include all the static files and gz+br compressed version of each of the assets. You don't need to clone these branches. Cloning the master branch is enough.

Oh, you are right! Just as you said. It would be great to add a clone tip in the contribution document. Here is the link: [CONTRIBUTING.md](https://github.com/saadeghi/daisyui/blob/60b4b654b965406d3451c6c713c7d9c0cc6b1d08/.github/CONTRIBUTING.md). Also, I have to say, I love DaisyUI so much. Yesterday, my friend said he didn't like it. I kicked his butt hard. I simply can't stand anyone saying bad things about it.
