### ISSUE TITLE
Bug: Can't change colors (Safari, macOS)

### ISSUE THREAD

**Issue by niklashaug** [saadeghi/daisyui#3]
Hi. I recognized that changing colors is not possible in Safari but works fine in Chrome. The color picker just doesn't show up.

https://daisyui.netlify.app/core/colors

**Comment by saadeghi** [comment]
Thanks @niklashaug,  
It will be fixed tomorrow.

**Comment by saadeghi** [comment]
Fixed on saadeghi/daisyui-demo@360148f0f436235ff1bb82f4730c53d2eb847cc8
