### ISSUE TITLE
fix card image responsiveness for any image size

### ISSUE THREAD

**Issue by saadeghi** [saadeghi/daisyui#30]

**Comment by Manitej66** [comment]
Hey, can give more info on the issue?

**Comment by saadeghi** [comment]
@Manitej66 Sure.  
Example: https://play.tailwindcss.com/4DqBsbrhiQ?size=1200x720  
The problem is when the image height is less than the `card-body` content, there will be a empty space under the image on desktop viewpoint. this is not unexpected behavior but it doesn't look good.  
I'm not sure how to improve this. potential solutions could be:  
- cropping the image when the ratio is unexpected
- keeping the image and text on top of each other even if they should be side by side
- ??

**Comment by devspectre91** [comment]
```
<div class="card lg:card-side lg:grid lg:grid-cols-2 bordered bg-neutral text-neutral-content">
  <figure class="lg:p-4">
    <img src="https://picsum.photos/id/1005/800/200" />
  </figure>
  <div class="card-body lg:bg-base-200">
    <p>Rerum reiciendis beatae tenetur excepturi aut pariatur est eos. Sit sit necessitatibus veritatis sed molestiae voluptates incidunt iure sapiente. Rerum reiciendis beatae tenetur excepturi aut pariatur est eos. Sit sit necessitatibus veritatis sed molestiae voluptates incidunt iure sapiente. Rerum reiciendis beatae tenetur excepturi aut pariatur est eos. Sit sit necessitatibus veritatis sed molestiae voluptates incidunt iure sapiente.</p>
  </div>
</div>
```

Check this out!

**Comment by saadeghi** [comment]
Fixed
