### ISSUE TITLE
Daisy seems to be double loading during build

### ISSUE THREAD

**Issue by jhirn** [saadeghi/daisyui#300]
Hello. This is probably a problem with my configuration and benign, but i'm getting the following output when starting my build: 

```bash
01:12:12 js.1   | 🌼 daisyUI components 1.16.2  https://github.com/saadeghi/daisyui
01:12:12 js.1   |   ✔︎ Including:  base, components, themes[1], utilities
01:12:12 js.1   |
01:12:12 js.1   |
01:12:12 js.1   | 🌼 daisyUI components 1.16.2  https://github.com/saadeghi/daisyui
01:12:12 js.1   |   ✔︎ Including:  base, components, themes[1], utilities
01:12:12 js.1   |
```

As much as I love the double daisy, my ocd is wondering why this is happening. Here is my tailwind config. I'm running tailwind with PostCSS via ESbuild so could absolutely have something to do with that. 

```javascript
module.exports = {
  mode: 'jit',
  purge: [
    ...
  ],
  plugins: [
    require('daisyui'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/aspect-ratio'),
    process.env.NODE_ENV !== 'production' ? require('tailwindcss-debug-screens') : null
  ].filter(Boolean),
  variants: {
    extend: {
      animation: ['hover']
    }
  },
  daisyui: {
    styled: true,
    themes: [
      ...
    ],
    base: true,
    utils: true,
    logs: true,
    rtl: false
  },
  theme: {
    extend: {
      fontSize: {
        hero: ['10rem', { lineHeight: 1 }]
      },
      letterSpacing: {
        superWide: '0.2rem',
        mondo: '1.2rem'
      },
      container: {
        center: true
      },
      fontFamily: {
        roboto: ['"Roboto Mono"', 'serif']
      },
      backgroundImage: {
        'hero-pattern': "url('/images/background.svg')",
        'mask-background': "url('/images/mask_background.png')"
      },
      boxShadow: {
        button: '0.5rem 0.5rem 0 black'
      }
    }
  }
}

```

**Comment by saadeghi** [comment]
I have no idea 🤷‍♂️  
I'm just sending one console log. Maybe it runs once for the initial build and once for the watch.  
Anyhow, you can disable the logs using `logs: false` config if you want.

**Comment by jhirn** [comment]
All good. It doesn't really effect things. Could be something with the postcss esbuild plugin i'm using. Everything around ESbuild requires some digging which I have not minded very much as it's been fun to hack and be in full control of the build. I'll close this for now and post a solution if I come across it.

**Comment by Notaduck** [comment]
@jhirn I'm seeing the exact same behaviour while using Daisyui, GatsbyJS and PostCSS.

Did you find a solution?

**Comment by saadeghi** [comment]
I wish I could fix it but there's nothing I can do about it. I `console.log` only once, when style is getting rendered.  
And there's no other way to print something, so based on how many times the build tool runs the file, it might result duplicate console logs.  

The only way is completely disable the console log from daisyUI config.

**Comment by jhirn** [comment]
DIdn't see any bad side effects so I fixed the problem by ignoring it =)

**Comment by timothymarois** [comment]
Also having this issue, its doing it about 6 times in the CLI for me on NuxtJS

**Comment by saadeghi** [comment]
@timothymarois Wow. 6 times is a lot 😅.  
[Here](https://github.com/saadeghi/daisyui/blob/79e5ba8feec60cc517b61ba230bf9a9fb907141c/src/index.js#L29) you can see that 🌼 is only printed once. So this is not something I can fix on my side. If it's printed 6 times it simply means your build step is executing `index.js` 6 times for some reason.  
If you're sure your build step is correct (with no duplicate build steps) it might be the way Nuxt is handling things.  
I suggest to disable that console.log using [`logs: false` config](https://daisyui.com/docs/config/#logs)
