### ISSUE TITLE
bug: area not disabled when using: Text input with text label inside

### ISSUE THREAD

**Issue by crescent1** [saadeghi/daisyui#3004]
### What version of daisyUI are you using?

v4.7.3

### Reproduction URL

https://play.tailwindcss.com/OAsyPadzrJ

### Describe your issue

the disabled area not worked when using Text input with text label inside

example code 
```
<!-- normal input disabled -->
<input type="text" placeholder="Type here" class="input input-bordered mb-4 w-full max-w-xs" disabled />

<!-- Text input with text label inside disabled -->
<label class="input input-bordered flex items-center gap-2">
  Name
  <input type="text" class="grow" placeholder="Daisy" disabled />
</label>
```

result 
![bug](https://github.com/saadeghi/daisyui/assets/8374604/9a66df24-2e65-41de-8d59-bf27870a1732)

**Comment by jondoe297tt** [comment]
you can add disabled on label tag.
