### ISSUE TITLE
False button hover styles

### ISSUE THREAD

**Issue by IamSAB** [saadeghi/daisyui#302]
I got DaisyUI installed with TailwindCSS using the CLI. I did anything according to the instructions, but the button hover styles are not correct. It always applies the styles from the `.btn` class instead of the modifiers.

If I take a look, the styles are present but the modifiers are earlier in the css file and therefore overwritten.

I am using a `tailwind.css`  in combination with a `tailwind.config.js` file to generate the CSS. I just require DaisyUI and nothing more.
How can I resolve this issue?

**Comment by saadeghi** [comment]
@IamSAB Can you please share a sample repo of your build?

**Comment by IamSAB** [comment]
You can take a look here: [https://github.com/IamSAB/grav-theme-jungschar](https://github.com/IamSAB/grav-theme-jungschar)

**Comment by IamSAB** [comment]
Sorry for the late reply. I missed the conversation.

You can take a look at the live website here: [https://jsek.ch](https://jsek.ch)

Here you can see, that the neutral hover style dominates. For me the problem occurs for dev and build mode.
