### ISSUE TITLE
bug: showModal using onKeyDown Enter not working

### ISSUE THREAD

**Issue by Drian-key** [saadeghi/daisyui#3025]
### What version of daisyUI are you using?

^4.8.0

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

-

### Describe your issue

document.getElementById("deletePurcaseOrder").showModal();

not working using on key down Enter, but if i using an-other key its work

**Comment by saadeghi** [comment]
daisyUI is just the CSS. We're simply using the HTML `<dialog>` element:  
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
