### ISSUE TITLE
Size options for steps

### ISSUE THREAD

**Issue by isaiahtaylor** [saadeghi/daisyui#303]
Hello, as it is, the size of the step "bubbles" cannot be easily modified with tailwind (tried `after:h-1` without success; the ::after defined by daisy takes precedence). It would be awesome to see a small variant of the step component that allows for a more compact steps display. Thanks!

**Comment by saadeghi** [comment]
@isaiahtaylor this might be a little tricky but you can customize the `before` and `after` if you're using JIT:  
https://play.tailwindcss.com/oi70JtKF53

**Comment by isaiahtaylor** [comment]
Ah! Thank you so much!

**Comment by mauscoelho** [comment]
unfortunately does not work with `steps-vertical`

**Comment by saadeghi** [comment]
@mauscoelho the example I linked, has custom width and height utility classes. So for vertical, you need to use `w-` instead of `h-` and vice versa:

[vice versa](https://play.tailwindcss.com/4nN6MS5A9L)

**Comment by mauscoelho** [comment]
> 

Nice! Thanks a lot
