### ISSUE TITLE
bug: prettier plugin for tailwind write credits and sometime tailwind lsp stopped on vim

### ISSUE THREAD

**Issue by fiik346** [saadeghi/daisyui#3036]
### What version of daisyUI are you using?

latest

### Reproduction URL

https://play.tailwindcss.com/RGJUjgS2RK

### Describe your issue

```json
{
  "bracketSameLine": true,
  "plugins": ["prettier-plugin-jinja-template", "prettier-plugin-tailwindcss"],
  "overrides": [
    {
      "files": ["*.html"],
      "options": {
        "parser": "jinja-template"
      }
    }
  ]
}
```
that is in the .prettierrc.json config, so when the formatting with prettier run in vim, it will write credits on topline of code like below.
![image](https://github.com/saadeghi/daisyui/assets/48739090/78c32442-b642-4c66-9bd1-d5e3c6e9521b)

sometime the lsp stopped working.

In other times, i had try it in vscode and no problems with that.

**Comment by saadeghi** [comment]
Probably the problem is Vim, using the raw terminal output as the result code. That can be problematic even without daisyUI (for example when Tailwind CSS returns a warning or error to the console log)

As a workaround, you can disable the daisyUI logs from the config file:  
https://daisyui.com/docs/config/#logs

Let me know if you have any questions

**Comment by fiik346** [comment]
Thank you, I think this will work. I will try when possible.

**Comment by hajirasyafi** [comment]
> Probably the problem is Vim, using the raw terminal output as the result code. That can be problematic even without daisyUI (for example when Tailwind CSS returns a warning or error to the console log)
> 
> As a workaround, you can disable the daisyUI logs from the config file: https://daisyui.com/docs/config/#logs
> 
> Let me know if you have any questions

Not work :(

**Comment by fiik346** [comment]
> > Probably the problem is Vim, using the raw terminal output as the result code. That can be problematic even without daisyUI (for example when Tailwind CSS returns a warning or error to the console log)
> > As a workaround, you can disable the daisyUI logs from the config file: https://daisyui.com/docs/config/#logs
> > Let me know if you have any questions
> 
> Not work :(

mine is work

**Comment by hajirasyafi** [comment]
> > > Probably the problem is Vim, using the raw terminal output as the result code. That can be problematic even without daisyUI (for example when Tailwind CSS returns a warning or error to the console log)
> > > As a workaround, you can disable the daisyUI logs from the config file: https://daisyui.com/docs/config/#logs
> > > Let me know if you have any questions
> > 
> > 
> > Not work :(
> 
> mine is work

Pake neovim apa vim biasa?

**Comment by hajirasyafi** [comment]
must be placed at the top in daisyui object

```ts
import type { Config } from "tailwindcss";
import { Config as DaisyUiConfig } from "daisyui";
const config: Config & { daisyui: DaisyUiConfig } = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {},
  plugins: [require("daisyui")],
  daisyui: {
    logs: false, // <-- place here
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
  },
};
export default config;

```
