### ISSUE TITLE
docs: Highlight that the first theme becomes the default

### ISSUE THREAD

**Issue by EnGassa** [saadeghi/daisyui#3051]
### On which page do you see this issue?

https://daisyui.com/docs/config/#themes

### Describe the issue

The text `the first theme will be the default theme` ought to be highlighted. I ended up wasting so much time trying to debug a misbehaving theme because this information is buried in the last sub-sentence of the doc on themes. Sure, it is my fault for not noticing this information there, however, it would help future devs to call this information out. 
Happy to push a PR for this if it helps.
![image](https://github.com/saadeghi/daisyui/assets/331780/063ac83d-763a-4bde-9fef-68ce21b3430c)

**Comment by saadeghi** [comment]
I understand.  
But which theme was expected to be default? Let's say we have `themes: ["light", "dark", "cupcake"],` I think it's obvious the first one is going to applied.

Also, this can happen to any other part of the docs. Someone may say `If it's true, all themes will be included` must be highlighted cuz they didn't read it.
