### ISSUE TITLE
Themes not working on NextJS.

### ISSUE THREAD

**Issue by arbob** [saadeghi/daisyui#306]
I'm trying to use themes as described here https://daisyui.com/docs/config/, but unable to change the theme. Is there a special way to change the theme in NextJS?

**Comment by GaelLanez** [comment]
@arbob Can you please provide a sample repo of your project ?
I'm using NextJS and custom themes are working fine.

**Comment by arbob** [comment]
@GaelLanez Although the code is private, here I've created a public repo with necessary files to get the idea of my repo.
https://github.com/arbob/daisy-next-sample

**Comment by GaelLanez** [comment]
@arbob Your project is currently set with `  daisyui: {
    themes: false,
  },` which means themes are disabled.
  You can enable the theme you want with `  daisyui: {
  themes: [
      "light",
      ]
  },` or create your own theme according to the doc.

**Comment by arbob** [comment]
@GaelLanez Ah. Sorry. Mistakenly, pushed the old version. The actual version does have themes enabled with `daisyui: {themes: ['cymk']}`

**Comment by GaelLanez** [comment]
@arbob Do you `import 'tailwindcss/tailwind.css'` on your _app.js ?
You can find a sample project at https://github.com/saadeghi/daisyui/tree/master/examples/nextjs

**Comment by saadeghi** [comment]
Thanks @arbob  
I see w problems here:
- You're using daisyUI `1.11.1` but CMYK theme [was added in `1.16.0`](https://github.com/saadeghi/daisyui/blob/master/CHANGELOG.md#1160-2021-10-23). Install the latest version: `npm i daisyui@latest`
- [Here](https://github.com/arbob/daisy-next-sample/blob/530645ce02955bda846df2929df9fef3049fde61/tailwind.config.js#L19) it's not `cymk`. it's `cmyk` 😁

Let me know if you have any questions.
