### ISSUE TITLE
css prefix

### ISSUE THREAD

**Issue by danielehrhardt** [saadeghi/daisyui#307]
I would love to integrate daisyui into my existing projects. 

The problem is that you used really generic css classes and these destroy my already existing design system. 

My idea would be to add a prefix in the tailwind config file for daisyui. 

What do you think about that? 

Best
Daniel

**Comment by saadeghi** [comment]
@danielehrhardt See this: https://github.com/saadeghi/daisyui/issues/117#issuecomment-891212876

Let me know if you have any questions.

**Comment by saadeghi** [comment]
New `prefix` config added to daisyUI `2.4.0`  
https://daisyui.com/docs/config/
