### ISSUE TITLE
Add some responsive navbar for small screen

### ISSUE THREAD

**Issue by Johnsiras** [saadeghi/daisyui#308]
Add some responsive navbar like

Adding a burger menu and if the user click it the items will show in a responsive **way**

After clicking in the burger menu it will replace that button with **"X"** where the user can closed the navbar.

**Comment by saadeghi** [comment]
There are `drawer` examples: https://daisyui.com/components/drawer  
It doesn't have replacing icons but it can be a **drawer sidebar for all screens** or a **fixed sidebar on desktop + drawer sidebar for mobile**
