### ISSUE TITLE
bug: Cannot use `@apply` with  `join` and `join-item`

### ISSUE THREAD

**Issue by TheHadiAhmadi** [saadeghi/daisyui#3084]
### What version of daisyUI are you using?

4.12.2

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://play.tailwindcss.com/8gTvGmHF0y

### Describe your issue

I want to create custom class name for my components, and use `@apply`. combination of join and join-item doesn't work with apply.

I expect this code works:
```html
<div class="my-pagination">
  <button class="my-pagination-item">1</button>
  <button class="my-pagination-item my-pagination-item-active">2</button>
  <button class="my-pagination-item">3</button>
  <button class="my-pagination-item">4</button>
</div>
```
```css
.my-pagination {
  @apply join;
}

.my-pagination-item {
  @apply join-item btn btn-primary btn-md;
}

.my-pagination-item-active {
  @apply btn-active;
}
```
but buttons have roundness and styles of join-item are not applied.

above code should be equivalent to below code:
```html
<div class="join">
  <button class="join-item btn btn-primary btn-md">1</button>
  <button class="join-item btn btn-primary btn-md btn-active">2</button>
  <button class="join-item btn btn-primary btn-md">3</button>
  <button class="join-item btn btn-primary btn-md">4</button>
</div>
```

thanks

**Comment by saadeghi** [comment]
That's how `@apply` works and there's nothing I can do about it.  
When you use
```css
.my-pagination {
  @apply join;
}
```
It copies the CSS rules of `.join` class to `.my-pagination` but it doesn't copy a child selector (`.join .join-item`) to a new class name `.my-pagination .my-pagination-item`. In other words, with `@apply` you can use a single CSS rule in a new class name but all the relations between class names will be ignored. This is not a bug, but simply how `@apply` is intented to work.

May I ask why you need to rename the class names?
