### ISSUE TITLE
Status bar on ios does not work with drawer

### ISSUE THREAD

**Issue by kominov** [saadeghi/daisyui#309]
it s my code from layout. Its work fine, but when i tryed to tap on status bar on iphone scrolling top doesnt work. Maybe you know how i can to fix it? i use nuxt [](ur
![пп](https://user-images.githubusercontent.com/76279904/142354823-678b070c-65a9-4863-be5d-6971fd50851a.png)
l)

**Comment by sshquack** [comment]
Not sure if this is also related to `window.scrollTo` not working but I filed a separate issue here https://github.com/saadeghi/daisyui/issues/431

**Comment by saadeghi** [comment]
I think this is related to #431  
`drawer-content` needs to be scrolled instead of root element
