### ISSUE TITLE
bug: RTL <select> padding

### ISSUE THREAD

**Issue by robsontenorio** [saadeghi/daisyui#3098]
### What version of daisyUI are you using?

4.12.6

### Which browsers are you seeing the problem on?

Safari

### Reproduction URL

https://play.tailwindcss.com/6BUfHiqeLD?file=config

### Describe your issue

Regression of 

<img width="965" alt="image" src="https://github.com/saadeghi/daisyui/assets/118955/268c520c-ae60-4be2-971d-3d322b569763">

**Comment by saadeghi** [comment]
Fixed in 4.12.7

**Comment by robsontenorio** [comment]
Thanks @saadeghi  ❤️
