### ISSUE TITLE
docs: btn docs

### ISSUE THREAD

**Issue by lwxtd** [saadeghi/daisyui#3106]
### On which page do you see this issue?

https://daisyui.com/components/button/

### Describe the issue

![Screenshot_6](https://github.com/saadeghi/daisyui/assets/18658526/ec57c004-c01c-4321-84eb-a4c5cf7bf609)

instead of Square button it is showing circle button

### What browsers are you seeing the problem on?

All browsers

**Comment by saadeghi** [comment]
A circle is a square with a big border radius value.  
The theme in your screenshot has big border radius for buttons, in result all buttons including square button has big border radius. It would be anti pattern if this specific button has no border radius like other buttons.

Let me know if you have any questions
