### ISSUE TITLE
bug: Sidekick browser crashing

### ISSUE THREAD

**Issue by sphotos** [saadeghi/daisyui#3107]
### What version of daisyUI are you using?

4.12.8

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

Not applicable :(

### Describe your issue

The latest Sidekick browser is running on Chrome v122. We also observed this with v124 of Chrome.

Chrome deub log is reporting the following:
[89127:259:0627/175826.238695:ERROR:fallback_task_provider.cc(126)] Every renderer should have at least one task provided by a primary task provider. If a "Renderer" fallback task is shown, it is a bug. If you have repro steps, please file a new bug and tag it as a dependency of crbug.com/739782.
[0627/175826.332510:WARNING:in_range_cast.h(38)] value -634136515 out of range
[89127:259:0627/175827.095491:ERROR:fallback_task_provider.cc(126)] Every renderer should have at least one task provided by a primary task provider. If a "Renderer" fallback task is shown, it is a bug. If you have repro steps, please file a new bug and tag it as a dependency of crbug.com/739782.

![image](https://github.com/saadeghi/daisyui/assets/46054780/264a36ba-cfd5-45a9-935f-20eee626f31d)

**Comment by saadeghi** [comment]
How is it related to daisyUI? daisyUI is CSS.

Please report this issue to Sidekick browser.

**Comment by sphotos** [comment]
It also happens with chrome 124, but yes a ticket there has also been opened.

**Comment by sphotos** [comment]
Thanks for looking into it. It is very weird. We're using v4.12.7 for now and also trying to dig into it. But do appreciate your support.

**Comment by saadeghi** [comment]
This is the changes of 4.12.8:   
https://github.com/saadeghi/daisyui/commit/92d98ed60acb8fa1300fc1665b9c1df3195a9b60

Both [scrollbar-color](https://caniuse.com/?search=scrollbar-color) and [color-mix()](https://caniuse.com/?search=color-mix) are supported on Chromium and is expected to work. And if it's not supported (For example Safari, the browser will just ignore that CSS line as expected). It shouldn't crash.

**Comment by saadeghi** [comment]
@NathanVG Please report this to Chromium. There is nothing I can do about this. I can't even see the issue or reproduce it.  

The link you clicked on the video is a simple HTML link with a really simple CSS hover style. No JS, no loops, no memory leak, no funny tricks etc to may cause a crash.  

Chromium, like any software has bugs too and the developers are fixing them constantly.  

You can also try clearing site data, rebooting your OS or reinstalling Chrome to see if it helps in your case.

**Comment by NathanVG** [comment]
@saadeghi I will report it to Chromium, just thought you should be aware as well, as it only happens once I add daisyUI to my tailwind config, if I remove it everything works fine again.

**Comment by saadeghi** [comment]
> just thought you should be aware as well

Yeah of course. Thanks. I just wanted to be clear that it's not something I can fix on my end.

> once I add daisyUI to my tailwind config, if I remove it everything works fine again.

daisyUI is just CSS but it's possible (maybe) using 2 specific line of CSS to cause a bug on Chrome on a specific OS on a specific hardware. Even if i knew which element or which line of CSS is causing this (which I don't because I can't reproduce unfortunately) I can't help about it because it's expected for the browser to render CSS as it is.

Thanks for reporting to Chromium.

**Comment by jgauna** [comment]
After weeks trying to fix this bug I've found the answer from this @saadeghi [comment](https://github.com/saadeghi/daisyui/issues/3107#issuecomment-2208885588) 

Simply add this to your `tailwind.config.cjs`

```javascript
  daisyui: {
    base: false, // applies background color and foreground color for root element by default
  }
```

run the project and the `Código de error: SIGSEGV` error will be gone.
