### ISSUE TITLE
bug: Dropdown overlapped by table header

### ISSUE THREAD

**Issue by gitmalong** [saadeghi/daisyui#3111]
### What version of daisyUI are you using?

4.12.10

### Reproduction URL

-

### Describe your issue

```html

 <table class="table table-xs table-zebra table-pin-cols table-pin-rows mt-2">
<thead>
    <tr>
        <th>"Date"</th>
        <th>
            <div class="dropdown dropdown-bottom">

                Col 1

                <ul
                      tabindex="0"
                      class="dropdown-content menu p-0 z-10 shadow bg-base-100 rounded-box w-52"
                  >
                      <li>
                          <a>
                              <label class="label cursor-pointer">
                                      Some dropdown content
                              </label>
                             </a>
                        </li>
                   </ul>

            </div>
        </th>
    </tr>
</thead>
</table>
```

Example: 
![image](https://github.com/saadeghi/daisyui/assets/18363591/76546cf0-318b-45d7-8d49-f9705f7992ae)

**Comment by twschum** [comment]
<img width="231" alt="Screenshot 2024-08-08 at 1 54 01 PM" src="https://github.com/user-attachments/assets/f1412058-2282-4d8d-9d24-5b1b2bf1e502">
I have also reproduced this problem, where table headings are on top of a nav dropdown. The navbar and dropdown are outside the table element.

**Comment by KozSuper** [comment]
![image](https://github.com/user-attachments/assets/22333611-572b-4515-95ff-72f47d7b75b0)

The dropdown is being covered by the table. i tried z-index but not working

**Comment by KozSuper** [comment]
when a dropdown is inside a div with transform, it will behave like this.

https://play.tailwindcss.com/NJPASKLtKE

**Comment by leouie28** [comment]
I have this error when i add dropdown inside a table.

https://play.tailwindcss.com/jaw5gLJBnA

**Comment by saadeghi** [comment]
@leouie28 `overflow-x-auto` class is causing that.  
This will be fixed in the upcoming daisyUI 5 release by using the new HTML popover API for dropdowns.
