### ISSUE TITLE
tailwind.css file? does not exists.

### ISSUE THREAD

**Issue by LeonardoDaLuz** [saadeghi/daisyui#312]
tailwind.css file does not exist.
![image](https://user-images.githubusercontent.com/80224694/142939419-aae5bfeb-7748-4b9b-9e46-b326eb0bb6af.png)
https://daisyui.com/docs/add-themes

In the documentation it mentions this file but it doesn't exist.

**Comment by saadeghi** [comment]
@LeonardoDaLuz That would be your main CSS file that Tailwind generates.  
The file name can be anything: `global.css`, `style.css`, etc...  
But the CSS file content is:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```
or
```css
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
```
more info: https://tailwindcss.com/docs/installation#include-tailwind-in-your-css

**Comment by LeonardoDaLuz** [comment]
I forgot to thank you. This UIKit/Framework is spectacular. Much better than a bootstrap! And it changed my way of thinking about layouts. Thanks!
