### ISSUE TITLE
bug: collapse with arrow or plus crashes edge

### ISSUE THREAD

**Issue by AndreasRoither** [saadeghi/daisyui#3128]
### What version of daisyUI are you using?

4.12.10

### Which browsers are you seeing the problem on?

Edge

### Reproduction URL

https://daisyui.com/components/collapse/

## Environment / Versions
Browser: Edge `122.0.2365.80`, no extensions installed
affected daisyui version: **>=** `4.12.8`

## Error Description

When hovering/clicking a collapse component that has either `collapse-arrow` or `collapse-plus` as css class, Edge (122.0.2365.80) crashes. There are no console errors or warnings in the console. 

From my tests, removing either `collapse-arrow` or `collapse-plus` class on the collapse component results in normal component behavior. Daisyui versions >= `4.12.8` all have the same problem (versions <= 4.12.7 have no problem).

Other browsers like Chrome or Firefox do not seem affected in the latest versions. Due to a constraint, I can not upgrade Edge to a newer version yet and can thus not circumvent the error unless I use a fixed daisyui version.

Component:
![image](https://github.com/saadeghi/daisyui/assets/9451065/99471948-424c-463a-9eb7-35e6a49e2ad0)

Crash:
![image](https://github.com/saadeghi/daisyui/assets/9451065/299a3f81-a90a-451d-9090-1f9967b8480a)

To download edge use the official site to select the version:
https://www.microsoft.com/en-us/edge/business/download
![image](https://github.com/saadeghi/daisyui/assets/9451065/d78d6b71-27c0-4596-bbf7-b4d850766bd6)

---

Edit: Hovering over cards at 
https://daisyui.com/docs/install/

![image](https://github.com/saadeghi/daisyui/assets/9451065/3fda7ee4-5dc4-40fc-a078-2773f013036f)

also produces the crash.

Edit 2:
Opening https://daisyui.com/ also crashes the browser tab.
#3124 seems related at first, but I have no extensions installed

**Comment by flip111** [comment]
this is a memory error in edge browser. Try upgrading your browser or use firefox. that daisyui triggers this edge bug doesn't make it a daisyui bug
