### ISSUE TITLE
bug: Can't Scroll through Closed Scrolling Modal

### ISSUE THREAD

**Issue by abegehr** [saadeghi/daisyui#3129]
### What version of daisyUI are you using?

v4.12.10

### Which browsers are you seeing the problem on?

Safari

### Reproduction URL

https://play.tailwindcss.com/CeDiRXRV2i

### Describe your issue

I've noticed a bug on one of my pages that uses daisyui, where a div that's marked with "overflow-y-scroll" doesn't scroll when the cursor is over a modal that itself scrolls, while the modal is closed. The issue doesn't occur on Chrome. 

There is a reproduction attached to this issue. Screenshots for explanation:
<img width="1360" alt="Screenshot 2024-07-11 at 13 49 30" src="https://github.com/saadeghi/daisyui/assets/23075874/aee312fb-f9e6-467a-a9b4-1eed228a6d07">
<img width="1360" alt="Screenshot 2024-07-11 at 13 49 46" src="https://github.com/saadeghi/daisyui/assets/23075874/f829bba4-e5ae-4dcf-88b2-f3132a8cd6ec">

**Comment by abegehr** [comment]
I'm working around this issue by setting `overflow-hidden` on the `modal-box` when the modal is closed now.

**Comment by saadeghi** [comment]
It does scroll anywhere on the green box. I don't see any issues 🤔  
This video is Safari 18:  
https://github.com/user-attachments/assets/3d46fa35-5f7e-451d-a1e7-422b60d4b416
