### ISSUE TITLE
Community chat

### ISSUE THREAD

**Issue by rishavs** [saadeghi/daisyui#314]
Will it be possible for you to join a community chat so that we can discuss and help each other?
Gitter or a channel in the Tailwind Discord would be great.

Right now, if we get stuck there is no place to ask for help. and these problem do not fit the Github issues template.

**Comment by saadeghi** [comment]
@rishavs I doing my best to answer GitHub issues as soon as possible and almost half of issues are not actual bugs. Issues can be bug reports, feature requests or just asking for help on a specific project setup.  
Discord and Gitter are good tools but those places need someone to constantly communicate with people and will take a lot of my time.

Feel free to open issues if you need help with something and me or one of the contributors will help.

Also, GitHub has a "discussions" section. That might be useful too.
