### ISSUE TITLE
docs: Official Website is not loading

### ISSUE THREAD

**Issue by SurenderLohia** [saadeghi/daisyui#3140]
### On which page do you see this issue?

https://daisyui.com/

### Describe the issue

Official Website is not loading.

<img width="1440" alt="Screenshot 2024-07-21 at 10 54 03 AM" src="https://github.com/user-attachments/assets/2be8d4ef-a3db-452f-86be-aa92d221dea6">

### What browsers are you seeing the problem on?

Chrome

**Comment by LarryTheFatCat** [comment]
Looks temporary, site's running back up again

**Comment by saadeghi** [comment]
This is an issue from browser.  
Try restarting browser or OS if necessary.  
Try updating the browser to see if the issue is fixed.

**Comment by SurenderLohia** [comment]
@LarryTheFatCat & @saadeghi, Yes it's due to the browser update, after I restarted it started working.
Thanks.
