### ISSUE TITLE
bug: daisyui website not working (https://daisyui.com/)

### ISSUE THREAD

**Issue by sachin-duhan** [saadeghi/daisyui#3147]
### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://daisyui.com/

### Describe your issue

![image](https://github.com/user-attachments/assets/b50d938a-111f-4852-9e3d-2a290123b66d)

**Comment by saadeghi** [comment]
This is a browser error.  
- Try restarting the browser (or OS if necessary) 
- Try updating the browser to the latest version.
