### ISSUE TITLE
footer-center on small screen, but normal on large screens

### ISSUE THREAD

**Issue by copleykj** [saadeghi/daisyui#315]
Is there any way to have centered content on small screens for footer, but remove the `footer-center` styles for larger screens? Something like a `footer-normal`. 

# Example Usage
```html
<footer class="footer footer-center lg:footer-normal" >
  <!-- content -->
</footer>
```

**Comment by deyanskiq** [comment]
You can always use a combination of `classnames` and `react-responsive` media queries packages. 
Something like:
```
<footer class={cx("footer", {"footer-center": isMobile})>
  <!-- content -->
</footer>
```

It's not clean as tailwind media queries though.

**Comment by saadeghi** [comment]
@copleykj `footer-center` is not responsive right now. I will work on it and I will make it responsive if there's no breaking change tho.  
Currently, you can use `place-items-center lg:place-items-start` instead of `footer-center`

let me know if you have any questions.
