### ISSUE TITLE
docs: Divider horizontal example not working

### ISSUE THREAD

**Issue by xl0** [saadeghi/daisyui#3151]
### On which page do you see this issue?

https://daisyui.com/components/divider/

### Describe the issue

The current horizontal divider example is
```
<div class="flex w-full">
  <div class="divider divider-start">Start</div>
  <div class="divider">Default</div>
  <div class="divider divider-end">End</div>
</div>
```

And the divider is not shown.
I think the `divider-horizontal` class is missing. The code works as expected:
```
<div class="flex w-full">
	<div class="divider divider-start divider-horizontal">Start</div>
	<div class="divider divider-horizontal">Default</div>
	<div class="divider divider-end divider-horizontal">End</div>
</div>
```

**Comment by BlueBles** [comment]
![image](https://github.com/user-attachments/assets/297ce198-f1d6-4b90-8900-ff8f38922bba)
![image](https://github.com/user-attachments/assets/89c9ab11-0ba8-4053-b00f-f2f6fa5c42a8)

The example is wrong, but the code behind is good.
