### ISSUE TITLE
bug: Only last color definition in theme override is applied

### ISSUE THREAD

**Issue by suburbanworrier** [saadeghi/daisyui#3168]
### What version of daisyUI are you using?

v4.12.10

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://play.tailwindcss.com/HPwAYbvcas?file=config

### Describe your issue

Overriding one of the standard colors works fine by redefining the css var in tailwind.config.js

Overriding multiple colors introduces quirks with seemingly only the final var being honoured.

However in making the Tailwind Play file I noticed that it was possible to successfully override both the primary and secondary color but never all three of "primary", "secondary" and "accent".

I initially mocked this up in a Stackblitz at https://stackblitz.com/edit/daisyui-sveltekit-3ys4xm?file=tailwind.config.cjs where I've updated daisyUI to the latest version. Toggling the order of lines 17 & 18 in tailwind.config.cjs exposes the problem as I initially saw it.

Both of these showcase an issue I'm seeing in a larger SvelteKit project where I'm attempting to style button text color.

**Comment by suburbanworrier** [comment]
More than happy to put some effort in to resolve this but honestly I'd need pointing in the right direction.

**Comment by saadeghi** [comment]
In config, it must be `accent-content` because we process the built-in colors to generate the missing ones with a valid contrast.
```diff
light: {
  ...require('daisyui/src/theming/themes')['light'],
-  '--pc': '99% 0 0',
-  '--ac': '100% 0 0',
+  'primary-content': '99% 0 0',
+  'accent-content': '100% 0 0',
},
```
Docs: https://daisyui.com/docs/themes/#-5

I know it can be confusing where to use color name like `--ac` and where to use `accent-content`. It will be only CSS variable in daisyUI 5 to avoid confusion.

**Comment by suburbanworrier** [comment]
Many thanks for providing the answer 🙇
