### ISSUE TITLE
bug: modal bug - the bottom page moves one scroll unit to the left

### ISSUE THREAD

**Issue by Zanehb** [saadeghi/daisyui#3171]
### What version of daisyUI are you using?

4.12.10

### Which browsers are you seeing the problem on?

Edge

### Reproduction URL

https://play.tailwindcss.com/22h1oVDng7

### Describe your issue

The css of global background set to "overflow-hidden". When use the "modal-open", the bottom page moves one scroll unit to the left. The version of "4.9" is normal, and version than "4.9" has the problem.
it can be seen in the URL example, when open the modal, the button move left.

**Comment by saadeghi** [comment]
related issue: #3040
