### ISSUE TITLE
bug: Textarea line height is too high, imo

### ISSUE THREAD

**Issue by alexandreL** [saadeghi/daisyui#3180]
### What version of daisyUI are you using?

4.12.10

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://play.tailwindcss.com/WayqISZyMb

### Describe your issue

In my opinion, the line height is too high inside a textarea. I investigated a little, and found that in `unstyled/textarea.css`, that the `leading-loose` which makes too much space between the lines of text, and should be removed.

<img width="348" alt="image" src="https://github.com/user-attachments/assets/e347588d-ecd2-4263-a80e-da5c29d7a96b">

I'll let you decide whether it's relevant or not. It may be a breaking change for some people.

**Comment by saadeghi** [comment]
It's for better readability.  
Every single component from daisyUI are opinionated and come with design decisions. Our goal is to provide the defaults which works for the majority and then for the small details like this, everyone can apply their own tweaks using utility classes. You can add `leading-normal` to decrease the line height:  
https://play.tailwindcss.com/uHGVjEiQh2

Let me know if you have a question.
