### ISSUE TITLE
The theme only takes effect on some elements

### ISSUE THREAD

**Issue by cangSDARM** [saadeghi/daisyui#319]
Version: chrome: ` 95.0.4638.69`; daisyui: `^1.16.2`; tailwindcss: `npm:@tailwindcss/postcss7-compat@^2.2.17`; sass: `^1.43.5`; postcss: `^7.0.39`

I try to use CMYK theme, but it does not work on a span, but it worked on a button.
Those text should appear black, but it is still white

This element:
```html
<section data-theme="cmyk">
   <span key="" className="inline subpixel-antialiased">Not Work</span>
   <button class="btn">Work</button>
</section>
```

Here is the effected css roles:

![image](https://user-images.githubusercontent.com/20441896/144193877-331e0498-762f-421a-9801-75637628d68d.png)
![image](https://user-images.githubusercontent.com/20441896/144193876-642bd19d-2a73-47f7-b768-ca90f55e6ff4.png)
![image](https://user-images.githubusercontent.com/20441896/144194419-939cfd0a-f9e5-486f-9dcc-638d145009f9.png)

**Comment by cangSDARM** [comment]
Like buttons, or other daisyUI components, this style is effective

**Comment by cangSDARM** [comment]
Ok, I found this issue.
It seems that the `data-theme` must be set on the `html` element, otherwise, the theme will not work on some elements.
What the official website says can be set on any element, which seems to be problematic

**Comment by saadeghi** [comment]
@cangSDARM `data-theme` affects all components but not text color and background colors inside. daisyUI also adds [a base style](https://github.com/saadeghi/daisyui/blob/master/src/base/colors.css) to define the text color and background color for the `:root` element (usually `<HTML>`) but It's not wise to apply this style to everything inside.  
So, if you want the background color and text color of the theme for a specific section, you can add `bg-base-100 text-base-content` classes. example:
https://play.tailwindcss.com/JAaSQC59oK  
Let me know if you have any questions
