### ISSUE TITLE
It is possible to scroll while a modal is open

### ISSUE THREAD

**Issue by danielfliegauf** [saadeghi/daisyui#321]
Hello dear DaisyUI Maintainer, 

thanks for your awesome work and this fantastique library. 
Unfortunately i stumbled over a bug today. 

On iOS it is still possible to scroll the background while a modal is open. This results in some nasty flickering since i have a fixed navbar on the bottom (position: fixed; bottom: 0), especially when the safari grows/shrinks the url line on the bottom.

Thank you!
Daniel

**Comment by StefanKandlbinder** [comment]
@danielfliegauf 
If you are not dependent on your latest scroll position of the body element,[ overflow-hidden ](https://tailwindcss.com/docs/overflow#hidden)on the body element should do the trick.
Add it when the modal is opened and remove it, when the modal is closed.
Hope this helps.

Cheers
Stefan

**Comment by saadeghi** [comment]
I was planning to use [overscroll-behavior](https://caniuse.com/css-overscroll-behavior) to handle this. Unfortunately Safari does not support that yet.

**Comment by StefanKandlbinder** [comment]
It's still hidden inside the Experimental Features Section on IOS. 
So, there is hope that it will be shipped in the near future by default...

**Comment by StefanKandlbinder** [comment]
It's in development: [overscroll behavior](https://webkit.org/css-status/#property-overscroll-behavior).
And you should be able to activate it inside the Experimental Features on IOS.
So, the signs look promising, that it will be shipped by default in the near future...

**Comment by saadeghi** [comment]
I added `overscroll-behavior` and it's preventing the scrolling of background content. It's currently an experimental feature on Safari but I hope it will be available by default soon.

**Comment by nullart** [comment]
This is my hack. Please refer to https://github.com/saadeghi/daisyui/issues/1341#issuecomment-1489443406
