### ISSUE TITLE
bug: spam message in dev mode: "thems added, star daiyUI on GitHub, support daisyUI project"

### ISSUE THREAD

**Issue by LeeKrane** [saadeghi/daisyui#3212]
### What version of daisyUI are you using?

4.12.10

### Which browsers are you seeing the problem on?

Other

### Reproduction URL

- https://play.tailwindcss.com/sFCTGVSc2Y?file=config

### Describe your issue

I use daisyui with Nuxt 3 and whenever I start up my project in dev mode, my terminal gets completely spammed with those daisy ui messages (look image). I have no clue why this is spammed around 20 times, once would be enough. This is just a very minor bug of very little relevance.

![image](https://github.com/user-attachments/assets/2e37db4e-ee01-4b3d-b43d-ffd95ed8bfac)

**Comment by saadeghi** [comment]
Can you provide a reproduction link? There must be something wrong about your config.

**Comment by LeeKrane** [comment]
@saadeghi  Yes I just uploaded my config in the original issue message.

**Comment by saadeghi** [comment]
I mean your framework/build tool config.  
I need a reproduction of your Nuxt project because apparently Vite is building your project every time instead of hot module reloading.

**Comment by saadeghi** [comment]
By the way you can disable the daisyUI logs like this if you want.

https://daisyui.com/docs/config/#logs

**Comment by LeeKrane** [comment]
My Nuxt config is like this, currently trying to add a font with the weights in different files that's why the fonts attribute looks like that.

`// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
	compatibilityDate: '2024-04-03',
	devtools: { enabled: true },
	modules: [
        "@nuxtjs/tailwindcss",
        "@nuxt/fonts",
        "@nuxt/image",
        "@nuxtjs/sitemap",
        "@nuxtjs/robots",
        "@nuxtjs/fontaine",
        "@nuxtjs/critters",
        "nuxt-delay-hydration",
		"@vueuse/nuxt",
		"@hypernym/nuxt-anime",
		"@nuxt/icon",
    ],
	postcss: {
		plugins: {
			tailwindcss: {},
			autoprefixer: {},
		},
	},
	css: ["~/assets/scss/main.scss"],
	future: {
		compatibilityVersion: 4,
	},
	image: {
		providers: {
			cloudflareImage: {
				name: "cloudflareImage",
				provider: "~/providers/cloudflare-image.ts",
				options: {
					baseURL: "...",
				}
			},
		},
		provider: "cloudflareImage",

		quality: 80,
		format: ["avif", "webp"],

		screens: {
			'2xs': 480,
			'xs': 640,
			'sm': 768,
			'md': 1024,
			'lg': 1280,
			'xl': 1536,
			'2xl': 1920,
			'3xl': 2560,
			'4xl': 3200,
		},
	},
	site: {
		url: '...',
		name: '...',
	},
	delayHydration: {
		mode: 'mount',
		// enables nuxt-delay-hydration in dev mode for testing
		debug: process.env.NODE_ENV === 'development'
	},
	robots: {
		disallow: []
	},
	fonts: {
		families: [
			{
				name: "Max",
				src: [
					"/fonts/MaxBla.otf",
					"/fonts/MaxExtBol.otf",
					"/fonts/MaxBol.otf",
					"/fonts/MaxSemBol.otf",
					"/fonts/MaxReg.otf",
					"/fonts/MaxLig.otf",
				]
			},
		],

		defaults: {
			weights: [300, 400, 600, 700, 800, 900],
			styles: ["normal"]
		}
	},
	anime: {
		composables: true,
	},
	app: {
		head: {
			titleTemplate: `...`,
			meta: [
					{ name: "description", content: "..." }
			],
			htmlAttrs: {
				lang: "de"
			}
		}
	}
})`

**Comment by LeeKrane** [comment]
Oh wait I might have to mention that this happens when I start the project, not during working on it. Just when I start it in dev mode or when I edit my nuxt config for example, where the whole project gets rebuilt.

**Comment by saadeghi** [comment]
My friend, just give a minimal reproduction link where I can run your project and see the same issue.

I made a Nuxt project, with your config file and installed your dependencies manually and I still can't see the issue:  
https://stackblitz.com/edit/nuxt-starter-j5f3gb?file=nuxt.config.ts

FYI:  
https://en.wikipedia.org/wiki/Minimal_reproducible_example

**Comment by LeeKrane** [comment]
Okay I don't know why, but this issue sometimes occurs, probably when I somehow change the nuxt config or the tailwind config in a certain way, rn at my own project is doesn't occur anymore and I can't get it to come back. Also tried modifying your stackblitz code to recreate it, but it doesn't happen at the moment. I played around with Nuxt fonts in the nuxt config and in the tailwind config, as well as my main scss file. I guess until I encounter it again somehow I can't give you a reproduction right now :/

I'll close it for now and when it comes back I will reopen, thank you for your time and sorry for being unable to provide enough context my friend. Have a good one

**Comment by saadeghi** [comment]
I would be happy to help but first I need a reproduction so I can run and see the issue so then I can track where the issue is coming from.

I guess for now you can disable daisyUI logs.  
For the record, if the log is being printed 10 times, it means your build tool is building your CSS file 10 times from scratch, which is not what should happen. With Vite, it should be 1 or 2 times max, then the changes will be seamless, with HMR.

**Comment by LeeKrane** [comment]
Yes, sorry I cannot reproduce it myself right now. I understand, so I somehow messed something up that my build tool rebuild the CSS file too often for some reason, well at the moment it is gone, but if I can reproduce it somehow in the future again I will re-open. Thank you.
