### ISSUE TITLE
bug: Carousel of Cards does not behave as expected

### ISSUE THREAD

**Issue by jpeterson** [saadeghi/daisyui#3217]
### What version of daisyUI are you using?

4.12.10

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://play.tailwindcss.com/jCdSW9XQ2A

### Describe your issue

Using the [default Carousel example](https://daisyui.com/components/carousel/#snap-to-start-default) but swapping out the `<img>` elements in the example with the [default Card example](https://daisyui.com/components/card/#card) breaks the Carousel's horizontal scroll behavior, allowing the Cards to cause a horizontal page scroll instead.

**Comment by saadeghi** [comment]
Add a width to it. Like `w-full`  
It's not a good idea if I add a default width to the library as default because the width depends on the content.

Let me know if you have a question.
