### ISSUE TITLE
Can't scroll in the modal

### ISSUE THREAD

**Issue by Johnsiras** [saadeghi/daisyui#323]
When the content is too long in the modal, it doesn't let me scroll, I used overflow for it but still doesn't work. 

What do i do?

**Comment by Johnsiras** [comment]
Example: 
![image](https://user-images.githubusercontent.com/78542955/144739699-5dd9f963-21d3-438b-bcb0-4fc4bf464478.png)

**Comment by Johnsiras** [comment]
**Example**:

![image](https://user-images.githubusercontent.com/78542955/144739744-21204b12-b637-4d70-9ca4-142a53d27c88.png)

**Comment by saadeghi** [comment]
@Johnsiras Try adding `overflow-y-auto max-h-[90vh]`  
example: https://play.tailwindcss.com/iovEA9BtKY

let me know if you have any questions
