### ISSUE TITLE
bug: using CSS Variable in tailwind.config.js not working

### ISSUE THREAD

**Issue by ylc6223** [saadeghi/daisyui#3238]
### What version of daisyUI are you using?

^4.12.13

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://stackblitz.com/edit/vitejs-vite-qtfuu9?file=src%2Fcomponents%2FHelloWorld.vue

### Describe your issue

I tried to set css variable in tailwind.config.js, 
but it doesn't work.
In this file,CSS style classname bg-primary background-color does not working
<img width="685" alt="image" src="https://github.com/user-attachments/assets/425cb16b-6306-44aa-96df-5688923849f1">
When I use a CSS variable, it doesn't work
<img width="623" alt="image" src="https://github.com/user-attachments/assets/b33984e2-6350-4921-aa6c-d81475fae623">
What should I do to make it work? I want to use my own CSS variables in it
<img width="658" alt="image" src="https://github.com/user-attachments/assets/285aee86-e775-42ed-92d4-f5076e0e9f25">
<img width="350" alt="image" src="https://github.com/user-attachments/assets/6be8d4b1-98a1-41cb-ae81-2c39ad3d6809">

I look forward to hearing from you,Thanks

**Comment by saadeghi** [comment]
They are already CSS variables. See this table:
https://daisyui.com/docs/colors/

Here's how you can use the CSS variables in runtime: https://unpkg.com/browse/daisyui@4.12.13/dist/themes.css

Color values are [OKLCH](https://oklch.com)

Let me know if you have any questions
