### ISSUE TITLE
feature: DaisyUI 5: file-input

### ISSUE THREAD

**Issue by lts20050703** [saadeghi/daisyui#3244]
### What version of daisyUI are you using?

5.0.0-alpha.20

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://play.tailwindcss.com/56OwrCwEaE

### Describe your issue

DaisyUI 5 (5.0.0-alpha.20)

![image](https://github.com/user-attachments/assets/4951daad-48ec-415f-aaec-e030971f4c60)

DaisyUI 4 (4.12.13)

![image](https://github.com/user-attachments/assets/cf58c99e-86f4-4919-82ec-5f31ebaa3218)

**Comment by saadeghi** [comment]
Some components are not ready yet.  
These are available: https://unpkg.com/browse/daisyui@alpha/components/

**Comment by lts20050703** [comment]
I updated to 5.0.0-alpha.29 and looks like it is implemented! Thank you so much! ❤️
