### ISSUE TITLE
bug: prettier adds dev output to the top of the file

### ISSUE THREAD

**Issue by pkpg** [saadeghi/daisyui#3247]
### What version of daisyUI are you using?

v4.12.13

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

not available

### Describe your issue

I am using nvim with lazyvim and I have prettier installed in my project with this setup:
```
{
    "$schema": "https://json.schemastore.org/prettierrc",
    "semi": false,
    "tabWidth": 4,
    "singleQuote": true,
    "printWidth": 100,
    "bracketSameLine": true,
    "trailingComma": "es5",
    "bracketSpacing": false,
    "arrowParens": "always",
    "singleAttributePerLine": true,
    "plugins": ["prettier-plugin-tailwindcss"]
}

```
When I save a `.vue` file, the following output of `npm run dev` gets added to the top of my vue file:
```

🌼   daisyUI 4.12.13
├─ ✔︎ 30 themes added		https://daisyui.com/docs/themes
╰─ ❤︎ Support daisyUI project:	https://opencollective.com/daisyui

<script setup>
...
```

**Comment by saadeghi** [comment]
This is vim issue. I can't do anything about it.  
But as a workaround, you can disable the logs: https://daisyui.com/docs/config/#logs
