### ISSUE TITLE
bug: text is too big for tooltip

### ISSUE THREAD

**Issue by straumat** [saadeghi/daisyui#3256]
### What version of daisyUI are you using?

4.12.14

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://play.tailwindcss.com/wWndQ9FxeZ

### Describe your issue

I would like to use a `tooltip` to display an ethereum address but the address doesn't fit.
I don't see in the documentation how to make the tooltip bigger

**Comment by ShoomanKhatri** [comment]
you can assigned this to me.

**Comment by straumat** [comment]
@saadeghi thanks, you are right.
