### ISSUE TITLE
Page returns an Internal error Go back"

### ISSUE THREAD

**Issue by DameHetfield9803** [saadeghi/daisyui#3259]
### On which page do you see this issue?

https://daisyui.com/docs/layout-and-typography/

### Describe the issue

![image](https://github.com/user-attachments/assets/5ed7d7ad-0f46-4fe8-879c-ced30b04e368)
<img width="1160" alt="Screenshot 2024-11-01 at 9 35 38 PM" src="https://github.com/user-attachments/assets/ae7672ff-c4c2-4ff5-bbf6-e08856bd83cc">

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
Is the issue still happening?
Only this page?

**Comment by DameHetfield9803** [comment]
> Is the issue still happening? Only this page?

It has been resolved, for that time, yes, it was only that page. Thank you Saadeghi.
