### ISSUE TITLE
bug: Emojis get cut off in input on Safari

### ISSUE THREAD

**Issue by abegehr** [saadeghi/daisyui#3260]
### What version of daisyUI are you using?

v4.12.14

### Which browsers are you seeing the problem on?

Safari

### Reproduction URL

https://daisyui.com/components/input-group/

### Describe your issue

Typing some emojis (`💬🚀🆙`) in a basic input field, like the ones in the DaisyUI docs, causes them to be slightly vertically cut off:
<img width="476" alt="Screenshot 2024-11-01 at 23 04 50" src="https://github.com/user-attachments/assets/3da9631c-a6ce-479e-aa0f-44cfd1e339bf">
(you can see the chat bubble bet slightly cut of at the bottom tip and top side, also the "Up!" box is cut off slightly on the top and bottom)

On Chrome it's fine:
<img width="412" alt="Screenshot 2024-11-01 at 23 05 08" src="https://github.com/user-attachments/assets/e5badab5-dfa2-444a-a43e-a4d2feed1a33">

**Comment by saadeghi** [comment]
Can you provide a Tailwind Play link?

**Comment by saadeghi** [comment]
@nilaygit-10721 Yes but can you reproduce the issue, because I wasn't able to see the problem.

**Comment by saadeghi** [comment]
Feel free to re-open the issue after providing a reproduction link.  
it's not possible to debug without seeing the bug.
