### ISSUE TITLE
docs: How to maintain state of collapse and expand submenu?

### ISSUE THREAD

**Issue by vishal-ainow** [saadeghi/daisyui#3264]
### On which page do you see this issue?

https://daisyui.com/components/menu/

### Describe the issue

How to maintain state of collapse and expand submenu? in documentation its only `<details open>` tag. I'm using astro + svelte.
 
<img width="939" alt="Screenshot 2024-11-07 at 2 50 33 AM" src="https://github.com/user-attachments/assets/3c4dcad8-1572-4c07-886c-b21a5a80c321">

### What browsers are you seeing the problem on?

All browsers

**Comment by saadeghi** [comment]
Here's docs for HTML `<details>` tag:  
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

Adding or removing `open` attribute opens or closes the menu. This happens automatically with click (no JS needed) But you can add/remove the `open` attribute using JS if you want to.

Also if you don't want to use `<details>` tag you can use spans and class names to get the same UI:
https://daisyui.com/components/menu/#collapsible-submenu-that-works-with-class-names

Let me know if you have a question.

**Comment by vishal-ainow** [comment]
Is it possible to get click event of `<details>` tag?
