### ISSUE TITLE
bug: spacing between .chat-bubble and .chat-bubble:before is wrong in 4K with various zooms

### ISSUE THREAD

**Issue by beegotsy** [saadeghi/daisyui#3265]
### What version of daisyUI are you using?

The one in daisyui.com

### Which browsers are you seeing the problem on?

Atleast Chrome

### Reproduction URL

https://daisyui.com/components/chat/

### Describe your issue

Hi there,

the `.chat-bubble:before` is separated from the `.chat-bubble` on 3840x2160 monitor and while using a 25%, 75%, 125%, 175% browser zoom and a 150% Windows zoom (if that matters).

Screenshots below for the 125% browser zoom version, on Chrome

![image](https://github.com/user-attachments/assets/ab499010-6666-4c35-9572-ce04e389da1c)

<img width="480" alt="image" src="https://github.com/user-attachments/assets/be44a724-d1b3-4da5-a3e4-1e866e711734">

It doesn't really matter to me, but I just wanted to let you know if it does to you.
Kudos for the library.

**Comment by beegotsy** [comment]
The same happens for the tooptip here: https://daisyui.com/components/tooltip/.

This time, the only ones connected on a 3840x2160 monitor are while using a 67%,90%,200%,250%,400% browser zoom.
This may be more important since at the default 100% zoom it's disconnected.

100%
![image](https://github.com/user-attachments/assets/bd29b4cd-e165-4643-80d3-666cd78176ee)

125%
![image](https://github.com/user-attachments/assets/392417f0-413b-4a96-8e4e-f2d669f0e182)

500%
![image](https://github.com/user-attachments/assets/74fbee9e-57df-4470-9297-c82cdda3e963)

**Comment by saadeghi** [comment]
Which OS is this?  
This looks like a render issue, because there's no space there in CSS.

**Comment by beegotsy** [comment]
@saadeghi thank you for the answer; it indeed seems a render issue.
On my Windows 10 with Chrome 123.0.6312.124 it doesn't work; but on my Windows 11 with 131.0.6778.86 works fine.

```
> ver
Microsoft Windows [Version 10.0.19045.5131]
```
