### ISSUE TITLE
bug: Modal "auto-scrolls" to the bottom

### ISSUE THREAD

**Issue by khesualdo** [saadeghi/daisyui#3283]
### What version of daisyUI are you using?

v4.9.0

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://play.tailwindcss.com/JGH2mvaANj

### Describe your issue

When there is lots of content in the modal box, the modal "auto-scrolls" to the bottom when it is opened.

Not sure if this is considered best practice, but I currently have to do `modalBoxRef.current.scrollTop = 0;` (in React) because I want the user to see the contents of the modal from the very beginning.

I was able to reproduce the issue in Tailwind Play.

**Comment by saadeghi** [comment]
Reproduction link please?

**Comment by roberfi** [comment]
Another fix for this would be creating an internal scrollable div:
https://play.tailwindcss.com/rrV7p5bCiS
