### ISSUE TITLE
bug: Tooltip for button doesn't appear if the button is disabled

### ISSUE THREAD

**Issue by tats-u** [saadeghi/daisyui#3286]
### Which browsers are you seeing the problem on?

Chrome, Firefox

### Reproduction URL

https://codepen.io/tats-u/pen/wvVLOJE

### Describe your issue

`tooltip` for `btn` doesn't work if combined with `btn-disabled` class or `disabled` attribute.
You want to describe why the button is disabled by a tooltip.

**Comment by saadeghi** [comment]
Disabled button disables everything including hover. 
```css
pointer-events: none;
```
There's no way in CSS to disable all events and you would need to manually disable events in JS or replace the button with a fake button.

To show a tooltip, put the button in a wrapper:  
https://play.tailwindcss.com/b8EjL9imA7

Let me know if you have a question.
