### ISSUE TITLE
docs: (v4) using daisyUI color variables with tailwind gradient color stops

### ISSUE THREAD

**Issue by ebarooni** [saadeghi/daisyui#3303]
### On which page do you see this issue?

https://daisyui.com/docs/colors/

### Describe the issue

Im trying to use the daisyUI colors with the gradient color stops from tailwind. But im not sure if i understood the [docs](https://daisyui.com/docs/colors/#:~:text=You%20can%20also%20use%20color%20names%20in%20utility%20classes%20just%20like%20Tailwind%27s%20original%20color%20names.%20These%20are%20utility%20classes%20that%20can%20be%20used%20with%20a%20color%20name%3A) correctly.

I would like to give my element a color gradient and from what i understood the tailwind classes can be used with daisyUI color variables. Therefore the following snippet:

```html
<div class="bg-gradient-to-t from-bg-base-300">...</div>
```

However this does not apply the color. The same snippet if i use any tailwind color variable, for example `from-indigo-500`, works as expected. Is there a possibility to make this combination work or my implementation is wrong? Tnx!

### What browsers are you seeing the problem on?

All browsers

**Comment by saadeghi** [comment]
```diff
- <div class="bg-gradient-to-t from-bg-base-300">...</div>
+ <div class="bg-gradient-to-t from-base-300">...</div>
```

`base-300` is color name. `bg-*`, `from-*`, etc are utility classes.
