### ISSUE TITLE
bug: daisyui/index.js Unknown word (v5)

### ISSUE THREAD

**Issue by atollk** [saadeghi/daisyui#3305]
### What version of daisyUI are you using?

5.0.0-alpha.46

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://github.com/atollk/daisyui_bug

### Describe your issue

When using Vite to run my app  ( `npm run dev` ) and visting any page that loads the DaisyUI CSS plugin, I get the following error:

```
6:17:04 PM [vite] Internal server error: [postcss] postcss-import: /foo/node_modules/daisyui/index.js:1:10: Unknown word
  Plugin: vite:css
  File: /foo/node_modules/daisyui/index.js:1:9
  1  |  import { version } from "./package.json"
     |           ^
  2  |  import { pluginOptionsHandler } from "./functions/pluginOptionsHandler.js"
  3  |  import { plugin } from "./functions/plugin.js"
      at Input.error (/foo/node_modules/postcss/lib/input.js:106:16)
      at Parser.unknownWord (/foo/node_modules/postcss/lib/parser.js:593:22)
      at Parser.other (/foo/node_modules/postcss/lib/parser.js:435:12)
      at Parser.parse (/foo/node_modules/postcss/lib/parser.js:470:16)
      at parse (/foo/node_modules/postcss/lib/parse.js:11:12)
      at get root (/foo/node_modules/postcss/lib/no-work-result.js:119:14)
      at Result.get [as root] (/foo/node_modules/postcss/lib/no-work-result.js:27:21)
      at loadImportContent (file:///foo/node_modules/vite/dist/node/chunks/dep-C6EFp3uH.js:867:33)
      at async Promise.all (index 0)
      at async resolveImportId (file:///foo/node_modules/vite/dist/node/chunks/dep-C6EFp3uH.js:800:27)
```

**Comment by saadeghi** [comment]
Here https://github.com/atollk/daisyui_bug/blob/5c4a4f0665b58fd80cddc43d6c3c4f888df5cbca/src/app.css#L2

Syntax is:
```diff
- @import 'daisyui';
+ @plugin 'daisyui';
```

**Comment by bnnnnnnnnnnnn** [comment]
> https://github.com/atollk/daisyui_bug/blob/5c4a4f0665b58fd80cddc43d6c3c4f888df5cbca/src/app.css#L2
> 
> 你好：
> 
> - @import 'daisyui';
> + @plugin 'daisyui';

Unknown at rule @plugincss(unknownAtRules)

**Comment by mfmasud** [comment]
> > https://github.com/atollk/daisyui_bug/blob/5c4a4f0665b58fd80cddc43d6c3c4f888df5cbca/src/app.css#L2
> > 你好：
> > 
> > * [@import](https://github.com/import) 'daisyui';
> > 
> > 
> > * [@plugin](https://github.com/plugin) 'daisyui';
> 
> Unknown at rule @plugincss(unknownAtRules)

This error appears when I use a vscode-based IDE to write Tailwind v4 code.

<img width="1423" height="540" alt="Image" src="https://github.com/user-attachments/assets/61919ea9-d81d-4ccb-92d7-39f852d0df9d" />

---

See https://stackoverflow.com/a/79513027/19543236 for a solution:

1. Install [TailwindCSS IntelliSense](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) from the  VSCode Marketplace 

<img width="949" height="236" alt="Image" src="https://github.com/user-attachments/assets/b5584fcb-a79c-4188-bdf3-1564b6c2ec24" />

2. Open VSCode settings and search for "files.associations" in the search bar.

<img width="2529" height="381" alt="Image" src="https://github.com/user-attachments/assets/73f12c8d-89aa-41a1-a961-a8be3c495c32" />

3.  Add the value `tailwindcss` for globs `*.css` and `*.scss`.

<img width="2537" height="647" alt="Image" src="https://github.com/user-attachments/assets/1a975800-0297-4c6f-b8d7-a69706e7f0e0" />

**Comment by saadeghi** [comment]
👆  
This is explained in the Tailwind CSS IntelliSense readme:  
https://github.com/tailwindlabs/tailwindcss-intellisense?tab=readme-ov-file#recommended-vs-code-settings

> ## Recommended VS Code Settings
> ### `files.associations`
> Use the `files.associations` setting to tell VS Code to always open `.css` files in Tailwind CSS mode:
> ```json
> "files.associations": {
>   "*.css": "tailwindcss"
> }
> ```
