### ISSUE TITLE
Issue: Aw, Snap! Something went wrong while displaying this webpage, Err code:SIGSEGV

### ISSUE THREAD

**Issue by RisheekOjha24** [saadeghi/daisyui#3307]
### What version of daisyUI are you using?

^4.12.14

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://daisyui.com/

### When I visit the DaisyUI website and click or even hover on the "How to Use" button (or the area nearby), the page crashes and shows the following error:

**_"Aw, Snap! Something went wrong while displaying this webpage."
The associated error code is:
ERR_CODE: SIGSEGV_**

This issue seems to be browser-specific, as it occurs on Google Chrome, but it works perfectly fine in Firefox. The problem persists even after clearing the browser cache and using incognito mode.

**Google Chrome:** Version 124.0.6367.78 (Official Build) (64-bit)

**My Laptop Specification:** 
Hardware Modal: Dell Inc. Latitude 3400
Processor: Intel® Core™ i5-8265U CPU @ 1.60GHz × 8

**My OS Specification**
Distributor ID:	Ubuntu
Description: Ubuntu 22.04.4 LTS
Release: 22.04

![Screenshot from 2024-12-10 12-53-47](https://github.com/user-attachments/assets/73702993-82be-4157-8ef1-d84e82b73065)

**Comment by saadeghi** [comment]
Thanks for reporting, but this is not something I can help with. It's either browser issue or hardware (Memory maybe?) issue.  
Usually updating the browser fixes this, or if it's the latest version of chrome, maybe downgrade to previous version 🤷‍♂️

**Comment by burgalon** [comment]
@saadeghi we're experiencing this also heavily after migrating from Twitter Bootstrap to Daisy

**Comment by saadeghi** [comment]
@burgalon Is this online?
Can you share a link + browser version + OS name?

**Comment by burgalon** [comment]
Yes - astria.ai/prompts or astria.ai/w/zara or
https://www.astria.ai/p/zara-pants
Chrome Version 145.0.7632.119
MacOS

**Comment by saadeghi** [comment]
@burgalon What are the steps to reproduce the error?

https://github.com/user-attachments/assets/28988b17-ce5d-4236-90d8-1573aa93f76d

**Comment by burgalon** [comment]
Hi,

This issue seems to be a combination of CSS, possibly Daisy and Cloudflare
email obfuscation. Once I disabled that, the crashes stopped.
I'm not entirely sure if it's actually Daisy. Sorry for the
missing information.

Alon
