### ISSUE TITLE
bug: [Nexus/Next.JS] Freshly unpacked purchased Nexus Next.JS does not run/compile

### ISSUE THREAD

**Issue by Jan-M** [saadeghi/daisyui#3311]
### What version of daisyUI are you using?

4.12.19

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

none.com

### Describe your issue

I have just purchased the Nexus UI Next.Js version wanted to play around with what looks like a very neat dashboard. Not a NextJs or Tailwind expert I run into below issue. I have only unpacked, npm install, and npm run dev, nothing else. Manually I tried bumping some versions, but hasent resolved the issue.

Any help is appreciated.

```
src/assets/css/custom/_layout.css The `border-base-200` class does not exist. If `border-base-200` is a custom class, make sure it is defined within a `@layer` directive.

  13 |     transition: all 0.3s;
  14 |     background: var(--leftmenu-background);
> 15 |     @apply sticky bottom-0 top-0 h-screen min-w-60 border-e-[1px] border-base-200;
     |     ^
  16 | }
  17 | 
```

**Comment by saadeghi** [comment]
That's not normal 🤔  
Thanks for reporting. 

Can you try `npm i` one more time to see if there are any errors at installing the dependencies?

**Comment by Jan-M** [comment]
I got it up and running, unpacking and running the TS version. I found some hints googling similar errors, talking about some tailwind ts config conflicting tailwind js config. But to me this seemed not to be the case, the unpacked JS version looked alright, no .ts files around.

I use npm 10.9.2, node 23.1.0

```
npm i
(node:56970) ExperimentalWarning: CommonJS module /opt/homebrew/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /opt/homebrew/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

up to date, audited 513 packages in 1s

152 packages are looking for funding
  run `npm fund` for details

4 vulnerabilities (1 low, 2 moderate, 1 high)
```

**Comment by withden** [comment]
Hey @Jan-M,

Thanks for sharing the details.

I tried Typescript & Javascript versions on every Node version (18 to 23).

The Typescript version is working fine on every node version. But for javascript, I get the same error on Nodejs (22 & 23). So yes there is an issue.

You can now use the typescript or javascript version (on Node <= 21).

I'm working on it and will inform you when it resolves.

**Comment by withden** [comment]
Hey @Jan-M,

Please use tailwind.config.mjs (for Node>=22) & use tailwind.config.js (for Node<22).

Feel free to open this issue again, if there is any other error regarding this

@saadeghi please close this issue.

**Comment by saadeghi** [comment]
Thanks @withden   
@Jan-M let us know if changing the extension from .js to .mjs fixes the issue

The package will include this change on Monday.

**Comment by Jan-M** [comment]
Yes, this resolves the issue for me with the Javascript version. Thank you.
