### ISSUE TITLE
bug: V5 `glass` does not work

### ISSUE THREAD

**Issue by J4gQBqqR** [saadeghi/daisyui#3316]
### What version of daisyUI are you using?

5.0.0-alpha.48

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://v5.daisyui.com/docs/utilities/#-2

### Describe your issue

I am using glass class in my website across multiple places. After upgrade to V5, it stops working.

**Comment by J4gQBqqR** [comment]
Glass class is now working with alpha 50. Thank you for your quick turn around and fix!

**Comment by saadeghi** [comment]
@J4gQBqqR let me know if you found anything else missing or not working correctly ✌️
