### ISSUE TITLE
bug: V5 `setAttribute("data-theme", theme)` failed in firefox nightly

### ISSUE THREAD

**Issue by J4gQBqqR** [saadeghi/daisyui#3317]
### What version of daisyUI are you using?

5.0.0-alpha.48

### Which browsers are you seeing the problem on?

Firefox

### Reproduction URL

N/A

### Describe your issue

I am changing theme using the following code:
```ts
<script lang="ts">
	import { s } from "$lib/utilities/Store.svelte";
	import Chart from "chart.js/auto";

	let theme = $derived(s.isDarkMode ? "dim" : "nord");
	$effect(() => {
		window.document.documentElement.setAttribute("data-theme", theme);
	});
</script>
```
`theme` is a derived rune that will change when the isDardMode $state() rune changes. I can change this state rune with a button click.

This is my sveltekit's main page:
```html
<!doctype html>
<html lang="en" data-theme="dim">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width" />
		<link rel="shortcut icon" href="#" />
		%sveltekit.head%
	</head>
	<body data-sveltekit-preload-data="hover">
		<div>%sveltekit.body%</div>
	</body>
</html>

```

This is my app.css:
```css
@import "tailwindcss";
@plugin "daisyui" {
	themes: all;
}
```

- Chrome is working fine:
![图片](https://github.com/user-attachments/assets/2134ba52-ca0b-4d30-a001-8c2d3ea00eaa)
![图片](https://github.com/user-attachments/assets/babf4158-40ad-40d3-921d-89190ab3b7c9)
- Floorp (currently based on Firefox ESR) is working fine:
![图片](https://github.com/user-attachments/assets/5dda5068-893a-47bd-8a2d-47a780ba5070)
![图片](https://github.com/user-attachments/assets/faa6cbb1-e867-414d-a51b-52d6d0d95345)

-------------------------------------------------------------------------

- However, Firefox nightly fail to change theme:
![图片](https://github.com/user-attachments/assets/59e5f24e-fdd8-422c-b2bc-9f3cf91edb70)
![图片](https://github.com/user-attachments/assets/10f7c34b-e25b-4146-913e-781d1285a27f)

**Comment by J4gQBqqR** [comment]
Hi @saadeghi, I can use a private channel to provide you a reproduction link to my deployed dev site for you to see this. Let me know if you want one and how to send this link privately to you.

**Comment by saadeghi** [comment]
Sure. pouya@daisyui.com

**Comment by J4gQBqqR** [comment]
It is now working in version alpha 49. Thank you for your awesome work!

**Comment by saadeghi** [comment]
Yeah. The theme rules were being applied by the wrong order. Fixed now 💚
