### ISSUE TITLE
bug: V5 Dropdown mispositioning using popover API and anchorpositioning

### ISSUE THREAD

**Issue by J4gQBqqR** [saadeghi/daisyui#3322]
### What version of daisyUI are you using?

5-alpha49

### Which browsers are you seeing the problem on?

Firefox

### Reproduction URL

https://v5.daisyui.com/components/dropdown/

### Describe your issue

![image](https://github.com/user-attachments/assets/3a43bef9-09d8-4324-9cd6-18359add716b)

It happens on both normal Firefox and Firefox nightly

**Comment by saadeghi** [comment]
Anchor positioning is the standard solution for dropdowns, but it's very new.  
Firefox doesn't support it yet: https://caniuse.com/css-anchor-positioning
So as and incremental adaptation, we show the dropdown in the middle of screen. It works, it doesn't break the functionality, but it shows in the middle of screen like a modal.

There's a polyfill that makes it work until Firefox adds the support:  
https://github.com/oddbird/css-anchor-positioning

Alternatively you can still use the other methods such as
- [details and summary elements](https://v5.daisyui.com/components/dropdown/#method-1-details-and-summary)
- [CSS focus](https://v5.daisyui.com/components/dropdown/#method-3-css-focus)
