### ISSUE TITLE
bug: Toggle switch checkboxes break when focused

### ISSUE THREAD

**Issue by B1tWhys** [saadeghi/daisyui#3329]
### What version of daisyUI are you using?

4.12.22

### Which browsers are you seeing the problem on?

Chrome, Firefox

### Reproduction URL

https://github.com/B1tWhys/daisyui-toggle-bug-report

### Describe your issue

Hi, I'm having an issue where toggle switches are rendering completely gray when focused, but render completely fine once focus goes away:

![screenshot](https://github.com/user-attachments/assets/5604b78f-7031-4513-b31b-fa79d68bf862)

Here's a repo that reproduces the error (see the readme for more detailed reproduction steps): https://github.com/B1tWhys/daisyui-toggle-bug-report

Thanks in advance!

**Comment by saadeghi** [comment]
This style is from `@tailwindcss/forms`, not daisyUI

If you really need `@tailwindcss/forms` use their class strategy so it doesn't apply styles to all inputs on the page.

Let me know if you have any questions

**Comment by B1tWhys** [comment]
Ah, woops. That makes sense. Thanks for the quick response!

**Comment by AckermannTM** [comment]
I had the same issue. Removing @tailwindcss/forms from `tailwind.config.js` fixed the issue! Thank you guys :D
