### ISSUE TITLE
window.scroll not working inside drawer-content

### ISSUE THREAD

**Issue by anhsirk0** [saadeghi/daisyui#333]
I have few elements inside drawer that uses window.scroll and window.scrollY to function.
Inside drawer-content window.scrollY is always 0 and window.scroll is not working anymore.
It works if I remove drawer.
Please help.

**Comment by anhsirk0** [comment]
Sorry for replying late.
I created a simple react project with create-react-app.
https://github.com/anhsirk0/daisy-drawer

Thanks

**Comment by saadeghi** [comment]
@anhsirk0  
instead of
```js
window.scroll({ top: y, behavior: "smooth" })
```
use this:
```js
document.querySelector('.drawer-content').scrollTo({ top: y - 70, behavior: "smooth" })
```
> (`70` is optional offset for navbar)

**Comment by anhsirk0** [comment]
Thanks this works.
Also i was having problem with 

```javascript
window.addEventListener("scroll", scrollFunction);
```

which I solved using similar method, 
```javascript
document.querySelector('.drawer-content').addEventListener("scroll", scrollFunction);
```

Thanks again.

**Comment by biplobsd** [comment]
> Thanks this works. Also i was having problem with
> 
> ```js
> window.addEventListener("scroll", scrollFunction);
> ```
> 
> which I solved using similar method,
> 
> ```js
> document.querySelector('.drawer-content').addEventListener("scroll", scrollFunction);
> ```
> 
> Thanks again.

And this...
Getting scroll value
```js
window.scrollY
```
to 
```js
document.querySelector('.drawer-content')!.scrollTop
```
🚀

**Comment by Krak86** [comment]
> ```js
> document.querySelector('.drawer-content')
> ```

Thanks man, you saved my day

**Comment by Krak86** [comment]
I think with last version of libs that problem is fixed automatically, using window:
`window.addEventListener("scroll", scrollFunction);`
In my case when I set the next libs I going to set `window.addEventListener` back again:
```
"react-daisyui": "^4.1.0",
"daisyui": "^3.6.1",
"tailwindcss": "^3.3.3",
```
