### ISSUE TITLE
bug: Navbar/Tab Navigation Not Switching Correctly in DaisyUI Version 4.12.22

### ISSUE THREAD

**Issue by FerdianFy13** [saadeghi/daisyui#3333]
### What version of daisyUI are you using?

v4.12.22

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://daisyui.com/components/dropdown/

### Describe your issue

In DaisyUI version 4.12.22, there is an issue with the Navbar or Tab Navigation component where the active item does not switch when selecting a new item. The switch only happens after the page is reloaded.

**Steps to Reproduce**

Install DaisyUI version 4.12.22.
Create a Navbar or Tab Navigation component.
Click on the first item (e.g., "Home").
Click on the second item (e.g., "About").
Notice that the component remains on the initial item ("Home") and does not switch to the new item ("About").
Reload the page, and only then does the active item switch.
Expected Behavior
The Navbar or Tab Navigation should immediately switch to the selected item without requiring a page reload.

**Actual Behavior**
The active item stays on the initial item, and only switches after reloading the page.

**Environment**

DaisyUI version: 4.12.22
Framework: Tailwind CSS
Browser: Chrome version 131.0.6778.205 (Official Build) (64-bit)
Operating System: Windows 11
Additional Information
This issue seems to occur when the application has been idle for a long time. It could be related to DaisyUI's internal state management or a conflict with Tailwind CSS.

**Temporary Workaround**
Reloading the page resolves the issue temporarily, but this is not an ideal solution.

**Comment by saadeghi** [comment]
My friend, daisyUI is a CSS framework. CSS is for styles, not routing…  

When your first item has an "active" class, clicking it is not going to magically move the class name to the next item. You should add the active class, based on your framework or routing library. For example if you are using a JS framework, you should check compare the current path with the path of the link, then if it was same, you add the "active" class. This way framework will change the class to the next item when you click it.

Let me know if you have a question.
