### ISSUE TITLE
bug: Tooltip does not shown under overflow

### ISSUE THREAD

**Issue by FilipBudzynski** [saadeghi/daisyui#3346]
### What version of daisyUI are you using?

v4.12.23

### Which browsers are you seeing the problem on?

Chrome, Safari

### Reproduction URL

https://play.tailwindcss.com/3jYJ52TPoP

### Describe your issue

Tooltips does not seem to be shown under the overflow-x-auto or any other overflow.
Additionally I would like to ask for the tooltips to be added to "steps" or if there is any workaround to that.
Keep the great work guys!

**Comment by saadeghi** [comment]
It will be possible in v5.

**Comment by FilipBudzynski** [comment]
Great to hear that! Thanks for quick response, cheers

**Comment by asabatba** [comment]
Hi! This should be working, right?
In the following example the tooltip is still being cut by the parent:

https://jsfiddle.net/pea2vowx/6/

Thanks

**Comment by icobg123** [comment]
Any fix for this, even in v5 it seems to still be happening.

**Comment by saadeghi** [comment]
In CSS when  there's an `overflow-scroll` in one direction the other direction will be cropped. This is the expected behavior and not a bug. For example we can't have vertical scroll on div and horizontal overflow at the same time.

There are JS libraries who fix this issue by placing the actual tooltip outside of the page content and then observing the element's position and moving the tooltip to that position. That method requires JS and as you can guess constantly observing the location of elements in JS is not efficient at all.

The CSS solution for this would be using CSS anchor positioning. We will be using that for tooltips as soon as Safari and Firefox start supporting this new CSS feature.

**Comment by icobg123** [comment]
Thank you for the succinct explanation, glad to hear there is an upcoming solution to this issue.

**Comment by wszgrcy** [comment]
> In CSS when there's an `overflow-scroll` in one direction the other direction will be cropped. This is the expected behavior and not a bug. For example we can't have vertical scroll on div and horizontal overflow at the same time.
> 
> There are JS libraries who fix this issue by placing the actual tooltip outside of the page content and then observing the element's position and moving the tooltip to that position. That method requires JS and as you can guess constantly observing the location of elements in JS is not efficient at all.
> 
> The CSS solution for this would be using CSS anchor positioning. We will be using that for tooltips as soon as Safari and Firefox start supporting this new CSS feature.

this feature was supported
https://caniuse.com/css-anchor-positioning

**Comment by icobg123** [comment]
Any plans on reworking the tooltips to use tthe css anchor positioning?

**Comment by saadeghi** [comment]
@icobg123 Yes. Now all browsers support anchor positioning. Tooltip with anchor positioning will be added in the next minor update soon (v5.6)

**Comment by DallasHoff** [comment]
Did this make it into 5.6? I can't find a reference to it in the docs.

**Comment by saadeghi** [comment]
Unfortunately no. There's a blocker from Safari that I wasn't aware of.

The plan was to implement it with popover API and anchor positioning. And for it to trigger with hover (as expected for a tooltip) we need `popover="hint"` but Safari is not supporting it yet. Unfortunately.

https://caniuse.com/wf-popover-hint

Meaning if we add this to daisyUI now, tooltips won't work on Safari nor on iOS 🤦‍♂️

**Comment by maxschmalenbach** [comment]
Hi, has there been any update so far?

**Comment by saadeghi** [comment]
> Hi, has there been any update so far?

Safari still doesn't support hint.  

You can check the current status here: https://caniuse.com/wf-popover-hint

This is not about daisyUI. If we want to use native CSS/HTML tooltips using CSS anchor positioning, we have to wait for Safari to support Popover hint.
