### ISSUE TITLE
Feature Request: Horizontal Steps

### ISSUE THREAD

**Issue by ThaddeusJiang** [saadeghi/daisyui#335]
Hey Team,

thanks for developing such a fantastic UI library. It has been a joy to use.

My product is responsive design, my design is

* Mobile:  Vertical Steps
* PC: Horizontal Steps

the code should 

```
class="steps steps-vertical md:steps-horizontal"
```

Thank you so much.

**Comment by tranvansang** [comment]
How about a similar feature for `card` and `menu`. For now, there is only compact class for them.

**Comment by saadeghi** [comment]
@tranvansang yes. Definitely would be useful. I will work on them but let's keep this issue relative to its title.
