### ISSUE TITLE
Extra padding on first line of `<code>` when using `tailwindcss-typography`

### ISSUE THREAD

**Issue by saadeghi** [saadeghi/daisyui#337]
With DaisyUI: https://play.tailwindcss.com/iWp6pl2vD6?file=config  
Without DaisyUI: https://play.tailwindcss.com/4gM0NQjxxT?file=config

more info:  
https://github.com/tailwindlabs/tailwindcss-typography/issues/227  
https://github.com/tailwindlabs/tailwindcss/discussions/6523
thanks to @spences10

**Comment by spences10** [comment]
Yay! I'm helping!! 😊
