### ISSUE TITLE
Question - open/close drawer programmatically

### ISSUE THREAD

**Issue by gjovanov** [saadeghi/daisyui#34]
Hi there,
I'm trying to understand if have some kind of reliable `state` or `indicator` that a `drawer` is opened or closed and how we can open/close a drawer component programmatically?

I've tried to e.g. to change the checked value of the checkbox ([first example](https://daisy.js.org/components/drawer)) by this Svelte code:

```html
<input id="my-drawer" type="checkbox" class="drawer-toggle" checked={checked}> 

<div class="flex flex-col items-center justify-center drawer-content">
    <label id="my-drawer-label" for="my-drawer" class="btn btn-primary drawer-button">open menu</label>
  </div> 

...
<button id="btn1" class="btn" on:click={toggleDrawer1} > open/close drawer </button>

<button id="btn2" class="btn" on:click={toggleDrawer2} > open/close drawer </button>
``` 

```javascript

let checked = false

const toggleDrawer1 = () => {
   checked = !checked
}

const toggleDrawer2 = () => {
  const elem = document.getElementById('my-drawer-label')
  elem.click()
}
 
```

It seems that clicking on `id="btn1"` doesn't result in drawer being opened/closed, even though the `checked` variable is being changed.

Clicking on `id="btn2"` does open/close the drawer.

However, our issue when the drawer is opened and clicking anywhere on the overlay and closing the drawer, it doesn't change the checkbox `id="my-drawer"` checked value so we don't have a `state` per say, that we can rely on that the Drawer is opened or closed based on which we can show or hide some UI components.

So maybe to rephrase our question, is there anything reliably we can use as a `state` of the `drawer` by which we can know in the code if the `drawer` is shown or hidden? e.g. checkbox checked value or element having certain class or any other indicator?

The same state would be valuable to know in other components e.g. in `accordion`, to know if it's open or closed.

I hope I was clear enough.

Thanks.

**Comment by saadeghi** [comment]
Hi @gjovanov,
Whenever checkbox is checked, drawer opens and whenever it's unchecked, drawer gets closed. There's no trick.

As you can see [here](https://github.com/saadeghi/daisyui-demo/blob/3323b23ff916a4e0e1f3d8fe673f3135afd8844a/layouts/default.vue#L5) I'm controling the drawer of [daisy.js.org](https://daisy.js.org) using the checkbox.  
It's a Vue project tho. I'm not sure how Svelte works but if you manage to check/uncheck the checkbox somehow, it will work. Maybe your Svelte code is changing the virtual DOM somehow and is not effecting the actual checkbox. Unfortunately I don't have any experience with Svelte.

**Comment by saadeghi** [comment]
@gjovanov Have you tried using `bind:checked={checked}` instead of `checked={checked}`  
I found [this](https://svelte.dev/tutorial/checkbox-inputs) example and it seems to only work with `bind:checked`

**Comment by gjovanov** [comment]
Hey @saadeghi ,
thanks for the suggestion.

Svelte doesn't have a Virtual DOM and it's more like a Compiler that compiles the reactivity into Vanilla JS. But, indeed, the issue was related to Svelte specifics with the bindings.

`bind:checked={checked}` works whereat `checked={checked}` doesn't. Still no idea why.

But in case when using a writable store like this:

```javascript
const checked = writable(false)
```

then both of them work (notice the $ sign in the binding):
```html
<input id="my-drawer1" type="checkbox" class="drawer-toggle" checked={$checked}>

<input id="my-drawer2" type="checkbox" class="drawer-toggle" bind:checked={$checked}>
```

Anyways, sorry to bother you with issues not related to Daisy UI.

The good news there is a way to manipulate the state of components like `drawer`, `accordion` etc via the state if its checkbox.

Thanks again..

Closing...
