### ISSUE TITLE
Button animations not working in Firefox 95 on Ubuntu

### ISSUE THREAD

**Issue by suneg** [saadeghi/daisyui#343]
I've noticed that the button animations do not work on latest Firefox (95.0) on Ubuntu 20.04. 

Firefox 95.0 on Ubuntu 20.04: :x: 
Chromium on Ubuntu 20.04: :heavy_check_mark: 
Firefox 95.0.2 on OSX 12.1: :heavy_check_mark: 
Chrome 96.0 on OSX 12.1: :heavy_check_mark: 

Screen recording (Firefox 95.0 on Ubuntu 20.04):
https://user-images.githubusercontent.com/1258383/146758049-e587a697-0dc1-42ac-b529-36a355265b36.mp4

**Comment by saadeghi** [comment]
@suneg I think you're just using a theme (`corporate`) that doesn't have button animations. That's just the config for that specific theme. If you want to add button animations for that specific theme, you can do it by [changing `--animation-btn` variable](https://daisyui.com/docs/add-themes)
