### ISSUE TITLE
help: lose step class in Next.js build

### ISSUE THREAD

**Issue by ThaddeusJiang** [saadeghi/daisyui#347]
reproduce repo:
https://github.com/ThaddeusJiang/daisyui-lose-step-class-in-nextjs

in dev: 
![CleanShot 2021-12-21 at 15 38 30@2x](https://user-images.githubusercontent.com/17308201/146883420-94f98404-3035-4eee-995b-1eb4bc4628aa.jpg)

in prod:
![CleanShot 2021-12-21 at 15 34 20@2x](https://user-images.githubusercontent.com/17308201/146883371-fe32646b-e4da-4da4-bb9c-900ee5091908.jpg)

lose `step` class

![CleanShot 2021-12-21 at 15 43 38@2x](https://user-images.githubusercontent.com/17308201/146884027-7e089f37-1ce9-4b41-8788-fc1036976ff4.jpg)

Can't  find daisyUI in  build log 

![CleanShot 2021-12-21 at 17 10 41@2x](https://user-images.githubusercontent.com/17308201/146894678-0fdd9f51-e046-430b-9c59-d9325c347779.jpg)

**Comment by saadeghi** [comment]
In latest version, there's been [a change](https://github.com/saadeghi/daisyui/commit/7ba7d6534b6a2abc6b6077faba4c2a5431307b42) with `steps` to make them responsive. To make this possible I had to change `.steps .step` to `.steps [class~=step]` ([reason](https://github.com/tailwindlabs/tailwindcss/issues/3361#issuecomment-927879795))  
It looks like if you're not using JIT mode, that will be purged.  

**So, the solution to this would be:**
1. Using JIT mode:
```js
//tailwind.config.js
module.exports = {
  mode: 'jit',
}
```
2. Or, safe listing the selector:
```js
//tailwind.config.js
module.exports = {
  purge: {
    content: ["./pages/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
    options: {
      safelist: [
        /[class~=step]$/,
      ]
    },
  },
}
```

**Comment by ThaddeusJiang** [comment]
@saadeghi Thank you so much. It was fixed.
