### ISSUE TITLE
Stats Sections Width don't Align

### ISSUE THREAD

**Issue by MentalGear** [saadeghi/daisyui#348]
When stats are stacked horizontally, it becomes apparent that the columns are a bit off between each other (white lines, highlighted with red lines), as portrayed on the [stat example page](https://daisyui.com/components/stat).

Optimally, they would always be the same width (1/2, 1/3, ...) and the content would had to wrap inside or get cut off.

<img width="1446" alt="Screenshot 2021-12-21 at 10 50 24" src="https://user-images.githubusercontent.com/2837147/146909124-c3eeb5c2-13f9-41be-aa31-49e0dd41b97c.png">

**Comment by saadeghi** [comment]
@MentalGear By default I don't want to force layouts to have a specific number of columns or have specific width. It can be 2 columns, it can be 8 columns. one column can have wide content, one can have smaller content. It's not for me to decide.  
But if you need to have 3 equal columns, you can use `stats grid-cols-3`  
Example: https://play.tailwindcss.com/4tPHi2guea

**Comment by MentalGear** [comment]
Thx man, would be great to have this tip also in the docs, but I can't find the page to add it.

**Comment by saadeghi** [comment]
You can use all Tailwind utility classes, Here's btn-group with even widths: https://play.tailwindcss.com/2lZbNHOjyB
