### ISSUE TITLE
Breaks Nuxt-WindiCSS with Nuxt 3

### ISSUE THREAD

**Issue by Destaq** [saadeghi/daisyui#349]
Encountering a similar issue when trying to #178  combine `nuxt-windicss` and `daisyui` - this issue only crops up when `transform`ing `daisyui` (as below). The difference here is that I am using Nuxt v3.

```js
const { transform } = require("windicss/helpers");

module.exports = {
  plugins: [transform("kutty")],
};
```

The error message that crops up:

```
 ERROR  Cannot start nuxt:  Maximum call stack size exceeded                                                                                         13:11:14

  at guessClassName (node_modules/windicss/lib/index.mjs:364:24)
  at node_modules/windicss/lib/index.mjs:367:67
  at Array.map (<anonymous>)
  at guessClassName (node_modules/windicss/lib/index.mjs:367:41)
  at node_modules/windicss/lib/index.mjs:367:67
  at Array.map (<anonymous>)
  at guessClassName (node_modules/windicss/lib/index.mjs:367:41)
  at node_modules/windicss/lib/index.mjs:367:67
  at Array.map (<anonymous>)
  at guessClassName (node_modules/windicss/lib/index.mjs:367:41)
```

Sample repo is [here](https://github.com/Destaq/nuxt3-windi-daisyui). Any way to overcome this issue?

**Comment by saadeghi** [comment]
@Destaq 
I'm not sure if it's from Nuxt or Windi, there are issues about this ([#1](https://github.com/nuxt/nuxt.js/issues/6294), [#2](https://github.com/nuxt/nuxt.js/issues/1354)) on Nuxt repo but they don't seem helpful for this case. You might want to open an issue on Windi repo or Nuxt repo.

I tested your project with Tailwind (instead of Windi) and everything works just fine.  
Here's a sample project config with Nuxt3 and Tailwind:  
https://github.com/saadeghi/daisyui/tree/master/examples/nuxtjs-v3

**Comment by Fanna1119** [comment]
this issue is still present(without nuxt)

```js
import { transform } from 'windicss/helpers'
import { defineConfig } from 'vite-plugin-windicss'

export default defineConfig({
    darkMode: false,
    theme: {
        extend: {
            colors: require('daisyui/colors/windi'),
        },
    },
    extract: {
        include: ['index.html', 'src/**/*.{vue,html,jsx,tsx}'],
        exclude: ['node_modules/**/*', '.git/**/*'],
    },
    plugins: [transform('daisyui')],
})



```

**Comment by saadeghi** [comment]
There are similar reports from Vite+Windi so I'm pretty sure the problem is from Windi itself.  
I would suggest using Tailwind CSS 3.0 instead of Windi. Now with JIT mode, I'm not sure if there's an advantage of using Windi instead of Tailwind CSS 🤷‍♂️

**Comment by old-zoomer** [comment]
If anyone still experiencing this error try updating windicss to latest version, `3.5.1` fixed it for me

**Comment by saadeghi** [comment]
That's great! Thanks @old-zoomer
