### ISSUE TITLE
Modal aligned button on mobile

### ISSUE THREAD

**Issue by hamzafaouzi** [saadeghi/daisyui#355]
@saadeghi daisyui modals are alligned to the bottom on mobile (breakpoint
<img width="505" alt="Screenshot 2021-12-25 at 12 07 44" src="https://user-images.githubusercontent.com/16428139/147383662-a14cc8a9-1a43-4358-8fcc-95fd64cd0f18.png">
)

**Comment by saadeghi** [comment]
@hamzafaouzi please provide more details about this issue.

**Comment by hamzafaouzi** [comment]
@saadeghi

**Comment by saadeghi** [comment]
Yes. This is for better accessibility.  
On a desktop resolution, modal is on center of screen to get more attention. On mobile, there's less space and modal fills most of the space anyway so there's no reason to be on center. It's better to put it on the bottom so user can reach the content more easily.
