### ISSUE TITLE
beautify the list for form-select components 

### ISSUE THREAD

**Issue by chenshuichao** [saadeghi/daisyui#357]
<img width="366" alt="Screen Shot 2021-12-26 at 11 22 07 AM" src="https://user-images.githubusercontent.com/77186544/147398099-e815d2dc-bfe7-4c63-be49-b79d29dc1978.png">

Why not compose the dropdown component :
<img width="228" alt="Screen Shot 2021-12-26 at 11 23 29 AM" src="https://user-images.githubusercontent.com/77186544/147398115-e66c82df-4462-449b-a6af-7444bb508e25.png">

**Comment by saadeghi** [comment]
`<select>` is the native HTML tag that handles picking values itself. [`dropdown`](https://daisyui.com/components/dropdown) is a visual menu without functionality. You can put links in it.  
But if you want `dropdown` to work as a functional `<select>` element, you should write custom JS to handle the functionality (or use libraries like [Headless UI](https://headlessui.dev/) - [[example]](https://github.com/saadeghi/daisyui/tree/master/examples/nextjs-headlessui))  
I wish there was a way to style the elements of native `<select>` element using CSS but it's not possible.
