### ISSUE TITLE
Allow Collapse to remain `collapse-open` when clicking on other collapse item

### ISSUE THREAD

**Issue by andrehadianto** [saadeghi/daisyui#361]
Currently, collapse item will automatically close when another collapse item is opened. There should be an option to keep it open until clicked

**Comment by saadeghi** [comment]
Check out examples: https://daisyui.com/components/collapse  
This one: `with checkbox (works with checkbox instead of focus)`

**Comment by andrehadianto** [comment]
How do I do that? Is there an example for collapse with checkbox?

**Comment by saadeghi** [comment]
It's in the page I linked: https://daisyui.com/components/collapse
Here's the Tailwind Play page: https://play.tailwindcss.com/zGSpy2fHAG

**Comment by andrehadianto** [comment]
Can you give an example where there are two `collapse-content`. One is `collapsed` and the other one is `closed`. When I click on the `closed` one, Both `collapse-content` will remain open.
