### ISSUE TITLE
Dark mode automatically applies and looks ugly on oculus browser

### ISSUE THREAD

**Issue by janat08** [saadeghi/daisyui#363]
I don't know if this is upstream, but dark mode turns on oculus browser, and it looks pretty ugly. Like some background colors just go black while text color doesn't change to white.

**Comment by janat08** [comment]
Considering github is also dark mode, it would seem dark mode on the whole isn't something you want to look at with daisyui. I have a striped table with disabled buttons, and you can't tell whats in those rows.

**Comment by janat08** [comment]
Quick fix for this would be just not having having dark mode.

**Comment by saadeghi** [comment]
I don't have access to an Oculus browser to test this but here's how it works:  
By default, theme applies to `<html>` tag and [there's a style](https://github.com/saadeghi/daisyui/blob/master/src/base/colors.css) that sets text color and background color to the root element. If it's light theme, text color will be dark. If it's dark theme, text color will be light.  
So, there shouldn't be any issues. However, if you're seeing dark text on dark background, try adding `text-base-content` class to the root element or the section that has this issue. this will fix the text color.

Also, you can add your own custom theme with customized colors: https://daisyui.com/docs/add-themes
You can name it as `dark` to replace the default `dark` theme

Let me know if you have any questions.

**Comment by janat08** [comment]
I fixed it. it would seem default theme didnt apply, until specified.
data-theme="lagh" in html tag as attribute. Some elements are still dark
for some reason, but stuff looks much better now. I didn't use daisyui
through out, so stuff looks pretty bad when you apply a theme.
