### ISSUE TITLE
Tailwind v3 support

### ISSUE THREAD

**Issue by anthonywebb** [saadeghi/daisyui#367]
With tailwind v3 here, how difficult will it be to support it with Daisy?  I noticed tailwindui has support out of the gate, but I dont know what that entailed for them. https://tailwindcss.com/blog/tailwindcss-v3

**Comment by saadeghi** [comment]
@anthonywebb daisyUI is compatible with Tailwind CSS 3.0 and there are no issues.  

You might want to check out the Tailwind CSS 3.0 changes: https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.0.0

**Comment by ajonp** [comment]
@saadeghi can we bump the dev dependencies from 
`"tailwindcss": "2.0.1"`
to
`"tailwindcss": "+2.0.1"`

**Comment by saadeghi** [comment]
@ajonp what does that `+` mean? I'm not sure if that's a correct semver syntax.

**Comment by ajonp** [comment]
@saadeghi sorry yep `>=`

**Comment by saadeghi** [comment]
@ajonp If you're referring the tailwindcss dev dependency of daisyUI package, I must say that won't affect your project. daisyUI has no dependencies and de dependencies are only for building the package. However I will update it to v3.0 when I'm done building the new docs site (will be finished this month).  

If you're referring the tailwindcss dependency on your project, it's up to you. You can use any version. I would suggest using the latest version (3.0)
