### ISSUE TITLE
Build components from another directory

### ISSUE THREAD

**Issue by Afshar07** [saadeghi/daisyui#368]
Hello dear Pouya.
I have a problem with building config, my main project is in '/folderOne' and i've got some core components in another folder ('/core').
I've used some daisyUI components in core, in dev server it's rendered as it should, but when i build, daisyUI don't recognize that components and styles are not added!.
Is there any way you can think of to solve this problem?
Thanks in advanced, you've done a great job, really appreciate daisy.

**Comment by saadeghi** [comment]
@Afshar07 I think your config is not including the path to all your template files.  
See content config here: https://tailwindcss.com/docs/installation

**Comment by Afshar07** [comment]
@saadeghi Thanks for your reply, i tried including it in tailwind config and nothing changed!
daisy classes are set, and in dev mode it works fine!
But on production it purges all classes and not include it (Only in external components).
Is there any way to set daisy classes to a whitelist or something?

**Comment by Afshar07** [comment]
Nuxt config:
 `      components: [
        "~/components",
        "../core"
      ],`
tailwind config: 
`content: [
    "../core/*.{js,vue,ts}"
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./nuxt.config.{js,ts}",
  ],`

and here is my component structure which is not loading classes properly: 
`  <div class="w-full shadow stats rounded-none">
    <div
      class="stat place-items-center place-content-center"
      v-for="stat in stats"
      :key="stat.order"
    >
      <div class="stat-title">
        {{ stat.title }}
      </div>
      <div class="stat-value my-2" :class="statClass(stat)">
        {{ stat.value }}
      </div>
    </div>
  </div>`

**Comment by saadeghi** [comment]
@Afshar07 Can you create a sample repo so I can reproduce the issue?

**Comment by Afshar07** [comment]
@saadeghi Yeah sure, Here you are.
[Sample Repo](https://github.com/Afshar07/daisyPurgeProblem)
Thanks for your kindness.

**Comment by saadeghi** [comment]
@Afshar07 Not working
```
 ERROR  Please set HOST_ADD in .env file                                                            


 ERROR  Cannot read property 'default' of undefined                                                 

  at Object.loadNuxtConfig (node_modules/@nuxt/config/dist/config.js:1090:21)
  at async loadNuxtConfig (node_modules/@nuxt/cli/dist/cli-index.js:338:19)
  at async NuxtCommand.getNuxtConfig (node_modules/@nuxt/cli/dist/cli-index.js:463:20)
  at async Object._listenDev (node_modules/@nuxt/cli/dist/cli-dev.js:75:20)
  at async Object.startDev (node_modules/@nuxt/cli/dist/cli-dev.js:58:14)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-dev.js:52:5)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)


 FATAL  Error while fetching async configuration                                                    


   ╭──────────────────────────────────────────────╮
   │                                              │
   │   ✖ Nuxt Fatal Error                         │
   │                                              │
   │   Error while fetching async configuration   │
   │                                              │
   ╰──────────────────────────────────────────────╯

```

**Comment by Afshar07** [comment]
@saadeghi Im sorry, my mistake.
I set up a new project in same link, you can see it now.
In dev mode everything is fine, but when you build it will purge all classes even when i add them to tailwind content.
[Sample Repo](https://github.com/Afshar07/daisyPurgeProblem)

**Comment by saadeghi** [comment]
You just removed everything and added a git submodule instead that I don't have access to 😐

**Comment by Afshar07** [comment]
@saadeghi Apologies again, im new to this.
I think it's okay now.
Thanks for your patience.

**Comment by Afshar07** [comment]
@saadeghi Hey dear Pouya, did the sample repo work correctly?

**Comment by saadeghi** [comment]
In `tailwind.config.js` I replaced `content` with `purge` and it works now.  
I think `@nuxtjs/tailwindcss` package is not updated with lates Tailwind CSS config syntax.

**Comment by Afshar07** [comment]
Thanks a lot, reallllly appreciate your help!
