### ISSUE TITLE
Data-theme not working on first render

### ISSUE THREAD

**Issue by alvaroserrrano** [saadeghi/daisyui#370]
I made a React hook that sets the theme based on a value in local storage. The hook works and it shows the correct result if I log it to the console. However, the value in the html remains incorrect.
Theming works fine after I toggle the switch. The issue only occurs on the first render. For instance, the toggle button works well according to the hook value. The only problem comes when setting the HTML on the first render
In the example below
```
 <ThemeProvider
            render={
              (theme: string) => {
                 console.log(theme) //shows the value I want
                return (
                  <div className='h-full text-base-content bg-base-100' data-theme={theme}> // shows an incorrect value
                    <PageRenderer {...props} />
                  </div>
                )
              }
            }
          />
```

**Comment by saadeghi** [comment]
@alvaroserrrano can you provide a small repo or a code sandbox page so I can try your code?

**Comment by alvaroserrrano** [comment]
![Screen Shot 2021-12-31 at 7 26 21 PM](https://user-images.githubusercontent.com/43758471/147835501-5bfb9ef6-a5aa-4877-8e18-2af7c637d821.png)
For example, in the screenshot below the dark mode is set as you can see in the toggle. My react components take the correct value "synthwave", however, as you can see the light mode is displayed and the html remains with data-theme="cupcake". If I click again the value on local storage changes to "cupcake" (light) and the light mode remains (as it should be), and from that point on the theme starts matching the value on local storage. Notice that the user sees the light mode even though the button reflects the "synthwave" value stored in local storage. Consequently, the user has to toggle twice to finally get the "synthwave" theme and for the site to start working properly

**Comment by alvaroserrrano** [comment]
This CodeSandbox is not working but it should give you an idea. I am using React, and Tailwindcss with the DaisyUI plugin and custom hooks to set and read the theme from local storage

**Comment by alvaroserrrano** [comment]
```
const ThemeProvider = (props: React.PropsWithChildren<AppProps<{}>>): ReactElement => {
  const { theme } = useTheme()
  console.log(theme) // "synthwave"
  return (
    <div className='h-full text-base-content bg-base-100' data-theme={theme}>
      <PageRenderer {...props} />
    </div>
  )
}
```
![Screen Shot 2022-01-01 at 11 25 48 AM](https://user-images.githubusercontent.com/43758471/147848553-b697f21e-98d2-4789-84a3-55b0d4b894fb.png)

**Comment by saadeghi** [comment]
@alvaroserrrano My friend, you're asking a React question on a CSS library repo. And you you're not even providing me a reproduction repo so I can run your code and see what's the problem 😅

**Comment by saadeghi** [comment]
Anyway, I think this might help you: https://github.com/saadeghi/theme-change

**Comment by alvaroserrrano** [comment]
I forgot to link the codesandbox, here it is in case you want to look at it
https://codesandbox.io/s/fervent-euclid-g1rbp?file=/src/App.js:480-494

**Comment by alvaroserrrano** [comment]
I am closing it. I was using Next.js and, therefore, it was rendering on the server, so your library would not work with my code. Sorry about that. Nice work on this library!

**Comment by saadeghi** [comment]
I can't run your code. It's not changing the theme or printing any console log. I also tried to download the files but there are missing files:
```js
Compiled with problems:X
ERROR in ./src/ToggleTheme.js 31:36-40
export 'Icon' (imported as 'Icon') was not found in './components/ui/Icon' (possible exports: default)
```
daisyUI is a CSS library and It has nothing to do with the JS.  
And theming is simple. It reads `data-theme` attribute from DOM. If there is `data-theme="cupcake"` on <html> tag, it shows the cupcake theme. it's CSS selector. not JS.
**That's why I said it's a react question.** You're trying to change `data-theme` attribute using react. Maybe your'e changing the virtual DOM instead of DOM.  

I use [`theme-change`](https://github.com/saadeghi/theme-change) for my own projects and it works with react too. you might want to take a look at [how it adds the `data-theme` attribute](https://github.com/saadeghi/theme-change/blob/master/src/toggle.js)
and here's an example with react: https://codesandbox.io/s/xenodochial-platform-vhpvo?file=/src/App.js

**Comment by alvaroserrrano** [comment]
Looks like we replied at the same time. Yes, the issue was on my side trying to access localStorage while doing server-side rendering. Thanks!
