### ISSUE TITLE
Content overflow in Model

### ISSUE THREAD

**Issue by Aravin** [saadeghi/daisyui#373]
![image](https://user-images.githubusercontent.com/4869265/147965696-de75a0df-880f-4c03-9952-04f44515b224.png)

Can we implement a feature to auto wrap?

**Comment by NikarashiHatsu** [comment]
I'm assuming your code has the "Bill nos" wrapped in a div or paragraph.
Consider using `break-all` class on the div parent instead of implementing it on the modal.

**Comment by Aravin** [comment]
Yes, its under div > p

It will work by break-all.

**Comment by NikarashiHatsu** [comment]
That's great to hear. So is the issue resolved?
If you want to implement the feature you wanted by default, consider submitting a pull request.

**Comment by Aravin** [comment]
is it? @NikarashiHatsu :)

**Comment by saadeghi** [comment]
As @NikarashiHatsu mentioned, `break-all` will fix.  
But I'm not sure if it's a good decision to add `break-all` to the source code of daisyUI modal. `break-all` might cause ugly result if we use it on a element, unaware of the content: https://play.tailwindcss.com/Apuqxeoi1V

If you need it to break, It's better to use it only for a specific part of your content.
