### ISSUE TITLE
Rating component example

### ISSUE THREAD

**Issue by ctwhome** [saadeghi/daisyui#374]
If only this example helps to implement the stars rating component or get inspired by I found this example. It is not my code.

[https://codepen.io/ashleynolan/pen/MyqrPr](https://codepen.io/ashleynolan/pen/MyqrPr)

![](https://user-images.githubusercontent.com/4195550/148072251-a765cbae-1d70-4f62-aecd-64864bec2ab8.png)

**Comment by saadeghi** [comment]
@ctwhome Thank you.
Here's an example with Tailwind CSS: https://play.tailwindcss.com/uLnmW8WXnh  
I'll be working on a daisyUI version soon.

**Comment by NikarashiHatsu** [comment]
I would like to see this component exists, seems good to have one.

**Comment by ctwhome** [comment]
Thanks for the effort! 🙋

**Comment by Bellzylu** [comment]
Heres my verison: https://github.com/Bellzylu/next-three-tw-daisyui
