### ISSUE TITLE
Suggestion: Make the animation modifiable

### ISSUE THREAD

**Issue by nicerazer** [saadeghi/daisyui#375]
Hi, and good evening. I have a thought for a while, in which daisy ui are able to modify the animations. Like easing, bouncing radius. Maybe more stuff but those two are the only things that I have in mind.

But I if possible can I try to implement it? If yes where do I start? Maybe I'll just give it a go and come back if I fail... Thank you for reading!

**Comment by NikarashiHatsu** [comment]
In the top-level, Tailwind has sets of animation available, and I'm pretty sure you can override those animation simply by putting classes on your component.

For Tailwind's animation, check out their documentation [here](https://tailwindcss.com/docs/animation). Have a great evening.

**Comment by saadeghi** [comment]
@nicerazer there are 2 CSS variables to modify the duration off button animations and input animations (checkbox, toggle, radio)  
https://daisyui.com/docs/add-themes
```css
--animation-btn: 0.25s;     /* bounce animation time for button */
--animation-input: 0.2s;     /* bounce animation time for checkbox, toggle, etc */
```
You can use them in a specific theme config or simply use them in your CSS file.  
You can also use Tailwind's animation utilities or you can write custom animations in your CSS file.
