### ISSUE TITLE
document mistake: responsive buttons not work

### ISSUE THREAD

**Issue by ThaddeusJiang** [saadeghi/daisyui#376]
https://daisyui.com/components/button

current:
![CleanShot 2022-01-05 at 15 16 42@2x](https://user-images.githubusercontent.com/17308201/148169815-db4ca846-8dd7-4807-96e9-2c78060d42c6.jpg)

expected:
![CleanShot 2022-01-05 at 15 17 00@2x](https://user-images.githubusercontent.com/17308201/148169853-b94967eb-1158-4c7a-b6f7-71731cb240cf.jpg)

**Comment by NikarashiHatsu** [comment]
I don't see any problems at all.
The button size is "resized" based on the Tailwind's viewport utility, as seen on the code itself:

```html
<button class="btn btn-square btn-xs md:btn-sm lg:btn-md xl:btn-lg">
```

As you can see, in default, the button size is XS, and gradually increases in size as you increase the viewport.

**Comment by saadeghi** [comment]
Fixed
