### ISSUE TITLE
Navbar demo is not responsive

### ISSUE THREAD

**Issue by shinokada** [saadeghi/daisyui#381]
https://daisyui.com/components/navbar

When I click the three lines to open a nav, it doesn't open.

![image](https://user-images.githubusercontent.com/147320/148325659-ac95a1fe-0930-4670-a216-a7cb202aa5dc.png)

**Comment by NikarashiHatsu** [comment]
The components listed on the documentation are just an example, you have to implement how the Navbar behaves on yourself.
You can whether use Alpine.js, jQuery, or another popular JavaScript library, or maybe make it from scratch.

**Comment by saadeghi** [comment]
As @NikarashiHatsu said, it's a demo for "navbar" and does not include a menu or a dropdown.  
You can use dropdown with [dropdown](https://daisyui.com/components/dropdown/) or [drawer](https://daisyui.com/components/drawer/) or any other elements.  
There's also an example of using navbar+dropdown on [dropdown](https://daisyui.com/components/dropdown/) page
