### ISSUE TITLE
Min-h-[50vh] arbitrary values on min-height not working

### ISSUE THREAD

**Issue by nolafs** [saadeghi/daisyui#387]
What version of Tailwind CSS are you using?

v3.0.12

What build tool (or framework if it abstracts the build tool) are you using?

webpack 5.28.0

What version of Node.js are you using?

v14.0.0

What browser are you using?

N/A

What operating system are you using?

macOS

Describe your issue

It seems vh arbitrary values do not work at all on min-height.

**Comment by saadeghi** [comment]
This is not related to daisyUI... It works however: https://play.tailwindcss.com/FO2gQQzvdH  
I'm not sure about WebPack. Can you share a small repo with me so I can reproduce the issue?

**Comment by nolafs** [comment]
Hi,

Thanks for getting back to me. Yes, standard Tailwindcss is perfectly fine, soon daisyUI is added, it won't work any longer. h-[50vh], works perfectly fine with daisyUI but min-height isn't. 

https://sleepy-keller-131ccf.netlify.app

This is my test theme. I have another look, perhaps my webPack setup is doing something funny.

Cheers
Olaf

**Comment by saadeghi** [comment]
I don't see `min-h-[50vh]` class being styled in your CSS.  

<img width="1503" alt="1" src="https://user-images.githubusercontent.com/7342023/148774905-6a57be15-584e-46c2-ae0f-ad104df3d8aa.png">  

That class name does not exist in your build at all. So please make sure if:
- You're using Tailwind version `3.0` or you're using JIT mode
- Your `purge` or [`content`](https://tailwindcss.com/docs/content-configuration) option on tailwind.config.js is including all your template files (all layouts, pages, components, etc...)

**Comment by nolafs** [comment]
Thanks, me being a complete muppet. Very new to tailwind, I am still trying to get my head around it. The build was not able to find min-h-[50vh] as it is added during hugo build.
