### ISSUE TITLE
Suggestion for groups of buttons + label

### ISSUE THREAD

**Issue by devopg** [saadeghi/daisyui#390]
Suggestion for groups of buttons + label

1) button + label 
![image](https://user-images.githubusercontent.com/61819835/148841413-9ba523a6-47db-4e90-a4d5-b35bf825fcdd.png)

2) button + label with pointer
![image](https://user-images.githubusercontent.com/61819835/148841583-0619888e-13e7-440f-9dd8-0e4b247e1514.png)

**Comment by saadeghi** [comment]
This can be done using [`input-group`](https://daisyui.com/components/form/input) or [`btn-group`](https://daisyui.com/components/button-group) or [an open `tooltip`](https://daisyui.com/components/tooltip)

examples: https://play.tailwindcss.com/PbLWtHn1cE
