### ISSUE TITLE
[Bug]: Can't scroll modal when he has much content.

### ISSUE THREAD

**Issue by LWJerri** [saadeghi/daisyui#391]
If I put in modal dialogue div much content, this goes part up behind the screen and I can't scroll up to see the start.

1) 
![image](https://user-images.githubusercontent.com/50290430/148842803-4d8ce15b-7261-4035-bedd-4a0df5041869.png)
2) 
![image](https://user-images.githubusercontent.com/50290430/148842840-2c90648f-22f3-42d7-9b3a-3afbf57e099b.png)

**Comment by LWJerri** [comment]
Code 

```svelte
<div id="notifications" class="modal overflow-y-auto select-none">
  <div class="modal-box m-5">
    <!-- Dublicate this code many times -->
    <div class="alert alert-info mb-1">
      <div class="flex-1">
        <p>Нет новых уведомлений!</p>
      </div>
    </div>
    <!-- Dublicate this code many times -->

    <div class="modal-action">
      <!-- svelte-ignore a11y-invalid-attribute -->
      <a href="#" class="btn">Закрыть</a>
    </div>
  </div>
</div>

```

Resolve my problem but on the small screen modal moves to the right.

**Comment by saadeghi** [comment]
I wouldn't suggest putting that much content in a modal (bad UX practice)  
However, you can make `modal-box` scrollable by adding `overflow-y-auto max-h-screen`: https://play.tailwindcss.com/EDvwyMxKGF  
Or you can make  the whole modal overlay scrollable by adding `overflow-y-auto` to `modal`: https://play.tailwindcss.com/7ixk4YzSvH
