### ISSUE TITLE
card is not working with fixed top navbar

### ISSUE THREAD

**Issue by froeb** [saadeghi/daisyui#396]
Contrary to some other components like e.g. the hero components, the daisyui caird component will, when the page is scrolled, happily scroll over/above a fixed top navbar with appropriate z-index etc. in the same html page. 

Interesting enough, I do not see in your css code any z-index below 0 or above 100, so it should theoretically not be an issue, but it is.

Also interesting is that the bug does not happen on your https://daisyui.com/components/card website with a home grown fixed topbar (may be an idea for another tailwinds daisyui component? especially if compatible with all your components).

Thanks 
Kai

**Comment by saadeghi** [comment]
Can you share an example code (GitHub repo or Tailwind Play page) with me so I can see the issue?

**Comment by saadeghi** [comment]
I'm closing this for now. Please provide a reproduction page so I can see this issue.
