### ISSUE TITLE
Request for a toggle button or allow images for Checkbox

### ISSUE THREAD

**Issue by littleyellowspider** [saadeghi/daisyui#398]
Hi,

I think DaisyUI is a great project.

Could I please put in an enhancement for a Toggle Button (2 state - on/off) which supports an On state text label or image and an Off state text label or image?

A Toggle Button Group would also be very useful.

Alternatively allow the Checkbox On and Off states to support custom SVG's or images.

Many thanks,

Shaun

**Comment by saadeghi** [comment]
To be clear: does this syntax work for what you described? 
```
<div class="someclass-on">
  <div>icon 1</div>
  <div>icon 2</div>
</div>
```
Only the first icon would be visible.  
and when we add `someclass-off` instead, the first icon hides and the second one gets visible.

Am I right?

**Comment by littleyellowspider** [comment]
Hi Saadeghi,

Perfect, that would definitely work!

Many thanks,

Shaun

**Comment by saadeghi** [comment]
Anyone has a suggestion for a class name?  
I think `swap` would be a good one.  
- `swap` and `swap-on`?
- `swap` and `swap-act`?
- `swap` and `swap-active`?

`toggle` is already used. And `switch` is another name for toggle.

I'm thinking of also adding optional transitions like this: https://codepen.io/saadeghi/pen/JjrzbEP?editors=1100

**Comment by xorik** [comment]
@saadeghi in your demo there is no checkbox input. I was expecting something like that:

```html
<div class="toggle-group">
  <input type="checkbox" class="toggle"/>
  <div class="toggle-on">on label</div>
  <div class="toggle-off">off label</div>
</div>
```

But maybe I'm wrong

**Comment by saadeghi** [comment]
@xorik This could be a thing too. But with some changes:
- I guess the checkbox itself must be invisible. so we can use custom text/icon/button in divs.
- The wrapper should be a label so it toggles the checkbox on click
- And I think `toggle-children` would be a better class name because `toggle-group` sounds like a wrapper for multiple toggles.
```
<label class="toggle-children">
  <input type="checkbox"/>
  <div class="toggle-on">on label</div>
  <div class="toggle-off">off label</div>
</label>
```

**Comment by FireSon** [comment]
Would it be possible to optionally add a picture for the indeterminate state as well? Basically you could than cycle through all the defined 'states' of the checkbox... In which case cycle could also be the name for the class :-)

**Comment by saadeghi** [comment]
@FireSon @xorik @littleyellowspider What do you think of this demo?  
https://play.tailwindcss.com/zULpO587wX

**Comment by saadeghi** [comment]
`swap` added in daisyUI v2.0 🎉  
https://daisyui.com/components/swap

**Comment by littleyellowspider** [comment]
Fantastic job and perfect! I'm going to make use of it immediately.

Many thanks for responding so quickly on this.

**Comment by FireSon** [comment]
Totally agree!! super job and many thanks :-)
