### ISSUE TITLE
accordion-item input:checked~.accordion-body to max-height: 100%

### ISSUE THREAD

**Issue by gjovanov** [saadeghi/daisyui#41]
Hey @saadeghi,
we have noticed that currently the `accordion-body` class has a `max-height: 100vh`. This seems to hide longer content inside the `accordion-body`. How can we override the value to `max-height: 100%`?
```
<style>
.accordion-item input:checked~.accordion-body {
    max-height: 100vh; // CHANGE TO 100%
</style>
```

We have tried to do this by brute force with a custom style="max-height: 100%", but it doesn't seem to have an effect.

Is there an elegant way to overwrite this?

Thanks.

**Comment by gjovanov** [comment]
Actually correction, the brute force with style attribute it does seem to work, but still wondering if there is a more elegant way of overriding it?

**Comment by saadeghi** [comment]
@gjovanov I should probably double check this to be sure, but I think `100vh` makes it possible for the content to open/close with an animation.  
I will test this tomorrow and update this issue.

**Comment by gjovanov** [comment]
hey @saadeghi,
maybe I should give u more context of the issue.

Basically, imagine in a `navbar` having a `dropdown` that looks like this:
```html
<div class="dropdown-content bg-base-100 text-base-content rounded-box lg:w-144 md:w-96 sm:w-72 overflow-y-scroll overflow-x-hide" style="max-height: 540px;">
   <div class="menu"> ...  having two menu items...</div>
   <ul class ="accordion">
      <li class="accordion-item"> 
      <input id="local-instances" type="checkbox"> 
            <label for="local-instances" class="accordion-title">
               <strong>LCL</strong>-<span>Local instances</span>
            </label>
       <div class="accordion-body">
            <ul class="menu">
                 17x menu items 
```

our issue since the `max-height: 540px` and vertical scroll bar is being shown in case of expanded `accordion`, those 17x menu items are not being show... only 4-5 we can see because of `max-height: 100vh`.


For the case when checkbox `local-instances` is checked,  we have set the custom style like this:
```html
<div class="accordion-body" style="max-height: 100%">
``` 
then all 17x menu items are being shown when scrolling the vertical scroll down.


Otherwise, the vertical scrollbar doesn't include all 17x menu items, but only 4-5.


So the question is if there is any elegant way (besides the style attribute) to override the `max-height: 100vh` of the `accordion-body`?

I hope the intention is more clean now.

**Comment by saadeghi** [comment]
@gjovanov  
I understand your point. I don't like limiting the height to `100vh` either but please take a look at this example and see what happens if I use 100% instead of 100vh:  
https://play.tailwindcss.com/92mYS639Dw  

As you can see, the content will lose the smooth animation and it opens instantly. That's the reason I had to use `100vh`.  
I will explore this issue this week to see if I can find a solution so we can have the animation without limiting the height.

**Comment by gjovanov** [comment]
I see the difference @saadeghi ... Anyways, you can keep it with `max-height: 100vh` and in cases like our, where we have large number of items to display, make sense to have an option to override it... Currently we are doing this via: `style="max-height: 100%"` on that element.

But I think generally is the question, how do we override some `css` default props of Daisy UI, for the small minority of cases?

Anyways, this one is not urgent at all there is a workaround.

**Comment by saadeghi** [comment]
@gjovanov Most components have lowest CSS specificity. For example, if you see the style of `.btn` it's like:  
```css
.btn{
  /*style*/
}
.btn-primary{
  /*style*/
}
```
So, when you add a Tailwind utility class, it works:  
```html
<button class="btn bg-red-100">
```
However some components are more interactive. like `accordion` that needs the element style change according to a  sibiling checkbox state:
```css
.accordion-item input:checked+.accordion-title{
}
```

**Comment by saadeghi** [comment]
@motzel `accordion` is now replaced with  new [`collapse`](https://daisyui.com/components/collapse) in version [1.0.0](https://github.com/saadeghi/daisyui/blob/master/CHANGELOG.md) and it's not limited to `100vh`.  
`collapse` works with focus but if you add a checkbox, it works with checkbox [[see examples](https://daisyui.com/components/collapse/)]  
Also there are `collapse-open` and `collapse-close` classes to use with JS

**Comment by gjovanov** [comment]
Hey @saadeghi ,
I have tried the new `collapse` and I confirm, it works fine. We have decided to stick to the checkbox-based state instead of focus-based one, because in our case it's less code and cleaner code to manipulate them programmatically.
Anyways, the new `collapse` works perfectly.
