### ISSUE TITLE
Toggle control has inconsistent style

### ISSUE THREAD

**Issue by JokerMartini** [saadeghi/daisyui#410]
On the website the Toggle icons look like this....
![image](https://user-images.githubusercontent.com/1416749/149775560-7c77740a-9744-4ab9-8310-5ac02ef283e4.png)

but on the github repo screenshot they look like this...

![image](https://user-images.githubusercontent.com/1416749/149775621-d0f121fc-9b0f-49c7-9172-383889f2ea96.png)

I'm trying to make a toggle button look more like the second image, how does one do that? I don't see an example of that on the website page for Toggles. I prefer the look of the pill shape being filled with a color kind of like this (created in tailwind). Side note, great stuff with Daisy UI it's great.

![image](https://user-images.githubusercontent.com/1416749/149775993-430a5ac0-5cf8-453e-82a1-a8088563cd0c.png)

**Comment by saadeghi** [comment]
The screenshot is from an older version of daisyUI. I changed the colors to have more contrast and be more accessible.  

Here's what you're looking for (Tailwind CSS version `3.0` required):  
https://play.tailwindcss.com/uKQyokRMak?file=css
