### ISSUE TITLE
Request for drawer-open class for drawers

### ISSUE THREAD

**Issue by stevorr** [saadeghi/daisyui#414]
This is a request for a "drawer-open" class for the drawer component that allows toggling of the open state with JS/React/Vue/etc, similar to the existing "modal-open" utility class for modals. Thank you!

**Comment by saadeghi** [comment]
`modal` works with CSS `:focus` so there was no way to keep it open other than having a class name for it.  
But `drawer` works with a checkbox and you can control it using JS if you want.  
- Svelte example: https://svelte.dev/repl/25363ca7a2c54b7d856096c983b76d41?version=3.29.7
- Vue example: https://codesandbox.io/s/funny-estrela-kkf02?file=/src/App.vue
