### ISSUE TITLE
somethings are different in different devices

### ISSUE THREAD

**Issue by arasovic** [saadeghi/daisyui#417]
its seems like:
![image](https://user-images.githubusercontent.com/9802740/150370353-443ab15f-1663-4350-8cdb-06b1245b6be4.png)

Operating System | IOS
Screen Size | 4.7"
Screen Resolution | 750×1334
OS Version | 13.5.1

but chrome is showing this:
![image](https://user-images.githubusercontent.com/9802740/150370751-5f14bd24-e208-4fb7-9689-c35ab5d24147.png)

I used to your components in my website, but colors are bugged too in some devices, right?

and one more 
![image](https://user-images.githubusercontent.com/9802740/150371822-f1c2deb5-7cb5-407b-a2ba-aa7268aadd66.png)

Model | SM-A520F
Brand | samsung
Operating System | ANDROID
Screen Size | 5.2"
Screen Resolution | 1080x1920
OS Version | 8.0.0

I found something good, maybe you can debug with this value:
`global.window.devicePixelRatio` 
when this value is `1`, everything is okay, but when it is different (I tried in genymotion, value was 2) everything is blowed up like my answers.
I hope it will be useful. I'm curious about the answer.

there is tailwindplay: https://play.tailwindcss.com/0ucI0g3qJp

you can select like this:
![image](https://user-images.githubusercontent.com/9802740/150428625-91b04586-cdbd-49e7-bbb9-d8041cf5618c.png)

and genymotion screenshots: no background color
![image](https://user-images.githubusercontent.com/9802740/150428676-d9591e22-6963-44a0-8839-63751b2f9864.png)
![image](https://user-images.githubusercontent.com/9802740/150428772-d3caa94f-12de-4b30-8191-c469b3d1572f.png)

device info:
![image](https://user-images.githubusercontent.com/9802740/150429825-0ad12e16-7532-4625-8731-1aabe3fd3304.png)

if you need more info let me know

**Comment by saadeghi** [comment]
I'm not sure what's your expected behavior 🤔  
If the problem is footer overlapping the content, you should remove `h-screen` from `<main>`

**Comment by arasovic** [comment]
Oh okay I got it overlap problem now. I'm really sorry, I'm trying to learn tailwind. ty

Second problem is as i said above, I used daisyui components my personal website and shared my website link to my friends. Some friends said to me "change white background" something like this and I said to them "there is no white background my site, clear cache etc.." and I installed genymotion for try different devices, I saw this white background you can see them above screenshoot.

And my solution is override your css's like this:

 **global.css**

.hero {
  color: white;
  background-color: #2a2e37;
}

.bg-base-200 {
  background-color: #2a2e37;
}

You can close this issue but i think you should know this color issue.

I don't really know on which devices it happens but I guess it depends on the `devicepixelratio `variable

**Comment by saadeghi** [comment]
`devicepixelratio` is about resolution of the display and has nothing to do with colors.   

I guess some of your friends are using light/dark mode so they see things different.  
By default, daisyUI has dark/light themes included (plus many other themes) and daisyUI color adapt the current theme.  
For example, If you use `bg-base-100 text-base-content` and you have light mode on your OS/browser you will see white background and dark text color. If you use dark mode, you will see dark gray background and white text.  
If you use a constant Tailwind CSS color, it won't adapt the theme of course. So using `text-black` will make your text back on both dark/light modes.  

You can opt-out of auto theming by using only one theme ([example](https://daisyui.com/docs/add-themes)) or test your site in dark/light mode to make sure everything looks good: ([how](https://stackoverflow.com/a/59223868))

**Comment by arasovic** [comment]
Oh thank you for your help Pouya!! I missed this: `color adapt the current theme.`  I'm really sorry my awkwardness.
You can close this.
