### ISSUE TITLE
Breaks when used within module

### ISSUE THREAD

**Issue by janat08** [saadeghi/daisyui#418]
if you specify "type": "module",
  "module": "./dist/index.mjs",
  in package.json, and change to tailwind.config.cljs which is required then daisy seems to stop working somewhat.

**Comment by saadeghi** [comment]
I'm using it the same way on [a `"type":"module"` project](https://github.com/manasky/cryptomeme/tree/master/web) and there are no issues.  
Can you create a small repo and share it with me so I can reproduce the issue?

**Comment by janat08** [comment]
Thanks for the example. Gist of it is that it just fails when using import rather than require, as the warning when running jit compilation recommends using imports rather than require.

**Comment by janat08** [comment]
Funny thing, nothing actually works when using imports, so this might be specific to jit or esbuild bundler or something else.
