### ISSUE TITLE
Even after your suggested installation, I am not able to use the Button component ?

### ISSUE THREAD

**Issue by ProPhycient5** [saadeghi/daisyui#421]
After following the given steps in `https://daisyui.com/docs/install`, still I am not see those className based components like Button and all. 
Is there anything, I need to do in order to use those component in my project ???
Please do reply, I really want to use your nice components.

**Comment by saadeghi** [comment]
- Does your Tailwind setup works correctly?  
- Did you you setup Tailwind's `purge` or `content` option correctly to target your template files?
- Are you using a `prefix` option on Tailwind config?
- can you share a GitHub repo so I can see your setup?

**Comment by flip111** [comment]
@ProPhycient5 after normal setup of tailwind and daisyUI according to their documentation you need to generate the css with something like `npx tailwindcss -i ./input.css -o ./output.css --watch`. And make sure to actually use `output.css` in your html file. Then after page reload everything should work.

**Comment by ProPhycient5** [comment]
> * Does your Tailwind setup works correctly?
> * Did you you setup Tailwind's `purge` or `content` option correctly to target your template files?
> * Are you using a `prefix` option on Tailwind config?
> * can you share a GitHub repo so I can see your setup?

**Comment by ProPhycient5** [comment]
> * Does your Tailwind setup works correctly?
> * Did you you setup Tailwind's `purge` or `content` option correctly to target your template files?
> * Are you using a `prefix` option on Tailwind config?
> * can you share a GitHub repo so I can see your setup?

Yes, I have done all the above setup. 
What command do I have to enter ?

**Comment by saadeghi** [comment]
With this config, if your content path is correct and if Tailwind utility classes are working, daisyUI classes should work as well.   
Please share a repo so I can reproduce the issue.

**Comment by ProPhycient5** [comment]
> With this config, if your content path is correct and if Tailwind utility classes are working, daisyUI classes should work as well. Please share a repo so I can reproduce the issue.

sure ,I am sharing with you, just me lil tym, let me create repo and upload that repo.

**Comment by ProPhycient5** [comment]
https://github.com/ProPhycient5/ToDo-List

Here is my repo. 

@saadeghi and  @flip111 Please do check let me know, what's need to be done more.

**Comment by saadeghi** [comment]
Ok, the problem is your `tailwind.config.js` has 2 `plugins`. remove the empty one.  
I haven't notice this at first too 😄

**Comment by ProPhycient5** [comment]
> Ok, the problem is your `tailwind.config.js` has 2 `plugins`. remove the empty one. I haven't notice this at first too 😄

Oh shit. Yeah, I also missed. Thank you, for correcting my mistake.😊🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼🙏🏼
