### ISSUE TITLE
Collapsible open transition

### ISSUE THREAD

**Issue by flip111** [saadeghi/daisyui#426]
The collapsible has a transition set on one of the inner elements `collapse-content`. This effect does not work well for increasing the height of the expandable section. The height of that element is set by it's content + the padding. The effect is only applied to the padding so the content opens fully immediately after which the padding increases a little bit as well. This becomes visible when the transition is slowed down to 2 seconds.

In case the `transition-property` is also set for `max-height` it works a little bit better on expanding. But on collapsing it doesn't look smooth, possibly this happens because the max-height had to come all the way down from `9999px` back to `0` instead of the height of the content.

I'm not sure if this can be solved with CSS alone, i remember in the past i was getting the bounded box in javascript do such things smoothly. It might be possible when max-height would be set to something else ... or maybe just using height instead of max-height. In case it can not be solved in CSS i think it's better to remove the transition on padding, because that little bit of extra vertical movement does not add so much and looks a bit weird now IMO.

**Comment by flip111** [comment]
Seems to be possible to do the transition right with CSS only, i found this codepen https://codepen.io/alligatorio/pen/KKzWqVX

**Comment by flip111** [comment]
Another which seems smooth https://tailwind-elements.com/docs/standard/components/collapse/

**Comment by saadeghi** [comment]
Unfortunately it's not possible to have a CSS transition to `auto` height so the only options would be:
- using JS
- settings a fixed height for content
- using hacky solutions to make it feel like a transition like I did

Thanks for the links but they won't be helpful in this case. One is using JS and the other one has a fixed height.

As far as I know there are no better solution for this so I have to close this issue. I will update it if I find any.  
Feel free to continue the conversation.

**Comment by flip111** [comment]
Might be good to write this in the documentation of the Collapsible component. It's not really obvious on first look.
