### ISSUE TITLE
checkbox check renders strangely

### ISSUE THREAD

**Issue by flip111** [saadeghi/daisyui#427]
I'm using firefox 96.0 on ubuntu 20.04

When i take a screenshot of the documentation of the checkbox https://daisyui.com/components/form/checkbox/ at 100% page zoom. The checkbox check doesn't look so good (see below left side). I also zoomed in with my photo editor to make the problem more clear (see further down). I think the checkbox should look like the one i manually adjusted on the right side.

![Screenshot from 2022-01-23 19-07-27](https://user-images.githubusercontent.com/2244480/150692120-8b115bd6-8566-4c41-88b2-e312bce347f5.png)

![Screenshot from 2022-01-23 19-15-09](https://user-images.githubusercontent.com/2244480/150692137-2e696f2b-87b6-4a3d-812e-3ee058063da8.png)

**Comment by saadeghi** [comment]
It's a problem from Firefox with gradients.  
I think the only option for me would be using SVG instead of gradient.

**Comment by flip111** [comment]
There are also these, arguably they might not give the same desired look https://unicode-table.com/en/sets/check/

**Comment by cwray-tech** [comment]
@flip111 I loaded up my site in Firefox windows and not having this issue. 

Did you happen to make sure you don't have any other checkmark styling set from another UI framework/library? I was using Tailwind forms and had this issue as the checkmark styling from the forms library was also loading for the toggle component. May also have this kind of conflict with the checkmark?

**Comment by flip111** [comment]
Yes i have

package.json
```json
{
  "devDependencies": {
    "tailwindcss": "^3.0.15"
  },
  "dependencies": {
    "@tailwindcss/forms": "^0.4.0",
    "daisyui": "^1.24.0"
  }
}
```

tailwind.config.js
```json
module.exports = {
  content: ["./**/*.html"],
  theme: {
    extend: {},
  },
  plugins: [
    require('daisyui'),
    require('@tailwindcss/forms'),
  ],
}
```

By the way i can not always reproduce this issue. I just opened the page again with the exact same config and it didn't show. Next time it shows i will remove the dependency on forms and see if that makes a difference.

**Comment by cwray-tech** [comment]
@flip111 Yeah I think it is the forms dependency. Btw, the forms dependency also screws with the daisy ui styling of other inputs as well, so I would just remove it and update form inputs... I did that and everything looked a lot more consistent.

**Comment by sshquack** [comment]
I see the same problem on Firefox but not on Safari. Open screenshot in full resolution to see the issue.

![Screenshot 000059@2x](https://user-images.githubusercontent.com/5678459/151422099-a1dbc943-26c0-408a-b39b-d3beede2a827.png)

**Comment by saadeghi** [comment]
Yup. It's just Firefox.

**Comment by devmaslov** [comment]
Same on Google Chrome Version 97.0.4692.99 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/17141793/151721322-a45fbf0c-6354-4e64-876d-052371db4e8a.png)

Simply opened https://daisyui.com/components/form/checkbox/

**Comment by filipot** [comment]
Happens to me on both chromium and firefox on linux (manjaro). Really strange bug

**Comment by saadeghi** [comment]
Fixed

**Comment by filipot** [comment]
@saadeghi Just checked and can confirm that it worked! Amazing work on v2.0!!! It's always fun to check on the changes that you have done! I'm so in love with daisy

**Comment by saadeghi** [comment]
@flip111 https://daisyui.com/docs/changelog/
