### ISSUE TITLE
The tooltip element will be at the bottom

### ISSUE THREAD

**Issue by kai0310** [saadeghi/daisyui#430]
When I place a tooltip under a table or other content with a fixed height, the tooltip element is hidden and I cannot see it. z-index and other methods I have used on the element have not helped. Is there any solution to this?
<img width="208" alt="スクリーンショット 2022-01-25 15 59 36" src="https://user-images.githubusercontent.com/52205108/150927266-62eb34fa-4ea2-45e1-81a5-b7e5d607dd87.png">

**Comment by saadeghi** [comment]
If there is a wrapper with `overflow-x-auto` class, that will cause the tooltip (or any overflow content) to get cropped.  
example: https://play.tailwindcss.com/aA8GvM3nFW

- You can remove the `overflow-x-auto` class
- or you can add some margin/padding to the table so the tooltip get enough space
- or you can change the direction of tooltip using `tooltip-bottom`, `tooltip-left`, etc...

**Comment by kai0310** [comment]
Thanks a lot ✨
