### ISSUE TITLE
Scroll to Top does not work in drawer-content

### ISSUE THREAD

**Issue by sshquack** [saadeghi/daisyui#431]
Thank you for this fantastic project! 🙇 

I'm using the drawer component in my app and the `window.scrollTo(0,0)` for scrolling to top of the page appears broken. This problem happens on both Chrome and Firefox. This works on a vanilla Tailwind app without DaisyUI. Please see screen recording for repro:

https://user-images.githubusercontent.com/5678459/151268147-77e99ec0-e1f3-49d1-a509-503cf253fce0.mp4

**Comment by saadeghi** [comment]
See this issue #333

**Comment by sshquack** [comment]
Thanks @saadeghi Using `document.querySelector('.drawer-content').scrollTo({ top: 0 })` worked!
