### ISSUE TITLE
Swipe to navigate does not work in drawer-content

### ISSUE THREAD

**Issue by sshquack** [saadeghi/daisyui#432]
Hi,

When using the mac trackpad for "Swipe to go back or forward" with drawer-content, it only works on "drawer-side" but it does not work on "drawer-content". This problem happens on both Chrome and Firefox. I have verified that this works on vanilla tailwind. Please see attached video (I'm swiping inside the drawer-content but the screen recording could not capture the swipe gesture in the video)

https://user-images.githubusercontent.com/5678459/151268681-e6759515-ecac-4c13-86c9-6fa6e2520c45.mp4

**Comment by saadeghi** [comment]
Adding `overscroll-auto` to `drawer-content` will make it work. I will fix it soon.

**Comment by sshquack** [comment]
Amazing -- Thank you @saadeghi 🙏
