### ISSUE TITLE
[Feature Request] Switch component

### ISSUE THREAD

**Issue by asportnoy** [saadeghi/daisyui#433]
Basically a checkbox but styled to look like a switch.

<img width="102" alt="Screenshot on 2022-01-26 at 22 16 02" src="https://user-images.githubusercontent.com/14863373/151290977-a6ef5e8e-fa39-4edc-85ae-b6088ff2f240.png">

**Comment by saadeghi** [comment]
https://daisyui.com/components/form/toggle

**Comment by asportnoy** [comment]
🤦‍♂️ I'm blind apparently. Thank you!
