### ISSUE TITLE
Table on mobile with overflow

### ISSUE THREAD

**Issue by gerciljunio** [saadeghi/daisyui#434]
On mobile the table when responsive the "thead" does not work as it should, the first column is fixed and does not follow the scroll showing the other columns.

I tested it on Chrome, Safari, Edge and Firefox, I don't know if I'm doing something wrong or if it's a bug.

Reproduction:
https://media.giphy.com/media/DJPgtuRty2vW2F6yxV/giphy.gif

**Comment by saadeghi** [comment]
@gerciljunio Please provide a code sample so I can reproduce the issue

**Comment by gerciljunio** [comment]
code (those v-html tags and the like is from Vuejs):

```html
<div class="overflow-x-auto">
    <table class="table w-full table-zebra">
        <thead>
            <tr>
                <th>Repository</th>
                <th>Author</th>
                <th>Visibility</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr v-for="(item, index) in data">
                <td>{{ item.title }}</td>
                <td>{{ item.author }}</td>
                <td v-html="item.private ? 'Private' : 'Public'"></td>
                <td><button @click="open(item.url, item.private)" class="btn btn-xs btn-success">Open</button></td>
            </tr>
        </tbody>
    </table>
</div>
```

**Comment by gerciljunio** [comment]
@saadeghi I just tested the examples on mobile at https://daisyui.com/components/table and the same thing happens.

**Comment by saadeghi** [comment]
This is intentional and it makes the first column accessible on mobile viewpoint. something [like this](https://coinmarketcap.com/)
You should use `<th>` for the first column. This makes the first column sticky (including the header and content)  

```html
<tr v-for="(item, index) in data">
    <th>{{ item.title }}</th>
    <td>{{ item.author }}</td>
    <td v-html="item.private ? 'Private' : 'Public'"></td>
    <td><button @click="open(item.url, item.private)" class="btn btn-xs btn-success">Open</button></td>
</tr>
```

**Comment by saadeghi** [comment]
![1716668-675d219a70280bf2cbebe1cdb87aba91](https://user-images.githubusercontent.com/7342023/151372149-44c7f39d-df15-4c7b-b52b-4fed238124c4.gif)

**Comment by gerciljunio** [comment]
hahahaha cool, thanks for the explanation! congratulations for the work!
