### ISSUE TITLE
I cannot get the daisyUI theme to work in my tailwind config

### ISSUE THREAD

**Issue by lindamacdonald** [saadeghi/daisyui#439]
Hey there guys, gone through your docs for adding the daisyui them to my next.js project. tried adding it to my tailwind config but it doesnt work any idea would be lovely :) tried adding it to extend: {} which seemed logical to me but that throws  an error

module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [

    require('daisyui')
  ],
}

**Comment by saadeghi** [comment]
Config is correct and it should work.   
Can you share a small repo so I can reproduce the issue?

**Comment by lindamacdonald** [comment]
Just testing on my mobile because i wasnt allowed to answer this thread Yesterday might be my browser 😆 but sure i Will share my repo🙂

**Comment by lindamacdonald** [comment]
ah yes it was my browser playing tricks on me yesterday, so sorry for the other thread, but it kept telling me I couldnt comment on this thread :/  so I have resolved the issue. I placed the daisy theme within the theme section of my Tailwind config. Found a good explanation on youtube and this is the correct way of adding it to my tailwind config for next.js:

module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes:[
      "dark"
    ]
  }
}

**Comment by saadeghi** [comment]
I'm glad it's fixed 👍
