### ISSUE TITLE
`stat` containers do not change border using break points

### ISSUE THREAD

**Issue by veado** [saadeghi/daisyui#440]
While using breakpoints, definition in `.stats.grid-flow-row` is still active, even by overriding it back to `grid-flow-col `. That's border won't change.

### Example

In following example, content of `Current block` and `Churn block` are `stat`. Border keeps at the top position in `Churn block`  while changing screen sizes

https://user-images.githubusercontent.com/61792675/151838762-37bd0599-b1ba-4941-8eab-447db685437a.mp4

```html
<div class="grid-flow-row sm:grid-flow-col shadow stats">
   <div class="stat">
            <div class="stat-figure">
              <Icon src={Cube} size="48" class="outline-none" />
            </div>
            <div class="stat-title">Current block</div>
             ...
    </div>
   <div class="stat">
            <div class="stat-figure">
              <Icon src={Tag} size="48" class="outline-none" />
            </div>
            <div class="stat-title">Churn block</div>
            ...
    </div>
 </div>
```

## Possible fix
 Add a definition for `.stats.grid-flow-column` in https://github.com/saadeghi/daisyui/blob/master/src/components/styled/stat.css

```css
.stats.grid-flow-row{
  .stat+.stat{
    @apply border-l-0 border-t;
  }
}
.stats.grid-flow-column{
  .stat+.stat{
    @apply border-l border-t-0;
  }
}
```

**Comment by saadeghi** [comment]
New responsive modifier classes added in daisyUI v2.0:  
```
stats-horizontal
stats-vertical
```
https://daisyui.com/components/stat

**Comment by veado** [comment]
Thanks @saadeghi !
