### ISSUE TITLE
How to add icon (svg/png) in step component

### ISSUE THREAD

**Issue by aprilahijriyan** [saadeghi/daisyui#442]
Hi, thanks in advance for providing a list of components with `tailwindcss` this was very helpful :).

I want to ask is it possible to add an icon (svg/png) to a `step` component? I'm using daisyUI with vuejs here.

Thank you.

**Comment by aprilahijriyan** [comment]
Finally, thank you. Maybe it's better if it's documented?

**Comment by saadeghi** [comment]
I'm not sure if it should be on the docs...  
It's an additional CSS style, not a feature from daisyUI.  
many customizations are possible with CSS but I can't document them all 😄
