### ISSUE TITLE
steps component not following tailwind prefix

### ISSUE THREAD

**Issue by shahraship** [saadeghi/daisyui#449]
My tailwind config contains a prefix property like this:
`prefix: 'tw-'`
The following highlighted css breaks because when it's used by tailwind it fails to convert the class with prefix.
https://github.com/saadeghi/daisyui/blob/master/src/components/styled/steps.css#L4

```
<ul class="tw-steps tw-w-full">
  <li class="step tw-step-primary">Test 1</li>  <-- We should be able to use tw-step here.
  <li class="step tw-step-primary">Test 2</li>
  <li class="step tw-step-primary">Test 3</li>
</ul>
```

**Comment by saadeghi** [comment]
Fixed in v2.0  
https://play.tailwindcss.com/IFdiVRSNqD
