### ISSUE TITLE
Add datepicker component

### ISSUE THREAD

**Issue by zemian** [saadeghi/daisyui#45]
Two of the common usecases are single date selection and a date range selection.

**Comment by saadeghi** [comment]
I'm planning to a add a `calendar` component however it will be just a *visual* calendar (not a fully functional date picker that works with JS). I'm afraid it's not possible to make a functional `datepicker` component using only CSS. Daisy UI is a CSS library and has no JS dependency.  
Also, unlike old days, I think using browser's native date picker makes more sense.
