### ISSUE TITLE
Document's "Mockup-Window" and "Mockup-Phone" html indentation is weird.

### ISSUE THREAD

**Issue by hmu332233** [saadeghi/daisyui#450]
Thank you for making great components!
I was looking at the documents, but some of them were not properly indented, so I left an issue.

- https://daisyui.com/components/mockup/window
- https://daisyui.com/components/mockup/phone

Browser: Chrome

![image](https://user-images.githubusercontent.com/10302969/152808367-0420ed01-ab51-41e3-adeb-49ac9f3c745f.png)

**Comment by saadeghi** [comment]
Fixed
