### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by georgebrianb** [saadeghi/daisyui#454]
I am pretty new to web development, but I can usually follow good documentation with no issues. However, the documentation for the framework lacks important imformation.

For example, I cannot find a way to actually combine a navbar with a drawer. I want to be able to have a button that extends a drawer with menu options. I want the navbar to show the button only when the screen is small. So far all I could do is show the button when that happens, but I could not add a drawer. I did not understand why/when/where do I have to put the "input" element to make the button active. 

As a beginner, documentation is the first thing I look at when I start a new framework. And if you could improve it, or at least have a community place (discord, telegram, slack..) where beginners could ask for help, that would be awesome.

**Comment by saadeghi** [comment]
I'm currently working on the new document website and it will be ready soon.  
There will be many more examples, including examples of how to use components together.  

Also there is GitHub Discussions if you have any questions:  
https://github.com/saadeghi/daisyui/discussions

About drawer:  
See this example: https://play.tailwindcss.com/Git3JSot0T?size=800x550  
Drawer is a grid layout with the following structure:
```c
drawer
- drawer-toggle // the checkbox that controls drawer open/close
- drawer-content // page content
  - navbar (optional)
  - //any page content
- drawer-side // the sidebar
  - drawer-overlay // the gray overlay
  - // sidebar content (menu or anything)
```
The checkbox is the native HTML element that allows us to style elements differently when it's checked or not. So when checkbox is checked, the drawer will be open. When checkbox is not checked, drawer will be closed.  
However, we don't want to show a checkbox to the user. We want to open/close the drawer using buttons. So the checkbox is hidden and we control it using `<label>` element which is the native HTML element that can control an input.  
So whenever we want to click something to open/close the drawer, it should be `<label>`. Thanks to CSS, we can make the label look like a button. So in [line 7](https://play.tailwindcss.com/Git3JSot0T?size=800x550) we have a label with a button style and a SVG hamburger icon inside. Clicking it will open the drawer.  
Also in line 31 there's another label which is styled as a overlay to cover the screen. When drawer is open and we click outside to close the drawer, we're actually clicking on this label.

How can the label control the checkbox?  
By pointing its ID. In the example I linked above, you can sell that the ID is `my-drawer-3` and all labels are referring to it `<label for="my-drawer-3">`

Please let me know how it goes and tell me if I you need more examples or answers.

**Comment by georgebrianb** [comment]
And is there a way to have a drawer on top of a hero without adding javascript?

**Comment by saadeghi** [comment]
When drawer is open, everything inside `drawer-content` will be covered. So you should put all page content inside `drawer-content` (after `navbar`) unless you don't want the drawer overlay to cover it.  

Examples:
- navbar, hero and footer inside `drawer-content`: https://play.tailwindcss.com/TCtR7y9Qlm  
- footer outside `drawer`: https://play.tailwindcss.com/18DVCiuLMK 
- sticky `navbar`: https://play.tailwindcss.com/VDN4eE9SWi

Let me know if you need more examples:

**Comment by georgebrianb** [comment]
Thanks a lot @saadeghi, I chose daisyUI for it's awesome components, but implementing has been a pain. I will go over your explanations and will try to work on that. I will also try to contribute to the docs when I get to a better understanding.

**Comment by saadeghi** [comment]
Thank.

Feel free to ask for help. I'd be glad to help.

But don't send pull request for docs yet, because I'm rewriting the whole website and the new version will be ready this month.
