### ISSUE TITLE
Outlined state buttons close to invisible with light themes

### ISSUE THREAD

**Issue by luhagel** [saadeghi/daisyui#455]
With the lighter state colors of 2.0, outlined state buttons have become close to invisible on light backgrounds.
<img width="1011" alt="Screenshot 2022-02-15 at 00 30 56" src="https://user-images.githubusercontent.com/7240688/153964621-c5e6af70-e568-432c-8115-e7f6202bc076.png">

**Comment by saadeghi** [comment]
Fixed.  
Thanks
