### ISSUE TITLE
Where is the Multi-level Menu?

### ISSUE THREAD

**Issue by NikarashiHatsu** [saadeghi/daisyui#458]
Hi, I'm looking for the documented multi-level menu.
I couldn't find it on 2.0.2, I used this component a lot in 1.19.0.
Is there any new documentation regarding this component?

This is the screenshot from a project that has 1.19.0 inside.
<img width="292" alt="Screen Shot 2022-02-15 at 13 41 15" src="https://user-images.githubusercontent.com/43662951/154006777-8cd98f34-b0e3-4707-9274-291ed4062873.png">

I can't achieve it in the newest 2.0.2 despite using the same syntax as before.
<img width="298" alt="Screen Shot 2022-02-15 at 13 42 38" src="https://user-images.githubusercontent.com/43662951/154006940-3805c07f-aa14-418b-9c40-ae84ff2981c8.png">
<img width="944" alt="Screen Shot 2022-02-15 at 13 43 10" src="https://user-images.githubusercontent.com/43662951/154007001-e039aa36-f0bb-4ab8-978d-6eb7eee3a764.png">

Any help is appreciated.

Edit: The Menu component is inside a drawer. The "Submenu" component is not something I tried to achieve.

**Comment by NikarashiHatsu** [comment]
An update to the issue, I managed to create a workaround.
Structurally, it is painful to see a `<ul>` inside a `<ul>`.
But here's how I did.

```html
<ul class="menu p-4">
    <li>
        <a href="javascript:void(0)">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
            </svg>
            <span>
                Dashboard
            </span>
        </a>
    </li>
    <ul x-data='{ open: false }'>
        <li>
            <a href="javascript:void(0)" x-on:click="open = !open">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                <span class="w-full flex items-center justify-between">
                    <span>
                        Dropdown Example
                    </span>
                    <span class="transition-transform duration-300 ease-in-out" x-bind:class="open ? 'rotate-90' : 'rotate-0'">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                        </svg>
                    </span>
                </span>
            </a>
        </li>
        <ul class="ml-7" x-show="open" x-transition>
            <li>
                <a href="javascript:void(0)">
                    Dropdown 1
                </a>
            </li>
            <li>
                <a href="javascript:void(0)">
                    Dropdown 2
                </a>
            </li>
            <li>
                <a href="javascript:void(0)">
                    Dropdown 3
                </a>
            </li>
        </ul>
    </ul>
</ul>
```

I'm keeping this issue open until I got some news from the dev team.
Cheers!

**Comment by saadeghi** [comment]
See nested examples here:  
https://daisyui.com/components/menu#a-lot-of-submenus  

The first level  of nested `<ul>` will [open as a dropdown](https://codepen.io/saadeghi/pen/WNXZYrz?editors=1100). Second level and more will show up like a cascade (because more than 2 level of dropdown is not accessible and it's hard to use)  

If you don't want a floating dropdown and want it work like your screenshot, you just need to put the nested `<ul>` inside a `<div>`:  
https://codepen.io/saadeghi/pen/QWOqJEx?editors=1000 (Line 30)

**Comment by young-altair** [comment]
What about Collapse [https://daisyui.com/components/collapse/](DaisyUI Collapse) as sub menu?
I mean, to get the autoclose function when clicked outside the container.
https://codepen.io/altairzeheb/pen/vYjbNQz
