### ISSUE TITLE
Form input with button is not single line on a mobile

### ISSUE THREAD

**Issue by zemian** [saadeghi/daisyui#46]
When viewing https://daisyui.com/components/form/input on a real iPhone XR, the "connected" example of input with button has the button wrapped in new line below the input (Not together in a single line). However the one "with space" looks fine on the same iPhone (it's one line).

NOTE: When I view the page in Firefox Devtool with Responsive Mode, and then select iPhone X, the form UI has no issue! Only on a real iPhone I see the problem.

**Comment by saadeghi** [comment]
Thanks  
Looks like the width is too much. I'll fix that.
