### ISSUE TITLE
Peer dependencies not fully specified

### ISSUE THREAD

**Issue by JamesYeoman** [saadeghi/daisyui#462]
After upgrading to DaisyUI V2, I got this message from Yarn
![image](https://user-images.githubusercontent.com/21042602/154077650-9ee020d0-e792-4507-bb95-c7bd7b1e5a12.png)

The reason that this is an issue is because it violates Yarn's hoisting behaviour. [Yarn documentation on missing transitive peer dependencies](https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency) and [blog post that the documentation references](https://dev.to/arcanis/implicit-transitive-peer-dependencies-ed0)

**Comment by JamesYeoman** [comment]
Yes, if you don't provide resolution for the dependencies yourself (which for autoprefixer, is certainly the case)

**Comment by saadeghi** [comment]
@JamesYeoman Please install daisyui version `2.0.7` and check if this fixes the issue

**Comment by JamesYeoman** [comment]
Yep, no more peer dependency message. Thanks a lot for taking the time to address it
