### ISSUE TITLE
Unable to find loader/spinner in new version.

### ISSUE THREAD

**Issue by rehmankhan-cloudways** [saadeghi/daisyui#463]
I've gone through new component API and it's great, but it's missing spinner component. 

https://daisyui.com/components

**Comment by saadeghi** [comment]
It was never a separate component. It's a modifier class for button:  
https://daisyui.com/components/button#button-with-loading-spinner
```html
<button class="btn loading">loading</button>
```
And because Tailwind has [a utility class for spin animation](https://tailwindcss.com/docs/animation#spin), I don't think there's a need for another class name.

**Comment by jptrsn** [comment]
Is this documentation incorrect?

https://daisyui.com/components/loading/
