### ISSUE TITLE
Accordion examples doesn't work?

### ISSUE THREAD

**Issue by zemian** [saadeghi/daisyui#47]
Are these examples in https://daisyui.com/components/accordion/ suppose to expand when clicked? It's not working for me.

**Comment by motzel** [comment]
It looks like it doesn't work on Android Edge. Works great on Chrome though.

**Comment by saadeghi** [comment]
@motzel `accordion` is now replaced with  new [`collapse`](https://daisyui.com/components/collapse) in version [1.0.0](https://github.com/saadeghi/daisyui/blob/master/CHANGELOG.md) and that bug is gone.
