### ISSUE TITLE
globals.css Variant cannot be generated because selector contains no classes.

### ISSUE THREAD

**Issue by PixelPage-YT** [saadeghi/daisyui#474]
Hello, 
i get this error
/Users/kloetzchengrafik/Documents/Stade/renderer/styles/globals.css Variant cannot be generated because selector contains no classes.

I added daisyui using yarn add daisyui.
Tailwind config:
module.exports = {
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      boxShadow: {
        "lg": "0 10px 15px -3px #F1E0AC, 0 4px 6px -4px #F1E0AC"
      }
    },
  },
  variants: {
    extend: {},
  },
  plugins: [require("daisyui")],
};

(I'm using nextjs with typescript)

**Comment by saadeghi** [comment]
@PixelPage-YT Can you provide a small repo so I can reproduce this issue?

**Comment by PixelPage-YT** [comment]
Sure!
https://github.com/PixelPage-YT/daisyui-error

**Comment by saadeghi** [comment]
Updating to Tailwind CSS 3.0 will fix the error. however, your app doesn't seem to generate styles when I install Tailwind CSS 3.0  
I'm not sure which package is no compatible but If you want to use Tailwind CSS 2.x, use daisyui 1.x with it.
