### ISSUE TITLE
Incorrect color of badge-error class

### ISSUE THREAD

**Issue by AdiletBekmuratov** [saadeghi/daisyui#475]
I recently updated to the latest version and noticed that "badge-error" has an incorrect color and it currently behaves like "badge-ghost".

My current version of daisy UI is 2.0.8

**Comment by saadeghi** [comment]
Color depends on the theme. Which theme are you using? Can you attach a screenshot?

**Comment by AdiletBekmuratov** [comment]
Yes, sure. I'm using `darkMode: 'media'` in tailwind config. Daisyui uses darkmode. But if I change badge class for `badge-warning`, it displays color correctly (Screenshot_2). 
Screenshot_1:
![image](https://user-images.githubusercontent.com/69452047/154626999-eb78a95f-aeac-4396-ad23-3e1760324ee3.png)

Screenshot_2:
![image](https://user-images.githubusercontent.com/69452047/154627341-3b871ae8-814b-44ee-8b9b-455727c66fa3.png)

**Comment by saadeghi** [comment]
@AdiletBekmuratov That's not okay. Here you can see daisyUI `light` and `dark` themes using `badge-ghost`, `badge-warning` and `badge-error` and they all look okay:  
https://play.tailwindcss.com/dja1Xew2Yd  

https://user-images.githubusercontent.com/7342023/154656483-83fa6762-5dfe-4e76-9fb8-3ecb75cbaee9.mp4

Are you sure you're not using a [custom theme](https://daisyui.com/docs/themes/) or any other CSS is not affecting the style?  
This should be the style you see on devtools:  

<img width="857" alt="Screen Shot 2022-02-18 at 12 36 19 PM" src="https://user-images.githubusercontent.com/7342023/154656961-8ca7c917-7063-4b76-8c6f-5bd72ba607a7.png">

**Comment by AdiletBekmuratov** [comment]
Sorry for interrupting you, I tried in another project and it worked perfectly
