### ISSUE TITLE
Components Overlapping.

### ISSUE THREAD

**Issue by itzmegood** [saadeghi/daisyui#478]
When using tooltip or dropdown with `Drawer for mobile + fixed sidebar for desktop`, the components tend to cut off when we lessen the width of the drawer

Can there be solution that they appear on top of the screen disregarding the width.

Trying to make this kinda dashboard 

![Screenshot_20220218-091543](https://user-images.githubusercontent.com/35160768/154613734-e40ead46-231f-4635-b27c-67234c04ee92.jpg)

So in this scenario you can see that there are only icons on the sidenav and when u hover it should show tooltip but because the width is less they get cut off.

**Comment by saadeghi** [comment]
It's a trade off.  
You can do this by adding `!overflow-y-visible` to `drawer-side` but this way content can't be scrollable 
https://play.tailwindcss.com/zNZZO2teKl  
> In CSS when we use `overflow-y: auto` on an element, it will crop the horizontal overflow but I had to add it people usually want scrollable content on sidebar.

**Comment by chargome** [comment]
Is there any other way to have items in the drawer-side that overflow horizontally?

**Comment by saadeghi** [comment]
@chargome Not as far as I know. If anyone found a way, I would appreciate if you share it here so others can use it too.
