### ISSUE TITLE
DaisyUI 2.0.9 --> Cannot find module 'daisyui/colors/themes'

### ISSUE THREAD

**Issue by cer1969** [saadeghi/daisyui#479]
I updated from version 2.0.2 to 2.0.9 and got this error:
Cannot find module 'daisyui/colors/themes'

I reverted back to 2.0.2 and works ok.

DaisyUI 2.0.9 on Windows 11
Tailwindcss 3.0.23

**Comment by saadeghi** [comment]
@cer1969 There's been a small change in file structure.  

Where ever you're importing themes:
```diff
# change this
- daisyui/colors/themes

# to this
+ daisyui/src/colors/themes
