### ISSUE TITLE
the css style of `input` is not corret

### ISSUE THREAD

**Issue by cctor** [saadeghi/daisyui#480]
**Problem**
`input`'s css style not corret
**Describe**
the underline character `_` is not seenable
**Example**
example from the [official doc](https://daisyui.com/components/input/) when typed `hello_world`
![image](https://user-images.githubusercontent.com/58580492/154659071-39b6b6c4-d0c8-43fa-9643-a19979e12c86.png)

**Comment by saadeghi** [comment]
@cctor what browser are you using?

**Comment by cctor** [comment]
> @cctor what browser are you using?

sorry, that may be caused by my computer settings. I checked it on another computer, and it works well.

thanks anyway.
