### ISSUE TITLE
Drawer Open-Close (like drawer-mobile) based on swap button

### ISSUE THREAD

**Issue by FireSon** [saadeghi/daisyui#481]
Hi Pouya,

The automatic hiding of the drawer with the drawer-mobile class is very helpful. Would it be possible to extend that functionality so that the drawer would be hidden with the use of a swat button in other breakpoints? 
That would mean that the existing functionality of the drawer-mobile would remain the same, but in the 'larger' breakpoints the drawer would be hidden if the checked property of the drawer-toggle is false and visible if it is true... 

Thanks!

**Comment by saadeghi** [comment]
So you want responsive classes to control the visibility of drawer on each screen size. Something like:
```html
<div class="drawer md:drawer-visible lg:drawer-hidden xl:drawer-visible">
```
- hidden on `sm`
- it's fixed on `md`
- it's hidden again on `lg`
- it's fixed on `xl`

Am I right?

**Comment by FireSon** [comment]
No not quite... The drawer should be hidden on `sm` and 'toggled' visible/invisible by a button on `md` `lg` and `xl` (hence the swap button)

**Comment by saadeghi** [comment]
So you don't want the drawer on `sm` at all?  
you can just hide the button on `sm` then:  
https://play.tailwindcss.com/jjR8zljNDk?size=1222x543

**Comment by FireSon** [comment]
Sorry for being unclear I tried to create an example [https://play.tailwindcss.com/CsjGJOU9XK?size=1106x543](url)

Basically everything works fine in the example except that when the drawer-side is visible, the swap button should be able to toggle the visibility of the drawer.

**Comment by FireSon** [comment]
I modified your Svelte code to do what I wanted, but I could not save it so I just paste it here:
The trick is done by the  hidden={!isDrawerOpen} attribute on the line: `<div class="drawer drawer-mobile w-full h-full" hidden={!isDrawerOpen}>` then the example does exactly what I wanted. 


`<script>
	//  🔵	initial value of drawer
	let isDrawerOpen = false;
</script>

<svelte:head>
	<link href="https://cdn.jsdelivr.net/npm/daisyui@2/dist/full.css" rel="stylesheet" type="text/css" />
	<script src="https://cdn.tailwindcss.com"></script>
</svelte:head>

<div class="h-screen w-full flex flex-col">

  <div class="w-full navbar bg-base-300 gap-2">
    <div class="flex-none">
			
      <label for="my-drawer-3" class:swap-active={isDrawerOpen} class="btn btn-circle swap swap-rotate">
        <svg class="swap-off fill-current" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 512 512"><path d="M64,384H448V341.33H64Zm0-106.67H448V234.67H64ZM64,128v42.67H448V128Z"/></svg>
        <svg class="swap-on fill-current" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 512 512"><polygon points="400 145.49 366.51 112 256 222.51 145.49 112 112 145.49 222.51 256 112 366.51 145.49 400 256 289.49 366.51 400 400 366.51 289.49 256 400 145.49"/></svg>
      </label>
    </div> 
    <span>isDrawerOpen = {isDrawerOpen}</span>
  </div> 

  <div class="drawer drawer-mobile w-full h-full" hidden={!isDrawerOpen}>
		
    <input id="my-drawer-3" type="checkbox" bind:checked={isDrawerOpen} class="drawer-toggle"> 
    <div class="flex flex-col items-center justify-center drawer-content">
      Content
    </div> 
    <div class="drawer-side">
      <label for="my-drawer-3" class="drawer-overlay"></label> 
      <ul class="p-4 overflow-y-auto menu w-80 bg-base-200">
        
        <li><span>Sidebar Item 1</span></li>
        <li><span>Sidebar Item 2</span></li>
      </ul>
    </div>
  </div>
</div>`

**Comment by FireSon** [comment]
In order to show what I mean, I modified your example to do what I want. Since I do not know how to save your Svelte example I just past the code below. 

`
<script>
	//  🔵	initial value of drawer
	let isDrawerOpen = false;
</script>

<svelte:head>
	<link href="https://cdn.jsdelivr.net/npm/daisyui@2/dist/full.css" rel="stylesheet" type="text/css" />
	<script src="https://cdn.tailwindcss.com"></script>
</svelte:head>

<div class="h-screen w-full flex flex-col">

  <div class="w-full navbar bg-base-300 gap-2">
    <div class="flex-none">
			
      <label for="my-drawer-3" class:swap-active={isDrawerOpen} class="btn btn-circle swap swap-rotate">
        <svg class="swap-off fill-current" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 512 512"><path d="M64,384H448V341.33H64Zm0-106.67H448V234.67H64ZM64,128v42.67H448V128Z"/></svg>
        <svg class="swap-on fill-current" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 512 512"><polygon points="400 145.49 366.51 112 256 222.51 145.49 112 112 145.49 222.51 256 112 366.51 145.49 400 256 289.49 366.51 400 400 366.51 289.49 256 400 145.49"/></svg>
      </label>
    </div> 
    <span>isDrawerOpen = {isDrawerOpen}</span>
  </div> 

  <div class="drawer drawer-mobile w-full h-full">
		
    <input id="my-drawer-3" type="checkbox" bind:checked={isDrawerOpen} class="drawer-toggle"> 
    <div class="flex flex-col items-center justify-center drawer-content">
      Content
    </div> 
    <div class="drawer-side">
      <label for="my-drawer-3" class="drawer-overlay"></label> 
      <ul class="p-4 overflow-y-auto menu w-80 bg-base-200" hidden={!isDrawerOpen}>
        
        <li><span>Sidebar Item 1</span></li>
        <li><span>Sidebar Item 2</span></li>
      </ul>
		</div>
  </div>
</div>`
