### ISSUE TITLE
[Question] Is there a way to extend or customize the ui from config?

### ISSUE THREAD

**Issue by vineryap** [saadeghi/daisyui#482]
Hi, let's say I want to make the `btn` class not too round.
I know I can do it by adding `rounded` or anything to override the default value, but I have to repeat this step every time I add a button.
I can't find any guide on the docs, so maybe this feature is not available?

**Comment by saadeghi** [comment]
I'm improving that part of docs.  
There are 3 ways:
- Using utility classes on each button (as you mentioned)
- Apply CSS to all `btn`s: https://play.tailwindcss.com/f6OJRDCWM7?file=css
- Extending a theme and change `--rounded-btn` CSS variable: https://play.tailwindcss.com/SHUzujnDWq?file=config
