### ISSUE TITLE
Question regarding Carousel component .

### ISSUE THREAD

**Issue by ProPhycient5** [saadeghi/daisyui#488]
Is there any way to get a carousel component having both indicator buttons and next/prev buttons?

<img width="537" alt="carsoul" src="https://user-images.githubusercontent.com/71059909/154800821-9e5a92b7-7739-4217-b190-706695972053.PNG">
Like in pic, you can see above Carousel has both indicator and next/prev buttons. 

Or can we merge both code for  `Carousel with indicator buttons` and `Carousel with next/prev buttons` ?????

**Comment by saadeghi** [comment]
Don't expect much from a CSS-only slider but here's an example:  
https://codepen.io/saadeghi/pen/zYPWGOq?editors=1000

**Comment by ProPhycient5** [comment]
Got it. Thank you for the help.
