### ISSUE TITLE
input-error on some themes doesn't look like a error

### ISSUE THREAD

**Issue by Siumauricio** [saadeghi/daisyui#492]
Hello, before the update the input error was showing the color red, but after appear like a low pink or something I attach an image, in another themes don't happen that

Dark theme
![image](https://user-images.githubusercontent.com/47042324/154825534-236b5dc7-b342-49a6-9edf-7da427c646aa.png)

in Bumblebee theme 
![image](https://user-images.githubusercontent.com/47042324/154825559-66fa5f0c-17ed-4806-b289-9cb007c1f2b4.png)

this happens in some themes like light, dark,Halloween and more..

**Comment by wuarmin** [comment]
Hey,
I have the same issue after update. The faulty inputs are almost invisible.

**Comment by saadeghi** [comment]
This will be fixed today

**Comment by saadeghi** [comment]
Fixed in `2.2.0`

**Comment by wuarmin** [comment]
Thank you for your great work!
