### ISSUE TITLE
Navigation Drawer/Sliding Sidebar?

### ISSUE THREAD

**Issue by RobertJGabriel** [saadeghi/daisyui#5]
Hey Guys,

Love the UI, is there plans to add a Navigation Drawer/Sliding Sidebar component in the future?

**Comment by saadeghi** [comment]
I think [menu component](https://daisyui.netlify.app/components/menu) can do the job (as I used it for the [site](https://daisyui.netlify.app/) itself)  
The only challenge might be the open/close functionality. I'm trying to keep all components free of JS. In this case however, I can make a CSS only drawer (using a hidden checkbox).
I will close this issue when I add it.  

Thanks.

**Comment by RobertJGabriel** [comment]
Amazing, I can't wait to see it. May I ask are you looking into accessibility aswell? Labels etc

**Comment by saadeghi** [comment]
@RobertJGabriel Of course! If you also find accessibility issues, I would appreciate if you report them so I can fix them faster.

**Comment by saadeghi** [comment]
Drawer component added on saadeghi/daisyui@5b500cdf7220f0d774bf7ef15c0823e6ad88983c  
Sample: https://daisyui.netlify.app/components/drawer  
Tailwind Play: https://play.tailwindcss.com/alzQNMAFsv
@RobertJGabriel
