### ISSUE TITLE
Allow using <button> in menu component

### ISSUE THREAD

**Issue by bttger** [saadeghi/daisyui#506]
Currently only the anchor element is supported (in terms of consistent design). Respective to the A11Y project, they require the href tag. Sometimes it would be good to have a button for js-only purposes.

I took a quick look into the CSS and there are already rules that select the button element. But unfortunately (I guess) there are some missing because the design is not consistent with anchor elements. Can they be added?

**Comment by saadeghi** [comment]
Starting from daisyUI version `2.0` anything in `<li>` will be styled as menu item.  
Example: https://play.tailwindcss.com/1ActCWWlYU

**Comment by bttger** [comment]
Thank you!
