### ISSUE TITLE
Component Drawer: The background color changes, but the drawer does not hide

### ISSUE THREAD

**Issue by brasilikum** [saadeghi/daisyui#509]
Hey, I am checking out DaisyUI and I hit a wall:

I tried both the label and the js (svelte) method to toggle the drawer, both with the same result:
> The background color changes, but the drawer does not hide

[Demo](https://vite-svelte-tauri.onrender.com/)
[Repo](https://github.com/brasilikum/vite_svelte_tauri/tree/main/src)

I copied the code one-to-one from and to the [svelte repl you posted in other issues](https://svelte.dev/repl/e06a5436ecd4425fa119f69c7629a6cc?version=3.44.1). It works in the repl, but not in my repo.

Given that it's just my repo that is not working, feel free to ignore this issue. I am just wondering what in the docs I might have missed that leads to this "half-working" behavior.

**Comment by saadeghi** [comment]
It's a problem from Windi CSS which generates wrong style. Use Tailwind CSS instead and it will be okay.

**Comment by bbjansen** [comment]
> It's a problem from Windi CSS which generates wrong style. Use Tailwind CSS instead and it will be okay.

Could you go more into depth about what is going wrong? thanks.

**Comment by saadeghi** [comment]
Windi has a transform API that should transform Tailwind CSS plugins to a Windi CSS plugin. However, the result CSS is not the expected style. Some rules are missing and some are merged incorrectly. I don't know what exactly is the issue but I know the issue is from the transform API.
