### ISSUE TITLE
[Request] Date picker

### ISSUE THREAD

**Issue by 17twenty** [saadeghi/daisyui#51]
A date picker would be really helpful

![image](https://user-images.githubusercontent.com/379176/119218028-6358a200-bb21-11eb-8e46-db4ae8d725d3.png)

## Subrequests
- Ranged selector
- Show only weekdays
- Events (dots on individual date)
- Month only picker (no days)

**Comment by saadeghi** [comment]
@17twenty I'm planning to a add a calendar component however it will be just a visual calendar (not a fully functional date picker that works with JS). I'm afraid it's not possible to make a functional datepicker component using only CSS. Daisy UI is a CSS library and has no JS dependency.
Also, unlike old days, I think using browser's native date picker makes more sense.
