### ISSUE TITLE
daisyUI pallet shortcut keys not working on Windows

### ISSUE THREAD

**Issue by spences10** [saadeghi/daisyui#513]
Using the alternative keyboard shortcut to open the command pallet (⌘ + k) on the daisyUI site for Windows (Cmd + k) doesn't work and instead opens the search bar.

Here's an example against the Tailwind site using the same keyboard shortcut in Windows on Edge

https://user-images.githubusercontent.com/234708/155485409-da6dc8fb-13c9-43ee-8967-915e23ebb1f0.mp4

**Comment by saadeghi** [comment]
Fixed
