### ISSUE TITLE
Text Input lacks :invalid pseudo-class

### ISSUE THREAD

**Issue by aaronshaf** [saadeghi/daisyui#520]

**Comment by saadeghi** [comment]
daisyUI provides the style for `info`, `success`, `warning` and `info` it's up to you when to use which one. You can choose if an invalid input should be visually an error or a warning or you can handle validation style using JS.

Here's an example:  
https://play.tailwindcss.com/Xe1xyHhbQ4
```html
<input type="email" class="input input-bordered invalid:input-error">
```
