### ISSUE TITLE
Images on the DaisyUI website are getting authorization issue due to Copyright Infringement

### ISSUE THREAD

**Issue by puneet3821** [saadeghi/daisyui#524]
Images are not loading in my browser. My company uses ZScaler which is blocking the images to load into the browser. It is identifying URLs as Copyright Infringement.

### DaisyUI Card Page:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/14244713/155842344-c07d68db-e1e7-4918-a7ce-30dea2229d58.png">

### After Inspect
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/14244713/155842414-238cc1aa-1e6b-4214-a87c-000b34fee1f3.png">

### Zscaler Warning
<img width="811" alt="image" src="https://user-images.githubusercontent.com/14244713/155842370-24f61d24-d526-417d-9532-65795080dd91.png">

I am raising the issue with them to unblock it but not sure if they will approve it.

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/14244713/155842252-b3caa6e5-16be-4d68-8ca8-87c3cf180d0e.png">

**Comment by saadeghi** [comment]
Images are from Unsplash and Pexels websites which only provide free images (even for commerical use)  
So I don't think they have copyright issues.  
If you got an answer from them, please let me know.
