### ISSUE TITLE
Try countdown but not work

### ISSUE THREAD

**Issue by nurabdullah94** [saadeghi/daisyui#529]
sorry if this issues been solved or not, first im new on tailwind and try daisyui, my step right now create laravel breeze, and add daisyui on tailwind.config,js. 
after this i try countdown on welcome blade and add app.css to after run on 2 type browser its still not count,
can you help for this issues 

sorry for my bad language
thanks a lot

**Comment by saadeghi** [comment]
From docs:
>Countdown gives you a transition effect of changing numbers  
You need to change to --value CSS variable using JS. Value must be a number between 0 and 99

https://daisyui.com/components/countdown/

Example: https://codepen.io/saadeghi/pen/jOazxMz?editors=1010
