### ISSUE TITLE
Suggestion for sidebar navigation on website

### ISSUE THREAD

**Issue by naveeninja** [saadeghi/daisyui#53]
`.menu.compact li>a, .menu.compact li>span{
    margin-bottom : 3px;
}`

Before SS : https://d.pr/i/ZMZ6E4
After SS : https://d.pr/i/0PQ0ru

**Comment by saadeghi** [comment]
Thanks! I made some changes and I think it looks better now:
![](https://user-images.githubusercontent.com/7342023/119259314-eb52b080-bbe2-11eb-97b5-4dc87f149176.gif)
