### ISSUE TITLE
Upgrade path from 1.x to 2.x

### ISSUE THREAD

**Issue by Wobbley** [saadeghi/daisyui#530]
Hey

I see that DaisyUI has hit 2.x, congratulations! I use it with my Sveltekit hobby projects and am really happy with it.

Is there an upgrade path from 1.x to 2.x? Would be nice so I know I didn't miss anything.

P.S Have you considered adding the github sponsors feature to the project?

**Comment by saadeghi** [comment]
The biggest change is daisyUI version `2.x` needs Tailwind CSS version `3.x` as a dependency.  
Other than that there are [changes in some colors](https://github.com/saadeghi/daisyui/blob/master/CHANGELOG.md#breaking-changes)  
If you're already using Tailwind CSS 3.0 there shouldn't be any issues.

About GitHub's sponsor program: I live in Turkey and unfortunately It's not available here yet.

Let me know if you found any issues upgrading to v2.x
