### ISSUE TITLE
bedge color inside button

### ISSUE THREAD

**Issue by matheusAle** [saadeghi/daisyui#538]
role .btn .bedge override .bedge-{color}.

![image](https://user-images.githubusercontent.com/22581882/156400718-7d73ff21-dd27-44b1-935e-78b883995bee.png)

**Comment by saadeghi** [comment]
@matheusAle Which version of daisyUI are you using?

**Comment by matheusAle** [comment]
@saadeghi I am using `daisyui@^1.25.4` and `tailwindcss@^3.0.18`

**Comment by saadeghi** [comment]
This is fixed already. Please upgrade to latest version.
