### ISSUE TITLE
Swap rotate enhancement

### ISSUE THREAD

**Issue by cer1969** [saadeghi/daisyui#541]
Is very easy to add some classes to swap in order to have some more natural rotates:

```
.swap-rotate-90 input:checked ~ .swap-on, .swap-rotate-180 input:checked ~ .swap-on { @apply rotate-0; }
.swap-rotate-90 .swap-off, .swap-rotate-180 .swap-off { @apply rotate-0; }
.swap-rotate-90 .swap-on { @apply rotate-90;}
.swap-rotate-90 input:checked ~ .swap-off { @apply -rotate-90; }
.swap-rotate-180 .swap-on { @apply rotate-180;}
.swap-rotate-180 input:checked ~ .swap-off { @apply -rotate-180; }
```

**Comment by saadeghi** [comment]
Yes but I think this level of customization should be done by the developers.  
There's [no limit](https://animate.style/) on how many animation styles can be added to daisyUI but I think we should keep it simple, while giving the developers the option to extend and customize it (like your example)
