### ISSUE TITLE
btn-sm inside menu inconsistent

### ISSUE THREAD

**Issue by soulsam480** [saadeghi/daisyui#543]
Hii, I'm not sure if this is a bug or not, but adding `btn-sm` to button inside menu > li is behaving differently. normal `btn` works properly.
- with `btn-sm` , notice the label offset from center
![image](https://user-images.githubusercontent.com/35460828/156515460-d3c124c4-c0c6-43ba-9d37-af6d645d10de.png)
- without `btn-sm`, normal button
![image](https://user-images.githubusercontent.com/35460828/156515584-82ffef86-e5de-43ab-a9ad-71bc9dd28ae2.png)

**Comment by saadeghi** [comment]
The element inside `.menu>li` will be styled as a menu item.  

If it's a button in `<li>`, you can just remove the `btn` class and it will look like a menu item as it should.  
Or if you want to have a `.btn`, put it in a div or something.  
Example: https://play.tailwindcss.com/4qoVmoErZU

Let me know if you have any questions.

**Comment by soulsam480** [comment]
Aah, got it. In my case the menu item needs to be a button element so I'll go with the li > div > button setup. more work but definitely required for my usecase. Thanks for the quick reply man :heart:
