### ISSUE TITLE
Next.js, DaisyUI and ThemeProvider

### ISSUE THREAD

**Issue by mxcdh** [saadeghi/daisyui#545]
Hello

I using next.js and theme-provider from next-themes for darkmode. 
How I can using daisyui with theme-provider?

Bellow my code:
https://stackblitz.com/edit/nextjs-vmteir?file=tailwind.config.js

**Comment by mxcdh** [comment]
OK, please close:
Solution: https://github.com/saadeghi/daisyui-nextjs-nextthemes

**Comment by saadeghi** [comment]
Yes. that example using buttons.  
Here's with `swap` checkbox:

https://stackblitz.com/edit/nextjs-11dfv5?file=components/DarkMode/DarkMode.tsx

**Comment by mxcdh** [comment]
@saadeghi 
When I want change background color in cyberpunk theme  - from yellow to blue, what I should to do?

**Comment by saadeghi** [comment]
I'm not sure if I understand you correctly.  
You mean change the theme using `next-themes` or modifying the colors of one theme?

**Comment by mxcdh** [comment]
@saadeghi  Yes, exactly.
I want in this code:
https://stackblitz.com/edit/nextjs-11dfv5?file=tailwind.config.js
- edit background for themes cyberpunk
- edit font size and family for themes synthwave

**Comment by saadeghi** [comment]
@mxcdh 
You can apply changes to built-in themes like this:  
Example: https://stackblitz.com/edit/nextjs-cxjxug?file=tailwind.config.js  
Docs: `How to customize an existing theme` section [here](https://daisyui.com/docs/themes/)

Also, you can make your own theme in no time: https://daisyui.com/theme-generator/

**Comment by saadeghi** [comment]
@youfoundron I don't have access to the old links but here's a new example with Next.js + Next Themes + daisyUI:  
https://stackblitz.com/edit/daisyui-nextjs-ftqupt?file=pages/index.js

**Comment by youfoundron** [comment]
@saadeghi thank you!
