### ISSUE TITLE
How customize out-of-box components like menu?

### ISSUE THREAD

**Issue by mxcdh** [saadeghi/daisyui#547]
Hi

Example:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/98115983/156800711-c9efa3c5-2bff-4559-87c7-6dbd4e76e503.png">
I have this menu, I know that clicked color is primary.
But if I want change only for this menu, this component primary color for example primary/75?  What I should to do? 

In touch!

**Comment by saadeghi** [comment]
Color shows up when the item inside `<li>` is `:active` so you can add a class like `active:bg-yellow-400`

Example: https://play.tailwindcss.com/uqEysRpoXD

Let me know if you have any questions

**Comment by mxcdh** [comment]
Hello again, 

This information is bellow, yes?
<img width="710" alt="image" src="https://user-images.githubusercontent.com/98115983/156804548-ec373a0d-cd72-486d-b7ec-fc32746c3c10.png">

Let me know, beacouse I beginner and I shouldn't ask you about easy things.

**Comment by saadeghi** [comment]
No, that's talking about the `active` class name. 
In [this example](https://daisyui.com/components/menu/#menu-with-active-item) you can see the second item is highlighted as active.  
```html
<ul class="menu bg-base-100 w-56">
  <li><a>Item 1</a></li>
  <li><a class="active">Item 2</a></li>
  <li><a>Item 3</a></li>
</ul>
```
This class name exists to easily style the active item in a menu (like the link of current page in a navigation menu)

But `:active` is a CSS pseudo-class (like `:hover`) and when we use `active:bg-yellow-400` the yellow background will be visible when we click the link and it gets `:active`.  
It might be confusing but to wrap up:  
- `{SELECTOR}:active` is the CSS pseudo-class
- `active:{UTILITY_CLASS}` is a Tailwind prefix
- `active` is simply a class name from daisyUI

**Comment by mxcdh** [comment]
Hmm

This is not active, I mean that color:
![image](https://user-images.githubusercontent.com/98115983/156825812-69458e1e-a1dd-4158-bcac-ad738315f537.png)
I want change this color, only in this component.

Below my code:
https://stackblitz.com/edit/nextjs-dp7bdi?file=components%2FMenu%2FMenu.tsx

**Comment by saadeghi** [comment]
If you see my example again, I added `active:bg-yellow-400` class to `<a>` tag.  
You added it to `<li>` and that's why you're not seeing the same result.  
Here it's yellow: https://stackblitz.com/edit/nextjs-74mbmf?file=components%2FMenu%2FMenu.tsx

**Comment by maburzynski** [comment]
@saadeghi  thanks for help.

**Comment by gsteen** [comment]
The color only changes to `active:bg-yellow-400` while mouse down. After that the color goes back to `bg-primary`.
How can i change the color for class="active" while not pressed or focued?

https://play.tailwindcss.com/QHbES10jT0

thx
