### ISSUE TITLE
UI Issues with Change Theme Dropdown Option

### ISSUE THREAD

**Issue by philson-philip** [saadeghi/daisyui#55]
@saadeghi I have figured out some issues in the Change Theme dropdown in the production UI. I will fix the issue and create PR for the same. Attaching the screenshot below.

<img width="337" alt="Screenshot 2021-05-23 at 3 22 52 AM" src="https://user-images.githubusercontent.com/22117214/119241711-2a96e800-bb76-11eb-8c07-936d58ebb56c.png">

**Comment by saadeghi** [comment]
Thanks! I made some changes and I think it looks better now:
![](https://user-images.githubusercontent.com/7342023/119259314-eb52b080-bbe2-11eb-97b5-4dc87f149176.gif)
