### ISSUE TITLE
Popover - html content for Tooltips

### ISSUE THREAD

**Issue by gjovanov** [saadeghi/daisyui#56]
Hey @saadeghi ,
I noticed the new `tooltip` component was added, which is great.

However, it seems that this `tooltip` component has the limitation of displaying only `plain text` without the option to put well formatted `html content`.

Maybe it makes sense to either consider improving the current `tooltip` or add a new component named e.g. `popover`, for displaying `html content`.

Here is an [example](https://github.com/Cosbgn/tailwindcss-tooltips) of one such implementation.

**Comment by saadeghi** [comment]
I think [`dropdown dropdown-hover`](https://daisyui.com/components/dropdown) is basically doing the same job. Showing an HTML element on hover 🤔

**Comment by gjovanov** [comment]
Not that have mentioned it, you right, no need for special component like that 😃  ... closing.

**Comment by Drumstix42** [comment]
One notable difference is that the tooltips have the arrow/caret attached to the tooltip, indicating the source element. Popovers do not have this same UI. I too would like some kind of option that mimics tooltips but can be any contents, and have the anchored arrow styling.

**Comment by saadeghi** [comment]
There's new native HTML `popover` API and we are planning to add it to daisyUI as soon as Firefox starts supporting it. It would be perfect for this use case:  
https://developer.mozilla.org/en-US/docs/Web/API/Popover_API

**Comment by nandor23** [comment]
Since the popover API is relatively new and not widely supported, with only newer browser versions offering compatibility, wouldn't it be more practical to not use it?

**Comment by saadeghi** [comment]
Yes, it's not widely supported yet. But it will be in the future. 
>we are **_planning_** to add it

**Comment by kuchta** [comment]
Hey guys, it's already supported in all major browsers, including Safari 🎉

**Comment by saadeghi** [comment]
@kuchta Yes. It will be in daisyUI 5.0
