### ISSUE TITLE
Code-mockup overflow on small displays like iPhone 4

### ISSUE THREAD

**Issue by rustynail1984** [saadeghi/daisyui#570]
Code mockup component overflow on small displays

so change     
`min-width: 20rem;`
to
`min-width: 15rem;`

![image](https://user-images.githubusercontent.com/65692019/157538459-7610cf29-2003-4588-9757-0fe045d44081.png)
![image](https://user-images.githubusercontent.com/65692019/157538735-db25da95-7982-4ffc-8cc5-2478bb5570f4.png)

**Comment by saadeghi** [comment]
iPhone 4 is from 11 years ago 💀

**Comment by rustynail1984** [comment]
> iPhone 4 is from 11 years ago 💀

Yeah, i know. But there are still Smartphones outside that using this Display Size. "Android Smartphones"

**Comment by saadeghi** [comment]
That's not true. You might find an old 320px phone on my grandma's drawer but it has near 0% market share.

Minimum screen size for mobile is 360px now

https://gs.statcounter.com/screen-resolution-stats/mobile/worldwide
