### ISSUE TITLE
JS-controlled modals

### ISSUE THREAD

**Issue by xorik** [saadeghi/daisyui#583]
Hey!

I wanted to use modals in my app. They looks really nice, but it turned out they are very limited:
- I can't add 2 or more buttons without weird checkbox logic
- Requires checkbox/unique ID
- Can't be shown/hidden by javascript (kinda possible but with checkbox manipulation)

So this is proposal to make js-controllable modals

It may look like this:
```html
<div v-if="visible" class="modal js" >
  <div class="modal-box">
    <h3 class="font-bold text-lg">Congratulations random Interner user!</h3>
    <div class="modal-action">
      <button @click="visible=false" class="btn">Yay!</button>
    </div>
  </div>
</div>

<button @click="visible = true">Open modal</button>
```

What do you think?

**Comment by nnnoel** [comment]
@xorik Currently, you can control the modal using javascript by toggling the `modal-open` class.

https://daisyui.com/components/modal/#

<img width="748" alt="Screen Shot 2022-03-13 at 6 15 23 PM" src="https://user-images.githubusercontent.com/14010887/158056893-41e8be26-f931-4bca-82fe-26fea32378c0.png">

I found the modal will still show if accessed via url hash, which might be an existing caveat.

**Comment by saadeghi** [comment]
I would like to add an example of using JS to the docs but data binding is a little bit different on each framework. Here's an example with Svelte: https://svelte.dev/repl/f61fe53d3d0544b98892ce629c5f6ccb?version=3.46.4

**Comment by xorik** [comment]
Ah, okay, thanks. I somehow missed that I can put a class.. Maybe you can add link to this demo, I think it can be easily implemented in any framework
