### ISSUE TITLE
Disable animation ?

### ISSUE THREAD

**Issue by kgnfth** [saadeghi/daisyui#6]
How to disable animation 
i dont like the animation when you click on a button

**Comment by saadeghi** [comment]
@kgnfth use this CSS variable: `--animation-btn`. ([example](https://play.tailwindcss.com/FOlmhxMqCQ?file=css))
```css
:root {
  --animation-btn: 0;
}
```
There are a few more variables to customize components as mentioned [here](https://daisyui.netlify.app/docs/add-themes).

**Comment by saadeghi** [comment]
Update: a classname `no-animation` has been added to disable animation for button and other inputs such as checkbox or toggle.

**Comment by kgnfth** [comment]
@saadeghi Thank you for your work

**Comment by callmevari** [comment]
Hey @saadeghi, is the animation tested on mobile? I'm using capacitor + daisyui, and the button animation goes well on browser, but not on mobile. I need to long-press the button (at least 1 second) to see the animation, weird.

**Comment by saadeghi** [comment]
@callmevari I'm not sure how's your experience but it's not about daisyUI or even CSS.  
click events with mouse is different from touch screen. With desktop, there's hover and click is actually a combination of mouse down and mouse up. On mobile the's no hover and tap is different from click (mouse down + mouse up). It's one event and it's instant. So it's expected for mouse down event animations to be skipped until you simulate a mouse down by doing a long press.

**Comment by rtritto** [comment]
Maybe can help, I disabled button animation using theme:

```ts
// tailwind.config.ts
import type { Config } from 'tailwindcss'
import daisyui from 'daisyui'
import themes from 'daisyui/src/theming/themes'

export default {
  content: [
    './src/**/*.{ts,tsx}'
  ],
  daisyui: {
    themes: [
      {
        dark: {
          ...themes['dark'],
          '.btn': {
            animation: 0
          }
        }
      }
    ]
  },
  plugins: [daisyui]
} satisfies Config
```

**Comment by jazoom** [comment]
Thanks @rtritto, that worked. Curiously, when I added that to one of my themes, the animation was disabled for all my themes.
