### ISSUE TITLE
Add center/bottom option to modal

### ISSUE THREAD

**Issue by Makohan** [saadeghi/daisyui#616]
＜Feature Request＞
https://daisyui.com/components/modal/#

Showing modal is difference by Desktop and Mobile. 
Desktop is center, but Mobile is from bottom.

Would you add center or bottom option for Usability?

**Comment by Makohan** [comment]
Thank you!!
I appreciate your quick response!!

**Comment by sciencecoder** [comment]
Thank you all for this. Just what I needed. I appreciate it.
