### ISSUE TITLE
Problem with modal in Next.js

### ISSUE THREAD

**Issue by mxcdh** [saadeghi/daisyui#621]
Hello

I have a problem with the modal in next.js.
Bellow my code:
https://stackblitz.com/edit/nextjs-b54m9m?file=components/Cookie/Cookie-A-Href.tsx
- component cookie-a-href is working
- component cookie-next-link, not working, hash added to URL, but modal is not shown in a browser, 

How I can fix the second component?

**Comment by mxcdh** [comment]
Maybe is option in Next.js, when I can after click force reload page?
I trying bellow, but is not working:
`  <Link key="id" passHref href="cookie-alert" as={`cookie-alert`}>
      <a>more</a>
    </Link>
`

**Comment by saadeghi** [comment]
Next.js `<Link>` is a component and is created to handle functionalities like `prefetch` or other navigation manipulations. I don't think you need to use it here and you can just use native HTML `<a>`.  
If you really want to use `<Link>` open a discussion or issue on Next.js repo and ask them why it doesn't work.  
daiyUI is basically using this method: https://codepen.io/peiche/pen/kQwYVJ?editors=1100
