### ISSUE TITLE
table overlaps modal - fixed through changing position values

### ISSUE THREAD

**Issue by tobealive** [saadeghi/daisyui#624]
Using the table component came with a problem. The table was overlapping another component in a modal. I was trying to solve this by working on the overlapped and other components in the modal, but to no avail. Also, things like fiddling with z-indexes for those components and the table elements didn't solve it. The only thing that helped was changing the position values back to default for the daisyUI table. (from `relative` to `static` for `<table>` and from `sticky` to `first:!static` for the `<th>` elements.)

Unfortunately, at this time it is not possible for me to create similar scenarios that I could share and that would be easy to reproduce, so you have an easier time with this. The interference in my use case was with a modal from solana anchor wallet integration developing a dApp with svelte frontend. 

Maybe this report helps anyway. And I might be wrong, but I don't see a strict necessity for the mentioned position values in the table components, so perhaps the property can be removed, so such issues won't occur?

**Comment by saadeghi** [comment]
I'm not sure how you're combining the elements.  
Here's an example of `table` in `modal`: https://play.tailwindcss.com/TVGRabghDe  

Please provide some clue so I can get some idea about your code.  
A repo, a code example, a screenshot... 🤷‍♂️

**Comment by tobealive** [comment]
Yes, I'm sending screenshots. Should have done that right away and be more specific. Sorry about that. The problem is that the table inside the page content ("behind" the modal), overlaps content in the modal.

Using table with no modification to `position`:
![position-daisyui](https://user-images.githubusercontent.com/34311583/158801106-6b9a042b-9e32-4a20-ae7d-58551b665170.jpg)

Settings position to static like mentioned in issue opening:
![position-static](https://user-images.githubusercontent.com/34311583/158801115-b4931d7c-9a01-4284-bdde-2b7ac7dc2564.jpg)

**Comment by saadeghi** [comment]
I still can't reproduce this issue.  
here's a table and a modal and it works as expected: https://play.tailwindcss.com/eH2zvHH56Q

Please provide an example where I can reproduce the issue

**Comment by tobealive** [comment]
Hey thanks again for the reply.
I tried again to find a reason why it behaves that way when mixing those two components. Unfortunately I still can't extract the reason to make it reproducible. 

Anyway, your test show that is doesn't seem to be a problem with the UI and that it works in "normal" scenarios. So I probably also wouldn't see a necessity to add it to the UI globally. Also, adding the position manually for that specific use case is definitely sufficient. All good 👍
