### ISSUE TITLE
NavBar component with dropdown render blank under it

### ISSUE THREAD

**Issue by tamagoez** [saadeghi/daisyui#631]
Seems occuring in [this docs](https://daisyui.com/components/navbar/#navbar-with-menu-and-submenu) too.

When I tried to add dropdown component into NavBar component, blank showed under the component.
When I add huge dropdown, blank will become more huge.
It might cause by dropdown spacing.

This makes viewers uncomfortable, so I think this should be resolved.
Thank you for reading.

**Comment by saadeghi** [comment]
Sorry but I'm not sure if I understand what you said. What is "blank"?  
Can you show me a code on [Tailwind Play](https://daisyui.com/tailwindplay/)? Or attach a screenshot of the problem?

**Comment by tamagoez** [comment]
![image](https://user-images.githubusercontent.com/87574268/159145388-b2f2e8c1-6cbb-443b-afce-90ba04ea1b2f.png)
Also [Tailwind Play](https://play.tailwindcss.com/DctJ2NrrPr)

**Comment by saadeghi** [comment]
Remove the `mb-40` class from your code. `mb-40` means margin on bottom

**Comment by tamagoez** [comment]
Why there are `mb-40` class in docs?

**Comment by saadeghi** [comment]
Because it's a demo and I needed space there for demonstration. I assume everyone who are using daisyUI already know about Tailwind CSS class names 🤷‍♂️

**Comment by tamagoez** [comment]
OK, thank you

**Comment by orbiteleven** [comment]
This just got me as well. I think it's safe to assume folks will copy-paste examples from the demo and could occasionally get tripped up by that. Yes, it's pretty obvious what's going on when it's called out, but on a Monday before enough coffee it can be a gotcha :D

Shouldn't the demo containers have their own dimensions so extra height/padding is there instead of in the sample code? Sorry to thread-jack.

**Comment by saadeghi** [comment]
@orbiteleven You're right.  
Which example still has the issue? Because I already removed the extra class names from the navbar examples

**Comment by orbiteleven** [comment]
@saadeghi The [Dropdown menu using <details> tag](https://daisyui.com/components/dropdown/#dropdown-menu-using-details-tag) got me this AM.

I *think* this fixes it, though I didn't go through trying to build docs myself: https://github.com/saadeghi/daisyui/pull/2437

**Comment by saadeghi** [comment]
Thanks for the PR. Merged ✅
