### ISSUE TITLE
Tooltip is broken when it is called under Card container.

### ISSUE THREAD

**Issue by riobahtiar** [saadeghi/daisyui#632]
Hi DaisyUI Maintainer,
Thank you for your stunning work and for making this cool project. 

I found a bug in the Tooltip component when combined with the Card component. [Here is the sample code and demo in Codepen](https://codepen.io/riobahtiar/pen/LYeNXNO) .

![Screen Recording 2022-03-20 at 00 00 49](https://user-images.githubusercontent.com/2656058/159130934-c53aa741-375a-4633-9c3a-6bbadb974ee9.gif)

Thank you. 👍 

Version: 

`"daisyui": "^2.11.0"`

`"tailwindcss": "^3.0.23"`

**Comment by saadeghi** [comment]
This can be fixed by adding `overflow-visible` class to the card: https://codepen.io/saadeghi/pen/oNpxrdy  
By default, card has `overflow-hidden` so that the image in `card` wont overflow the border-radius of `card`

**Comment by vbersier** [comment]
Can this be added to the documentation for `tooltip`? I was looking for this information but it's not easy to find in the closed issues.

**Comment by saadeghi** [comment]
Sure. I will update the docs
