### ISSUE TITLE
Safari: Textarea Resizing

### ISSUE THREAD

**Issue by cesoun** [saadeghi/daisyui#635]
**Version(s):**

_Safari 15.3 (17612.4.9.1.8)_
_Chrome 99.0.4844.83_
_macOS Monterey 12.2.1 (Intel)_
_daisyui ^2.6.3_

Reproduced on the [Tailwind Play Demo](https://play.tailwindcss.com/j19s5PHWEZ) page.

**Description:**

When working with textareas on Safari the resize functionality seems to be lost as a result of the applied `padding-left,right,top,bottom` from the `textarea` class. 

This can be seen through the [textarea demos](https://daisyui.com/components/textarea/#textarea) on the DaisyUI site which resize fine on Chrome but have no resizing functionality on Safari. (Unsure if this is theme related, tried: business, light, dark)

My current solution is to add `p-0.5` (or any padding variant) class to override the default padding which returns the resizing functionality to Safari.

The tailwind class `resize` and its variants also seem to have no effect when used in addition to the `textarea` class on Safari as a result of the styled padding.

**Comment by saadeghi** [comment]
This is a bug from Safari and you can see it here even without Tailwind CSS or daisyUI:  
https://codepen.io/saadeghi/pen/RwxGjXe?editors=1000

I opened an issue on WebKit issue tracker here:  
https://bugs.webkit.org/show_bug.cgi?id=238193
