### ISSUE TITLE
Scroll history broken on drawer

### ISSUE THREAD

**Issue by velser** [saadeghi/daisyui#637]
Hi.

Apparently drawer-content which has max-height: 100vh breaks scroll history when user navigates back. I've used docs an all content(nav, content and footer) were placed into drawer-content by hierarchy provided in the docs.

I mainly use it for a mobile, so it's only relevant to make 100vh max when opened. Not sure if that's the bug or something I'm doing wrong, altho I've came up with a temporary fix by adding some scss:

```
.drawer-toggle ~ .drawer-content {
  max-height: 100%;
}

.drawer.drawer-end .drawer-toggle:checked ~ .drawer-content {
  max-height: 100vh;
}

```
So now max-height is only set when drawer is opened(in my case it's only for mobile so it's what's needed).

Anyone faced same issues ?

Just in case, hierarchy pseudo-example I use:

```
<div class='drawer'>
 <input id='drawer'/>
 <div class='drawer-content'>
   header
   <label for='drawer'/>
   content
   footer
 </div>
 <div class='drawer-side'>
   side menu
 </div>
</div>
```

**Comment by saadeghi** [comment]
I'm not sure what do you mean by "scroll history"?  
You mean the swipe left/right to go to next/prev pages on mobile?  
Or what you mean is when yo leave a page and get back, you're not getting the same scroll position where you left the page?

Also what is your mobile OS and browser version?

**Comment by velser** [comment]
Ahh pardon me, I was in a hurry when wrote an issue.

I mean going to another page and then going back via browsers back button (or swipe back) and keeping same scroll position.

Browsers are the latest safari and chrome.

I've tested both with current code and just simple multiple divs as a content and got same result until I came up with a quick solution to remove max 100vh from a content if drawer is not opened

**Comment by saadeghi** [comment]
thank you for clarifying. I will look into it.

**Comment by velser** [comment]
> thank you for clarifying. I will look into it.

Also, to mention, I use latest GatsbyJS and I'm not sure if it's a default browsers behaviour to keep position on refresh or it's gatsbys' out of the box solution, altho most of the pages do keep the state on refresh.

And I have same issue if I keep `h-screen` from example so I've removed it also and added that quickfix.

Thanks!

**Comment by saadeghi** [comment]
This looks like a browser specific behavior.  
`drawer-content` is a scrollable div and when we scroll the div (not the page) then leave the page and go back again, some browsers remember the scroll position of div and some reset it to the top.  
In my test, Safari always remembers the scroll position of div but chrome always resets the scroll position to the top.

The CSS you provided had no effect tho 🤷‍♂️ (tested on Chrome 99.0 and Safari 15.4)

**Comment by velser** [comment]
> This looks like a browser specific behavior. `drawer-content` is a scrollable div and when we scroll the div (not the page) then leave the page and go back again, some browsers remember the scroll position of div and some reset it to the top. In my test, Safari always remembers the scroll position of div but chrome always resets the scroll position to the top.
> 
> The CSS you provided had no effect tho 🤷‍♂️ (tested on Chrome 99.0 and Safari 15.4)

Have you tried removing 'h-screen' from an official example and then applying the fix? It works well on my page with that fix, same chrome - 99, tested both with mobile and browser and page position stays the same

**Comment by saadeghi** [comment]
It's weird that you're getting a different result.

Here's a video of Chrome 99:  
(you can see the additional `max-height: 100%` style is being used)  

https://user-images.githubusercontent.com/7342023/159781342-4fa63fb1-1fb4-4b3f-926e-61e3bb6a13f2.mp4

And iOS Safari:

https://user-images.githubusercontent.com/7342023/159781529-c3ade0f4-c5d9-4fe1-889a-543097f15d17.mp4

**Comment by velser** [comment]
> It's weird that you're getting a different result.
> 
> Here's a video of Chrome 99: (you can see the additional `max-height: 100%` style is being used)
> 
>  chrome.mp4 
> And iOS Safari:
> 
>  safari.mp4

Yeah, but I see `h-screen` is still presented in your chrome example. Have you tried removing it? Then scroll position persists

**Comment by saadeghi** [comment]
So we can't let the height of `drawer` be larger than the height of screen because we want `drawer-content` and `drawer-side` to scroll independently. And problem is when the div is getting scrolled (instead of whole document) chrome forgets the scroll position of div after leaving the page

**Comment by velser** [comment]
Yep, fortunately for me I don’t need a drawer on desktop and only top(not fixed) menu burger on mobile and everything fits into non-scroll manner yet. Otherwise my fix would have issues I supose.

**Comment by saadeghi** [comment]
I don't think I can do anything about this for now. because what I need here is the div having scroll (instead of body) so I can control the scroll of sidebar and content separately and whether it's open or collapsed. 
And when the div has scroll, some browsers reset the scroll position when we leave the page.

One way is to use CSS `:has` to apply styles based on the layout but browsers [don't support `:has` yet](https://caniuse.com/css-has)
