### ISSUE TITLE
Checkbox background color is white on all themes

### ISSUE THREAD

**Issue by banktransacties** [saadeghi/daisyui#638]
The checkbox background color stays white (#fff) on all themes and in all variants (default, primary, secondary, etc):

![Checkbox](https://user-images.githubusercontent.com/100417439/159652524-ce8bec55-95ab-436d-91e4-8c5fa8f8d4ca.png)

**Comment by saadeghi** [comment]
Unchecked checkbox has no background color. Example: https://play.tailwindcss.com/7C2kYPZeOU  
are you sure you're not using any other CSS code that might set that color (for example `@tailwindcss/forms` package)?

**Comment by banktransacties** [comment]
Only using these css styles (from the latest stable tailwind version):

```
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';
```

Maybe the issue is in the latest tailwind, I see also some issues with the default styling of inputs (the Chrome browser puts a blue ring all inputs). For which there's an open pull request.

**Comment by saadeghi** [comment]
Can you share your `tailwind.config.js` file?

**Comment by banktransacties** [comment]
Found it, in the tailwind.config.js it included the tailwindforms. Didn't know about about that.

**Comment by saadeghi** [comment]
Yup. That applies colors and other styles to all form elements

**Comment by NathanVG** [comment]
@saadeghi I just ran into this is well, maybe mention this in the documentation?

**Comment by saadeghi** [comment]
It's not even a style from daisyUI. Why should it be in daisyUI docs 😅

It's a style from a different plugin (tailwind forms) and it is mentioned in its repo that it applies styles to all form HTML tags.
