### ISSUE TITLE
Weird color and size shift on Next Js

### ISSUE THREAD

**Issue by NeoPrint3D** [saadeghi/daisyui#641]
So for some reason when the page is first loaded in the production server it makes the text grow bigger or change different color.

is there any fix?

website here:
[https://zion-producers.vercel.app/](url)

**Comment by NeoPrint3D** [comment]
I think that daisyui is loading after the page is already served, but I don't really know

**Comment by saadeghi** [comment]
Do you have this issue without daisyUI?  
Can you share your code?

**Comment by saadeghi** [comment]
I'm closing this due to no answers and no code examples.  
Please re-open after providing an example repo to reproduce the issue.

**Comment by NeoPrint3D** [comment]
https://user-images.githubusercontent.com/77029802/160286747-64186512-23eb-42a6-bf21-7bf3558b5acf.mp4


The code has changed so I don't have the original code
