### ISSUE TITLE
countdown component is drawn above overlapping elements.

### ISSUE THREAD

**Issue by comfuture** [saadeghi/daisyui#643]
Since `.countdown > span` has a relative position, it will be drawn above the overlapping `fixed` and `sticky` elements.
So it should have a style `z-index: -1` by default.

example:
https://stackblitz.com/edit/daisyui-nuxtjs-tb4y76?file=pages%2Findex.vue

**Comment by saadeghi** [comment]
`z-index: -1` was causing visibility issues. You can use a simple `z-10` on your sticky element if you want it to go in front:

https://stackblitz.com/edit/daisyui-nuxtjs-pcib7y?file=pages/index.vue
