### ISSUE TITLE
[Question] Drawer usage with max width

### ISSUE THREAD

**Issue by iozcelik** [saadeghi/daisyui#654]
I want to use drawer however I also want to use max width. So I add `max-w-xl` class to drawer content area. Then the sidebar open at near the content. I don't want to use like that. How can I fix it?
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/10682780/160184282-8675d85a-d3cb-4c00-bc7e-4e24577afdf6.png">
https://play.tailwindcss.com/gRZzIBVVqF

**Comment by iozcelik** [comment]
I try but it is not worked. I put all level of drawer. Actually I want to make content middle of screen (I use mx-auto) with max width.
I try all possibilities as I think. I am not succeed.

**Comment by saadeghi** [comment]
Ok, this is what you're looking for:  
https://play.tailwindcss.com/gcfB2itGrh?size=1436x658

`drawer` is a grid layout and that allows us to have 2 columns side-by-side with separated scrollable areas and conditionally hide the sidebar (or not)

In my example, to push both columns in the center, I give `60vw` to the content and `40vw` to the sidebar and then justify the content to start and the sidebar to left so they will meet in the center (at 40%/60% of screen)

I will add this example to the document website.
