### ISSUE TITLE
Suggestion: Buttom Sheet component for mobile devices

### ISSUE THREAD

**Issue by skadiD** [saadeghi/daisyui#658]
i find a project but its based  on  React. I think it might be great on mobile device
[react-spring-bottom-sheet](https://github.com/stipsan/react-spring-bottom-sheet)

**Comment by saadeghi** [comment]
You can have something similar using `modal-bottom`  
See last example here: https://daisyui.com/components/modal/#responsive-modal-goes-bottom-on-mobile-screen-and-goes-middle-on-desktop

The difference is, it doesn't have the swipe effect (you need JS for that)
