### ISSUE TITLE
daiyui left-side TOC

### ISSUE THREAD

**Issue by pspierce** [saadeghi/daisyui#659]
When you divided the TOC along the left into categories, it actually made it more difficult to find what I'm looking for than when it was a simple, alphabetically ordered list.  Now, I have to ctrl-f and search.  Having to think through what category what I'm looking for is under, though intuitively seems more straightforward, actually takes more thought.  For example, if I am looking for "modal", I have to now consider what category that would be under and if I have to scroll up or down from where I am.  Is it Layout?  No.  Is it Data Display? Nope, not there.  Oh, Actions.  So now, I have to take the extra steps to do a find in my browser whereas before, I could just scroll up or down depending on the alphabet and where I am positioned currently.  If I was previously looking at "Range", I scroll up to find Modal.  If I was previously looking at Checkbox, down.  Sounds petty, but I'm creating a large application using daisyUI and therefore spend a lot of time in the docs.  Just, FYI.  Appreciate daisyUI and the work you have put into it.

**Comment by saadeghi** [comment]
Alphabetical order without categories was only helpful for people that already knew there's a `modal` and they went straight to the `m`. But people who don't know about the name of available components had a hard time to find things.  

Anyway, now that site has a search box, that's the fastest way to find things.
Press `⌘`+`K` and type `mo` and you get `modal`. No need for scrolling and scanning the list to find the `m` in alphabetical order.  
This is also helpful for components that have different names elsewhere. For example typing `switch` suggests what you're looking for: `toggle`
