### ISSUE TITLE
help how to generate this code  

### ISSUE THREAD

**Issue by kknono** [saadeghi/daisyui#660]
--p:0 100% 50%; --s:221 83% 53%; --a:261 100% 90%; --n:215 27% 14%; --b1:214 29% 22%; --in:216 61% 67%; --su:171 67% 51%; --wa:38 96% 56%; --er:352 77% 53%; --pf:0 100% 40%; --sf:221 83% 43%; --af:261 100% 72%; --nf:216 26% 11%; --b2:213 29% 20%; --b3:215 29% 18%; --bc:214 88% 84%; --pc:0 100% 90%; --sc:221 100% 91%; --ac:261 100% 18%; --nc:215 48% 83%; --inc:216 100% 13%; --suc:171 100% 10%; --wac:38 100% 11%; --erc:352 100% 91%;

**Comment by saadeghi** [comment]
Explain more please. What is the problem and what are you trying to do?

The code you provided is the HSL values of color variables.

**Comment by kknono** [comment]
thank you very much . we need to load dynamic theme config,  but hope just style the component timely.(do not rewrite/reload tailwind.config.js)
for example, a user set 'primary' value with '#123456',  current page changed real-time.

**Comment by saadeghi** [comment]
There's a table in this page where you can find the name of colors and their CSS variables:  
https://daisyui.com/docs/colors/

For example, `primary` color CSS variable is `--p`  
And the value is HSL.
So if the user is picking a hex color, you need to convert hex to HSL and put 3 HSL values into CSS variabls. For example if HSL color is `hsl(0deg 100% 50%)` variable should be like `--p:0 100% 50%`

For converting color from hex to HSL, there are packages on npm like [this one](https://www.npmjs.com/package/color)

Let me know if you have any questions

**Comment by kknono** [comment]
I got it . thank you very much
