### ISSUE TITLE
Navbar horizontal menu isn't hiding the submenu

### ISSUE THREAD

**Issue by sarahk** [saadeghi/daisyui#661]
I'm new to tailwind and daisyui looks like a great tool to get standard components styled. I'm trying to get the horizontal menu working but the centre menu wasn't hiding the dropdowns. 

I've cut out everything from the page and I've got very little in my global.css and its all for "main" anyway. 
If I inspect the page I can see all the styles are either inline or coming from "globals.css:1" (or line 2 or 3) but not from anything I've added. 
Nextjs is spitting out clean HTML - nothing in the console, it all looks good.

what I want...
https://play.tailwindcss.com/xvlGXyT06l?layout=horizontal

The "play" proves that it should work, now I need to work out how to debug this so that it works on my page. What should I be looking for?

**Comment by saadeghi** [comment]
Can you share your next.js code which isn't working as expected?

**Comment by sarahk** [comment]
sure...

```const menuItems = [
  {
    label: "About Us",
    url: "/aboutus",
    key: "aboutus",
    submenu: [
      { label: "Claim your puppy", url: "/puppies" },
      { label: "Add your puppy", url: "/addaapuppy" },
    ],
  },
  { label: "Contact", url: "/contact" },
];

// Top navbar
export default function Navbar() {
  const { user, userName, role } = useContext(UserContext);

  return (
    <div className="navbar bg-neutral text-neutral-content">
      {<NavBarStart key="navbarstart" />}
      <div className="navbar-center hidden lg:flex">
        <ul className="menu menu-horizontal p-0">
          {menuItems.map((item) => (
            <NavBarItem key={`${item.label}`.replace(" ", "")} item={item} />
          ))}
        </ul>
      </div>
      {<NavBarEnd key="navbarend" user={user} />}
    </div>
  );
}```

**Comment by sarahk** [comment]
```export function NavBarItem(props) {
  console.log("NavBarItem", props);
  if (props.item.submenu) {
    return (
      <li tabIndex="0">
        <Link href="#">
          <a className="justify-between">
            {props.item.label}
            <svg
              className="fill-current"
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
            >
              <path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z" />
            </svg>
          </a>
        </Link>
        <ul className="p-2">
          {props.item.submenu.map((item) => (
            <li key={`${item.label}`.replace(" ", "")}>
              <Link href={item.url}>
                <a>{item.label}</a>
              </Link>
            </li>
          ))}
        </ul>
      </li>
    );
  }```

**Comment by saadeghi** [comment]
The only problem I see here is submenu doesn't have background color and text color.  
Everything else looks good.
Example: https://stackblitz.com/edit/daisyui-nextjs-vmlpwi?file=components/NavBarItem.jsx

**Comment by sarahk** [comment]
Yeah, that's what I'd expect. Thanks for doing that and stackblitz is new to me, looks useful. I still have this... [https://cldup.com/m7gJnyWz8J.png](url)

My tailwind config is very empty - just what I had in that first post, I've added daisyui but nothing else. 

**How do I debug this?** I normally just use inspect to see what classes are active but with tailwind there's so much in there that I've relied on the content being right so long as it was marked globals.css:3 etc. 

example inspect screenshots 
[https://cldup.com/QBvKnpYfGB.png](url)
[https://cldup.com/677OxI7yZp.png](url)

**Comment by saadeghi** [comment]
What version of daisyUI are you using?  
also please share your `tailwind.config.js`  

This would be easier if you could share your repo in the first place

**Comment by sarahk** [comment]
My tailwind config was in the "play" in the first post. I don't feel confident sharing the repo, there's some stuff we're still sorting out legally to do with the domain, trading entity that I wouldn't want "out there" just yet. Are there no other debugging tools or strategies?

**Comment by sarahk** [comment]
Hmmm, I run npm update most days but you were right, it was stuck on v1.25 for some reason. 

I've created a test at https://github.com/sarahk/daisytest

package.json now has "daisyui": "^2.13.4", but my demo is still wrong. I really appreciate your help.

**Comment by sarahk** [comment]
I've just gone and updated all the same things on my dev site and it's now working. I've discovered "npm outdated" so I've learnt something! Thanks for your help.
