### ISSUE TITLE
Date input - using 'input' class disables datepicker on Chrome (Daisy ver 2.2.0)

### ISSUE THREAD

**Issue by TomBers** [saadeghi/daisyui#662]
I am loving using DaisyUI, but I had an interesting issue recently.

Using : `"daisyui": "^2.2.0"`

I have a date input with class `input` but in Chrome on Mac the date picker widget did not appear.  Removing the class fixed the issue.

I have not got round to testing on the latest version, so hopefully it can be replicated. 

All the best.

Tom

**Comment by saadeghi** [comment]
It's fixed in 2.6.3
