### ISSUE TITLE
Table header first-child <th> is sticky by default

### ISSUE THREAD

**Issue by bherbruck** [saadeghi/daisyui#665]
The table header `first-child` `<th>` tag is sticky and has left-0 by default. I think this should be optional (maybe a new CSS class) because it doesn't work well with responsive layouts when you don't want a sticky first column.

https://github.com/saadeghi/daisyui/blob/91ef44f1814fbea969af5f1fc50886a2fe611f8d/src/components/unstyled/table.css#L3-L
![daisyui-table-header-sticky](https://user-images.githubusercontent.com/5258126/160611544-b9ef3ace-fc74-4c0a-af59-e9beaee1958d.gif)

**Comment by saadeghi** [comment]
It will look better if the first column of each row be `<th>` (not `<td>`)  
Like the examples here: https://daisyui.com/components/table/

But you're right, it would be better if being sticky was optional. I will work on it

**Comment by NikarashiHatsu** [comment]
How about adding `sticky` option for `<th>` and the first column of each row?
There are some cases where both could be used in a large data table.

**Comment by loreberti89** [comment]
> How about adding `sticky` option for `<th>` and the first column of each row? There are some cases where both could be used in a large data table.

I have solved with little override in my CSS

```
.table th:first-child {
     position: relative !important;
}
.table.sticky th:first-child {
    position: sticky !important;
    position: -webkit-sticky !important;
    left: 0px;
    z-index: 11;
}
```
Now if I want sticky I add class sticky on table

**Comment by riuci-admin** [comment]
Same issue here, in my case if I don't add an empty th and a number then it takes the first column and make it sticky when scrolling horizontally. This does not make sense. Please fix this issue, shouldn't be that hard to fix
