### ISSUE TITLE
Collapse component not fully working on mobile (iphone 11 pro)

### ISSUE THREAD

**Issue by heyjochen** [saadeghi/daisyui#671]
I am having trouble with the collapse components on mobile (tested on an iPhone 11 Pro, in Chrome). The issues are:

- When a component is open, it is shown with a border (see image attached)
- When a component is open it can't be closed

Everything works fine on desktop in Chrome. 
Is anyone able to reproduce this issue?
![Untitled](https://user-images.githubusercontent.com/94847959/160958841-8f3b6c44-a89c-45d1-b8a5-c6a851978d51.jpg)

**Comment by saadeghi** [comment]
- Which version of daisyUI are you using?  
- Which type of `collapse` are you having problem with? (the one with checkbox or without checkbox)

**Comment by AlessioToniolo** [comment]
**I am having this same issue.** In fact, I copied the code for a navbar straight off of the DaisyUI docs. 

- My environment is a SvelteKit app with TailwindCSS and Daisy UI. 
- When tested in the browser on my computer, I have no issues, however when testing this on Chrome on my mobile device, when you click on an item in the menu containing submenus, **the submenu in addition to the parent menu item is highlighted with a blue border.**
- **_My version is `2.13.6`_**
- **I also have the issue where you cannot exit out of the collapsible menu. On the browser, this can be accomplished by clicking anywhere on the page or on the hamburger.**

I am not sure if this is can be simply solved with some code or if this is an issue with the DaisyUI library's responsiveness to mobile devices. I appreciate any help you can give to me and @heyjochen, and I am grateful for this amazing library.

Below is the code: 

```html
<div class="navbar bg-base-100">
  <div class="navbar-start">
    <div class="dropdown">
      <label tabindex="0" class="btn btn-ghost lg:hidden">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" /></svg>
      </label>
      <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
        <li><a>Item 1</a></li>
        <li tabindex="0">
          <a class="justify-between">
            Parent
            <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M8.59,16.58L13.17,12L8.59,7.41L10,6L16,12L10,18L8.59,16.58Z"/></svg>
          </a>
          <ul class="p-2">
            <li><a>Submenu 1</a></li>
            <li><a>Submenu 2</a></li>
          </ul>
        </li>
        <li><a>Item 3</a></li>
      </ul>
    </div>
    <a class="btn btn-ghost normal-case text-xl">daisyUI</a>
  </div>
  <div class="navbar-center hidden lg:flex">
    <ul class="menu menu-horizontal p-0">
      <li><a>Item 1</a></li>
      <li tabindex="0">
        <a>
          Parent
          <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"><path d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"/></svg>
        </a>
        <ul class="p-2">
          <li><a>Submenu 1</a></li>
          <li><a>Submenu 2</a></li>
        </ul>
      </li>
      <li><a>Item 3</a></li>
    </ul>
  </div>
  <div class="navbar-end">
    <a class="btn">Get started</a>
  </div>
</div>
```

**Comment by Makohan** [comment]
I had same issue.

But, I have resolved by removing tabindex property.

**Comment by dgmp88** [comment]
I've also noticed this issue with [collapse with checkbox](https://daisyui.com/components/collapse/#collapse-with-checkbox). For me the border isn't an issue, but the collapse box wont close when pressed. 

I think this is a Safari problem - I've noticed the issue on a Macbook using Safari, and on an iPad in Safari. Using Chrome it works fine.

**Comment by dgmp88** [comment]
As @Makohan , removing the tabindex property fixed it. 

@saadeghi - shall I make a PR changing the docs?

**Comment by saadeghi** [comment]
Yes, I just tested on Chrome, Firefox, Safari and iOS Safari.  
And I can confirm that collapse with checkbox, should not have `tabindex` to work properly on all browsers.

@dgmp88 If you want to open a PR, there are 2 examples on docs that should be updated:  
https://github.com/saadeghi/daisyui/blob/master/src/docs/src/routes/components/collapse.svelte.md?plain=1
And you should remove `tabindex` from lines: 48, 58, 197, 207

**Comment by saadeghi** [comment]
Fixed in https://github.com/saadeghi/daisyui/pull/784 thanks to @dgmp88
