### ISSUE TITLE
Responsive modal problem

### ISSUE THREAD

**Issue by saadeghi** [saadeghi/daisyui#675]
### Discussed in https://github.com/saadeghi/daisyui/discussions/668

<div type='discussions-op-text'>

<sup>Originally posted by **bptrsn** March 30, 2022</sup>
I'm trying to use the responsive modal from https://daisyui.com/components/modal/ - the one at the bottom.
It's working on the https://daisyui.com/components/modal/ demo page but not when I copy the modal to my own html file.
I always get the modal on the bottom, unless I remove modal-bottom class.
I've tried sm/md/lg prefixes.

I'm loading daisyui/tailwind from CDN as on https://daisyui.com/docs/cdn/

Any suggestions what I'm doing wrong?</div>

**Comment by Rafath-Auvee** [comment]
Any update on this?
