### ISSUE TITLE
Try it online — tailwind play not working

### ISSUE THREAD

**Issue by braynm** [saadeghi/daisyui#680]
Hi,

First of all, amazing work! can't wait to play around with it, Thank you for making this amazing library.

I want to report, just in case you haven't seen the DaisyUI tailwind play [demo](https://daisyui.com/tailwindplay) link from the `README` isn't working:

<img width="1663" alt="Screen Shot 2022-04-02 at 10 28 46 AM" src="https://user-images.githubusercontent.com/1388366/161362352-97ccc51c-1e31-435f-9edf-ff3c6bc76dcb.png">

**Comment by saadeghi** [comment]
So you still has this issue?  
Because it works now.  
Maybe it was a temporary problem while finding the package.

**Comment by arafays** [comment]
Working for me 
![image](https://user-images.githubusercontent.com/6192554/161372555-d132a3a1-b1bd-4deb-944f-63b2e1ae29e3.png)

**Comment by saadeghi** [comment]
Yeah. it works.  
I think it was a temporary issue. Maybe from Tailwind Play or maybe a temporary issue while getting the package from npm.

**Comment by braynm** [comment]
This seems to be a browser issue. Working fine on chrome. Will report it directly to `tailwind play` repo. Thanks for your time! :)
