### ISSUE TITLE
Button component which has title square button is in circle shape

### ISSUE THREAD

**Issue by StarTrooper08** [saadeghi/daisyui#681]
Here is the SS for reference :
![image](https://user-images.githubusercontent.com/72031540/161385438-dbe0443f-39cc-47b0-9012-2791ef0ba928.png)

**Comment by saadeghi** [comment]
This is a theme-specific design for `cupcake` theme. Buttons use `--rounded-btn` CSS variable for border-radius and as you can see, everything on `cupcake` theme is rounded and circular (more than other themes). Even normal buttons are circular

**Comment by StarTrooper08** [comment]
Ok 👍,apology for noise 😅
