### ISSUE TITLE
Label is clickable with checkbox

### ISSUE THREAD

**Issue by plugza** [saadeghi/daisyui#682]
Normally if you use checkbox you can click anywhere in form-control include label.
I want to separate click behavior to just only checkbox.
I want to add more icon to click and with label.

Can I do that?

**Comment by saadeghi** [comment]
I hope I understand correctly. You want this code:
```html
<div class="form-control">
  <label class="label cursor-pointer">
    <span class="label-text">Remember me</span> 
    <input type="checkbox" checked="checked" class="checkbox">
  </label>
</div>
```
but you don't want the checkbox to change when you click the `Remember me` text.  
In that case, you can use a `<div>` instead of `<label>`
```html
<div class="form-control">
  <div class="label">
    <span class="label-text">Remember me</span> 
    <input type="checkbox" checked="checked" class="checkbox">
  </div>
</div>
```

Let me know if you have any questions

**Comment by plugza** [comment]
> I hope I understand correctly. You want this code:
> 
> ```
> <div class="form-control">
>   <label class="label cursor-pointer">
>     <span class="label-text">Remember me</span> 
>     <input type="checkbox" checked="checked" class="checkbox">
>   </label>
> </div>
> ```
> 
> but you don't want the checkbox to change when you click the `Remember me` text. In that case, you can use a `<div>` instead of `<label>`
> 
> ```
> <div class="form-control">
>   <div class="label">
>     <span class="label-text">Remember me</span> 
>     <input type="checkbox" checked="checked" class="checkbox">
>   </div>
> </div>
> ```
> 
> Let me know if you have any questions

That's do the job. Thank you!
