### ISSUE TITLE
use with shadow dom

### ISSUE THREAD

**Issue by JiangWeixian** [saadeghi/daisyui#687]
I want to use it in my chrome webext project. Here is my content-script to apply styles

```ts
const container = document.createElement('div')
const root = document.createElement('div')
const styleEl = document.createElement('link')
const shadowDOM = container.attachShadow?.({ mode: __DEV__ ? 'open' : 'closed' }) || container
container.className = 'repo-stack'
styleEl.setAttribute('rel', 'stylesheet')
styleEl.setAttribute('href', browser.runtime.getURL('dist/contentScripts/style.css'))
shadowDOM.appendChild(styleEl)
shadowDOM.appendChild(root)
document.body.appendChild(container)
render(<App />, root)
```

It will looks like this

<img width="386" alt="image" src="https://user-images.githubusercontent.com/6839576/161563705-16a4e58a-e4d6-401a-a6cc-fd65cb6e1ff8.png">

However, the CSS variables from daisyui is on `:root`, so component UI is broken. Is there anyway to fix this...

**Comment by Sleepful** [comment]
I did not find it necessary to add the `data-theme` attribute to the shadow dom, css variables work fine inside shadow dom. Therefore, an approach [like this one](https://github.com/saadeghi/daisyui/discussions/1293#discussioncomment-4480406) works very well.
