### ISSUE TITLE
css from components list won't apply

### ISSUE THREAD

**Issue by viccabezos** [saadeghi/daisyui#690]
hi! sorry for using the issue section to ask this, i have a problem and can't find why, i am doing a project on Nextjs, tailwind is working, daisy seems to work on buttons and code that i copy from the playground test https://play.tailwindcss.com/gTlq3iys55. 

but the rest of the components from the list like : https://daisyui.com/components/drawer/ 

just will show a broken css => https://pasteboard.co/RYAg71VS0Umf.png

ive tried few other components, and as you can see from the example, the ones coming from playground will work, the ones coming from the components won't. i have fixed the css class to className already aswell.... i don't really understand :/ 

Thanks no anyone that could take 2 minutes to have a look at this

**Comment by saadeghi** [comment]
Do you have the path of all your template files (js, jsx, etc...) inside `content` object in `tailwind.config.js` file?  
Here's an example: https://stackblitz.com/edit/daisyui-nextjs?file=tailwind.config.js  
All your pages and components should be listed there.

**Comment by saadeghi** [comment]
Config looks good to me 🤔  
Can you provide a sample repo so I can reproduce the issue and see what's wrong?

**Comment by viccabezos** [comment]
sure, https://github.com/viccabezos/impromptus  txs so much

**Comment by saadeghi** [comment]
@viccabezos I will look into it today

**Comment by viccabezos** [comment]
okay ^_^ thank you

**Comment by saadeghi** [comment]
In `tailwind.config.js` you have this:
```js
content: [
  "./pages/**/*.{js,ts,jsx,tsx}",
  "./components/**/*.{js,ts,jsx,tsx}",
],
```
But all your template files are not in `/pages` and `/components`. Your navbar is in `/layout`
So you should add that one too:
```js
content: [
  "./pages/**/*.{js,ts,jsx,tsx}",
  "./components/**/*.{js,ts,jsx,tsx}",
  "./layout/**/*.{js,ts,jsx,tsx}",
],
```

**Comment by viccabezos** [comment]
it worked! thank you so much!
