### ISSUE TITLE
bug: docs homepage hero features icon

### ISSUE THREAD

**Issue by ronakmistrydev** [saadeghi/daisyui#693]
First of all thanks making such a great open source project. its awesome work. This bug happens because of the size of carbon ad. 

I have already fixed this by adding `flex-none` on each icons. 

<img width="500" alt="Screen Shot 2022-04-07 at 10 01 53 PM" src="https://user-images.githubusercontent.com/26488456/162355297-943be45b-6af2-459a-ba19-197170dc121a.png">

<img width="500" alt="Screen Shot 2022-04-07 at 10 02 18 PM" src="https://user-images.githubusercontent.com/26488456/162355308-8b4f7655-8f60-43be-9fc4-b70b8e46cb92.png">

## *file - src/docs/src/components/homepage/Hero.svelte*

```
<div class="flex gap-2">
    <svg 
       width="20" 
       height="20" xmlns="http://www.w3.org/2000/svg" 
       fill="none" 
       viewBox="0 0 24 24" 
       class="flex-none inline-block h-6 w-6 stroke-current"
   >
     <path 
         stroke-linecap="round" 
         stroke-linejoin="round" 
         stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" 
     />
   </svg>
   {$t("feat-1")}
</div>
```

**Comment by saadeghi** [comment]
The ad on your first screenshot has no style and that's not okay.  
How can I reproduce that?

**Comment by ronakmistry36** [comment]
yeah,  in order to reproduce it 

instead of this 

```
<div>
   <Ads slot="carbon1" />
</div>
```

apply this,

```
<div>
   <div class="w-[40rem] h-[8rem]" />
</div>
```

It wasn't every time, but whenever the ad size is bit bigger it breaks the icons.
