### ISSUE TITLE
Tabs with Radio Control

### ISSUE THREAD

**Issue by MentalGear** [saadeghi/daisyui#695]
I was wondering if tabs could also be controlled via the Radio Input. This would avoid having to put in an extra controller just for the switching. Thank you.

**Comment by saadeghi** [comment]
You mean switching tab content without JS?

**Comment by MentalGear** [comment]
Yes, like it is in the guide for the Button Group:
https://daisyui.com/components/button-group/

```html
<div class="btn-group">
  <input type="radio" name="options" data-title="1" class="btn">
  <input type="radio" name="options" data-title="2" class="btn" checked>
  <input type="radio" name="options" data-title="3" class="btn">
  <input type="radio" name="options" data-title="4" class="btn">
</div>
```

**Comment by gotjoshua** [comment]
> switching tab content without JS?

is there an example somewhere of your recommended usage for tabs?

**Comment by gotjoshua** [comment]
> controlled via the Radio Input.

indeed it is possible:
https://github.com/saadeghi/daisyui/discussions/577#discussioncomment-3382031

**Comment by saadeghi** [comment]
Here's another example:  
https://play.tailwindcss.com/IlSZ3DVeUT?file=css
```css
:where(.tabs input[type=radio]:checked+label){
  @apply tab-active;
}
```
```html
<div class="tabs m-10">
  <input type="radio" class="hidden" name="options" id="option-1" checked />
  <label for="option-1" class="tab tab-lifted">Tab 1</label>
  
  <input type="radio" class="hidden" name="options" id="option-2" />
  <label for="option-2" class="tab tab-lifted">Tab 2</label> 
  
  <input type="radio" class="hidden" name="options" id="option-3" />
  <label for="option-3" class="tab tab-lifted">Tab 3</label>
</div>
```

**Comment by gotjoshua** [comment]
Yes but this example doesn't have content. Do you know a way to also show content with pure css?
