### ISSUE TITLE
bg-neutral with night theme

### ISSUE THREAD

**Issue by yudaprama** [saadeghi/daisyui#696]
`bg-neutral` with `default` theme looks good:
![image](https://user-images.githubusercontent.com/33281225/162551390-2ba438d8-0ca7-456d-b011-0ed8a93047a4.png)

`bg-neutral` with `dark` theme looks good:
![image](https://user-images.githubusercontent.com/33281225/162551427-c6752ddf-26a9-48cd-936b-614c7ccdc747.png)

`bg-neutral` with `night` theme looks weird:
![image](https://user-images.githubusercontent.com/33281225/162551454-a2254435-f5cf-4a7e-a650-f6adc601922c.png)

**Comment by saadeghi** [comment]
Each color has a `*-content` color with the best contrast.  
If you use `bg-primary`, also use `text-primary-content` with it.  
If you use `bg-neutral`, also use `text-neutral-content` with it.  
This will guarantee all your background+foreground color combinations to have a good contrast.  

Example:  
https://play.tailwindcss.com/jTcA9jepZf  

You can also see the preview of all foreground+background colors of all themes on this page:  
(see text color and background colors of `A` letters)   
https://daisyui.com/docs/themes/
