### ISSUE TITLE
Add additional colors to textarea component

### ISSUE THREAD

**Issue by akhil-gautam** [saadeghi/daisyui#70]
Similar to Form-Input, it would be nice if `textarea` supports various colors like `primary, secondary, etc..`.
@saadeghi Let me if I can help. It might be just a matter of pasting in [here](https://github.com/saadeghi/daisyui/blob/master/src/components/styled/textarea.css)😄

**Comment by saadeghi** [comment]
I will add them today.  
Thanks 👍

**Comment by saadeghi** [comment]
Fixed. Please update to latest version
