### ISSUE TITLE
DaisyUI's card class realigns whole webpage by a couple of pixles. Cannot use card components because of it.

### ISSUE THREAD

**Issue by Sagefully** [saadeghi/daisyui#707]
When going to a sub-page within my local website that is not using the component with the class: card, it jumps back to the position it should be in:

#1 is with Cards class

#2 is without cards class

![Screenshot 2022-04-12 at 14-06-05 Screenshot](https://user-images.githubusercontent.com/87486272/162959066-2ce812e6-4fd3-46b0-87f0-c6ee26ec0389.png)
![Screenshot 2022-04-12 at 14-05-56 Screenshot](https://user-images.githubusercontent.com/87486272/162959068-c433ad68-24f4-443a-842a-250287e70c62.png)

**Comment by saadeghi** [comment]
card does not (and can not) affect the page layout at all.  
I'm not sure I understand the issue you described...  

Can you provide an example repo where I can see your code?

**Comment by Sagefully** [comment]
Try this: https://test-ten-ebon.vercel.app/

**Comment by Sagefully** [comment]
@saadeghi I updated my text in above post.

Any ideas?

**Comment by saadeghi** [comment]
I'm still not sure what is the issue.  
Here's a video, where I go to Kontakta page and go back to homepage:

https://user-images.githubusercontent.com/7342023/163146075-3741d4ca-7224-42ad-96fb-733e53f68e83.mp4

However whenever I refresh the page, there's a new image with a different size, and that's because of the random image generator API ([lorem.space](https://lorem.space/)) and each image have a different size. If you use a fixed size for image there would be no jump.

**Comment by Sagefully** [comment]
Thanks

Med vänliga hälsningar,
Max Lundell
________________________________
Från: Pouya Saadeghi ***@***.***>
Skickat: den 13 april 2022 11:33
Till: saadeghi/daisyui ***@***.***>
Kopia: Sagefully ***@***.***>; Author ***@***.***>
Ämne: Re: [saadeghi/daisyui] DaisyUI's card class realigns whole webpage by a couple of pixles. Cannot use card components because of it. (Issue #707)


I'm still not sure what is the issue.
Here's a video, where I go to Kontakta page and go back to homepage:

https://user-images.githubusercontent.com/7342023/163146075-3741d4ca-7224-42ad-96fb-733e53f68e83.mp4

However whenever I refresh the page, there's a new image with a different size, and that's because of the random image generator API (lorem.space<https://lorem.space/>) and each image have a different size. If you use a fixed size for image there would be no jump.

**Comment by saadeghi** [comment]
I'm closing this.  
If you needed help, let me know

**Comment by Sagefully** [comment]
Do you know why my website shifts? I am a noob that wants to learn how to control it :D
Struggling with this now as we speak
@saadeghi

**Comment by saadeghi** [comment]
If mean the shift when the image loads, that's because you're image doesn't have width and height.
