### ISSUE TITLE
add new color names `[colorname]-muted` for content with lower opacities

### ISSUE THREAD

**Issue by saadeghi** [saadeghi/daisyui#71]

**Comment by dumptyd** [comment]
Hello, I was wondering if this was ever added, I couldn't find a class for it. 😄

**Comment by dumptyd** [comment]
For now, I'm combining text-* classes with opacity-* to get the same-ish behavior.

**Comment by kurtome** [comment]
@saadeghi Can you add this to the docs? I was also looking for something similar to Bootstrap's `text-muted`, https://getbootstrap.com/docs/4.0/utilities/colors/. Especially something that I could be sure would work in both dark and light themes

**Comment by saadeghi** [comment]
@kurtome Bootstrap's `muted` color is a normal text color with more brightness.  

The problem with bootstrap's muted color is:
- `muted` color should not always be a text with more brightness. It should be a mix of background color and normal text color so it will look goon on every background color
- we need to define a new `muted` color for each theme
- we have no control on the level of brightness for the text color we will only have one "muted" class
- we might need multiple levels of text brightness on our content which would't be possible unless we add multiple brightness levels like `muted-100`, `muted-200`, etc...

So having one `muted` color won't fix the problem. Instead, by controlling the opacity, we can achieve the same result while having full control on the color.  
Here you can see the difference between brightness and opacity and how it will look like on background colors:  
https://play.tailwindcss.com/d6nruycay4  

In the future we can mix the foreground color and background color using [CSS color-mix()](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix()) to get a good color result for a `muted` text on all backgrounds but for now, browsers are not supporting this CSS function so I think currently, using text opacity is the safest solution

**Comment by kurtome** [comment]
> So having one `muted` color won't fix the problem. Instead, by controlling the opacity, we can achieve the same result while having full control on the color. Here you can see the difference between brightness and opacity and how it will look like on background colors: https://play.tailwindcss.com/d6nruycay4

Thanks! I'll add this utility to my css for use in my project:

```css
.text-muted {
    @apply text-base-content/50;
}
```
