### ISSUE TITLE
DaisyUI does not support Tailwind JIT

### ISSUE THREAD

**Issue by AsyncBanana** [saadeghi/daisyui#72]
When Tailwind JIT mode is on (using `mode: 'jit'` in `tailwind.config.cjs`), DaisyUI does not do anything. This does not happen when Tailwind is set to the default mode.
**Versions**
Tailwind: `2.1.2`
DaisyUI: `1.2.0`

**Comment by saadeghi** [comment]
Well... That's not true.
Here you can see it works both in dev and production env:  https://github.com/saadeghi/daisyui-starter  
The issue must be from somewhere else 🤷‍♂️
