### ISSUE TITLE
Custom colors do not show in production build

### ISSUE THREAD

**Issue by nolafs** [saadeghi/daisyui#720]
Hi,

Very strange behaviour. I added small number of colors for the social media buttons. Works perfectly fine during development but when build for production, the live build css has no record of those colors.

```
theme: {
        colors: {
            "facebook" :  "#1877f2",
            "twitter" : "#1da1f2",
            "linkedin" : "#0077b5",
            "neutral-100" : "#1d1480"
        },
```
Local: 

![local](https://user-images.githubusercontent.com/8676371/163587342-ef40fdb0-eb34-4325-a253-dc6116d56c6a.png)

Live: 

![live](https://user-images.githubusercontent.com/8676371/163587382-0333790f-02d0-4391-a4ea-4706c66bc9ba.png)

**Comment by saadeghi** [comment]
Can you share a repo so I can reproduce this issue?

**Comment by nolafs** [comment]
Hi,

Thanks for getting back to me. I realised that I am interpolate the class name. When building the production version, it would not include those colours.  My mistake. 

cheers
Olaf
