### ISSUE TITLE
The input looks ugly

### ISSUE THREAD

**Issue by skyboy2020** [saadeghi/daisyui#722]
The input looks ugly because he is two boders, which is very distracting. How can it be changed to a boder so that people can concentrate like normal input。

**Comment by saadeghi** [comment]
Input does not have border by default. But if you use `input-bordered` it will have border.  
Regardless of the border, when input is focused, it gets an `outline` and if you don't like that, you can disable it by adding `focus:outline-none`

Example: https://play.tailwindcss.com/tCFmd4r6gW
