### ISSUE TITLE
Defined and displayed colors are not the same

### ISSUE THREAD

**Issue by akkie** [saadeghi/daisyui#727]
There is an issue with the colors that are defined and the colors that are displayed. They are not the same. As example if I define the color #a5b4fc (165, 180, 252) then it's displayed as #a6b4fc (166, 180, 252). I can reproduce that with all colors in the theme generator as example. It's always the first RGB value which is one step greater than defined.

I have tested that with Tailwind directly and there is no issue. Colors are the same. So it seems that the issue is in daisyui.

**Comment by saadeghi** [comment]
This is fixed already.
