### ISSUE TITLE
Issue with rounded button groups with elements that are not buttons

### ISSUE THREAD

**Issue by pjotrsavitski** [saadeghi/daisyui#731]
In case a button group contains elements that are not of the same type, rounded corners are applied to inner elements of the group. An example could be a button, then a link, then another button. This change breaks the visuals. Maybe it would be possible to have a different class to keep the behavior consistent with what it used to be.

https://github.com/saadeghi/daisyui/blob/aca92dc2c4f5bd534af67933a859ab745f6d0d26/src/components/styled/button.css#L218

**Comment by divyashC** [comment]
@saadeghi can you assign me this issue?

PS: I wanted to try contributing to daisyUI as this is one of the best tool I've discovered till now. And this will be my first public contribution to open source on github.

**Comment by saadeghi** [comment]
This issue was fixed: https://play.tailwindcss.com/KosvPM6mjk  
I just forgot to close it. Sorry.  

@divyashC Thank you very much. Maybe start with another issue 😁
