### ISSUE TITLE
Border radius on rounded menu items not applied when using prefix

### ISSUE THREAD

**Issue by camslice** [saadeghi/daisyui#733]
According to the documentation, all that is required to apply a border radius to menu items is to add `p-*` and `rounded-box` to the parent `ul.menu` element.  This does not appear to work when using a prefix.

Not working with a prefix: https://play.tailwindcss.com/kWLnz6C0gj

Working without a prefix: https://play.tailwindcss.com/Ug9j9FSzoH

Probably a job for @vnphanquang :)

**Comment by saadeghi** [comment]
I had to come up with a rule to dynamically add radius to the menu items if the menu had paddings, this is not ideal but for now I'm checking if the menu has `p-*` class: `[class^="p-"]`  
I wish there was a better way to detect that. For now, a workaround would be having `p-2 r-p-2` (where `r-` is your prefix)

**Comment by camslice** [comment]
Ah yep, doubling up with `r-p-2` works thanks.  I wonder if there's a better solution...

**Comment by saadeghi** [comment]
@vnphanquang It's probably a temporary issue while getting the package from npm. Sometimes happens with Tailwind Play. Does the problem still exist?

**Comment by vnphanquang** [comment]
@saadeghi working fine in Chrome but not Firefox. I did some test just now with Tailwind Play and in Firefox, it stopped working from `^daisyui@2.3.0`, which was when we introduced the `prefix` feature. Very strange, something else to look into...

**Comment by saadeghi** [comment]
Created a new issue for that #734

**Comment by nahtnam** [comment]
Tangentially related, I noticed that if you have a one-item rounded menu, and hover on it, it is not rounded on the top:
![image](https://user-images.githubusercontent.com/20051852/166872609-09c8718e-3732-4c84-80ac-4bab014ef0ed.png)

Let me know if I should create another issue for this

**Comment by vnphanquang** [comment]
@nahtnam it could be related, can you share the markup that renders to that and if any workaround you've found? Thanks

**Comment by saadeghi** [comment]
@nahtnam @vnphanquang This is a different issue and is not related to prefix.  
https://play.tailwindcss.com/7Je92jySrB

I created a new issue here: https://github.com/saadeghi/daisyui/issues/778
