### ISSUE TITLE
Content doesn't fit badge indicator

### ISSUE THREAD

**Issue by Vermorxt** [saadeghi/daisyui#736]
The content of indicator for images doesn't fit the badge: 

[https://daisyui.com/components/indicator/#in-center-of-an-image](https://daisyui.com/components/indicator/#in-center-of-an-image)

<img width="928" alt="Bildschirmfoto 2022-04-21 um 16 29 48" src="https://user-images.githubusercontent.com/22641208/164480729-5f9e5e8d-7757-4c83-885b-b9696c6da9f3.png">

Don't have time to make a PR, but a possible fix might be:

`width: max-content;` for .badge css class. 

Nice work  btw. I really like the framework. :o)

Cheers ...

**Comment by TheophileMot** [comment]
The issue is closed, but the example in question is still broken (see the "uploading images" example at https://daisyui.com/components/indicator/).

What about doing this?
```
.badge {
  /* height: 1.25rem; */
  height: fit-content;
  min-height: 1.25rem;
}
```
