### ISSUE TITLE
After I installed DiasyUI in large project with NuxtJS I got ERROR (Javascript heap out of memory)

### ISSUE THREAD

**Issue by MuhammadMoftah** [saadeghi/daisyui#737]
After I installed **DiasyUI** in large project with **NuxtJS** I got ERROR (**JavaScript heap out of memory**)
like every 15 mints
and I should do **yarn dev** the project again 

any help !

**Comment by saadeghi** [comment]
Make sure you're using the latest version of Nuxt.js
Here's an example repo: https://stackblitz.com/edit/daisyui-nuxtjs

**Comment by saadeghi** [comment]
let me know if you have any questions

**Comment by MuhammadMoftah** [comment]
yeah I used it with Nuxt V2, not Nuxt V3,
I can't switch to nuxt3 now

**Comment by MuhammadMoftah** [comment]
I put it here because it's only happened when I install DaisyUI in my project, but ok I'm gonna ask at Nuxt Repo

Thanks!
