### ISSUE TITLE
Feature Suggestions: vertical button-group, vertical tabs

### ISSUE THREAD

**Issue by arunstop** [saadeghi/daisyui#738]
Hello there! First of all, what an awesome project you have built here! Saved me a lot of times. Thank you!

Amazed by how amazing and simple the components are. It can only get better. For example the additions of : 

- vertical button-group 
- vertical tab (e.g : https://vuetifyjs.com/en/components/tabs/#vertical-tabs)

**Comment by zfranco55** [comment]
or as it was in fact sveltestrap:
https://sveltestrap.js.org/?path=/story/components--tabs

**Comment by ptfw** [comment]
@saadeghi how does one make a btn-group vertical? it would seem you added that feature based on this Issue, but it is not in documentation. I tried `btn-group-vertical` but that did not do it.

**Comment by saadeghi** [comment]
@ptfw this issue is still open. We don't have vertical group yet.

**Comment by ptfw** [comment]
ah, yes. sorry. you simply added labels to the issue... I will keep track of this issue. THANK YOU!

**Comment by saadeghi** [comment]
`btn-group-vertical` [added](https://github.com/saadeghi/daisyui/pull/863) in daisyUI `2.17.0` 🎉  
However, "vertical tabs" would look a lot like [`menu`](https://daisyui.com/components/menu/) and there wouldn't be much differences.
