### ISSUE TITLE
Input tags missing closing slashes

### ISSUE THREAD

**Issue by claysam75** [saadeghi/daisyui#739]
I have found that in multiple component types which use <Input/> tags, the closing / is missing, causing errors when the provided html is copied into VSCode. 

For example, from the Text Input component - 
```
<input type="text" placeholder="Type here" class="input w-full max-w-xs">
```
Proposed fix - 
```
<input type="text" placeholder="Type here" class="input w-full max-w-xs"/>
```
Happy to have this assigned to me and I'll go through and add where required.

**Comment by saadeghi** [comment]
Sure!
