### ISSUE TITLE
How to controll step height?

### ISSUE THREAD

**Issue by wick3ds0ul** [saadeghi/daisyui#742]
Hi I am trying to use steps in multi step form, using tailwind css and daisy ui.

```html

      <div className="grid grid-cols-12  gap-4">
        <div className="col-span-10 grid">
         ....
       </div>
         
        <ul className="steps steps-vertical col-span-2">
          <li className="step step-primary">Basic Details</li>
          <li className="step">Add image</li>
          <li className="step">Confirmation</li>
        </ul>
      </div>
```
<img width="547" alt="Screenshot 2022-04-22 at 10 27 45 PM" src="https://user-images.githubusercontent.com/48680692/164773783-9bc5ffc6-41db-426a-8756-3d0d9e2a155f.png">
They are showing up evenly by default.
I am trying to adjust the adjust the height of `1`, `2` and `3`, so they look like the above image.
I tried using tailwind grid rows. It breaks the steps.

```html

    <ul className="col-span-2 steps steps-vertical  grid grid-rows-6">
          <li className="step step-primary row-span-4">Basic Details</li>
          <li className="step step-primary row-span-1">Add image</li>
          <li className="step row-span-1">Confirmation</li>
        </ul>
```

<img width="279" alt="Screenshot 2022-04-23 at 12 07 39 AM" src="https://user-images.githubusercontent.com/48680692/164774514-b231efd1-135d-4e22-9e6d-030a88a688cb.png">

**Comment by saadeghi** [comment]
Grid cells should be aligned evenly because the progress line from `step 1` to `step 2` is the `:before` of `step 2` (because if `step 2` is `primary` the line from `step 1` to `step 2` should be that color)  
And the line has 100% height, If `step 1` is larger than others, the `:before` of `step 2` wouldn't have any idea about its height.

So I don't have any solution for making it work for uneven heights yet...  
But, you can do something like this:
```css
<ul class="steps steps-vertical">
  <li class="step step-primary">Basic Details</li>
  <li class="step step-primary after:!hidden"></li>
  <li class="step step-primary after:!hidden"></li>
  <li class="step step-primary">Add image</li>
  <li class="step">Confirmation</li>
</ul>
```
Some rows without circle.

**Comment by saadeghi** [comment]
let me know if you have any questions

**Comment by wick3ds0ul** [comment]
This works
<img width="191" alt="Screenshot 2022-04-24 at 2 08 20 AM" src="https://user-images.githubusercontent.com/48680692/164945319-28b02012-6dd8-4785-b1b4-6aa2bcadbeff.png">
