### ISSUE TITLE
Can I hide a drawer-button when drawer is showing.

### ISSUE THREAD

**Issue by hidekatsu-izuno** [saadeghi/daisyui#744]
I have a question.
I make a web site on a drawer based layout. I want to hide a drawer-button when a drawer is showing.
Is there any way I can do this ?

**Comment by saadeghi** [comment]
doing this with CSS only would be an ugly an unstable code so I would suggest using JS.
Bind the value of checkbox to a JS state and show/hide the button based on the value of state.

**Comment by hidekatsu-izuno** [comment]
Thank you for your answer. I will try to use a checkbox click event.

**Comment by saadeghi** [comment]
Not the click event. You should observe the change event. Or if you're using a framework, bind the value of checkbox.
