### ISSUE TITLE
Issue: When focussing input, drawer overflows

### ISSUE THREAD

**Issue by NathanTe** [saadeghi/daisyui#746]
Hey, 
I don't know if it's my personal styling or the one from daisyui but when I hover an input it overflows my drawer.
Hope you guys will be able to help me 😞 

[![Image from Gyazo](https://i.gyazo.com/1d92e5ea47661ed130c4b0d91b485623.gif)](https://gyazo.com/1d92e5ea47661ed130c4b0d91b485623)

**Comment by NathanTe** [comment]
giving my shopping cart component a w-80 fixed it

**Comment by saadeghi** [comment]
I don't think the issue is from daisyUI because elements neither change their size on hover or change their border/margin size (by default)
