### ISSUE TITLE
Multiple drawers

### ISSUE THREAD

**Issue by Loosie94** [saadeghi/daisyui#750]
Hi guys,

Really like the updated drawer component!
I was only wondering if it's possible to have multiple drawers in 1 project.
I currently have 1 drawer for the menu, and now want a second one to trigger for some additional information on a website.
I don't think this is possible at the moment, because of the class names? Or am I doing something wrong here?

Thanks, and keep up the good work! :)

**Comment by saadeghi** [comment]
See this discussion: https://github.com/saadeghi/daisyui/discussions/709
