### ISSUE TITLE
The example "Activate using class name instead of checkbox" does not work

### ISSUE THREAD

**Issue by rpayanm** [saadeghi/daisyui#759]
This example is not working:

https://daisyui.com/components/swap/#activate-using-class-name-instead-of-checkbox

**Comment by saadeghi** [comment]
It's showing the correct content based on the `swap-active` class name. Take a look at the code:
```html
<label class="swap text-6xl">
  <div class="swap-on">🥵</div>
  <div class="swap-off">🥶</div>
</label>
<label class="swap swap-active text-6xl">
  <div class="swap-on">🥳</div>
  <div class="swap-off">😭</div>
</label>
```
and you can see for the first `swap`, `swap-off` is visible. for the second one, `swap-on` is visible because it's active.

**Comment by msh2050** [comment]
It will be better to add a button or a click event to show how we can swap.

**Comment by rpayanm** [comment]
I agree with @msh2050
