### ISSUE TITLE
Docs Request - Store Prefix in LocalStorage

### ISSUE THREAD

**Issue by nahtnam** [saadeghi/daisyui#763]
Hey,

I love that there's a little text box to set the prefix for the class names. However, I noticed that on refresh, it gets reset. It would be nice if it was persisted in localStorage so that it remains until the textbox is cleared.

**Comment by saadeghi** [comment]
I'm not sure about this 😕 
I'm afraid that someone adds a prefix just to play around, and then, days later they want to copy/paste class names for some other project and it would be confusing to permanently have a prefix.

**Comment by nahtnam** [comment]
That's true, alternative solutions would be:

1. Check for a query param `?prefix=...` and when you open other tabs or links in new tabs it persists the prefix in the query param. Still a similar problem to what you proposed but at least it would be obvious
2. Add support for localStorage BUT no way to set it. Only advanced users would go and manually set the prefix. Maybe documented as an easter egg

Either way, just suggestions, its a small enough issue that it's not worth overthinking

**Comment by saadeghi** [comment]
I just want to avoid confusions.  
Currently the prefix value will remain (in store) while navigation through pages. So the only problem is when you close the site and open it again later.  
I think if you want to keep the prefix value, it's better to keep the site open, or if you close it, just re-enter the value on the next visit. It's just typing a few characters and wouldn't take any time 🤷‍♂️
