### ISSUE TITLE
How to trigger the tooltip in daisyui

### ISSUE THREAD

**Issue by eroist** [saadeghi/daisyui#771]
Daisy UI is really powerful set UI components.
but I got some issue with tooltip.
how to trigger the tooltip component after click the button?

**Comment by saadeghi** [comment]
Tooltip has a class name and a data attribute:
```html
<div class="tooltip" data-tip="hello">
```
So you can add/remove the `tooltip` class name or `data-tip` attribute when something is clicked.

The way you should handle click event depends on the JS framework you use of course.
