### ISSUE TITLE
Triggering button hover state on group hover? 

### ISSUE THREAD

**Issue by k1sul1** [saadeghi/daisyui#772]
I've tried googling to no avail, sorry in advance if this is already documented somewhere.

I have a list of blog posts that use the `card` class. Inside is a button. The whole card works as a link, but design states that there must also be a button.

However, I can't seem to figure out the proper way to put the button in the hover state. I tried addind a `group` class to the card and `group-hover` to the button, expecting it to work, but nah. I can only get the hover / active state to trigger using devtools or by hovering the actual button.

![image](https://user-images.githubusercontent.com/2719615/166252771-43d127d9-c54d-45cb-8adc-e7316fd644f0.png)

Is `.btn.group-hover { transform: translateY(-.25rem); }` my only option?

**Comment by saadeghi** [comment]
When button is hovered, it's mostly the change of background color. For example, `btn-primary` has `bg-primary` background color and when it's hovered, it has `bg-primary-focus` (see the [table of all color names](https://daisyui.com/docs/colors/) to learn more)

So if you want the button to get a hover style when card is hovered, you can use `group-hover:bg-primary-focus`  
https://play.tailwindcss.com/j2nAbk08uV

Let me know if you have any questions

**Comment by k1sul1** [comment]
Thank you! That solves my problem.
