### ISSUE TITLE
Full width Navbar with toggable drawer

### ISSUE THREAD

**Issue by xstmjh** [saadeghi/daisyui#773]
Hi, thanks for the great work.

Got a question about the setup for a drawer included layout. From the documentation, I understand that navbar, content, and footers are grouped into one pieces inside the drawer-content container. This makes it impossible to have a full-width navbar at all times as it scales with everything except the drawer. Please see the picture below for better demo. 

To summarize, it seems very hard to have a full width navbar and the drawer at the same time with the current drawer configurations.

Thank you!

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/5315814/166449748-acb99f69-057f-4e84-a5a8-4f958e3b487a.png">

**Comment by msh2050** [comment]
you can do that very easy... by making the navbar and the footer out of the drawer.
```svelte
<Navbar />
<Drawer />
<Footer />
```
then on the style, you need the change the height of the drawer (submit the height of the footer and navbar form total)

```css
height: calc(100vh - theme('spacing.20'));
```

where spacing.20 is the sum of navbar and footer height

**Comment by xstmjh** [comment]
> you can do that very easy... by making the navbar and the footer out of the drawer.
> 
> ```svelte
> <Navbar />
> <Drawer />
> <Footer />
> ```
> 
> then on the style, you need the change the height of the drawer (Subtract the height of the footer and navbar form total)
> 
> ```css
> height: calc(100vh - theme('spacing.20'));
> ```
> 
> where spacing.20 is the sum of navbar and footer height

Ah, I see what you mean. Somehow I was confused that I thought drawer is a full page container that everything needs to go into the drawer. Your explaniation makes perfect sense. Thanks!

**Comment by kkharji** [comment]
I'm trying to reproduce that unfortunately I'm get no where. So far I got the navbar to be at the top but the content area is blur, the navbar isn't sticky as with drawer hidden

```jsx
const App = () =>
  <>
    <Header />
    <div class="drawer">
      <input id="main-drawer" type="checkbox" class="drawer-toggle" checked={true} />
      <div class="drawer-content flex flex-col">
        <div class="flex-grow">
          <Routes>
            <FileRoutes />
          </Routes>
        </div>
      </div>
      <div class="drawer-side">
        <label for="main-drawer" class="drawer-overlay" />
        <ul class="menu p-4 overflow-y-auto w-80 bg-base-100">
          <For each={navigation.sideMenu}>
            {(info) => <NavLink {...info} />}
          </For>
        </ul>
      </div>
    </div>
    <Footer />
  </>
```

Basically it's

```html
<Navbar />
<Drawer />
<Footer />
```
