### ISSUE TITLE
Suggestion Multi range slider

### ISSUE THREAD

**Issue by eroist** [saadeghi/daisyui#774]
daisyui has awesome components! 😊😊😊
but can we have a multi range slider that is similar to range component.
![image](https://user-images.githubusercontent.com/97012368/166502788-ac3bcf05-ceb2-4735-b6c2-a6969014f141.png)

**Comment by saadeghi** [comment]
See this please: https://github.com/saadeghi/daisyui/issues/573#issuecomment-1064453159
