### ISSUE TITLE
Docs: Update Nuxt 3 starter

### ISSUE THREAD

**Issue by Atinux** [saadeghi/daisyui#775]
Beautiful work on DaisyUI ❤️ 

I forked and updated the Nuxt 3 starter to use the TailwindCSS module and simplify as much as possible 😊 

https://stackblitz.com/edit/daisyui-nuxtjs-svr578?file=app.vue

**Comment by saadeghi** [comment]
Hey Sébastien,
Thanks for the update.  
I replaced the link with the new one 👍

**Comment by Atinux** [comment]
Seems not updated on https://daisyui.com/docs/install/ 🤔

**Comment by saadeghi** [comment]
Yeah... I didn't check after deploy. 
Fixed now. Thanks!
