### ISSUE TITLE
Table with strange behavior

### ISSUE THREAD

**Issue by iagocavalcante** [saadeghi/daisyui#78]
When i use table it takes the dark theme from the browser automatically, but i don't want this happen, how to fix this ?

**Comment by saadeghi** [comment]
@iagocavalcante If you add `data-theme=light` to your `<html>` or container element, it forces everything inside to use light theme.
But if you want your page to use dark theme and you want only your table to use light theme, you can add `data-theme=light` to the table.  
You can do this with other themes and other elements too.  

Please let me know if you have any questions.
