### ISSUE TITLE
class .modal-box will cover the modal in the other modal

### ISSUE THREAD

**Issue by doukai** [saadeghi/daisyui#787]
it's happens in scenarios where multiple modal are nested, I think this is a problem

**Comment by saadeghi** [comment]
I'm not sure how you're using it, but there's no need to nest modals in the HTML. You can have modals` markup next to each other and open/close them whenever you need.  

Example of 3 modals, where `modal-2` opens by clicking on a button in `modal-1` and `modal-3` opens by clicking a button in `modal-2`:  
https://play.tailwindcss.com/xHSr48WOzm

Let me know if you need help.

**Comment by doukai** [comment]
thank you for your reply
but sometimes for example：I have a table in modal, each row has its own modal to edit detail
That's the kind of situation I'm talking about

**Comment by saadeghi** [comment]
I think in this situation it's better to have 1 modal and for all rows and dynamically change the content using JS. Otherwise there would be a lot of duplicate HTML for modals.

**Comment by saadeghi** [comment]
However if you want to have duplicate modals for every row, it's still possible with daisyUI. But you need to put modals next to each other.

**Comment by doukai** [comment]
very thankful
