### ISSUE TITLE
Menu dropdown doesn't click throught

### ISSUE THREAD

**Issue by ctwhome** [saadeghi/daisyui#79]
First of all, thanks for this fantastical and beautiful job you are doing. As a matter of feedback, I am not able to use the menu dropdowns to trigger click events because the menu closes before (with vuejs)

do you have a specific way to make the menu items triggering a method?

```html
<div class="dropdown">
      <div tabindex="0" class=" btn" @click="openMenu">
        Menu
      </div>
      <div class="shadow menu dropdown-content bg-base-100 w-72 h-72 overflow-y-auto">
        <div
          v-for="(exchange, i) in ccxtExchanges"
          :key="i"
          class="flex mb-2 p-2 hover:bg-gray-100 transition cursor-pointer"
          @click="$emit('on-row-selected', item)"
        >
          <img :src="logo" class="mr-1">
          {{ name }}
        </div>
      </div>
    </div>
```

**Comment by saadeghi** [comment]
Thanks.  
If you want to have clickable items inside dropdown, you need to add tab index (like `tabindex="0"`) to that element.

Reason: this dropdown works with CSS :focus. When we click the button, the menu gets focus but as soon as we click a div (that is not focusable) the menu will lose the focus and will close before the div gets the click event. So we need to make our links focusable by adding `tabindex="0"`  

  
Please let me know if you have any questions.

**Comment by ctwhome** [comment]
Following your comment, I was able to click on the items, and close the menu by focusing on another HTML element (with tabindex=0, otherwise it doesn't work)

```html

 <div ref="dropdown" tabindex="0">     << Added
    <div class="dropdown">
      <div tabindex="0" class="btn" @click="openMenu">
        Menu
      </div>
      <div class="shadow menu dropdown-content bg-base-100  w-72 h-72 overflow-y-auto">
        <div
          v-for="item in itmes"
          :key="i"
          tabindex="0"         << Added
          class="flex mb-2 p-2 hover:bg-gray-100 transition cursor-pointer"
          @click="$emit('on-row-selected', exchange); $refs.dropdown.focus()"    << Added
        >
          <img :src="logo">
          {{ name }}
        </div>
      </div>
    </div>
```
