### ISSUE TITLE
make radial progress direction reversable

### ISSUE THREAD

**Issue by mattbodman** [saadeghi/daisyui#793]
for a certain situations, it could be nice to have the progress bar go  anticlockwise

**Comment by saadeghi** [comment]
I don't think this is something necessary because a progress' job is to visually show a numerical value. it doesn't matter to be clockwise or anticlockwise.
However, If you really need that, you can just use CSS `rotateY` to mirror it.

Example: https://play.tailwindcss.com/VkPN2sGbmg
