### ISSUE TITLE
Indeterminate progress in firefox has no animation

### ISSUE THREAD

**Issue by saadeghi** [saadeghi/daisyui#794]
Discussion: https://github.com/saadeghi/daisyui/discussions/788 by @bayang

**Comment by sfinktah** [comment]
Is there any way to select for non-chrome browsers via CSS and show **something**, or a javascript feature based  detection as a stop-gap?

**Comment by BRAiNCHiLD95** [comment]
@saadeghi any possible solutions to this yet? It seems like this has been reported multiple times since in #846 #1330 #1608

**Comment by sfinktah** [comment]
@saadeghi What the daisyui guys do, is incredibly amazing.  To package such remarkable capabilities into such succinct pure-css modules can sometimes defy belief (e.g. fake terminal window).

They are well aware of the "problem" (lack of support in non-chrome browsers), but it is not something that can just be magically fixed.

Whilst I'm sure there is some quick fix that could be achieve with an animated gif, or somesuch - it just wouldn't be the "Zen" soilution, and it wouldn't be daisyui.

If this isn't your style, you might try https://vuetifyjs.com/en/components/progress-linear/ or one of the many other javascript libraries.

**Comment by saadeghi** [comment]
duplicate of #1330
