### ISSUE TITLE
Drawer mobile start custom breakpoint

### ISSUE THREAD

**Issue by saadeghi** [saadeghi/daisyui#797]
### Discussed in https://github.com/saadeghi/daisyui/discussions/795

<div type='discussions-op-text'>

<sup>Originally posted by **elitenoire** May 16, 2022</sup>
The ```drawer-mobile``` makes the drawer always visible from desktop (1024px breakpoint).

Is there a  way I can make the drawer visible from a smaller breakpoint for e.g. 768px breakpoint?
That is, drawer is toggleable from < 768px and always visible from >= 768px.</div>

**Comment by audunolsen** [comment]
+1

**Comment by dvlpr91** [comment]
I need it too
