### ISSUE TITLE
All inputs are hidden within an accordion

### ISSUE THREAD

**Issue by maxgfb** [saadeghi/daisyui#8]
".accordion-item input" is used to hide the check box unfortunately it also hides all inputs in the body of the accordion

Could it be changed to ".accordion-item input:first-child"

**Comment by saadeghi** [comment]
@maxgfb thanks for reporting this.  
I'll fix this today.

**Comment by saadeghi** [comment]
@maxgfb Fixed. please update to the latest version (0.11.4)

**Comment by maxgfb** [comment]
Thats done the trick thanks!
