### ISSUE TITLE
How do I use the tooltip with the rating control?

### ISSUE THREAD

**Issue by abishekrsrikaanth** [saadeghi/daisyui#800]
So here is what I tried and even though it renders correctly and the tooltip shows on each rating, the rating control stops working.

```html
<div class="rating">
    <div class="tooltip" data-tip="Unsatisfied">
         <input type="radio" name="rating-1" class="mask mask-star" />
     </div>
    <div class="tooltip" data-tip="Neutral">
         <input type="radio" name="rating-1" class="mask mask-star" />
     </div>
    <div class="tooltip" data-tip="Satisfied">
         <input type="radio" name="rating-1" class="mask mask-star" />
     </div>
    <div class="tooltip" data-tip="Very Satisfied">
         <input type="radio" name="rating-1" class="mask mask-star" />
     </div>
</div>
```

Here is an example of this issue https://jsbin.com/dihujaqimu/edit?html,output

**Comment by saadeghi** [comment]
`rating` works by checking the value of sibling `<input>` so it's not possible to put inputs on divs and make it work.  
Also, `tooltip` needs to have a wrapper div so it can show the new pseudo element on hover.  
So these two don't work together.

In this situation, I would show normal text under the rating using a grid. something like this:  
![4](https://user-images.githubusercontent.com/7342023/169174117-0f0233c7-4ae1-4f8f-9bc8-557be9edc193.png)


Let me know if you have any question
