### ISSUE TITLE
Toggle is broken on Chrome 

### ISSUE THREAD

**Issue by scottbarrow** [saadeghi/daisyui#804]
Chrome 101.0.4951.64

https://user-images.githubusercontent.com/5571736/169422211-46c97024-4759-4c99-92bc-f8fd25835be3.mov

Sorta works on safari but there's a check background image that is not aligned and not configurable with a modifier. I believe if a checkmark is require it should be specified as an additional modifier class

https://user-images.githubusercontent.com/5571736/169422220-c3ba1194-0ea5-4b0e-a949-1f16de3a3358.mov

**Comment by saadeghi** [comment]
This is not from daisyUI. There's another plugin or some external CSS applying styles to the checkbox. If you're using `@tailwindcss/forms` plugin, please disable it (because this plugin and daisyUI do the same job and you don't need them both together)

Let me know if you have any questions
