### ISSUE TITLE
Any way to change the steps width/height?

### ISSUE THREAD

**Issue by kdesimini** [saadeghi/daisyui#810]
The default size of the step circles is too big. Is there a way to change it with arbitrary values? 
![image](https://user-images.githubusercontent.com/34429274/169663620-1d9b2034-a39e-4111-8db0-70f4f5efec6e.png)

**Comment by saadeghi** [comment]
@kdesimini You can do it like this:
```html
<ul class="steps">
  <li class="step step-primary">Register</li>
  <li class="step step-primary after:!w-6 after:!h-6">Choose plan</li>
  <li class="step">Purchase</li>
  <li class="step">Receive Product</li>
</ul>
```
https://play.tailwindcss.com/CtL5XNP1xO

Let me know if you have any questions
