### ISSUE TITLE
Header added wen formatting with prettier

### ISSUE THREAD

**Issue by luizcarlos1405** [saadeghi/daisyui#811]
# What's happening
When using prettier in a project that uses `daisyui` and `prettier-plugin-tailwindcss`, the daisyui header is added to the prettier output. This ends up in the file I'm trying to format.

I'll add that the problem only happens for me when using the prettier inside `node_modules/.bin` and not when using a globally installed prettier. If I uninstall `prettier-plugin-tailwindcss` the problem stops.

This seems to be a specific bad interaction between daisyui and prettier-plugin-tailwindcss.

Prettier version 2.6.2 (both the on inside node_modules and the globally installed)
DaisyUI version 2.15.0

# What I've tried so far

* Reinstalling prettier
* Updating prettier and daisyui to latest versions

# Other considerations
It boggles me that it doesn't happen with the prettier I installed with homebrew...

This person is having the same issue:
https://github.com/tailwindlabs/tailwindcss/discussions/8380

![image](https://user-images.githubusercontent.com/15899938/169668672-fce8cd6e-399e-4a93-9c89-e7f3ca521034.png)

**Comment by saadeghi** [comment]
Thanks for reporting.  
I answered here: https://github.com/tailwindlabs/tailwindcss/discussions/8380#discussioncomment-2797350
> This is not something I can fix on my end. daisyUI just has `console.log`s in [this file](https://github.com/saadeghi/daisyui/blob/master/src/index.js) and it's meant to be printed on terminal after building the CSS, to inform the developer about the stuff daisyUI is adding. It should only be on the terminal (because it's just a console.log) and should not be added to the output file.
> 
> A workaround is to disable daisyUI logs from `tailwind.config.js`:
> 
> ```js
> module.exports = {
>   //...
>   daisyui: {
>     logs: false,
>     //...
>   },
> }
> ```

Let me know if I can help

**Comment by ofseed** [comment]
If I call prettier with `prettier -w`, the header will be shown on the terminal and the correct formatted content will be written to the file. So I think prettier can distinguish the two kinds of output (obviously console.log will not write to any file), I would like to ask, how can I call prettier to get the formatted content only? I'm using a plugin to call prettier in neovim, and I'm finding a way to make it get the correct formatted content.

**Comment by 5c077m4n** [comment]
> Thanks for reporting. I answered here: [tailwindlabs/tailwindcss#8380 (comment)](https://github.com/tailwindlabs/tailwindcss/discussions/8380#discussioncomment-2797350)
> 
> > This is not something I can fix on my end. daisyUI just has `console.log`s in [this file](https://github.com/saadeghi/daisyui/blob/master/src/index.js) and it's meant to be printed on terminal after building the CSS, to inform the developer about the stuff daisyUI is adding. It should only be on the terminal (because it's just a console.log) and should not be added to the output file.
> > A workaround is to disable daisyUI logs from `tailwind.config.js`:
> > module.exports = {
> >   //...
> >   daisyui: {
> >     logs: false,
> >     //...
> >   },
> > }
> 
> Let me know if I can help

For anyone still having this issue, the config has been moved to the main CSS file where the plugin is imported:
```css
@plugin "daisyui" {
  logs: false;
}
```
https://daisyui.com/docs/config/?lang=en#logs
