### ISSUE TITLE
Progress Bar Not Showing on Chrome

### ISSUE THREAD

**Issue by reasecret** [saadeghi/daisyui#818]
I was trying something with two browsers (Chrome 102 and Firefox 100.0.2) but I can't see progress bar on Chrome:
![chrome](https://user-images.githubusercontent.com/32717963/170779301-1c8836dc-813e-4e64-8cdc-e379fbd659de.jpg)

Same element on Firefox:
![Screenshot 2022-05-27 at 22-37-15 Laravel](https://user-images.githubusercontent.com/32717963/170779344-96ab7c1e-3d99-4d1a-aa71-ca38c18afe8e.png)

On page source, the progress bar's code is exist but not showing.

My progress bar Laravel component:
```
<div>
    <progress {{ $attributes->merge(['class' => 'progress progress-'.$type.' w-full']) }} value="{{ $value }}" max="100"></progress>
</div>
```

And I'm using like this:
```
<x-components.progress-bar type="primary" value="{{ $item->completePercent() }}" />
    <span>
        %{{ $item->completePercent() }}
    </span>
```

**Comment by saadeghi** [comment]
fixed already
