### ISSUE TITLE
Interpolated progress bar classes don't apply style

### ISSUE THREAD

**Issue by scarrick68** [saadeghi/daisyui#820]
Only some of the progress bar styles are working (chrome desktop, mobile view). *-info, *-accent, and *-error are showing correctly and primary, secondary, success, and warning all have default .progress styling. I am using light theme. This is reproduce-able by changing the classes directly in the element inspector.

I noticed that only the .progress class shows up in the css panel when inspecting an element, even when it does change color. I tried the same with a button for comparison. The .btn-warning worked and also showed up in the css panel when inspecting the element.

**Comment by scarrick68** [comment]
Ok, so I solved this one. It's an issue with Tailwind 3 JIT and interpolated styles. 

I am using string interpolation on my progress bar to set the color depending on the value like 20/21 is good in blackjack so it's *-success progress bar, but 22/21 changes the class to *-error. 

The JIT only generates styles that are used, so it doesn't know to generate the classes that were added later via interpolation. I think this is why I would see the classes correctly on my elements, but only some classes would work in the .cls css panel, if the bg-{color} had already seen somewhere else in the build. It also seemed the interpolation / rendering was racing the JIT bc results were inconsistent.

I solved it by putting the classes i needed in a hidden div as a hack. (shrug)

**Comment by saadeghi** [comment]
Yes. With Tailwind CSS yours should always use the class name as a whole string. (Not part string, part variable.  
But if you have to use half-variable class names, a cleaner way would be to have a whitelist of possible dynamic class names in .txt file and add it to `content` array in `tailwind.config.js`
