### ISSUE TITLE
Animation for steps

### ISSUE THREAD

**Issue by yassermohammad** [saadeghi/daisyui#821]
Hello and thanks for good package
I want to set fade in animation effect for any step which is active or set animation since changes any step,
How?

**Comment by yassermohammad** [comment]
One way is here:
In the tailwind.config.js:
![Screenshot from 2022-05-31 16-05-18](https://user-images.githubusercontent.com/34732441/171164233-85adfdbc-d566-463f-a3cf-09399b2a44c3.png)

and in the blade file:
![Screenshot from 2022-05-31 16-07-31](https://user-images.githubusercontent.com/34732441/171164634-8d241449-4db0-4528-a5ac-c9a6cb9910a2.png)
the highlighted section uses animation
I hope this help anybody...

**Comment by saadeghi** [comment]
This can not be a **default style** in daisyUI because anyone may or may nor want an animation and they may want a totally different animation.  
So I think the best way is to define your own animation the way you mentioned 🙌
