### ISSUE TITLE
hover effect persisting in touch devices

### ISSUE THREAD

**Issue by MrSnor** [saadeghi/daisyui#827]
Whenever buttons and such (those components having hover effects) are clicked through touch devices or even touch emulation of dev tools, the effect persists till something else is clicked (and focus is shifted I guess).

It can be easily reproduced even on the examples of daisy UI.

I think it is more of an *css* issue than daisy's. So, I am not really sure if it needs to be *fixed*, but I would very much like to know ways through which the components can be used on touch devices (or basically mobile devices) with minimal *fixes*.

One of the ways I could think of is, if the **hover** effect rules were separated from **active** rules, maybe removing **hover** rules using js for mobile/touch devices could work? But this one sounds flawed as you would have to re-write way too much :(

**Comment by gabrielesilinic** [comment]
Nope, it's actually a feature, it doesn't have to be fixed, that's what a lot of web components rely on to work on both mobile and desktop, daisyui does this as well with the dropdown component for example, also a while ago i really loved creating css only menus which relied on hover to open,  currently one example you can find it's still hosted on [gabrielesilinic.github.io](https://gabrielesilinic.github.io), my very much abandoned gitub pages website

btw javascript has an api dedicated to touch screen and maybe you could look into :focus
anyway look at pure css first then convert it back to the daisyui/tailwindcss way to get a more stylish approach out of it

**Comment by gabrielesilinic** [comment]
okay i found something, to remove hover there's this https://medium.com/@mezoistvan/finally-a-css-only-solution-to-hover-on-touchscreens-c498af39c31c

now the spec is official so you can use it, unless you want to support internet explorer

**Comment by saadeghi** [comment]
I'm not sure if there's a reason to disable hover changes on mobile. There's no mouse move event on mobile so just when we start touching an element, it gets the hover style. Otherwise there would no way to hover things on a touch device.  
For example, when we hover on daisyUI button, it slightly changes the color.  

I don't think if it's a good decision to completely disable the hover effect on mobile, just because touch devices don't have a `mouse out` event (unless we touch some other element)

I'm closing this because I don't see it as an issue but feel free to keep the conversation going.

**Comment by MrSnor** [comment]
Thanks for the input, and yes it was wasn't an issue per se, but I only wanted a way to not have persisting color change for **button**. Guess I'll go with tweaking the css to achieve that.

**Comment by danielo515** [comment]
Is this active globally or just for daisy components? I am noticing it in daisy buttons and also in other buttons on the same page that doesn't have any daisy class.
Also, is there any simple way to deactivate it globally? I don't want to remove hover states, but I don't want it to stick on touch devices either.

**Comment by andys8** [comment]
I'm encountering the same problem with an application using buttons that you can click multiple times. With react `key` the issue doesn't appear on most devices, but on mobile Safari it does. Is there a more idiomatic way to disable the hover color on mobile devices than the example above (where you rely on internal daisyui implementation)? What would be the simplest way to disable the `:hover` state for a button?

**Comment by MrSnor** [comment]
@danielo515 sticky hover effect is part of css itself and how specific browsers deal with it. For what you want, my solution might work for you. Though, you've to use it on every class that you want to be affected by your change.

**Comment by MrSnor** [comment]
@andys8 You can try removing `:hover` changes along with its respective class using javascript from the stylesheet while on a touch device.
