### ISSUE TITLE
[Feature Request/Bug report/Hacky solution] Select Multiple is not supported

### ISSUE THREAD

**Issue by gabrielesilinic** [saadeghi/daisyui#833]
Basically if i apply the select style to a select with the multiple property renders it unusable since it shrinks it to the same height to the of an ordinary select, the solution i found is to use the textbox's style to make such ui component blend in with the rest anyway and respects the size proprety, but it would be nice if the styles for the textarea could be modified to add support for such edge case

why do i need a select with multiple proprety? it's a lazy and fast way to make something which can be used to sort items with javascript, the drag and drop api is supported on PC only anyway, so why bother using it?

did i read [this?](https://github.com/saadeghi/daisyui/issues/291#issue-1046717874) yes i did, but i found a better way so i thought someone may care about that?

(also, i could try to contribute, but to be extremly honest i yet do not know how to navigate others' open source projects, and i'm decently worried about messing something up because of that)

@saadeghi  sorry for bothering you but thanks for making such amazing library/tool

**Comment by gabrielesilinic** [comment]
@saadeghi in the end i figured out how to test it even on windows, it works on the git bash, except the minimization task in the end panicking the build process works flawlessly, i think i'm going to start contributing and adding features when i'm allowed to, like btn-group-vertical is missing

**Comment by gabrielesilinic** [comment]
so basically you can assign this one to me if you want

**Comment by saadeghi** [comment]
Sure.  
I think adding:
```css
.select[multiple] {
  @apply h-auto;
}
```
would be enough. I don't think adding `.select-multiple` would be helpful.

**Comment by gabrielesilinic** [comment]
i know, i just wasn't sure about it, i'm going to try to edit my own pull request accordingly

**Comment by gabrielesilinic** [comment]
fixed the weird thing i added, just because... stupid decision and forced consistency, the pull request is now ready and decent
