### ISSUE TITLE
Any CSS classname for input file

### ISSUE THREAD

**Issue by eroist** [saadeghi/daisyui#834]
I'm using daisyui for frontend css framework and it is great!
but I can't find out any css classname for input file.
please help me.

**Comment by saadeghi** [comment]
There's none ...yet.  
I will add it soon but for now, you can do this:  
https://play.tailwindcss.com/JXzVqKAGqZ?file=css
```html
<input class="file-input" type="file">
```
```css
.file-input::file-selector-button{
  @apply btn;
}
```

**Comment by barryodev** [comment]
With a secondary button this doesn't work for the hover background colour. I can get it working using a hard coded hex value but wondering if there's another way to do it.

```
.file-input::file-selector-button{
    @apply btn;
    @apply btn-secondary;
    @apply hover:bg-[#d49b0d];
}
```

**Comment by saadeghi** [comment]
This is tricky because this usage of `@apply` already generates some unwanted selectors and it's just a temporary fix.  
But don't worry, file selector style will be added in next minor version (`2.25.0`) soon.

**Comment by gonzabrusco** [comment]
Any news about this feature? Thanks for your great library!!
