### ISSUE TITLE
Daisyui is recognized by tailwind but not apply in pages (Electron app)

### ISSUE THREAD

**Issue by KrishenK0** [saadeghi/daisyui#835]
Hi,

I followed all installation steps for tailwindcss and daisyui. But, the implementation does not work fine, the classes are not working, but if I change the theme it will be applied.

There is my repo, where my application is https://github.com/KrishenK0/playzik

From the logs, daisyui is included
```
🌼 daisyUI components 2.15.2  https://github.com/saadeghi/daisyui
  ✔︎ Including:  base, components, themes[29], utilities
```

However, in my page **./views/index.ejs** I put the daisyui classe btn, and some tailwind classes. But my custom class **test** works.
```html
<button class="btn tw-w-64 tw-rounded-full">Button</button>
```
The button doesn't change.
![image](https://user-images.githubusercontent.com/90158435/172028561-91de2df2-15b1-46cb-8922-881d4f9e5f7f.png)

tailwind.config.js

```js
const colors = require('tailwindcss/colors')

module.exports = {
  mode: 'jit',
  prefix: 'tw-',
  content: [
    './src/**/*.{html, ejs}',
    './public/js/*.js'
  ],
  darkMode: 'media', // or 'class' or false
  theme: {
    extend: {
      colors: {
        green: colors.emerald,
        yellow: colors.amber,
        purple: colors.violet,
      }
    }
  },
  variants: {},
  plugins: [
    require("@tailwindcss/typography"),
    require("autoprefixer"),
    require("daisyui"),
  ],
  daisyui: {
    styled: true,
    themes: true,
    base: true,
    utils: true,
    logs: true,
    rtl: false,
    prefix: "",
    darkTheme: "black",
  },
}
```

Thank you for your awesome work, I will appricate any help.

(Sorry for my bad English _baguette_)

**Comment by saadeghi** [comment]
Your template files are in `/views` but your `content` array in `tailwind.config.js` is pointing to `/src`  
That might be the issue.

**Comment by KrishenK0** [comment]
Oh that true! However, the problem remains :(
My `tailwind.config.js` :
```js
module.exports = {
  mode: 'jit',
  prefix: 'tw-',
  content: [
    './views/**/*.{html, ejs}',
    './public/js/*.js'
  ],
  ...
}
```
And the result
![image](https://user-images.githubusercontent.com/90158435/172049196-5688b3a2-e6eb-4547-bbf8-ea9b947b8182.png)

*I also update my repo https://github.com/KrishenK0/playzik

**Comment by KrishenK0** [comment]
Ok, after multiple tries, and little research on Google, I realize that my express was bad configured. And the prefix 'tw-' cause some problem, it works without, I let like this.

For people who have the same issue, there is my config.

`tailwind.config.js`
```js
module.exports = {
  mode: 'jit',
  content: [
    './views/*.ejs',
    './public/**/*.{js, css, html}'
  ],
  theme: {
    ...
  },
  variants: {},
  plugins: [
    require("@tailwindcss/typography"),
    require("autoprefixer"),
    require("daisyui"),
  ],
  daisyui: {
    ...
    darkTheme: "black",
  },
}
```

`server.js` (only the view engine *that was the cause*)
```js
// view engine
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

app.use(cors());
app.use(express.static(path.join(__dirname, 'public')));
```

`index.ejs`
```ejs
<!DOCTYPE html>
<html>
<head>
  ...
  <link rel="stylesheet" href="/css/style.css" />
</head>
<body>
  ...
  <button class="btn w-64 rounded-full">Button</button>
  ...
</body>
</html>
```

Tree folder : 
```
│   package-lock.json
│   package.json
│   postcss.config.js
│   server.js
│   tailwind.config.js
│
├───public
│   ├───css
│   │       style.css
│
└───views
    │   error.ejs
    │   index.ejs
    │
    └───css
            tailwind.css
```
