### ISSUE TITLE
card-side only on sm:, normal on larger breakpoints?

### ISSUE THREAD

**Issue by divan** [saadeghi/daisyui#836]
Hi,

I'm trying to make card use card-side layout on sm: breakpoint, but be a normal (vertical) card on larger (md:).

I'm trying to do

```html
<div class="card-side md:card-normal ...">
```

but it doesn't seem to work. Am I doing something wrong?

```html
    <div class="card card-side md:card-normal">
      <img src="https://picsum.photos/200/300" />
      <div class="card-body">body</div>
    </div>
```

**Comment by saadeghi** [comment]
`card-normal` and `card-compact` are about paddings as mention on [docs](https://daisyui.com/components/card/)  
Not to be confused with `card-side` which changes the   
>![1](https://user-images.githubusercontent.com/7342023/184460559-d16d27b0-069f-4b37-89f6-e160ad90929a.png)

Currently there's no class name to "reset" the `card-side` style for a specific resolution but I will consider this on the next update.

For now, you can use `sm:flex-col` utility class to put the image on top again for a specific resolution.  
https://play.tailwindcss.com/spI1xkJgFX
```html
<div class="card m-20 card-side sm:flex-col">
  <img src="https://picsum.photos/200/300" />
  <div class="card-body bg-base-200">body</div>
</div>
```

**Comment by perelin** [comment]
Also stumbled over this. Maybe a hint in the documentation would already be enough. I try to make a PR later.

**Comment by saadeghi** [comment]
I know the name `normal` can be confusing.  
I'm planning to replace that with `xs`, `sm`, `md`, `lg` names (similar to other components).  
This will be done in the next major version because it's a breaking change.
