### ISSUE TITLE
[Bug]: Can't apply `rounded` to `input-group` class

### ISSUE THREAD

**Issue by LWJerri** [saadeghi/daisyui#837]
Hello! I can't apply `rounded` class.

Minimal code for reproducing problem:
```svelte
        <div class="input-group rounded"> <!-- I try add rounded here, but it's doesen't work -->
          <input
            type="text"
            class="input-ghost input input-sm input-bordered w-full" <!-- Not work if I set it here -->
            disabled
          />
          <input
            type="number"
            class="input input-sm input-ghost w-32" <!-- or here :( -->
            placeholder="MAX 75 GB"
            disabled
          />
        </div>
```

![image](https://user-images.githubusercontent.com/50290430/172121102-389b3071-be5a-4302-9474-702cf9ec159c.png)

**Comment by Gypsy-147** [comment]
me too

**Comment by saadeghi** [comment]
`input-group`'s job is:
- put items in a row
- add **left** border radius to the first item
- add **right** border radius to the last item
- and keep all other border radiuses `0`
so all items inside sit next to each other while the first and last one have border radius.

The value of border radius can be modified using `--rounded-btn` CSS variable like this:
```html
<div class="input-group [--rounded-btn:3rem]">
```
https://play.tailwindcss.com/y2cD0pCwEl

Let me know if you have any questions
