### ISSUE TITLE
How to build dynamic theme from json data return by rest api

### ISSUE THREAD

**Issue by workingxx92** [saadeghi/daisyui#841]

**Comment by saadeghi** [comment]
Take a look at this file: https://unpkg.com/browse/daisyui@2.15.2/dist/themes.css  
As you can see, these are all the built-in themes.  
Each theme just applies a few CSS variables and the color values are `HSL` values
Use [this table](https://daisyui.com/docs/colors/) as color reference.  

So you can basically apply a new theme using JS, by changing the CSS variable
```css
:root {
  --p: 326 100% 74%;
  --s: 265 89% 78%;
  /* ...other values */
}

Let me know if you have any questions

**Comment by Meadowsys** [comment]
Not sure if it was added later, but for reference for people (like me) finding this issue later, there is this docs page: <https://daisyui.com/docs/colors/#-2>

Under the section titled "List of all daisyUI color names", rightmost column, look for lines such as `CSS variable: hsl(var(--p))`
