### ISSUE TITLE
vscode Intellisense plugin

### ISSUE THREAD

**Issue by valmormn** [saadeghi/daisyui#842]
I'm a noob who loves daisyui and I've been looking without success for a daisyui vscode intellisense plugin. Does anyone have any idea how this can be achieved?

**Comment by saadeghi** [comment]
Just use Tailwind CSS intellisense plugin:  
https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss  
It will include Tailwind CSS class names and every aplugins installed (including daisyUI)

Let me know if you have any questions

**Comment by daveteu** [comment]
@saadeghi how do you get the colors to show? Can u share your plugin settings?

<img width="548" alt="image" src="https://user-images.githubusercontent.com/18649392/193003802-8a324e5e-dfb3-471d-bcbf-ca26b04b36cd.png">
bg-base vs bg-red
