### ISSUE TITLE
Feature Request: btn-group-vertical (modifier)

### ISSUE THREAD

**Issue by gabrielesilinic** [saadeghi/daisyui#847]
## What is it?
so, basically i can add this one myself, the name is pretty self-explanatory, i'm going to look how btn-group is made and how input-group-vertical and create this new modifier accordingly, the look it's going to be the same as btn-group but rotated by 90 degrees more or less (i actually already looked into those modifiers/components)

## Docs needed?
should i commit the documentation edits as well or i let the mantainer do it? (the only mantainer being saadeghi as far as i know)
do you want separate pull requests? (one being for the modifier and the other for the documentation)

## Why do i need a vertical button group?
controls, that's it, controlling other stuff via javascript functions on click, also this feature would make daisyui more consistent since we already have input-group-vertical

**Comment by gabrielesilinic** [comment]
i noticed that btn-group-sm -md etc are missing, i was thinking of implementing them by applying their corrisponding btn- size (es btn-sm, btn-md etc), i do it another way or i just don't?

also there's a weird bug going on not my fault, i'll make a separate issue for that and fix it later, it doesn't break anything to be honest, just a visual bug going on with the hover state, it doesn't affect on click

**Comment by saadeghi** [comment]
Why do we need sizing (like `btn-group-sm` or `btn-group-lg`)? 🤔

**Comment by gabrielesilinic** [comment]
@saadeghi honestly i asked because the input group does have sizing, so i wondered if i should add it to btn-group as well, to me it doesn't make much difference since i got twig (template engine) which can add the size of buttons once then creates more with the same time look, it's not needed, it's just a nice thing to add, though i don't know if btn-sm etc can be inherited, honestly, just say yes or no, i don't care at this point about this specific detail

**Comment by saadeghi** [comment]
There's no need for sizing for the group.

**Comment by gabrielesilinic** [comment]
@saadeghi the pull request is ready
