### ISSUE TITLE
Class "sr-only" within footer breaks Drawer component

### ISSUE THREAD

**Issue by Chrysippus** [saadeghi/daisyui#851]
I'm not sure exactly why this happens, but it seems to have to do with the "sr-only" class using absolute positioning at the bottom of the screen. 

If a page has a navigation drawer (using the "drawer" class) that wraps the entire content of the page (as it should, so that the overlay and side-panel properly block scrolling) _and_ a `<span class="sr-only">` inside `<footer class="footer">` it causes a second scroll-bar to appear and, sometimes, a large amount of whitespace below the footer. It may also cause this problem in drawers that don't wrap the entire page, but I'm not certain of this.

The "sr-only" class doesn't seem to cause this problem in other locations, including at the bottom of the screen (if _not_ inside `<footer class="footer">`).

The scrollbar issue goes away if a "relative" class is added after the "sr-only" class, so it probably is just the absolute positioning causing the problem. Of course, that positioning is needed for the class to make any sense. Adding an "h-0" class to override the 1px height also solves the problem, but I'm not sure if that breaks the screen-reader functionality.

Here's a Tailwind Play example that shows the doubled scrollbars and extra whitespace: https://play.tailwindcss.com/aD83nXMfJF

**Comment by saadeghi** [comment]
As you can see on all the examples [here](https://daisyui.com/components/footer/) the direct children of `class="footer"` must be a simple `div` because those divs create the columns.

You can use `sr-only` inside the divs.

Let me know if you have any questions.

**Comment by Chrysippus** [comment]
Thanks. I missed that. Just a suggestion: for people like me who sometimes forget basic css stuff, if I didn't miss that you did this already, it might be helpful to make the div requirement explicit somewhere (maybe as a comment on the examples?) rather than just implied.
