### ISSUE TITLE
component styled & unstyled: is merged together?

### ISSUE THREAD

**Issue by skmohammadi** [saadeghi/daisyui#856]
Hi dear Pouya.

Please look at following image:
![image](https://user-images.githubusercontent.com/12100097/173312531-457bc028-d901-422d-9bca-ffc58134bc3d.png)

It seems Alert`s style is formed by two parts: **styled** & **unstyled**

_Components > styled > alert:_
```
.alert {
  @apply bg-base-200 p-4 rounded-box;
}
```
_Components > unstyled > alert:_
```
.alert {
  @apply flex w-full flex-col items-center justify-between gap-4 space-y-2 md:flex-row md:space-y-0;
  > :where(*) {
    @apply flex items-center gap-2;
  }
}
```

Where did this merge occur?

I've only seen **styled** or **unstyled** files injecting into components when I look at the TW plugin function `mainFunction`.

**Comment by saadeghi** [comment]
This is up to the CSS processor.  
- diasyUI as a plugin for Tailwind CSS only sends styles to Tailwind CSS and Tailwind CSS processes them as it needs.
- daisyUI [CDN file](https://unpkg.com/daisyui@2.22.1/dist/full.css) is being processed by [Parcel-CSS](https://github.com/parcel-bundler/parcel-css)

Let me know if you have any questions
