### ISSUE TITLE
Dividers doesn't working

### ISSUE THREAD

**Issue by Cokaps** [saadeghi/daisyui#86]
Hi there, I've tried to set the dividers (Intel Cosumers and Intel HEDT) but as the picture below, it doesn't work.

![image](https://user-images.githubusercontent.com/64778285/122433235-3aacb680-cfc0-11eb-8dd9-eed4442625f2.png)

My code can be found on [Github](https://github.com/Cokaps/GenZOC/blob/master/src/index.html#L100-L133)

**Comment by saadeghi** [comment]
@Cokaps everything's fine?

**Comment by Cokaps** [comment]
Yeah, it works without changing anything, I used to tried to reopen the PowerShell for several times.
