### ISSUE TITLE
React component not working with daisyui

### ISSUE THREAD

**Issue by alexribeirodesa** [saadeghi/daisyui#864]
here a very simple react+nextjs component to draw the avatar using the code from sample with no modification:

export function Avatar(props) {

	return(
		<div className="avatar">
			<div className="w-10 mask mask-squircle">
				<img src="https://api.lorem.space/image/face?hash=47449" />
			</div>
		</div>
	)
}

the result is this:
![image](https://user-images.githubusercontent.com/2172704/173757935-d556f3f6-b97f-418a-add7-22fcb2e7f067.png)

I'm doing something wrong?? I miss something?? 

thx

**Comment by MehdiHali** [comment]
the solution worked very well for me ! thanks.
i hope if you can add that somewhere in the Docs so that others not repeat the same mistake.

**Comment by saadeghi** [comment]
Well... this is not about daisyUI. It's a necessary Tailwind CSS config and it's already documented on the official Tailwind CSS website.
