### ISSUE TITLE
Tooltip not showing

### ISSUE THREAD

**Issue by JohannGit** [saadeghi/daisyui#867]
Hi. I just copied the code from documentation but tooltip component is not showing in the page. (hidden ?)

<img width="1660" alt="image" src="https://user-images.githubusercontent.com/43565480/174121427-5697ea3b-02c8-4170-9946-2f5f0ab649b6.png">

<img width="573" alt="Capture d’écran 2022-06-16 à 17 35 59" src="https://user-images.githubusercontent.com/43565480/174121490-b530b17b-cd3f-41cf-9d3f-7bbc33732574.png">

Build is OK 
<img width="427" alt="image" src="https://user-images.githubusercontent.com/43565480/174121634-ad2ef039-d51a-4088-abc3-5527dc127500.png">

**Comment by saadeghi** [comment]
Can you share a small repo so I can reproduce the issue?

**Comment by JohannGit** [comment]
Another project member had added the tw-elements library which was causing interference. Sorry for the issue, and thank you for the good work. Have a nice day.
