### ISSUE TITLE
overriding button padding

### ISSUE THREAD

**Issue by khoivan88** [saadeghi/daisyui#87]
Hi,

First of all, thank you for this very useful library. I have been using this for one of my websites and it works great. Today, I was upgrading from 0.20.1 to 1.3.7 and noticed that something broke. Specifically, I have a button with this class: `...btn btn-primary btn-lg px-1...` . In the earlier version, I use the `px-1` to control the width of the button and it worked great. However, switching to the newer daisyui, it seems that `px-1` is overridden by the `btn-lg` class. I believe this is a bug but I'm not 100% sure. Would you have any pointer for me?

Thank you very much!

**Comment by saadeghi** [comment]
@khoivan88 Thanks for reporting this. fixed on latest version `1.3.8`  
demo: https://play.tailwindcss.com/f91t1expmq

**Comment by khoivan88** [comment]
Thank you very very much! 😄  👍
