### ISSUE TITLE
DaisyUI styles not showing up on Brave browser

### ISSUE THREAD

**Issue by Q-T5** [saadeghi/daisyui#889]
Hi y'all. I have about a month's experience with Tailwind and wanted to try out this Library along with it. I followed the instructions for installing it into a tailwind project I already have. Here is my tailwind.config.js file:
```
module.exports = {
  // content: [],
  theme: {
    extend: {
      colors: {
        primary: '#FF6363',
        secondary: {
          100: '#E2E2D5', 
          200: '#888883',
        }
      },

      fontFamily: {
        body: ['Nunito']
      }
    },
  },
  plugins: [require("daisyui")],

  daisyui: {
    styled: true,
    themes: true,
    base: true,
    utils: true,
    prefix: "daisy-"
  }
}
```
The file shows an error that I cant find a fix for on Google, whenever I hover over `require("daisyui")`. The error says:
```
module "/home/bikathi_martin/Bikathi Martin/HTML&CSS/ninjafood/node_modules/daisyui/src/index"
Could not find a declaration file for module 'daisyui'. '/home/bikathi_martin/Bikathi Martin/HTML&CSS/ninjafood/node_modules/daisyui/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/daisyui` if it exists or add a new declaration (.d.ts) file containing `declare module 'daisyui';`ts(7016)
```
I tried running the `npm i --save-dev @types/daisyui` but it produced an error:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fdaisyui - Not found
npm ERR! 404 
npm ERR! 404  '@types/daisyui@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bikathi_martin/.npm/_logs/2022-06-24T07_43_07_518Z-debug-0.log
```
So I created a `global.d.ts` file at the root of my project  and added the line `declare module 'daisyui` and this time the error went away. But when I try to create a sample component and view it in Brave, nothing special happens. I had tried creating a progress bar like this:
`<progress class="daisy-progress w-56" value="20" max="100"></progress>` (I added the prefix `daisy-` to my config) but it shows up like a with Tailwind's default styles (wish I could show an image but I don't know how to.) Basically the components are not showing up as expected rather they are showing up with Tailwind's default. How do I fix this? I can't find a solution over on Google.

**Comment by saadeghi** [comment]
Hey,

`declaration` error is from Typescript and the solution is the one you mentioned.

But components not having styles is a different issue.  
It might be an issue with the `content` config: make sure the path to all your template files are specified on `tailwind.config.js`

If that doesn't fix the problem, please share a small repo so I can reproduce the issue.

**Comment by Q-T5** [comment]
I tried adding the correct paths into the `content[]` section like this `content: ["./public/**/*.{html,js}"]` but it still does not show up when I test it under the `index.html` file in the `./public` folder. Here is a link to the repo: [Link to GitRepo](https://github.com/Q-T5/diasyui-test).
