### ISSUE TITLE
Question: Can I align card image overlay to be centered?

### ISSUE THREAD

**Issue by Dzoukr** [saadeghi/daisyui#891]
When I have a really thin card with image overlay, the image is not centered:

![image](https://user-images.githubusercontent.com/851307/175551753-f1882f98-a855-43c5-a796-926d65e3e275.png)

Is there any way how to make the image be vertically centered? 🤔 

Thanks for any hint!

**Comment by saadeghi** [comment]
You can add `place-content-center` to `card`  
And add `self-center` to `card-body`:  
https://play.tailwindcss.com/A0XapdKwRT
```html
<div class="card w-96 image-full h-52 place-content-center">
  <figure>
    <img src="https://placeimg.com/500/1000/arch" />
  </figure>
  <div class="card-body self-center">
    <h2 class="card-title">Shoes!</h2>
    <p>If a dog chews shoes whose shoes does he choose?</p>
    <div class="justify-end card-actions">
      <button class="btn btn-primary">Buy Now</button>
    </div>
  </div>
</div>
```

**Comment by Dzoukr** [comment]
Thanks a lot, sir!!! 🙏♥️
