### ISSUE TITLE
input-group corners not rounded after Tailwind 3.0.23

### ISSUE THREAD

**Issue by spencermize** [saadeghi/daisyui#894]
Hi! 

It appears that a way that Tailwind handles `!important` generation has caused `input-group` corners to have `border-radius: 0px !important` applied after the `3.0.23` version of Tailwind. Reverting this change: https://github.com/tailwindlabs/tailwindcss/pull/7664/files#diff-1d8d199860deae6bdf03efc5c6e7f8515de4dfb42e254cca0ee2b664d15b5e66R101 shows the proper behavior. I think the Tailwind change is actually correct, as it should _reduce_ the number of false positives - yet here we are with a new false positive!

It seems that the relevant line(s) are here, yet I don't see anything fishy.

https://github.com/saadeghi/daisyui/blob/77fd3ab729e6074dae5e2f20068f5615f4ef6907/src/components/unstyled/input.css#L7

For me, a reproduction is simply:
```
<label class="input-group">
	<span>label</span>
	<input type="text" />
</label>
```

The generated styles in 3.0.23:
```
.input-group > *, 
  .input-group > .input {
  border-radius: 0px;
}
.\!input-group > *, 
  .\!input-group > .\!input {
  border-radius: 0px !important;
}
```

And the generated styles in 3.0.24:
```
.input-group > *, 
  .input-group > .input {
  border-radius: 0px;
}
.input-group > *,  (this is the incorrect line!)
  .input-group > .\!input {
  border-radius: 0px !important;
}
```
The styles in Chrome:
![image](https://user-images.githubusercontent.com/936433/175762777-63c9a2c5-7702-4865-811f-cf5e7d0c64a7.png)

Let me know if I can provide more detail - thanks!

**Comment by francoism90** [comment]
Reporting the same bug here:
![image](https://user-images.githubusercontent.com/5028905/177040084-5f830fb5-0675-41b2-97af-df913a96b7d2.png)

**Comment by demetrius-mp** [comment]
are there any workarounds for this?

**Comment by long2ice** [comment]
Same there

**Comment by demetrius-mp** [comment]
thanks for sharing!

**Comment by Mashiane** [comment]
I started working with DaisyUI during the weekend, I have just picked this also.

![image](https://user-images.githubusercontent.com/5799306/189627101-18f1d8c1-4c2a-4438-b6a1-38e1448579dc.png)

In my use case I have a "hidden" hint for both as I want to toggle this depending on whether its specified or not.

I guess for now I can just leave them blank.

**Comment by vhollo** [comment]
When checkboxes precede buttons,
_:first-child_ and _:last-child_ should be replaced with **:first-of-type** and **:last-of-type**

**Comment by saadeghi** [comment]
My friends, I've been trying to reproduce this in many ways but I can't see the issue.  
This is my code and it works as expected
```html
<label class="input-group m-4">
  <span>label</span>
  <input type="text" class="input input-bordered" />
</label>
```
The only way I could break the radius was adding an extra element at he start or end of group:
```html
<label class="input-group m-4">
  <div class="hidden">is there an invisible element here like this one?</div>
  <span>label</span>
  <input type="text" class="input input-bordered" />
</label>
```
Example: https://play.tailwindcss.com/qPsib3e9EG

This is how it works: 
1. remove border radius of all children
2. add border radius to the first item at the right
3. add border radius to the last item at the left

Please give me a Tailwind Play example or a sample repo if it's not working for you

**Comment by Mashiane** [comment]
Hi.

I have reproduced this based on my use case, this is the planned target, https://play.tailwindcss.com/d2zHjLGOVD

with functionality to show a prefix, prepend-dicon, suffix, append-icon on demand at run-time. The prepend-icon & prefix are mutually exclusive, same as append-icon and suffix, but, if I dont want any of them, it should be possible.

The reproduction here is with all these items hidden, https://play.tailwindcss.com/9hPHLH5PWo

My aim is just a single component that I can control what to show / how depending on the "hidden" class.

I hope it makes sense.

**Comment by saadeghi** [comment]
@Mashiane Can you conditionally render the optional elements using your JS library of your component props instead of adding/removing `hidden` class? Because I think that's the correct the way to do. If the element shouldn't be visible at some point, we should ideally remove it from the DOM and it's easy to do with all modern frameworks.

**Comment by ymongo** [comment]
Hi there, same problem here: I have an input-group whose corners aren't rounded, css in dev console gives: 

```.input-group > *, .input-group > .\!input {
    border-radius: 0px !important;
    border-top-left-radius: 0px !important;
    border-top-right-radius: 0px !important;
    border-bottom-right-radius: 0px !important;
    border-bottom-left-radius: 0px !important;```
    
    Added classes as proposed by @spencermize  [here](https://github.com/saadeghi/daisyui/issues/894#issuecomment-1208203928) into my global.css, fixed

**Comment by jelledv49** [comment]
> for my particular usage, i added this to my app's `.postcss` file.
> 
> ```
> /* Fixes https://github.com/saadeghi/daisyui/issues/894 */
> .input-group :first-child {
>   @apply !rounded-tl-lg !rounded-bl-lg;
> }
> 
> .input-group :last-child {
>   @apply !rounded-tr-lg !rounded-br-lg;
> }
> ```
> 
> It's not as robust as what Daisy should be creating, but again - it worked for my purposes.

Facing the same issue. This workaround works!

**Comment by saadeghi** [comment]
What do you think about this idea: https://github.com/saadeghi/daisyui/discussions/1572

**Comment by Koaieus** [comment]
> What do you think about this idea: #1572

Lovely idea, sounds like a good solution for all elements that aren't direct children.

Would solve a lot of issues with e.g. input tags which require a wrapper so that other elements can use absolute positioning, as the inputs have no slots and thus *need* to be wrapped
