### ISSUE TITLE
Feature dropdown drawer

### ISSUE THREAD

**Issue by arthurvanl** [saadeghi/daisyui#896]
Add an drawer dropdown component where it expand the parent and add the elements underneath the parent

**Comment by saadeghi** [comment]
Can you share a screenshot of something similar so I see what exactly you mean?

**Comment by arthurvanl** [comment]
https://user-images.githubusercontent.com/20114845/175826592-e864aa16-cd5c-402e-be53-9b01a8ff769b.mp4

Something like this. This is created with alpine because i didnt knew how to do it otherwise.

**Comment by saadeghi** [comment]
I recommend to keep using JS for this menu but if you want to use css only, this is what you want:  
https://play.tailwindcss.com/XiJotgrSQP
```html
<div class="drawer">
  <input id="my-drawer" type="checkbox" class="drawer-toggle" />
  <div class="drawer-content">
    <!-- Page content here -->
    <label for="my-drawer" class="btn btn-primary drawer-button">Open drawer</label>
  </div>
  <div class="drawer-side">
    <label for="my-drawer" class="drawer-overlay"></label>
    <ul class="menu w-80 overflow-y-auto bg-base-100 p-4 text-base-content">
      <!-- Sidebar content here -->
      <li><a>Sidebar Item 1</a></li>
      <li><a>Sidebar Item 2</a></li>
      <div tabindex="0" class="collapse collapse-arrow">
        <input type="checkbox" />
        <div class="collapse-title font-medium">Parent</div>
        <ul class="collapse-content menu">
          <li><a>Child Item 1</a></li>
          <li><a>Child Item 2</a></li>
        </ul>
      </div>
      <li><a>Sidebar Item 3</a></li>
    </ul>
  </div>
</div>
```

**Comment by Mashiane** [comment]
Thank you so much!!

**Comment by gonzabrusco** [comment]
Hi @saadeghi . If you have too many items in the drawer, how do you avoid that second column they create?

**Comment by saadeghi** [comment]
@gonzabrusco remove the `overflow-y-auto` from `menu`.  
https://play.tailwindcss.com/7oU2d6CFA8

**Comment by gonzabrusco** [comment]
@saadeghi worked perfectly. Thank you!!
