### ISSUE TITLE
Feature: Toasts?

### ISSUE THREAD

**Issue by GamingInfinite** [saadeghi/daisyui#898]
Are there plans for adding popup toasts at all?  Not at all required for what I'm doing but it'd just be convenient.

**Comment by cryptodeal** [comment]
Recently switched to using DaisyUI with SvelteKit and was looking to replace a svelte toast library with a custom store/DaisyUI implementation of toast notifications. I've forked the repository and built a working component consistent with your vision of the toast component & accompanying wrapper by largely imitating the styles of the Alert component.

If you can assign this to me @saadeghi,I'll gladly submit a PR with the changes as I'd likely need help with the animations, to clean up styles.

You're welcome to test by testing the passwordless auth on the (WIP) basketball stats platform I'm working on using dummy emails (just has to have valid email format; use @example.com domain for testing); but should receive success toast notification that's been implemented w the styles from forked daisyUI.

**Comment by saadeghi** [comment]
@cryptodeal awesome! PRs are welcome of course.

**Comment by saadeghi** [comment]
Added in daisyUI `2.19.0` with this PR https://github.com/saadeghi/daisyui/pull/909 🎉
