### ISSUE TITLE
Adding Modal Component

### ISSUE THREAD

**Issue by ronyfhebrian** [saadeghi/daisyui#9]
Hi @saadeghi, love your work on daisyui!

I haven't found the Modal Component, yet.
Is it on purpose since for example it'll be provided by react modal or will you add it later?

Thank you for your great work btw.

**Comment by saadeghi** [comment]
Thanks @ronyfhebrian  
There's no modal component yet, but I will add it until next week.

**Comment by ronyfhebrian** [comment]
Thank you very much!
Looking forward to it. 🙏🏾

**Comment by saadeghi** [comment]
@ronyfhebrian Modal component added (98e6fe046a36ee9e944263d4f0e913fbbf865ff2)
demo: https://daisy.js.org/components/modal/
codepen: https://codepen.io/saadeghi/pen/ZEBvMey?editors=1000

please update to latest version (0.11.5)
