### ISSUE TITLE
Question: How to convert rem into px

### ISSUE THREAD

**Issue by liaoliao666** [saadeghi/daisyui#900]
e.g. 
```css
/* raw */
font-size: .875rem;

/* converted */
font-size: 14px;
```

**Comment by saadeghi** [comment]
I'm not sure how is this question is related to daisyUI or Tailwind CSS, but 1 rem equals 16px by default and we use rem instead of pixel because it's better for accessibility. If user changes their browser's default font size, all elements will resize accordingly.

Let me know if you have any questions

**Comment by liaoliao666** [comment]
@saadeghi 
Currently I write a chrome extension. But Daisyui is weird when the website's font-size is not my expect.

**Comment by saadeghi** [comment]
can you set a `px` font size for the root element of extension?

```css
:root{
  font-size: 14px;
}
```

**Comment by liaoliao666** [comment]
@saadeghi 
I think i should not cahnge any css of the website

**Comment by saadeghi** [comment]
I meant the extension, not the current page. I assumed your extension has HTML elements that are styled using daisyUI.

I still don't know what exactly is the issue here.

**Comment by liaoliao666** [comment]
emmmm
cuz I'll inject my content-script in any website. so that's the current page.
and the `:root` can only change `<html />` styles and not the root styles of my script.

**Comment by saadeghi** [comment]
And how is the result font size "weird" using `rem`?  
Can you explain more about the issue? Or add some screenshots?

**Comment by liaoliao666** [comment]
@saadeghi 
![image](https://user-images.githubusercontent.com/26479949/175820593-abcb5bdb-f058-4db1-8f56-5ec4d2b610c4.png)
![c0jKovFObT](https://user-images.githubusercontent.com/26479949/175820615-a3c5619a-eb51-4dab-8ba2-ab0076db7dc0.png)
u can see the font size is diffrence between the two websites

**Comment by saadeghi** [comment]
Can you use Tailwind CSS arbitrary utility classes for the container element of your plugin?  
Something like this https://tailwindcss.com/docs/font-size#arbitrary-values

**Comment by liaoliao666** [comment]
@saadeghi 
of course I can, but it's just a workaround and annoying when I using per class of daisyui
is there any way to configure it like tailwind that does, like below
```js
theme: {
    fontSize: {
      xs: "12px",
      sm: "14px",
      base: "16px",
      lg: "18px",
      xl: "20px",
      "2xl": "24px",
      "3xl": "30px",
      "4xl": "36px",
      "5xl": "48px",
      "6xl": "60px",
      "7xl": "72px"
    },
    spacing: {
      px: "1px",
      0: "0",
      0.5: "2px",
      1: "4px",
      1.5: "6px",
      2: "8px",
      2.5: "10px",
      3: "12px",
      3.5: "14px",
      4: "16px",
      5: "20px",
      6: "24px",
      7: "28px",
      8: "32px",
      9: "36px",
      10: "40px",
      11: "44px",
      12: "48px",
      14: "56px",
      16: "64px",
      20: "80px",
      24: "96px",
      28: "112px",
      32: "128px",
      36: "144px",
      40: "160px",
      44: "176px",
      48: "192px",
      52: "208px",
      56: "224px",
      60: "240px",
      64: "256px",
      72: "288px",
      80: "320px",
      96: "384px"
    },
    extend: {
      lineHeight: {
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        7: "28px",
        8: "32px",
        9: "36px",
        10: "40px"
      }
    }
  }
```

**Comment by saadeghi** [comment]
I think that should work too.

**Comment by wuyue92tree** [comment]
I found this, hope can help u. @liaoliao666 

https://github.com/TheDutchCoder/postcss-rem-to-px
