### ISSUE TITLE
Click outside modal to close it

### ISSUE THREAD

**Issue by ctwhome** [saadeghi/daisyui#91]
Hi! is it possible to be able to close the modal when clicking outside (in the black area?) with only css?

**Comment by saadeghi** [comment]
@ctwhome It is possible using labels, because checkbox controls the modal and you can check/uncheck a checkbox using any label:
https://play.tailwindcss.com/JYBmEBLBin

**Comment by ctwhome** [comment]
Very clever, thank you for the fast response. Another good example for the toolkit!
