### ISSUE TITLE
Disable colors but keep the styles?

### ISSUE THREAD

**Issue by mamcx** [saadeghi/daisyui#910]
Currently using `styled: false` not just disable the colors, but also the padding and other subtle design choices. Is possible to keep them and just change colors?

**Comment by saadeghi** [comment]
`styled: false` disables every design decisions and only keeps the structure.  

However, you can set it to `true` and change the colors using [CSS variables](https://daisyui.com/docs/colors/) to change the colors on a theme or you can use Tailwind's color utility classes (like `bg-red-600`) to change colors on a specific element.
