### ISSUE TITLE
Rendering issues on firefox

### ISSUE THREAD

**Issue by KaruroChori** [saadeghi/daisyui#919]
I am not really sure whether this is a problem specific of daisyui or of tailwind itself, but there are some serious problems while rendering on firefox against webkit.
Visible artifacts with aliasing in rounded corners, but even worse with text alignment.
It is subtle, just a fraction at 200%, but enough to feel like badges are unbalanced.
For example, this is in firefox 101 at 200%:
![image](https://user-images.githubusercontent.com/9377545/177035980-f6f5ea95-f209-470a-aa43-cfb841699ccf.png)
and here a random version of chromium:
![image](https://user-images.githubusercontent.com/9377545/177035993-0f109030-ce50-4451-9665-405a66d357e2.png)

At 100% scale it is even worse due to rounding while rendering the pixels.
Firefox 100%
![image](https://user-images.githubusercontent.com/9377545/177036145-066c1522-d824-4bdb-9878-6b5c75e7c667.png)
Chromium
![image](https://user-images.githubusercontent.com/9377545/177036162-ce011b89-619f-4e13-aec7-93dcabc5a505.png)

**Comment by saadeghi** [comment]
This might be an issue from your browser preferences or your OS.  
There are no special font style or any render tricks used on daisyUI. It's just a normal border radius on badges and daisyUI uses default system fonts (by default)

I'm closing this because this is not an issue from daisyUI but feel free to continue the conversation.

**Comment by KaruroChori** [comment]
@saadeghi It is not a problem related to the OS, nor any reasonable browser setting I set custom.
This is the pair of renders obtained on a windows machine (the previous ones were on a ubuntu distro) with a freshly installed firefox 102 and a more recent version of chromium
Firefox:
![image](https://user-images.githubusercontent.com/9377545/177037463-a150fba4-9efc-4bf8-9992-37beafb1262b.png)
Chromium:
![image](https://user-images.githubusercontent.com/9377545/177037481-3811960f-e909-4430-9f8c-200a7eb77c76.png)
The glitches are virtually the same. The firefox rendering of that css has text misaligned in the vertical position in either case.
