### ISSUE TITLE
How to reset Button size to Normal the easy way?

### ISSUE THREAD

**Issue by chasoft** [saadeghi/daisyui#925]
Hello,

The sample for button size in the docs as below

```
<button class="btn btn-lg">Large</button>
<button class="btn">Normal</button>
<button class="btn btn-sm">Small</button>
<button class="btn btn-xs">Tiny</button>
```

But how to reset the button to normal size? Tailwind need a class to reset!

My `use case` is small button in small screen size and bigger button in bigger screen, and in the middle, I want it has normal size.

```
class="btn btn-sm md: ??   lg:btn-lg"
```

Thank you!

**Comment by saadeghi** [comment]
Use `btn-md` class.  
It's documented on the table of class names [here](https://daisyui.com/components/button/)

Let me know if you have any questions
