### ISSUE TITLE
Button Loading Does Not Show Spinner on Input Element

### ISSUE THREAD

**Issue by appindus-kanderson** [saadeghi/daisyui#931]
The loading indicator on a `button` or `div` shows as expected.
The loading indicator on an `input` does not show as expected.

```html
<!-- shows spinner -->
<div class="btn btn-primary loading">save</div>

<!-- does not show spinner -->
<input type="submit" class="btn btn-primary loading" value="save">
```

![image](https://user-images.githubusercontent.com/42982427/177799560-19d90784-f406-4406-b980-f8ae8b332aff.png)

**Comment by appindus-kanderson** [comment]
Possibly not possible to accommodate given self closing tags aren't container elements and therefor `::after` and `::before` don't apply to them.

https://stackoverflow.com/a/47632195/5537062

**Comment by saadeghi** [comment]
Self closing `<input />` tag can not have pseudo elements and the spinner is a pseudo element.  
So there's nothing we can do about this limitation...
