### ISSUE TITLE
Set height to screen height minus navbar

### ISSUE THREAD

**Issue by Garito** [saadeghi/daisyui#937]
How can we achieve this?
I've noticed that navbar has min-height set to 4rem
Perhaps a variable? height: calc(100vh - (--navbar-height + (--navbar-padding * 2)));

**Comment by saadeghi** [comment]
You can do this:  
```html
<div class="drawer h-[calc(100vh-4rem)]">
```
https://play.tailwindcss.com/Tfo32ZdxKd

`4rem` is min-height of drawer but it has no `max-height`. If you're putting larger elements inside `navbar`, consider using your custom height size.

**Comment by Garito** [comment]
Have you read my issue?

**Comment by saadeghi** [comment]
Yes. If you want screen height minus navbar height, use `h-[calc(100vh-4rem)]` class name.  
What's the problem?

**Comment by Garito** [comment]
I already point to your "solution"
I has asking if you can use a variable for the navbar height

**Comment by saadeghi** [comment]
I don't think using a CSS variable here adds any value or makes any improvement. 
Using a CSS variable is a waste when you can override the height value with one CSS property.

**Comment by Garito** [comment]
Why are you using the other variables then?

**Comment by saadeghi** [comment]
I don't know why are you talking so aggressive in a GitHub issue.  

CSS variables are used when one value must control multiple variables or when there's no easier way to override a property.

**Comment by Garito** [comment]
Aggressive?
You don't read my issue, then you close the issue with a good solution and I am the aggressive?
I'm asking to add a line of code and change another to allow to customize the property
Perhaps we should stop this discussion and I should look for a better library and problem solved

**Comment by saadeghi** [comment]
First of all, your issue is not an issue. So it gets closed.  
You're just suggesting to add a CSS variable for no reason.  
Second, there is no problem here to solve. You already know the solution. And I already told you the solution so I don't know how else I can help you.

**Comment by Garito** [comment]
Short minded
See ya

**Comment by kkharji** [comment]
Wow, @saadeghi sorry you had to deal with such a toxic interaction. I deeply appreciate your work bro. Thank you

**Comment by tansanDOTeth** [comment]
> Aggressive? You don't read my issue, then you close the issue with a good solution and I am the aggressive? I'm asking to add a line of code and change another to allow to customize the property Perhaps we should stop this discussion and I should look for a better library and problem solved

Rage quit

**Comment by abrahamgreyson** [comment]
If I don't click on his profile, I could easily imagine he's Chinese, just like me 🤣
