### ISSUE TITLE
[BUG]: DaisyUI and state of react

### ISSUE THREAD

**Issue by AbhijithGanesh** [saadeghi/daisyui#938]
I currently use DaisyUI with TailwindCSS and React. I am experiencing the following error:
DaisyUI is somehow tampering with state of React:
- It doesn't maintain the state and/or doesn't handle click events well.

You can view it here: https://dok-community-tracker.vercel.app

**Comment by saadeghi** [comment]
I can't help you without seeing the source code. Please provide a sample repo and specify what exactly is the issue.
And please remember that daisyUI is only a CSS framework and has nothing to do with JS state values.

Let me know if you have any questions.
