### ISSUE TITLE
Responsive menu NOT disappearing

### ISSUE THREAD

**Issue by ABIOLI-COM** [saadeghi/daisyui#944]
It's really an edge case, but in the page

https://daisyui.com/components/navbar/

at the example

responsive (dropdown menu on small screen, center menu on large screen)

if the page is narrow, you open the hamburger menu, and ALSO open the submenu ('parent'), the whole menu doesn't disappear when enlarging the page (only the hamburger menu disappears, and the centered menu comes up): so you see both (same) menus on screen. This doesn't happen if you DON'T open the submenu.

**Comment by saadeghi** [comment]
You can fix this by adding `lg:hidden` class to the `menu`  

But I don't see this as a bug. 
- Any dropdown menu opens when it's focued and it closes when it loses focus and the dropdown button hides on large screens
- It's not a normal behavior to open a menu on a mobile screen and then suddenly scale up the browser to use the desktop menus.

**Comment by ABIOLI-COM** [comment]
Sorry, but if you have TWO (different) copies of the SAME menu on the screen, at a given time, for me it's always a bug. Period.
Then, I accept that you confirm what I said, that we are talking about an edge case. :-)
