### ISSUE TITLE
How to make the modal component on the right?

### ISSUE THREAD

**Issue by workingon92** [saadeghi/daisyui#95]
How to make the modal component on the right?
<img width="1118" alt="Screen Shot 2021-06-28 at 6 37 47 AM" src="https://user-images.githubusercontent.com/86577210/123562880-99054080-d7db-11eb-9a5f-aa2a368e38fe.png">

**Comment by saadeghi** [comment]
@workingon92 You can do this by adding a `justify-end` class to modal (to send it to right)  
and you can expand the height by adding `h-screen` to modal-box.  
Example: https://play.tailwindcss.com/9VIa7IYlHj

**Comment by workingon92** [comment]
@saadeghi 
Thank you for your reply. 
How to  transition from right to left when modal show

**Comment by saadeghi** [comment]
@workingon92 using `justify-start` instead of `justify-end` will put the modal to left.
