### ISSUE TITLE
tooltip making not preffered paddings

### ISSUE THREAD

**Issue by restareaByWeezy** [saadeghi/daisyui#959]
Having issue when I use Tooltip component in my project.

The small gap between 2 divs appear when I add tooltip className to bottom div.
Is there any way that I can get rid off that padding? 

<img width="341" alt="image" src="https://user-images.githubusercontent.com/64529155/179692780-48828310-a236-4d1f-8df9-49e19a023928.png">

the following code represents 2 divs with tooltip

```js
    <div className='w-[120px]'>
      <div className='w-full h-[130px]'>
        <div
          className='bg-primaryLight'
          style={{ height: `${100 - percent}%` }}
        />
        <div
          data-tip='hello'
          className='tooltip relative w-full bg-primaryHeavy2'
          style={{ height: `${percent}%` }}
        >
          <p className='text-center text-white text-sm'>{percent}%</p>
        </div>
      </div>
    </div>
```

**Comment by saadeghi** [comment]
`tooltip` is `inline-block` by default and being `inline-block` causes that white space.  
You can add `block` class to fix that
```html
<div class="tooltip block">
```

**Comment by restareaByWeezy** [comment]
@saadeghi oh I see, Thank you for the answer!
