### ISSUE TITLE
[carousel ] how to active item and how to build carousel like this below?

### ISSUE THREAD

**Issue by workingon92** [saadeghi/daisyui#96]
<img width="914" alt="Screen Shot 2021-06-28 at 11 02 46 AM" src="https://user-images.githubusercontent.com/86577210/123578673-84876f00-d800-11eb-90a2-c771d4d14ca2.png">

**Comment by saadeghi** [comment]
@workingon92 I think it's better to handle this kind of functionality using javascript.  
It's not impossible to do it using pure CSS but we will end up with a complex and large amount of HTML/CSS.  
Without JavaScript, the best we can do is using `<a>` links to target each item with `id`:
```html
<div class="w-64 carousel rounded-box">
  <div class="w-full carousel-item" id="one">
    <img src="https://picsum.photos/id/500/256/144" class="w-full">
  </div> 
  <div class="w-full carousel-item" id="two">
    <img src="https://picsum.photos/id/501/256/144" class="w-full">
  </div>
</div>
```
```html
<a class="btn" href="#one">1</a>
<a class="btn" href="#two">2</a>
```

**Comment by dessalines** [comment]
Is there any way to set the active / current slide? What if I'd like the slide to start on the 2nd one?
