### ISSUE TITLE
Vertical Toggle switch

### ISSUE THREAD

**Issue by Rar9** [saadeghi/daisyui#962]
A vertical toggle switch would be nice to add to https://daisyui.com/components/toggle

So we could use something like **toggle-vertical**

**Comment by saadeghi** [comment]
I don't have any plans for adding `toggle-vertical` because I don't think there's a place where the being vertical adds any value or fixes any design problem.  
However, you can always use utility classes to rotate things:  
https://play.tailwindcss.com/y5550WzJID
```html
<input type="checkbox" class="toggle rotate-90 m-20" checked />
```

**Comment by Rar9** [comment]
Ok and how to ad tooltips that are then rotated?

**Comment by saadeghi** [comment]
To rotate a tooltip, put it in a `div` or `span` and add `rotate-90` class.

**Comment by Rar9** [comment]
Two issues  https://play.tailwindcss.com/FP9BkgJKWd

Moon SVG not clickable after rotating
Tooltip still not rotated dont know where to put SPAN

**Comment by saadeghi** [comment]
SVG is not clickable (and should not be clickable). The clickable element is the invisible `<input>` but when we have SVGs before it, SVGs go on top of the invisible `<input>`. To fix this, I added `z-[2]` (`z-index:2`)  to the `<input>`  
And tooltip is rotated already. I see no problem. I just added more margin so you can see it.

Example: https://play.tailwindcss.com/aylUjsA70e

Let me know if you have any questions.
