### ISSUE TITLE
daisyui components do not respect `darkMode: 'class'` configuration

### ISSUE THREAD

**Issue by luizkowalski** [saadeghi/daisyui#963]
Hey 👋🏻 

First of all, thanks for this project, awesome work!

The issue I'm seeing is that I'm trying to create a dark mode toggle by using `darkMode: 'class'` and I noticed that the components I built (custom inputs) on top of DaisyUI respect the config but regular DaisyUI components, like cards, don't:

Card with custom input and default `card` class:
<img width="386" alt="image" src="https://user-images.githubusercontent.com/112706/180281169-cbb3de94-e7d6-4cce-9f41-77e3d107e045.png">

👆🏻 Here, the `darkMode` is set to `class`, meaning it should not look into the system's dark mode but rely on the class being present on the HTML on not

👇🏻 Now with `dark` set on the HTML tag:

<img width="457" alt="image" src="https://user-images.githubusercontent.com/112706/180281685-2bdee540-367c-42cb-ac57-e8314c80b429.png">

the custom component respects it

Is there any workaround?

Thanks a lot!

**Comment by SpaceCowboyMax** [comment]
looks like daisy ui uses different aprouch for darkMode setup, maby this discussion can help [#640 ](https://github.com/saadeghi/daisyui/discussions/640#discussioncomment-2424834)

**Comment by luizkowalski** [comment]
yup, that answers it, thanks a lot @SpaceCowboyMax
