### ISSUE TITLE
Failed to resolve component

### ISSUE THREAD

**Issue by MotionPhix** [saadeghi/daisyui#97]
In vue 3, I am getting 

> [Vue warn]: Failed to resolve component: Badge

Any way to resolve this issue, because daisyui components don't get displayed correctly on the page

**Comment by saadeghi** [comment]
@MotionPhix I need more details.  
Can you create a small repo so I can reproduce this issue?  

There's an example with the latest version of Vue + Vite and everything looks fine: https://github.com/saadeghi/daisyui/tree/master/examples/vue-vite

**Comment by saadeghi** [comment]
@MotionPhix I'm closing this for now. It seems like a problem with your build config (not with daisyUI).  
You can take a look at the example build [here](https://github.com/saadeghi/daisyui/tree/master/examples/vue-vite). 
Feel free to continue the conversation with more info if the problem still exists.
