### ISSUE TITLE
Focused input outline border on WebKit based browser is not rounded

### ISSUE THREAD

**Issue by zer09** [saadeghi/daisyui#978]
When focused the focused border outline is not rounded.

Tested only on Epiphany, Midor and Tauri

Here is the result if the input is focused.
```html
<input type="text" placeholder="Type here" class="w-full max-w-xs input input-bordered" />
```
![Screenshot_20220727_175035](https://user-images.githubusercontent.com/780780/181219887-e35438c7-5d3e-4eff-a79c-19e96765dbbe.png)

**Comment by saadeghi** [comment]
That's an issue from Safari. `outline` in Safari does not respect border-radius.  
I can't do anything about it. I just hope Safari fix this in future versions.

**Comment by saadeghi** [comment]
> @saadeghi why not using `box-shadow` instead of `outline`?

Because if we use box shadow, developers can not add their own box shadow.  
Using box shadow instead of outline was just an old workaround from the years when we couldn't style the outline, we used to hide the outline and then simulate the outline using box shadow.
